# Notebook 02 — Source Field Quality Profile

## Analytical question

How is each field in the source `raceform.db` table actually stored, and what observable quality issues must be understood before cleaning, parsing, filtering, or target-schema design begins?

## Purpose

This notebook profiles the 37 source fields as stored.

It will produce:

- a source data dictionary;
- a field-level quality register;
- evidence on SQLite storage classes;
- counts of blanks, nulls, placeholders and special codes;
- observed numeric and date-like ranges where appropriate;
- representative values and frequency distributions;
- identification of fields requiring separate racing-domain investigation.

## Source

Database: `data/raw/form_2015-present/form_2015-present/raceform.db`

Source table: `data`

The first physical row is an imported header row and must be excluded from field-quality calculations without modifying the raw database.

## Methodological boundaries

This notebook will not:

- modify the raw database;
- replace or impute missing values;
- standardise text;
- parse composite fields into new fields;
- remove records;
- assign permanent identifiers;
- design the analytical target schema;
- assume undocumented racing-domain meanings;
- treat unusual values as errors without supporting evidence.

Observed evidence and later transformation decisions will remain separate.

## Profiling sequence

Fields will be examined in coherent groups:

1. identifier and race-description fields;
2. runner identity and demographics;
3. result and finishing fields;
4. odds, ratings, weight and time fields;
5. pedigree and ownership fields;
6. free-text comments.

The first group is:

- `date`
- `course`
- `race_id`
- `off`
- `race_name`
- `type`
- `class`
- `pattern`
- `rating_band`
- `age_band`
- `sex_rest`
- `dist`
- `going`
- `ran`

In [1]:
from pathlib import Path
import sqlite3

import pandas as pd

# Resolve the repository root whether Jupyter was started from the project root
# or from inside the notebooks directory.
current_directory = Path.cwd().resolve()

if (current_directory / "data").exists():
    project_root = current_directory
elif (current_directory.parent / "data").exists():
    project_root = current_directory.parent
else:
    raise FileNotFoundError(
        "Could not locate the project root containing the data directory."
    )

source_database = (
    project_root
    / "data"
    / "raw"
    / "form_2015-present"
    / "form_2015-present"
    / "raceform.db"
)

if not source_database.is_file():
    raise FileNotFoundError(f"Source database not found: {source_database}")

# Open the immutable source database in read-only mode.
connection = sqlite3.connect(f"file:{source_database}?mode=ro", uri=True)

print(f"Project root:    {project_root}")
print(f"Source database: {source_database}")
print("Connection mode: read-only")

Project root:    /home/rob/Documents/inside-rails-horse-racing
Source database: /home/rob/Documents/inside-rails-horse-racing/data/raw/form_2015-present/form_2015-present/raceform.db
Connection mode: read-only

In [2]:
# Read the declared SQLite column definitions without loading the full table.
schema = pd.read_sql_query(
    'PRAGMA table_info("data")',
    connection,
)

# Keep the most useful schema evidence for this notebook.
source_data_dictionary = schema[
    ["cid", "name", "type", "notnull", "dflt_value", "pk"]
].copy()

source_data_dictionary = source_data_dictionary.rename(
    columns={
        "cid": "column_position",
        "name": "field_name",
        "type": "declared_sqlite_type",
        "notnull": "declared_not_null",
        "dflt_value": "declared_default",
        "pk": "declared_primary_key",
    }
)

# SQLite uses zero-based internal column positions.
source_data_dictionary["column_position"] += 1

print(f"Declared field count: {len(source_data_dictionary):,}")

display(source_data_dictionary)

Declared field count: 37

,column_position,field_name,declared_sqlite_type,declared_not_null,declared_default,declared_primary_key
0,1,date,NUMERIC,0,None,0
1,2,course,TEXT,0,None,0
2,3,race_id,INTEGER,0,None,0
3,4,off,TEXT,0,None,0
4,5,race_name,TEXT,0,None,0
5,6,type,TEXT,0,None,0
6,7,class,TEXT,0,None,0
7,8,pattern,TEXT,0,None,0
8,9,rating_band,TEXT,0,None,0
9,10,age_band,TEXT,0,None,0
10,11,sex_rest,TEXT,0,None,0
11,12,dist,TEXT,0,None,0
12,13,going,TEXT,0,None,0
13,14,ran,INTEGER,0,None,0
14,15,num,INTEGER,0,None,0
15,16,pos,INTEGER,0,None,0
16,17,draw,INTEGER,0,None,0
17,18,ovr_btn,NUMERIC,0,None,0
18,19,btn,NUMERIC,0,None,0
19,20,horse,TEXT,0,None,0
20,21,age,INTEGER,0,None,0
21,22,sex,TEXT,0,None,0
22,23,wgt,TEXT,0,None,0
23,24,hg,TEXT,0,None,0
24,25,time,TEXT,0,None,0
25,26,sp,TEXT,0,None,0
26,27,jockey,TEXT,0,None,0
27,28,trainer,TEXT,0,None,0
28,29,prize,INTEGER,0,None,0
29,30,or,INTEGER,0,None,0
30,31,rpr,INTEGER,0,None,0
31,32,ts,INTEGER,0,None,0
32,33,sire,TEXT,0,None,0
33,34,dam,TEXT,0,None,0
34,35,damsire,TEXT,0,None,0
35,36,owner,TEXT,0,None,0
36,37,comment,TEXT,0,None,0

In [3]:
# Inspect the first few physical rows, including SQLite's internal rowid.
identifier_race_fields = [
    "date",
    "course",
    "race_id",
    "off",
    "race_name",
    "type",
    "class",
    "pattern",
    "rating_band",
    "age_band",
    "sex_rest",
    "dist",
    "going",
    "ran",
]

quoted_fields = ", ".join(f'"{field}"' for field in identifier_race_fields)

first_rows = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        {quoted_fields}
    FROM data
    ORDER BY rowid
    LIMIT 5
    """,
    connection,
)

display(first_rows)

,source_rowid,date,course,race_id,off,race_name,type,class,pattern,rating_band,age_band,sex_rest,dist,going,ran
0,1,date,course,race_id,off,race_name,type,class,pattern,rating_band,age_band,sex_rest,dist,going,ran
1,2,2015-01-01,Catterick,615704,12:30,Happy New Year Novices Hurdle,Hurdle,Class 4,,,4yo+,,2m3½f,Good To Soft,10
2,3,2015-01-01,Tramore (IRE),616859,12:35,2015 Waterford & Tramore Racecourse Supporters...,Hurdle,,,80-109,4yo+,,2m,Heavy,8
3,4,2015-01-01,Tramore (IRE),616860,1:05,Padraig Curran - South East Cleaners Maiden Hu...,Hurdle,,,,5yo+,,2m5f,Heavy,8
4,5,2015-01-01,Tramore (IRE),616860,1:05,Padraig Curran - South East Cleaners Maiden Hu...,Hurdle,,,,5yo+,,2m5f,Heavy,8

In [4]:
# Verify that the first physical row reproduces every declared field name.
all_source_fields = source_data_dictionary["field_name"].tolist()

header_row = pd.read_sql_query(
    """
    SELECT *
    FROM data
    WHERE rowid = 1
    """,
    connection,
).iloc[0]

header_check = pd.DataFrame(
    {
        "field_name": all_source_fields,
        "stored_header_value": [
            str(header_row[field]) for field in all_source_fields
        ],
    }
)

header_check["matches_field_name"] = (
    header_check["stored_header_value"]
    == header_check["field_name"]
)

matching_fields = int(header_check["matches_field_name"].sum())

print(
    f"Header-name matches: {matching_fields:,} "
    f"of {len(all_source_fields):,}"
)
print(f"All 37 fields match: {header_check['matches_field_name'].all()}")

# This predicate will be included explicitly in profiling queries.
# It excludes the imported header without altering the raw source.
DATA_ROW_PREDICATE = "rowid <> 1"

display(header_check)

Header-name matches: 37 of 37
All 37 fields match: True

     field_name stored_header_value  matches_field_name
0          date                date                True
1        course              course                True
2       race_id             race_id                True
3           off                 off                True
4     race_name           race_name                True
5          type                type                True
6         class               class                True
7       pattern             pattern                True
8   rating_band         rating_band                True
9      age_band            age_band                True
10     sex_rest            sex_rest                True
11         dist                dist                True
12        going               going                True
13          ran                 ran                True
14          num                 num                True
15          pos                 pos                True
16         draw                draw                True
17      ovr_btn             ovr_btn                True
18          btn                 btn                True
19        horse               horse                True
20          age                 age                True
21          sex                 sex                True
22          wgt                 wgt                True
23           hg                  hg                True
24         time                time                True
25           sp                  sp                True
26       jockey              jockey                True
27      trainer             trainer                True
28        prize               prize                True
29           or                  or                True
30          rpr                 rpr                True
31           ts                  ts                True
32         sire                sire                True
33          dam                 dam                True
34      damsire             damsire                True
35        owner               owner                True
36      comment             comment                True

In [5]:
# Build a compact field-level quality summary for the first field group.
#
# No values are cleaned or converted here. All counts describe the source
# exactly as SQLite stores it, excluding only the confirmed header row.

profile_rows = []

for field in identifier_race_fields:
    quoted_field = f'"{field}"'

    query = f"""
    SELECT
        COUNT(*) AS total_rows,
        SUM(CASE WHEN {quoted_field} IS NULL THEN 1 ELSE 0 END) AS null_count,
        SUM(
            CASE
                WHEN typeof({quoted_field}) = 'text'
                 AND length(trim({quoted_field})) = 0
                THEN 1 ELSE 0
            END
        ) AS blank_text_count,
        COUNT(DISTINCT {quoted_field}) AS distinct_non_null_values,
        SUM(CASE WHEN typeof({quoted_field}) = 'null' THEN 1 ELSE 0 END)
            AS storage_null,
        SUM(CASE WHEN typeof({quoted_field}) = 'integer' THEN 1 ELSE 0 END)
            AS storage_integer,
        SUM(CASE WHEN typeof({quoted_field}) = 'real' THEN 1 ELSE 0 END)
            AS storage_real,
        SUM(CASE WHEN typeof({quoted_field}) = 'text' THEN 1 ELSE 0 END)
            AS storage_text,
        SUM(CASE WHEN typeof({quoted_field}) = 'blob' THEN 1 ELSE 0 END)
            AS storage_blob
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """

    result = pd.read_sql_query(query, connection).iloc[0].to_dict()

    declared_type = source_data_dictionary.loc[
        source_data_dictionary["field_name"] == field,
        "declared_sqlite_type",
    ].iloc[0]

    result["field_name"] = field
    result["declared_sqlite_type"] = declared_type

    profile_rows.append(result)

identifier_race_quality = pd.DataFrame(profile_rows)

identifier_race_quality = identifier_race_quality[
    [
        "field_name",
        "declared_sqlite_type",
        "total_rows",
        "null_count",
        "blank_text_count",
        "distinct_non_null_values",
        "storage_null",
        "storage_integer",
        "storage_real",
        "storage_text",
        "storage_blob",
    ]
]

display(identifier_race_quality)

,field_name,declared_sqlite_type,total_rows,null_count,blank_text_count,distinct_non_null_values,storage_null,storage_integer,storage_real,storage_text,storage_blob
0,date,NUMERIC,1851285,0,0,4130,0,0,0,1851285,0
1,course,TEXT,1851285,0,0,528,0,0,0,1851285,0
2,race_id,INTEGER,1851285,0,0,188782,0,1851285,0,0,0
3,off,TEXT,1851285,0,0,1380,0,0,0,1851285,0
4,race_name,TEXT,1851285,0,0,108632,0,0,0,1851285,0
5,type,TEXT,1851285,0,0,4,0,0,0,1851285,0
6,class,TEXT,1851285,0,768544,8,0,0,0,1851285,0
7,pattern,TEXT,1851285,0,1587927,11,0,0,0,1851285,0
8,rating_band,TEXT,1851285,0,1081546,384,0,0,0,1851285,0
9,age_band,TEXT,1851285,0,159,28,0,0,0,1851285,0
10,sex_rest,TEXT,1851285,0,1612425,6,0,0,0,1851285,0
11,dist,TEXT,1851285,0,0,63,0,0,0,1851285,0
12,going,TEXT,1851285,0,45,22,0,0,0,1851285,0
13,ran,INTEGER,1851285,0,0,37,0,1851285,0,0,0

In [6]:
# Add interpretable rates without changing any source values.
identifier_race_quality_rates = identifier_race_quality.copy()

identifier_race_quality_rates["null_pct"] = (
    identifier_race_quality_rates["null_count"]
    / identifier_race_quality_rates["total_rows"]
    * 100
)

identifier_race_quality_rates["blank_text_pct"] = (
    identifier_race_quality_rates["blank_text_count"]
    / identifier_race_quality_rates["total_rows"]
    * 100
)

identifier_race_quality_rates["populated_rows"] = (
    identifier_race_quality_rates["total_rows"]
    - identifier_race_quality_rates["null_count"]
    - identifier_race_quality_rates["blank_text_count"]
)

identifier_race_quality_rates["populated_pct"] = (
    identifier_race_quality_rates["populated_rows"]
    / identifier_race_quality_rates["total_rows"]
    * 100
)

rate_columns = [
    "field_name",
    "declared_sqlite_type",
    "total_rows",
    "null_count",
    "null_pct",
    "blank_text_count",
    "blank_text_pct",
    "populated_rows",
    "populated_pct",
    "distinct_non_null_values",
]

display(
    identifier_race_quality_rates[rate_columns].round(
        {
            "null_pct": 4,
            "blank_text_pct": 4,
            "populated_pct": 4,
        }
    )
)

,field_name,declared_sqlite_type,total_rows,null_count,null_pct,blank_text_count,blank_text_pct,populated_rows,populated_pct,distinct_non_null_values
0,date,NUMERIC,1851285,0,0.0,0,0.0000,1851285,100.0000,4130
1,course,TEXT,1851285,0,0.0,0,0.0000,1851285,100.0000,528
2,race_id,INTEGER,1851285,0,0.0,0,0.0000,1851285,100.0000,188782
3,off,TEXT,1851285,0,0.0,0,0.0000,1851285,100.0000,1380
4,race_name,TEXT,1851285,0,0.0,0,0.0000,1851285,100.0000,108632
5,type,TEXT,1851285,0,0.0,0,0.0000,1851285,100.0000,4
6,class,TEXT,1851285,0,0.0,768544,41.5141,1082741,58.4859,8
7,pattern,TEXT,1851285,0,0.0,1587927,85.7743,263358,14.2257,11
8,rating_band,TEXT,1851285,0,0.0,1081546,58.4214,769739,41.5786,384
9,age_band,TEXT,1851285,0,0.0,159,0.0086,1851126,99.9914,28
10,sex_rest,TEXT,1851285,0,0.0,1612425,87.0976,238860,12.9024,6
11,dist,TEXT,1851285,0,0.0,0,0.0000,1851285,100.0000,63
12,going,TEXT,1851285,0,0.0,45,0.0024,1851240,99.9976,22
13,ran,INTEGER,1851285,0,0.0,0,0.0000,1851285,100.0000,37

In [7]:
# Show complete value distributions for fields with relatively few distinct values.
low_cardinality_fields = [
    "type",
    "class",
    "pattern",
    "age_band",
    "sex_rest",
    "going",
]

distribution_frames = []

for field in low_cardinality_fields:
    quoted_field = f'"{field}"'

    distribution = pd.read_sql_query(
        f"""
        SELECT
            {quoted_field} AS stored_value,
            COUNT(*) AS row_count
        FROM data
        WHERE {DATA_ROW_PREDICATE}
        GROUP BY {quoted_field}
        ORDER BY row_count DESC, stored_value
        """,
        connection,
    )

    distribution["field_name"] = field
    distribution["row_pct"] = (
        distribution["row_count"]
        / distribution["row_count"].sum()
        * 100
    )

    distribution_frames.append(distribution)

low_cardinality_distributions = pd.concat(
    distribution_frames,
    ignore_index=True,
)

for field in low_cardinality_fields:
    print(f"\n{field.upper()}")
    display(
        low_cardinality_distributions.loc[
            low_cardinality_distributions["field_name"] == field,
            ["stored_value", "row_count", "row_pct"],
        ].round({"row_pct": 4})
    )

TYPE

  stored_value  row_count  row_pct
0         Flat    1268229  68.5053
1       Hurdle     358441  19.3617
2        Chase     179645   9.7038
3      NH Flat      44970   2.4291

CLASS

   stored_value  row_count  row_pct
4                   768544  41.5141
5       Class 5     312687  16.8903
6       Class 4     307371  16.6031
7       Class 6     191263  10.3314
8       Class 3     124168   6.7071
9       Class 2      81783   4.4176
10      Class 1      63008   3.4035
11      Class 7       2461   0.1329

PATTERN

   stored_value  row_count  row_pct
12                 1587927  85.7743
13       Listed      56854   3.0711
14      Group 3      43015   2.3235
15      Grade 3      42321   2.2860
16      Group 1      36346   1.9633
17      Grade 1      28045   1.5149
18      Grade 2      26988   1.4578
19      Group 2      23256   1.2562
20      Grade B       4360   0.2355
21      Grade A       1817   0.0981
22      Grade C        356   0.0192

AGE_BAND

   stored_value  row_count  row_pct
23         4yo+     606576  32.7651
24         3yo+     556237  30.0460
25          3yo     237914  12.8513
26          2yo     179439   9.6927
27         5yo+     145227   7.8447
28          4yo      44999   2.4307
29        4-6yo      24236   1.3091
30        4-7yo      10220   0.5520
31         2yo+      10198   0.5509
32        3-5yo       8450   0.4564
33        4-5yo       8057   0.4352
34        3-4yo       4646   0.2510
35         6yo+       3904   0.2109
36        5-7yo       3175   0.1715
37          5yo       3171   0.1713
38        10yo+       2061   0.1113
39        2-3yo        944   0.0510
40         7yo+        415   0.0224
41        5-6yo        357   0.0193
42        3-6yo        248   0.0134
43         8yo+        206   0.0111
44                     159   0.0086
45        5-8yo        159   0.0086
46        4-8yo         95   0.0051
47        6-7yo         87   0.0047
48         9yo+         76   0.0041
49        3-7yo         17   0.0009
50          6yo         12   0.0006

SEX_REST

   stored_value  row_count  row_pct
51                 1612425  87.0976
52            F     123667   6.6801
53            M      52478   2.8347
54        F & M      37354   2.0177
55        C & G      25292   1.3662
56        C & F         69   0.0037

GOING

        stored_value  row_count  row_pct
57              Good     499160  26.9629
58          Standard     343818  18.5719
59              Soft     211462  11.4224
60      Good To Soft     184351   9.9580
61      Good To Firm     177363   9.5805
62             Heavy     116237   6.2787
63  Standard To Slow      62870   3.3960
64          Yielding      48747   2.6331
65              Fast      45728   2.4701
66         Very Soft      43035   2.3246
67  Good To Yielding      38947   2.1038
68              Firm      31471   1.7000
69     Soft To Heavy      20601   1.1128
70  Yielding To Soft      19076   1.0304
71              Slow       3580   0.1934
72            Sloppy       2602   0.1406
73             Muddy       1754   0.0947
74            Frozen        341   0.0184
75  Standard To Fast         65   0.0035
76                           45   0.0024
77           Holding         28   0.0015
78              Hard          4   0.0002

In [8]:
# Examine the source date field as stored text.
#
# The checks below test observed string structure only. They do not yet
# convert the field into a Python or SQLite date type.

date_profile = pd.read_sql_query(
    f"""
    SELECT
        MIN(date) AS minimum_stored_value,
        MAX(date) AS maximum_stored_value,
        MIN(length(date)) AS minimum_length,
        MAX(length(date)) AS maximum_length,
        SUM(
            CASE
                WHEN date GLOB
                    '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'
                 AND length(date) = 10
                THEN 1 ELSE 0
            END
        ) AS yyyy_mm_dd_shape_count,
        SUM(
            CASE
                WHEN NOT (
                    date GLOB
                        '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'
                    AND length(date) = 10
                )
                THEN 1 ELSE 0
            END
        ) AS other_shape_count,
        COUNT(DISTINCT substr(date, 1, 4)) AS distinct_year_strings
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

date_year_distribution = pd.read_sql_query(
    f"""
    SELECT
        substr(date, 1, 4) AS stored_year,
        COUNT(*) AS row_count,
        COUNT(DISTINCT date) AS distinct_dates
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY substr(date, 1, 4)
    ORDER BY stored_year
    """,
    connection,
)

display(date_profile)
display(date_year_distribution)

,minimum_stored_value,maximum_stored_value,minimum_length,maximum_length,yyyy_mm_dd_shape_count,other_shape_count,distinct_year_strings
0,2015-01-01,2026-05-27,10,10,1851285,0,12

   stored_year  row_count  distinct_dates
0         2015     157683             365
1         2016     157938             366
2         2017     167494             365
3         2018     172047             363
4         2019     173039             365
5         2020     121683             335
6         2021     175552             365
7         2022     167479             365
8         2023     156075             365
9         2024     169702             365
10        2025     167664             364
11        2026      64929             147

In [9]:
# Profile the scheduled off-time field exactly as stored.
#
# The source appears to contain both zero-padded and non-zero-padded times,
# so the checks distinguish common H:MM and HH:MM string shapes.

off_profile = pd.read_sql_query(
    f"""
    SELECT
        MIN(length(off)) AS minimum_length,
        MAX(length(off)) AS maximum_length,
        SUM(
            CASE
                WHEN off GLOB '[0-9]:[0-9][0-9]'
                 AND length(off) = 4
                THEN 1 ELSE 0
            END
        ) AS h_mm_shape_count,
        SUM(
            CASE
                WHEN off GLOB '[0-9][0-9]:[0-9][0-9]'
                 AND length(off) = 5
                THEN 1 ELSE 0
            END
        ) AS hh_mm_shape_count,
        SUM(
            CASE
                WHEN NOT (
                    (
                        off GLOB '[0-9]:[0-9][0-9]'
                        AND length(off) = 4
                    )
                    OR
                    (
                        off GLOB '[0-9][0-9]:[0-9][0-9]'
                        AND length(off) = 5
                    )
                )
                THEN 1 ELSE 0
            END
        ) AS other_shape_count,
        COUNT(DISTINCT off) AS distinct_stored_values
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

off_length_distribution = pd.read_sql_query(
    f"""
    SELECT
        length(off) AS stored_length,
        COUNT(*) AS row_count,
        COUNT(DISTINCT off) AS distinct_values
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY length(off)
    ORDER BY stored_length
    """,
    connection,
)

off_examples = pd.read_sql_query(
    f"""
    SELECT
        off AS stored_value,
        COUNT(*) AS row_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY off
    ORDER BY row_count DESC, off
    LIMIT 30
    """,
    connection,
)

display(off_profile)
display(off_length_distribution)
display(off_examples)

,minimum_length,maximum_length,h_mm_shape_count,hh_mm_shape_count,other_shape_count,distinct_stored_values
0,4,5,1600952,250333,0,1380

   stored_length  row_count  distinct_values
0              4    1600952              540
1              5     250333              840

   stored_value  row_count
0          5:00      26917
1          2:15      25663
2          5:30      25611
3          2:50      25016
4          2:00      24321
5          6:00      23861
6          3:00      23769
7          2:40      23607
8          4:00      23478
9          3:10      23354
10         3:40      23253
11         2:30      23029
12         1:50      22904
13         3:15      22530
14         6:30      22492
15         3:50      22398
16         3:30      22254
17         2:20      21700
18         4:30      21462
19         4:10      21332
20         2:10      21320
21         7:00      20963
22         3:25      20508
23         3:45      20354
24         4:20      20224
25         3:20      20202
26         7:30      20014
27         4:45      19871
28         5:10      19697
29         2:45      19540

In [10]:
# Profile integer ranges and potentially special values.
#
# These checks describe the stored numbers only. They do not assume that
# race_id is globally unique or that every ran value is necessarily valid.

integer_field_profile = pd.read_sql_query(
    f"""
    SELECT
        MIN(race_id) AS minimum_race_id,
        MAX(race_id) AS maximum_race_id,
        COUNT(DISTINCT race_id) AS distinct_race_ids,
        SUM(CASE WHEN race_id <= 0 THEN 1 ELSE 0 END)
            AS non_positive_race_id_rows,

        MIN(ran) AS minimum_ran,
        MAX(ran) AS maximum_ran,
        COUNT(DISTINCT ran) AS distinct_ran_values,
        SUM(CASE WHEN ran <= 0 THEN 1 ELSE 0 END)
            AS non_positive_ran_rows
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

ran_distribution = pd.read_sql_query(
    f"""
    SELECT
        ran AS stored_value,
        COUNT(*) AS row_count,
        ROUND(
            100.0 * COUNT(*) /
            (
                SELECT COUNT(*)
                FROM data
                WHERE {DATA_ROW_PREDICATE}
            ),
            4
        ) AS row_pct
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY ran
    ORDER BY ran
    """,
    connection,
)

display(integer_field_profile)
display(ran_distribution)

,minimum_race_id,maximum_race_id,distinct_race_ids,non_positive_race_id_rows,minimum_ran,maximum_ran,distinct_ran_values,non_positive_ran_rows
0,0,4803590,188782,15,1,40,37,0

    stored_value  row_count  row_pct
0              1         22   0.0012
1              2        688   0.0372
2              3       5949   0.3213
3              4      23856   1.2886
4              5      58098   3.1383
5              6      98636   5.3280
6              7     138894   7.5026
7              8     167367   9.0406
8              9     179289   9.6846
9             10     181640   9.8116
10            11     173899   9.3934
11            12     196884  10.6350
12            13     133822   7.2286
13            14     171150   9.2449
14            15      84960   4.5892
15            16     101103   5.4612
16            17      38539   2.0817
17            18      38610   2.0856
18            19      12901   0.6969
19            20      15120   0.8167
20            21       5082   0.2745
21            22       6336   0.3422
22            23       4370   0.2361
23            24       4104   0.2217
24            25       3375   0.1823
25            26       1196   0.0646
26            27       1485   0.0802
27            28       1232   0.0665
28            29        725   0.0392
29            30       1110   0.0600
30            31         93   0.0050
31            32         64   0.0035
32            33         99   0.0053
33            34        272   0.0147
34            38         38   0.0021
35            39        117   0.0063
36            40        160   0.0086

In [11]:
# Inspect the small set of non-positive race_id records.
#
# No records are classified as erroneous here. The purpose is to capture
# their surrounding context for later investigation.

non_positive_race_ids = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        type,
        class,
        pattern,
        rating_band,
        age_band,
        sex_rest,
        dist,
        going,
        ran,
        num,
        pos,
        horse
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND race_id <= 0
    ORDER BY date, course, off, rowid
    """,
    connection,
)

print(f"Rows with race_id <= 0: {len(non_positive_race_ids):,}")
print(
    "Distinct provisional races represented: "
    f"{non_positive_race_ids[['date', 'course', 'off', 'race_name']].drop_duplicates().shape[0]:,}"
)

display(non_positive_race_ids)

Rows with race_id <= 0: 15
Distinct provisional races represented: 1

,source_rowid,date,course,race_id,off,race_name,type,class,pattern,rating_band,age_band,sex_rest,dist,going,ran,num,pos,horse
0,286607,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,1,1,Loud And Clear (GB)
1,286614,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,4,2,Donnas Delight (IRE)
2,286624,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,9,3,Pot Committed (IRE)
3,286625,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,3,4,Carry On Arcadio (IRE)
4,286626,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,12,6,Strong Economy (IRE)
5,286635,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,13,15,The Germany One (IRE)
6,286636,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,11,14,Solway Storm (IRE)
7,286637,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,2,13,Captain Sam (GB)
8,286638,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,8,12,Mullaghboy (IRE)
9,286639,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,15,11,Seelateralligator (IRE)
10,286640,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,10,10,Schnabel (IRE)
11,286641,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,5,9,Ka Maresco (FR)
12,286642,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,6,8,Katalystic (IRE)
13,286643,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,7,7,Minella Suite (IRE)
14,286646,2016-10-24,Ayr,0,4:40,Racing UK Day Pass Just £10 Standard Open Nati...,NH Flat,Class 6,,,4-6yo,,2m,Good To Soft,15,14,5,Medinah Theatre (IRE)

In [12]:
# Profile course labels exactly as stored.
#
# This does not yet split venue, jurisdiction, surface, or course variant.
# It only records the observed text structure and common values.

course_profile = pd.read_sql_query(
    f"""
    SELECT
        MIN(length(course)) AS minimum_length,
        MAX(length(course)) AS maximum_length,
        COUNT(DISTINCT course) AS distinct_values,
        SUM(CASE WHEN course LIKE '%(%)%' THEN 1 ELSE 0 END)
            AS rows_with_parentheses,
        COUNT(
            DISTINCT CASE
                WHEN course LIKE '%(%)%' THEN course
            END
        ) AS distinct_values_with_parentheses
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

course_top_values = pd.read_sql_query(
    f"""
    SELECT
        course AS stored_value,
        COUNT(*) AS row_count,
        ROUND(
            100.0 * COUNT(*) /
            (
                SELECT COUNT(*)
                FROM data
                WHERE {DATA_ROW_PREDICATE}
            ),
            4
        ) AS row_pct
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY course
    ORDER BY row_count DESC, course
    LIMIT 40
    """,
    connection,
)

course_parenthesis_examples = pd.read_sql_query(
    f"""
    SELECT
        course AS stored_value,
        COUNT(*) AS row_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND course LIKE '%(%)%'
    GROUP BY course
    ORDER BY row_count DESC, course
    LIMIT 40
    """,
    connection,
)

display(course_profile)
display(course_top_values)
display(course_parenthesis_examples)

,minimum_length,maximum_length,distinct_values,rows_with_parentheses,distinct_values_with_parentheses
0,3,30,528,1101537,339

          stored_value  row_count  row_pct
0   Wolverhampton (AW)      64746   3.4974
1         Sha Tin (HK)      52010   2.8094
2         Kempton (AW)      50268   2.7153
3       Chantilly (FR)      48744   2.6330
4       Deauville (FR)      48618   2.6262
5       Newcastle (AW)      42092   2.2737
6       Lingfield (AW)      41632   2.2488
7   Dundalk (AW) (IRE)      39075   2.1107
8      Chelmsford (AW)      37741   2.0386
9       Southwell (AW)      34488   1.8629
10        Auteuil (FR)      32708   1.7668
11   Happy Valley (HK)      31058   1.6776
12    Saint-Cloud (FR)      28412   1.5347
13           Doncaster      26166   1.4134
14       Curragh (IRE)      21921   1.1841
15             Newbury      21535   1.1632
16                 Ayr      20921   1.1301
17      Longchamp (FR)      20911   1.1295
18            Chepstow      20804   1.1238
19  Leopardstown (IRE)      19839   1.0716
20               Ascot      19669   1.0625
21    Fairyhouse (IRE)      19326   1.0439
22             Haydock      19065   1.0298
23   Punchestown (IRE)      18872   1.0194
24          Naas (IRE)      17920   0.9680
25         Navan (IRE)      17799   0.9614
26          Cork (IRE)      17738   0.9581
27             Windsor      17677   0.9549
28   Gowran Park (IRE)      17448   0.9425
29           Catterick      17389   0.9393
30         Musselburgh      16365   0.8840
31           Uttoxeter      16185   0.8743
32           Leicester      16172   0.8736
33                York      16170   0.8734
34      Limerick (IRE)      15333   0.8282
35            Carlisle      15282   0.8255
36        Meydan (UAE)      14881   0.8038
37           Newmarket      14772   0.7979
38          Nottingham      14711   0.7946
39          Cheltenham      14146   0.7641

             stored_value  row_count
0      Wolverhampton (AW)      64746
1            Sha Tin (HK)      52010
2            Kempton (AW)      50268
3          Chantilly (FR)      48744
4          Deauville (FR)      48618
5          Newcastle (AW)      42092
6          Lingfield (AW)      41632
7      Dundalk (AW) (IRE)      39075
8         Chelmsford (AW)      37741
9          Southwell (AW)      34488
10           Auteuil (FR)      32708
11      Happy Valley (HK)      31058
12       Saint-Cloud (FR)      28412
13          Curragh (IRE)      21921
14         Longchamp (FR)      20911
15     Leopardstown (IRE)      19839
16       Fairyhouse (IRE)      19326
17      Punchestown (IRE)      18872
18             Naas (IRE)      17920
19            Navan (IRE)      17799
20             Cork (IRE)      17738
21      Gowran Park (IRE)      17448
22         Limerick (IRE)      15333
23           Meydan (UAE)      14881
24           Galway (IRE)      13166
25       Newmarket (July)      11820
26  Maisons-Laffitte (FR)      10770
27        Tipperary (IRE)      10388
28        Killarney (IRE)      10167
29          Clonmel (IRE)       9967
30       Down Royal (IRE)       9900
31         Compiegne (FR)       9347
32          Tramore (IRE)       9066
33          Thurles (IRE)       8946
34         Listowel (IRE)       8575
35          Wexford (IRE)       8539
36       Ballinrobe (IRE)       8433
37        Roscommon (IRE)       8117
38        Kilbeggan (IRE)       8013
39         Randwick (AUS)       7850

In [13]:
# Extract every parenthesised fragment from the distinct stored course labels.
#
# This is exploratory evidence only. A fragment may represent jurisdiction,
# surface, course configuration, or something else.

import re
from collections import Counter

distinct_courses = pd.read_sql_query(
    f"""
    SELECT DISTINCT course
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    ORDER BY course
    """,
    connection,
)["course"]

parenthesised_fragments = Counter()

for course_value in distinct_courses:
    fragments = re.findall(r"\(([^()]*)\)", course_value)

    for fragment in fragments:
        parenthesised_fragments[fragment] += 1

course_fragment_profile = pd.DataFrame(
    [
        {
            "parenthesised_fragment": fragment,
            "distinct_course_labels": label_count,
        }
        for fragment, label_count in parenthesised_fragments.items()
    ]
).sort_values(
    ["distinct_course_labels", "parenthesised_fragment"],
    ascending=[False, True],
    ignore_index=True,
)

print(
    "Distinct parenthesised fragments: "
    f"{len(course_fragment_profile):,}"
)

display(course_fragment_profile)

Distinct parenthesised fragments: 40

   parenthesised_fragment  distinct_course_labels
0                      FR                      73
1                     USA                      56
2                     AUS                      51
3                     IRE                      27
4                     JPN                      21
5                     GER                      17
6                      NZ                      14
7                     SAF                       9
8                      AW                       8
9                     ITY                       7
10                    SWI                       5
11                    UAE                       5
12                    CAN                       4
13                    ARG                       3
14                    BEL                       3
15                    BRZ                       3
16                    CHI                       3
17                    SWE                       3
18                    BHR                       2
19                    CZE                       2
20                     HK                       2
21                    KOR                       2
22                  Perth                       2
23                     QA                       2
24                    SPA                       2
25         South Carolina                       2
26                    TUR                       2
27                    CHN                       1
28                    DEN                       1
29                    GUE                       1
30                    HUN                       1
31                    JER                       1
32                   July                       1
33                    KSA                       1
34                    NOR                       1
35                    PER                       1
36                    POL                       1
37                     RH                       1
38                    SIN                       1
39                    URU                       1

In [14]:
# Profile race names exactly as stored.
#
# Repeated race names are expected because the same named race can occur
# across years, meetings, or jurisdictions. No uniqueness assumption is made.

race_name_profile = pd.read_sql_query(
    f"""
    SELECT
        MIN(length(race_name)) AS minimum_length,
        MAX(length(race_name)) AS maximum_length,
        ROUND(AVG(length(race_name)), 2) AS average_length,
        COUNT(DISTINCT race_name) AS distinct_values,

        SUM(
            CASE
                WHEN race_name <> trim(race_name)
                THEN 1 ELSE 0
            END
        ) AS rows_with_outer_whitespace,

        COUNT(
            DISTINCT CASE
                WHEN race_name <> trim(race_name)
                THEN race_name
            END
        ) AS distinct_values_with_outer_whitespace
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

race_name_top_values = pd.read_sql_query(
    f"""
    SELECT
        race_name AS stored_value,
        COUNT(*) AS row_count,
        COUNT(
            DISTINCT date || '|' || course || '|' || off
        ) AS apparent_race_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY race_name
    ORDER BY apparent_race_count DESC, row_count DESC, race_name
    LIMIT 30
    """,
    connection,
)

race_name_longest = pd.read_sql_query(
    f"""
    SELECT DISTINCT
        race_name AS stored_value,
        length(race_name) AS stored_length
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    ORDER BY stored_length DESC, race_name
    LIMIT 20
    """,
    connection,
)

display(race_name_profile)
display(race_name_top_values)
display(race_name_longest)

,minimum_length,maximum_length,average_length,distinct_values,rows_with_outer_whitespace,distinct_values_with_outer_whitespace
0,8,100,47.73,108632,0,0

,stored_value,row_count,apparent_race_count
0,Betway Handicap,6029,679
1,Sky Sports Racing Sky 415 Handicap,2346,275
2,Irish Stallion Farms EBF Maiden,2775,259
3,32Red.com Handicap,2212,254
4,Betway Casino Handicap,2336,244
5,32Red Casino Handicap,1818,197
6,Download The At The Races App Handicap,1707,186
7,32Red Handicap,1438,169
8,Irish Stallion Farms EBF Maiden (Plus 10 Race),1871,168
9,Heed Your Hunch At Betway Handicap,1588,167
10,Every Race Live On Racing TV Handicap,1498,161
11,Betway Sprint Handicap,1521,154
12,Adare Manor Opportunity Handicap Hurdle,2123,149
13,sunbets.co.uk Handicap,1481,148
14,Ladbrokes Handicap,1294,147
15,Irish Stallion Farms EBF Fillies Maiden,1735,146
16,Free Tips Daily On attheraces.com Handicap,1321,146
17,Join Racing TV Now Handicap,1357,145
18,Irish Stallion Farms EBF Fillies Handicap,1275,131
19,Betway Live Casino Handicap,1173,120
20,Irish Stallion Farms EBF Fillies Maiden (Plus ...,1382,115
21,Betway Heed Your Hunch Handicap,1105,112
22,racingtv.com Handicap,1087,112
23,Irish Stallion Farms EBF Beginners Chase,1077,111
24,Betway Novice Stakes,820,111
25,Racing TV Handicap,1060,107
26,British Stallion Studs EBF Novice Stakes (GBB ...,860,106
27,Play 4 To Win At Betway Handicap,943,104
28,Irish Stallion Farms EBF Median Auction Maiden,1192,99
29,Irishinjuredjockeys.com Handicap,1188,99

                                         stored_value  stored_length
0   100% Racing TV Profits Back To Racing Apprenti...            100
1   188Bet Casino Apprentice Handicap (Racing Exce...            100
2   188Bet Faller Refunds At Cheltenham Thursday H...            100
3   2026 Annual Badges On Sale Now Handicap Chase ...            100
4   67th Prix Georges Courtois - Trophee Studio Ha...            100
5   69th Prix Georges Courtois - Trophee Studio Ha...            100
6   70th Prix Georges Courtois - Trophee Studio Ha...            100
7   7bets4free.com Fixed Brush Hurdle Series Maide...            100
8   All-Electric Macan EBF Restricted Maiden Stake...            100
9   Anderson Anderson & Brown Handicap Hurdle (Qua...            100
10  ApolloBet Bet Through Your Mobile Handicap (Jo...            100
11  ApolloBet Weekly Golf Refunds Handicap (Jockey...            100
12  Arabian Horse Equestrian Services Sprint Cup s...            100
13  Ascot Local Sports & Social Clubs Handicap Hur...            100
14  Association Of Hong Kong Racing Journalists 40...            100
15  At The Races App Form Study EBF Restricted Mai...            100
16  At The Races App Form Study Restricted Novice ...            100
17  Attwood Memorial Trophy Handicap Chase (Qualif...            100
18  Ayr Racecourse Gift Vouchers Handicap Chase (N...            100
19  B Wayne Hughes Beholder Mile Stakes presented ...            100

In [15]:
# Investigate the apparent 100-character ceiling in race_name.
#
# Hitting the exact maximum does not prove truncation, but a large number of
# values ending mid-word or without natural punctuation would support that
# interpretation.

race_name_length_distribution = pd.read_sql_query(
    f"""
    SELECT
        length(race_name) AS stored_length,
        COUNT(*) AS row_count,
        COUNT(DISTINCT race_name) AS distinct_values
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY length(race_name)
    ORDER BY stored_length
    """,
    connection,
)

race_name_ceiling_profile = pd.read_sql_query(
    f"""
    SELECT
        COUNT(*) AS rows_at_100_characters,
        COUNT(DISTINCT race_name) AS distinct_names_at_100_characters,
        ROUND(
            100.0 * COUNT(*) /
            (
                SELECT COUNT(*)
                FROM data
                WHERE {DATA_ROW_PREDICATE}
            ),
            4
        ) AS row_pct_at_100_characters
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND length(race_name) = 100
    """,
    connection,
)

race_name_ceiling_endings = pd.read_sql_query(
    f"""
    SELECT DISTINCT
        race_name AS stored_value,
        substr(race_name, -20) AS final_20_characters
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND length(race_name) = 100
    ORDER BY race_name
    LIMIT 50
    """,
    connection,
)

display(race_name_length_distribution.tail(15))
display(race_name_ceiling_profile)
display(race_name_ceiling_endings)

    stored_length  row_count  distinct_values
78             86       5146              458
79             87       5604              487
80             88       5321              462
81             89       4941              444
82             90       4925              459
83             91       5167              475
84             92       4730              489
85             93       4967              517
86             94       6163              623
87             95       7123              723
88             96       7718              820
89             97       8476              886
90             98       7358              782
91             99       5753              591
92            100       2861              303

,rows_at_100_characters,distinct_names_at_100_characters,row_pct_at_100_characters
0,2861,303,0.1545

                                         stored_value   final_20_characters
0   100% Racing TV Profits Back To Racing Apprenti...  ice Training Series)
1   188Bet Casino Apprentice Handicap (Racing Exce...  er Sprint Qualifier)
2   188Bet Faller Refunds At Cheltenham Thursday H...   Hurdle Series Qual)
3   2026 Annual Badges On Sale Now Handicap Chase ...  ualifier) (GBB Race)
4   67th Prix Georges Courtois - Trophee Studio Ha...  men Amateurs) (Poly)
5   69th Prix Georges Courtois - Trophee Studio Ha...  men Amateurs) (Poly)
6   70th Prix Georges Courtois - Trophee Studio Ha...  men Amateurs) (Poly)
7   7bets4free.com Fixed Brush Hurdle Series Maide...   Hurdle Series Qual)
8   All-Electric Macan EBF Restricted Maiden Stake...  /IRE Incentive Race)
9   Anderson Anderson & Brown Handicap Hurdle (Qua...   Mile Hurdle Series)
10  ApolloBet Bet Through Your Mobile Handicap (Jo...  ce Series Qualifier)
11  ApolloBet Weekly Golf Refunds Handicap (Jockey...  nce Series Qualifier
12  Arabian Horse Equestrian Services Sprint Cup s...   (3yo+) (Outer Turf)
13  Ascot Local Sports & Social Clubs Handicap Hur...  ies Final Qualifier)
14  Association Of Hong Kong Racing Journalists 40...   (3yo+) (B+2) (Turf)
15  At The Races App Form Study EBF Restricted Mai...  an Three Runs) (GBB)
16  At The Races App Form Study Restricted Novice ...  s B-D) (GBB)(Div II)
17  Attwood Memorial Trophy Handicap Chase (Qualif...   Chase Series Final)
18  Ayr Racecourse Gift Vouchers Handicap Chase (N...  se Series Qualifier)
19  B Wayne Hughes Beholder Mile Stakes presented ...   Mares) (Main Track)
20  Best Free Tips At valuerater.co.uk Handicap (V...   Sprint Series Qual)
21  Best Free Tips At valuerater.co.uk Handicap (V...   Sprint Series Quali
22  Best Odds Guaranteed Daily At Vickers.Bet Rest...  n Band D) (GBB Race)
23  Best Odds Guaranteed With Dragonbet Open Natio...  mination) (GBB Race)
24  Best Racing Odds On Smarkets Handicap (Jockey ...  ce Series Qualifier)
25  Bet Builder - Make Every Match Your Own Appren...  e) (Part Of The REI)
26  Bet Online With jenningsbet.com Handicap (A Jo...  ce Series Qualifier)
27  Bet toteWIN At betfred.com Handicap (A Qualifi...  urlong Series Final)
28  Bet £10 Get £40 At BetMGM EBF Restricted Maide...   Than 3 Times) (GBB)
29  Bet £10 Get £40 At BetMGM EBF Restricted Novic...  Less) (GBB) (Div II)
30  Bet £20 Get £20 With DragonBet EBF Restricted ...   C And D) (GBB Race)
31  BetUK. Home Of The Acca-Fenwa Maiden Stakes (F...  han Once) (GBB Race)
32  Betfair HPR Training Series Apprentice Handica...  sroots Stayers Qual)
33  Betfred Goals Galore Extra Handicap (A Qualifi...  urlong Series Final)
34  Betfred Goals Galore Haydock Park Apprentice T...  cellence Initiative)
35  Biggest Ever Jumps Season On RacingUK Handicap...  taying Chase Series)
36  Bloomfields Horseboxes Presents The Raceline P...  t Race (Cat 1) (GBB)
37  Book For The Ayrshire Wedding Show Handicap Hu...  le Series Qualifier)
38  Book Online For William Hill Medieval Day Hand...   Distance Qualifier)
39  Boost Your Acca At BetMGM Restricted Maiden St...   (GBB Race) (Div II)
40  Bothwell Building Supplies Saints & Sinners Am...  nners Challenge Cup)
41  British EBF Confined Novice Stakes (Horses Wit...   (GBB/IRE Incentive)
42  British EBF Future Stayers Maiden Stakes (Plus...  Dam Restricted Race)
43  British Stallion Studs EBF Future Stayers Nurs...  Race) (GBBPlus Race)
44  British Stallion Studs EBF Maiden Stakes (High...  fier) (Plus 10 Race)
45  British Stallion Studs EBF Maiden Stakes (Winn...  Leger) (GBB/GBBPlus)
46  British Stallion Studs EBF Restricted Maiden S...  Qualifier)(GBB Race)
47  British Stallion Studs EBF Restricted Maiden S...  (IRE Incentive)(GBB)
48  British Stallion Studs EBF Restricted Maiden S...  /IRE Incentive Race)
49  British Stallion Studs EBF Restricted Novice S...  ted Qual) (GBB Race)

In [16]:
# Profile race distance labels exactly as stored.
#
# No conversion to furlongs, metres, yards, or miles is attempted here.
# The aim is to document the source notation and identify unusual codes.

distance_profile = pd.read_sql_query(
    f"""
    SELECT
        MIN(length(dist)) AS minimum_length,
        MAX(length(dist)) AS maximum_length,
        COUNT(DISTINCT dist) AS distinct_values,
        SUM(
            CASE
                WHEN dist <> trim(dist)
                THEN 1 ELSE 0
            END
        ) AS rows_with_outer_whitespace
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

distance_distribution = pd.read_sql_query(
    f"""
    SELECT
        dist AS stored_value,
        COUNT(*) AS row_count,
        ROUND(
            100.0 * COUNT(*) /
            (
                SELECT COUNT(*)
                FROM data
                WHERE {DATA_ROW_PREDICATE}
            ),
            4
        ) AS row_pct
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY dist
    ORDER BY row_count DESC, dist
    """,
    connection,
)

display(distance_profile)
display(distance_distribution)

   minimum_length  maximum_length  distinct_values  rows_with_outer_whitespace
0               2               5               63                           0

   stored_value  row_count  row_pct
0            1m     225603  12.1863
1            6f     213342  11.5240
2            7f     205608  11.1062
3            2m     131238   7.0890
4            5f     108768   5.8753
..          ...        ...      ...
58        4m1½f        144   0.0078
59        3m7½f        137   0.0074
60         4m1f        121   0.0065
61         3m7f         70   0.0038
62        4m4½f         14   0.0008

[63 rows x 3 columns]

In [17]:
# Show every distinct stored distance value without notebook row truncation.
with pd.option_context("display.max_rows", None):
    display(distance_distribution)

   stored_value  row_count  row_pct
0            1m     225603  12.1863
1            6f     213342  11.5240
2            7f     205608  11.1062
3            2m     131238   7.0890
4            5f     108768   5.8753
5          1m2f     108760   5.8748
6          1m4f      80320   4.3386
7          2m4f      63594   3.4351
8          2m½f      48639   2.6273
9         1m1½f      43606   2.3554
10         1m1f      40510   2.1882
11           3m      39142   2.1143
12         1m½f      37446   2.0227
13         2m1f      34481   1.8625
14        2m3½f      32119   1.7350
15        2m4½f      26341   1.4228
16         2m2f      25816   1.3945
17        1m2½f      24321   1.3137
18          7½f      23885   1.2902
19         2m3f      23689   1.2796
20         2m5f      22518   1.2163
21         1m6f      21263   1.1486
22          6½f      21003   1.1345
23        1m4½f      19830   1.0711
24         1m3f      18881   1.0199
25        1m7½f      18549   1.0020
26        2m1½f      18211   0.9837
27        2m5½f      17614   0.9514
28          5½f      16319   0.8815
29        2m7½f      15253   0.8239
30         2m6f      14975   0.8089
31         2m7f      12784   0.6905
32         3m½f      11102   0.5997
33         3m1f      10618   0.5735
34        2m2½f      10453   0.5646
35        2m6½f       8502   0.4592
36        1m3½f       8254   0.4459
37         1m7f       7986   0.4314
38         3m2f       7455   0.4027
39        3m1½f       6767   0.3655
40         1m5f       6376   0.3444
41        1m5½f       5679   0.3068
42        3m2½f       2820   0.1523
43        1m6½f       1483   0.0801
44         3m5f       1341   0.0724
45         3m3f        956   0.0516
46        3m3½f        944   0.0510
47        3m4½f        931   0.0503
48         3m6f        799   0.0432
49        3m6½f        638   0.0345
50        4m2½f        611   0.0330
51         3m4f        522   0.0282
52           4m        468   0.0253
53        3m5½f        441   0.0238
54          4½f        426   0.0230
55         4m½f        346   0.0187
56           4f        269   0.0145
57         4m2f        184   0.0099
58        4m1½f        144   0.0078
59        3m7½f        137   0.0074
60         4m1f        121   0.0065
61         3m7f         70   0.0038
62        4m4½f         14   0.0008

In [18]:
# Profile rating_band notation without parsing it into numeric limits.
#
# The categories below describe visible string structure only. They are not
# racing-domain classifications and do not imply any cleaning decision.

rating_band_distribution = pd.read_sql_query(
    f"""
    SELECT
        rating_band AS stored_value,
        COUNT(*) AS row_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY rating_band
    ORDER BY row_count DESC, rating_band
    """,
    connection,
)

def classify_rating_band_shape(value):
    """Describe the visible structure of one stored rating-band value."""
    if value == "":
        return "blank"

    if re.fullmatch(r"\d+-\d+", value):
        return "numeric range"

    if re.fullmatch(r"\d+", value):
        return "single number"

    if re.fullmatch(r"\d+\+", value):
        return "number with plus"

    if re.fullmatch(r"\d+-\d+\s+\([^)]+\)", value):
        return "numeric range with parenthetical text"

    if re.fullmatch(r"\d+\s+\([^)]+\)", value):
        return "single number with parenthetical text"

    return "other text shape"


rating_band_distribution["observed_shape"] = (
    rating_band_distribution["stored_value"].map(
        classify_rating_band_shape
    )
)

rating_band_shape_profile = (
    rating_band_distribution
    .groupby("observed_shape", as_index=False)
    .agg(
        distinct_values=("stored_value", "count"),
        row_count=("row_count", "sum"),
    )
)

rating_band_shape_profile["row_pct"] = (
    rating_band_shape_profile["row_count"]
    / rating_band_shape_profile["row_count"].sum()
    * 100
)

rating_band_shape_profile = rating_band_shape_profile.sort_values(
    ["row_count", "observed_shape"],
    ascending=[False, True],
    ignore_index=True,
)

display(rating_band_shape_profile.round({"row_pct": 4}))

# Show every value that does not match the simple expected shapes.
rating_band_other_values = rating_band_distribution.loc[
    rating_band_distribution["observed_shape"]
    == "other text shape"
].copy()

print(
    "Distinct values with other text shapes: "
    f"{len(rating_band_other_values):,}"
)

with pd.option_context("display.max_rows", None):
    display(rating_band_other_values)

     observed_shape  distinct_values  row_count  row_pct
0             blank                1    1081546  58.4214
1     numeric range              381     769622  41.5723
2  other text shape                2        117   0.0063

Distinct values with other text shapes: 2

    stored_value  row_count    observed_shape
92            --        110  other text shape
360     (75-100)          7  other text shape

In [19]:
# Inspect the context of exceptional rating_band values.
#
# This helps distinguish isolated formatting issues from repeated
# source conventions without changing the values.

exceptional_rating_band_rows = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        type,
        class,
        pattern,
        rating_band,
        age_band,
        sex_rest,
        dist,
        going,
        ran,
        num,
        pos,
        horse
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND rating_band IN ('--', '(75-100)')
    ORDER BY rating_band, date, course, off, rowid
    """,
    connection,
)

exceptional_rating_band_races = (
    exceptional_rating_band_rows[
        [
            "rating_band",
            "date",
            "course",
            "race_id",
            "off",
            "race_name",
            "type",
            "class",
            "pattern",
            "age_band",
            "sex_rest",
            "dist",
            "going",
            "ran",
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["rating_band", "date", "course", "off"],
        ignore_index=True,
    )
)

print(
    "Runner rows with exceptional rating_band values: "
    f"{len(exceptional_rating_band_rows):,}"
)
print(
    "Distinct apparent races represented: "
    f"{len(exceptional_rating_band_races):,}"
)

with pd.option_context(
    "display.max_rows",
    None,
    "display.max_colwidth",
    120,
):
    display(exceptional_rating_band_races)

Runner rows with exceptional rating_band values: 117
Distinct apparent races represented: 13

,rating_band,date,course,race_id,off,race_name,type,class,pattern,age_band,sex_rest,dist,going,ran
0,(75-100),2026-02-25,Happy Valley,914010,11:40,Magazine Gap Handicap (B Course) (Turf),Flat,Class 2,,,,1m1f,Good,7
1,--,2016-02-19,Jebel Ali (UAE),644459,11:20,Jebel Ali Stakes () (Dirt),Flat,,Listed,3yo+,,1m2f,Fast,11
2,--,2017-11-03,Ohi (JPN),689802,10:07,JBC Sprint (Local (Dirt),Flat,,Grade 1,3yo+,,6f,Muddy,16
3,--,2017-11-03,Ohi (JPN),689592,11:07,JBC Classic (Local (Dirt),Flat,,Grade 1,3yo+,,1m1f,Muddy,13
4,--,2018-01-26,Jebel Ali (UAE),693130,11:30,Jebel Ali Mile Sponsored By Shadwell Farm (Dirt),Flat,,Group 3,3yo+,,1m,Fast,7
5,--,2018-04-30,NAGOYA (JPN),701640,11:07,Kakitsubata Kinen (Handicap) (4yo+) (Local (Dirt),Flat,,Grade 3,4yo+,,7f,Standard,12
6,--,2018-05-13,Les Landes (JER),702426,4:50,Bloodstock Advisory Services Handicap,Flat,,,3yo+,,1m½f,Good To Firm,8
7,--,2018-05-30,Urawa (JPN),704187,11:07,Sakitama Hai (Local (Dirt),Flat,,Grade 2,4yo+,,7f,Standard,11
8,--,2018-07-22,Les Landes (JER),707986,2:30,Milbrook July Conditions Hurdle,Hurdle,,,3yo+,,2m,Firm,6
9,--,2018-07-22,Les Landes (JER),707991,3:05,Patricia K Pritchard Handicap Sprint,Flat,,,3yo+,,5½f,Firm,5
10,--,2018-07-22,Les Landes (JER),707996,3:40,La Vallette 2018 Jersey Derby,Flat,,,3yo+,,1m4f,Firm,8
11,--,2019-06-21,Les Landes (JER),734345,8:50,Mid-Summer Glorious Les Landes Handicap,Flat,,,3yo+,,1m4f,Good,5
12,--,2021-11-26,Jebel Ali (UAE),799081,10:00,Commemoration Day Cup Sponsored By Dubai Real Estate Centre (Maiden) (Dirt),Flat,,,4yo+,,7f,Fast,8

In [20]:
# Inspect every row where age_band is stored as a blank string.
#
# The aim is to determine whether blankness occurs at race level and whether
# it is associated with particular jurisdictions or race types.

blank_age_band_rows = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        type,
        class,
        pattern,
        rating_band,
        age_band,
        sex_rest,
        dist,
        going,
        ran,
        num,
        pos,
        horse
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND length(trim(age_band)) = 0
    ORDER BY date, course, off, rowid
    """,
    connection,
)

blank_age_band_races = (
    blank_age_band_rows[
        [
            "date",
            "course",
            "race_id",
            "off",
            "race_name",
            "type",
            "class",
            "pattern",
            "rating_band",
            "sex_rest",
            "dist",
            "going",
            "ran",
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["date", "course", "off"],
        ignore_index=True,
    )
)

print(f"Runner rows with blank age_band: {len(blank_age_band_rows):,}")
print(
    "Distinct apparent races represented: "
    f"{len(blank_age_band_races):,}"
)

with pd.option_context(
    "display.max_rows",
    None,
    "display.max_colwidth",
    120,
):
    display(blank_age_band_races)

Runner rows with blank age_band: 159
Distinct apparent races represented: 13

,date,course,race_id,off,race_name,type,class,pattern,rating_band,sex_rest,dist,going,ran
0,2015-06-07,Baden-Baden (GER),630735,3:30,Badener Roulette Preis (Turf),Flat,,,,,1m2f,Good,5
1,2021-05-27,Limerick (IRE),785625,8:10,Athea INH Flat Race,NH Flat,,,,,2m,Yielding To Soft,18
2,2021-07-16,Kilbeggan (IRE),789491,8:10,Follow Kilbeggan On Facebook INH Flat Race,NH Flat,,,,,2m4f,Good,11
3,2026-02-14,Sha Tin,913671,04:45,Tvb Lok Sin Tong Charity Corner Hcp (C4) (Handicap) (Turf),Flat,,,,,6f,Good To Firm,12
4,2026-02-14,Sha Tin,913672,05:40,Tvb Yan Oi Tong Charity Show Hcp (C4) (Handicap) (Turf),Flat,,,,,7f,Good To Firm,14
5,2026-02-14,Sha Tin,913673,06:10,Tvb Yan Chai Charity Show Hcp (C3) (Handicap) (Turf),Flat,,,,,6f,Good To Firm,11
6,2026-02-14,Sha Tin,913674,06:40,Tvb Pok Oi Charity Show Hcp (C4) (Handicap) (Turf),Flat,,,,,1m1f,Good To Firm,14
7,2026-02-14,Sha Tin,913675,07:10,Tvb Lo And Behold Hcp (C3) (Handicap) (Dirt),Flat,,,,,1m,Standard,14
8,2026-02-14,Sha Tin,913676,07:40,Tvb The Queen Of News Hcp (C4) (Handicap) (Dirt),Flat,,,,,1m,Standard,14
9,2026-02-14,Sha Tin,913677,08:15,The Tvb Cup (C2) (Handicap) (Turf),Flat,,,,,6f,Good To Firm,11
10,2026-02-14,Sha Tin,913678,08:50,Tvb Scoop Hcp (C4) (Handicap) (Turf),Flat,,,,,7f,Good To Firm,14
11,2026-02-14,Sha Tin,913679,09:25,Tvb Midlife Sing & Shine Hcp (C3) (Handicap) (Turf),Flat,,,,,5f,Good To Firm,14
12,2026-02-25,Happy Valley,914010,11:40,Magazine Gap Handicap (B Course) (Turf),Flat,Class 2,,(75-100),,1m1f,Good,7

In [21]:
# Inspect every row where going is stored as a blank string.
#
# This determines whether the missing values affect isolated runners,
# complete races, particular meetings, or particular jurisdictions.

blank_going_rows = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        type,
        class,
        pattern,
        rating_band,
        age_band,
        sex_rest,
        dist,
        going,
        ran,
        num,
        pos,
        horse
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND length(trim(going)) = 0
    ORDER BY date, course, off, rowid
    """,
    connection,
)

blank_going_races = (
    blank_going_rows[
        [
            "date",
            "course",
            "race_id",
            "off",
            "race_name",
            "type",
            "class",
            "pattern",
            "rating_band",
            "age_band",
            "sex_rest",
            "dist",
            "ran",
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["date", "course", "off"],
        ignore_index=True,
    )
)

print(f"Runner rows with blank going: {len(blank_going_rows):,}")
print(
    "Distinct apparent races represented: "
    f"{len(blank_going_races):,}"
)

with pd.option_context(
    "display.max_rows",
    None,
    "display.max_colwidth",
    120,
):
    display(blank_going_races)

Runner rows with blank going: 45
Distinct apparent races represented: 4

,date,course,race_id,off,race_name,type,class,pattern,rating_band,age_band,sex_rest,dist,ran
0,2015-02-27,Sakhir (BHR),629750,12:15,SH. ISA Bin Salman Bin Hamad Al Khalifa Cup (Local (Turf),Flat,,Grade 2,,3yo+,,1m,12
1,2015-05-01,Tours (FR),625766,4:30,Prix des Fleurs de Touraine (Conditions) (4yo+) (Turf),Flat,,,,4yo+,,1m,11
2,2015-11-17,Doha (QA),639711,4:10,Barzan Cup (Handicap) (Turf),Flat,,,,3yo+,,1m,11
3,2019-12-19,Wolverhampton (AW),745750,8:30,Betway Casino Handicap,Flat,Class 6,,0-55,4yo+,,1m6f,11

In [22]:
# Validate the numeric components of off-time strings as stored.
#
# Both H:MM and HH:MM formats are accepted. This check only asks whether
# the hour and minute portions fall within ordinary clock ranges.

off_component_profile = pd.read_sql_query(
    f"""
    WITH parsed_off AS (
        SELECT
            off,
            CAST(substr(off, 1, instr(off, ':') - 1) AS INTEGER)
                AS stored_hour,
            CAST(substr(off, instr(off, ':') + 1, 2) AS INTEGER)
                AS stored_minute
        FROM data
        WHERE {DATA_ROW_PREDICATE}
    )
    SELECT
        MIN(stored_hour) AS minimum_hour,
        MAX(stored_hour) AS maximum_hour,
        MIN(stored_minute) AS minimum_minute,
        MAX(stored_minute) AS maximum_minute,

        SUM(
            CASE
                WHEN stored_hour < 0 OR stored_hour > 23
                THEN 1 ELSE 0
            END
        ) AS invalid_hour_rows,

        SUM(
            CASE
                WHEN stored_minute < 0 OR stored_minute > 59
                THEN 1 ELSE 0
            END
        ) AS invalid_minute_rows,

        COUNT(
            DISTINCT CASE
                WHEN stored_hour < 0 OR stored_hour > 23
                  OR stored_minute < 0 OR stored_minute > 59
                THEN off
            END
        ) AS distinct_invalid_values
    FROM parsed_off
    """,
    connection,
)

off_hour_distribution = pd.read_sql_query(
    f"""
    SELECT
        CAST(substr(off, 1, instr(off, ':') - 1) AS INTEGER)
            AS stored_hour,
        COUNT(*) AS row_count,
        COUNT(DISTINCT off) AS distinct_off_values
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY stored_hour
    ORDER BY stored_hour
    """,
    connection,
)

display(off_component_profile)
display(off_hour_distribution)

,minimum_hour,maximum_hour,minimum_minute,maximum_minute,invalid_hour_rows,invalid_minute_rows,distinct_invalid_values
0,0,23,0,59,0,0,0

    stored_hour  row_count  distinct_off_values
0             0        167                   16
1             1     171356                   69
2             2     276436                   73
3             3     274007                   76
4             4     247001                   77
5             5     217114                   80
6             6     151027                   80
7             7     140310                   79
8             8      96760                   77
9             9      35770                   74
10           10      30279                   60
11           11      38365                   60
12           12      90335                   59
13           13      11049                   51
14           14      15847                   60
15           15      15575                   57
16           16      12630                   57
17           17      10521                   45
18           18       5999                   48
19           19       5434                   50
20           20       3468                   37
21           21        625                   33
22           22        749                   34
23           23        461                   28

In [23]:
# Test race-level consistency within the provisional race grouping:
# date + course + off + race_name.
#
# These fields are repeated on every runner row. A field should normally have
# one stored value within a race, but this test records evidence rather than
# imposing that assumption.

repeated_race_fields = [
    "race_id",
    "type",
    "class",
    "pattern",
    "rating_band",
    "age_band",
    "sex_rest",
    "dist",
    "going",
    "ran",
]

race_consistency_rows = []

for field in repeated_race_fields:
    quoted_field = f'"{field}"'

    consistency_result = pd.read_sql_query(
        f"""
        WITH apparent_races AS (
            SELECT
                date,
                course,
                off,
                race_name,
                COUNT(*) AS runner_rows,
                COUNT(DISTINCT {quoted_field}) AS distinct_stored_values
            FROM data
            WHERE {DATA_ROW_PREDICATE}
            GROUP BY
                date,
                course,
                off,
                race_name
        )
        SELECT
            COUNT(*) AS apparent_race_count,
            SUM(
                CASE
                    WHEN distinct_stored_values > 1
                    THEN 1 ELSE 0
                END
            ) AS inconsistent_race_count,
            MAX(distinct_stored_values) AS maximum_values_within_race
        FROM apparent_races
        """,
        connection,
    ).iloc[0]

    race_consistency_rows.append(
        {
            "field_name": field,
            "apparent_race_count": int(
                consistency_result["apparent_race_count"]
            ),
            "inconsistent_race_count": int(
                consistency_result["inconsistent_race_count"]
            ),
            "maximum_values_within_race": int(
                consistency_result["maximum_values_within_race"]
            ),
        }
    )

race_level_consistency = pd.DataFrame(race_consistency_rows)

race_level_consistency["inconsistent_race_pct"] = (
    race_level_consistency["inconsistent_race_count"]
    / race_level_consistency["apparent_race_count"]
    * 100
)

display(
    race_level_consistency.round(
        {"inconsistent_race_pct": 6}
    )
)

,field_name,apparent_race_count,inconsistent_race_count,maximum_values_within_race,inconsistent_race_pct
0,race_id,189043,0,1,0.0
1,type,189043,0,1,0.0
2,class,189043,0,1,0.0
3,pattern,189043,0,1,0.0
4,rating_band,189043,0,1,0.0
5,age_band,189043,0,1,0.0
6,sex_rest,189043,0,1,0.0
7,dist,189043,0,1,0.0
8,going,189043,0,1,0.0
9,ran,189043,0,1,0.0

In [24]:
# Compare the stored ran value with the number of physical rows in each
# provisional race grouping.
#
# A mismatch does not automatically indicate an error. It may reflect
# withdrawals, non-runners, missing source rows, or a different domain meaning
# of ran. This cell records the observed relationship only.

ran_row_count_comparison = pd.read_sql_query(
    f"""
    WITH apparent_races AS (
        SELECT
            date,
            course,
            off,
            race_name,
            MIN(race_id) AS race_id,
            MIN(ran) AS stored_ran,
            COUNT(*) AS physical_runner_rows
        FROM data
        WHERE {DATA_ROW_PREDICATE}
        GROUP BY
            date,
            course,
            off,
            race_name
    )
    SELECT
        COUNT(*) AS apparent_race_count,

        SUM(
            CASE
                WHEN stored_ran = physical_runner_rows
                THEN 1 ELSE 0
            END
        ) AS matching_race_count,

        SUM(
            CASE
                WHEN stored_ran <> physical_runner_rows
                THEN 1 ELSE 0
            END
        ) AS mismatching_race_count,

        MIN(stored_ran - physical_runner_rows)
            AS minimum_stored_minus_rows,

        MAX(stored_ran - physical_runner_rows)
            AS maximum_stored_minus_rows
    FROM apparent_races
    """,
    connection,
)

ran_difference_distribution = pd.read_sql_query(
    f"""
    WITH apparent_races AS (
        SELECT
            date,
            course,
            off,
            race_name,
            MIN(ran) AS stored_ran,
            COUNT(*) AS physical_runner_rows
        FROM data
        WHERE {DATA_ROW_PREDICATE}
        GROUP BY
            date,
            course,
            off,
            race_name
    )
    SELECT
        stored_ran - physical_runner_rows AS stored_ran_minus_rows,
        COUNT(*) AS apparent_race_count
    FROM apparent_races
    GROUP BY stored_ran_minus_rows
    ORDER BY stored_ran_minus_rows
    """,
    connection,
)

display(ran_row_count_comparison)

with pd.option_context("display.max_rows", None):
    display(ran_difference_distribution)

,apparent_race_count,matching_race_count,mismatching_race_count,minimum_stored_minus_rows,maximum_stored_minus_rows
0,189043,189038,5,0,4

   stored_ran_minus_rows  apparent_race_count
0                      0               189038
1                      1                    4
2                      4                    1

In [25]:
# Inspect the five apparent races where stored ran does not equal the number
# of physical runner rows.
#
# The difference may reflect missing runner records, non-runners excluded
# from the table, or another source convention. No cause is assumed yet.

ran_mismatch_races = pd.read_sql_query(
    f"""
    WITH apparent_races AS (
        SELECT
            date,
            course,
            off,
            race_name,
            MIN(race_id) AS race_id,
            MIN(type) AS type,
            MIN(class) AS class,
            MIN(pattern) AS pattern,
            MIN(rating_band) AS rating_band,
            MIN(age_band) AS age_band,
            MIN(sex_rest) AS sex_rest,
            MIN(dist) AS dist,
            MIN(going) AS going,
            MIN(ran) AS stored_ran,
            COUNT(*) AS physical_runner_rows
        FROM data
        WHERE {DATA_ROW_PREDICATE}
        GROUP BY
            date,
            course,
            off,
            race_name
    )
    SELECT
        *,
        stored_ran - physical_runner_rows AS stored_ran_minus_rows
    FROM apparent_races
    WHERE stored_ran <> physical_runner_rows
    ORDER BY
        stored_ran_minus_rows DESC,
        date,
        course,
        off
    """,
    connection,
)

print(f"Races with ran/row-count mismatches: {len(ran_mismatch_races):,}")

with pd.option_context(
    "display.max_rows",
    None,
    "display.max_colwidth",
    120,
):
    display(ran_mismatch_races)

Races with ran/row-count mismatches: 5

,date,course,off,race_name,race_id,type,class,pattern,rating_band,age_band,sex_rest,dist,going,stored_ran,physical_runner_rows,stored_ran_minus_rows
0,2024-09-26,Funabashi (JPN),11:07,Marine Cup (Local (Fillies) (Dirt),878244,Flat,,Grade 3,,3yo,F,1m1f,Standard,6,2,4
1,2024-06-18,Nantes (FR),2:14,Prix Sarah Gosse (Conditions Hurdle) (Turf),873374,Hurdle,,,,3yo,,2m1½f,Heavy,8,7,1
2,2024-06-26,Ohi (JPN),11:07,Teio Sho (Local (Dirt),871722,Flat,,Grade 1,,4yo+,,1m2f,Standard,5,4,1
3,2024-09-03,Morioka (JPN),11:07,Kozukata Sho (Local (Dirt),876244,Flat,,Grade 3,,3yo,,1m2f,Standard,5,4,1
4,2025-10-09,Ohi (JPN),11:07,Tokyo Hai (Local (Dirt),905803,Flat,,Grade 3,,3yo+,,6f,Standard,16,15,1

In [26]:
# Inspect the stored runner rows for the five races where ran exceeds the
# number of physical source rows.
#
# Gaps in num or pos may help describe which records are absent, but this
# still does not establish why those records are missing.

ran_mismatch_runner_rows = pd.read_sql_query(
    f"""
    WITH mismatch_races AS (
        SELECT
            date,
            course,
            off,
            race_name
        FROM data
        WHERE {DATA_ROW_PREDICATE}
        GROUP BY
            date,
            course,
            off,
            race_name
        HAVING MIN(ran) <> COUNT(*)
    )
    SELECT
        d.rowid AS source_rowid,
        d.date,
        d.course,
        d.race_id,
        d.off,
        d.race_name,
        d.ran AS stored_ran,
        d.num,
        d.pos,
        d.horse,
        d.sp,
        d.comment
    FROM data AS d
    INNER JOIN mismatch_races AS m
        ON d.date = m.date
       AND d.course = m.course
       AND d.off = m.off
       AND d.race_name = m.race_name
    WHERE d.rowid <> 1
    ORDER BY
        d.date,
        d.course,
        d.off,
        d.pos,
        d.num,
        d.rowid
    """,
    connection,
)

with pd.option_context(
    "display.max_rows",
    None,
    "display.max_colwidth",
    120,
):
    display(ran_mismatch_runner_rows)

,source_rowid,date,course,race_id,off,race_name,stored_ran,num,pos,horse,sp,comment
0,1524983,2024-06-18,Nantes (FR),873374,2:14,Prix Sarah Gosse (Conditions Hurdle) (Turf),8,,1,Pyrrhaa (FR),74/10,
1,1524982,2024-06-18,Nantes (FR),873374,2:14,Prix Sarah Gosse (Conditions Hurdle) (Turf),8,,2,Lhubert De Houelle (FR),58/10,
2,1524981,2024-06-18,Nantes (FR),873374,2:14,Prix Sarah Gosse (Conditions Hurdle) (Turf),8,,3,Bakarelo (IRE),7/5F,
3,1524980,2024-06-18,Nantes (FR),873374,2:14,Prix Sarah Gosse (Conditions Hurdle) (Turf),8,,4,Shalez (FR),19/1,
4,1524979,2024-06-18,Nantes (FR),873374,2:14,Prix Sarah Gosse (Conditions Hurdle) (Turf),8,,5,Bonham Strand (FR),4/1,
5,1524978,2024-06-18,Nantes (FR),873374,2:14,Prix Sarah Gosse (Conditions Hurdle) (Turf),8,,6,Lulu Stars (FR),22/1,
6,1524977,2024-06-18,Nantes (FR),873374,2:14,Prix Sarah Gosse (Conditions Hurdle) (Turf),8,,7,Cockling (FR),25/1,
7,1528630,2024-06-26,Ohi (JPN),871722,11:07,Teio Sho (Local (Dirt),5,12,1,Kings Sword (JPN),,
8,1528614,2024-06-26,Ohi (JPN),871722,11:07,Teio Sho (Local (Dirt),5,8,2,Wilson Tesoro (JPN),,
9,1528615,2024-06-26,Ohi (JPN),871722,11:07,Teio Sho (Local (Dirt),5,3,3,Diktaean (JPN),,
10,1528616,2024-06-26,Ohi (JPN),871722,11:07,Teio Sho (Local (Dirt),5,1,4,Grand Bridge (JPN),,
11,1560076,2024-09-03,Morioka (JPN),876244,11:07,Kozukata Sho (Local (Dirt),5,7,1,Sunrise Zipangu (JPN),,
12,1560075,2024-09-03,Morioka (JPN),876244,11:07,Kozukata Sho (Local (Dirt),5,4,2,Kashima Espada (JPN),,
13,1560074,2024-09-03,Morioka (JPN),876244,11:07,Kozukata Sho (Local (Dirt),5,1,3,Satono Phoenix (JPN),,
14,1560073,2024-09-03,Morioka (JPN),876244,11:07,Kozukata Sho (Local (Dirt),5,8,4,Fuji Eugene (JPN),,
15,1571458,2024-09-26,Funabashi (JPN),878244,11:07,Marine Cup (Local (Fillies) (Dirt),6,,1,Tenka Jo (IRE),,
16,1571457,2024-09-26,Funabashi (JPN),878244,11:07,Marine Cup (Local (Fillies) (Dirt),6,,2,Clavichord (JPN),,
17,1747011,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,,1,Yamanin Cerchi (JPN),,
18,1747012,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,,2,Kurojishi Joe (JPN),,
19,1747013,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,,3,Sunrise Amour (JPN),,
20,1747014,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,,4,Don Amitie (JPN),,
21,1747015,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,,5,Max (JPN),,
22,1747016,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,,6,Continuar (JPN),,
23,1747017,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,,7,Entelecheia (JPN),,
24,1747018,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,,8,Dream Believer (JPN),,
25,1747019,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,,9,Johnson Tesoro (JPN),,
26,1747020,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,,10,Omega Rainbow (JPN),,
27,1747021,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,,11,Exult (JPN),,
28,1747022,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,0,12,Arms Reign (JPN),,
29,1747023,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,,13,Mars Indy (JPN),,
30,1747024,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,,14,Theurgist (USA),,
31,1747025,2025-10-09,Ohi (JPN),905803,11:07,Tokyo Hai (Local (Dirt),16,,15,Win Librement (JPN),,

## Group 1 findings — Identifier and race-description fields

### Storage and completeness

The 14 fields in this group contain no SQL `NULL` values.

Missing race-description information is instead stored as blank text, principally in:

- `class`;
- `pattern`;
- `rating_band`;
- `sex_rest`.

Smaller blank populations occur in:

- `age_band`;
- `going`.

The fields `race_id` and `ran` are stored consistently as SQLite integers. The field `date` is declared `NUMERIC` but is stored entirely as text.

### Race-level consistency

Within the provisional race grouping formed from `date`, `course`, `off`, and `race_name`, every repeated race-description field has exactly one stored value.

This supports the interpretation that the following are race-level attributes repeated on runner rows:

- `race_id`;
- `type`;
- `class`;
- `pattern`;
- `rating_band`;
- `age_band`;
- `sex_rest`;
- `dist`;
- `going`;
- `ran`.

### Fields with strong structural consistency

- `date` always has the stored shape `YYYY-MM-DD`.
- `off` always has the shape `H:MM` or `HH:MM`, with valid clock components.
- `type` contains four stored categories.
- `dist` uses a compact and regular miles-and-furlongs notation.
- `ran` is always positive and ranges from 1 to 40.

### Identified quality issues

#### `race_id`

One complete 15-runner race has `race_id = 0`.

The value is therefore an identifier defect affecting one race, rather than a general missing-value convention.

#### `race_name`

The field has an apparent 100-character ceiling.

There are 303 distinct race names at exactly 100 characters, and some end mid-word. This is evidence of probable source truncation.

#### `rating_band`

Most populated values are simple numeric ranges.

Two exceptional stored forms occur:

- `--`, affecting 110 rows across 12 races;
- `(75-100)`, affecting seven rows from one race.

These require later domain investigation.

#### `age_band`

There are 159 blank rows across 13 complete races. The blankness is concentrated in particular meetings and jurisdictions rather than scattered among individual runners.

#### `going`

There are 45 blank rows across four complete races. These are race-level source omissions.

#### `ran`

The stored value equals the number of physical runner rows in 189,038 of 189,043 apparent races.

Five races have fewer stored runner rows than the stated `ran` value. In each case, the available finishing positions are contiguous from first place onward, indicating that the final one or more runner records are absent from the source table.

### Fields requiring separate domain investigation

- parsing the composite `course` field;
- interpreting course parenthetical fragments;
- converting `dist` to a standard numeric measure;
- interpreting blank `class`, `pattern`, and `sex_rest` values;
- interpreting `rating_band` placeholders and formatting variants;
- determining the source convention behind the five incomplete races;
- determining whether truncated race names can be recovered from another supplied source.

## Group 2 — Runner identity and demographics

The next fields to profile are:

- `num`;
- `horse`;
- `age`;
- `sex`;
- `jockey`;
- `trainer`.

In [27]:
# Define the runner identity and demographic field group.
runner_identity_fields = [
    "num",
    "horse",
    "age",
    "sex",
    "jockey",
    "trainer",
]

# Build the same source-quality summary used for the first field group.
runner_identity_profile_rows = []

for field in runner_identity_fields:
    quoted_field = f'"{field}"'

    query = f"""
    SELECT
        COUNT(*) AS total_rows,
        SUM(CASE WHEN {quoted_field} IS NULL THEN 1 ELSE 0 END)
            AS null_count,
        SUM(
            CASE
                WHEN typeof({quoted_field}) = 'text'
                 AND length(trim({quoted_field})) = 0
                THEN 1 ELSE 0
            END
        ) AS blank_text_count,
        COUNT(DISTINCT {quoted_field}) AS distinct_non_null_values,
        SUM(CASE WHEN typeof({quoted_field}) = 'null' THEN 1 ELSE 0 END)
            AS storage_null,
        SUM(CASE WHEN typeof({quoted_field}) = 'integer' THEN 1 ELSE 0 END)
            AS storage_integer,
        SUM(CASE WHEN typeof({quoted_field}) = 'real' THEN 1 ELSE 0 END)
            AS storage_real,
        SUM(CASE WHEN typeof({quoted_field}) = 'text' THEN 1 ELSE 0 END)
            AS storage_text,
        SUM(CASE WHEN typeof({quoted_field}) = 'blob' THEN 1 ELSE 0 END)
            AS storage_blob
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """

    result = pd.read_sql_query(query, connection).iloc[0].to_dict()

    declared_type = source_data_dictionary.loc[
        source_data_dictionary["field_name"] == field,
        "declared_sqlite_type",
    ].iloc[0]

    result["field_name"] = field
    result["declared_sqlite_type"] = declared_type

    runner_identity_profile_rows.append(result)

runner_identity_quality = pd.DataFrame(
    runner_identity_profile_rows
)

runner_identity_quality = runner_identity_quality[
    [
        "field_name",
        "declared_sqlite_type",
        "total_rows",
        "null_count",
        "blank_text_count",
        "distinct_non_null_values",
        "storage_null",
        "storage_integer",
        "storage_real",
        "storage_text",
        "storage_blob",
    ]
]

display(runner_identity_quality)

,field_name,declared_sqlite_type,total_rows,null_count,blank_text_count,distinct_non_null_values,storage_null,storage_integer,storage_real,storage_text,storage_blob
0,num,INTEGER,1851285,0,7032,42,0,1844253,0,7032,0
1,horse,TEXT,1851285,0,0,208631,0,0,0,1851285,0
2,age,INTEGER,1851285,0,0,19,0,1851285,0,0,0
3,sex,TEXT,1851285,0,0,8,0,0,0,1851285,0
4,jockey,TEXT,1851285,0,2,7918,0,0,0,1851285,0
5,trainer,TEXT,1851285,0,9,10709,0,0,0,1851285,0

In [28]:
# Add comparable completeness rates for runner identity fields.
runner_identity_quality_rates = runner_identity_quality.copy()

runner_identity_quality_rates["null_pct"] = (
    runner_identity_quality_rates["null_count"]
    / runner_identity_quality_rates["total_rows"]
    * 100
)

runner_identity_quality_rates["blank_text_pct"] = (
    runner_identity_quality_rates["blank_text_count"]
    / runner_identity_quality_rates["total_rows"]
    * 100
)

runner_identity_quality_rates["populated_rows"] = (
    runner_identity_quality_rates["total_rows"]
    - runner_identity_quality_rates["null_count"]
    - runner_identity_quality_rates["blank_text_count"]
)

runner_identity_quality_rates["populated_pct"] = (
    runner_identity_quality_rates["populated_rows"]
    / runner_identity_quality_rates["total_rows"]
    * 100
)

rate_columns = [
    "field_name",
    "declared_sqlite_type",
    "total_rows",
    "null_count",
    "null_pct",
    "blank_text_count",
    "blank_text_pct",
    "populated_rows",
    "populated_pct",
    "distinct_non_null_values",
    "storage_integer",
    "storage_text",
]

display(
    runner_identity_quality_rates[rate_columns].round(
        {
            "null_pct": 4,
            "blank_text_pct": 4,
            "populated_pct": 4,
        }
    )
)

,field_name,declared_sqlite_type,total_rows,null_count,null_pct,blank_text_count,blank_text_pct,populated_rows,populated_pct,distinct_non_null_values,storage_integer,storage_text
0,num,INTEGER,1851285,0,0.0,7032,0.3798,1844253,99.6202,42,1844253,7032
1,horse,TEXT,1851285,0,0.0,0,0.0000,1851285,100.0000,208631,0,1851285
2,age,INTEGER,1851285,0,0.0,0,0.0000,1851285,100.0000,19,1851285,0
3,sex,TEXT,1851285,0,0.0,0,0.0000,1851285,100.0000,8,0,1851285
4,jockey,TEXT,1851285,0,0.0,2,0.0001,1851283,99.9999,7918,0,1851285
5,trainer,TEXT,1851285,0,0.0,9,0.0005,1851276,99.9995,10709,0,1851285

In [29]:
# Show complete stored-value distributions for age and sex.
#
# These are descriptive source profiles only. No biological or racing-domain
# assumptions are imposed at this stage.

age_distribution = pd.read_sql_query(
    f"""
    SELECT
        age AS stored_value,
        COUNT(*) AS row_count,
        ROUND(
            100.0 * COUNT(*) /
            (
                SELECT COUNT(*)
                FROM data
                WHERE {DATA_ROW_PREDICATE}
            ),
            4
        ) AS row_pct
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY age
    ORDER BY age
    """,
    connection,
)

sex_distribution = pd.read_sql_query(
    f"""
    SELECT
        sex AS stored_value,
        COUNT(*) AS row_count,
        ROUND(
            100.0 * COUNT(*) /
            (
                SELECT COUNT(*)
                FROM data
                WHERE {DATA_ROW_PREDICATE}
            ),
            4
        ) AS row_pct
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY sex
    ORDER BY row_count DESC, sex
    """,
    connection,
)

display(age_distribution)
display(sex_distribution)

    stored_value  row_count  row_pct
0              1          5   0.0003
1              2     180383   9.7437
2              3     400774  21.6484
3              4     342278  18.4887
4              5     299403  16.1727
5              6     231753  12.5185
6              7     161945   8.7477
7              8     105400   5.6933
8              9      64630   3.4911
9             10      35998   1.9445
10            11      17389   0.9393
11            12       7773   0.4199
12            13       2737   0.1478
13            14        658   0.0355
14            15        121   0.0065
15            16         30   0.0016
16            17          5   0.0003
17            18          2   0.0001
18            31          1   0.0001

  stored_value  row_count  row_pct
0            G    1078420  58.2525
1            F     371961  20.0920
2            M     190797  10.3062
3            C     178499   9.6419
4            H      30728   1.6598
5            R        878   0.0474
6            B          1   0.0001
7           BB          1   0.0001

In [30]:
# Inspect rare age and sex values in their full runner and race context.
#
# These values are not classified as errors yet. The purpose is to determine
# whether they are plausible within particular jurisdictions or appear to be
# isolated source defects.

rare_age_sex_rows = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        type,
        age_band,
        sex_rest,
        dist,
        going,
        ran,
        num,
        pos,
        horse,
        age,
        sex,
        jockey,
        trainer
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND (
            age IN (1, 17, 18, 31)
         OR sex IN ('B', 'BB')
      )
    ORDER BY
        age,
        sex,
        date,
        course,
        off,
        pos,
        rowid
    """,
    connection,
)

print(f"Rows with rare age or sex values: {len(rare_age_sex_rows):,}")

with pd.option_context(
    "display.max_rows",
    None,
    "display.max_colwidth",
    120,
):
    display(rare_age_sex_rows)

Rows with rare age or sex values: 15

,source_rowid,date,course,race_id,off,race_name,type,age_band,sex_rest,dist,going,ran,num,pos,horse,age,sex,jockey,trainer
0,528628,2018-04-30,Windsor,698537,5:40,British EBF Novice Stakes (Plus 10 Race),Flat,2yo,,5f,Good,7,2,6,Anthem Of Peace (AUS),1,C,Oisin Murphy,Brian Meehan
1,534896,2018-05-10,Chester,699325,4:05,British Stallion Studs EBF Maiden Stakes (Plus 10 Race),Flat,2yo,,5f,Good,9,1,9,Anthem Of Peace (AUS),1,C,Oisin Murphy,Brian Meehan
2,547934,2018-06-01,Bath,701386,6:20,EBF Novice Stakes,Flat,2yo,,5f,Good,6,2,6,Anthem Of Peace (AUS),1,C,Charles Bishop,Brian Meehan
3,553245,2018-06-10,Goodwood,702154,3:10,Sutton Winson Backing The NSPCC Selling Stakes,Flat,2yo,,5f,Good To Firm,13,1,12,Anthem Of Peace (AUS),1,C,Tom Marquand,Brian Meehan
4,557431,2018-06-18,Windsor,703307,7:00,Sky Bet Best Odds Guaranteed Selling Stakes,Flat,2yo,,6f,Good To Firm,11,1,7,Anthem Of Peace (AUS),1,C,Tom Marquand,Brian Meehan
5,814999,2019-11-29,Gulfstream Park (USA),746195,8:30,Starter Optional Claiming (Claimer) (2yo Fillies) (Turf),Flat,2yo,F,1m,Firm,11,2,7,La Venezolana (VEN),2,B,Jairo Rendon,Rodolfo Garcia
6,448648,2017-10-15,Cologne (GER),687124,1:35,Kolner Steher Cup Der Pferdeklinik Burg () (3yo+) (Turf),Flat,3yo+,,1m7f,Soft,11,10,5,Par Coeur (GER),3,BB,Lukas Delozier,W Mongil
7,880,2015-01-02,Ffos Las,615744,1:10,Radio Carmarthenshire and Scarlet FM Handicap Chase,Chase,5yo+,,3m,Heavy,6,1,CO,Victory Gunner (IRE),17,G,Micheal Nolan,Richard Lee
8,15003,2015-02-16,Lingfield,618067,2:45,888sport.com Handicap Chase,Chase,5yo+,,3m,Heavy,10,1,PU,Victory Gunner (IRE),17,G,Micheal Nolan,Richard Lee
9,913242,2020-10-20,Tipperary (IRE),769812,4:55,Golden Handicap Chase (Div II),Chase,4yo+,,2m4f,Soft To Heavy,9,11,PU,See Double You (IRE),17,G,Sean Flanagan,Ronan M P McNally
10,941054,2020-12-10,Tramore (IRE),773412,3:10,Ladys Cove Handicap Chase,Chase,4yo+,,2m5½f,Heavy,11,11,7,See Double You (IRE),17,G,Darragh OKeeffe,Ronan M P McNally
11,944889,2020-12-18,Navan (IRE),774275,12:00,Happy Christmas And New Year To All Our Members Handicap Chase,Chase,4yo+,,2m4f,Heavy,18,19,PU,See Double You (IRE),17,G,Sean OKeeffe,Ronan M P McNally
12,953748,2021-01-12,Fairyhouse (IRE),775482,3:00,Fairyhouse Committee Handicap Hurdle (Div I),Hurdle,4yo+,,2m4f,Heavy,16,15,8,See Double You (IRE),18,G,B J Foley,Ronan M P McNally
13,1004627,2021-05-04,Ayr,781565,2:55,Visit racingtv.com Handicap Hurdle,Hurdle,4yo+,,3m½f,Good To Soft,12,14,11,See Double You (IRE),18,G,Charlie Price,Ronan M P McNally
14,1543314,2024-07-27,Woodbine (CAN),873561,9:47,Ontario Colleen Stakes (3yo Fillies) (Turf),Flat,3yo,F,1m,Good,12,8,11,Ecstasy (USA),31,M,Fraser Aebly,Sid C Attard

In [31]:
# Compare the rare-value horses with their other records in the source.
#
# This checks whether age and sex values remain consistent across appearances
# or whether the unusual values are isolated within each horse's history.

rare_value_horses = [
    "Anthem Of Peace (AUS)",
    "La Venezolana (VEN)",
    "Par Coeur (GER)",
    "Victory Gunner (IRE)",
    "See Double You (IRE)",
    "Ecstasy (USA)",
]

placeholders = ", ".join("?" for _ in rare_value_horses)

rare_horse_histories = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        age_band,
        sex_rest,
        num,
        pos,
        horse,
        age,
        sex,
        jockey,
        trainer
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND horse IN ({placeholders})
    ORDER BY
        horse,
        date,
        course,
        off,
        rowid
    """,
    connection,
    params=rare_value_horses,
)

rare_horse_summary = (
    rare_horse_histories
    .groupby("horse", as_index=False)
    .agg(
        appearance_count=("source_rowid", "count"),
        first_date=("date", "min"),
        last_date=("date", "max"),
        distinct_ages=("age", lambda values: sorted(set(values))),
        distinct_sex_codes=("sex", lambda values: sorted(set(values))),
    )
)

display(rare_horse_summary)

with pd.option_context(
    "display.max_rows",
    None,
    "display.max_colwidth",
    120,
):
    display(rare_horse_histories)

,horse,appearance_count,first_date,last_date,distinct_ages,distinct_sex_codes
0,Anthem Of Peace (AUS),5,2018-04-30,2018-06-18,[1],[C]
1,Ecstasy (USA),4,2024-07-27,2025-07-26,"[3, 4, 31]","[F, M]"
2,La Venezolana (VEN),1,2019-11-29,2019-11-29,[2],[B]
3,Par Coeur (GER),1,2017-10-15,2017-10-15,[3],[BB]
4,See Double You (IRE),42,2015-11-29,2021-05-04,"[12, 13, 14, 15, 16, 17, 18]",[G]
5,Victory Gunner (IRE),2,2015-01-02,2015-02-16,[17],[G]

,source_rowid,date,course,race_id,off,race_name,age_band,sex_rest,num,pos,horse,age,sex,jockey,trainer
0,528628,2018-04-30,Windsor,698537,5:40,British EBF Novice Stakes (Plus 10 Race),2yo,,2,6,Anthem Of Peace (AUS),1,C,Oisin Murphy,Brian Meehan
1,534896,2018-05-10,Chester,699325,4:05,British Stallion Studs EBF Maiden Stakes (Plus 10 Race),2yo,,1,9,Anthem Of Peace (AUS),1,C,Oisin Murphy,Brian Meehan
2,547934,2018-06-01,Bath,701386,6:20,EBF Novice Stakes,2yo,,2,6,Anthem Of Peace (AUS),1,C,Charles Bishop,Brian Meehan
3,553245,2018-06-10,Goodwood,702154,3:10,Sutton Winson Backing The NSPCC Selling Stakes,2yo,,1,12,Anthem Of Peace (AUS),1,C,Tom Marquand,Brian Meehan
4,557431,2018-06-18,Windsor,703307,7:00,Sky Bet Best Odds Guaranteed Selling Stakes,2yo,,1,7,Anthem Of Peace (AUS),1,C,Tom Marquand,Brian Meehan
5,1543314,2024-07-27,Woodbine (CAN),873561,9:47,Ontario Colleen Stakes (3yo Fillies) (Turf),3yo,F,8,11,Ecstasy (USA),31,M,Fraser Aebly,Sid C Attard
6,1596072,2024-11-09,Woodbine (CAN),881605,9:20,Maple Leaf Stakes (3yo+ Fillies & Mares) (All-Weather Track) (Tapeta),3yo+,F & M,3,7,Ecstasy (USA),3,F,Fraser Aebly,Sid C Attard
7,1702256,2025-07-05,Woodbine (CAN),899417,10:20,Hendrie Stakes (3yo+ Fillies & Mares) (All-Weather Track) (Tapeta),3yo+,F & M,4,7,Ecstasy (USA),4,F,Fraser Aebly,Sid C Attard
8,1711509,2025-07-26,Woodbine (CAN),900447,8:07,Trillium Stakes presented by Don Julio (3yo+ Fillies & Mares) (All-Weather Track) (Tapeta),3yo+,F & M,6,6,Ecstasy (USA),4,F,Fraser Aebly,Sid C Attard
9,814999,2019-11-29,Gulfstream Park (USA),746195,8:30,Starter Optional Claiming (Claimer) (2yo Fillies) (Turf),2yo,F,2,7,La Venezolana (VEN),2,B,Jairo Rendon,Rodolfo Garcia
10,448648,2017-10-15,Cologne (GER),687124,1:35,Kolner Steher Cup Der Pferdeklinik Burg () (3yo+) (Turf),3yo+,,10,5,Par Coeur (GER),3,BB,Lukas Delozier,W Mongil
11,147408,2015-11-29,Fairyhouse (IRE),639860,2:10,Underwriting Exchange Handicap Hurdle,4yo+,,9,18,See Double You (IRE),12,G,Mr R M P McNally,Ronan M P McNally
12,150760,2015-12-10,Punchestown (IRE),640717,3:25,Buy Your Go Racing In Kildare Badge Handicap Hurdle,4yo+,,5,21,See Double You (IRE),12,G,Mr R M P McNally,Ronan M P McNally
13,154211,2015-12-19,Fairyhouse (IRE),641378,2:10,New Years Day Racing At Fairyhouse Handicap Hurdle,4yo+,,2,7,See Double You (IRE),12,G,Mr R M P McNally,Ronan M P McNally
14,162798,2016-01-20,Fairyhouse (IRE),642923,3:35,Your Clubs Fundraiser At Fairyhouse Enquire Today Handicap Hurdle,4yo+,,4,4,See Double You (IRE),13,G,Mr R M P McNally,Ronan M P McNally
15,177694,2016-03-11,Ayr,644298,3:40,All 28 Cheltenham Races On RacingUK Handicap Hurdle (for The James Barclay Challenge Trophy),4yo+,,3,3,See Double You (IRE),13,G,Mr R M P McNally,Ronan M P McNally
16,178616,2016-03-12,Ayr,644316,2:55,AJ Gallagher Private Clients Handicap Hurdle,4yo+,,3,2,See Double You (IRE),13,G,Mr R M P McNally,Ronan M P McNally
17,178712,2016-03-13,Kelso,645794,4:40,Rocky Lions Pride Of Hazelrigg Handicap Hurdle,4yo+,,1,2,See Double You (IRE),13,G,Mr R M P McNally,Ronan M P McNally
18,185337,2016-03-29,Hexham,645550,3:40,Follow Hexham On Facebook Handicap Hurdle,4yo+,,3,1,See Double You (IRE),13,G,Mr R M P McNally,Ronan M P McNally
19,207153,2016-05-14,Bangor-on-Dee,649004,3:40,Bet With CorbettSports Handicap Chase,5yo+,,2,2,See Double You (IRE),13,G,Mr R M P McNally,Ronan M P McNally
20,213619,2016-05-26,Bangor-on-Dee,650131,3:10,Stella Cidre Handicap Chase,5yo+,,2,4,See Double You (IRE),13,G,Mr R M P McNally,Ronan M P McNally
21,225988,2016-06-19,Hexham,652037,3:00,Reef Salon At Ramside Spa Handicap Hurdle,4yo+,,1,4,See Double You (IRE),13,G,Mr R M P McNally,Ronan M P McNally
22,321422,2017-01-16,Ayr,666093,2:10,Dawn Homes Zoopla Peoples Choice Award Handicap Hurdle (Northern Lights Stayers Hurdle Qualifier),4yo+,,4,8,See Double You (IRE),14,G,Mr R M P McNally,Ronan M P McNally
23,331333,2017-02-14,Ayr,667612,3:20,Pay And Watch Racing UK Via Mobile Handicap Hurdle,4yo+,,1,PU,See Double You (IRE),14,G,Mr R M P McNally,Ronan M P McNally
24,340451,2017-03-11,Ayr,668895,3:55,Caledonia Best Handicap Hurdle (for The Craigie Cup),4yo+,,7,PU,See Double You (IRE),14,G,Callum Whillans,Ronan M P McNally
25,347707,2017-03-28,Hexham,670095,3:30,188Bet Handicap Hurdle,4yo+,,4,PU,See Double You (IRE),14,G,Callum Whillans,Ronan M P McNally
26,359414,2017-04-22,Bangor-on-Dee,671706,2:35,Weatherbys General Stud Book Online Handicap Hurdle,4yo+,,9,8,See Double You (IRE),14,G,Alain Cawley,Ronan M P McNally
27,376266,2017-05-23,Hexham,674582,8:20,Hexham Racecourse Caravan Site Handicap Hurdle,4yo+,,1,8,See Double You (IRE),14,G,Mr R M P McNally,Ronan M P McNally
28,382164,2017-06-03,Hexham,677282,5:55,Come Racing On Saturday 17th June Amateur Riders Handicap Hurdle,4yo+,,6,5,See Double You (IRE),14,G,Paul Cawley,Ronan M P McNally
29,389406,2017-06-17,Hexham,679106,5:40,St Martins Care Handicap Chase (Div II),5yo+,,2,3,See Double You (IRE),14,G,Richard Johnson,Ronan M P McNally
30,407875,2017-07-24,Cartmel,680199,3:20,Heart FM Handicap Hurdle,4yo+,,6,2,See Double You (IRE),14,G,Danny Mullins,Ronan M P McNally
31,411911,2017-08-02,Perth,680619,5:10,Pitlochry Golf Handicap Hurdle,4yo+,,6,2,See Double You (IRE),14,G,Mr R M P McNally,Ronan M P McNally
32,419680,2017-08-18,Tramore (IRE),682762,5:35,Tom Murphy Car Sales (Mercedes-Benz) Handicap Chase,4yo+,,6,10,See Double You (IRE),14,G,Danny Mullins,Ronan M P McNally
33,602565,2018-09-17,Hexham,710288,4:30,Watch Live Programming On The ATR App Handicap Chase (Northern Lights Staying Chase Qualifier),4yo+,,9,1,See Double You (IRE),15,G,Brian Hughes,Ronan M P McNally
34,626047,2018-10-29,Ayr,713313,3:15,Book Coral Scottish Grand National Tickets Conditional Jockeys Training Handicap Hurdle,4yo+,,3,5,See Double You (IRE),15,G,Jonjo ONeill Jr,Ronan M P McNally
35,631891,2018-11-09,Hexham,713898,3:45,Racing Partnership Handicap Hurdle,4yo+,,4,8,See Double You (IRE),15,G,Brian Hughes,Ronan M P McNally
36,650673,2018-12-20,Hexham,717153,2:30,Next Meeting Cheltenham Thursday 14th March Handicap Chase,4yo+,,4,2,See Double You (IRE),15,G,Fergus Gregory,Ronan M P McNally
37,664729,2019-01-26,Fairyhouse (IRE),721202,1:00,Bobbyjo Bistro Great Food Great Deals Handicap Chase,5yo+,,13,2,See Double You (IRE),16,G,G B Noonan,Ronan M P McNally
38,665458,2019-01-29,Down Royal (IRE),721634,1:40,Bet 5 Get 30 For All New Customers At BetVictor Handicap Chase,5yo+,,7,2,See Double You (IRE),16,G,Sean Flanagan,Ronan M P McNally
39,667712,2019-02-06,Ayr,720465,4:10,Wine-Dine-Stay At Western House Hotel Handicap Chase,5yo+,,3,3,See Double You (IRE),16,G,Mr E P OBrien,Ronan M P McNally
40,694466,2019-04-11,Limerick (IRE),726969,4:15,Book Online At www.limerickraces.ie Handicap Hurdle,4yo+,,13,5,See Double You (IRE),16,G,Miss M OSullivan,Ronan M P McNally
41,703219,2019-04-27,Wexford (IRE),728551,5:20,Eoin OGorman Solicitors Handicap Chase,5yo+,,7,8,See Double You (IRE),16,G,Shane Shortall,Ronan M P McNally
42,731245,2019-06-15,Downpatrick (IRE),733378,4:50,Tote Supporting Downpatrick Racecourse Handicap Chase,4yo+,,10,3,See Double You (IRE),16,G,Darragh OKeeffe,Ronan M P McNally
43,743597,2019-07-09,Roscommon (IRE),735247,8:30,Leo Dolan Memorial Handicap Hurdle,4yo+,,9,1,See Double You (IRE),16,G,Darragh OKeeffe,Ronan M P McNally
44,747050,2019-07-16,Southwell,734042,6:00,Rotary Foundation End Polio Handicap Chase,5yo+,,8,2,See Double You (IRE),16,G,Aidan Coleman,Ronan M P McNally
45,757270,2019-08-06,Roscommon (IRE),737282,8:10,Michael Holland Tyres Handicap Chase,5yo+,,6,5,See Double You (IRE),16,G,Darragh OKeeffe,Ronan M P McNally
46,771533,2019-09-06,Kilbeggan (IRE),739415,5:50,Devitts And Doheny & Nesbitt Handicap Hurdle,4yo+,,9,PU,See Double You (IRE),16,G,Shane Shortall,Ronan M P McNally
47,783552,2019-09-28,Navan (IRE),740829,2:55,Dun A Ri Blinds Handicap Hurdle,4yo+,,17,15,See Double You (IRE),16,G,Conor McNamara,Ronan M P McNally
48,913242,2020-10-20,Tipperary (IRE),769812,4:55,Golden Handicap Chase (Div II),4yo+,,11,PU,See Double You (IRE),17,G,Sean Flanagan,Ronan M P McNally
49,941054,2020-12-10,Tramore (IRE),773412,3:10,Ladys Cove Handicap Chase,4yo+,,11,7,See Double You (IRE),17,G,Darragh OKeeffe,Ronan M P McNally
50,944889,2020-12-18,Navan (IRE),774275,12:00,Happy Christmas And New Year To All Our Members Handicap Chase,4yo+,,19,PU,See Double You (IRE),17,G,Sean OKeeffe,Ronan M P McNally
51,953748,2021-01-12,Fairyhouse (IRE),775482,3:00,Fairyhouse Committee Handicap Hurdle (Div I),4yo+,,15,8,See Double You (IRE),18,G,B J Foley,Ronan M P McNally
52,1004627,2021-05-04,Ayr,781565,2:55,Visit racingtv.com Handicap Hurdle,4yo+,,14,11,See Double You (IRE),18,G,Charlie Price,Ronan M P McNally
53,880,2015-01-02,Ffos Las,615744,1:10,Radio Carmarthenshire and Scarlet FM Handicap Chase,5yo+,,1,CO,Victory Gunner (IRE),17,G,Micheal Nolan,Richard Lee
54,15003,2015-02-16,Lingfield,618067,2:45,888sport.com Handicap Chase,5yo+,,1,PU,Victory Gunner (IRE),17,G,Micheal Nolan,Richard Lee

In [32]:
# Inspect the rare blank jockey and trainer records.
#
# Because there are only 11 affected rows in total, complete contextual
# inspection is more useful than aggregate profiling.

blank_jockey_trainer_rows = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        type,
        age_band,
        dist,
        going,
        ran,
        num,
        pos,
        horse,
        age,
        sex,
        jockey,
        trainer,
        comment
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND (
            length(trim(jockey)) = 0
         OR length(trim(trainer)) = 0
      )
    ORDER BY
        date,
        course,
        off,
        pos,
        rowid
    """,
    connection,
)

blank_jockey_trainer_summary = pd.DataFrame(
    {
        "condition": [
            "blank jockey",
            "blank trainer",
            "both blank",
        ],
        "row_count": [
            int((blank_jockey_trainer_rows["jockey"].str.strip() == "").sum()),
            int((blank_jockey_trainer_rows["trainer"].str.strip() == "").sum()),
            int(
                (
                    (blank_jockey_trainer_rows["jockey"].str.strip() == "")
                    & (blank_jockey_trainer_rows["trainer"].str.strip() == "")
                ).sum()
            ),
        ],
    }
)

display(blank_jockey_trainer_summary)

with pd.option_context(
    "display.max_rows",
    None,
    "display.max_colwidth",
    120,
):
    display(blank_jockey_trainer_rows)

       condition  row_count
0   blank jockey          2
1  blank trainer          9
2     both blank          0

,source_rowid,date,course,race_id,off,race_name,type,age_band,dist,going,ran,num,pos,horse,age,sex,jockey,trainer,comment
0,50160,2015-05-06,Sonoda (JPN),627438,11:07,Hyogo Championship (Local (Dirt),Flat,3yo,1m1½f,Standard,12,,10,Maximum Kaiser (JPN),3,C,Shoichi Kawahara,,
1,189632,2016-04-08,Auteuil (FR),648524,2:15,Prix Guy Hunault (Hurdle) (Conditions) (5yo) (Turf),Hurdle,5yo,2m2f,Very Soft,12,12,PU,Ahzana (FR),5,M,,L Viel,
2,203870,2016-05-07,Maisons-Laffitte (FR),651027,3:30,Prix de lEtoile dArtois (Handicap) (4yo) (Round) (Turf),Flat,4yo,1m2f,Good,16,9,7,Star White (FR),4,F,Tony Piccone,,
3,203991,2016-05-07,Maisons-Laffitte (FR),651027,3:30,Prix de lEtoile dArtois (Handicap) (4yo) (Round) (Turf),Flat,4yo,1m2f,Good,16,5,12,Colombia DEmra (FR),4,F,Richard Juteau,,
4,599152,2018-09-10,Chantilly (FR),711601,3:30,Prix de Foulangues (Handicap) (4yo+) (Turf),Flat,4yo+,1m1f,Good,18,17,15,Numbers Talk (IRE),10,G,Ronan Thomas,,
5,600778,2018-09-14,Saint-Cloud (FR),712047,3:10,Prix de Lamarque (Handicap) (5yo+) (Turf),Flat,5yo+,1m2½f,Good,18,7,7,Valley Kid (FR),5,H,Michelle Swinnens,,
6,602610,2018-09-17,Maisons-Laffitte (FR),712142,3:55,Prix Du Moulin De Maisons-laffitte (Handicap) (3yo+) (Turf),Flat,3yo+,6f,Good To Soft,15,6,9,Unital (FR),7,G,Tony Piccone,,
7,602570,2018-09-17,Maisons-Laffitte (FR),712151,4:25,Prix de la Porte du Parc (Handicap) (3yo+) (Turf),Flat,3yo+,6f,Good To Soft,15,2,4,Talento (IRE),5,G,Mickael Barzalona,,
8,608243,2018-09-28,Saint-Cloud (FR),713069,3:40,Prix du Lieu Feral (Handicap) (3yo) (Turf),Flat,3yo,1m,Good,16,8,5,Totem (FR),3,G,Mlle Chloe Hue,,
9,608142,2018-09-28,Saint-Cloud (FR),713071,4:10,Prix du Lieu Jourdain (Handicap) (3yo) (Turf),Flat,3yo,1m,Good,16,16,4,Jasmine A La Plage (FR),3,F,Antoine Coutier,,
10,1068784,2021-09-05,Baden-Baden (GER),792961,2:15,149th Wettstar Grosser Preis von Baden (3yo+) (Turf),Flat,3yo+,1m4f,Good To Soft,7,5,PU,Millebosc (FR),3,C,,Mlle Stephanie Nigge,Led - clear when hung right onto outside rail entering back straight - soon headed and lost touch - pulled up before...

In [33]:
# Profile the runner-number field as stored.
#
# The field is declared INTEGER but contains blank text in some rows. This cell
# separates numeric values from blanks and checks whether populated numbers are
# unique within each apparent race.

num_profile = pd.read_sql_query(
    f"""
    SELECT
        MIN(
            CASE
                WHEN typeof(num) = 'integer'
                THEN num
            END
        ) AS minimum_numeric_value,

        MAX(
            CASE
                WHEN typeof(num) = 'integer'
                THEN num
            END
        ) AS maximum_numeric_value,

        COUNT(
            DISTINCT CASE
                WHEN typeof(num) = 'integer'
                THEN num
            END
        ) AS distinct_numeric_values,

        SUM(
            CASE
                WHEN typeof(num) = 'integer'
                 AND num < 0
                THEN 1 ELSE 0
            END
        ) AS negative_value_rows,

        SUM(
            CASE
                WHEN typeof(num) = 'integer'
                 AND num = 0
                THEN 1 ELSE 0
            END
        ) AS zero_value_rows,

        SUM(
            CASE
                WHEN typeof(num) = 'text'
                 AND length(trim(num)) = 0
                THEN 1 ELSE 0
            END
        ) AS blank_value_rows
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

num_distribution = pd.read_sql_query(
    f"""
    SELECT
        CASE
            WHEN typeof(num) = 'text'
             AND length(trim(num)) = 0
            THEN '<blank>'
            ELSE CAST(num AS TEXT)
        END AS stored_value,
        typeof(num) AS sqlite_storage_class,
        COUNT(*) AS row_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY
        stored_value,
        sqlite_storage_class
    ORDER BY
        CASE
            WHEN stored_value = '<blank>' THEN 1
            ELSE 0
        END,
        CAST(stored_value AS INTEGER)
    """,
    connection,
)

num_uniqueness = pd.read_sql_query(
    f"""
    WITH apparent_races AS (
        SELECT
            date,
            course,
            off,
            race_name,
            COUNT(*) AS runner_rows,
            COUNT(
                CASE
                    WHEN typeof(num) = 'integer'
                    THEN 1
                END
            ) AS populated_num_rows,
            COUNT(
                DISTINCT CASE
                    WHEN typeof(num) = 'integer'
                    THEN num
                END
            ) AS distinct_populated_nums
        FROM data
        WHERE {DATA_ROW_PREDICATE}
        GROUP BY
            date,
            course,
            off,
            race_name
    )
    SELECT
        COUNT(*) AS apparent_race_count,

        SUM(
            CASE
                WHEN populated_num_rows > distinct_populated_nums
                THEN 1 ELSE 0
            END
        ) AS races_with_duplicate_populated_nums,

        SUM(
            CASE
                WHEN populated_num_rows < runner_rows
                THEN 1 ELSE 0
            END
        ) AS races_with_blank_nums,

        MAX(populated_num_rows - distinct_populated_nums)
            AS maximum_duplicate_excess
    FROM apparent_races
    """,
    connection,
)

display(num_profile)

with pd.option_context("display.max_rows", None):
    display(num_distribution)

display(num_uniqueness)

,minimum_numeric_value,maximum_numeric_value,distinct_numeric_values,negative_value_rows,zero_value_rows,blank_value_rows
0,0,40,41,0,1179,7032

   stored_value sqlite_storage_class  row_count
0             0              integer       1179
1             1              integer     175522
2             2              integer     176109
3             3              integer     175925
4             4              integer     175151
5             5              integer     171354
6             6              integer     163013
7             7              integer     150581
8             8              integer     134371
9             9              integer     116310
10           10              integer      97714
11           11              integer      80427
12           12              integer      65705
13           13              integer      48164
14           14              integer      38429
15           15              integer      24157
16           16              integer      18470
17           17              integer      10387
18           18              integer       7077
19           19              integer       4100
20           20              integer       3168
21           21              integer       1866
22           22              integer       1438
23           23              integer        995
24           24              integer        755
25           25              integer        536
26           26              integer        371
27           27              integer        271
28           28              integer        227
29           29              integer        158
30           30              integer        118
31           31              integer         58
32           32              integer         37
33           33              integer         25
34           34              integer         24
35           35              integer         15
36           36              integer         11
37           37              integer         11
38           38              integer          8
39           39              integer          8
40           40              integer          8
41      <blank>                 text       7032

,apparent_race_count,races_with_duplicate_populated_nums,races_with_blank_nums,maximum_duplicate_excess
0,189043,539,877,16

In [34]:
# Summarise the main num quality patterns by course and race context.
#
# The aim is to see whether zeroes, blanks, and duplicates are concentrated
# in particular jurisdictions or race types before drawing conclusions.

num_issue_rows = pd.read_sql_query(
    f"""
    WITH duplicate_num_races AS (
        SELECT
            date,
            course,
            off,
            race_name
        FROM data
        WHERE {DATA_ROW_PREDICATE}
          AND typeof(num) = 'integer'
        GROUP BY
            date,
            course,
            off,
            race_name,
            num
        HAVING COUNT(*) > 1
    )
    SELECT
        d.rowid AS source_rowid,
        d.date,
        d.course,
        d.race_id,
        d.off,
        d.race_name,
        d.type,
        d.ran,
        d.num,
        typeof(d.num) AS num_storage_class,
        d.pos,
        d.horse,
        CASE
            WHEN typeof(d.num) = 'text'
             AND length(trim(d.num)) = 0
            THEN 'blank'
            WHEN typeof(d.num) = 'integer'
             AND d.num = 0
            THEN 'zero'
            WHEN EXISTS (
                SELECT 1
                FROM duplicate_num_races AS r
                WHERE r.date = d.date
                  AND r.course = d.course
                  AND r.off = d.off
                  AND r.race_name = d.race_name
            )
            THEN 'race contains duplicate populated num'
            ELSE 'other'
        END AS num_issue_type
    FROM data AS d
    WHERE d.rowid <> 1
      AND (
            (
                typeof(d.num) = 'text'
                AND length(trim(d.num)) = 0
            )
         OR (
                typeof(d.num) = 'integer'
                AND d.num = 0
            )
         OR EXISTS (
                SELECT 1
                FROM duplicate_num_races AS r
                WHERE r.date = d.date
                  AND r.course = d.course
                  AND r.off = d.off
                  AND r.race_name = d.race_name
            )
      )
    """,
    connection,
)

num_issue_summary = (
    num_issue_rows
    .groupby("num_issue_type", as_index=False)
    .agg(
        runner_rows=("source_rowid", "count"),
        apparent_races=(
            "race_id",
            lambda values: values.nunique(),
        ),
        distinct_courses=("course", "nunique"),
    )
    .sort_values(
        "runner_rows",
        ascending=False,
        ignore_index=True,
    )
)

num_issue_top_courses = (
    num_issue_rows
    .groupby(
        ["num_issue_type", "course"],
        as_index=False,
    )
    .agg(
        runner_rows=("source_rowid", "count"),
        apparent_races=("race_id", "nunique"),
    )
    .sort_values(
        ["num_issue_type", "runner_rows", "course"],
        ascending=[True, False, True],
        ignore_index=True,
    )
)

display(num_issue_summary)

for issue_type in num_issue_top_courses["num_issue_type"].unique():
    print(f"\n{issue_type.upper()} — TOP COURSES")
    display(
        num_issue_top_courses.loc[
            num_issue_top_courses["num_issue_type"] == issue_type
        ].head(20)
    )

,num_issue_type,runner_rows,apparent_races,distinct_courses
0,blank,7032,877,142
1,race contains duplicate populated num,4316,362,29
2,zero,1179,186,23

BLANK — TOP COURSES

   num_issue_type                 course  runner_rows  apparent_races
0           blank       Les Landes (JER)         1196             193
1           blank              Ohi (JPN)          416              33
2           blank         Kawasaki (JPN)          229              20
3           blank  Gulfstream Park (USA)          219              26
4           blank        Funabashi (JPN)          193              20
5           blank      Santa Anita (USA)          178              25
6           blank         San Siro (ITY)          174              32
7           blank          Morioka (JPN)          165              15
8           blank         Nakayama (JPN)          154              11
9           blank         Mombetsu (JPN)          146              12
10          blank              Doha (QA)          138              10
11          blank            Urawa (JPN)          129              13
12          blank           Sonoda (JPN)          126              11
13          blank         Ellerslie (NZ)          118               9
14          blank      Baden-Baden (GER)          112              16
15          blank      Hoppegarten (GER)          110              14
16          blank       Capannelle (ITY)          107              18
17          blank          Hanover (GER)          102              13
18          blank            Kyoto (JPN)          101               7
19          blank     Oaklawn Park (USA)           97              12

RACE CONTAINS DUPLICATE POPULATED NUM — TOP COURSES

,num_issue_type,course,runner_rows,apparent_races
142,race contains duplicate populated num,San Isidro (ARG),889,66
143,race contains duplicate populated num,Cidade Jardim (BRZ),668,60
144,race contains duplicate populated num,Gavea (BRZ),588,46
145,race contains duplicate populated num,Palermo (ARG),547,48
146,race contains duplicate populated num,Monterrico (PER),497,40
147,race contains duplicate populated num,Maronas (URU),368,28
148,race contains duplicate populated num,La Plata (ARG),172,12
149,race contains duplicate populated num,Aqueduct (USA),82,11
150,race contains duplicate populated num,Belmont Park (USA),74,8
151,race contains duplicate populated num,Churchill Downs (USA),52,5
152,race contains duplicate populated num,Parx (USA),52,5
153,race contains duplicate populated num,Club Hipico de Santiago (CHI),51,5
154,race contains duplicate populated num,Oaklawn Park (USA),47,4
155,race contains duplicate populated num,Keeneland (USA),45,5
156,race contains duplicate populated num,Meydan (UAE),22,2
157,race contains duplicate populated num,Saratoga (USA),19,2
158,race contains duplicate populated num,Fair Grounds (USA),17,2
159,race contains duplicate populated num,Penn National (USA),16,2
160,race contains duplicate populated num,Deauville (FR),15,1
161,race contains duplicate populated num,Saint-Cloud (FR),13,1

ZERO — TOP COURSES

    num_issue_type                 course  runner_rows  apparent_races
171           zero       Les Landes (JER)          911             139
172           zero       L'Ancresse (GUE)           57              15
173           zero        Caulfield (AUS)           41               4
174           zero                 Chukyo           17               1
175           zero         Mombetsu (JPN)           17               2
176           zero            Kyoto (JPN)           16               1
177           zero      Lyon-La Soie (FR)           16               1
178           zero               Nakayama           16               1
179           zero      Santa Anita (USA)           16               3
180           zero         Saratoga (USA)           16               3
181           zero     Sunland Park (USA)            8               2
182           zero    Cagnes-Sur-Mer (FR)            7               1
183           zero      Baden-Baden (GER)            6               2
184           zero          Del Mar (USA)            6               1
185           zero              Ohi (JPN)            6               2
186           zero    Clairefontaine (FR)            4               1
187           zero     Fair Grounds (USA)            4               1
188           zero  Gulfstream Park (USA)            4               1
189           zero             Nancy (FR)            4               1
190           zero         San Siro (ITY)            4               1

In [35]:
# Profile exact duplicate populated num groups within apparent races.
#
# This identifies how many runners share each duplicated number and provides
# examples. It does not assume whether these represent coupled entries,
# local numbering conventions, or source defects.

duplicate_num_groups = pd.read_sql_query(
    f"""
    SELECT
        date,
        course,
        off,
        race_name,
        num,
        COUNT(*) AS runners_sharing_num,
        GROUP_CONCAT(horse, ' | ') AS horses
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND typeof(num) = 'integer'
    GROUP BY
        date,
        course,
        off,
        race_name,
        num
    HAVING COUNT(*) > 1
    ORDER BY
        runners_sharing_num DESC,
        date,
        course,
        off,
        num
    """,
    connection,
)

duplicate_num_multiplicity = (
    duplicate_num_groups
    .groupby("runners_sharing_num", as_index=False)
    .agg(
        duplicate_number_groups=("num", "count"),
        distinct_apparent_races=(
            "race_name",
            lambda _: 0,
        ),
    )
)

# Recalculate race counts using the full provisional race identity rather
# than race_id, which is not globally reliable.
duplicate_num_multiplicity["distinct_apparent_races"] = [
    duplicate_num_groups.loc[
        duplicate_num_groups["runners_sharing_num"] == multiplicity,
        ["date", "course", "off", "race_name"],
    ].drop_duplicates().shape[0]
    for multiplicity in duplicate_num_multiplicity[
        "runners_sharing_num"
    ]
]

duplicate_num_multiplicity = duplicate_num_multiplicity.sort_values(
    "runners_sharing_num",
    ignore_index=True,
)

print(
    "Exact duplicated num groups: "
    f"{len(duplicate_num_groups):,}"
)
print(
    "Distinct apparent races with duplicated populated num: "
    f"{duplicate_num_groups[['date', 'course', 'off', 'race_name']].drop_duplicates().shape[0]:,}"
)

display(duplicate_num_multiplicity)

with pd.option_context(
    "display.max_rows",
    50,
    "display.max_colwidth",
    140,
):
    display(duplicate_num_groups.head(50))

Exact duplicated num groups: 700
Distinct apparent races with duplicated populated num: 539

    runners_sharing_num  duplicate_number_groups  distinct_apparent_races
0                     2                      488                      339
1                     3                       48                       47
2                     4                       26                       26
3                     5                       29                       29
4                     6                       28                       28
5                     7                       24                       24
6                     8                       23                       23
7                     9                       13                       13
8                    10                       10                       10
9                    11                        5                        5
10                   13                        1                        1
11                   15                        1                        1
12                   16                        3                        3
13                   17                        1                        1

,date,course,off,race_name,num,runners_sharing_num,horses
0,2026-03-21,Chukyo,06:20,Chunichi Sports Sho Falcon Stakes (Turf),0,17,Diamond Knot (JPN) | A Shin Deed (JPN) | Fukuchan Sho (JPN) | Tagano Aralia (JPN) | Vogel (JPN) | Tamamo Icarus (JPN) | Triumph Pass (JP...
1,2016-12-07,Lyon-La Soie (FR),5:10,Prix Du Haras Des Chataigniers (Claimer) (All-Weather),0,16,Absolute Summer (FR) | Miss Charlotte (IRE) | Briseide (IRE) | Txalupa (FR) | National Velvet (FR) | Zahiria (FR) | Highgate (FR) | Marr...
2,2018-11-04,Kyoto (JPN),6:01,JBC Sprint (Local (Dirt),0,16,Graceful Leap (JPN) | Matera Sky (USA) | Kitasan Mikazuki (JPN) | Moanin (USA) | Lets Go Donki (JPN) | Kings Guard (JPN) | T O Helios (U...
3,2026-03-21,Nakayama,06:45,Flower Cup (Fillies) (Turf),0,16,Smart Priere (JPN) | Longing Celine (JPN) | Exceed (JPN) | Ametista (JPN) | Cara Persona (JPN) | Early Harvest (JPN) | Godiamo (JPN) | N...
4,2018-08-16,Mombetsu (JPN),11:07,Breeders Gold Cup (Local (Dirt),0,15,Up To You (JPN) | So This Is Love (JPN) | Cross Wind (JPN) | Noble Sapphire (JPN) | Junaino Kimi (JPN) | Time Beyond (JPN) | Rinehart (J...
5,2015-02-28,Caulfield (AUS),5:35,Crown Golden Ale Peter Young Stakes (Turf),0,13,Mourinho (AUS) | Happy Trails (AUS) | Akzar (IRE) | Spillway (GB) | Au Revoir (IRE) | Protectionist (GER) | Jacquinot Bay (AUS) | Real L...
6,2015-02-28,Caulfield (AUS),3:40,Polytrack Angus Armanasco Stakes (Fillies) (Turf),0,11,Sabatini (AUS) | Fontein Ruby (AUS) | Samartested (AUS) | Bottle Of Smoke (AUS) | Thinking Of You (NZ) | Marple Miss (AUS) | Mossbeat (A...
7,2016-05-15,Les Landes (JER),3:05,Bloodstock Advisory Services Handicap,0,11,Pas DAction (GB) | Valmina (GB) | Tax Reform (IRE) | Spanish Bounty (GB) | Engaging Smile (GB) | Purley Queen (IRE) | Chapeau Bleu (IRE)...
8,2016-10-01,Santa Anita (USA),1:06,Eddie D Stakes (Div II) (3yo+) (Turf),0,11,Holy Lute (USA) | Boozer (USA) | Guns Loaded (USA) | Toowindytohaulrox (USA) | Ohio (BRZ) | Bottle Rocket (USA) | So Sweetitiz (USA) | E...
9,2018-04-22,Les Landes (JER),4:50,The Presidents Handicap,0,11,George Baker (IRE) | Major Tom (GB) | Pas DAction (GB) | Princess Kodia (IRE) | Grey Panel (FR) | Mendacious Harpy (IRE) | House Of Frau...
10,2022-04-18,Les Landes (JER),4:20,La Verte Rue Associates Handicap (Turf),0,11,Vicence (FR) | Arthurs Angel (IRE) | Sumatran Tiger (FR) | Whatzupwithme (GB) | Allegro Jete (FR) | Clear Man (IRE) | Rubeus (IRE) | Har...
11,2016-04-17,Les Landes (JER),4:50,Bloodstock Advisory Services Handicap,0,10,Frankki M (GB) | Larch (IRE) | Wicked Tara (GB) | Lady Petrus (GB) | Carrera (GB) | Fast Freddie (GB) | Ocean Crystal (GB) | Lucifers Sh...
12,2016-05-15,Les Landes (JER),4:15,Plantagenot 1 Mile Handicap,0,10,Bond Mystery (GB) | Rainbow Charlie (GB) | Captain James (FR) | Carrera (GB) | Grey Panel (FR) | First Cat (GB) | Albecq (GB) | Fast Fre...
13,2016-05-30,Les Landes (JER),4:50,The Crawford Family Handicap,0,10,Hawaiian Freeze (GB) | Lady Petrus (GB) | Grey Panel (FR) | Carrera (GB) | Captain James (FR) | Bond Mystery (GB) | Steely (GB) | Frankk...
14,2016-07-01,Les Landes (JER),8:15,La Verte Rue Handicap,0,10,City Ground (USA) | Grey Panel (FR) | Rebel Woman (GB) | Frankki M (GB) | Larch (IRE) | Rainbow Charlie (GB) | Engaging Smile (GB) | Bro...
15,2016-07-24,Les Landes (JER),4:15,Animal Health Trust Celebration Mile (Handicap) (Turf),0,10,Ocean Crystal (GB) | Spanish Bounty (GB) | Fast Freddie (GB) | Hawaiian Freeze (GB) | Brown Velvet (GB) | Grey Panel (FR) | Pas DAction ...
16,2018-08-12,Les Landes (JER),3:40,The Ravenscroft Ladies Day Feature Handicap,0,10,Dancing Dragon (IRE) | National Service (USA) | Koshi (GB) | Beast (GB) | Spring Dixie (IRE) | Molliana (GB) | Kalani Rose (GB) | Grey P...
17,2021-06-25,Les Landes (JER),7:05,Thatchermackenzie Handicap (Turf),0,10,Sky Patrol (IRE) | Lets Go Lucky (GB) | Chapeau Bleu (IRE) | Sing Something (GB) | Ice Royal (IRE) | Man Of The Sea (IRE) | Relaxed Boy ...
18,2021-06-25,Les Landes (JER),8:50,UBS Handicap (Turf),0,10,Snejinska (FR) | Jersey Jack (JER) | Sky Central (GB) | Brown Velvet (GB) | Koshi (GB) | Dark Moonlight (IRE) | Captain James (FR) | Men...
19,2022-04-18,Les Landes (JER),3:40,Mysugarwatch Spring Cup (Conditions Handicap) (Turf),0,10,Relaxed Boy (FR) | Zuhair (GB) | Deverell (GB) | Brown Mouse (IRE) | St Ouen (IRE) | Honcho (IRE) | Cool Dandy (IRE) | Sky Patrol (IRE) ...
20,2024-08-26,Les Landes (JER),4:15,Rubis Channel Islands Handicap (Turf),0,10,Akkeringa (GB) | Zuhair (GB) | Agapanther (GB) | Petite Fiammetta (FR) | Casaruan (GB) | Cueros (IRE) | Chelsea Annie (IRE) | Resilient ...
21,2015-02-28,Caulfield (AUS),2:30,William Hill Zeditave Stakes (Colts & Geldings) (Turf),0,9,Ulmann (AUS) | Setinum (AUS) | Schneller (AUS) | Onerous (AUS) | Armada (AUS) | Rommel (AUS) | Galaxy Pegasus (AUS) | Convincible (AUS) ...
22,2015-08-31,Les Landes (JER),4:50,HSBC Handicap Mile,0,9,Larch (IRE) | Lucifers Shadow (IRE) | First Cat (GB) | Fast Freddie (GB) | Captain James (FR) | Frankki M (GB) | Speedy Writer (GB) | Oc...
23,2016-06-17,Les Landes (JER),8:15,UBS Handicap,0,9,Black Night (IRE) | Grey Panel (FR) | Fast Freddie (GB) | Lucifers Shadow (IRE) | Brown Velvet (GB) | Rainbow Charlie (GB) | Spring Dixi...
24,2016-07-01,Les Landes (JER),8:50,Building A Better Working World Handicap,0,9,Lady Petrus (GB) | Spring Overture (GB) | Major Maximus (GB) | King Kenny (GB) | Black Night (IRE) | Aussie Lyrics (FR) | Zarliman (IRE)...
25,2017-05-14,Les Landes (JER),4:50,Liberation Brewery Handicap (Turf),0,9,Grey Gem (IRE) | Lady Petrus (GB) | Carrera (GB) | Grey Panel (FR) | Ocean Crystal (GB) | Caius College Girl (IRE) | Brown Velvet (GB) |...
26,2017-07-07,Les Landes (JER),8:50,Wilsons Estate Agents Handicap (Turf),0,9,Spring Dixie (IRE) | Bowl Imperior (GB) | Gabster (IRE) | Lady Petrus (GB) | Mr Opulence (GB) | Grey Gem (IRE) | Carrera (GB) | Toretto ...
27,2017-07-23,Les Landes (JER),4:15,Building A Better World Handicap,0,9,Larch (IRE) | Chapeau Bleu (IRE) | Mendacious Harpy (IRE) | Pas DAction (GB) | Hard To Handel (GB) | First Cat (GB) | Brown Velvet (GB) ...
28,2017-07-23,Les Landes (JER),4:50,Animal Health Trust Handicap,0,9,Toretto (IRE) | Blue Sea Of Ibrox (IRE) | Carrera (GB) | Lady Petrus (GB) | Spring Dixie (IRE) | Ocean Crystal (GB) | Hawaiian Freeze (G...
29,2019-06-09,Les Landes (JER),3:05,Brady & Gallagher (1999) Handicap,0,9,White Valiant (FR) | Mrs Burbidge (GB) | Barwick (GB) | Benoordenhout (IRE) | Frivolous Prince (IRE) | Safira Menina (GB) | Winklevi (FR...
30,2019-06-09,Les Landes (JER),4:15,Geoffrey Edwards Memorial Handicap,0,9,Lucifers Shadow (IRE) | Brown Velvet (GB) | Order Of Service (GB) | Salve Helena (IRE) | Chapeau Bleu (IRE) | Ice Royal (IRE) | St Ouen ...
31,2019-07-05,Les Landes (JER),7:05,Millbrook Handicap Sprint (Turf),0,9,Man Of The Sea (IRE) | Relaxed Boy (FR) | Fruit Salad (GB) | Sing Something (GB) | Lady Joanna Vassa (IRE) | Doctor Parkes (GB) | Limeli...
32,2024-09-08,Les Landes (JER),4:50,Fine & Country Handicap (Turf),0,9,Casaruan (GB) | Cool Dandy (IRE) | Akkeringa (GB) | Evening Song (GB) | Zuhair (GB) | Resilient Power (IRE) | Chelsea Annie (IRE) | Neve...
33,2025-05-11,Les Landes (JER),3:40,Brighter Futures 2025 Jersey Guineas (Conditions) (Turf),0,9,Tempus (GB) | Cueros (IRE) | Never Said Nothing (IRE) | Countess Ciara (GB) | Jersey Rocs (IRE) | Arthurs Angel (IRE) | Evening Song (GB...
34,2015-02-28,Caulfield (AUS),3:07,Premier Signs Stakes (Mares) (Turf),0,8,Tycoon Tara (AUS) | Street Allure (AUS) | Winta Chiller (AUS) | Bonaria (AUS) | Bippo No Bungus (AUS) | Precious Gem (AUS) | Girl Guide ...
35,2015-08-31,Les Landes (JER),3:40,Ross-Gower Associates 2015 Clarendon Trophy (Handicap),0,8,Aussie Lyrics (FR) | Wicked Tara (GB) | Herbalist (GB) | King Kenny (GB) | Steely (GB) | Major Maximus (GB) | Rossetti (GB) | River Du N...
36,2016-04-17,Les Landes (JER),3:10,Jersey Bookmakers Handicap,0,8,Chesterslittlegem (IRE) | Country Blue (FR) | Valmina (GB) | Hawaiian Freeze (GB) | Chapeau Bleu (IRE) | Purley Queen (IRE) | Brown Velv...
37,2016-05-15,Les Landes (JER),3:40,El Presidente 2016 Warwick Vase (Handicap),0,8,Spring Dixie (IRE) | Larch (IRE) | Aussie Lyrics (FR) | Steely (GB) | Major Maximus (GB) | Black Night (IRE) | Benoordenhout (IRE) | Eig...
38,2016-05-30,Les Landes (JER),3:00,Geoffrey Edwards Memorial Handicap,0,8,Aussie Lyrics (FR) | Foiled (GB) | Bowl Imperior (GB) | Wicked Tara (GB) | Spring Dixie (IRE) | Black Night (IRE) | Mr Opulence (GB) | K...
39,2016-06-17,Les Landes (JER),8:50,Liberation Brewery Handicap,0,8,Albecq (GB) | Bowl Imperior (GB) | Carrera (GB) | Captain James (FR) | Mr Opulence (GB) | King Kenny (GB) | Spring Overture (GB) | Engag...
40,2016-08-14,Les Landes (JER),4:15,Ladbrokes Ladies Day Handicap,0,8,Rebel Woman (GB) | Engaging Smile (GB) | Frankki M (GB) | Benoordenhout (IRE) | Spring Dixie (IRE) | Lady Petrus (GB) | Captain James (F...
41,2017-04-17,Les Landes (JER),3:40,Millbrook Easter Feature Handicap,0,8,First Cat (GB) | National Service (USA) | Country Blue (FR) | Benoordenhout (IRE) | Brown Velvet (GB) | Princess Kodia (IRE) | My Meteor...
42,2017-04-17,Les Landes (JER),4:15,Trump (Not Him) Holdings Limited Handicap,0,8,Honcho (IRE) | Frankki M (GB) | Gabster (IRE) | Flutterbee (GB) | Alcatraz (IRE) | Hard To Handel (GB) | City Ground (USA) | Grey Panel ...
43,2017-04-17,Les Landes (JER),4:50,Bloodstock Advisory Services Handicap,0,8,Ocean Crystal (GB) | Lucifers Shadow (IRE) | Granny Anne (IRE) | Engaging Smile (GB) | Carrera (GB) | Grey Gem (IRE) | Chesterslittlegem...
44,2017-08-05,Saratoga (USA),11:22,Fasig-Tipton De La Rose Stakes (Fillies & Mares) (Inner Turf),0,8,Proper Discretion (USA) | Thundering Sky (USA) | On Leave (USA) | Bar Of Gold (USA) | Elyseas World (IRE) | Sky My Sky (USA) | Light In ...
45,2017-08-13,Les Landes (JER),4:15,Ladbrokes Ladies Day Handicap,0,8,Blue Sea Of Ibrox (IRE) | Hard To Handel (GB) | Darling Baie (FR) | Gabster (IRE) | Flutterbee (GB) | Cecilator (GB) | Benoordenhout (IR...
46,2018-07-06,Les Landes (JER),7:05,Presidents Handicap (Turf),0,8,National Service (USA) | Rons Ballad (GB) | Frankki M (GB) | Kalani Rose (GB) | Princess Kodia (IRE) | Pas DAction (GB) | Captain James ...
47,2018-08-12,Les Landes (JER),3:05,The Ladbrokes Slots Cash Match Bonus Handicap,0,8,Order Of Service (GB) | Sing Something (GB) | Limelite (IRE) | Al Sail (FR) | Doctor Parkes (GB) | Chapeau Bleu (IRE) | Pas DAction (GB)...
48,2018-08-12,Les Landes (JER),4:15,The Ladbrokes Ladies Day Handicap,0,8,Hawaiian Freeze (GB) | Vexillum (IRE) | Flutterbee (GB) | Princess Kodia (IRE) | Ice Royal (IRE) | Hard To Handel (GB) | Bonjour (IRE) |...
49,2019-04-22,Les Landes (JER),2:30,Koka Fast Handicap Hurdle (Turf),0,8,Barwick (GB) | Veronicas Napkin (IRE) | Bal Amie (FR) | Captain James (FR) | Grey Gem (IRE) | Born Legend (IRE) | Brac Jag (FR) | Steely...

In [36]:
# Separate duplicate positive runner numbers from races where num = 0
# is repeated across multiple runners.
#
# This prevents the zero-code convention from inflating the duplicate-number
# problem and lets us inspect only repeated positive values.

positive_duplicate_num_groups = pd.read_sql_query(
    f"""
    SELECT
        date,
        course,
        off,
        race_name,
        num,
        COUNT(*) AS runners_sharing_num,
        GROUP_CONCAT(horse, ' | ') AS horses
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND typeof(num) = 'integer'
      AND num > 0
    GROUP BY
        date,
        course,
        off,
        race_name,
        num
    HAVING COUNT(*) > 1
    ORDER BY
        runners_sharing_num DESC,
        date,
        course,
        off,
        num
    """,
    connection,
)

positive_duplicate_summary = pd.DataFrame(
    {
        "measure": [
            "duplicate positive num groups",
            "distinct apparent races affected",
            "distinct courses affected",
            "maximum runners sharing one positive num",
        ],
        "value": [
            len(positive_duplicate_num_groups),
            positive_duplicate_num_groups[
                ["date", "course", "off", "race_name"]
            ].drop_duplicates().shape[0],
            positive_duplicate_num_groups["course"].nunique(),
            (
                int(
                    positive_duplicate_num_groups[
                        "runners_sharing_num"
                    ].max()
                )
                if not positive_duplicate_num_groups.empty
                else 0
            ),
        ],
    }
)

positive_duplicate_top_courses = (
    positive_duplicate_num_groups
    .groupby("course", as_index=False)
    .agg(
        duplicate_groups=("num", "count"),
        apparent_races=(
            "race_name",
            lambda _: 0,
        ),
    )
)

positive_duplicate_top_courses["apparent_races"] = [
    positive_duplicate_num_groups.loc[
        positive_duplicate_num_groups["course"] == course,
        ["date", "course", "off", "race_name"],
    ].drop_duplicates().shape[0]
    for course in positive_duplicate_top_courses["course"]
]

positive_duplicate_top_courses = (
    positive_duplicate_top_courses
    .sort_values(
        ["duplicate_groups", "course"],
        ascending=[False, True],
        ignore_index=True,
    )
)

display(positive_duplicate_summary)
display(positive_duplicate_top_courses.head(30))

with pd.option_context(
    "display.max_rows",
    50,
    "display.max_colwidth",
    140,
):
    display(positive_duplicate_num_groups.head(50))

                                    measure  value
0             duplicate positive num groups    523
1          distinct apparent races affected    362
2                 distinct courses affected     29
3  maximum runners sharing one positive num      4

                           course  duplicate_groups  apparent_races
0                San Isidro (ARG)               109              66
1             Cidade Jardim (BRZ)                90              60
2                     Gavea (BRZ)                77              46
3                Monterrico (PER)                71              40
4                   Palermo (ARG)                54              48
5                   Maronas (URU)                34              28
6                  La Plata (ARG)                21              12
7                  Aqueduct (USA)                12              11
8              Belmont Park (USA)                 8               8
9   Club Hipico de Santiago (CHI)                 6               5
10             Oaklawn Park (USA)                 6               4
11          Churchill Downs (USA)                 5               5
12                Keeneland (USA)                 5               5
13                     Parx (USA)                 5               5
14             Fair Grounds (USA)                 3               2
15                   Meydan (UAE)                 2               2
16            Penn National (USA)                 2               2
17                 Saratoga (USA)                 2               2
18                   Auteuil (FR)                 1               1
19                        Bahrain                 1               1
20                 Chantilly (FR)                 1               1
21                 Deauville (FR)                 1               1
22                  Del Mar (USA)                 1               1
23            Delaware Park (USA)                 1               1
24               Ellis Park (USA)                 1               1
25              Happy Valley (HK)                 1               1
26       Presque Isle Downs (USA)                 1               1
27               Saint-Cloud (FR)                 1               1
28              Thistledown (USA)                 1               1

,date,course,off,race_name,num,runners_sharing_num,horses
0,2018-12-08,San Isidro (ARG),9:55,Copa de Plata (3yo+ Fillies & Mares) (Turf),11,4,London Show (URU) | Litle Eatly (BRZ) | Mendel Sweet (BRZ) | Linda Le (BRZ)
1,2015-01-11,Monterrico (PER),10:25,Premio Enrique Meiggs (3yo+) (Dirt),10,3,Good Luck Keny (ARG) | Sweet Cazanova (ARG) | Mr. Rodrigo (CHI)
2,2015-03-07,Aqueduct (USA),9:50,Gotham Stakes (3yo) (Dirt),1,3,Dontbetwithbruno (USA) | Uninfluenced (USA) | Blame Jim (USA)
3,2015-07-05,Club Hipico de Santiago (CHI),8:35,Premio Arturo Lyon P (3yo Fillies) (Turf),2,3,Superdotada (CHI) | Kitcat (CHI) | Cimalta (CHI)
4,2015-08-02,Club Hipico de Santiago (CHI),8:35,Premio Polla de Potrancas (3yo Fillies) (Turf),3,3,Cimalta (CHI) | Wapi (CHI) | Kitcat (CHI)
5,2015-09-06,Monterrico (PER),10:50,Premio Polla de Potrillos - Roberto Alvarez Calderon Rey (3yo Colts & Geldings) (Dirt),3,3,Mr Inspiration (ARG) | Abueyo (ARG) | Street Lolo (ARG)
6,2015-10-04,Monterrico (PER),10:55,Ricardo Ortiz de Zevallos (3yo) (Dirt),2,3,Street Lolo (ARG) | Indio Dakota (ARG) | Abueyo (ARG)
7,2015-11-08,Monterrico (PER),10:35,Derby Nacional (3yo) (Dirt),9,3,Mr. Omar (CHI) | La Candy (PER) | Rubirosa (PER)
8,2015-11-08,Monterrico (PER),10:35,Derby Nacional (3yo) (Dirt),10,3,Street Lolo (ARG) | Blue Demon (ARG) | Mr. Leguia (PER)
9,2015-11-14,San Isidro (ARG),8:25,Premio Enrique Acebal (3yo Fillies) (Turf),5,3,Quatro Folhas (ARG) | Valencia (ARG) | Feet First (ARG)
10,2015-12-06,Club Hipico de Santiago (CHI),9:58,Las Oaks (3yo Fillies) (Turf),2,3,Wapi (CHI) | Bauxita (CHI) | Kitcat (CHI)
11,2015-12-12,San Isidro (ARG),10:25,Gran Premio Felix de Alzaga Unzue (3yo+) (Turf),3,3,Forza Key (ARG) | Compadron Key (ARG) | Emocion Key (ARG)
12,2015-12-13,Monterrico (PER),9:55,Gran Premio Nacional Augusto B. Leguia (3yo) (Turf),4,3,Ivo (PER) | Mr. Omar (CHI) | Rubirosa (PER)
13,2016-03-19,Oaklawn Park (USA),9:57,Razorback Handicap (4yo+) (Dirt),1,3,La Macchina (USA) | Looks To Spare (USA) | Incremental (USA)
14,2016-10-08,San Isidro (ARG),8:20,Gran Premio Suipacha (3yo+) (Turf),1,3,Forza Key (ARG) | Compadron Key (ARG) | Che Patron Key (ARG)
15,2017-01-06,Maronas (URU),7:25,Gran Premio Ciudad de Montevideo - Presidente Jorge Batlle (3yo+ Fillies & Mares) (Dirt),1,3,Jump Lady (BRZ) | Jazz Band (BRZ) | Financial Aid (URU)
16,2017-05-01,Palermo (ARG),10:20,Gran Premio Republica Argentina (3yo+) (Dirt),3,3,Snow Lion (ARG) | Igual A Mi (ARG) | Emerging Talent (ARG)
17,2017-06-24,Thistledown (USA),10:30,Ohio Derby (3yo) (Dirt),1,3,Game Over (USA) | Talk Less (USA) | Vibe (USA)
18,2017-09-24,La Plata (ARG),10:05,Seleccion de Potrancas (3yo Fillies) (Dirt),3,3,Roman Shiner (ARG) | Halo Holiday (ARG) | Marquesa Nistel (ARG)
19,2017-10-14,San Isidro (ARG),8:00,Gran Premio Suipacha (3yo+) (Turf),7,3,Sunny Point (ARG) | Ultra Urbano (ARG) | Prime Prize (ARG)
20,2017-11-04,San Isidro (ARG),9:35,Gran Premio Enrique Acebal (3yo Fillies) (Turf),6,3,Luna Inc (ARG) | Rockanrolera Inc (ARG) | Pure Sexista (ARG)
21,2017-12-10,Monterrico (PER),10:20,Gran Premio Nacional Augusto B. Leguia (3yo) (Turf),3,3,Nochero Bueno (ARG) | After All (CHI) | Mr Bailetti (ARG)
22,2017-12-16,San Isidro (ARG),7:15,Gran Premio Felix de Alzaga Unzue (3yo+) (Turf),6,3,Nashville Texan (ARG) | Happy Roman (ARG) | Moeche (ARG)
23,2020-12-19,San Isidro (ARG),7:30,Gran Premio Copa de Plata - Roberto Vazquez Mansilla (3yo+ Fillies & Mares) (Round) (Turf),2,3,Blue Stripe (ARG) | Henestrosa (ARG) | Serenata Huasteca (ARG)
24,2021-09-12,Monterrico (PER),10:40,Premio Polla de Potrillos - Roberto Alvarez Calderon Rey (3yo) (Dirt),7,3,Eliitas (ARG) | Super Rafito (ARG) | Papa Chocho (PER)
25,2021-10-10,Monterrico (PER),10:30,Premio Ricardo Ortiz de Zevallos (2-3yo Colts) (Dirt),7,3,Eliitas (ARG) | Forever Estreli (USA) | Super Rafito (ARG)
26,2021-11-19,La Plata (ARG),8:00,Gran Premio Joaquin V Gonzalez (3yo+) (Dirt),12,3,Aspavento (ARG) | Storm Dynamico (ARG) | Hatim (ARG)
27,2021-11-21,Monterrico (PER),9:55,Derby Nacional (3yo) (Dirt),5,3,Forever Estreli (USA) | Eliitas (ARG) | El Gran Quintero (ARG)
28,2022-01-06,Maronas (URU),11:40,Gran Premio Jose Pedro Ramirez (3yo+) (Dirt),1,3,On The Flood (URU) | Olimpo Mt (URU) | Pingo (URU)
29,2022-09-04,Monterrico (PER),10:45,Premio Polla de Potrancas (2-3yo Fillies) (Dirt),11,3,La Pampera (PER) | Abu Eva (PER) | Mama Nanzy (ARG)
30,2022-09-05,Maronas (URU),12:10,Gran Premio Polla de Potrillos (Local (3yo Colts & Geldings) (Dirt),1,3,Quixote (URU) | Quentin Tarantino (URU) | Quesadilha (URU)
31,2022-09-11,Monterrico (PER),10:55,Premio Polla de Potrillos (3yo Colts & Geldings) (Dirt),9,3,Faruk (PER) | Avispado (PER) | Mercyful Fate (PER)
32,2022-10-01,Monterrico (PER),10:45,Premio Enrique Ayulo Pardo (3yo Fillies) (Dirt),5,3,Morena Luna (ARG) | Capa Soy (ARG) | Sugar Fix (PER)
33,2022-10-02,Maronas (URU),11:00,Gran Premio Jockey Club (Local (3yo) (Dirt),1,3,Quentin Tarantino (URU) | Quixote (URU) | Quesadilha (URU)
34,2023-12-16,San Isidro (ARG),10:15,Gran Premio Carlos Pellegrini Internacional (3yo+) (Round) (Turf),5,3,Jazz Seiver (ARG) | Natan (ARG) | Happy Happy Day (ARG)
35,2023-12-16,San Isidro (ARG),8:45,Gran Premio Copa de Plata Roberto Vazquez Mansilla Internacional (3yo+ F & M) (Rnd) (Turf),5,3,Esnara (ARG) | Punta Turquesa (ARG) | Nanda Dea (ARG)
36,2024-05-25,San Isidro (ARG),8:40,Gran Premio Gran Criterium (2yo Colts) (Round) (Turf),4,3,Es Mio (ARG) | Ruso Real (ARG) | Mago Beto (ARG)
37,2015-01-01,Aqueduct (USA),6:20,Affectionately Stakes () (4yo+ Fillies & Mares) (Dirt),1,2,Simply Spectacular (USA) | Mylitta (USA)
38,2015-01-01,Aqueduct (USA),6:20,Affectionately Stakes () (4yo+ Fillies & Mares) (Dirt),2,2,Penwith (USA) | Divided Attention (USA)
39,2015-01-03,Palermo (ARG),8:45,Clasico Apertura (3yo+ Fillies & Mares) (Turf),2,2,La Lugones (ARG) | Belle Saison (ARG)
40,2015-01-06,Maronas (URU),10:45,Gran Premio Jose Pedro Ramirez (3yo+) (Dirt),1,2,Hielo (BRZ) | All Saints (BRZ)
41,2015-01-06,Maronas (URU),10:45,Gran Premio Jose Pedro Ramirez (3yo+) (Dirt),2,2,Imperrito (URU) | Fletcher (URU)
42,2015-01-16,Aqueduct (USA),8:48,Busanda Stakes () (3yo Fillies) (Dirt),1,2,Bonnet Plume (USA) | Been Here Before (USA)
43,2015-01-20,Gavea (BRZ),7:15,Grande Premio Estado do Rio de Janeiro (3yo) (Turf),2,2,Oregon Pine (BRZ) | Paint Naif (BRZ)
44,2015-01-20,Gavea (BRZ),7:15,Grande Premio Estado do Rio de Janeiro (3yo) (Turf),3,2,Caballo De Hierro (BRZ) | Universal Law (BRZ)
45,2015-01-20,Gavea (BRZ),8:15,Grande Premio Henrique Possollo (3yo Fillies) (Turf),4,2,Energia Galileo (BRZ) | Energia Garoa (BRZ)
46,2015-01-20,Gavea (BRZ),8:15,Grande Premio Henrique Possollo (3yo Fillies) (Turf),7,2,Dignaty (BRZ) | Darin (BRZ)
47,2015-01-20,Gavea (BRZ),8:15,Grande Premio Henrique Possollo (3yo Fillies) (Turf),11,2,Cacarola (BRZ) | Colorado Girl (BRZ)
48,2015-01-20,Gavea (BRZ),8:15,Grande Premio Henrique Possollo (3yo Fillies) (Turf),13,2,Rosa Brava (BRZ) | Leading Hat (BRZ)
49,2015-01-25,Cidade Jardim (BRZ),7:15,Grande Premio 25 de Janeiro (3yo+ Fillies & Mares) (Dirt),1,2,Moving Along (BRZ) | Letra De Samba (BRZ)

In [37]:
# Profile runner and participant names exactly as stored.
#
# This cell does not standardise punctuation, split names permanently,
# or attempt entity resolution.

name_field_profile = pd.read_sql_query(
    f"""
    SELECT
        MIN(length(horse)) AS horse_min_length,
        MAX(length(horse)) AS horse_max_length,
        ROUND(AVG(length(horse)), 2) AS horse_avg_length,
        SUM(CASE WHEN horse <> trim(horse) THEN 1 ELSE 0 END)
            AS horse_outer_whitespace_rows,

        MIN(length(jockey)) AS jockey_min_length,
        MAX(length(jockey)) AS jockey_max_length,
        ROUND(AVG(length(jockey)), 2) AS jockey_avg_length,
        SUM(CASE WHEN jockey <> trim(jockey) THEN 1 ELSE 0 END)
            AS jockey_outer_whitespace_rows,

        MIN(length(trainer)) AS trainer_min_length,
        MAX(length(trainer)) AS trainer_max_length,
        ROUND(AVG(length(trainer)), 2) AS trainer_avg_length,
        SUM(CASE WHEN trainer <> trim(trainer) THEN 1 ELSE 0 END)
            AS trainer_outer_whitespace_rows
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

# Load distinct horse names only, then inspect terminal parenthesised suffixes
# in Python because SQLite has no built-in reverse-string function.
distinct_horse_names = pd.read_sql_query(
    f"""
    SELECT DISTINCT horse
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    ORDER BY horse
    """,
    connection,
)["horse"]

horse_suffix_counts = Counter()

for horse_name in distinct_horse_names:
    match = re.search(r"\(([^()]*)\)$", horse_name)

    if match:
        horse_suffix_counts[match.group(1)] += 1
    else:
        horse_suffix_counts["<no terminal parenthesis>"] += 1

horse_suffix_profile = pd.DataFrame(
    [
        {
            "apparent_suffix": suffix,
            "distinct_horse_names": count,
        }
        for suffix, count in horse_suffix_counts.items()
    ]
).sort_values(
    ["distinct_horse_names", "apparent_suffix"],
    ascending=[False, True],
    ignore_index=True,
)

display(name_field_profile)
display(horse_suffix_profile.head(50))

,horse_min_length,horse_max_length,horse_avg_length,horse_outer_whitespace_rows,jockey_min_length,jockey_max_length,jockey_avg_length,jockey_outer_whitespace_rows,trainer_min_length,trainer_max_length,trainer_avg_length,trainer_outer_whitespace_rows
0,7,26,16.85,0,0,33,12.95,0,0,39,12.86,0

   apparent_suffix  distinct_horse_names
0              IRE                 70682
1               GB                 41810
2               FR                 36245
3              USA                 21854
4              AUS                 14132
5              JPN                  5993
6               NZ                  3802
7              GER                  2967
8              SAF                  2575
9              ARG                  2480
10             BRZ                  1814
11             CHI                  1203
12             CAN                   899
13             PER                   425
14             URU                   359
15             ITY                   353
16             TUR                   238
17             SPA                   117
18             KSA                    98
19             BHR                    94
20             SWE                    82
21             CZE                    55
22             DEN                    53
23             SWI                    50
24             KOR                    48
25             POL                    39
26              GR                    23
27             BEL                    16
28              QA                    15
29             MOR                    13
30             NOR                    13
31             AUT                    12
32             HUN                    12
33             UAE                     8
34             HOL                     7
35             SLO                     7
36             MEX                     6
37             RUS                     5
38             UKR                     4
39             VEN                     4
40             IND                     3
41             POR                     3
42             AZE                     2
43             BUL                     2
44             CRO                     2
45             SER                     2
46             ALG                     1
47             ECU                     1
48             JER                     1
49             TUN                     1

In [38]:
# Inspect horse-name suffix coverage and uncommon terminal fragments.
#
# This remains a text-structure investigation. It does not assign countries
# or create a permanent horse identifier.

horse_suffix_summary = pd.DataFrame(
    {
        "measure": [
            "distinct horse names",
            "with terminal parenthesised suffix",
            "without terminal parenthesised suffix",
            "distinct terminal suffixes",
        ],
        "value": [
            len(distinct_horse_names),
            int(
                horse_suffix_profile.loc[
                    horse_suffix_profile["apparent_suffix"]
                    != "<no terminal parenthesis>",
                    "distinct_horse_names",
                ].sum()
            ),
            int(
                horse_suffix_profile.loc[
                    horse_suffix_profile["apparent_suffix"]
                    == "<no terminal parenthesis>",
                    "distinct_horse_names",
                ].sum()
            ),
            int(
                (
                    horse_suffix_profile["apparent_suffix"]
                    != "<no terminal parenthesis>"
                ).sum()
            ),
        ],
    }
)

horse_names_without_suffix = pd.DataFrame(
    {
        "horse": [
            horse_name
            for horse_name in distinct_horse_names
            if re.search(r"\(([^()]*)\)$", horse_name) is None
        ]
    }
)

rare_horse_suffixes = horse_suffix_profile.loc[
    horse_suffix_profile["distinct_horse_names"] <= 10
].copy()

display(horse_suffix_summary)

print(
    "Examples without terminal parenthesised suffix: "
    f"{min(50, len(horse_names_without_suffix)):,}"
)
display(horse_names_without_suffix.head(50))

with pd.option_context("display.max_rows", None):
    display(rare_horse_suffixes)

                                 measure   value
0                   distinct horse names  208631
1     with terminal parenthesised suffix  208631
2  without terminal parenthesised suffix       0
3             distinct terminal suffixes      51

Examples without terminal parenthesised suffix: 0

Empty DataFrame
Columns: [horse]
Index: []

   apparent_suffix  distinct_horse_names
33             UAE                     8
34             HOL                     7
35             SLO                     7
36             MEX                     6
37             RUS                     5
38             UKR                     4
39             VEN                     4
40             IND                     3
41             POR                     3
42             AZE                     2
43             BUL                     2
44             CRO                     2
45             SER                     2
46             ALG                     1
47             ECU                     1
48             JER                     1
49             TUN                     1
50             ZIM                     1

In [39]:
# Examine horse names after temporarily separating the terminal suffix.
#
# This is an exploratory text profile only. It does not create permanent
# horse identifiers or assume that equal base names refer to the same horse.

horse_name_parts = pd.DataFrame(
    {
        "stored_horse_name": distinct_horse_names,
    }
)

horse_name_parts[["base_name", "apparent_suffix"]] = (
    horse_name_parts["stored_horse_name"]
    .str.extract(r"^(.*) \(([^()]*)\)$")
)

horse_base_name_summary = pd.DataFrame(
    {
        "measure": [
            "distinct stored horse names",
            "distinct base names",
            "base names used with multiple suffixes",
            "maximum suffixes for one base name",
        ],
        "value": [
            len(horse_name_parts),
            horse_name_parts["base_name"].nunique(),
            int(
                (
                    horse_name_parts
                    .groupby("base_name")["apparent_suffix"]
                    .nunique()
                    > 1
                ).sum()
            ),
            int(
                horse_name_parts
                .groupby("base_name")["apparent_suffix"]
                .nunique()
                .max()
            ),
        ],
    }
)

horse_base_suffix_variants = (
    horse_name_parts
    .groupby("base_name", as_index=False)
    .agg(
        distinct_suffixes=("apparent_suffix", "nunique"),
        suffixes=(
            "apparent_suffix",
            lambda values: " | ".join(sorted(set(values))),
        ),
        stored_names=(
            "stored_horse_name",
            lambda values: " | ".join(sorted(set(values))),
        ),
    )
)

horse_base_suffix_variants = (
    horse_base_suffix_variants.loc[
        horse_base_suffix_variants["distinct_suffixes"] > 1
    ]
    .sort_values(
        ["distinct_suffixes", "base_name"],
        ascending=[False, True],
        ignore_index=True,
    )
)

display(horse_base_name_summary)

print(
    "Examples of base names occurring with multiple suffixes: "
    f"{min(50, len(horse_base_suffix_variants)):,}"
)

with pd.option_context(
    "display.max_rows",
    50,
    "display.max_colwidth",
    160,
):
    display(horse_base_suffix_variants.head(50))

                                  measure   value
0             distinct stored horse names  208631
1                     distinct base names  200156
2  base names used with multiple suffixes    7635
3      maximum suffixes for one base name       5

Examples of base names occurring with multiple suffixes: 50

,base_name,distinct_suffixes,suffixes,stored_names
0,Draco,5,AUS | FR | GB | URU | USA,Draco (AUS) | Draco (FR) | Draco (GB) | Draco (URU) | Draco (USA)
1,Earthquake,5,AUS | BRZ | FR | GB | USA,Earthquake (AUS) | Earthquake (BRZ) | Earthquake (FR) | Earthquake (GB) | Earthquake (USA)
2,Gold Standard,5,AUS | FR | IRE | SAF | USA,Gold Standard (AUS) | Gold Standard (FR) | Gold Standard (IRE) | Gold Standard (SAF) | Gold Standard (USA)
3,Hall Of Fame,5,AUS | FR | IRE | SWE | USA,Hall Of Fame (AUS) | Hall Of Fame (FR) | Hall Of Fame (IRE) | Hall Of Fame (SWE) | Hall Of Fame (USA)
4,Liberty Island,5,AUS | GER | IRE | JPN | USA,Liberty Island (AUS) | Liberty Island (GER) | Liberty Island (IRE) | Liberty Island (JPN) | Liberty Island (USA)
5,Maximus,5,AUS | FR | GER | PER | USA,Maximus (AUS) | Maximus (FR) | Maximus (GER) | Maximus (PER) | Maximus (USA)
6,Moana,5,FR | GB | JPN | NZ | USA,Moana (FR) | Moana (GB) | Moana (JPN) | Moana (NZ) | Moana (USA)
7,Overlord,5,ARG | AUS | FR | GB | TUR,Overlord (ARG) | Overlord (AUS) | Overlord (FR) | Overlord (GB) | Overlord (TUR)
8,Raphael,5,AUS | FR | GER | NZ | USA,Raphael (AUS) | Raphael (FR) | Raphael (GER) | Raphael (NZ) | Raphael (USA)
9,Samoa,5,FR | GER | PER | SAF | USA,Samoa (FR) | Samoa (GER) | Samoa (PER) | Samoa (SAF) | Samoa (USA)
10,Tyson,5,BRZ | FR | GER | IRE | USA,Tyson (BRZ) | Tyson (FR) | Tyson (GER) | Tyson (IRE) | Tyson (USA)
11,Aftermath,4,AUS | IRE | NZ | USA,Aftermath (AUS) | Aftermath (IRE) | Aftermath (NZ) | Aftermath (USA)
12,Agreeable,4,ARG | AUS | IRE | USA,Agreeable (ARG) | Agreeable (AUS) | Agreeable (IRE) | Agreeable (USA)
13,Alaskan,4,AUS | IRE | NZ | USA,Alaskan (AUS) | Alaskan (IRE) | Alaskan (NZ) | Alaskan (USA)
14,American Star,4,AUS | FR | IRE | JPN,American Star (AUS) | American Star (FR) | American Star (IRE) | American Star (JPN)
15,Amigo,4,AUS | FR | GER | USA,Amigo (AUS) | Amigo (FR) | Amigo (GER) | Amigo (USA)
16,Amsterdam,4,BRZ | GB | GER | SAF,Amsterdam (BRZ) | Amsterdam (GB) | Amsterdam (GER) | Amsterdam (SAF)
17,Arizona,4,CAN | FR | GER | IRE,Arizona (CAN) | Arizona (FR) | Arizona (GER) | Arizona (IRE)
18,Athena,4,AUS | GER | IRE | USA,Athena (AUS) | Athena (GER) | Athena (IRE) | Athena (USA)
19,Bad Boy,4,AUS | FR | JPN | USA,Bad Boy (AUS) | Bad Boy (FR) | Bad Boy (JPN) | Bad Boy (USA)
20,Bella Ciao,4,FR | GB | URU | USA,Bella Ciao (FR) | Bella Ciao (GB) | Bella Ciao (URU) | Bella Ciao (USA)
21,Better And Better,4,ARG | AUS | IRE | USA,Better And Better (ARG) | Better And Better (AUS) | Better And Better (IRE) | Better And Better (USA)
22,Brutus,4,BRZ | CAN | FR | JPN,Brutus (BRZ) | Brutus (CAN) | Brutus (FR) | Brutus (JPN)
23,Casino Queen,4,IRE | JPN | SAF | USA,Casino Queen (IRE) | Casino Queen (JPN) | Casino Queen (SAF) | Casino Queen (USA)
24,Destin,4,AUS | CHI | FR | USA,Destin (AUS) | Destin (CHI) | Destin (FR) | Destin (USA)
25,Elliptical,4,ARG | AUS | GB | IRE,Elliptical (ARG) | Elliptical (AUS) | Elliptical (GB) | Elliptical (IRE)
26,Emerald Bay,4,AUS | GB | IRE | USA,Emerald Bay (AUS) | Emerald Bay (GB) | Emerald Bay (IRE) | Emerald Bay (USA)
27,English,4,AUS | FR | GB | USA,English (AUS) | English (FR) | English (GB) | English (USA)
28,Fearless,4,AUS | FR | IRE | USA,Fearless (AUS) | Fearless (FR) | Fearless (IRE) | Fearless (USA)
29,Fletcher,4,GB | IRE | URU | USA,Fletcher (GB) | Fletcher (IRE) | Fletcher (URU) | Fletcher (USA)
30,Follow Me,4,AUS | FR | IRE | SAF,Follow Me (AUS) | Follow Me (FR) | Follow Me (IRE) | Follow Me (SAF)
31,Forte,4,GB | JPN | NZ | USA,Forte (GB) | Forte (JPN) | Forte (NZ) | Forte (USA)
32,Furioso,4,FR | GER | NZ | SPA,Furioso (FR) | Furioso (GER) | Furioso (NZ) | Furioso (SPA)
33,Gambler,4,AUS | FR | JPN | USA,Gambler (AUS) | Gambler (FR) | Gambler (JPN) | Gambler (USA)
34,Good Fortune,4,DEN | FR | GB | NZ,Good Fortune (DEN) | Good Fortune (FR) | Good Fortune (GB) | Good Fortune (NZ)
35,Happy Angel,4,ARG | FR | IRE | JPN,Happy Angel (ARG) | Happy Angel (FR) | Happy Angel (IRE) | Happy Angel (JPN)
36,Harvest Moon,4,AUS | GB | JPN | USA,Harvest Moon (AUS) | Harvest Moon (GB) | Harvest Moon (JPN) | Harvest Moon (USA)
37,Ikigai,4,FR | GB | SAF | USA,Ikigai (FR) | Ikigai (GB) | Ikigai (SAF) | Ikigai (USA)
38,Invader,4,AUS | BRZ | FR | USA,Invader (AUS) | Invader (BRZ) | Invader (FR) | Invader (USA)
39,Istanbul,4,AUS | BHR | FR | IRE,Istanbul (AUS) | Istanbul (BHR) | Istanbul (FR) | Istanbul (IRE)
40,King David,4,BRZ | DEN | FR | IRE,King David (BRZ) | King David (DEN) | King David (FR) | King David (IRE)
41,London,4,FR | GER | QA | SAF,London (FR) | London (GER) | London (QA) | London (SAF)
42,Los Angeles,4,BRZ | IRE | SWI | TUN,Los Angeles (BRZ) | Los Angeles (IRE) | Los Angeles (SWI) | Los Angeles (TUN)
43,Love Story,4,BRZ | FR | GB | PER,Love Story (BRZ) | Love Story (FR) | Love Story (GB) | Love Story (PER)
44,Maputo,4,AUS | GB | IRE | SAF,Maputo (AUS) | Maputo (GB) | Maputo (IRE) | Maputo (SAF)
45,Matterhorn,4,FR | IRE | SAF | USA,Matterhorn (FR) | Matterhorn (IRE) | Matterhorn (SAF) | Matterhorn (USA)
46,Milton,4,FR | GB | SAF | USA,Milton (FR) | Milton (GB) | Milton (SAF) | Milton (USA)
47,My Way,4,CHI | CZE | FR | GER,My Way (CHI) | My Way (CZE) | My Way (FR) | My Way (GER)
48,Nashville,4,FR | IRE | NZ | USA,Nashville (FR) | Nashville (IRE) | Nashville (NZ) | Nashville (USA)
49,Nom De Plume,4,FR | IRE | NZ | USA,Nom De Plume (FR) | Nom De Plume (IRE) | Nom De Plume (NZ) | Nom De Plume (USA)

### Runner identity and demographics — interim findings

#### `num`

The field is declared as `INTEGER` but uses mixed SQLite storage:

- 1,844,253 rows contain integers;
- 7,032 rows contain blank text;
- numeric values range from 0 to 40.

The value `0` occurs 1,179 times and is concentrated in particular jurisdictions and meetings. It appears to function as a source convention in at least some races rather than as an ordinary runner number.

Populated positive values are not universally unique within a race:

- 523 duplicated positive-number groups;
- 362 apparent races affected;
- 29 courses affected;
- up to four runners share one positive number.

These duplicates are heavily concentrated in South American and North American racing and may represent jurisdiction-specific coupled-entry or betting-number conventions.

`num` must therefore not be used as a universal runner identifier without further domain rules.

#### `horse`

The field is fully populated and has no outer whitespace.

Every one of the 208,631 distinct stored horse names ends with a terminal parenthesised suffix. There are 51 distinct suffix forms.

Removing the suffix would be unsafe:

- 200,156 distinct base names remain;
- 7,635 base names occur with multiple suffixes;
- some base names occur with as many as five suffixes.

The complete stored name should therefore remain intact until the suffix has been separately verified and parsed.

#### `age`

The field is fully populated and stored consistently as integers.

Most values range from 2 to 16. Rare older ages of 17 and 18 were supported by consistent histories for long-running National Hunt horses.

Two separate quality patterns were identified:

- one Australian-bred horse is stored as age 1 in five British 2-year-old races, suggesting a systematic international age-convention issue;
- one Woodbine record stores `Ecstasy (USA)` as age 31, while later records show ages 3 and 4. This is a clear isolated source defect.

#### `sex`

The field is fully populated and contains eight stored codes.

The dominant codes are:

- `G`;
- `F`;
- `M`;
- `C`;
- `H`;
- `R`.

The values `B` and `BB` each occur once and remain unresolved special codes.

One record for `Ecstasy (USA)` stores `M`, while later records consistently store `F`. Combined with the erroneous age 31 on the same row, this is a clear isolated source defect.

#### `jockey`

There are two blank values, both in French races.

No outer whitespace was found.

#### `trainer`

There are nine blank values:

- eight in French races;
- one in a Japanese race.

No outer whitespace was found.

#### Fields requiring separate domain investigation

- jurisdiction-specific meaning of `num = 0`;
- coupled-entry or shared-number conventions;
- horse suffix semantics and historical jurisdiction codes;
- international horse-age conventions;
- the meanings of `B` and `BB` in `sex`;
- entity resolution for horse, jockey, and trainer names.

In [40]:
# Define the result and finishing field group.
result_finishing_fields = [
    "pos",
    "ovr_btn",
    "btn",
]

# Build the same field-level source-quality summary used for earlier groups.
result_finishing_profile_rows = []

for field in result_finishing_fields:
    quoted_field = f'"{field}"'

    query = f"""
    SELECT
        COUNT(*) AS total_rows,
        SUM(CASE WHEN {quoted_field} IS NULL THEN 1 ELSE 0 END)
            AS null_count,
        SUM(
            CASE
                WHEN typeof({quoted_field}) = 'text'
                 AND length(trim({quoted_field})) = 0
                THEN 1 ELSE 0
            END
        ) AS blank_text_count,
        COUNT(DISTINCT {quoted_field}) AS distinct_non_null_values,
        SUM(CASE WHEN typeof({quoted_field}) = 'null' THEN 1 ELSE 0 END)
            AS storage_null,
        SUM(CASE WHEN typeof({quoted_field}) = 'integer' THEN 1 ELSE 0 END)
            AS storage_integer,
        SUM(CASE WHEN typeof({quoted_field}) = 'real' THEN 1 ELSE 0 END)
            AS storage_real,
        SUM(CASE WHEN typeof({quoted_field}) = 'text' THEN 1 ELSE 0 END)
            AS storage_text,
        SUM(CASE WHEN typeof({quoted_field}) = 'blob' THEN 1 ELSE 0 END)
            AS storage_blob
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """

    result = pd.read_sql_query(query, connection).iloc[0].to_dict()

    declared_type = source_data_dictionary.loc[
        source_data_dictionary["field_name"] == field,
        "declared_sqlite_type",
    ].iloc[0]

    result["field_name"] = field
    result["declared_sqlite_type"] = declared_type

    result_finishing_profile_rows.append(result)

result_finishing_quality = pd.DataFrame(
    result_finishing_profile_rows
)

result_finishing_quality = result_finishing_quality[
    [
        "field_name",
        "declared_sqlite_type",
        "total_rows",
        "null_count",
        "blank_text_count",
        "distinct_non_null_values",
        "storage_null",
        "storage_integer",
        "storage_real",
        "storage_text",
        "storage_blob",
    ]
]

display(result_finishing_quality)

,field_name,declared_sqlite_type,total_rows,null_count,blank_text_count,distinct_non_null_values,storage_null,storage_integer,storage_real,storage_text,storage_blob
0,pos,INTEGER,1851285,0,0,46,0,1756674,0,94611,0
1,ovr_btn,NUMERIC,1851285,0,0,951,0,589977,1167316,93992,0
2,btn,NUMERIC,1851285,0,0,245,0,661250,1096043,93992,0

In [41]:
# Profile every text-valued result code exactly as stored.
#
# These values are not interpreted yet. The purpose is to separate numeric
# finishing information from special text codes and quantify each code.

text_result_code_frames = []

for field in result_finishing_fields:
    quoted_field = f'"{field}"'

    text_codes = pd.read_sql_query(
        f"""
        SELECT
            {quoted_field} AS stored_value,
            COUNT(*) AS row_count
        FROM data
        WHERE {DATA_ROW_PREDICATE}
          AND typeof({quoted_field}) = 'text'
        GROUP BY {quoted_field}
        ORDER BY row_count DESC, stored_value
        """,
        connection,
    )

    text_codes["field_name"] = field
    text_codes["row_pct"] = (
        text_codes["row_count"]
        / 1_851_285
        * 100
    )

    text_result_code_frames.append(text_codes)

text_result_codes = pd.concat(
    text_result_code_frames,
    ignore_index=True,
)

for field in result_finishing_fields:
    print(f"\n{field.upper()} — TEXT VALUES")

    with pd.option_context("display.max_rows", None):
        display(
            text_result_codes.loc[
                text_result_codes["field_name"] == field,
                ["stored_value", "row_count", "row_pct"],
            ].round({"row_pct": 4})
        )

POS — TEXT VALUES

   stored_value  row_count  row_pct
0            PU      65832   3.5560
1             F      15681   0.8470
2            UR       9527   0.5146
3            BD       1020   0.0551
4            RR        723   0.0391
5           DSQ        619   0.0334
6            RO        463   0.0250
7            SU        371   0.0200
8           REF        291   0.0157
9            CO         77   0.0042
10          LFT          7   0.0004

OVR_BTN — TEXT VALUES

   stored_value  row_count  row_pct
11            -      93992   5.0771

BTN — TEXT VALUES

   stored_value  row_count  row_pct
12            -      93992   5.0771

In [42]:
# Compare ovr_btn and btn storage patterns row by row.
#
# This tests whether the two fields jointly switch between numeric and
# special-text states, without yet interpreting their racing meaning.

button_storage_relationship = pd.read_sql_query(
    f"""
    SELECT
        typeof(ovr_btn) AS ovr_btn_storage,
        typeof(btn) AS btn_storage,
        COUNT(*) AS row_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY
        typeof(ovr_btn),
        typeof(btn)
    ORDER BY row_count DESC
    """,
    connection,
)

button_dash_relationship = pd.read_sql_query(
    f"""
    SELECT
        SUM(
            CASE
                WHEN ovr_btn = '-' AND btn = '-'
                THEN 1 ELSE 0
            END
        ) AS both_dash_rows,

        SUM(
            CASE
                WHEN ovr_btn = '-' AND btn <> '-'
                THEN 1 ELSE 0
            END
        ) AS ovr_only_dash_rows,

        SUM(
            CASE
                WHEN ovr_btn <> '-' AND btn = '-'
                THEN 1 ELSE 0
            END
        ) AS btn_only_dash_rows
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

display(button_storage_relationship)
display(button_dash_relationship)

  ovr_btn_storage btn_storage  row_count
0            real        real     860050
1         integer     integer     353984
2            real     integer     307266
3         integer        real     235993
4            text        text      93992

   both_dash_rows  ovr_only_dash_rows  btn_only_dash_rows
0           93992                   0                   0

In [43]:
# Test how finishing-status codes relate to the dash placeholders in
# ovr_btn and btn.
#
# This records the observed relationship only. It does not yet assign formal
# meanings to the status codes or distance fields.

position_button_relationship = pd.read_sql_query(
    f"""
    SELECT
        CASE
            WHEN typeof(pos) = 'text'
            THEN pos
            ELSE '<numeric position>'
        END AS position_state,

        CASE
            WHEN ovr_btn = '-' AND btn = '-'
            THEN 'both dash'
            ELSE 'both numeric'
        END AS button_state,

        COUNT(*) AS row_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY
        position_state,
        button_state
    ORDER BY
        position_state,
        button_state
    """,
    connection,
)

position_code_button_summary = pd.read_sql_query(
    f"""
    SELECT
        pos AS position_code,
        COUNT(*) AS row_count,

        SUM(
            CASE
                WHEN ovr_btn = '-' AND btn = '-'
                THEN 1 ELSE 0
            END
        ) AS both_dash_rows,

        SUM(
            CASE
                WHEN ovr_btn <> '-' AND btn <> '-'
                THEN 1 ELSE 0
            END
        ) AS numeric_button_rows
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND typeof(pos) = 'text'
    GROUP BY pos
    ORDER BY row_count DESC, pos
    """,
    connection,
)

display(position_button_relationship)
display(position_code_button_summary)

        position_state  button_state  row_count
0   <numeric position>  both numeric    1756674
1                   BD     both dash       1020
2                   CO     both dash         77
3                  DSQ  both numeric        619
4                    F     both dash      15681
5                  LFT     both dash          7
6                   PU     both dash      65832
7                  REF     both dash        291
8                   RO     both dash        463
9                   RR     both dash        723
10                  SU     both dash        371
11                  UR     both dash       9527

   position_code  row_count  both_dash_rows  numeric_button_rows
0             PU      65832           65832                    0
1              F      15681           15681                    0
2             UR       9527            9527                    0
3             BD       1020            1020                    0
4             RR        723             723                    0
5            DSQ        619               0                  619
6             RO        463             463                    0
7             SU        371             371                    0
8            REF        291             291                    0
9             CO         77              77                    0
10           LFT          7               7                    0

In [44]:
# Profile numeric finishing-distance values exactly as stored.
#
# Integer and real storage classes are combined as numeric values. The dash
# placeholder rows are excluded from these range calculations but remain
# documented separately.

button_numeric_profile = pd.read_sql_query(
    f"""
    SELECT
        MIN(
            CASE
                WHEN typeof(ovr_btn) IN ('integer', 'real')
                THEN ovr_btn
            END
        ) AS minimum_ovr_btn,

        MAX(
            CASE
                WHEN typeof(ovr_btn) IN ('integer', 'real')
                THEN ovr_btn
            END
        ) AS maximum_ovr_btn,

        COUNT(
            DISTINCT CASE
                WHEN typeof(ovr_btn) IN ('integer', 'real')
                THEN ovr_btn
            END
        ) AS distinct_numeric_ovr_btn,

        SUM(
            CASE
                WHEN typeof(ovr_btn) IN ('integer', 'real')
                 AND ovr_btn < 0
                THEN 1 ELSE 0
            END
        ) AS negative_ovr_btn_rows,

        SUM(
            CASE
                WHEN typeof(ovr_btn) IN ('integer', 'real')
                 AND ovr_btn = 0
                THEN 1 ELSE 0
            END
        ) AS zero_ovr_btn_rows,

        MIN(
            CASE
                WHEN typeof(btn) IN ('integer', 'real')
                THEN btn
            END
        ) AS minimum_btn,

        MAX(
            CASE
                WHEN typeof(btn) IN ('integer', 'real')
                THEN btn
            END
        ) AS maximum_btn,

        COUNT(
            DISTINCT CASE
                WHEN typeof(btn) IN ('integer', 'real')
                THEN btn
            END
        ) AS distinct_numeric_btn,

        SUM(
            CASE
                WHEN typeof(btn) IN ('integer', 'real')
                 AND btn < 0
                THEN 1 ELSE 0
            END
        ) AS negative_btn_rows,

        SUM(
            CASE
                WHEN typeof(btn) IN ('integer', 'real')
                 AND btn = 0
                THEN 1 ELSE 0
            END
        ) AS zero_btn_rows
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

button_common_values = pd.read_sql_query(
    f"""
    SELECT
        CAST(ovr_btn AS TEXT) AS stored_ovr_btn,
        CAST(btn AS TEXT) AS stored_btn,
        COUNT(*) AS row_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND typeof(ovr_btn) IN ('integer', 'real')
      AND typeof(btn) IN ('integer', 'real')
    GROUP BY
        ovr_btn,
        btn
    ORDER BY
        row_count DESC,
        ovr_btn,
        btn
    LIMIT 40
    """,
    connection,
)

display(button_numeric_profile)
display(button_common_values)

,minimum_ovr_btn,maximum_ovr_btn,distinct_numeric_ovr_btn,negative_ovr_btn_rows,zero_ovr_btn_rows,minimum_btn,maximum_btn,distinct_numeric_btn,negative_btn_rows,zero_btn_rows
0,0,331.5,950,0,189408,0,186,244,0,192162

   stored_ovr_btn stored_btn  row_count
0               0          0     189408
1             0.5        0.5      19483
2             0.3        0.3      16795
3            0.75       0.75      15758
4            1.25       1.25      14137
5               1          1      11058
6             0.2        0.2      10957
7             1.5        1.5      10611
8            1.75       1.75       9238
9               2          2       7956
10           2.25       2.25       6598
11            0.1        0.1       6499
12            2.5        2.5       6436
13              3          3       5145
14           2.75       2.75       4436
15           0.05       0.05       4155
16            2.5        0.5       3851
17            3.5        0.5       3819
18              3        0.5       3809
19            3.5        3.5       3780
20           2.25        0.5       3776
21           3.25        0.5       3773
22              5          5       3768
23           2.75        0.5       3763
24              4          4       3737
25              2        0.5       3682
26           3.75        0.5       3617
27              2        0.3       3589
28              4        0.5       3577
29           3.25       3.25       3575
30           2.25        0.3       3556
31           1.75        0.5       3536
32           2.75        0.3       3524
33            2.5        0.3       3510
34           3.25        0.3       3492
35            4.5        0.5       3450
36              6          6       3432
37           1.75        0.3       3422
38            3.5        0.3       3385
39           4.25        0.5       3379

In [45]:
# Compare numeric finishing positions with ovr_btn and btn.
#
# This tests structural relationships only:
# - whether winners have zero values;
# - whether non-winners can also have zero values;
# - whether ovr_btn is ever smaller than btn.
#
# No formal racing-domain meaning is assigned yet.

position_distance_relationship = pd.read_sql_query(
    f"""
    SELECT
        SUM(
            CASE
                WHEN typeof(pos) = 'integer'
                 AND pos = 1
                THEN 1 ELSE 0
            END
        ) AS winner_rows,

        SUM(
            CASE
                WHEN typeof(pos) = 'integer'
                 AND pos = 1
                 AND ovr_btn = 0
                THEN 1 ELSE 0
            END
        ) AS winners_with_zero_ovr_btn,

        SUM(
            CASE
                WHEN typeof(pos) = 'integer'
                 AND pos = 1
                 AND btn = 0
                THEN 1 ELSE 0
            END
        ) AS winners_with_zero_btn,

        SUM(
            CASE
                WHEN typeof(pos) = 'integer'
                 AND pos > 1
                 AND ovr_btn = 0
                THEN 1 ELSE 0
            END
        ) AS non_winners_with_zero_ovr_btn,

        SUM(
            CASE
                WHEN typeof(pos) = 'integer'
                 AND pos > 1
                 AND btn = 0
                THEN 1 ELSE 0
            END
        ) AS non_winners_with_zero_btn,

        SUM(
            CASE
                WHEN typeof(ovr_btn) IN ('integer', 'real')
                 AND typeof(btn) IN ('integer', 'real')
                 AND ovr_btn < btn
                THEN 1 ELSE 0
            END
        ) AS rows_where_ovr_btn_less_than_btn,

        SUM(
            CASE
                WHEN typeof(ovr_btn) IN ('integer', 'real')
                 AND typeof(btn) IN ('integer', 'real')
                 AND ovr_btn = btn
                THEN 1 ELSE 0
            END
        ) AS rows_where_values_equal,

        SUM(
            CASE
                WHEN typeof(ovr_btn) IN ('integer', 'real')
                 AND typeof(btn) IN ('integer', 'real')
                 AND ovr_btn > btn
                THEN 1 ELSE 0
            END
        ) AS rows_where_ovr_btn_greater_than_btn
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

position_distance_examples = pd.read_sql_query(
    f"""
    SELECT
        pos,
        ovr_btn,
        btn,
        COUNT(*) AS row_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND typeof(pos) = 'integer'
      AND typeof(ovr_btn) IN ('integer', 'real')
      AND typeof(btn) IN ('integer', 'real')
    GROUP BY
        pos,
        ovr_btn,
        btn
    ORDER BY
        pos,
        row_count DESC,
        ovr_btn,
        btn
    LIMIT 60
    """,
    connection,
)

display(position_distance_relationship)
display(position_distance_examples)

,winner_rows,winners_with_zero_ovr_btn,winners_with_zero_btn,non_winners_with_zero_ovr_btn,non_winners_with_zero_btn,rows_where_ovr_btn_less_than_btn,rows_where_values_equal,rows_where_ovr_btn_greater_than_btn
0,189344,188844,188845,371,3121,421,386778,1370094

    pos  ovr_btn    btn  row_count
0     0     0.00   0.00          8
1     1     0.00   0.00     188844
2     1     0.05   0.05         86
3     1     0.20   0.20         82
4     1     0.10   0.10         74
5     1     0.30   0.30         54
6     1     0.50   0.50         39
7     1     0.75   0.75         28
8     1     1.00   1.00         15
9     1     1.50   1.50         15
10    1     2.00   2.00         14
11    1     1.75   1.75         11
12    1     1.25   1.25          9
13    1     2.50   2.50          9
14    1     2.75   2.75          8
15    1     2.25   2.25          6
16    1     4.50   4.50          5
17    1     5.00   5.00          5
18    1     3.25   3.25          4
19    1     3.50   3.50          4
20    1     3.75   3.75          3
21    1     7.00   7.00          3
22    1     3.00   3.00          2
23    1     4.00   4.00          2
24    1     4.25   4.25          2
25    1     5.50   5.50          2
26    1     6.00   6.00          2
27    1     9.00   9.00          2
28    1    10.00  10.00          2
29    1     0.25   0.25          1
30    1     0.75   0.30          1
31    1     1.50   1.00          1
32    1     2.00   0.00          1
33    1     7.25   7.25          1
34    1     7.50   7.50          1
35    1     8.00   8.00          1
36    1    13.00  13.00          1
37    1    14.00  14.00          1
38    1    18.00  18.00          1
39    1    26.00  26.00          1
40    1    30.25   0.50          1
41    2     0.50   0.50      18381
42    2     0.30   0.30      16699
43    2     0.75   0.75      14812
44    2     1.25   1.25      13260
45    2     0.20   0.20      10797
46    2     1.00   1.00      10345
47    2     1.50   1.50       9906
48    2     1.75   1.75       8634
49    2     2.00   2.00       7501
50    2     0.10   0.10       6405
51    2     2.25   2.25       6176
52    2     2.50   2.50       6015
53    2     3.00   3.00       4840
54    2     2.75   2.75       4158
55    2     0.05   0.05       4051
56    2     5.00   5.00       3605
57    2     3.50   3.50       3590
58    2     4.00   4.00       3552
59    2     3.25   3.25       3384

In [46]:
# Inspect unusual relationships among pos, ovr_btn, and btn.
#
# The selected rows include:
# - numeric position zero;
# - winners with a non-zero distance;
# - non-winners with zero overall distance;
# - rows where overall distance is smaller than the adjacent margin.
#
# These are evidence candidates only. No correction is applied.

unusual_position_distance_rows = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        type,
        ran,
        num,
        pos,
        ovr_btn,
        btn,
        horse,
        comment,
        CASE
            WHEN typeof(pos) = 'integer'
             AND pos = 0
            THEN 'position zero'

            WHEN typeof(pos) = 'integer'
             AND pos = 1
             AND (
                    ovr_btn <> 0
                 OR btn <> 0
             )
            THEN 'winner with non-zero distance'

            WHEN typeof(pos) = 'integer'
             AND pos > 1
             AND ovr_btn = 0
            THEN 'non-winner with zero overall distance'

            WHEN typeof(ovr_btn) IN ('integer', 'real')
             AND typeof(btn) IN ('integer', 'real')
             AND ovr_btn < btn
            THEN 'overall distance smaller than btn'

            ELSE 'other'
        END AS issue_type
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND (
            (
                typeof(pos) = 'integer'
                AND pos = 0
            )
         OR (
                typeof(pos) = 'integer'
                AND pos = 1
                AND (
                       ovr_btn <> 0
                    OR btn <> 0
                )
            )
         OR (
                typeof(pos) = 'integer'
                AND pos > 1
                AND ovr_btn = 0
            )
         OR (
                typeof(ovr_btn) IN ('integer', 'real')
                AND typeof(btn) IN ('integer', 'real')
                AND ovr_btn < btn
            )
      )
    ORDER BY
        issue_type,
        date,
        course,
        off,
        pos,
        rowid
    """,
    connection,
)

unusual_position_distance_summary = (
    unusual_position_distance_rows
    .groupby("issue_type", as_index=False)
    .agg(
        runner_rows=("source_rowid", "count"),
        apparent_races=(
            "race_name",
            lambda _: 0,
        ),
        distinct_courses=("course", "nunique"),
    )
)

unusual_position_distance_summary["apparent_races"] = [
    unusual_position_distance_rows.loc[
        unusual_position_distance_rows["issue_type"] == issue_type,
        ["date", "course", "off", "race_name"],
    ].drop_duplicates().shape[0]
    for issue_type in unusual_position_distance_summary["issue_type"]
]

display(unusual_position_distance_summary)

for issue_type in unusual_position_distance_summary["issue_type"]:
    print(f"\n{issue_type.upper()} — FIRST 30 ROWS")

    with pd.option_context(
        "display.max_rows",
        30,
        "display.max_colwidth",
        120,
    ):
        display(
            unusual_position_distance_rows.loc[
                unusual_position_distance_rows["issue_type"] == issue_type
            ].head(30)
        )

,issue_type,runner_rows,apparent_races,distinct_courses
0,non-winner with zero overall distance,371,341,124
1,overall distance smaller than btn,421,421,121
2,position zero,8,2,2
3,winner with non-zero distance,500,499,133

NON-WINNER WITH ZERO OVERALL DISTANCE — FIRST 30 ROWS

,source_rowid,date,course,race_id,off,race_name,type,ran,num,pos,ovr_btn,btn,horse,comment,issue_type
0,2688,2015-01-08,Gulfstream Park (USA),617268,7:07,Maiden Special Weight (Maiden) (3yo) (Dirt),Flat,8,8,6,0.0,0.0,Tradesman (USA),Broke well from wide draw and chased leaders - close 3rd and nudged along halfway - shaken up to challenge outside t...,non-winner with zero overall distance
1,4538,2015-01-15,Wolverhampton (AW),616318,6:40,Bet In Play At Coral Handicap (Tapeta),Flat,7,7,2,0.0,0.0,Warfare (GB),Chased leaders - led over 1f out - ridden and edged left inside final furlong - edged right towards finish - joined ...,non-winner with zero overall distance
2,9570,2015-01-31,Tampa Bay Downs (USA),618671,10:50,Lambholm South Endeavour Stakes (Fillies & Mares) (Turf),Flat,11,,2,0.0,0.0,Hard Not To Like (CAN),Finished 1st - disqualified and placed 2nd,non-winner with zero overall distance
3,12161,2015-02-08,Delta downs (USA),619102,3:24,LA Bred Premier Night Matron Stakes (Fillies & Mares) (Dirt),Flat,9,,2,0.0,0.0,Solid Sender (USA),Finsihed 1st - disqualified and placed 2nd,non-winner with zero overall distance
4,13538,2015-02-13,Chantilly (FR),619427,4:25,Prix du Chemin Royal (Handicap) (5yo+) (Polytrack),Flat,17,14,3,0.0,0.0,Gonetrio (USA),Finished 1st - disqualified and placed 3rd,non-winner with zero overall distance
5,16967,2015-02-21,Gulfstream Park (USA),619838,10:30,Besilu Stables Fountain Of Youth Stakes (3yo) (Dirt),Flat,8,,2,0.0,0.0,Upstart (USA),Finished 1st - disqualified and placed 2nd,non-winner with zero overall distance
6,17590,2015-02-24,Catterick,618467,5:00,Racing Again 4th March Handicap Hurdle,Hurdle,7,1,2,0.0,0.0,Harris (IRE),Made all - driven 8th - eged left run-in - all out - finished 1st - disqualified and placed 2nd(op 14/1 tchd 18/1),non-winner with zero overall distance
7,41078,2015-04-18,Keeneland (USA),624644,9:11,Maiden Special Weight (3yo) (Turf),Flat,12,2,10,0.0,0.0,Lookaroundcorners (USA),Finished 1st - disqualified and placed 10th,non-winner with zero overall distance
8,45551,2015-04-28,Nottingham,623004,4:50,£10 Free At 32Red Handicap,Flat,7,5,2,0.0,0.0,Mountain Man (GB),In rear - switched right to outer and headway well over 1f out - soon ridden and edged left - strong run to lead ent...,non-winner with zero overall distance
9,50532,2015-05-07,Worcester,626399,5:05,Post Your Bets @ bookies.com Mares Maiden Hurdle (Div II),Hurdle,10,4,2,0.0,0.0,Nellies Quest (GB),Held up - headway and not fluent 5th - led 2 out - ridden and went right last - all out - finished 1st - placed 2nd(...,non-winner with zero overall distance
10,54104,2015-05-14,Newmarket,624391,6:55,Chassis Cab DAF Handicap,Flat,7,1,2,0.0,0.0,Urban Castle (USA),Steadied start - held up in touch in rear - ridden and headway 2f out - challenging when bumped 1f out - driven to l...,non-winner with zero overall distance
11,56893,2015-05-18,Saint-Cloud (FR),627644,2:55,Prix Sicarelle (Maiden) (3yo Fillies) (Turf),Flat,11,6,2,0.0,0.0,Lucelle (IRE),Finished 1st - disqualified and placed 2nd,non-winner with zero overall distance
12,57453,2015-05-19,Chepstow,625061,3:10,Patricks Perfect Pride of Place Handicap,Flat,8,10,2,0.0,0.0,Abyaat (IRE),Midfield - pulled out and rapid headway over 3f out - led well over 2f out - soon ridden - edged right final furlong...,non-winner with zero overall distance
13,60958,2015-05-27,Hamilton,625863,4:15,Cadzow Castle Fillies Handicap,Flat,9,7,2,0.0,0.0,Miss Van Gogh (GB),In touch - ridden over 2f out - headway to lead over 1f out - soon edged right - hard pressed when hung and carried ...,non-winner with zero overall distance
14,72897,2015-06-20,Ayr,627940,2:20,Scottish Sun On Sunday Handicap,Flat,6,6,2,0.0,0.0,Little Lady Katie (IRE),Made all - ridden over 2f out - drifted right inside final furlong - held on gamely - finished first - placed second...,non-winner with zero overall distance
15,72918,2015-06-20,Compiegne (FR),630164,2:40,Prix Ridgway () (3yo) (Turf),Flat,6,2,3,0.0,0.0,Zafiro (FR),Finished 1st - dsqualified and placed 3rd,non-winner with zero overall distance
16,78737,2015-07-02,Deauville (FR),631049,12:30,Prix de Ticheville (Maiden) (2yo Colts & Geldings) (Round) (Turf),Flat,11,10,4,0.0,0.0,Radipole (IRE),Finished 1st - disqualified and placed 4th,non-winner with zero overall distance
17,85150,2015-07-17,Hamilton,629937,8:45,Jordan Electrics Handicap,Flat,7,4,2,0.0,0.0,Henpecked (GB),Close up - led halfway - ridden and hung badly left 2f out - straighted inside final furlong - kept on - finished fi...,non-winner with zero overall distance
18,87943,2015-07-23,Limerick (IRE),631934,6:05,Book Online At Limerickraces.ie Mares Novice Hurdle,Hurdle,8,2,2,0.0,0.0,Thanks For Tea (IRE),Held up until took closer order 3 out to chase leaders in 3rd - ridden to dispute last and led narrowly - kept on we...,non-winner with zero overall distance
19,88734,2015-07-25,Saratoga (USA),632377,10:32,Sanford Stakes (2yo) (Dirt),Flat,10,4,3,0.0,0.0,Magna Light (USA),Finished 1st - disqualified and placed 3rd,non-winner with zero overall distance
20,89276,2015-07-26,Saratoga (USA),632338,11:07,Coaching Club American Oaks (3yo Fillies) (Dirt),Flat,7,8,2,0.0,0.0,Im A Chatterbox (USA),Made all - set a decent gallop - ridden and rallied over 1f out - ran on gamely under pressure final furlong - edged...,non-winner with zero overall distance
21,92203,2015-08-01,Deauville (FR),632813,1:00,Prix dEtreham (Prix de Sauternes) (Conditions) (2yo Colts & Geldings) (Turf),Flat,5,2,2,0.0,0.0,Elombo (FR),Finished 1st - disqualified and placed 2nd,non-winner with zero overall distance
22,94282,2015-08-06,Sligo (IRE),632755,6:40,Leo McMorrow Memorial Handicap Hurdle,Hurdle,9,3,2,0.0,0.0,He Is Top Class (IRE),Chased leaders - 3rd halfway - went 2nd after 3 out - pushed into lead between last 2 - ridden from last and soon dr...,non-winner with zero overall distance
23,96750,2015-08-12,Gowran Park (IRE),633151,6:00,Join The Gowran Park Racing Club For 100 Euro Nursery (Plus 10 Race),Flat,12,3,2,0.0,0.0,Bobailin (IRE),Soon led narrowly - ridden to extend advantage under 2f out - clear entering final furlong - edged left closing stag...,non-winner with zero overall distance
24,96833,2015-08-12,Newton Abbot,631860,4:15,SIS Handicap Hurdle,Hurdle,16,8,2,0.0,0.0,Kentford Heiress (GB),Towards rear - good progress 6th - led 3 out - drew clear with one rival next and going best but allowed to drift le...,non-winner with zero overall distance
25,98345,2015-08-15,Arlington Park (USA),633531,11:05,Beverly D. Stakes (3yo+ Fillies & Mares) (Turf),Flat,9,10,3,0.0,0.0,Secret Gesture (GB),Chased leader - ridden over 2f out - driven to lead inside final furlong - edged right closing stages - comfortably ...,non-winner with zero overall distance
26,101863,2015-08-23,Deauville (FR),633947,4:55,Prix des Gorges Saint-Aubert (Handicap) (4yo+) (Turf),Flat,12,12,3,0.0,0.0,Soulside (IRE),Finished 1st - disqualified and placed 3rd,non-winner with zero overall distance
27,108153,2015-09-06,Longchamp (FR),634788,4:20,Prix des Bouleaux (Claimer) (4yo+) (Turf),Flat,12,5,4,0.0,0.0,Saon Secret (FR),Finished 4th - disqualified and placed 4th,non-winner with zero overall distance
28,109231,2015-09-08,Chantilly (FR),634873,5:10,Prix des Tourelles () (3yo+ Fillies & Mares) (Turf),Flat,6,6,2,0.0,0.0,Lady Of Kyushu (USA),Held up towards rear - ridden and headway from 2f out - hung right inside final furlong - stayed on strongly to lead...,non-winner with zero overall distance
29,110272,2015-09-11,Enghien (FR),635176,1:35,Prix Jim Crow (Chase) (Conditions) (5yo+) (Turf),Chase,8,5,2,0.0,0.0,Pythagore (GB),Finished 1st - disqualified and placed 2nd,non-winner with zero overall distance

OVERALL DISTANCE SMALLER THAN BTN — FIRST 30 ROWS

,source_rowid,date,course,race_id,off,race_name,type,ran,num,pos,ovr_btn,btn,horse,comment,issue_type
371,5651,2015-01-18,Nakayama (JPN),617866,6:35,Kiesei Hai Stakes (Turf),Flat,17,,3,0.25,0.3,Kluger (JPN),,overall distance smaller than btn
372,6683,2015-01-22,Meydan (UAE),617889,6:15,gulfnews.com (Handicap) (Turf),Flat,14,11,3,0.25,0.3,Earth Drummer (IRE),Mid-division - ran on final 2f - just failed,overall distance smaller than btn
373,7027,2015-01-23,Wolverhampton (AW),616393,4:15,Bet In Play At Coral Apprentice Handicap (Tapeta),Flat,10,5,3,0.25,0.3,Thrtypointstothree (IRE),Raced keenly - chased leaders - ridden and outpaced over 2f out - rallied inside final furlong - ran on and closed t...,overall distance smaller than btn
374,9103,2015-01-30,Wolverhampton (AW),616967,5:45,Download The Coral App Handicap (Tapeta),Flat,8,8,3,0.25,0.3,Perfect Cracker (GB),Tracked leaders - raced keenly - ridden to lead 1f out - edged left and headed well inside final furlong - ran on(tc...,overall distance smaller than btn
375,12878,2015-02-11,Lingfield (AW),617696,3:05,32RedPoker.com Handicap,Flat,8,9,8,111.00,147.0,Premier Jacks (GB),Took keen hold - led and soon clear - headed 7f out - dropped out rapidly 5f out - tailed final 4f,overall distance smaller than btn
376,13937,2015-02-14,Caulfield (AUS),619440,4:55,Herald Sun Carlyon Cup (Turf),Flat,11,8,3,0.25,0.3,Backstedt (AUS),,overall distance smaller than btn
377,13954,2015-02-14,Lingfield (AW),617718,1:25,Unibet Offer Daily Jockey/Trainer Specials Median Auction Maiden Stakes,Flat,7,1,3,0.25,0.3,Autumn Tonic (IRE),In touch in midfield - effort on inner over 1f out - every chance final 100yds - ran on - no extra close home(op 6/4...,overall distance smaller than btn
378,14611,2015-02-15,Kyoto (JPN),619464,6:35,Kyoto Kinen (Grade2) (Turf),Flat,11,,3,0.25,0.3,Kizuna (JPN),,overall distance smaller than btn
379,14954,2015-02-16,Laurel Park (USA),619524,8:57,Miracle Wood Stakes (Dirt),Flat,6,2,3,0.25,0.3,Golden Years (USA),,overall distance smaller than btn
380,14975,2015-02-16,Wolverhampton (AW),618007,3:05,Coral Connect Maiden Stakes (Tapeta),Flat,9,5,3,0.25,0.3,Goathland (IRE),Prominent - chased leader 7f out - shaken up over 3f out - led over 2f out - ridden and hung left over 1f out - head...,overall distance smaller than btn
381,19475,2015-03-01,Hanshin (JPN),620367,6:35,Hankyu Hai (Turf),Flat,16,,3,0.25,0.3,Robe Tissage (JPN),,overall distance smaller than btn
382,24079,2015-03-12,Chantilly (FR),621070,2:30,Prix Ronde de Nuit () (3yo Fillies) (Polytrack),Flat,8,6,3,0.25,0.3,Super Eria (FR),,overall distance smaller than btn
383,34677,2015-04-06,Huntingdon,621288,5:50,Flexicruise Intermediate Open National Hunt Flat Race,NH Flat,10,3,8,132.75,147.0,Domino King (GB),Took keen hold - held up in last pair - ridden 4f out - soon lost touch - tailed off when hung badly left and came t...,overall distance smaller than btn
384,35005,2015-04-07,Lingfield (AW),623311,4:40,Avensys Handicap (Div II),Flat,9,2,3,0.25,0.3,Dont Have It Then (GB),Settled in rear - progress on inner over 2f out - ridden and stayed on final furlong to take 3rd near finish - just ...,overall distance smaller than btn
385,47676,2015-05-02,Newmarket,623092,5:30,Qipco Supports Racing Welfare Handicap,Flat,7,1,2,0.25,0.3,Emirates Skycargo (IRE),Held up in touch in last pair - headway to chase leaders when short of room - hampered and switched right over 1f ou...,overall distance smaller than btn
386,52363,2015-05-10,Leopardstown (IRE),623249,2:40,Ard Glen Amethyst Stakes,Flat,7,2,3,0.25,0.3,Fire Ship (GB),Led - 1 length clear at halfway - ridden and pressed closely entering final furlong - reduced advantage inside final...,overall distance smaller than btn
387,54126,2015-05-14,Newmarket,624393,8:00,Redbourn Engineering Ltd Fillies Handicap (Jockey Club Grassroots Flat Middle Distance Series),Flat,11,13,3,0.25,0.3,All My Love (IRE),Led - ridden well over 1f out - hard pressed but battled on gamely under pressure - headed inside final furlong - no...,overall distance smaller than btn
388,58148,2015-05-21,Sandown,625126,7:35,ApolloBet Home Of Cash Back Specials Handicap,Flat,10,7,3,0.25,0.3,Soluble (GER),Led - ridden 2f out - headed over 1f out - kept on well and every chance after - just held towards finish - lost 2nd...,overall distance smaller than btn
389,59115,2015-05-23,Beverley,625168,5:00,Beryl And Joe Turner Memorial Handicap,Flat,10,1,3,0.25,0.3,Shamaheart (IRE),Tracked leaders - headway 3f out - effort on outer well over 1f out - ridden to challenge entering final furlong - s...,overall distance smaller than btn
390,63575,2015-05-31,Fakenham,626000,4:30,Welcome to Norfolk Princess Charlotte Novices Limited Handicap Chase,Chase,4,5,3,102.00,155.0,Radsoc De Sivola (FR),Soon detached in last - tailed off from 7th(op 66/1),overall distance smaller than btn
391,67365,2015-06-08,Pontefract,627211,6:40,Racing Together Maiden Auction Fillies Stakes (Plus 10 Race),Flat,12,10,3,0.25,0.3,Magic Garden (IRE),Led - ridden along well over 1f out - driven inside final furlong - headed and no extra last 40yds(op 33/1),overall distance smaller than btn
392,72777,2015-06-20,Ayr,627944,4:50,Arnold Clark Handicap,Flat,6,2,3,0.25,0.3,Kimberella (GB),Prominent - effort and switched right over 1f out - soon every chance - hung left inside final furlong - no extra cl...,overall distance smaller than btn
393,77486,2015-06-29,Musselburgh,628845,7:45,Investec Wealth And Investment June Selling Stakes,Flat,6,5,3,0.25,0.3,Rio Deva (IRE),Led - ridden 2f out - headed inside final furlong - rallied - held close home,overall distance smaller than btn
394,86641,2015-07-20,Beverley,630290,7:40,Richard And Carol Hudson Handicap,Flat,6,5,3,0.25,0.3,Unnoticed (GB),Tracked leader - headway over 2f out - soon close up - ridden to challenge well over 1f out - driven entering final ...,overall distance smaller than btn
395,87496,2015-07-22,Catterick,630340,5:00,catterickbridge.co.uk Apprentice Training Series Handicap (Racing Excellence Initiative),Flat,9,6,3,0.25,0.3,Christmas Light (GB),Mid-division - driven over 3f out - upsides over 2f out - led narrowly last 75yds - soon headed - no extra near fini...,overall distance smaller than btn
396,87885,2015-07-23,Limerick (IRE),631934,6:05,Book Online At Limerickraces.ie Mares Novice Hurdle,Hurdle,8,4,3,0.25,0.3,What A Jewel (IRE),Led until headed after - led again after 4th until joined approaching last - rallied well on inner until no extra in...,overall distance smaller than btn
397,88739,2015-07-25,Saratoga (USA),632301,11:07,TVG Diana Stakes (3yo+ Fillies & Mares) (Turf),Flat,7,3,3,0.25,0.3,Kittens Queen (USA),Led - ridden and rallied 2f out - strongly pressed throughout final furlong - headed close home - no extra,overall distance smaller than btn
398,92121,2015-08-01,Deauville (FR),632821,4:50,Prix des Alpes Mancelles (Handicap) (4yo+) (Polytrack),Flat,16,14,3,0.25,0.3,Lloydminster (FR),,overall distance smaller than btn
399,106375,2015-09-02,Gowran Park (IRE),634241,5:55,Best Of Luck To The Kilkenny Hurlers This Sunday Fillies Maiden,Flat,12,3,3,0.25,0.3,Aunt Sally (IRE),Prominent until settled behind leader after 1f - ridden in 3rd under 2f out and kept on well under pressure inside f...,overall distance smaller than btn
400,111368,2015-09-13,Hanshin (JPN),635204,7:35,Centaur Stakes (3yo+) (Turf),Flat,16,8,3,0.25,0.3,Barbara (JPN),,overall distance smaller than btn

POSITION ZERO — FIRST 30 ROWS

,source_rowid,date,course,race_id,off,race_name,type,ran,num,pos,ovr_btn,btn,horse,comment,issue_type
792,40679,2015-04-18,Nakayama (JPN),624701,7:40,Nakayama Grand Jump (Turf),Flat,15,,0,0.0,0.0,Rikiai Kurofune (JPN),,position zero
793,40680,2015-04-18,Nakayama (JPN),624701,7:40,Nakayama Grand Jump (Turf),Flat,15,,0,0.0,0.0,Fire (JPN),,position zero
794,40681,2015-04-18,Nakayama (JPN),624701,7:40,Nakayama Grand Jump (Turf),Flat,15,,0,0.0,0.0,Shonan Coming (JPN),,position zero
795,40682,2015-04-18,Nakayama (JPN),624701,7:40,Nakayama Grand Jump (Turf),Flat,15,,0,0.0,0.0,Tenjin Kiyomori (JPN),,position zero
796,40683,2015-04-18,Nakayama (JPN),624701,7:40,Nakayama Grand Jump (Turf),Flat,15,,0,0.0,0.0,Country Snow (JPN),,position zero
797,77097,2015-06-28,Klampenborg (DEN),630668,3:00,Dansk Hesteforsikring Scandinavian Open Championship (3yo+) (Turf),Flat,13,1,0,0.0,0.0,Bank Of Burden (USA),,position zero
798,77098,2015-06-28,Klampenborg (DEN),630668,3:00,Dansk Hesteforsikring Scandinavian Open Championship (3yo+) (Turf),Flat,13,10,0,0.0,0.0,Mekong River (IRE),,position zero
799,77099,2015-06-28,Klampenborg (DEN),630668,3:00,Dansk Hesteforsikring Scandinavian Open Championship (3yo+) (Turf),Flat,13,2,0,0.0,0.0,Moe Green (IRE),,position zero

WINNER WITH NON-ZERO DISTANCE — FIRST 30 ROWS

,source_rowid,date,course,race_id,off,race_name,type,ran,num,pos,ovr_btn,btn,horse,comment,issue_type
800,2657,2015-01-08,Gulfstream Park (USA),617268,7:07,Maiden Special Weight (Maiden) (3yo) (Dirt),Flat,8,2,1,0.50,0.50,Royal Son (USA),Finished 2nd - awarded the race,winner with non-zero distance
801,9564,2015-01-31,Tampa Bay Downs (USA),618671,10:50,Lambholm South Endeavour Stakes (Fillies & Mares) (Turf),Flat,11,,1,0.75,0.75,Testa Rossi (FR),Finished 2nd - awarded the race,winner with non-zero distance
802,12159,2015-02-08,Delta downs (USA),619102,3:24,LA Bred Premier Night Matron Stakes (Fillies & Mares) (Dirt),Flat,9,,1,0.05,0.05,Afternoon Tango (USA),Finished 2nd - awarded the race,winner with non-zero distance
803,13537,2015-02-13,Chantilly (FR),619427,4:25,Prix du Chemin Royal (Handicap) (5yo+) (Polytrack),Flat,17,1,1,2.50,2.50,El Nino (FR),Finished 2nd - placed 1st,winner with non-zero distance
804,14782,2015-02-15,Navan (IRE),619171,3:55,Ten Up Novice Chase,Chase,6,2,1,4.25,4.25,Noble Emperor (IRE),Led narrowly until joined before 4th where not fluent - regained advantage from 6th until headed from 8th - regained...,winner with non-zero distance
805,15824,2015-02-19,Meydan (UAE),619483,5:05,District One (Handicap) (Dirt),Flat,15,6,1,1.25,1.25,Toolain (IRE),Mid-division - smooth progress 3f out - ran on well final 2f but no chance with winner - finished 2nd - awarded the ...,winner with non-zero distance
806,16168,2015-02-20,Jebel Ali (UAE),619514,11:35,Jebel Ali Mile Sponsored By Derrinstown Stud (Dirt),Flat,9,10,1,0.10,0.10,Silver Galaxy (GB),Tracked leader - led 2 1/2f out - headed 100yds out - battled back - just failed - finished 2nd - later awarded the ...,winner with non-zero distance
807,16970,2015-02-21,Gulfstream Park (USA),619838,10:30,Besilu Stables Fountain Of Youth Stakes (3yo) (Dirt),Flat,8,,1,2.75,2.75,Itsaknockout (USA),Finished 2nd - awarded the race,winner with non-zero distance
808,17591,2015-02-24,Catterick,618467,5:00,Racing Again 4th March Handicap Hurdle,Hurdle,7,5,1,0.10,0.10,Allez Cool (IRE),Chased leaders - 2nd from 8th - driven approaching 2 out - upsides when carried left run-in - just held - finished 2...,winner with non-zero distance
809,19222,2015-02-28,Meydan (UAE),619987,3:20,IPIC 30th Anniversary (Handicap) (Dirt),Flat,8,5,1,1.50,1.50,Press Room (USA),Tracked leaders - every chance 1 1/2f out - ran on same pace final furlong - finished 2nd - later awarded the race,winner with non-zero distance
810,41079,2015-04-18,Keeneland (USA),624644,9:11,Maiden Special Weight (3yo) (Turf),Flat,12,10,1,0.30,0.30,Animal Kracker (USA),Finished 2nd - awarded the race,winner with non-zero distance
811,45550,2015-04-28,Nottingham,623004,4:50,£10 Free At 32Red Handicap,Flat,7,6,1,0.30,0.30,Star Fire (GB),Dwelt and held up in rear - effort when not much room well over 1f out - soon switched right and ridden - stayed on ...,winner with non-zero distance
812,50543,2015-05-07,Worcester,626399,5:05,Post Your Bets @ bookies.com Mares Maiden Hurdle (Div II),Hurdle,10,1,1,0.05,0.05,Giveagirlachance (IRE),Held up - headway approaching 3 out - chased winner and hampered last - stayed on under pressure - finished 2nd - pl...,winner with non-zero distance
813,50949,2015-05-08,Ripon,623666,8:05,SIS At Heart the of Racing Handicap,Flat,8,2,1,3.25,3.25,Tuscan Gold (GB),Dwelt - held up - headway 4f out - went 2nd over 2f out - soon ridden - stayed on - finished 2nd - later awarded the...,winner with non-zero distance
814,54083,2015-05-14,Newmarket,624391,6:55,Chassis Cab DAF Handicap,Flat,7,5,1,0.05,0.05,Excellent Puck (IRE),Chased leaders - ridden to chase leader over 2f out - driven and every chance when bumped 1f out - soon lead - heade...,winner with non-zero distance
815,55633,2015-05-16,Punchestown (IRE),627095,2:40,Punchestown For Events Maiden Hurdle,Hurdle,18,2,1,4.50,4.50,Caledon Craic (IRE),In touch - took closer order in 6th before 4 out - ridden before last and no impression on winner under pressure in ...,winner with non-zero distance
816,56865,2015-05-18,Saint-Cloud (FR),627644,2:55,Prix Sicarelle (Maiden) (3yo Fillies) (Turf),Flat,11,12,1,0.20,0.20,Shiba (FR),Finished 2nd - placed 1st,winner with non-zero distance
817,57452,2015-05-19,Chepstow,625061,3:10,Patricks Perfect Pride of Place Handicap,Flat,8,9,1,0.10,0.10,Oskar Denarius (IRE),Held up - ridden and headway over 3f out - chased winner 2f out - soon hung left - carried right final furlong - clo...,winner with non-zero distance
818,60937,2015-05-27,Hamilton,625863,4:15,Cadzow Castle Fillies Handicap,Flat,9,3,1,0.20,0.20,Lil Sophella (IRE),Slowly into stride - held up - headway to chase leaders when not clear run over 1f out - switched left and challengi...,winner with non-zero distance
819,72898,2015-06-20,Ayr,627940,2:20,Scottish Sun On Sunday Handicap,Flat,6,3,1,0.10,0.10,Intiwin (IRE),Tracked leaders - effort and ridden 2f out - every chance when carried right and baulked inside final furlong - just...,winner with non-zero distance
820,72919,2015-06-20,Compiegne (FR),630164,2:40,Prix Ridgway () (3yo) (Turf),Flat,6,4,1,0.50,0.50,Palace Prince (GER),Held up in rear - ridden 2f out - stayed on and went 2nd towards finish - not quite reach winner - finished 2nd - aw...,winner with non-zero distance
821,76770,2015-06-27,Deauville (FR),630596,1:45,Prix de la Calonne - Fonds Europeen de lElevage () (4yo+ Fillies & Mares) (Polytrack),Flat,9,6,1,2.00,2.00,Persona Grata (GB),Waited with in touch on outer - ridden over 1 1/2f out - stayed on from over 1f out to go 2nd final 150yds - kept on...,winner with non-zero distance
822,78735,2015-07-02,Deauville (FR),631049,12:30,Prix de Ticheville (Maiden) (2yo Colts & Geldings) (Round) (Turf),Flat,11,9,1,1.50,1.50,Post Var (FR),Finished 2nd - placed 1st,winner with non-zero distance
823,85149,2015-07-17,Hamilton,629937,8:45,Jordan Electrics Handicap,Flat,7,6,1,0.20,0.20,Moon Arc (IRE),Tracked leaders - effort and ridden over 2f out - every chance when hampered twice over 1f out - switched left and e...,winner with non-zero distance
824,85425,2015-07-17,Newmarket (July),629959,8:55,Mead Construction Handicap,Flat,12,4,1,0.50,0.50,Zeshov (IRE),Held up in rear of main group - ridden and headway just over 1f out - ran on well under pressure to lead final 75yds...,winner with non-zero distance
825,86478,2015-07-19,Curragh (IRE),629629,3:10,Friarstown Stud Minstrel Stakes,Flat,9,2,1,3.50,3.50,Gordon Lord Byron (IRE),Raced in mid-division - progress to chase leader in 3rd over 2f out on inner - kept on well into 2nd final 100yds - ...,winner with non-zero distance
826,87809,2015-07-23,Limerick (IRE),631934,6:05,Book Online At Limerickraces.ie Mares Novice Hurdle,Hurdle,8,3,1,0.05,0.05,Duckweed (IRE),Chased leaders in 3rd until closer to track leader in 2nd 3 out - challenged in 3rd approaching last - rallied well ...,winner with non-zero distance
827,88733,2015-07-25,Saratoga (USA),632377,10:32,Sanford Stakes (2yo) (Dirt),Flat,10,11,1,0.75,0.75,Uncle Vinny (USA),Finished 2nd - awarded the race,winner with non-zero distance
828,89297,2015-07-26,Saratoga (USA),632338,11:07,Coaching Club American Oaks (3yo Fillies) (Dirt),Flat,7,3,1,0.05,0.05,Curalina (USA),Bumped with rivals leaving stalls - chased leaders - ridden in pursuit of leader from 2f out - ran on gamely under p...,winner with non-zero distance
829,91139,2015-07-31,Goodwood,629332,3:10,Betfred Mile (Heritage Handicap) (formerly known as the Golden Mile),Flat,18,10,1,0.75,0.75,Belgian Bill (GB),Chased leading trio - went 2nd over 1f out - ridden to lead entering final furlong - driven inside final furlong - h...,winner with non-zero distance

In [47]:
# Separate small notation differences from larger contradictions where
# overall distance is smaller than the adjacent margin.
#
# A difference of 0.05 is common in the data and may reflect rounding between
# quarter-length and decimal representations. Larger gaps need inspection.

ovr_btn_less_than_btn_profile = pd.read_sql_query(
    f"""
    SELECT
        ROUND(btn - ovr_btn, 4) AS btn_minus_ovr_btn,
        COUNT(*) AS row_count,
        COUNT(
            DISTINCT date || '|' || course || '|' || off || '|' || race_name
        ) AS apparent_race_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND typeof(ovr_btn) IN ('integer', 'real')
      AND typeof(btn) IN ('integer', 'real')
      AND ovr_btn < btn
    GROUP BY ROUND(btn - ovr_btn, 4)
    ORDER BY btn_minus_ovr_btn
    """,
    connection,
)

material_ovr_btn_contradictions = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        type,
        ran,
        num,
        pos,
        ovr_btn,
        btn,
        ROUND(btn - ovr_btn, 4) AS btn_minus_ovr_btn,
        horse,
        comment
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND typeof(ovr_btn) IN ('integer', 'real')
      AND typeof(btn) IN ('integer', 'real')
      AND ovr_btn < btn
      AND (btn - ovr_btn) > 0.05
    ORDER BY
        btn_minus_ovr_btn DESC,
        date,
        course,
        off,
        pos,
        rowid
    """,
    connection,
)

print(
    "Rows where ovr_btn < btn: "
    f"{ovr_btn_less_than_btn_profile['row_count'].sum():,}"
)
print(
    "Rows where btn exceeds ovr_btn by more than 0.05: "
    f"{len(material_ovr_btn_contradictions):,}"
)

with pd.option_context("display.max_rows", None):
    display(ovr_btn_less_than_btn_profile)

with pd.option_context(
    "display.max_rows",
    100,
    "display.max_colwidth",
    120,
):
    display(material_ovr_btn_contradictions.head(100))

Rows where ovr_btn < btn: 421
Rows where btn exceeds ovr_btn by more than 0.05: 61

    btn_minus_ovr_btn  row_count  apparent_race_count
0                0.05        360                  360
1                1.00          1                    1
2                1.25          2                    2
3                1.50          1                    1
4                2.50          2                    2
5                3.75          1                    1
6                4.00          1                    1
7                4.50          1                    1
8                5.00          2                    2
9                5.50          1                    1
10               6.25          1                    1
11               6.50          1                    1
12               7.00          1                    1
13               7.25          1                    1
14               7.75          1                    1
15               9.25          1                    1
16               9.50          1                    1
17              10.00          1                    1
18              10.25          1                    1
19              10.50          1                    1
20              12.75          2                    2
21              13.00          1                    1
22              13.25          1                    1
23              14.25          1                    1
24              14.50          1                    1
25              15.00          1                    1
26              16.00          3                    3
27              18.00          1                    1
28              18.25          1                    1
29              19.25          2                    2
30              19.50          1                    1
31              20.25          1                    1
32              20.50          1                    1
33              23.25          1                    1
34              23.50          1                    1
35              24.00          1                    1
36              25.50          1                    1
37              26.50          2                    2
38              27.00          1                    1
39              29.00          1                    1
40              33.00          1                    1
41              34.00          1                    1
42              36.00          1                    1
43              36.25          1                    1
44              38.25          1                    1
45              40.00          1                    1
46              40.25          1                    1
47              41.00          1                    1
48              53.00          1                    1
49              56.50          2                    2
50              57.75          1                    1
51              65.25          1                    1
52             138.25          1                    1

,source_rowid,date,course,race_id,off,race_name,type,ran,num,pos,ovr_btn,btn,btn_minus_ovr_btn,horse,comment
0,553992,2018-06-12,Thirsk,702720,3:15,100% Racing UK Profits Back To Racing Handicap,Flat,16,2,16,43.75,182,138.25,Lexington Times (IRE),Effectively refused to race (starter reported gelding had been reluctant to race and virtually refused to race)
1,272120,2016-09-26,Newton Abbot,658353,3:00,Bryan And Ilva Westcott Memorial Novices Hurdle,Hurdle,3,2,3,100.75,166,65.25,Captain Bonsai (GB),Tracked leaders - awkward on bend after 6th - soon lost touch - tailed off
2,202772,2016-05-06,Lingfield (AW),648250,1:30,Heart FM Maiden Stakes,Flat,7,4,7,108.25,166,57.75,Northman (IRE),Pushed along after 3f - under strong pressure by halfway and soon dropped away - tailed off when virtually pulled up...
3,203540,2016-05-07,Lingfield,648279,4:35,betfred.com Handicap,Flat,7,1,7,109.50,166,56.50,Slowfoot (GER),Steadied start - held up in last pair - lost touch 3f out - virtually pulled up final 2f - tailed off (trainer said ...
4,695646,2019-04-13,Wolverhampton (AW),725295,6:30,Betway Sprint Handicap,Flat,10,2,10,109.50,166,56.50,The Establishment (GB),Reared start and lost all chance(op 11/1 tchd 10/1)
5,63575,2015-05-31,Fakenham,626000,4:30,Welcome to Norfolk Princess Charlotte Novices Limited Handicap Chase,Chase,4,5,3,102.00,155,53.00,Radsoc De Sivola (FR),Soon detached in last - tailed off from 7th(op 66/1)
6,302856,2016-11-30,Lingfield (AW),662707,12:10,sunbets.co.uk EBF Maiden Stakes,Flat,7,7,7,114.00,155,41.00,Portland Belle (IRE),Very slowly away - flashing tail and refused to race properly - soon tailed off(op 14/1 tchd 16/1 and 10/1)
7,308624,2016-12-14,Lingfield (AW),663694,3:00,Betway Maiden Stakes,Flat,9,2,9,115.75,156,40.25,Thenobleprankster (IRE),Chased leader 3f out - soon niggled along - lost place and behind 6f out - lost touch quickly 4f out - soon eased an...
8,580608,2018-08-04,Chelmsford (AW),706799,1:40,Bet toteexacta At totesport.com Handicap,Flat,9,5,9,126.00,166,40.00,Fantasy Keeper (GB),Chased leading pair on the outer - niggled along when blowing bend over 3f out - virtually pulled up after (jockey s...
9,582419,2018-08-08,Yarmouth,707176,5:20,Eastern Power Systems Of Norwich Handicap,Flat,7,7,6,106.75,145,38.25,Caledonia Earl (GB),Badly hampered start - always tailed off and hacking along (jockey said gelding was badly hampered by unseated horse...
10,524361,2018-04-22,Stratford,697375,5:15,totepool Betting On All UK Racing Grassroots Hunter Chase,Chase,7,7,5,116.75,153,36.25,The Caller (GB),Always in rear - well behind from 10th - came home in own time(op 8/1)
11,12878,2015-02-11,Lingfield (AW),617696,3:05,32RedPoker.com Handicap,Flat,8,9,8,111.00,147,36.00,Premier Jacks (GB),Took keen hold - led and soon clear - headed 7f out - dropped out rapidly 5f out - tailed final 4f
12,579326,2018-08-02,Stratford,706774,2:00,Priority SMS Selling Hurdle,Hurdle,5,5,4,115.00,149,34.00,Jumbos Boy (GB),Jumped moderately in last - ridden 4th - hopelessly tailed off before 3 out - left 4th at last(op 50/1)
13,751074,2019-07-25,Sandown,733927,2:50,Young Stayers Handicap,Flat,6,1,6,107.00,140,33.00,Summer Moon (GB),Tried to lead but unable to do so - chased leader to halfway - weakened over 4f out - virtually pulled up final 3f (...
14,139256,2015-11-08,Sandown,636884,4:05,Bibendum Wine Standard Open National Hunt Flat Race,NH Flat,9,2,8,118.00,147,29.00,Arroyeau (FR),Held up in touch in last trio - ridden 5f out - soon lost touch - tailed off and virtually pulled up final 3f(op 50/...
15,716292,2019-05-19,Ripon,727796,4:20,Wilmot-Smith Memorial Handicap,Flat,10,5,9,115.00,142,27.00,Knighted (IRE),Chased leader until stumbled on bend under 5f out - lost place quickly - eased when behind final 3f - tailed off (jo...
16,550662,2018-06-06,Wetherby,702048,8:40,Hope & Social Playing Here Live Handicap,Flat,13,1,12,127.50,154,26.50,The Resdev Way (GB),Always in rear - lost touch 4f out - soon well tailed off (vet said gelding was suffering from atrial fibrillation)(...
17,667665,2019-02-06,Kempton (AW),720644,1:50,Move Over To Matchbook Handicap,Flat,10,1,9,112.50,139,26.50,Gabrial The Giant (IRE),Held up in last - badly hampered by faller well over 3f out and eased - virtually pulled - tailed off (jockey said g...
18,766605,2019-08-26,Epsom,736777,4:15,Walter Nightingall Conditions Stakes,Flat,3,1,3,103.50,129,25.50,Desert Fire (IRE),Stumbled badly leaving stalls - rider lost irons - no chance to recover irons and hacked round in rear - tailed off ...
19,345123,2017-03-21,Exeter,669664,3:40,Higos Insurance Services Novices Chase,Chase,3,3,3,110.00,134,24.00,Oscars Way (IRE),Chased leading pair - detached 7th - tailed off when blundered 11th
20,632265,2018-11-09,Fontwell,713890,3:25,Follow The Albion With Seagull Travel Handicap Chase,Chase,6,5,4,111.50,135,23.50,Polo The Mumm (FR),Tracked leaders - pressed leader after 11th until after 4 out - weakened next - tailed off(op 33/1)
21,700275,2019-04-22,Huntingdon,726106,5:10,MansionBet Intermediate Open National Hunt Flat Race,NH Flat,6,6,6,115.75,139,23.25,Dinnerlady (GB),In touch - ridden and weakened quickly halfway - tailed off(op 33/1)
22,776167,2019-09-14,Chelmsford (AW),738150,5:05,Fred Done Handicap,Flat,10,10,10,133.50,154,20.50,Sleepdancer (IRE),Raced awkwardly - in touch towards rear - dropped to last and lost touch 3f out - soon eased - tailed off (jockey sa...
23,746998,2019-07-16,Southwell,734047,9:00,DMRC Benevolence Intermediate Open National Hunt Flat Race,NH Flat,9,2,9,145.75,166,20.25,Alneel (IRE),Raced keenly in midfield - lost place 5f out - soon behind - tailed off (jockey said gelding ran too freely)(op 66/1)
24,508089,2018-03-15,Towcester,694590,3:15,Bet Online Now At starsports.bet Handicap Chase,Chase,5,4,3,103.50,123,19.50,Bobonyx (GB),2nd until left in lead 10th - headed 12th - led again next - ridden 3 out - headed before 2 out - weakened rapidly t...
25,615072,2018-10-10,Southwell,711799,4:50,Mintbet Best Odds Guaranteed Singles & Multiples Newcomers Standard Open National Hunt Flat Race,NH Flat,11,7,11,128.75,148,19.25,Paloma Rosa (GB),Behind - ridden halfway - badly tailed off and virtually pulled up 3f out
26,638567,2018-11-23,Ffos Las,714949,3:25,myracing.com Tips For Every Meeting Standard National Hunt Flat Race (Cond Jockeys And Amateurs),NH Flat,10,11,9,116.75,136,19.25,Fishermans Tale (IRE),Close up until led after 1f - headed 5f out - weakened rapidly - virtually pulled up over 3f out(op 50/1 tchd 80/1)
27,658951,2019-01-10,Catterick,718680,12:25,Racing To School Juvenile Hurdle,Hurdle,7,4,6,114.75,133,18.25,Shandon (IRE),Chased leaders - lost place after 3rd - soon in rear - tailed off after 3 out(op 100/1)
28,758941,2019-08-10,Ascot,735000,1:40,Dubai Duty Free Shergar Cup Stayers (Handicap),Flat,10,4,10,119.00,137,18.00,Alfredo (IRE),Awkward start but soon led - pushed along and headed well over 2f out - heavily eased 2f out - tailed off (jockey sa...
29,272113,2016-09-26,Newton Abbot,658351,2:30,South West Racing Club Novices Chase,Chase,3,3,3,108.00,124,16.00,Oscars Way (IRE),Jumped right - reminders and lost touch 3rd - tailed off
30,565693,2018-07-04,Musselburgh,704587,4:30,TPF Schemes Handicap,Flat,8,1,8,123.00,139,16.00,Tewafeedj (GB),Pulled hard - led until ran wide and saddle slipped bend after 2f - in touch on outside - struggling 3f out - soon l...
31,676267,2019-03-01,Doncaster,721932,4:20,888Sport Take Em On British EBF Mares National Hunt Novices Hurdle (EBF Mares NH Novices Qual),Hurdle,3,3,3,103.00,119,16.00,Big Fiddle (GB),In rear - struggling and left well behind after 7th - jumped badly right 3 out and 2 out when mistake - tailed off (...
32,111754,2015-09-14,Brighton,635193,3:30,Ronald McDonald House Brighton Handicap (Div II),Flat,11,11,11,141.00,156,15.00,Catakanta (GB),In touch in midfield - lost place and ridden 4f out - tailed off and virtually pulled up final 2f
33,410775,2017-07-30,Uttoxeter,680218,4:15,Gordon Banks Novices Chase,Chase,4,4,4,125.50,140,14.50,The Land Agent (IRE),Chased leaders - dropped to rear approaching 4th - well behind 8th - jumped left from 9th and lost touch - tailed of...
34,34677,2015-04-06,Huntingdon,621288,5:50,Flexicruise Intermediate Open National Hunt Flat Race,NH Flat,10,3,8,132.75,147,14.25,Domino King (GB),Took keen hold - held up in last pair - ridden 4f out - soon lost touch - tailed off when hung badly left and came t...
35,355812,2017-04-15,Kempton (AW),671245,3:10,Follow @racing_uk On Twitter Handicap,Flat,10,8,10,116.75,130,13.25,Eljaddaaf (IRE),Reluctant to race and lost all chance - allowed to amble round and hanging left - lame (jockey said the gelding was ...
36,563240,2018-06-29,Doncaster,703999,2:30,Pepsi Max EBF Fillies Novice Stakes (Plus 10 Race),Flat,8,4,8,105.00,118,13.00,Bawtry Lady (GB),Chased leaders when hung badly right to stands' rail after 1 1/2f - soon outpaced and well behind from halfway (jock...
37,483725,2018-01-01,Fakenham,690577,2:30,Happy New Year Handicap Hurdle,Hurdle,6,4,6,106.25,119,12.75,Postbridge (IRE),Led until ridden and headed after 7th - soon dropped to rear and tailed off 3 out(op 25/1)
38,573678,2018-07-21,Ripon,705747,4:05,Ripon Bell-Ringer Handicap,Flat,13,8,13,110.25,123,12.75,Final (GB),Dwelt - never going in rear - eased and tailed off final 4f (jockey said gelding was never travelling; vet reported ...
39,1691983,2025-06-13,Goodwood,895155,5:30,Sir Eric Parker Memorial EBF Restricted Maiden Fillies Stakes (EBF Qual) (GBB/IRE Incentive Race),Flat,9,4,9,112.50,123,10.50,Storm Terri (GB),Soon outpaced and detached - tailed off (jockey said filly ran green)(op 66/1)
40,138172,2015-11-06,Hexham,636843,3:20,Tyneside Samaritans 50th Anniversary Handicap Hurdle,Hurdle,10,5,10,129.75,140,10.25,Tokyo Brown (USA),Pressed leader - lost place 5th - behind after 3 out - eased(op 10/1 tchd 8/1)
41,619067,2018-10-17,Newcastle (AW),712381,5:10,188Bet Extra Place Races Handicap,Flat,14,14,14,127.00,137,10.00,No Civil Justice (GB),Dwelt - took keen hold in rear - struggling over 5f out - soon lost touch - tailed off
42,195445,2016-04-22,Plumpton,647198,5:20,Bet & Watch At coral.co.uk Conditional Jockeys Handicap Chase,Chase,7,4,6,121.50,131,9.50,The Perfect Crime (IRE),Mistake 1st - in touch in midfield - mistake 9th - soon outpaced and behind when not fluent next - soon lost touch -...
43,680461,2019-03-11,Stratford,722890,4:10,BetVictor Horse Racing Multiples Cash Out Novices Hunters Chase,Chase,9,4,5,117.75,127,9.25,Carumba (IRE),Midfield early - tailed off from 8th - still on way to last after rest had finished
44,179221,2016-03-14,Plumpton,644628,2:10,Your Ultimate Cheltenham Guide At attheraces.com/cheltenham National Hunt Novices Hurdle,Hurdle,4,4,3,100.25,108,7.75,The Child (IRE),In touch in rear - reminders after 8th - soon ridden and lost touch - tailed off after next(op 200/1)
45,690098,2019-04-03,Market Rasen,724055,2:30,starsports.bet National Hunt Novices Hurdle,Hurdle,6,7,6,139.75,147,7.25,Molly Whuppie (GB),Led at very slow pace until hung violently left on bend after 5th - tailed off last after blunder 7th - kept hanging...
46,658034,2019-01-07,Wolverhampton (AW),718729,5:45,Betway Live Casino Handicap,Flat,6,3,6,115.00,122,7.00,Jack Bear (GB),Chased leaders - pushed along 5f out - weakened over 3f out (jockey said gelding moved poorly and stopped quickly. p...
47,501673,2018-02-24,Lingfield (AW),693329,5:00,Betway Live Casino Handicap,Flat,11,10,11,110.50,117,6.50,Pivotal Flame (IRE),Chased leaders - ridden 3f out - soon lost place and short of room over 2f out - behind and virtually pulled up from...
48,560717,2018-06-24,Pontefract,703430,4:00,Bet totetrifecta At totesport.com Pontefract Cup Handicap (Round 4 Of The Pontefract Stayers 2018),Flat,7,3,7,108.75,115,6.25,Cool Macavity (IRE),Tracked leader - ridden along over 4f out - weakened 3f out - soon behind and eased
49,128839,2015-10-18,Bath,635390,2:30,Thomas Firbank Removals Handicap,Flat,9,3,9,114.50,120,5.50,Dream Ruler (GB),Slowly away and rousted along - soon chasing leaders - driven 5f out - weakened 3f out - virtually pulled up (traine...
50,659732,2019-01-12,Newcastle (AW),718799,3:30,Betway Casino Handicap,Flat,14,5,14,134.00,139,5.00,Glasgon (GB),In touch - ridden halfway - lost place over 4f out - lost touch and eased final 3f (jockey said gelding weakened qui...
51,660659,2019-01-15,Newcastle,719123,12:45,Sky Sports Racing Sky 415 Newcomers Standard Open NH Flat Race (All-Weather),NH Flat,8,3,8,109.00,114,5.00,Lucky Wind (IRE),Veered badly right and almost unrideable at start - soon well behind - back on even keel after 2f - lost touch final...
52,1827012,2026-04-11,Ascot,917872,10:00,Schweppes - WATC Derby (Turf),Flat,9,5,9,111.50,116,4.50,Sovereign Salute (AUS),
53,693327,2019-04-09,Southwell,724991,2:50,Toalsbet Casino Novices Chase,Chase,4,4,4,118.00,122,4.00,Sussex Road (IRE),Led early - chased leader to 3rd - dropped to rear 6th - lost touch before next - tailed off(op 200/1)
54,403606,2017-07-15,Ascot,678937,5:35,GL Events UK Handicap,Flat,14,12,14,112.25,116,3.75,Anfaass (IRE),Pulled hard - held up - lost action over 2f out and virtually pulled up after (jockey said his saddle slipped)
55,354015,2017-04-11,Lingfield (AW),671210,4:30,Betway Stayers Handicap,Flat,10,9,10,116.50,119,2.50,Shrubland (GB),Chased leading trio - urged along before halfway - weakened rapidly over 5f out - tailed off and virtually pulled up...
56,577065,2018-07-28,Newcastle (AW),706316,4:30,Collingwood Over 50s Insurance Handicap (Div I),Flat,11,7,11,119.50,122,2.50,Good Boy Jasper (GB),Soon well behind - no chance from before halfway (jockey said gelding was never travelling)(op 25/1)
57,498183,2018-02-15,Kelso,692902,4:05,Office Bar Hawick Open Hunters Chase,Chase,5,4,5,111.50,113,1.50,Winged Crusader (IRE),Led to 2nd - chased leader to 7th - outpaced and struggling when hit 2 out (usual 4 out) - soon lost touch - tailed off
58,604433,2018-09-21,Ayr,710240,4:45,BAM Properties Ltd Handicap,Flat,5,5,5,115.75,117,1.25,Dalshand (FR),Tracked leaders until weakened quickly over 3f out - virtually pulled up from over 1f out (jockey said gelding stopp...
59,1730681,2025-09-08,Windsor,901427,4:04,Ivor Laws Memorial Race Novice Stakes (GBB Race),Flat,14,6,14,113.75,115,1.25,Mystery Nituna (GB),Never going well - slowly away - lost touch after 1f - tailed off (jockey said filly was slowly away from stalls and...
60,563151,2018-06-29,Cartmel,703870,3:20,rijo42 Beginners Chase,Chase,7,8,4,119.00,120,1.00,Sussex Road (IRE),Held up - well behind from halfway - came home in own time

In [48]:
# Profile numeric and special finishing-position values separately.
#
# This records the complete stored range and checks whether numeric positions
# exceed the stated number of runners in the race.

position_numeric_profile = pd.read_sql_query(
    f"""
    SELECT
        MIN(
            CASE
                WHEN typeof(pos) = 'integer'
                THEN pos
            END
        ) AS minimum_numeric_position,

        MAX(
            CASE
                WHEN typeof(pos) = 'integer'
                THEN pos
            END
        ) AS maximum_numeric_position,

        COUNT(
            DISTINCT CASE
                WHEN typeof(pos) = 'integer'
                THEN pos
            END
        ) AS distinct_numeric_positions,

        SUM(
            CASE
                WHEN typeof(pos) = 'integer'
                 AND pos < 0
                THEN 1 ELSE 0
            END
        ) AS negative_position_rows,

        SUM(
            CASE
                WHEN typeof(pos) = 'integer'
                 AND pos = 0
                THEN 1 ELSE 0
            END
        ) AS zero_position_rows,

        SUM(
            CASE
                WHEN typeof(pos) = 'integer'
                 AND pos > ran
                THEN 1 ELSE 0
            END
        ) AS position_greater_than_ran_rows
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

position_numeric_distribution = pd.read_sql_query(
    f"""
    SELECT
        pos AS stored_position,
        COUNT(*) AS row_count,
        ROUND(
            100.0 * COUNT(*) /
            (
                SELECT COUNT(*)
                FROM data
                WHERE {DATA_ROW_PREDICATE}
            ),
            4
        ) AS row_pct
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND typeof(pos) = 'integer'
    GROUP BY pos
    ORDER BY pos
    """,
    connection,
)

display(position_numeric_profile)

with pd.option_context("display.max_rows", None):
    display(position_numeric_distribution)

,minimum_numeric_position,maximum_numeric_position,distinct_numeric_positions,negative_position_rows,zero_position_rows,position_greater_than_ran_rows
0,0,34,35,0,8,10

    stored_position  row_count  row_pct
0                 0          8   0.0004
1                 1     189344  10.2277
2                 2     189007  10.2095
3                 3     188141  10.1627
4                 4     184662   9.9748
5                 5     175886   9.5008
6                 6     161327   8.7143
7                 7     142993   7.7240
8                 8     122268   6.6045
9                 9     101726   5.4949
10               10      82495   4.4561
11               11      65421   3.5338
12               12      50715   2.7394
13               13      35507   1.9180
14               14      26002   1.4045
15               15      15392   0.8314
16               16      10532   0.5689
17               17       5388   0.2910
18               18       3507   0.1894
19               19       1952   0.1054
20               20       1394   0.0753
21               21        893   0.0482
22               22        666   0.0360
23               23        441   0.0238
24               24        311   0.0168
25               25        220   0.0119
26               26        149   0.0080
27               27        119   0.0064
28               28         82   0.0044
29               29         56   0.0030
30               30         38   0.0021
31               31         12   0.0006
32               32          9   0.0005
33               33          8   0.0004
34               34          3   0.0002

In [49]:
# Inspect every row where the numeric finishing position exceeds the stated
# number of runners.
#
# This will show whether the mismatch comes from:
# - an incorrect ran value;
# - a malformed finishing position;
# - a race record affected by withdrawals, disqualifications, or incomplete
#   source coverage.

position_exceeds_ran_rows = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        type,
        ran,
        num,
        pos,
        ovr_btn,
        btn,
        horse,
        jockey,
        trainer,
        comment
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND typeof(pos) = 'integer'
      AND pos > ran
    ORDER BY
        date,
        course,
        off,
        pos,
        rowid
    """,
    connection,
)

print(
    "Rows where numeric pos exceeds ran: "
    f"{len(position_exceeds_ran_rows):,}"
)

with pd.option_context(
    "display.max_rows",
    None,
    "display.max_columns",
    None,
    "display.max_colwidth",
    140,
):
    display(position_exceeds_ran_rows)

Rows where numeric pos exceeds ran: 10

,source_rowid,date,course,race_id,off,race_name,type,ran,num,pos,ovr_btn,btn,horse,jockey,trainer,comment
0,270486,2016-09-23,Haydock,657954,5:05,Griffiths And Armour Handicap,Flat,13,14,14,19.75,3.00,Jack Of Diamonds (IRE),Oisin Murphy,Roger Teal,In touch on outer - ridden along over 3f out - soon weakened(op 18/1)
1,330864,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),Flat,18,8,19,15.50,0.75,Pista Olimpica (BRZ),W Blandi,R Solanes,
2,334725,2017-02-23,Meydan (UAE),669525,5:25,Curlin Handicap Sponsored by Al Naboodah SUNWIN Buses (Listed Handicap) (Dirt),Flat,9,9,10,58.75,10.50,Beach Bar (IRE),Tadhg OShea,Brendan Powell,Never better than mid-division
3,854999,2020-04-10,Gulfstream Park (USA),755688,9:41,Allowance Optional Claiming Race (Allowance) (3yo Fillies) (Main Track) (Dirt),Flat,8,6,9,42.25,20.00,Takestwotowiggle (USA),Marcos Meneses,Steve Budhoo,
4,875197,2020-08-15,Merano (ITY),765471,5:55,EBF Terme Di Merano () (3yo+) (Fillies & Mares) (Turf),Flat,6,,7,8.25,0.00,Quita (GB),Ivan Rossi,Waldemar Hickst,In rear of midfield - ridden along over 2f out - kept on - never on terms with leaders
5,875198,2020-08-15,Merano (ITY),765471,5:55,EBF Terme Di Merano () (3yo+) (Fillies & Mares) (Turf),Flat,6,,9,8.25,0.00,Volkovka (FR),Dario Vargiu,Simone Brogi,Prominent - pushed along to chase leader over 3f out - ridden 2f out - limited response - eased when held inside final furlong - btn 20 ...
6,1439296,2023-12-09,Oaklawn Park (USA),857908,10:14,Mistletoe Stakes (Black Type) (Fillies & Mares) (Dirt),Flat,4,,8,5.25,4.50,Effortlesslyelgant (USA),Rafael Bejarano,Norm W Casse,Finished fourth - placed eighth - caused interference
7,1445952,2023-12-23,Gulfstream Park (USA),857782,9:36,Mr. Prospector Stakes (3yo+) (Main Track) (Dirt),Flat,8,3,9,28.25,11.50,Scaramouche (USA),John R Velazquez,Guadalupe Preciado,
8,1461415,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),Flat,16,12,18,18.00,2.50,Kona Coast (JPN),Keita Tosaki,Hisashi Shimizu,
9,1813783,2026-03-13,Meydan,915628,17:45,Binghatti (Handicap) (Dirt),Flat,9,2,10,35.50,20.00,Local Dynasty (IRE),Silvestre De Sousa,Simon & Ed Crisford,Never better than midfield

In [50]:
# Inspect every runner from the races containing pos > ran.
#
# This compares:
# - the repeated ran value;
# - the number of physical source rows;
# - the complete set of finishing positions and status codes.
#
# The aim is to determine whether the mismatch is caused by a single bad row
# or by a race-level convention.

position_exceeds_ran_races = position_exceeds_ran_rows[
    ["date", "course", "off", "race_name"]
].drop_duplicates()

race_condition_parts = []
race_parameters = []

for race in position_exceeds_ran_races.itertuples(index=False):
    race_condition_parts.append(
        "(date = ? AND course = ? AND off = ? AND race_name = ?)"
    )
    race_parameters.extend(
        [race.date, race.course, race.off, race.race_name]
    )

race_condition_sql = " OR ".join(race_condition_parts)

affected_race_rows = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        ran,
        num,
        pos,
        ovr_btn,
        btn,
        horse,
        comment
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND ({race_condition_sql})
    ORDER BY
        date,
        course,
        off,
        CASE
            WHEN typeof(pos) = 'integer' THEN pos
            ELSE 999
        END,
        rowid
    """,
    connection,
    params=race_parameters,
)

affected_race_summary = (
    affected_race_rows
    .groupby(
        ["date", "course", "off", "race_name"],
        as_index=False,
    )
    .agg(
        repeated_ran=("ran", "first"),
        physical_rows=("source_rowid", "count"),
        maximum_numeric_pos=(
            "pos",
            lambda values: max(
                [
                    int(value)
                    for value in values
                    if isinstance(value, int)
                ],
                default=None,
            ),
        ),
        stored_positions=(
            "pos",
            lambda values: " | ".join(
                str(value) for value in values
            ),
        ),
    )
)

display(affected_race_summary)

for race in position_exceeds_ran_races.itertuples(index=False):
    print(
        f"\n{race.date} — {race.course} — "
        f"{race.off} — {race.race_name}"
    )

    race_rows = affected_race_rows.loc[
        (affected_race_rows["date"] == race.date)
        & (affected_race_rows["course"] == race.course)
        & (affected_race_rows["off"] == race.off)
        & (affected_race_rows["race_name"] == race.race_name)
    ]

    with pd.option_context(
        "display.max_rows",
        None,
        "display.max_columns",
        None,
        "display.max_colwidth",
        120,
    ):
        display(race_rows)

,date,course,off,race_name,repeated_ran,physical_rows,maximum_numeric_pos,stored_positions
0,2016-09-23,Haydock,5:05,Griffiths And Armour Handicap,13,13,14,1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | ...
1,2017-02-12,Gavea (BRZ),7:45,Grande Premio Henrique Possollo (3yo Fillies)...,18,18,19,1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | ...
2,2017-02-23,Meydan (UAE),5:25,Curlin Handicap Sponsored by Al Naboodah SUNWI...,9,9,10,1 | 2 | 3 | 4 | 5 | 6 | 7 | 9 | 10
3,2020-04-10,Gulfstream Park (USA),9:41,Allowance Optional Claiming Race (Allowance) (...,8,8,9,1 | 2 | 3 | 5 | 6 | 7 | 8 | 9
4,2020-08-15,Merano (ITY),5:55,EBF Terme Di Merano () (3yo+) (Fillies & Mares...,6,6,9,1 | 2 | 3 | 4 | 7 | 9
5,2023-12-09,Oaklawn Park (USA),10:14,Mistletoe Stakes (Black Type) (Fillies & Mares...,4,4,8,1 | 2 | 3 | 8
6,2023-12-23,Gulfstream Park (USA),9:36,Mr. Prospector Stakes (3yo+) (Main Track) (Dirt),8,8,9,1 | 2 | 3 | 4 | 6 | 7 | 8 | 9
7,2024-02-04,Tokyo (JPN),6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,16,18,1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | ...
8,2026-03-13,Meydan,17:45,Binghatti (Handicap) (Dirt),9,9,10,1 | 2 | 3 | 4 | 5 | 6 | 7 | 9 | 10

2016-09-23 — Haydock — 5:05 — Griffiths And Armour Handicap

,source_rowid,date,course,race_id,off,race_name,ran,num,pos,ovr_btn,btn,horse,comment
0,270465,2016-09-23,Haydock,657954,5:05,Griffiths And Armour Handicap,13,13,1,0.00,0.00,Pumaflor (IRE),Slight lead - headed over 4f out - close up - led again 2f out - ridden well over 1f out - driven inside final furlo...
1,270481,2016-09-23,Haydock,657954,5:05,Griffiths And Armour Handicap,13,8,2,0.20,0.20,Top Beak (IRE),Close up on inner - slight lead over 4f out - ridden and headed 2f out - driven and rallied entering final furlong -...
2,270467,2016-09-23,Haydock,657954,5:05,Griffiths And Armour Handicap,13,11,3,2.50,2.25,Dark Devil (IRE),Tracked leaders - smooth headway on outer over 3f out - close up 2f out - soon ridden and every chance - driven and ...
3,270495,2016-09-23,Haydock,657954,5:05,Griffiths And Armour Handicap,13,2,4,3.00,0.50,Rousayan (IRE),Chased leaders - ridden along over 2f out - driven over 1f out - kept on final furlong(op 7/1)
4,270494,2016-09-23,Haydock,657954,5:05,Griffiths And Armour Handicap,13,10,5,3.50,0.50,Column (GB),Tracked leaders - headway over 3f out - ridden along 2f out - driven over 1f out - kept on same pace
5,270493,2016-09-23,Haydock,657954,5:05,Griffiths And Armour Handicap,13,7,6,4.25,0.75,Wilde Inspiration (IRE),Held up in touch - effort well over 2f out - soon ridden - kept on same pace(op 11/1)
6,270492,2016-09-23,Haydock,657954,5:05,Griffiths And Armour Handicap,13,6,7,5.00,0.75,See The Rock (IRE),Held up in rear - headway over 2f out - ridden well over 1f out - stayed on final furlong - nearest finish
7,270491,2016-09-23,Haydock,657954,5:05,Griffiths And Armour Handicap,13,1,8,5.00,0.05,Fort Bastion (IRE),Held up in rear - headway 2f out - soon ridden and kept on final furlong - nearest finish (jockey said that the geld...
8,270490,2016-09-23,Haydock,657954,5:05,Griffiths And Armour Handicap,13,4,9,5.50,0.50,Commodore (IRE),In touch - headway to chase leaders over 4f out - ridden along over 3f out - one pace final 2f(op 16/1)
9,270489,2016-09-23,Haydock,657954,5:05,Griffiths And Armour Handicap,13,3,10,6.50,1.00,Gratzie (GB),Dwelt and behind - headway on inner 3f out - soon not clear run and never dangerous (jockey said that the mare was s...
10,270488,2016-09-23,Haydock,657954,5:05,Griffiths And Armour Handicap,13,5,11,6.75,0.30,Little Lady Katie (IRE),Tracked leaders on inner - effort 3f out - ridden along over 2f out - soon driven and weakened over 1f out(op 20/1)
11,270487,2016-09-23,Haydock,657954,5:05,Griffiths And Armour Handicap,13,12,12,16.75,10.00,Justice Smart (IRE),Prominent - ridden along well over 2f out - soon weakened
12,270486,2016-09-23,Haydock,657954,5:05,Griffiths And Armour Handicap,13,14,14,19.75,3.00,Jack Of Diamonds (IRE),In touch on outer - ridden along over 3f out - soon weakened(op 18/1)

2017-02-12 — Gavea (BRZ) — 7:45 — Grande Premio Henrique Possollo  (3yo Fillies) (Turf)

,source_rowid,date,course,race_id,off,race_name,ran,num,pos,ovr_btn,btn,horse,comment
13,330842,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,13,1,0.00,0.00,No Regrets (BRZ),
14,330871,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,11,2,2.00,2.00,Vega Sicilia (BRZ),
15,330840,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,3,3,4.25,2.25,Etapa Vencida (BRZ),
16,330839,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,5,4,4.50,0.30,Expense Account (BRZ),
17,330838,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,7,5,5.50,1.00,Envoi De Fleurs (BRZ),
18,330837,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,1,6,6.00,0.50,Kings Gate (BRZ),
19,330836,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,9,7,6.75,0.75,Et La Vie Continue (BRZ),
20,330835,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,15,8,7.50,0.75,Domenica (BRZ),
21,330834,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,4,9,7.75,0.30,Friendlys (BRZ),
22,330849,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,9,10,8.25,0.30,Electora (BRZ),
23,330850,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,14,11,9.50,1.25,Isla De Flores (BRZ),
24,330851,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,10,12,10.75,1.25,Estella Rossa (BRZ),
25,330852,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,1,13,11.75,1.00,Kobe Beef Good (BRZ),
26,330868,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,13,14,12.00,0.30,No No Caroline (BRZ),
27,330867,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,2,15,13.00,1.00,Holy Byblos (BRZ),
28,330866,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,6,16,13.75,0.75,Kanton (BRZ),
29,330865,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,12,17,14.75,1.00,Etoile Des Etoiles (BRZ),
30,330864,2017-02-12,Gavea (BRZ),669090,7:45,Grande Premio Henrique Possollo (3yo Fillies) (Turf),18,8,19,15.50,0.75,Pista Olimpica (BRZ),

2017-02-23 — Meydan (UAE) — 5:25 — Curlin Handicap Sponsored by Al Naboodah SUNWIN Buses (Listed Handicap) (Dirt)

,source_rowid,date,course,race_id,off,race_name,ran,num,pos,ovr_btn,btn,horse,comment
31,334724,2017-02-23,Meydan (UAE),669525,5:25,Curlin Handicap Sponsored by Al Naboodah SUNWIN Buses (Listed Handicap) (Dirt),9,7,1,0.00,0.00,Etijaah (USA),Mid-division - smooth progress 2 1/2f out - led 1 1/2f out - ran on well(op 13/2)
32,334723,2017-02-23,Meydan (UAE),669525,5:25,Curlin Handicap Sponsored by Al Naboodah SUNWIN Buses (Listed Handicap) (Dirt),9,4,2,2.50,2.50,Mubtaahij (IRE),Mid-division - smooth progress 3f out - every chance 1 1/2f out - one pace final 110yds
33,334721,2017-02-23,Meydan (UAE),669525,5:25,Curlin Handicap Sponsored by Al Naboodah SUNWIN Buses (Listed Handicap) (Dirt),9,5,3,7.00,4.50,Alabaster (USA),Tracked leader - led 6f out - ridden clear 3 1/2f out - headed 1 1/2f out - ran on same pace(op 9/4)
34,334720,2017-02-23,Meydan (UAE),669525,5:25,Curlin Handicap Sponsored by Al Naboodah SUNWIN Buses (Listed Handicap) (Dirt),9,6,4,9.75,2.75,Sharpalo (FR),Mid-division - ran on same pace final 2 1/2f
35,334719,2017-02-23,Meydan (UAE),669525,5:25,Curlin Handicap Sponsored by Al Naboodah SUNWIN Buses (Listed Handicap) (Dirt),9,10,5,14.25,4.50,Layl (USA),Slowly into stride - never near to challenge(op 6/1)
36,334718,2017-02-23,Meydan (UAE),669525,5:25,Curlin Handicap Sponsored by Al Naboodah SUNWIN Buses (Listed Handicap) (Dirt),9,3,6,16.50,2.25,Storm Belt (USA),Tracked leader - weakened final 3f(op 16/1)
37,334717,2017-02-23,Meydan (UAE),669525,5:25,Curlin Handicap Sponsored by Al Naboodah SUNWIN Buses (Listed Handicap) (Dirt),9,8,7,17.25,0.75,Gold City (IRE),Slowly away - never near to challenge(op 10/1)
38,334716,2017-02-23,Meydan (UAE),669525,5:25,Curlin Handicap Sponsored by Al Naboodah SUNWIN Buses (Listed Handicap) (Dirt),9,1,9,48.25,31.00,Memorial Day (IRE),Soon led - headed 6f out - soon beaten
39,334725,2017-02-23,Meydan (UAE),669525,5:25,Curlin Handicap Sponsored by Al Naboodah SUNWIN Buses (Listed Handicap) (Dirt),9,9,10,58.75,10.50,Beach Bar (IRE),Never better than mid-division

2020-04-10 — Gulfstream Park (USA) — 9:41 — Allowance Optional Claiming Race (Allowance) (3yo Fillies) (Main Track) (Dirt)

,source_rowid,date,course,race_id,off,race_name,ran,num,pos,ovr_btn,btn,horse,comment
40,854992,2020-04-10,Gulfstream Park (USA),755688,9:41,Allowance Optional Claiming Race (Allowance) (3yo Fillies) (Main Track) (Dirt),8,5,1,0.00,0.00,Finding Fame (USA),
41,854993,2020-04-10,Gulfstream Park (USA),755688,9:41,Allowance Optional Claiming Race (Allowance) (3yo Fillies) (Main Track) (Dirt),8,3,2,1.25,1.25,Sweet Mia (USA),
42,854994,2020-04-10,Gulfstream Park (USA),755688,9:41,Allowance Optional Claiming Race (Allowance) (3yo Fillies) (Main Track) (Dirt),8,9,3,2.25,1.00,Money Never Sleeps (USA),
43,854995,2020-04-10,Gulfstream Park (USA),755688,9:41,Allowance Optional Claiming Race (Allowance) (3yo Fillies) (Main Track) (Dirt),8,8,5,9.00,6.75,Four Graces (USA),
44,854996,2020-04-10,Gulfstream Park (USA),755688,9:41,Allowance Optional Claiming Race (Allowance) (3yo Fillies) (Main Track) (Dirt),8,4,6,13.00,4.00,Four Grands (USA),
45,854997,2020-04-10,Gulfstream Park (USA),755688,9:41,Allowance Optional Claiming Race (Allowance) (3yo Fillies) (Main Track) (Dirt),8,2,7,14.00,1.00,Heiressindy (USA),
46,854998,2020-04-10,Gulfstream Park (USA),755688,9:41,Allowance Optional Claiming Race (Allowance) (3yo Fillies) (Main Track) (Dirt),8,1,8,22.25,8.25,Super Cute (USA),
47,854999,2020-04-10,Gulfstream Park (USA),755688,9:41,Allowance Optional Claiming Race (Allowance) (3yo Fillies) (Main Track) (Dirt),8,6,9,42.25,20.00,Takestwotowiggle (USA),

2020-08-15 — Merano (ITY) — 5:55 — EBF Terme Di Merano () (3yo+) (Fillies & Mares) (Turf)

,source_rowid,date,course,race_id,off,race_name,ran,num,pos,ovr_btn,btn,horse,comment
48,875193,2020-08-15,Merano (ITY),765471,5:55,EBF Terme Di Merano () (3yo+) (Fillies & Mares) (Turf),6,,1,0.00,0.0,Stex (IRE),
49,875194,2020-08-15,Merano (ITY),765471,5:55,EBF Terme Di Merano () (3yo+) (Fillies & Mares) (Turf),6,,2,3.00,3.0,Cima Fire (FR),
50,875195,2020-08-15,Merano (ITY),765471,5:55,EBF Terme Di Merano () (3yo+) (Fillies & Mares) (Turf),6,,3,8.00,5.0,Imsexyandiknowit (IRE),
51,875196,2020-08-15,Merano (ITY),765471,5:55,EBF Terme Di Merano () (3yo+) (Fillies & Mares) (Turf),6,,4,8.25,0.2,Light My Fire (FR),
52,875197,2020-08-15,Merano (ITY),765471,5:55,EBF Terme Di Merano () (3yo+) (Fillies & Mares) (Turf),6,,7,8.25,0.0,Quita (GB),In rear of midfield - ridden along over 2f out - kept on - never on terms with leaders
53,875198,2020-08-15,Merano (ITY),765471,5:55,EBF Terme Di Merano () (3yo+) (Fillies & Mares) (Turf),6,,9,8.25,0.0,Volkovka (FR),Prominent - pushed along to chase leader over 3f out - ridden 2f out - limited response - eased when held inside fin...

2023-12-09 — Oaklawn Park (USA) — 10:14 — Mistletoe Stakes (Black Type) (Fillies & Mares) (Dirt)

,source_rowid,date,course,race_id,off,race_name,ran,num,pos,ovr_btn,btn,horse,comment
54,1439274,2023-12-09,Oaklawn Park (USA),857908,10:14,Mistletoe Stakes (Black Type) (Fillies & Mares) (Dirt),4,,1,0.00,0.0,Butterbean (USA),
55,1439273,2023-12-09,Oaklawn Park (USA),857908,10:14,Mistletoe Stakes (Black Type) (Fillies & Mares) (Dirt),4,,2,0.50,0.5,Misty Veil (USA),
56,1439281,2023-12-09,Oaklawn Park (USA),857908,10:14,Mistletoe Stakes (Black Type) (Fillies & Mares) (Dirt),4,,3,0.75,0.3,Ice Orchid (USA),
57,1439296,2023-12-09,Oaklawn Park (USA),857908,10:14,Mistletoe Stakes (Black Type) (Fillies & Mares) (Dirt),4,,8,5.25,4.5,Effortlesslyelgant (USA),Finished fourth - placed eighth - caused interference

2023-12-23 — Gulfstream Park (USA) — 9:36 — Mr. Prospector Stakes  (3yo+) (Main Track) (Dirt)

,source_rowid,date,course,race_id,off,race_name,ran,num,pos,ovr_btn,btn,horse,comment
58,1445932,2023-12-23,Gulfstream Park (USA),857782,9:36,Mr. Prospector Stakes (3yo+) (Main Track) (Dirt),8,9,1,4.25,4.25,Sibelius (USA),
59,1445951,2023-12-23,Gulfstream Park (USA),857782,9:36,Mr. Prospector Stakes (3yo+) (Main Track) (Dirt),8,7,2,4.00,4.00,Gilmore (USA),
60,1445947,2023-12-23,Gulfstream Park (USA),857782,9:36,Mr. Prospector Stakes (3yo+) (Main Track) (Dirt),8,6,3,9.00,0.75,Dreaming Of Kona (USA),
61,1445948,2023-12-23,Gulfstream Park (USA),857782,9:36,Mr. Prospector Stakes (3yo+) (Main Track) (Dirt),8,8,4,9.00,0.05,Long Range Toddy (USA),
62,1445949,2023-12-23,Gulfstream Park (USA),857782,9:36,Mr. Prospector Stakes (3yo+) (Main Track) (Dirt),8,5,6,9.50,0.50,Hurricane J (USA),
63,1445950,2023-12-23,Gulfstream Park (USA),857782,9:36,Mr. Prospector Stakes (3yo+) (Main Track) (Dirt),8,2,7,10.50,1.00,Howbeit (USA),
64,1445955,2023-12-23,Gulfstream Park (USA),857782,9:36,Mr. Prospector Stakes (3yo+) (Main Track) (Dirt),8,4,8,16.75,6.25,Winfromwithin (USA),
65,1445952,2023-12-23,Gulfstream Park (USA),857782,9:36,Mr. Prospector Stakes (3yo+) (Main Track) (Dirt),8,3,9,28.25,11.50,Scaramouche (USA),

2024-02-04 — Tokyo (JPN) — 6:45 — Tokyo Shimbun Hai  (4yo+) (Turf)

,source_rowid,date,course,race_id,off,race_name,ran,num,pos,ovr_btn,btn,horse,comment
66,1461428,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,1,1,0.00,0.00,Sakura Toujours (JPN),
67,1461427,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,5,2,1.00,1.00,Win Carnelian (JPN),
68,1461598,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,8,3,1.25,0.30,Ho O Biscuits (JPN),
69,1461426,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,2,4,1.25,0.05,Ask Konnamonda (JPN),
70,1461425,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,11,5,2.00,0.75,Matenro Sky (JPN),Prominent early - soon dropped into midfield - pushed along to close over 2f out - challenged for places approaching...
71,1461424,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,6,6,2.50,0.30,Masked Diva (JPN),
72,1461423,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,16,7,3.25,0.75,Avverare (JPN),
73,1461422,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,4,8,3.75,0.50,Rouge Lignage (JPN),
74,1461421,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,9,9,3.75,0.20,Umbrail (JPN),
75,1461420,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,13,10,4.25,0.30,Tudo De Bom (JPN),
76,1461419,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,15,11,4.50,0.30,Hrimfaxi (JPN),
77,1461411,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,7,12,7.00,2.50,Justin Cafe (JPN),
78,1461418,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,3,13,8.50,1.50,Dolce More (JPN),
79,1461417,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,14,14,11.50,3.00,Sound Vivace (JPN),
80,1461416,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,10,15,15.50,4.00,Danon Touchdown (JPN),
81,1461415,2024-02-04,Tokyo (JPN),860553,6:45,Tokyo Shimbun Hai (4yo+) (Turf),16,12,18,18.00,2.50,Kona Coast (JPN),

2026-03-13 — Meydan — 17:45 — Binghatti (Handicap) (Dirt)

,source_rowid,date,course,race_id,off,race_name,ran,num,pos,ovr_btn,btn,horse,comment
82,1813775,2026-03-13,Meydan,915628,17:45,Binghatti (Handicap) (Dirt),9,3,1,0.00,0.00,Diamond Dealer (USA),Prominent - led after 1f - joined 5f out - against far rail and clear when ridden over 1f out - went further clear i...
83,1813776,2026-03-13,Meydan,915628,17:45,Binghatti (Handicap) (Dirt),9,5,2,2.75,2.75,Nam Phrik (BRZ),Towards rear - hung left but steady headway 2f out - went second towards finish - no match for winner
84,1813777,2026-03-13,Meydan,915628,17:45,Binghatti (Handicap) (Dirt),9,6,3,3.00,0.30,Jolly Roger (IRE),In touch with leaders on outer early - soon midfield - headway on inner over 3f out - went second inside final furlo...
85,1813778,2026-03-13,Meydan,915628,17:45,Binghatti (Handicap) (Dirt),9,4,4,3.75,0.75,Gun Carriage (USA),Soon prominent - joined leader 5f out - lost position over 2f out - weakened over 1f out
86,1813779,2026-03-13,Meydan,915628,17:45,Binghatti (Handicap) (Dirt),9,8,5,4.75,1.00,Nyaar (USA),Reared in stalls before start - led - prominent after 1f - weakened 2f out
87,1813780,2026-03-13,Meydan,915628,17:45,Binghatti (Handicap) (Dirt),9,1,6,6.00,1.25,Shaq Diesel (USA),In touch with leaders - on outer when outpaced 3f out - weakened under 2f out
88,1813781,2026-03-13,Meydan,915628,17:45,Binghatti (Handicap) (Dirt),9,7,7,7.50,1.50,Laasudood (USA),Prominent early - soon in touch with leaders - outpaced 4f out - some headway over 2f out - weakened inside final fu...
89,1813782,2026-03-13,Meydan,915628,17:45,Binghatti (Handicap) (Dirt),9,9,9,15.50,8.00,Quality Humor (USA),Reared in stalls before start - in rear - soon switched right and on outer - weakened over 2f out
90,1813783,2026-03-13,Meydan,915628,17:45,Binghatti (Handicap) (Dirt),9,2,10,35.50,20.00,Local Dynasty (IRE),Never better than midfield

### Result and finishing fields — interim findings

#### `pos`

`pos` uses mixed SQLite storage:

- 1,756,674 integer rows;
- 94,611 text rows;
- no SQL `NULL` values;
- no blank text values.

Numeric positions range from `0` to `34`.

Eight rows contain `pos = 0`. They occur in only two international races and appear to represent unresolved or unavailable placings rather than a normal finishing position.

The text values are finishing-status codes:

- `PU`;
- `F`;
- `UR`;
- `BD`;
- `RR`;
- `DSQ`;
- `RO`;
- `SU`;
- `REF`;
- `CO`;
- `LFT`.

Most text-status rows have `-` in both distance fields. `DSQ` is the exception: all 619 disqualified runners retain numeric `ovr_btn` and `btn` values.

Numeric `pos` is not guaranteed to form a dense sequence from `1` to `ran`.

Ten rows have `pos > ran`, but whole-race inspection showed that:

- `ran` still matches the number of physical runner rows;
- the stored position sequence contains gaps;
- demotions and revised official placings can produce positions greater than the number of stored runners.

Therefore, `pos <= ran` and contiguous-position checks would be invalid universal quality rules.

#### `ovr_btn` and `btn`

Both fields use mixed numeric and text storage.

`ovr_btn` contains:

- integers;
- real numbers;
- 93,992 text values.

`btn` contains:

- integers;
- real numbers;
- the same 93,992 text values.

Every text row contains `-` in both fields. There are no rows where only one of the two fields contains `-`.

Numeric ranges are:

- `ovr_btn`: `0` to `331.5`;
- `btn`: `0` to `186`.

No negative values occur.

The observed structure is consistent with:

- `ovr_btn` representing a cumulative or overall distance;
- `btn` representing a local or adjacent finishing margin.

This interpretation remains provisional until confirmed against source documentation.

Most winners have zero in both distance fields. Exceptions are largely explained by promoted winners whose comments state that they originally finished behind another horse and were later awarded the race.

Likewise, many non-winners with zero overall distance were originally first past the post and later demoted or disqualified.

There are 421 rows where `ovr_btn < btn`:

- 360 differ by exactly `0.05`, commonly `0.25` versus `0.3`, and appear to reflect notation or rounding differences;
- 61 contain larger contradictions, concentrated among tailed-off, eased, reluctant, virtually pulled-up, or otherwise abnormal performances.

These 61 rows should be flagged for investigation, not automatically corrected.

#### Cleaning implications

- Preserve the raw `pos`, `ovr_btn`, and `btn` values.
- Derive separate numeric and status representations for `pos`.
- Treat `pos = 0` as a special unresolved state.
- Do not assume finishing positions are contiguous.
- Do not enforce `pos <= ran`.
- Convert `-` in the distance fields to an explicit missing or not-applicable state only in a derived layer.
- Retain a quality flag for material cases where `ovr_btn < btn`.
- Do not overwrite promoted, demoted, or disqualified official placings using the stored distance values.

In [51]:
# Identify the source fields that have not yet been profiled.
#
# This prevents us from relying on memory or assumptions about the remaining
# schema and gives us the exact next field group to examine.

profiled_fields = {
    # Race and event description
    "date",
    "course",
    "race_id",
    "off",
    "race_name",
    "type",
    "class",
    "pattern",
    "rating_band",
    "age_band",
    "sex_rest",
    "dist",
    "going",
    "ran",

    # Runner identity and demographics
    "num",
    "horse",
    "age",
    "sex",
    "jockey",
    "trainer",

    # Result and finishing information
    "pos",
    "ovr_btn",
    "btn",
}

remaining_source_fields = (
    source_data_dictionary.loc[
        ~source_data_dictionary["field_name"].isin(profiled_fields)
    ]
    .reset_index(drop=True)
)

print(
    "Remaining unprofiled source fields: "
    f"{len(remaining_source_fields)}"
)

display(remaining_source_fields)

Remaining unprofiled source fields: 14

,column_position,field_name,declared_sqlite_type,declared_not_null,declared_default,declared_primary_key
0,17,draw,INTEGER,0,None,0
1,23,wgt,TEXT,0,None,0
2,24,hg,TEXT,0,None,0
3,25,time,TEXT,0,None,0
4,26,sp,TEXT,0,None,0
5,29,prize,INTEGER,0,None,0
6,30,or,INTEGER,0,None,0
7,31,rpr,INTEGER,0,None,0
8,32,ts,INTEGER,0,None,0
9,33,sire,TEXT,0,None,0
10,34,dam,TEXT,0,None,0
11,35,damsire,TEXT,0,None,0
12,36,owner,TEXT,0,None,0
13,37,comment,TEXT,0,None,0

In [52]:
# Profile the next source-quality group:
# draw, weight, headgear, race time, and starting price.
#
# This first pass records missingness, distinct counts, and SQLite storage
# classes without yet interpreting the field formats.

setup_market_fields = [
    "draw",
    "wgt",
    "hg",
    "time",
    "sp",
]

setup_market_profile_rows = []

for field in setup_market_fields:
    quoted_field = f'"{field}"'

    result = pd.read_sql_query(
        f"""
        SELECT
            COUNT(*) AS total_rows,

            SUM(
                CASE
                    WHEN {quoted_field} IS NULL
                    THEN 1 ELSE 0
                END
            ) AS null_count,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) = 'text'
                     AND length(trim({quoted_field})) = 0
                    THEN 1 ELSE 0
                END
            ) AS blank_text_count,

            COUNT(DISTINCT {quoted_field})
                AS distinct_non_null_values,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) = 'null'
                    THEN 1 ELSE 0
                END
            ) AS storage_null,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) = 'integer'
                    THEN 1 ELSE 0
                END
            ) AS storage_integer,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) = 'real'
                    THEN 1 ELSE 0
                END
            ) AS storage_real,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) = 'text'
                    THEN 1 ELSE 0
                END
            ) AS storage_text,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) = 'blob'
                    THEN 1 ELSE 0
                END
            ) AS storage_blob
        FROM data
        WHERE {DATA_ROW_PREDICATE}
        """,
        connection,
    ).iloc[0].to_dict()

    result["field_name"] = field

    result["declared_sqlite_type"] = (
        source_data_dictionary.loc[
            source_data_dictionary["field_name"] == field,
            "declared_sqlite_type",
        ].iloc[0]
    )

    setup_market_profile_rows.append(result)

setup_market_quality = pd.DataFrame(
    setup_market_profile_rows
)[
    [
        "field_name",
        "declared_sqlite_type",
        "total_rows",
        "null_count",
        "blank_text_count",
        "distinct_non_null_values",
        "storage_null",
        "storage_integer",
        "storage_real",
        "storage_text",
        "storage_blob",
    ]
]

display(setup_market_quality)

,field_name,declared_sqlite_type,total_rows,null_count,blank_text_count,distinct_non_null_values,storage_null,storage_integer,storage_real,storage_text,storage_blob
0,draw,INTEGER,1851285,0,592778,38,0,1258507,0,592778,0
1,wgt,TEXT,1851285,0,0,79,0,0,0,1851285,0
2,hg,TEXT,1851285,0,1122490,61,0,0,0,1851285,0
3,time,TEXT,1851285,0,0,46537,0,0,0,1851285,0
4,sp,TEXT,1851285,0,9097,843,0,0,0,1851285,0

In [53]:
# Inspect the stored-value distributions for draw, weight, headgear, time,
# and starting price.
#
# For low-cardinality fields, show all values.
# For time and starting price, show the most common values first because
# their distinct-value counts are much larger.

setup_market_value_limits = {
    "draw": None,
    "wgt": None,
    "hg": None,
    "time": 50,
    "sp": 100,
}

for field in setup_market_fields:
    quoted_field = f'"{field}"'
    row_limit = setup_market_value_limits[field]

    limit_sql = (
        ""
        if row_limit is None
        else f"LIMIT {row_limit}"
    )

    value_distribution = pd.read_sql_query(
        f"""
        SELECT
            CASE
                WHEN typeof({quoted_field}) = 'text'
                 AND length({quoted_field}) = 0
                THEN '<blank>'
                ELSE CAST({quoted_field} AS TEXT)
            END AS stored_value,

            typeof({quoted_field}) AS storage_class,

            COUNT(*) AS row_count,

            ROUND(
                100.0 * COUNT(*) /
                (
                    SELECT COUNT(*)
                    FROM data
                    WHERE {DATA_ROW_PREDICATE}
                ),
                4
            ) AS row_pct
        FROM data
        WHERE {DATA_ROW_PREDICATE}
        GROUP BY
            {quoted_field},
            typeof({quoted_field})
        ORDER BY
            row_count DESC,
            stored_value
        {limit_sql}
        """,
        connection,
    )

    print(f"\n{field.upper()} — STORED VALUES")

    with pd.option_context(
        "display.max_rows",
        None,
        "display.max_colwidth",
        120,
    ):
        display(value_distribution)

DRAW — STORED VALUES

   stored_value storage_class  row_count  row_pct
0       <blank>          text     592778  32.0198
1             3       integer     118714   6.4125
2             2       integer     118683   6.4108
3             1       integer     118603   6.4065
4             4       integer     118128   6.3809
5             5       integer     116584   6.2975
6             6       integer     112277   6.0648
7             7       integer     104480   5.6436
8             8       integer      94065   5.0811
9             9       integer      81576   4.4065
10           10       integer      68892   3.7213
11           11       integer      56467   3.0502
12           12       integer      45996   2.4845
13           13       integer      32529   1.7571
14           14       integer      25697   1.3881
15           15       integer      15494   0.8369
16           16       integer      12180   0.6579
17           17       integer       6482   0.3501
18           18       integer       3912   0.2113
19           19       integer       2223   0.1201
20           20       integer       1662   0.0898
21           21       integer       1008   0.0544
22           22       integer        745   0.0402
23           23       integer        527   0.0285
24           24       integer        361   0.0195
25           25       integer        290   0.0157
26           26       integer        220   0.0119
27           27       integer        176   0.0095
28           28       integer        142   0.0077
29           29       integer        114   0.0062
30           30       integer         84   0.0045
31           31       integer         69   0.0037
32           32       integer         48   0.0026
33           33       integer         43   0.0023
34           35       integer         14   0.0008
35           34       integer         13   0.0007
36           36       integer          7   0.0004
37           37       integer          2   0.0001

WGT — STORED VALUES

   stored_value storage_class  row_count  row_pct
0           9-0          text     127748   6.9005
1           9-2          text     117269   6.3345
2           9-5          text      81374   4.3955
3          8-11          text      74459   4.0220
4           9-7          text      71569   3.8659
5           9-4          text      70493   3.8078
6           9-3          text      62768   3.3905
7          8-13          text      61389   3.3160
8           9-6          text      58025   3.1343
9           9-1          text      57427   3.1020
10          8-9          text      52462   2.8338
11         8-10          text      48396   2.6142
12         11-0          text      42599   2.3011
13          8-8          text      40791   2.2034
14          9-9          text      40031   2.1623
15         8-12          text      39128   2.1136
16          8-7          text      38736   2.0924
17        10-12          text      35570   1.9214
18         11-7          text      34938   1.8872
19         11-4          text      33471   1.8080
20          9-8          text      33285   1.7979
21         11-2          text      32730   1.7680
22        11-12          text      32580   1.7599
23          8-6          text      30236   1.6332
24         11-5          text      30108   1.6263
25        10-11          text      21455   1.1589
26         11-3          text      21395   1.1557
27         9-11          text      21218   1.1461
28        10-10          text      21212   1.1458
29         11-9          text      21152   1.1426
30          8-5          text      21129   1.1413
31         10-8          text      20992   1.1339
32        10-13          text      20755   1.1211
33         9-10          text      20293   1.0962
34         10-9          text      19108   1.0321
35         11-6          text      19056   1.0293
36         10-6          text      19028   1.0278
37         11-1          text      18309   0.9890
38         10-0          text      18144   0.9801
39         10-7          text      17231   0.9308
40          8-4          text      16033   0.8660
41        11-10          text      15231   0.8227
42         9-12          text      15072   0.8141
43         11-8          text      14865   0.8030
44         10-2          text      14141   0.7638
45         12-0          text      13379   0.7227
46         10-3          text      12686   0.6853
47         9-13          text      12526   0.6766
48        11-11          text      12002   0.6483
49         10-5          text      11372   0.6143
50          8-3          text      11193   0.6046
51         10-1          text      10544   0.5696
52         10-4          text      10331   0.5580
53          8-2          text       8819   0.4764
54          8-0          text       5434   0.2935
55          8-1          text       4384   0.2368
56        11-13          text       4021   0.2172
57         7-13          text       2711   0.1464
58         7-11          text       1706   0.0922
59         7-12          text       1662   0.0898
60         12-2          text       1454   0.0785
61         12-1          text       1219   0.0658
62         7-10          text        605   0.0327
63          7-9          text        559   0.0302
64         12-3          text        356   0.0192
65          7-8          text        244   0.0132
66         12-4          text        219   0.0118
67         12-6          text        135   0.0073
68          7-7          text        115   0.0062
69         12-5          text         90   0.0049
70         12-7          text         73   0.0039
71         12-8          text         16   0.0009
72          7-6          text         13   0.0007
73          7-5          text          9   0.0005
74         12-9          text          3   0.0002
75        12-10          text          1   0.0001
76        12-11          text          1   0.0001
77         6-12          text          1   0.0001
78         6-13          text          1   0.0001

HG — STORED VALUES

   stored_value storage_class  row_count  row_pct
0       <blank>          text    1122490  60.6330
1             t          text     178727   9.6542
2             p          text     173713   9.3834
3             b          text     128859   6.9605
4             h          text      62258   3.3630
5            tp          text      52073   2.8128
6             v          text      40585   2.1923
7            tb          text      40299   2.1768
8            ht          text      22190   1.1986
9            tv          text       9729   0.5255
10          e/s          text       2943   0.1590
11           hp          text       2423   0.1309
12           hb          text       2094   0.1131
13           et          text       1544   0.0834
14           p1          text       1530   0.0826
15          htb          text       1306   0.0705
16           t1          text       1129   0.0610
17           eb          text        996   0.0538
18          htp          text        821   0.0443
19           h1          text        800   0.0432
20          het          text        744   0.0402
21           b1          text        732   0.0395
22           he          text        673   0.0364
23          tp1          text        588   0.0318
24           v1          text        414   0.0224
25           hv          text        394   0.0213
26          tb1          text        284   0.0153
27          ht1          text        242   0.0131
28          etb          text        159   0.0086
29          tv1          text        131   0.0071
30          htv          text        106   0.0057
31          heb          text         56   0.0030
32            e          text         48   0.0026
33         e/sp          text         34   0.0018
34           bp          text         32   0.0017
35          hp1          text         23   0.0012
36         e/s1          text         22   0.0012
37           vp          text         16   0.0009
38          tbp          text         11   0.0006
39          hep          text          8   0.0004
40          hb1          text          7   0.0004
41         htp1          text          7   0.0004
42          et1          text          6   0.0003
43           hc          text          5   0.0003
44         hetb          text          5   0.0003
45          eb1          text          4   0.0002
46          he1          text          3   0.0002
47         het1          text          3   0.0002
48          cvp          text          2   0.0001
49         etb1          text          2   0.0001
50          hct          text          2   0.0001
51          hev          text          2   0.0001
52         htb1          text          2   0.0001
53          tvp          text          2   0.0001
54          bp1          text          1   0.0001
55          etp          text          1   0.0001
56           ev          text          1   0.0001
57         heb1          text          1   0.0001
58         hetp          text          1   0.0001
59         htbp          text          1   0.0001
60         tbp1          text          1   0.0001

TIME — STORED VALUES

   stored_value storage_class  row_count  row_pct
0             -          text      94408   5.0996
1       1:13.75          text        374   0.0202
2       1:13.95          text        351   0.0190
3       1:13.30          text        350   0.0189
4       1:10.90          text        348   0.0188
5       1:14.00          text        347   0.0187
6       1:12.85          text        345   0.0186
7       1:13.90          text        342   0.0185
8       1:40.52          text        340   0.0184
9       1:13.60          text        338   0.0183
10      1:13.35          text        334   0.0180
11      1:12.70          text        333   0.0180
12      1:39.80          text        333   0.0180
13      1:12.90          text        332   0.0179
14      1:13.80          text        332   0.0179
15      1:14.20          text        331   0.0179
16      1:39.75          text        330   0.0178
17      1:14.07          text        329   0.0178
18      1:13.77          text        328   0.0177
19      1:40.55          text        328   0.0177
20      1:14.65          text        327   0.0177
21      1:13.22          text        325   0.0176
22      1:14.10          text        325   0.0176
23      1:12.80          text        324   0.0175
24      1:13.50          text        324   0.0175
25      1:13.65          text        324   0.0175
26      1:10.56          text        323   0.0174
27      1:13.00          text        323   0.0174
28      1:13.55          text        323   0.0174
29      1:40.25          text        323   0.0174
30      1:40.70          text        323   0.0174
31      1:13.31          text        322   0.0174
32      1:14.50          text        322   0.0174
33      1:13.17          text        321   0.0173
34      1:12.48          text        320   0.0173
35      1:40.85          text        320   0.0173
36      1:13.16          text        319   0.0172
37      1:13.20          text        319   0.0172
38      1:40.00          text        319   0.0172
39      1:12.57          text        318   0.0172
40      1:13.25          text        318   0.0172
41      1:13.40          text        318   0.0172
42      1:12.96          text        317   0.0171
43      1:13.83          text        317   0.0171
44      1:14.60          text        317   0.0171
45      1:13.45          text        316   0.0171
46      1:13.56          text        316   0.0171
47      1:40.59          text        316   0.0171
48      1:13.28          text        315   0.0170
49      1:13.66          text        315   0.0170

SP — STORED VALUES

   stored_value storage_class  row_count  row_pct
0          12/1          text      72682   3.9260
1          16/1          text      72258   3.9031
2          14/1          text      66930   3.6153
3          25/1          text      64100   3.4625
4          10/1          text      63656   3.4385
5          33/1          text      63615   3.4363
6          20/1          text      61820   3.3393
7           8/1          text      56458   3.0497
8           9/1          text      49756   2.6876
9          50/1          text      48761   2.6339
10          7/1          text      46828   2.5295
11          6/1          text      43995   2.3765
12          5/1          text      43611   2.3557
13         11/1          text      41853   2.2608
14          9/2          text      41078   2.2189
15         40/1          text      40049   2.1633
16          4/1          text      38722   2.0916
17         66/1          text      37458   2.0234
18         11/2          text      33534   1.8114
19        100/1          text      33079   1.7868
20         28/1          text      29989   1.6199
21         18/1          text      29545   1.5959
22          7/2          text      29088   1.5712
23         13/2          text      28976   1.5652
24         22/1          text      28182   1.5223
25         15/2          text      24144   1.3042
26          3/1          text      19619   1.0598
27         80/1          text      17890   0.9664
28         17/2          text      17686   0.9553
29        150/1          text      14087   0.7609
30       100/30          text      13605   0.7349
31        200/1          text      11856   0.6404
32         11/4          text      11477   0.6199
33         2/1F          text      11095   0.5993
34          5/2          text      10984   0.5933
35        125/1          text      10540   0.5693
36         5/2F          text      10334   0.5582
37         9/4F          text       9479   0.5120
38         3/1F          text       9398   0.5076
39      <blank>          text       9097   0.4914
40         13/1          text       8485   0.4583
41         6/4F          text       7971   0.4306
42        11/4F          text       7883   0.4258
43         15/1          text       7301   0.3944
44          9/4          text       6991   0.3776
45         7/4F          text       6657   0.3596
46        250/1          text       6586   0.3558
47         30/1          text       6401   0.3458
48         17/1          text       6322   0.3415
49         7/2F          text       6286   0.3395
50        11/8F          text       5620   0.3036
51         5/4F          text       5615   0.3033
52       EvensF          text       5553   0.3000
53        15/8F          text       5502   0.2972
54          2/1          text       5429   0.2933
55        13/8F          text       5326   0.2877
56         19/1          text       5150   0.2782
57       11/10F          text       5141   0.2777
58         4/1F          text       4500   0.2431
59         26/1          text       4218   0.2278
60      100/30F          text       4171   0.2253
61         21/1          text       3959   0.2139
62         6/5F          text       3895   0.2104
63         23/1          text       3657   0.1975
64         29/1          text       3593   0.1941
65         24/1          text       3466   0.1872
66         27/1          text       3434   0.1855
67       10/11F          text       3433   0.1854
68         16/5          text       3358   0.1814
69         4/5F          text       3233   0.1746
70        300/1          text       3226   0.1743
71         31/1          text       3223   0.1741
72         32/1          text       2978   0.1609
73         34/1          text       2854   0.1542
74         7/2J          text       2797   0.1511
75         3/1J          text       2782   0.1503
76         36/1          text       2771   0.1497
77         35/1          text       2706   0.1462
78         4/1J          text       2630   0.1421
79         5/6F          text       2598   0.1403
80         18/5          text       2494   0.1347
81        8/11F          text       2494   0.1347
82         60/1          text       2447   0.1322
83         37/1          text       2415   0.1304
84         9/2F          text       2404   0.1299
85         38/1          text       2338   0.1263
86         19/5          text       2248   0.1214
87         39/1          text       2218   0.1198
88         15/8          text       2193   0.1185
89          7/4          text       2175   0.1175
90         41/1          text       2071   0.1119
91         4/6F          text       2047   0.1106
92         42/1          text       2017   0.1090
93        63/10          text       2002   0.1081
94        48/10          text       1977   0.1068
95        58/10          text       1970   0.1064
96        53/10          text       1966   0.1062
97        43/10          text       1929   0.1042
98        67/10          text       1928   0.1041
99         5/2J          text       1924   0.1039

In [54]:
# Validate the structural formats of draw, weight, time, and starting price.
#
# This identifies rows that do not match the dominant observed patterns:
# - draw: blank or positive integer;
# - wgt: stone-pounds text such as 9-0;
# - time: dash or M:SS.xx / MM:SS.xx;
# - sp: blank, Evens, or fractional odds with optional suffixes.
#
# The patterns are descriptive checks only. They do not alter source values.

format_validation_summary = pd.read_sql_query(
    f"""
    SELECT
        SUM(
            CASE
                WHEN typeof(draw) = 'text'
                 AND length(trim(draw)) = 0
                THEN 0
                WHEN typeof(draw) = 'integer'
                 AND draw >= 1
                THEN 0
                ELSE 1
            END
        ) AS invalid_draw_rows,

        SUM(
            CASE
                WHEN wgt GLOB '[0-9]-[0-9]'
                  OR wgt GLOB '[0-9]-[0-9][0-9]'
                  OR wgt GLOB '[0-9][0-9]-[0-9]'
                  OR wgt GLOB '[0-9][0-9]-[0-9][0-9]'
                THEN 0
                ELSE 1
            END
        ) AS invalid_weight_format_rows,

        SUM(
            CASE
                WHEN time = '-'
                THEN 0
                WHEN time GLOB '[0-9]:[0-9][0-9].[0-9][0-9]'
                  OR time GLOB '[0-9][0-9]:[0-9][0-9].[0-9][0-9]'
                THEN 0
                ELSE 1
            END
        ) AS invalid_time_format_rows,

        SUM(
            CASE
                WHEN length(trim(sp)) = 0
                THEN 0
                WHEN sp IN (
                    'Evens',
                    'EvensF',
                    'EvensJ',
                    'EvensJF'
                )
                THEN 0
                WHEN sp GLOB '[0-9]*/[0-9]*'
                  OR sp GLOB '[0-9]*/[0-9]*F'
                  OR sp GLOB '[0-9]*/[0-9]*J'
                  OR sp GLOB '[0-9]*/[0-9]*JF'
                THEN 0
                ELSE 1
            END
        ) AS invalid_sp_format_rows
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

weight_components = pd.read_sql_query(
    f"""
    SELECT
        MIN(CAST(substr(wgt, 1, instr(wgt, '-') - 1) AS INTEGER))
            AS minimum_stone,

        MAX(CAST(substr(wgt, 1, instr(wgt, '-') - 1) AS INTEGER))
            AS maximum_stone,

        MIN(CAST(substr(wgt, instr(wgt, '-') + 1) AS INTEGER))
            AS minimum_pounds_component,

        MAX(CAST(substr(wgt, instr(wgt, '-') + 1) AS INTEGER))
            AS maximum_pounds_component,

        SUM(
            CASE
                WHEN CAST(
                    substr(wgt, instr(wgt, '-') + 1)
                    AS INTEGER
                ) >= 14
                THEN 1 ELSE 0
            END
        ) AS pounds_component_14_or_more
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

display(format_validation_summary)
display(weight_components)

,invalid_draw_rows,invalid_weight_format_rows,invalid_time_format_rows,invalid_sp_format_rows
0,0,0,289743,182

,minimum_stone,maximum_stone,minimum_pounds_component,maximum_pounds_component,pounds_component_14_or_more
0,6,12,0,13,0

In [55]:
# Inspect values rejected by the provisional time and starting-price patterns.
#
# The earlier validation deliberately used narrow patterns. This cell shows
# the actual rejected values so that the accepted formats can be based on
# evidence rather than assumptions.

invalid_time_values = pd.read_sql_query(
    f"""
    SELECT
        time AS stored_time,
        COUNT(*) AS row_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND time <> '-'
      AND NOT (
            time GLOB '[0-9]:[0-9][0-9].[0-9][0-9]'
         OR time GLOB '[0-9][0-9]:[0-9][0-9].[0-9][0-9]'
      )
    GROUP BY time
    ORDER BY
        row_count DESC,
        stored_time
    """,
    connection,
)

invalid_sp_values = pd.read_sql_query(
    f"""
    SELECT
        CASE
            WHEN length(trim(sp)) = 0
            THEN '<blank>'
            ELSE sp
        END AS stored_sp,
        COUNT(*) AS row_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND length(trim(sp)) > 0
      AND sp NOT IN (
            'Evens',
            'EvensF',
            'EvensJ',
            'EvensJF'
      )
      AND NOT (
            sp GLOB '[0-9]*/[0-9]*'
         OR sp GLOB '[0-9]*/[0-9]*F'
         OR sp GLOB '[0-9]*/[0-9]*J'
         OR sp GLOB '[0-9]*/[0-9]*JF'
      )
    GROUP BY sp
    ORDER BY
        row_count DESC,
        stored_sp
    """,
    connection,
)

print(
    "Distinct time values rejected by provisional pattern: "
    f"{len(invalid_time_values):,}"
)
print(
    "Rows represented by rejected time values: "
    f"{invalid_time_values['row_count'].sum():,}"
)

with pd.option_context(
    "display.max_rows",
    150,
    "display.max_colwidth",
    120,
):
    display(invalid_time_values.head(150))

print(
    "\nDistinct SP values rejected by provisional pattern: "
    f"{len(invalid_sp_values):,}"
)
print(
    "Rows represented by rejected SP values: "
    f"{invalid_sp_values['row_count'].sum():,}"
)

with pd.option_context(
    "display.max_rows",
    None,
    "display.max_colwidth",
    120,
):
    display(invalid_sp_values)

Distinct time values rejected by provisional pattern: 7,127
Rows represented by rejected time values: 289,743

    stored_time  row_count
0        4:8.00        254
1        4:9.70        252
2        4:3.80        250
3        4:5.00        249
4        4:2.20        247
5        4:8.30        247
6        4:4.60        246
7        4:7.90        246
8        4:3.10        245
9        4:3.30        245
10       4:3.50        245
11       4:7.60        245
12       4:8.50        245
13       4:3.20        244
14       4:3.70        244
15       4:8.10        244
16       4:8.80        244
17       4:8.60        243
18       4:4.40        241
19       4:5.30        240
20       4:6.30        240
21       4:7.00        240
22       4:4.90        239
23       4:9.90        239
24       4:1.50        238
25       4:8.90        238
26       4:4.50        237
27       4:9.50        237
28       4:0.60        236
29       4:1.90        236
30       4:2.50        236
31       4:5.50        236
32       4:4.00        234
33       4:5.20        234
34       4:6.20        234
35       1:9.98        233
36       4:2.00        233
37       4:4.70        233
38       4:6.50        233
39       4:0.10        232
40       4:4.10        232
41       4:4.80        232
42       4:6.40        232
43       4:9.80        232
44       1:1.00        231
45       4:2.10        231
46       4:3.00        231
47       4:7.80        231
48       4:3.40        230
49       4:6.60        230
50       4:7.40        230
51       4:1.00        229
52       4:5.60        229
53       4:7.70        229
54       4:1.70        228
55       4:5.10        227
56       4:9.10        227
57       4:1.20        226
58       4:5.80        226
59       4:5.90        226
60       4:9.40        226
61       1:9.99        225
62       4:0.70        225
63       4:5.70        225
64       4:6.00        225
65       4:6.10        225
66       4:7.10        225
67       4:1.10        224
68       4:9.30        224
69       4:8.40        223
70       4:9.00        223
71       4:2.30        222
72       4:2.40        222
73       4:3.60        222
74       1:9.97        221
75       4:2.80        221
76       4:5.40        221
77       4:6.70        221
78       4:7.20        221
79       4:0.00        220
80       4:0.90        220
81       4:4.20        220
82       4:7.30        220
83       4:1.80        218
84       1:9.86        216
85       1:9.91        216
86       4:1.40        216
87       4:9.20        216
88       4:0.50        215
89       1:9.85        214
90       1:9.90        214
91       1:9.96        214
92       4:4.30        214
93       1:0.30        213
94       4:0.40        213
95       4:6.90        213
96       4:2.70        212
97       4:6.80        212
98       4:0.30        211
99       4:2.90        211
100      1:9.70        210
101      4:1.60        210
102      4:7.50        209
103      4:3.90        208
104      1:0.85        207
105      1:1.22        207
106      1:0.33        206
107      4:1.30        206
108      4:9.60        205
109      1:0.25        204
110      1:0.50        204
111      4:6.05        203
112      1:1.20        202
113      1:1.06        201
114      1:9.81        200
115      1:9.94        200
116      1:0.70        199
117      1:0.80        199
118      1:1.30        199
119      1:9.88        199
120      4:8.20        198
121      1:1.05        197
122      1:9.92        197
123      1:0.60        196
124      1:0.20        195
125      1:0.42        195
126      4:0.80        194
127      4:2.60        194
128      1:0.65        193
129      1:0.67        193
130      1:9.95        193
131      1:0.00        192
132      1:0.15        192
133      1:1.15        192
134      4:8.70        192
135      1:0.71        191
136      4:0.20        191
137      1:0.24        190
138      1:0.40        190
139      1:0.19        189
140      1:0.35        189
141      1:0.55        189
142      1:0.68        189
143      1:9.55        189
144      4:5.95        189
145      1:0.41        188
146      1:0.86        188
147      1:9.80        188
148      1:9.82        188
149      1:1.26        187

Distinct SP values rejected by provisional pattern: 3
Rows represented by rejected SP values: 182

  stored_sp  row_count
0       Evs        123
1      EvsJ         58
2         F          1

In [56]:
# Classify every distinct race-time string using Python regular expressions.
#
# SQLite GLOB was too rigid for this field because valid-looking times may use
# either one or two digits for the seconds component, for example:
#   1:9.98
#   1:13.75
#   4:8.00
#
# Also inspect the single starting-price value stored as "F".

import re

distinct_time_values = pd.read_sql_query(
    f"""
    SELECT
        time AS stored_time,
        COUNT(*) AS row_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY time
    ORDER BY row_count DESC, stored_time
    """,
    connection,
)

def classify_time_format(value):
    if value == "-":
        return "dash placeholder"

    if re.fullmatch(r"\d+:\d{1,2}\.\d{2}", value):
        return "minutes:seconds.hundredths"

    return "unclassified"

distinct_time_values["format_class"] = (
    distinct_time_values["stored_time"]
    .map(classify_time_format)
)

time_format_summary = (
    distinct_time_values
    .groupby("format_class", as_index=False)
    .agg(
        distinct_values=("stored_time", "count"),
        runner_rows=("row_count", "sum"),
    )
    .sort_values("runner_rows", ascending=False)
    .reset_index(drop=True)
)

unclassified_time_values = distinct_time_values.loc[
    distinct_time_values["format_class"] == "unclassified"
].copy()

single_f_sp_rows = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        num,
        pos,
        horse,
        sp,
        comment
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND sp = 'F'
    """,
    connection,
)

display(time_format_summary)

print(
    "Unclassified distinct time values: "
    f"{len(unclassified_time_values):,}"
)
print(
    "Rows represented by unclassified time values: "
    f"{unclassified_time_values['row_count'].sum():,}"
)

with pd.option_context(
    "display.max_rows",
    None,
    "display.max_colwidth",
    120,
):
    display(unclassified_time_values)
    display(single_f_sp_rows)

                 format_class  distinct_values  runner_rows
0  minutes:seconds.hundredths            46536      1756877
1            dash placeholder                1        94408

Unclassified distinct time values: 0
Rows represented by unclassified time values: 0

Empty DataFrame
Columns: [stored_time, row_count, format_class]
Index: []

,source_rowid,date,course,race_id,off,race_name,num,pos,horse,sp,comment
0,1708860,2025-07-20,Del Mar (USA),900160,1:03,Wickerr Stakes () (3yo+) (Turf),9,1,Almendares (GB),F,

In [57]:
# Test whether race-level time is repeated consistently across all runner rows.
#
# The source is runner-grain, but time appears to describe the whole race.
# This checks:
# - whether every apparent race has only one stored time value;
# - whether dash placeholders occur for the complete race or only some runners;
# - how many races have a usable time.

race_time_consistency = pd.read_sql_query(
    f"""
    WITH race_time_summary AS (
        SELECT
            date,
            course,
            off,
            race_name,

            COUNT(*) AS physical_rows,
            COUNT(DISTINCT time) AS distinct_time_values,

            SUM(
                CASE
                    WHEN time = '-'
                    THEN 1 ELSE 0
                END
            ) AS dash_rows,

            SUM(
                CASE
                    WHEN time <> '-'
                    THEN 1 ELSE 0
                END
            ) AS populated_time_rows
        FROM data
        WHERE {DATA_ROW_PREDICATE}
        GROUP BY
            date,
            course,
            off,
            race_name
    )
    SELECT
        COUNT(*) AS apparent_races,

        SUM(
            CASE
                WHEN distinct_time_values = 1
                THEN 1 ELSE 0
            END
        ) AS races_with_one_time_value,

        SUM(
            CASE
                WHEN distinct_time_values > 1
                THEN 1 ELSE 0
            END
        ) AS races_with_multiple_time_values,

        SUM(
            CASE
                WHEN dash_rows = physical_rows
                THEN 1 ELSE 0
            END
        ) AS races_all_dash,

        SUM(
            CASE
                WHEN populated_time_rows = physical_rows
                THEN 1 ELSE 0
            END
        ) AS races_all_populated,

        SUM(
            CASE
                WHEN dash_rows > 0
                 AND populated_time_rows > 0
                THEN 1 ELSE 0
            END
        ) AS races_mixing_dash_and_time
    FROM race_time_summary
    """,
    connection,
)

mixed_race_time_examples = pd.read_sql_query(
    f"""
    SELECT
        date,
        course,
        off,
        race_name,
        COUNT(*) AS physical_rows,
        COUNT(DISTINCT time) AS distinct_time_values,
        GROUP_CONCAT(DISTINCT time) AS stored_time_values
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY
        date,
        course,
        off,
        race_name
    HAVING COUNT(DISTINCT time) > 1
    ORDER BY
        date,
        course,
        off,
        race_name
    LIMIT 50
    """,
    connection,
)

display(race_time_consistency)

print(
    "Examples of races with multiple stored time values: "
    f"{len(mixed_race_time_examples):,}"
)
display(mixed_race_time_examples)

,apparent_races,races_with_one_time_value,races_with_multiple_time_values,races_all_dash,races_all_populated,races_mixing_dash_and_time
0,189043,77,188966,66,145607,43370

Examples of races with multiple stored time values: 50

,date,course,off,race_name,physical_rows,distinct_time_values,stored_time_values
0,2015-01-01,Aqueduct (USA),6:20,Affectionately Stakes () (4yo+ Fillies & Mares...,8,8,"1:44.68,1:44.69,1:45.28,1:45.38,1:45.83,1:46.0..."
1,2015-01-01,Ascot (AUS),6:50,La Trice Classic (Fillies & Mares),8,8,"1:53.01,1:52.60,1:52.51,1:51.81,1:51.91,1:52.1..."
2,2015-01-01,Ascot (AUS),8:50,Golden River Development Perth Cup (Handicap),16,16,"2:30.24,2:30.44,2:30.74,2:31.19,2:31.20,2:31.3..."
3,2015-01-01,Catterick,12:30,Happy New Year Novices Hurdle,10,10,"4:50.90,4:51.20,4:51.50,4:51.60,4:52.60,4:55.0..."
4,2015-01-01,Catterick,1:05,Buy Your 2015 Annual Badge Today Handicap Hurdle,11,11,"-,4:58.35,4:55.55,4:52.05,4:46.70,4:47.70,4:48..."
5,2015-01-01,Catterick,1:40,Dine And View At Catterick Races Novices Chase,5,4,"6:39.90,6:41.10,6:43.70,-"
6,2015-01-01,Catterick,2:15,Racing Again On 8th January Novices Hurdle,3,3,"6:39.40,6:39.85,6:44.25"
7,2015-01-01,Catterick,2:50,Watch On 3 Devices racinguk.com/anywhere Handi...,6,6,"4:51.60,4:51.90,4:52.90,4:55.30,5:0.50,-"
8,2015-01-01,Catterick,3:25,yorkshire-outdoors.co.uk Handicap Hurdle,11,8,"6:33.60,6:34.80,6:39.20,6:44.20,6:44.95,6:45.1..."
9,2015-01-01,Cheltenham,12:10,Neptune Investment Management Novices Hurdle,8,8,"5:7.20,5:8.90,5:9.25,5:9.40,5:9.70,5:9.85,5:25..."
10,2015-01-01,Cheltenham,12:45,BetBright On Mobile Handicap Chase,13,10,"7:0.10,7:3.30,7:4.30,7:6.70,-,6:57.70,6:57.65,..."
11,2015-01-01,Cheltenham,1:20,BetBright Novices Chase (Registered As The Dip...,7,6,"5:16.40,5:17.60,5:21.40,5:21.70,5:24.70,-"
12,2015-01-01,Cheltenham,1:55,BetBright Best For Festival Betting Handicap C...,13,13,"5:23.59,5:25.35,5:25.45,5:27.85,5:28.60,5:29.2..."
13,2015-01-01,Cheltenham,2:30,BetBright Casino Handicap Hurdle,10,10,"-,6:20.25,6:12.45,6:9.80,6:9.95,6:10.30,6:10.4..."
14,2015-01-01,Cheltenham,3:05,Dornan Engineering Hurdle,7,7,"5:6.50,5:7.00,5:7.05,5:7.55,5:10.15,5:11.95,5:..."
15,2015-01-01,Cheltenham,3:40,EBF Cheltenham Pony Club Standard Open Nationa...,15,15,"3:30.30,3:30.34,3:30.75,3:31.55,3:31.64,3:31.7..."
16,2015-01-01,Ellerslie (NZ),1:35,Barneswood Farm Eclipse Stakes,9,9,"1:10.79,1:10.94,1:11.14,1:11.39,1:11.89,1:12.1..."
17,2015-01-01,Ellerslie (NZ),2:55,New Zealand Bloodstock Royal Stakes (Fillies),14,12,"2:2.57,2:2.67,2:3.87,2:4.02,2:4.11,2:4.47,2:4...."
18,2015-01-01,Ellerslie (NZ),3:35,Sound Great Northern Guineas,12,12,"1:39.31,1:38.71,1:38.61,1:36.21,1:36.76,1:36.7..."
19,2015-01-01,Ellerslie (NZ),4:15,Rich Hill Mile Handicap),15,15,"1:34.51,1:34.79,1:34.89,1:35.04,1:35.09,1:35.1..."
20,2015-01-01,Ellerslie (NZ),4:55,Sistema Railway Stakes (3yo+) (Turf),14,13,"1:11.33,1:11.49,1:12.19,1:11.24,1:10.94,1:10.7..."
21,2015-01-01,Ellerslie (NZ),5:35,Scot Thrust City of Auckland Cup,18,18,"2:29.60,2:29.62,2:29.80,2:30.20,2:30.27,2:30.7..."
22,2015-01-01,Exeter,12:35,Passage House Inn Topsham Novices Handicap Hurdle,10,7,"6:6.20,6:9.20,6:11.00,6:12.60,6:14.60,-,6:17.40"
23,2015-01-01,Exeter,1:10,Bathwick Tyres Plymouth Maiden Hurdle,16,16,"4:29.15,4:30.55,4:31.55,4:32.00,4:33.20,4:33.2..."
24,2015-01-01,Exeter,1:45,Bathwick Tyres Bridgwater Handicap Chase (Jock...,10,7,"6:22.20,6:23.00,6:23.02,6:25.80,6:25.87,6:26.25,-"
25,2015-01-01,Exeter,2:20,Royal Castle Hotel National Hunt Novices Hurdle,11,9,"4:42.70,4:50.30,4:56.10,5:2.10,5:2.45,5:2.60,5..."
26,2015-01-01,Exeter,2:55,Thurlestone Hotel Handicap Hurdle (Connollys R...,18,15,"4:58.75,4:58.85,4:59.00,5:4.40,5:5.80,-,4:58.2..."
27,2015-01-01,Exeter,3:30,Bathwick Tyres Beginners Chase,7,6,"4:50.80,4:51.45,4:55.85,4:58.05,5:4.05,-"
28,2015-01-01,Exeter,4:00,Billy Williams Memorial Maiden Open National H...,16,16,"4:20.90,4:21.95,4:21.15,4:22.25,4:24.45,4:24.7..."
29,2015-01-01,Fairyhouse (IRE),12:25,Happy New Year Maiden Hurdle,22,22,"4:30.20,4:30.21,4:31.20,4:33.10,4:35.30,4:35.4..."
30,2015-01-01,Fairyhouse (IRE),12:55,Fairyhouse Members Mares Maiden Hurdle,19,16,"5:48.10,5:52.30,5:55.70,5:57.20,5:57.21,5:57.5..."
31,2015-01-01,Fairyhouse (IRE),1:25,Start The New Year @ Fairyhouse Handicap Hurdle,12,12,"4:25.80,4:26.15,4:26.70,4:27.40,4:29.30,4:30.3..."
32,2015-01-01,Fairyhouse (IRE),2:00,Special Offers In Bobbyjo Bistro Handicap Hurdle,11,11,"6:19.90,6:20.25,6:21.00,6:22.30,6:23.40,6:25.6..."
33,2015-01-01,Fairyhouse (IRE),2:35,Fairyhouse Supporting Ratoath Beginners Chase,5,5,"-,6:8.05,6:5.45,6:5.30,6:0.90"
34,2015-01-01,Fairyhouse (IRE),3:10,Boylesports Irish Grand National @ Fairyhouse ...,11,8,"7:13.10,7:13.35,7:14.10,7:16.30,7:19.30,7:23.3..."
35,2015-01-01,Fairyhouse (IRE),3:40,Follow Fairyhouse On Twitter (Pro/Am) Flat Race,9,9,"-,4:53.80,4:34.60,4:30.00,4:22.10,4:22.40,4:25..."
36,2015-01-01,Fakenham,12:40,Bet totejackpot Selling Hurdle,5,5,"5:28.50,5:29.25,5:30.05,5:32.45,-"
37,2015-01-01,Fakenham,1:15,Fakenham Racecourse Annual Members Maiden Hurdle,9,9,"4:17.00,4:17.50,4:20.50,4:20.10,4:20.55,4:21.0..."
38,2015-01-01,Fakenham,1:50,Fakenham Amateur Riders Handicap Chase,4,3,"5:58.10,5:58.70,-"
39,2015-01-01,Fakenham,2:25,POW Grandstand For Private Functions Handicap ...,6,6,"5:22.30,5:25.10,5:25.80,5:29.60,5:29.65,5:42.05"
40,2015-01-01,Fakenham,3:00,Independent Racecourses Ltd. Novices Handicap ...,4,4,"-,6:0.70,5:57.70,5:59.30"
41,2015-01-01,Fakenham,3:35,Happy New Year Handicap Hurdle,8,5,"6:34.00,6:35.60,6:39.00,6:41.20,-"
42,2015-01-01,Flemington (AUS),5:20,Standish Handicap,11,11,"1:9.70,1:9.85,1:10.10,1:10.70,1:10.85,1:10.94,..."
43,2015-01-01,Laurel Park (USA),7:52,Maiden Special Weight (4yo+ Fillies & Mares) (...,6,6,"1:48.36,1:48.56,1:48.71,1:50.31,1:52.06,1:55.91"
44,2015-01-01,Musselburgh,12:25,toteplacepot First Foot Juvenile Hurdle,10,10,"3:50.90,3:51.90,3:52.20,-,3:50.30,3:49.30,3:47..."
45,2015-01-01,Musselburgh,1:00,Happy New Year From totepool Handicap Hurdle,11,9,"4:46.70,4:48.52,4:49.15,4:49.22,4:51.00,4:51.8..."
46,2015-01-01,Musselburgh,1:35,totequadpot Scottish Premier Chase (Handicap),9,9,"5:8.90,5:12.10,5:19.90,5:25.10,-,5:8.45,5:7.55..."
47,2015-01-01,Musselburgh,2:10,totepool Hogmaneigh Hurdle (Handicap),10,10,"3:44.80,3:45.10,3:45.70,3:46.00,3:47.00,3:47.5..."
48,2015-01-01,Musselburgh,2:45,totepool Supporting Scottish Racing Handicap C...,8,7,"6:18.82,6:24.60,-,6:18.80,6:16.60,6:13.90,6:15.70"
49,2015-01-01,Musselburgh,3:20,Collect totepool Winnings At Betfred Shops Han...,6,6,"5:49.90,5:52.30,5:52.65,5:55.45,5:55.55,5:55.95"

In [58]:
# Test the runner-level interpretation of time.
#
# Convert each parseable time string to total seconds, then compare it with:
# - finishing position;
# - overall distance behind;
# - completion status.
#
# This does not yet assume that the fastest stored time is always the official
# winner because promoted and demoted runners may retain their original times.

runner_time_sample = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        off,
        race_name,
        pos,
        ovr_btn,
        btn,
        time,
        horse
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

def time_to_seconds(value):
    if value == "-":
        return pd.NA

    minutes_text, seconds_text = value.split(":")
    return (
        int(minutes_text) * 60
        + float(seconds_text)
    )

runner_time_sample["time_seconds"] = (
    runner_time_sample["time"]
    .map(time_to_seconds)
    .astype("Float64")
)

runner_time_sample["numeric_position"] = pd.to_numeric(
    runner_time_sample["pos"],
    errors="coerce",
)

runner_time_relationship_summary = pd.DataFrame(
    {
        "measure": [
            "rows with parseable time",
            "rows with dash time",
            "numeric finishers with parseable time",
            "text-status runners with parseable time",
            "correlation: numeric position vs time seconds",
            "correlation: numeric ovr_btn vs time seconds",
        ],
        "value": [
            runner_time_sample["time_seconds"].notna().sum(),
            runner_time_sample["time_seconds"].isna().sum(),
            (
                runner_time_sample["numeric_position"].notna()
                & runner_time_sample["time_seconds"].notna()
            ).sum(),
            (
                runner_time_sample["numeric_position"].isna()
                & runner_time_sample["time_seconds"].notna()
            ).sum(),
            runner_time_sample[
                ["numeric_position", "time_seconds"]
            ].corr().iloc[0, 1],
            runner_time_sample.assign(
                numeric_ovr_btn=pd.to_numeric(
                    runner_time_sample["ovr_btn"],
                    errors="coerce",
                )
            )[["numeric_ovr_btn", "time_seconds"]]
            .corr()
            .iloc[0, 1],
        ],
    }
)

race_time_order_checks = (
    runner_time_sample
    .dropna(subset=["time_seconds", "numeric_position"])
    .groupby(
        ["date", "course", "off", "race_name"],
        as_index=False,
    )
    .agg(
        timed_runners=("source_rowid", "count"),
        minimum_position=("numeric_position", "min"),
        maximum_position=("numeric_position", "max"),
        fastest_time=("time_seconds", "min"),
        slowest_time=("time_seconds", "max"),
    )
)

print(
    "Apparent races containing at least two timed numeric finishers: "
    f"{(race_time_order_checks['timed_runners'] >= 2).sum():,}"
)

display(runner_time_relationship_summary)
display(race_time_order_checks.head(30))

Apparent races containing at least two timed numeric finishers: 188,897

                                         measure         value
0                       rows with parseable time  1.756877e+06
1                            rows with dash time  9.440800e+04
2          numeric finishers with parseable time  1.756258e+06
3        text-status runners with parseable time  6.190000e+02
4  correlation: numeric position vs time seconds -9.200331e-02
5   correlation: numeric ovr_btn vs time seconds  4.044796e-01

,date,course,off,race_name,timed_runners,minimum_position,maximum_position,fastest_time,slowest_time
0,2015-01-01,Aqueduct (USA),6:20,Affectionately Stakes () (4yo+ Fillies & Mares...,8,1.0,8.0,104.68,109.38
1,2015-01-01,Ascot (AUS),6:50,La Trice Classic (Fillies & Mares),8,1.0,8.0,111.81,113.01
2,2015-01-01,Ascot (AUS),8:50,Golden River Development Perth Cup (Handicap),16,1.0,16.0,149.94,153.19
3,2015-01-01,Catterick,12:30,Happy New Year Novices Hurdle,9,1.0,9.0,290.9,296.25
4,2015-01-01,Catterick,1:05,Buy Your 2015 Annual Badge Today Handicap Hurdle,10,1.0,10.0,286.7,298.35
5,2015-01-01,Catterick,1:40,Dine And View At Catterick Races Novices Chase,3,1.0,3.0,399.9,403.7
6,2015-01-01,Catterick,2:15,Racing Again On 8th January Novices Hurdle,3,1.0,3.0,399.4,404.25
7,2015-01-01,Catterick,2:50,Watch On 3 Devices racinguk.com/anywhere Handi...,5,1.0,5.0,291.6,300.5
8,2015-01-01,Catterick,3:25,yorkshire-outdoors.co.uk Handicap Hurdle,7,1.0,7.0,393.6,409.75
9,2015-01-01,Cheltenham,12:10,Neptune Investment Management Novices Hurdle,8,1.0,8.0,307.2,325.65
10,2015-01-01,Cheltenham,12:45,BetBright On Mobile Handicap Chase,9,1.0,9.0,416.8,426.7
11,2015-01-01,Cheltenham,1:20,BetBright Novices Chase (Registered As The Dip...,5,1.0,5.0,316.4,324.7
12,2015-01-01,Cheltenham,1:55,BetBright Best For Festival Betting Handicap C...,12,1.0,12.0,321.4,329.7
13,2015-01-01,Cheltenham,2:30,BetBright Casino Handicap Hurdle,9,1.0,9.0,369.8,380.25
14,2015-01-01,Cheltenham,3:05,Dornan Engineering Hurdle,7,1.0,7.0,306.5,317.95
15,2015-01-01,Cheltenham,3:40,EBF Cheltenham Pony Club Standard Open Nationa...,15,1.0,15.0,210.3,217.6
16,2015-01-01,Ellerslie (NZ),1:35,Barneswood Farm Eclipse Stakes,9,1.0,9.0,70.79,77.69
17,2015-01-01,Ellerslie (NZ),2:55,New Zealand Bloodstock Royal Stakes (Fillies),11,1.0,11.0,122.57,137.97
18,2015-01-01,Ellerslie (NZ),3:35,Sound Great Northern Guineas,12,1.0,12.0,96.21,99.31
19,2015-01-01,Ellerslie (NZ),4:15,Rich Hill Mile Handicap),15,1.0,15.0,94.49,96.99
20,2015-01-01,Ellerslie (NZ),4:55,Sistema Railway Stakes (3yo+) (Turf),14,1.0,14.0,70.34,72.19
21,2015-01-01,Ellerslie (NZ),5:35,Scot Thrust City of Auckland Cup,17,1.0,17.0,148.5,157.7
22,2015-01-01,Exeter,12:35,Passage House Inn Topsham Novices Handicap Hurdle,6,1.0,6.0,366.2,377.4
23,2015-01-01,Exeter,1:10,Bathwick Tyres Plymouth Maiden Hurdle,16,1.0,16.0,259.8,279.9
24,2015-01-01,Exeter,1:45,Bathwick Tyres Bridgwater Handicap Chase (Jock...,6,1.0,6.0,382.2,386.25
25,2015-01-01,Exeter,2:20,Royal Castle Hotel National Hunt Novices Hurdle,8,1.0,8.0,282.7,316.0
26,2015-01-01,Exeter,2:55,Thurlestone Hotel Handicap Hurdle (Connollys R...,14,1.0,14.0,287.3,305.8
27,2015-01-01,Exeter,3:30,Bathwick Tyres Beginners Chase,5,1.0,5.0,290.8,304.05
28,2015-01-01,Exeter,4:00,Billy Williams Memorial Maiden Open National H...,15,1.0,15.0,260.9,275.0
29,2015-01-01,Fairyhouse (IRE),12:25,Happy New Year Maiden Hurdle,21,1.0,21.0,261.9,288.0

In [59]:
# Test whether runner times are ordered sensibly within each race.
#
# Comparing raw time with position across the entire dataset is misleading
# because race distances vary greatly. Instead, compare each runner with the
# fastest recorded time in the same apparent race.
#
# For ordinary numeric finishers, elapsed time behind the race minimum should
# usually be non-negative and should generally increase with finishing position.

timed_numeric_finishers = (
    runner_time_sample
    .dropna(
        subset=[
            "time_seconds",
            "numeric_position",
        ]
    )
    .copy()
)

timed_numeric_finishers["race_minimum_time_seconds"] = (
    timed_numeric_finishers
    .groupby(
        [
            "date",
            "course",
            "off",
            "race_name",
        ]
    )["time_seconds"]
    .transform("min")
)

timed_numeric_finishers["seconds_behind_fastest"] = (
    timed_numeric_finishers["time_seconds"]
    - timed_numeric_finishers["race_minimum_time_seconds"]
)

within_race_time_summary = pd.DataFrame(
    {
        "measure": [
            "timed numeric finisher rows",
            "rows faster than race minimum",
            "position 1 rows that are fastest timed runner",
            "position 1 rows not fastest timed runner",
            "non-winners tied for fastest time",
            "correlation: position vs seconds behind fastest",
            "correlation: ovr_btn vs seconds behind fastest",
        ],
        "value": [
            len(timed_numeric_finishers),

            (
                timed_numeric_finishers["seconds_behind_fastest"]
                < 0
            ).sum(),

            (
                (timed_numeric_finishers["numeric_position"] == 1)
                & (
                    timed_numeric_finishers["seconds_behind_fastest"]
                    == 0
                )
            ).sum(),

            (
                (timed_numeric_finishers["numeric_position"] == 1)
                & (
                    timed_numeric_finishers["seconds_behind_fastest"]
                    > 0
                )
            ).sum(),

            (
                (timed_numeric_finishers["numeric_position"] > 1)
                & (
                    timed_numeric_finishers["seconds_behind_fastest"]
                    == 0
                )
            ).sum(),

            timed_numeric_finishers[
                [
                    "numeric_position",
                    "seconds_behind_fastest",
                ]
            ].corr().iloc[0, 1],

            timed_numeric_finishers.assign(
                numeric_ovr_btn=pd.to_numeric(
                    timed_numeric_finishers["ovr_btn"],
                    errors="coerce",
                )
            )[
                [
                    "numeric_ovr_btn",
                    "seconds_behind_fastest",
                ]
            ].corr().iloc[0, 1],
        ],
    }
)

winner_not_fastest_examples = (
    timed_numeric_finishers.loc[
        (timed_numeric_finishers["numeric_position"] == 1)
        & (
            timed_numeric_finishers["seconds_behind_fastest"]
            > 0
        ),
        [
            "source_rowid",
            "date",
            "course",
            "off",
            "race_name",
            "horse",
            "pos",
            "ovr_btn",
            "btn",
            "time",
            "time_seconds",
            "race_minimum_time_seconds",
            "seconds_behind_fastest",
        ],
    ]
    .sort_values(
        [
            "seconds_behind_fastest",
            "date",
            "course",
            "off",
        ],
        ascending=[
            False,
            True,
            True,
            True,
        ],
    )
)

display(within_race_time_summary)

print(
    "Examples where official position 1 is not the fastest timed runner: "
    f"{len(winner_not_fastest_examples):,}"
)

with pd.option_context(
    "display.max_rows",
    50,
    "display.max_colwidth",
    120,
):
    display(winner_not_fastest_examples.head(50))

                                           measure         value
0                      timed numeric finisher rows  1.756258e+06
1                    rows faster than race minimum  0.000000e+00
2    position 1 rows that are fastest timed runner  1.889510e+05
3         position 1 rows not fastest timed runner  3.270000e+02
4                non-winners tied for fastest time  3.710000e+02
5  correlation: position vs seconds behind fastest  4.602975e-01
6   correlation: ovr_btn vs seconds behind fastest  9.988109e-01

Examples where official position 1 is not the fastest timed runner: 327

,source_rowid,date,course,off,race_name,horse,pos,ovr_btn,btn,time,time_seconds,race_minimum_time_seconds,seconds_behind_fastest
727219,727221,2019-06-08,Gavea (BRZ),8:00,Grande Premio Major Suckow (2yo+) (Turf),Happy Bryan (BRZ),1,4.5,4.5,0:57.51,57.51,56.61,0.9
1752289,1752291,2025-10-19,Leopardstown,16:35,Bahrain Turf Club October Handicap (Premier Handicap),Blake (GB),1,3.25,3.25,2:47.82,167.82,167.17,0.65
1743583,1743585,2025-10-03,Keeneland (USA),10:16,Darley Alcibiades Stakes (2yo Fillies) (Main Track) (Dirt),Tommy Jo (USA),1,2.75,2.75,1:45.24,105.24,104.69,0.55
16968,16970,2015-02-21,Gulfstream Park (USA),10:30,Besilu Stables Fountain Of Youth Stakes (3yo) (Dirt),Itsaknockout (USA),1,2.75,2.75,1:46.83,106.83,106.28,0.55
970842,970844,2021-02-27,Gulfstream Park (USA),5:26,Herecomesthebride Stakes (3yo Fillies) (Turf),Con Lima (USA),1,2.75,2.75,1:41.85,101.85,101.3,0.55
13535,13537,2015-02-13,Chantilly (FR),4:25,Prix du Chemin Royal (Handicap) (5yo+) (Polytrack),El Nino (FR),1,2.5,2.5,1:56.66,116.66,116.16,0.5
871742,871744,2020-08-08,Saratoga (USA),9:22,Troy Stakes (4yo+) (Mellon Course) (Turf),American Sailor (USA),1,2.25,2.25,1:1.72,61.72,61.27,0.45
116817,116819,2015-09-24,Maisons-Laffitte (FR),3:00,Prix de Carrieres-sous-Poissy (Claimer) (4yo+) (Round) (Turf),Key To Fun (GER),1,2,2,2:11.12,131.12,130.72,0.4
787181,787183,2019-10-05,Woodbine (CAN),9:59,Mazarine Stakes (2yo Fillies) (All-Weather Track) (Tapeta),Curlins Voyage (CAN),1,2,2,1:43.70,103.7,103.3,0.4
855117,855119,2020-04-11,Gulfstream Park (USA),8:52,Maiden Special Weight (Maiden) (3yo+) (Main Track) (Dirt),Colonel Liam (USA),1,2,2,1:38.31,98.31,97.91,0.4
1530123,1530125,2024-06-29,San Isidro (ARG),10:40,Gran Premio Estrellas Mile (3yo+) (Round) (Turf),Bronx (ARG),1,2,2,1:35.68,95.68,95.28,0.4
1530124,1530126,2024-06-29,San Isidro (ARG),10:40,Gran Premio Estrellas Mile (3yo+) (Round) (Turf),Folie Ninja (ARG),1,2,0,1:35.68,95.68,95.28,0.4
791728,791730,2019-10-14,Gulfstream Park West (USA),9:09,Maiden Special Weight (Maiden) (2yo Fillies) (Turf),Cheermeister (USA),1,2,2,1:32.10,92.1,91.7,0.4
592345,592347,2018-08-29,Deauville (FR),1:50,Prix des Cotes de Normandie (Handicap) (4yo+) (Polytrack),Iken Water (FR),1,1.75,1.75,1:17.67,77.67,77.32,0.35
707024,707026,2019-05-04,Churchill Downs (USA),11:50,Kentucky Derby presented by Woodford Reserve (3yo) (Main Track) (Dirt),Country House (USA),1,1.75,1.75,2:4.28,124.28,123.93,0.35
926974,926976,2020-11-12,Taunton,2:05,Invest Southwest Handicap Hurdle,Robinshill (IRE),1,1.75,1.75,4:4.81,244.81,244.46,0.35
1500812,1500814,2024-05-06,Down Royal (IRE),2:10,Club Lemon Handicap Hurdle,Benjis Benefit (IRE),1,1.75,1.75,4:5.15,245.15,244.8,0.35
96830,96832,2015-08-12,Newton Abbot,4:15,SIS Handicap Hurdle,Always Managing (GB),1,1.75,1.75,5:12.15,312.15,311.8,0.35
698483,698485,2019-04-20,Gavea (BRZ),8:39,Grande Premio Zelia Gonzaga Peixoto de Castro (3yo Fillies) (Turf),Naomi Broadway (BRZ),1,1.5,1,2:26.50,146.5,146.2,0.3
1391302,1391304,2023-08-31,Longchamp (FR),12:48,Prix de Fontenoy (Maiden) (Unraced 2yo Colts & Geldings) (Grande Course) (Turf),Lord Sinclair (FR),1,1.5,1.5,1:44.77,104.77,104.47,0.3
78733,78735,2015-07-02,Deauville (FR),12:30,Prix de Ticheville (Maiden) (2yo Colts & Geldings) (Round) (Turf),Post Var (FR),1,1.5,1.5,1:27.85,87.85,87.55,0.3
878554,878556,2020-08-22,Monmouth Park (USA),7:29,Philip H Iselin Stakes (3yo+) (Main Track) (Dirt),Warriors Charge (USA),1,1.5,1.5,1:43.67,103.67,103.37,0.3
1713780,1713782,2025-08-01,Saratoga (USA),9:36,National Museum of Racing Hall of Fame Stakes (3yo) (Inner Turf),Luther (GB),1,1.5,1.5,1:35.36,95.36,95.06,0.3
98344,98346,2015-08-15,Arlington Park (USA),11:05,Beverly D. Stakes (3yo+ Fillies & Mares) (Turf),Watsdachances (IRE),1,1.25,1.25,1:57.61,117.61,117.36,0.25
118176,118178,2015-09-26,Auteuil (FR),1:30,Prix de Chambly (Hurdle) () (3yo Fillies) (Turf),Caresse DEstruval (FR),1,1.25,1.25,4:26.28,266.28,266.03,0.25
301256,301258,2016-11-26,Gulfstream Park West (USA),8:01,Tropical Turf Handicap (3yo+) (Turf),Lubash (USA),1,1.25,1.25,1:42.72,102.72,102.47,0.25
402552,402554,2017-07-13,Ovrevoll (NOR),7:35,Oslo Cup (3yo+) (Turf),Giuseppe Piazzi (IRE),1,1.25,1.25,2:33.25,153.25,153.0,0.25
924893,924895,2020-11-08,Capannelle (ITY),1:30,Premio Guido Berardelli - II Tris (2yo) (Grande Course) (Turf),Isfahani (GER),1,1.25,1.25,1:48.01,108.01,107.76,0.25
101860,101862,2015-08-23,Deauville (FR),4:55,Prix des Gorges Saint-Aubert (Handicap) (4yo+) (Turf),Ismane (FR),1,1,1,2:16.40,136.4,136.2,0.2
271541,271543,2016-09-24,Cologne (GER),3:05,Preis des Medienhauses DuMont Rheinland - Winterkonigin-Trial () (2yo Fillies) (Turf),Arazza (GER),1,1,1,1:31.25,91.25,91.05,0.2
1017868,1017870,2021-05-28,Stratford,5:10,PPSA Open Hunters Chase,Creative Inerta (IRE),1,1,1,4:13.88,253.88,253.68,0.2
1416806,1416808,2023-10-21,Woodbine (CAN),10:41,Ontario Derby (3yo) (All-Weather Track) (Tapeta),Touchn Ride (CAN),1,1,1,1:49.13,109.13,108.93,0.2
1424426,1424428,2023-11-05,Capannelle (ITY),1:55,Premio Criterium Femminile Memorial Lorenzo Brogi () (2yo Fillies) (Grande Course) (Turf),Mysterious Shadow (IRE),1,1,1,1:36.10,96.1,95.9,0.2
9562,9564,2015-01-31,Tampa Bay Downs (USA),10:50,Lambholm South Endeavour Stakes (Fillies & Mares) (Turf),Testa Rossi (FR),1,0.75,0.75,1:42.19,102.19,102.04,0.15
259341,259343,2016-08-29,Newcastle (AW),12:45,vertem.co.uk/ebf Irish Stallion Farms Maiden Stakes (Plus 10 Race),Mushaireb (GB),1,0.75,0.75,1:29.03,89.03,88.88,0.15
475076,475078,2017-12-09,Los Alamitos (USA),9:28,Los Alamitos Cash Call Futurity (2yo) (Dirt),McKinzie (USA),1,0.75,0.75,1:42.72,102.72,102.57,0.15
567494,567496,2018-07-07,Gulfstream Park (USA),8:19,Martha Washington Stakes (Conditions) (3yo Fillies) (Turf),Camila Princess (USA),1,0.75,0.75,1:38.99,98.99,98.84,0.15
1075278,1075280,2021-09-18,Laurel Park (USA),9:18,Frank J De Francis Memorial Dash Stakes (3yo+) (Main Track) (Dirt),Jalen Journey (USA),1,0.75,0.75,1:9.67,69.67,69.52,0.15
1192015,1192017,2022-05-28,Ffos Las,8:00,Caswell Interiors Handicap Hurdle,Chasamax (IRE),1,0.75,0.75,3:43.55,223.55,223.4,0.15
1374181,1374183,2023-07-23,Hoppegarten (GER),12:23,Furstenberg-Rennen (3yo+) (Turf),Kolossal (GER),1,0.75,0.75,2:31.25,151.25,151.1,0.15
88731,88733,2015-07-25,Saratoga (USA),10:32,Sanford Stakes (2yo) (Dirt),Uncle Vinny (USA),1,0.75,0.75,1:11.07,71.07,70.92,0.15
1174794,1174796,2022-04-27,Musselburgh,6:50,Every Race Live On Racing TV Maiden Stakes (GBB Race),Code Purple (GB),1,0.75,0.75,1:33.82,93.82,93.67,0.15
1559272,1559274,2024-09-01,Kentucky Downs (USA),11:24,National Thoroughbred League Juvenile Sprint Stakes () (2yo) (Turf),Chasing Liberty (USA),1,0.75,0.75,1:15.80,75.8,75.65,0.15
886290,886292,2020-09-06,Fontwell,3:50,Final Furlong Podcast Novices Handicap Chase (GBB Race),Schnabel (IRE),1,0.75,0.75,6:37.25,397.25,397.1,0.15
999179,999181,2021-04-24,Sandown,3:40,bet365 Gold Cup Handicap Chase (GBB Race),Potterman (GB),1,0.75,0.75,7:38.02,458.02,457.87,0.15
636851,636853,2018-11-18,Punchestown (IRE),3:20,Connollys RED MILLS Irish EBF Auction Maiden Hurdle,Satoshi (IRE),1,0.5,0.5,5:40.80,340.8,340.7,0.1
839551,839553,2020-02-07,Bangor-on-Dee,3:15,Totes Back Novices Hurdle,The Cashel Man (IRE),1,0.5,0.5,6:15.88,375.88,375.78,0.1
851148,851150,2020-03-15,Limerick (IRE),4:50,Follow Limerick Racecourse On Instagram Handicap Chase,Enduring Love (IRE),1,0.5,0.5,7:33.00,453.0,452.9,0.1
2655,2657,2015-01-08,Gulfstream Park (USA),7:07,Maiden Special Weight (Maiden) (3yo) (Dirt),Royal Son (USA),1,0.5,0.5,1:37.40,97.4,97.3,0.1
126393,126395,2015-10-13,Curragh (IRE),2:35,Curragh 2016 Starts 20th March Handicap,Oliveraie (GB),1,0.5,0.5,1:13.92,73.92,73.82,0.1

In [60]:
# Quantify the relationship between elapsed-time difference and ovr_btn.
#
# The near-perfect correlation suggests that runner times may be derived from,
# or closely linked to, the stored distance-behind values. However, the
# conversion from lengths to seconds may vary by race code and race distance.
#
# This cell calculates seconds per recorded length for ordinary positive
# distance values, then profiles the ratio by race type.

time_distance_relationship = (
    timed_numeric_finishers
    .assign(
        numeric_ovr_btn=pd.to_numeric(
            timed_numeric_finishers["ovr_btn"],
            errors="coerce",
        )
    )
    .loc[
        lambda frame:
            (frame["numeric_ovr_btn"] > 0)
            & (frame["seconds_behind_fastest"] > 0)
    ]
    .copy()
)

time_distance_relationship["seconds_per_length"] = (
    time_distance_relationship["seconds_behind_fastest"]
    / time_distance_relationship["numeric_ovr_btn"]
)

# Add race type from the source using the source row identifier.
row_type_lookup = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        type
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

time_distance_relationship = (
    time_distance_relationship
    .merge(
        row_type_lookup,
        on="source_rowid",
        how="left",
        validate="one_to_one",
    )
)

time_distance_overall = pd.DataFrame(
    {
        "measure": [
            "eligible runner rows",
            "minimum seconds per length",
            "median seconds per length",
            "mean seconds per length",
            "maximum seconds per length",
        ],
        "value": [
            len(time_distance_relationship),
            time_distance_relationship["seconds_per_length"].min(),
            time_distance_relationship["seconds_per_length"].median(),
            time_distance_relationship["seconds_per_length"].mean(),
            time_distance_relationship["seconds_per_length"].max(),
        ],
    }
)

time_distance_by_type = (
    time_distance_relationship
    .groupby("type", as_index=False)
    .agg(
        runner_rows=("source_rowid", "count"),
        median_seconds_per_length=(
            "seconds_per_length",
            "median",
        ),
        mean_seconds_per_length=(
            "seconds_per_length",
            "mean",
        ),
        minimum_seconds_per_length=(
            "seconds_per_length",
            "min",
        ),
        maximum_seconds_per_length=(
            "seconds_per_length",
            "max",
        ),
    )
    .sort_values("runner_rows", ascending=False)
    .reset_index(drop=True)
)

display(time_distance_overall)
display(time_distance_by_type)

                      measure         value
0        eligible runner rows  1.566928e+06
1  minimum seconds per length  5.714286e-03
2   median seconds per length  2.000000e-01
3     mean seconds per length  1.999497e-01
4  maximum seconds per length  3.000000e-01

,type,runner_rows,median_seconds_per_length,mean_seconds_per_length,minimum_seconds_per_length,maximum_seconds_per_length
0,Flat,1136957,0.2,0.19931,0.01,0.232
1,Hurdle,273704,0.2,0.20172,0.005714,0.3
2,Chase,116927,0.2,0.201539,0.036364,0.3
3,NH Flat,39340,0.2,0.201404,0.036364,0.3

In [61]:
# Test whether runner time is mathematically reconstructed from:
#
#     fastest race time + (ovr_btn * 0.2 seconds)
#
# Small differences may arise from rounding to hundredths of a second.
# This cell measures the reconstruction error without modifying the source.

time_distance_relationship["expected_time_seconds"] = (
    time_distance_relationship["race_minimum_time_seconds"]
    + (time_distance_relationship["numeric_ovr_btn"] * 0.2)
)

time_distance_relationship["time_reconstruction_error"] = (
    time_distance_relationship["time_seconds"]
    - time_distance_relationship["expected_time_seconds"]
)

time_reconstruction_summary = pd.DataFrame(
    {
        "measure": [
            "eligible runner rows",
            "exact reconstruction",
            "absolute error <= 0.01 seconds",
            "absolute error <= 0.02 seconds",
            "absolute error <= 0.05 seconds",
            "absolute error > 0.05 seconds",
            "median absolute error",
            "mean absolute error",
            "maximum absolute error",
        ],
        "value": [
            len(time_distance_relationship),

            (
                time_distance_relationship[
                    "time_reconstruction_error"
                ].abs()
                < 1e-9
            ).sum(),

            (
                time_distance_relationship[
                    "time_reconstruction_error"
                ].abs()
                <= 0.01
            ).sum(),

            (
                time_distance_relationship[
                    "time_reconstruction_error"
                ].abs()
                <= 0.02
            ).sum(),

            (
                time_distance_relationship[
                    "time_reconstruction_error"
                ].abs()
                <= 0.05
            ).sum(),

            (
                time_distance_relationship[
                    "time_reconstruction_error"
                ].abs()
                > 0.05
            ).sum(),

            time_distance_relationship[
                "time_reconstruction_error"
            ].abs().median(),

            time_distance_relationship[
                "time_reconstruction_error"
            ].abs().mean(),

            time_distance_relationship[
                "time_reconstruction_error"
            ].abs().max(),
        ],
    }
)

material_time_reconstruction_errors = (
    time_distance_relationship.loc[
        time_distance_relationship[
            "time_reconstruction_error"
        ].abs() > 0.05,
        [
            "source_rowid",
            "date",
            "course",
            "off",
            "race_name",
            "type",
            "horse",
            "pos",
            "numeric_ovr_btn",
            "time",
            "time_seconds",
            "race_minimum_time_seconds",
            "expected_time_seconds",
            "time_reconstruction_error",
        ],
    ]
    .sort_values(
        "time_reconstruction_error",
        key=lambda series: series.abs(),
        ascending=False,
    )
)

display(time_reconstruction_summary)

print(
    "Rows with absolute reconstruction error above 0.05 seconds: "
    f"{len(material_time_reconstruction_errors):,}"
)

with pd.option_context(
    "display.max_rows",
    100,
    "display.max_colwidth",
    120,
):
    display(material_time_reconstruction_errors.head(100))

                          measure         value
0            eligible runner rows  1.566928e+06
1            exact reconstruction  1.366085e+06
2  absolute error <= 0.01 seconds  1.378966e+06
3  absolute error <= 0.02 seconds  1.418335e+06
4  absolute error <= 0.05 seconds  1.509409e+06
5   absolute error > 0.05 seconds  5.751900e+04
6           median absolute error  0.000000e+00
7             mean absolute error  2.212620e-02
8          maximum absolute error  1.561000e+01

Rows with absolute reconstruction error above 0.05 seconds: 57,519

,source_rowid,date,course,off,race_name,type,horse,pos,numeric_ovr_btn,time,time_seconds,race_minimum_time_seconds,expected_time_seconds,time_reconstruction_error
1516227,1790503,2026-01-12,Punchestown,15:48,Irish Stallion Farms EBF Mares INH Flat Race,NH Flat,Smart Answer (IRE),13,312.25,5:35.16,335.16,257.1,319.55,15.61
1518859,1793722,2026-01-21,Catterick,15:50,Racing Again 30th January Junior National Hunt Flat Race (GBB Race),NH Flat,Cribbins (CAN),9,268.75,4:59.19,299.19,232.0,285.75,13.44
1541904,1821608,2026-04-01,Compiegne,10:51,Prix Sicie (Claiming Hurdle) (Turf),Hurdle,Pegase Bailleuil (FR),7,251.25,5:14.87,314.87,252.06,302.31,12.56
1549217,1830435,2026-04-18,Bellewstown,17:35,Irish Stallion Farms EBF Auction (Pro/Am) INH Flat Race (IRE Incentive Race),NH Flat,Deep Manhattan (IRE),15,228.50,5:08.32,308.32,251.2,296.9,11.42
1516226,1790502,2026-01-12,Punchestown,15:48,Irish Stallion Farms EBF Mares INH Flat Race,NH Flat,Aint Over Yet (IRE),12,223.25,5:12.91,312.91,257.1,301.75,11.16
1494087,1763977,2025-11-09,Naas,16:10,Irish Stallion Farms EBF Mares (Pro/Am) INH Flat Race,NH Flat,Mighty Moments (GB),11,217.50,5:00.57,300.57,246.2,289.7,10.87
1496683,1767144,2025-11-18,Limerick,15:35,Limerick (Ladies Pro/Am) INH Flat Race,NH Flat,Abelene (IRE),7,213.75,5:24.84,324.84,271.4,314.15,10.69
1549216,1830434,2026-04-18,Bellewstown,17:35,Irish Stallion Farms EBF Auction (Pro/Am) INH Flat Race (IRE Incentive Race),NH Flat,Billy Bob (IRE),14,207.50,5:03.07,303.07,251.2,292.7,10.37
1510460,1783618,2025-12-26,Limerick,12:58,Signsplus Maiden Hurdle,Hurdle,Lucky Crystal (IRE),17,200.50,5:06.12,306.12,256.0,296.1,10.02
1518621,1793414,2026-01-20,Down Royal,12:50,Molson Coors Beverage Company Maiden Hurdle,Hurdle,Six Mile Suzy (IRE),18,193.50,5:15.77,315.77,267.4,306.1,9.67
1553570,1835534,2026-04-28,Punchestown,17:25,Goffs Defender Bumper,NH Flat,Barstool Prophet (IRE),19,190.25,4:52.36,292.36,244.8,282.85,9.51
1516922,1791321,2026-01-15,Fairyhouse,15:52,William Hill Each Way Extra Challenge Series Handicap Hurdle (Div II),Hurdle,Great Island (IRE),10,190.25,6:26.76,386.76,339.2,377.25,9.51
1516225,1790501,2026-01-12,Punchestown,15:48,Irish Stallion Farms EBF Mares INH Flat Race,NH Flat,Jenina (IRE),11,188.25,5:04.16,304.16,257.1,294.75,9.41
1506385,1778782,2025-12-13,Fairyhouse,13:40,Fairyhouse Christmas Party Maiden Hurdle,Hurdle,Daws Cross (IRE),9,188.25,7:18.06,438.06,391.0,428.65,9.41
1516224,1790500,2026-01-12,Punchestown,15:48,Irish Stallion Farms EBF Mares INH Flat Race,NH Flat,Fastnet Crystal (IRE),10,187.50,5:03.98,303.98,257.1,294.6,9.38
1523069,1798813,2026-02-03,Fairyhouse,13:50,BetVictor Still Best Odds Guaranteed Maiden Hurdle,Hurdle,The Weeping Ash (IRE),15,182.50,5:11.32,311.32,265.7,302.2,9.12
1510507,1783681,2025-12-26,Limerick,15:50,Play perysbingo.com Mares INH Flat Race,NH Flat,Pegasuslane (IRE),14,179.00,5:02.57,302.57,257.8,293.6,8.97
1530109,1807371,2026-02-26,Wetherby,16:10,Join Racing TV Now Handicap Hurdle (Qualifier For The Challenger Stayers Hurdle Series Final),Hurdle,Block Rockin Beats (IRE),8,179.25,7:03.81,423.81,379.0,414.85,8.96
1510506,1783680,2025-12-26,Limerick,15:50,Play perysbingo.com Mares INH Flat Race,NH Flat,Beautiful Beauty (IRE),13,178.75,5:02.49,302.49,257.8,293.55,8.94
1516983,1791411,2026-01-15,Fairyhouse,13:33,Racing Again 24th January Maiden Hurdle,Hurdle,Ballyhasty (IRE),12,176.75,4:54.19,294.19,250.0,285.35,8.84
1523787,1799709,2026-02-05,Thurles,16:37,John Thomas McNamara Series INH Flat Race,NH Flat,No Time To Think (IRE),11,176.25,5:09.76,309.76,265.7,300.95,8.81
1518858,1793721,2026-01-21,Catterick,15:50,Racing Again 30th January Junior National Hunt Flat Race (GBB Race),NH Flat,Broadway Dreamer (GB),8,175.75,4:35.94,275.94,232.0,267.15,8.79
1505501,1777731,2025-12-11,Punchestown,12:50,Matchbook Backs Irish Racing Maiden Hurdle,Hurdle,Hens Tooth (IRE),15,171.50,5:40.57,340.57,297.7,332.0,8.57
1487409,1756088,2025-10-26,Galway,13:25,Irish Stallion Farms EBF Beginners Chase,Chase,Hello Jack (IRE),8,169.00,6:27.15,387.15,344.9,378.7,8.45
1533077,1811000,2026-03-07,Gowran Park,13:58,William Hill Each Way Extra Challenge Series Maiden Hurdle,Hurdle,Lanzhou (FR),15,167.00,5:06.45,306.45,264.7,298.1,8.35
1520352,1795544,2026-01-25,Naas,14:55,Aloga Equestrian (Pro/Am) INH Flat Race,NH Flat,Esprit De Rue (IRE),8,165.00,5:39.05,339.05,297.8,330.8,8.25
1525866,1802222,2026-02-13,Chepstow,16:55,Chepstow 9th August Centenary Raceday Handicap Hurdle,Hurdle,Hunting Percival (GB),9,164.50,7:10.11,430.11,388.98,421.88,8.23
1516982,1791410,2026-01-15,Fairyhouse,13:33,Racing Again 24th January Maiden Hurdle,Hurdle,Thatsmyroadie (IRE),11,162.75,4:50.69,290.69,250.0,282.55,8.14
1530005,1807215,2026-02-26,Clonmel,12:49,Irish Stallion Farms EBF Maiden Hurdle,Hurdle,Davitts Quay (IRE),15,162.00,6:10.70,370.7,330.2,362.6,8.1
1520351,1795543,2026-01-25,Naas,14:55,Aloga Equestrian (Pro/Am) INH Flat Race,NH Flat,Fly Away Home (IRE),7,160.50,5:37.93,337.93,297.8,329.9,8.03
1543849,1823915,2026-04-05,Cork,17:15,Ampion Ltd. Electrical And Testing (Pro/Am) INH Flat Race,NH Flat,Cloghoula More (IRE),15,160.25,5:24.06,324.06,284.0,316.05,8.01
1561720,1845164,2026-05-16,Auteuil,12:23,Prix Djarvis (Conditions Chase) (Turf),Chase,Marbre Rose AA (FR),5,159.25,6:25.61,385.61,345.8,377.65,7.96
1539354,1818589,2026-03-25,Hexham,17:13,Horslyx - For Horses Health & Welfare Mares Open Maiden NH Flat Race (Cat 3 Elimination) (GBB),NH Flat,Abbotrule (GB),8,158.75,5:14.49,314.49,274.8,306.55,7.94
1541120,1820684,2026-03-29,Downpatrick,14:07,Tote Every Days A Money Back Day Maiden Hurdle,Hurdle,Leo Messy (IRE),10,158.50,6:20.12,380.12,340.5,372.2,7.92
1511592,1784994,2025-12-28,Limerick,13:05,CUBE Maiden Hurdle,Hurdle,Queen ODroad (IRE),10,158.25,6:36.26,396.26,356.7,388.35,7.91
1523786,1799708,2026-02-05,Thurles,16:37,John Thomas McNamara Series INH Flat Race,NH Flat,Drombane (IRE),10,157.25,5:05.01,305.01,265.7,297.15,7.86
1511591,1784993,2025-12-28,Limerick,13:05,CUBE Maiden Hurdle,Hurdle,Battle With Time (IRE),9,156.25,6:35.76,395.76,356.7,387.95,7.81
1516258,1790541,2026-01-12,Punchestown,12:48,Matchbook 50:50 Graduation Series Maiden Hurdle,Hurdle,Ray Gun (USA),14,155.50,4:52.57,292.57,253.7,284.8,7.77
1538856,1817982,2026-03-23,Compiegne,13:12,Prix Master Bob (Conditions Hurdle) (Turf),Hurdle,Lozen De Lorme (FR),15,155.00,4:48.92,288.92,250.17,281.17,7.75
1533084,1811011,2026-03-07,Gowran Park,17:23,Docs Bumper INH Flat Race,NH Flat,Daily Devotion (IRE),8,155.00,5:38.15,338.15,299.4,330.4,7.75
1520350,1795542,2026-01-25,Naas,14:55,Aloga Equestrian (Pro/Am) INH Flat Race,NH Flat,Doctor Elvis (FR),6,154.50,5:36.43,336.43,297.8,328.7,7.73
1503876,1775750,2025-12-06,Navan,12:35,Timeless Sash Windows Maiden Hurdle,Hurdle,Sneddy Eddie (IRE),26,154.25,4:58.06,298.06,259.5,290.35,7.71
1553569,1835533,2026-04-28,Punchestown,17:25,Goffs Defender Bumper,NH Flat,Strategic (FR),18,154.25,4:43.36,283.36,244.8,275.65,7.71
1533076,1810999,2026-03-07,Gowran Park,13:58,William Hill Each Way Extra Challenge Series Maiden Hurdle,Hurdle,Diesel Deans (IRE),14,154.00,5:03.20,303.2,264.7,295.5,7.7
1501773,1773284,2025-11-30,Fairyhouse,15:41,BAR 1 Casino (Pro/Am) INH Flat Race,NH Flat,Harbour Man (IRE),13,152.50,4:39.32,279.32,241.2,271.7,7.62
1541903,1821607,2026-04-01,Compiegne,10:51,Prix Sicie (Claiming Hurdle) (Turf),Hurdle,Clovis Desbrousses (FR),6,152.25,4:50.12,290.12,252.06,282.51,7.61
1512069,1785567,2025-12-29,Limerick,12:00,Vision Contracting Novice Handicap Chase,Chase,Shotgun Jack (IRE),9,152.00,6:47.80,407.8,369.8,400.2,7.6
1555010,1837238,2026-05-02,Auteuil,10:18,Prix Vieux Beaufai (Conditions) (Chase) (Turf),Chase,Volodymyr (FR),7,152.00,6:26.48,386.48,348.48,378.88,7.6
1525114,1801326,2026-02-10,Limerick,15:25,Follow Limerick Racecourse On Instagram (C & G) Maiden Hurdle,Hurdle,Lucky Crystal (IRE),4,150.00,5:20.60,320.6,283.1,313.1,7.5
1527471,1804174,2026-02-18,Punchestown,16:45,Matchbook 50:50 Graduation Series INH Flat Race,NH Flat,Born De Ceres (FR),6,149.75,5:12.94,312.94,275.5,305.45,7.49
1516257,1790540,2026-01-12,Punchestown,12:48,Matchbook 50:50 Graduation Series Maiden Hurdle,Hurdle,Nile Star (FR),13,149.00,4:50.95,290.95,253.7,283.5,7.45
1530814,1808224,2026-02-28,Navan,13:18,Navan Racecourse Maiden Hurdle,Hurdle,Bravemans Bounce (IRE),8,149.00,5:08.95,308.95,271.7,301.5,7.45
1528550,1805438,2026-02-21,Chepstow,17:18,Pertemps Network Maiden National Hunt Flat Race (Conditional/Amateurs) (Cat 3 Elimination) (GBB),NH Flat,Ta Ra For Now Jack (GB),8,148.00,4:40.71,280.71,243.71,273.31,7.4
1516981,1791409,2026-01-15,Fairyhouse,13:33,Racing Again 24th January Maiden Hurdle,Hurdle,Three Leaf Clover (IRE),10,147.75,4:46.94,286.94,250.0,279.55,7.39
1516223,1790499,2026-01-12,Punchestown,15:48,Irish Stallion Farms EBF Mares INH Flat Race,NH Flat,Fancy Fox (IRE),9,147.50,4:53.98,293.98,257.1,286.6,7.38
1495055,1765132,2025-11-13,Punchestown,14:10,Matchbook Supporting Irish Racing Maiden Hurdle,Hurdle,Tarquin The Proud (IRE),20,147.25,4:40.21,280.21,243.4,272.85,7.36
1495054,1765131,2025-11-13,Punchestown,14:10,Matchbook Supporting Irish Racing Maiden Hurdle,Hurdle,Call Me Flash (IRE),19,146.75,4:40.09,280.09,243.4,272.75,7.34
1555523,1837843,2026-05-02,Punchestown,18:05,Sebden Steel Celebrating 30 Years In Business (Pro/Am) INH Flat Race,NH Flat,Jacks Bridge (IRE),16,146.75,4:33.89,273.89,237.2,266.55,7.34
1543931,1824014,2026-04-05,Fairyhouse,13:30,Ryans Cleaning Maiden Hurdle,Hurdle,Areema Dreamer (IRE),22,146.25,4:52.66,292.66,256.1,285.35,7.31
1543930,1824013,2026-04-05,Fairyhouse,13:30,Ryans Cleaning Maiden Hurdle,Hurdle,Deep Warrior (IRE),21,146.00,4:52.60,292.6,256.1,285.3,7.3
1515356,1789462,2026-01-09,Naas,12:43,Irish Stallion Farms EBF Maiden Hurdle,Hurdle,Takemebacktodakota (IRE),25,144.00,4:34.40,274.4,238.4,267.2,7.2
1530004,1807214,2026-02-26,Clonmel,12:49,Irish Stallion Farms EBF Maiden Hurdle,Hurdle,The Ducks Walk (IRE),14,144.00,6:06.20,366.2,330.2,359.0,7.2
1549649,1830916,2026-04-19,Auteuil,15:28,Prix Leon Rambaud (Hurdle) (Turf),Hurdle,Rooster Crowing (FR),6,143.00,5:44.81,344.81,309.06,337.66,7.15
1562424,1846021,2026-05-17,Auteuil,16:30,Prix Ferdinand Dufaure (Chase) (Turf),Chase,Quonstantine (FR),7,143.00,6:28.42,388.42,352.67,381.27,7.15
1501383,1772798,2025-11-29,Fairyhouse,14:25,Kettles Country House Hotel Maiden Hurdle,Hurdle,Lohengrin (GB),22,142.50,4:40.93,280.93,245.3,273.8,7.13
1555025,1837260,2026-05-02,Auteuil,12:40,Prix Rigoletto (Chase) (Turf),Chase,Rosemale Has (FR),10,142.25,6:21.21,381.21,345.65,374.1,7.11
1497595,1768189,2025-11-20,Thurles,13:25,Irish Stallion Farms EBF Mares Maiden Hurdle,Hurdle,Barnahash Hill (IRE),8,142.25,6:23.96,383.96,348.4,376.85,7.11
1527945,1804738,2026-02-19,Thurles,16:53,Irish Stallion Farms EBF Mares INH Flat Race,NH Flat,Dlightofdsun (IRE),6,142.00,5:06.40,306.4,270.9,299.3,7.1
1529006,1806010,2026-02-22,Naas,14:00,William Hill Ireland Bet10 Get5 Maiden Hurdle,Hurdle,Jolly Potter (FR),20,141.75,4:45.54,285.54,250.1,278.45,7.09
1535590,1814029,2026-03-14,Auteuil,15:25,Prix Auricula (Maiden Hurdle) (Fillies & Mares) (Turf),Hurdle,Rosa Mia (FR),9,141.25,4:31.76,271.76,236.45,264.7,7.06
1523809,1799746,2026-02-05,Thurles,14:52,www.thurlesraces.ie Maiden Hurdle,Hurdle,Clarin Breeze (IRE),13,141.00,6:26.85,386.85,351.6,379.8,7.05
1497594,1768188,2025-11-20,Thurles,13:25,Irish Stallion Farms EBF Mares Maiden Hurdle,Hurdle,Venturi Effect (IRE),7,141.00,6:23.65,383.65,348.4,376.6,7.05
1507160,1779705,2025-12-15,Naas,14:20,Care At Home Services Mares Maiden Hurdle,Hurdle,Super Exceed (IRE),19,140.75,4:50.69,290.69,255.5,283.65,7.04
1515355,1789461,2026-01-09,Naas,12:43,Irish Stallion Farms EBF Maiden Hurdle,Hurdle,Daws Cross (IRE),24,140.25,4:33.46,273.46,238.4,266.45,7.01
1516256,1790539,2026-01-12,Punchestown,12:48,Matchbook 50:50 Graduation Series Maiden Hurdle,Hurdle,Granlahan (IRE),12,139.50,4:48.57,288.57,253.7,281.6,6.97
1507221,1779773,2025-12-15,Naas,13:20,BAR 1 Betting Merry Christmas Maiden Hurdle,Hurdle,Head To Capri (IRE),20,139.50,5:41.27,341.27,306.4,334.3,6.97
1554806,1836983,2026-05-01,Punchestown,19:40,Stables Restaurant Naas INH Flat Race,NH Flat,Jukebox Charlie (IRE),21,139.25,5:13.91,313.91,279.1,306.95,6.96
1511590,1784992,2025-12-28,Limerick,13:05,CUBE Maiden Hurdle,Hurdle,Rony Has (FR),8,138.25,6:31.26,391.26,356.7,384.35,6.91
1494389,1764317,2025-11-10,Carlisle,15:58,Nigel Hawke Raceday Experiences Mares Open Maiden National Hunt Flat Race (Category 3 Elimination),NH Flat,Whispering Cloud (GB),12,137.75,5:03.07,303.07,268.63,296.18,6.89
1516222,1790498,2026-01-12,Punchestown,15:48,Irish Stallion Farms EBF Mares INH Flat Race,NH Flat,Tountinna (IRE),8,136.50,4:51.23,291.23,257.1,284.4,6.83
1554805,1836982,2026-05-01,Punchestown,19:40,Stables Restaurant Naas INH Flat Race,NH Flat,Tubberfinn Gordon (IRE),20,136.00,5:13.10,313.1,279.1,306.3,6.8
1541939,1821654,2026-04-01,Compiegne,13:12,Prix Journaliste (Chase) (Turf),Chase,Jachar (FR),7,135.50,5:53.46,353.46,319.59,346.69,6.77
1509319,1782218,2025-12-20,Thurles,15:40,Irish Stallion Farms EBF Mares INH Flat Race,NH Flat,Loughdoo (IRE),15,135.25,4:51.21,291.21,257.4,284.45,6.76
1533083,1811010,2026-03-07,Gowran Park,17:23,Docs Bumper INH Flat Race,NH Flat,Dorie Miller (IRE),7,135.00,5:33.15,333.15,299.4,326.4,6.75
1543897,1823974,2026-04-05,Cork,16:45,Irish Stallion Farms EBF Beginners Chase,Chase,Major Wells (IRE),7,134.75,4:49.69,289.69,256.0,282.95,6.74
1501382,1772797,2025-11-29,Fairyhouse,14:25,Kettles Country House Hotel Maiden Hurdle,Hurdle,Sneddy Eddie (IRE),21,134.50,4:38.93,278.93,245.3,272.2,6.73
1529005,1806009,2026-02-22,Naas,14:00,William Hill Ireland Bet10 Get5 Maiden Hurdle,Hurdle,Awordinyourear (IRE),19,134.25,4:43.66,283.66,250.1,276.95,6.71
1525991,1802390,2026-02-13,Kelso,16:45,Racing TV Open Maiden National Hunt Flat Race (GBB Race),NH Flat,Captain Cognac (IRE),9,134.00,4:57.59,297.59,264.09,290.89,6.7
1543929,1824012,2026-04-05,Fairyhouse,13:30,Ryans Cleaning Maiden Hurdle,Hurdle,Fun Daddy (IRE),20,134.00,4:49.60,289.6,256.1,282.9,6.7
1536537,1815163,2026-03-16,Ffos Las,15:30,Celtic Subaru Novices Hurdle (GBB Race),Hurdle,Makinbecon (GB),4,133.50,6:00.50,360.5,327.12,353.82,6.68
1510459,1783617,2025-12-26,Limerick,12:58,Signsplus Maiden Hurdle,Hurdle,Cailin Mahler (IRE),16,133.50,4:49.38,289.38,256.0,282.7,6.68
1537175,1815968,2026-03-19,Cork,15:30,Mouse Trap Bar & Bridge House Bar Pre Race Party Maiden Hurdle,Hurdle,Shine Bright (IRE),16,132.75,5:45.19,345.19,312.0,338.55,6.64
1515354,1789460,2026-01-09,Naas,12:43,Irish Stallion Farms EBF Maiden Hurdle,Hurdle,Major Wells (IRE),23,132.75,4:31.59,271.59,238.4,264.95,6.64
1510436,1783590,2025-12-26,Leopardstown,12:35,Thorntons Recycling Maiden Hurdle,Hurdle,Gerrymandering (IRE),21,132.75,4:29.59,269.59,236.4,262.95,6.64
1543290,1823255,2026-04-04,Fairyhouse,15:50,Tom Quinlan Electrical Maiden Hurdle,Hurdle,Leo Messy (IRE),16,132.75,5:50.49,350.49,317.3,343.85,6.64
1536706,1815372,2026-03-17,Down Royal,13:53,Albert Bartlett Triple Crown Series At Punchestown Festival 2026 Qualifier Novice Handicap Hurdle,Hurdle,Needs Must (IRE),16,132.50,5:39.43,339.43,306.3,332.8,6.63
1509346,1782258,2025-12-20,Thurles,14:32,William Hill Each Way Extra Challenge Series Maiden Hurdle (Div II),Hurdle,Del Boys Diva (IRE),12,132.25,4:52.86,292.86,259.8,286.25,6.61
1509482,1782436,2025-12-21,Lingfield,15:30,At The Races App Expert Tips Conditional Jockeys Novices Handicap Hurdle,Hurdle,Known Warrior (FR),6,132.25,5:42.70,342.7,309.64,336.09,6.61
1536671,1815323,2026-03-17,Down Royal,13:18,Bluegrass Relite Maiden Hurdle,Hurdle,Carrig Padraig (IRE),18,132.25,4:48.16,288.16,255.1,281.55,6.61
1529190,1806215,2026-02-23,Auteuil,13:30,Prix Tofano (Conditions Chase) (Turf),Chase,Pinaclouddown (IRE),6,132.00,6:34.92,394.92,361.92,388.32,6.6

In [62]:
# Profile the performance-measure fields:
# prize, official rating, Racing Post Rating, and Topspeed.
#
# This first pass records missingness, distinct counts, and SQLite storage
# classes without yet interpreting the values.

performance_fields = [
    "prize",
    "or",
    "rpr",
    "ts",
]

performance_profile_rows = []

for field in performance_fields:
    quoted_field = f'"{field}"'

    result = pd.read_sql_query(
        f"""
        SELECT
            COUNT(*) AS total_rows,

            SUM(
                CASE
                    WHEN {quoted_field} IS NULL
                    THEN 1 ELSE 0
                END
            ) AS null_count,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) = 'text'
                     AND length(trim({quoted_field})) = 0
                    THEN 1 ELSE 0
                END
            ) AS blank_text_count,

            COUNT(DISTINCT {quoted_field})
                AS distinct_non_null_values,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) = 'null'
                    THEN 1 ELSE 0
                END
            ) AS storage_null,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) = 'integer'
                    THEN 1 ELSE 0
                END
            ) AS storage_integer,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) = 'real'
                    THEN 1 ELSE 0
                END
            ) AS storage_real,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) = 'text'
                    THEN 1 ELSE 0
                END
            ) AS storage_text,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) = 'blob'
                    THEN 1 ELSE 0
                END
            ) AS storage_blob
        FROM data
        WHERE {DATA_ROW_PREDICATE}
        """,
        connection,
    ).iloc[0].to_dict()

    result["field_name"] = field

    result["declared_sqlite_type"] = (
        source_data_dictionary.loc[
            source_data_dictionary["field_name"] == field,
            "declared_sqlite_type",
        ].iloc[0]
    )

    performance_profile_rows.append(result)

performance_quality = pd.DataFrame(
    performance_profile_rows
)[
    [
        "field_name",
        "declared_sqlite_type",
        "total_rows",
        "null_count",
        "blank_text_count",
        "distinct_non_null_values",
        "storage_null",
        "storage_integer",
        "storage_real",
        "storage_text",
        "storage_blob",
    ]
]

display(performance_quality)

,field_name,declared_sqlite_type,total_rows,null_count,blank_text_count,distinct_non_null_values,storage_null,storage_integer,storage_real,storage_text,storage_blob
0,prize,INTEGER,1851285,0,839715,47215,0,225078,618026,1008181,0
1,or,INTEGER,1851285,0,0,182,0,1116633,0,734652,0
2,rpr,INTEGER,1851285,0,0,186,0,1644176,0,207109,0
3,ts,INTEGER,1851285,0,0,179,0,1227384,0,623901,0

In [63]:
# Inspect text-coded values and numeric ranges for the performance fields.
#
# This separates:
# - blank prize values;
# - any non-blank text values;
# - numeric minima and maxima.
#
# No interpretation or cleaning is applied yet.

performance_text_distributions = {}

for field in performance_fields:
    quoted_field = f'"{field}"'

    text_values = pd.read_sql_query(
        f"""
        SELECT
            CASE
                WHEN length(trim({quoted_field})) = 0
                THEN '<blank>'
                ELSE {quoted_field}
            END AS stored_value,

            COUNT(*) AS row_count
        FROM data
        WHERE {DATA_ROW_PREDICATE}
          AND typeof({quoted_field}) = 'text'
        GROUP BY {quoted_field}
        ORDER BY
            row_count DESC,
            stored_value
        """,
        connection,
    )

    performance_text_distributions[field] = text_values

performance_numeric_ranges = pd.read_sql_query(
    f"""
    SELECT
        MIN(
            CASE
                WHEN typeof(prize) IN ('integer', 'real')
                THEN prize
            END
        ) AS minimum_prize,

        MAX(
            CASE
                WHEN typeof(prize) IN ('integer', 'real')
                THEN prize
            END
        ) AS maximum_prize,

        SUM(
            CASE
                WHEN typeof(prize) IN ('integer', 'real')
                 AND prize < 0
                THEN 1 ELSE 0
            END
        ) AS negative_prize_rows,

        MIN(
            CASE
                WHEN typeof("or") = 'integer'
                THEN "or"
            END
        ) AS minimum_or,

        MAX(
            CASE
                WHEN typeof("or") = 'integer'
                THEN "or"
            END
        ) AS maximum_or,

        MIN(
            CASE
                WHEN typeof(rpr) = 'integer'
                THEN rpr
            END
        ) AS minimum_rpr,

        MAX(
            CASE
                WHEN typeof(rpr) = 'integer'
                THEN rpr
            END
        ) AS maximum_rpr,

        MIN(
            CASE
                WHEN typeof(ts) = 'integer'
                THEN ts
            END
        ) AS minimum_ts,

        MAX(
            CASE
                WHEN typeof(ts) = 'integer'
                THEN ts
            END
        ) AS maximum_ts
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    """,
    connection,
)

for field in performance_fields:
    print(f"\n{field.upper()} — TEXT VALUES")

    with pd.option_context(
        "display.max_rows",
        None,
        "display.max_colwidth",
        120,
    ):
        display(performance_text_distributions[field])

print("\nNUMERIC RANGES")
display(performance_numeric_ranges)

PRIZE — TEXT VALUES

     stored_value  row_count
0         <blank>     839715
1            €400       4485
2            €200       4067
3            €900       3860
4           €1900       3464
5            €100       3120
6           €5900       3061
7            €440       2288
8            €420       1828
9            €220       1815
10           €210       1811
11           €240       1761
12           €990       1709
13           €480       1699
14           €500       1660
15           €110       1657
16          €2090       1639
17           €945       1587
18          €1080       1514
19          €6490       1499
20          €2280       1493
21          €1995       1431
22          €1000       1413
23           €105       1372
24           €600       1331
25          €6195       1311
26           €120       1279
27          €7080       1276
28           €360       1115
29           €460       1092
30           €150       1076
31           €160       1058
32           €300       1030
33           €250        977
34          €2185        972
35          €2000        971
36          €1035        970
37           €230        921
38          €1800        920
39          €6785        912
40           €320        906
41           €910        899
42           €800        888
43          €1350        883
44           €115        873
45          €2850        852
46          €1125        814
47          €2375        811
48           €410        807
49          €1440        805
50           €180        800
51          €1910        800
52          €1001        795
53          €2101        794
54           €451        794
55          €8850        756
56          €1092        727
57          €2292        725
58           €492        724
59           €176        676
60           €640        655
61          €6776        649
62          €6160        646
63           €125        634
64          €7375        633
65          €3800        630
66           €520        615
67          €1710        604
68          €2250        595
69          €4750        591
70          €7392        584
71           €192        575
72           €560        575
73           €810        573
74          €1200        567
75          €1600        548
76         €11800        530
77          €3040        528
78          €4500        517
79       €2387.50        513
80       €1137.50        512
81        €512.50        508
82          €9500        496
83          €4000        486
84          €1365        475
85          €2865        473
86           €135        463
87           €615        463
88          €1170        462
89         €29500        457
90           €620        455
91          €2470        452
92          €9000        452
93           €165        445
94           €700        444
95         €19000        443
96           €660        435
97          €9440        428
98           €260        417
99          €2945        417
100         €1395        415
101      €2196.50        413
102      €1046.50        412
103       €471.50        412
104        €59000        412
105          €580        403
106       €430.50        402
107       €955.50        402
108      €2005.50        400
109         €7700        398
110          €450        394
111         €9145        381
112         €9240        381
113         €1260        380
114          €840        373
115         €1305        372
116         €2755        372
117         €2700        371
118          €280        362
119          €310        362
120         €7670        362
121          €770        359
122         €1820        358
123         €5700        358
124         €7590        358
125         €1760        357
126         €3820        356
127          €820        355
128         €8555        347
129        €14750        344
130          €290        340
131          €130        339
132          €630        337
133         €1485        333
134         €3135        333
135         €2400        326
136          €720        325
137          €155        323
138         €2483        322
139         €1183        321
140         €5310        321
141          €540        321
142         €2660        320
143          €533        320
144           €90        317
145         €1500        316
146          €184        316
147         €6150        316
148         €7084        316
149          €145        309
150          €680        306
151          €168        304
152         €6468        304
153         €3600        292
154         €8550        292
155          €375        288
156         €4050        285
157         €6210        285
158         €2565        282
159         €1530        276
160         €3230        275
161        €12320        274
162         €7600        271
163          €340        270
164        €26550        266
165         €8008        262
166         €3990        258
167         €1890        257
168         €3000        252
169          €330        252
170          €208        251
171        €23600        250
172         €5535        247
173          €880        247
174         €4180        246
175         €1980        245
176          €380        242
177         €1620        239
178         €3420        239
179         €9735        238
180         €1215        237
181         €6900        236
182        €12980        230
183        €10030        229
184        €10620        226
185         €8260        225
186         €7380        220
187        €15375        218
188         €1100        213
189          €270        213
190         €1280        212
191         €5520        210
192         €1456        209
193         €3056        209
194          €656        208
195        €12390        207
196          €750        202
197         €1547        200
198        €17700        200
199         €3247        200
200          €697        200
201          €140        199
202         €7965        196
203      €1592.50        188
204          €170        187
205      €3342.50        187
206       €717.50        184
207      €1228.50        182
208      €2578.50        182
209         €2160        181
210         €5400        180
211       €553.50        180
212         €1300        175
213         €9856        175
214      €7687.50        172
215        €11400        170
216       €187.50        167
217          €256        167
218          €550        163
219         €2340        161
220         €4940        159
221         €6000        157
222         €5910        156
223         €1040        155
224      €1501.50        152
225      €3151.50        152
226         €8316        152
227        €10780        150
228       €676.50        150
229          €216        149
230        €35400        149
231        €10472        147
232          €231        146
233         €2500        146
234         €6501        146
235          €121        145
236         €7092        143
237          €252        142
238         €6765        142
239         €2200        141
240         €2268        141
241          €272        141
242         €7068        141
243         €1068        140
244          €132        140
245          €468        139
246          €228        138
247         €2674        138
248      €1319.50        137
249         €1920        137
250      €2769.50        137
251         €5000        137
252       €594.50        137
253         €1274        136
254          €108        135
255         €4950        135
256         €1050        133
257          €574        133
258        €10450        132
259         €8280        132
260          €225        130
261        €5,900        130
262        €1,900        129
263          €315        129
264         €1400        128
265         €4275        128
266       €157.50        127
267       €262.50        126
268         €1120        124
269          €350        123
270         €7125        122
271      €6457.50        121
272         €3375        119
273        €11040        118
274         €2560        118
275        €28500        118
276        €10164        117
277      €7387.50        117
278        €13500        116
279          €650        116
280          €855        116
281        €32450        115
282        €18450        112
283          €264        112
284         €8932        112
285         €1638        111
286         €1805        111
287      €5842.50        111
288         €1575        110
289       €137.50        109
290       €142.50        109
291          €950        109
292        €10350        108
293         €4560        108
294         €3438        107
295         €6650        107
296        €22125        106
297         €3325        106
298          €738        104
299         €2080        103
300          €232        103
301         €8624        103
302        €88500        103
303        €10800        102
304          €390        102
305         €8970        102
306         €2925        101
307       €247.50        100
308         €3150        100
309          €475         98
310      €6796.50         98
311       €220.50         97
312       €241.50         97
313       €115.50         96
314       €126.50         96
315      €6205.50         96
316     €10147.50         95
317         €8610         95
318        €22800         94
319          €740         94
320         €6175         93
321          €224         92
322         €8865         92
323         €9840         92
324        €10325         91
325        €15990         91
326         €9225         91
327        €12350         90
328         €3515         90
329         €5850         90
330         €1665         89
331         €1700         89
332        €70800         89
333         €7995         89
334         €2600         88
335          €285         88
336         €4800         88
337          €195         84
338          €525         84
339        €10915         83
340        €11385         83
341         €1155         83
342         €2640         83
343        €6,195         83
344        €1,995         82
345        €11088         82
346        €11820         82
347         €1840         82
348          €780         82
349         €7935         81
350          €805         81
351         €2475         80
352        €38350         79
353         €5225         79
354         €7200         79
355         €8000         79
356        €15200         78
357         €1780         77
358        €20650         77
359         €2835         77
360         €4725         77
361        €14250         74
362         €1520         74
363          €288         74
364          €960         74
365        €10000         73
366         €3200         73
367          €850         73
368         €9315         73
369        €2,090         72
370        €47200         72
371        €6,490         72
372         €6750         72
373         €9025         72
374         €8835         71
375       €172.50         70
376          €370         70
377         €8075         70
378        €28025         68
379         €3825         68
380        €44250         68
381        €23750         67
382         €3780         67
383        €73750         67
384        €11250         66
385      €7072.50         65
386        €16225         64
387         €1335         63
388         €1360         63
389          €585         62
390         €1250         61
391         €7683         61
392          €273         60
393        €11780         59
394          €143         59
395        €15340         59
396          €470         59
397          €940         59
398          €175         58
399     €19987.50         58
400         €2025         58
401          €665         58
402          €185         57
403        €25075         57
404       €487.50         57
405        €18000         56
406        €13000         55
407        €10047         54
408          €209         54
409          €875         54
410        €12000         53
411        €38000         53
412         €2800         52
413          €357         52
414         €5865         52
415         €5175         51
416          €595         51
417          €187         50
418        €1,080         49
419      €1683.50         49
420        €2,280         49
421         €2079         49
422      €3533.50         49
423         €6479         49
424         €6555         49
425        €7,080         49
426       €758.50         49
427          €980         49
428        €1,125         48
429          €429         48
430        €57000         48
431          €979         48
432        €1,350         47
433      €1410.50         47
434        €2,375         47
435        €2,850         47
436          €255         47
437      €2960.50         47
438          €425         47
439        €7,375         47
440          €760         47
441        €8,850         47
442         €8625         47
443        €10455         46
444        €12300         46
445         €3500         46
446           €99         46
447         €2240         45
448         €9660         45
449        €15600         44
450         €2115         44
451         €4465         44
452       €635.50         44
453          €735         44
454         €9975         44
455        €13865         43
456       €202.50         43
457        €27000         43
458         €5415         43
459      €8302.50         43
460        €12915         42
461         €1680         42
462          €235         42
463         €5670         42
464         €7245         42
465        €11396         41
466         €2100         41
467        €30975         41
468         €1950         40
469        €14725         39
470        €16150         39
471        €19500         39
472          €296         39
473         €1140         38
474          €570         38
475         €7650         38
476      €9532.50         38
477     €10342.50         37
478        €22500         37
479       €367.50         37
480        €47500         37
481        €14760         36
482         €3610         36
483         €9548         36
484        €1,035         35
485        €13275         35
486       €192.50         35
487        €2,185         35
488         €2300         35
489         €2520         35
490        €36000         35
491        €6,785         35
492        €60000         35
493         €8274         35
494      €9751.50         35
495        €1,000         34
496         €1157         34
497         €1729         34
498       €232.50         34
499         €2457         34
500       €346.50         34
501         €3629         34
502          €507         34
503        €76000         34
504         €7657         34
505          €779         34
506         €9456         34
507          €975         34
508        €19175         33
509        €20000         33
510         €2225         33
511          €294         33
512          €304         33
513          €336         33
514        €10695         32
515         €1085         32
516          €154         32
517        €16000         32
518        €16815         32
519       €177000         32
520       €181.50         32
521         €2480         32
522        €16250         31
523        €21535         31
524          €247         31
525         €6935         31
526        €11970         30
527       €148.50         30
528        €2,000         30
529       €283.50         30
530        €29450         30
531         €3285         30
532         €3400         30
533         €4450         30
534          €675         30
535      €7978.50         30
536         €9450         30
537        €95000         30
538         €1150         29
539       €118000         29
540        €14160         29
541       €147500         29
542          €275         29
543        €37170         29
544        €45000         29
545        €50150         29
546          €117         28
547        €13300         28
548          €198         28
549        €41300         28
550        €1,440         27
551         €1460         27
552          €248         27
553        €3,040         27
554         €6300         27
555        €9,440         27
556        €1,800         26
557        €11210         26
558        €11704         26
559        €17100         26
560         €2880         26
561        €30000         26
562         €3900         26
563         €7000         26
564      €8569.50         26
565      €8917.50         26
566        €10638         25
567          €190         25
568       €304.50         25
569          €378         25
570          €730         25
571         €8100         25
572       €217.50         24
573        €26000         24
574        €10013         23
575         €1513         23
576          €153         23
577         €2720         23
578       €285000         23
579         €3213         23
580          €323         23
581          €325         23
582         €4720         23
583          €663         23
584        €10005         22
585         €1015         22
586      €1774.50         22
587        €20900         22
588         €2320         22
589         €4005         22
590        €53100         22
591           €80         22
592         €9900         22
593        €10925         21
594        €11730         21
595         €1190         21
596       €159.50         21
597      €3724.50         21
598       €799.50         21
599        €12012         20
600        €12075         20
601         €1225         20
602         €1330         20
603        €21525         20
604        €21850         20
605         €2430         20
606        €29250         20
607        €39000         20
608         €4230         20
609         €4400         20
610         €5130         20
611        €64900         20
612         €8930         20
613        €1,170         19
614        €12420         19
615         €1755         19
616         €1880         19
617       €19,000         19
618        €2,470         19
619          €312         19
620        €4,000         19
621       €59,000         19
622        €7,670         19
623         €1650         18
624       €236000         18
625        €26255         18
626        €33925         18
627         €8455         18
628        €9,000         18
629       €11,800         17
630        €2,945         17
631         €2550         17
632        €3,800         17
633          €365         17
634        €9,145         17
635        €1,395         16
636         €1750         16
637        €27730         16
638          €399         16
639         €4600         16
640        €67850         16
641          €858         16
642          €920         16
643        €1,200         15
644        €1,305         15
645     €10762.50         15
646        €12825         15
647        €14000         15
648        €15930         15
649        €18900         15
650        €2,755         15
651        €32500         15
652         €3705         15
653          €575         15
654        €58900         15
655         €6075         15
656        €8,555         15
657          €890         15
658         €8900         15
659        €11070         14
660        €11700         14
661        €12958         14
662        €25000         14
663        €31500         14
664         €5985         14
665        €66500         14
666        €11505         13
667        €13230         13
668        €13570         13
669     €16912.50         13
670       €17,700         13
671         €1958         13
672        €2,700         13
673         €2070         13
674         €2730         13
675        €39825         13
676        €41230         13
677         €4158         13
678          €418         13
679         €4370         13
680        €5,700         13
681         €5035         13
682         €6230         13
683        €1,980         12
684       €10,030         12
685       €12,980         12
686         €1275         12
687        €13530         12

OR — TEXT VALUES

  stored_value  row_count
0            –     734652

RPR — TEXT VALUES

  stored_value  row_count
0            –     207109

TS — TEXT VALUES

  stored_value  row_count
0            –     623901

NUMERIC RANGES

,minimum_prize,maximum_prize,negative_prize_rows,minimum_or,maximum_or,minimum_rpr,maximum_rpr,minimum_ts,maximum_ts
0,0.12,8000000,0,1,181,1,775,1,178

In [64]:
# Summarise prize storage conventions and inspect extreme rating values.
#
# The aim is to identify:
# - how euro-denominated prizes differ from numeric prize storage;
# - whether other currency symbols occur;
# - the rows behind unusually large rating values.
#
# This is a targeted quality check, not a full prize-money analysis.

prize_storage_summary = pd.read_sql_query(
    f"""
    SELECT
        CASE
            WHEN typeof(prize) = 'text'
             AND length(trim(prize)) = 0
            THEN 'blank text'

            WHEN typeof(prize) = 'text'
             AND prize LIKE '€%'
            THEN 'euro text'

            WHEN typeof(prize) = 'text'
            THEN 'other text'

            WHEN typeof(prize) = 'integer'
            THEN 'integer numeric'

            WHEN typeof(prize) = 'real'
            THEN 'real numeric'

            ELSE typeof(prize)
        END AS prize_storage_group,

        COUNT(*) AS row_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY prize_storage_group
    ORDER BY row_count DESC
    """,
    connection,
)

other_prize_text_values = pd.read_sql_query(
    f"""
    SELECT
        prize AS stored_prize,
        COUNT(*) AS row_count
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND typeof(prize) = 'text'
      AND length(trim(prize)) > 0
      AND prize NOT LIKE '€%'
    GROUP BY prize
    ORDER BY row_count DESC, stored_prize
    """,
    connection,
)

extreme_rating_rows = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        horse,
        pos,
        "or",
        rpr,
        ts,
        comment
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND (
            (typeof("or") = 'integer' AND "or" > 180)
         OR (typeof(rpr) = 'integer' AND rpr > 200)
         OR (typeof(ts) = 'integer' AND ts > 180)
      )
    ORDER BY
        rpr DESC,
        "or" DESC,
        ts DESC,
        date,
        course,
        off
    """,
    connection,
)

display(prize_storage_summary)

print(
    "Distinct non-euro, non-blank text prize values: "
    f"{len(other_prize_text_values):,}"
)
display(other_prize_text_values)

print(
    "Rows with extreme rating values: "
    f"{len(extreme_rating_rows):,}"
)

with pd.option_context(
    "display.max_rows",
    None,
    "display.max_columns",
    None,
    "display.max_colwidth",
    120,
):
    display(extreme_rating_rows)

  prize_storage_group  row_count
0          blank text     839715
1        real numeric     618026
2     integer numeric     225078
3           euro text     168466

Distinct non-euro, non-blank text prize values: 0

Empty DataFrame
Columns: [stored_prize, row_count]
Index: []

Rows with extreme rating values: 3

,source_rowid,date,course,race_id,off,race_name,horse,pos,or,rpr,ts,comment
0,1619851,2025-01-03,Deauville (FR),885653,4:27,Prix de la Seulette (Handicap) (4yo) (All-Weather Track) (Polytrack),Si Capo Si (FR),1,–,775,50,
1,1814076,2026-03-14,Auteuil,915705,16:35,Prix Hubert de Navailles (Conditions Hurdle) (Turf),Theleme (FR),1,181,136,–,
2,1830913,2026-04-19,Auteuil,918364,15:28,Prix Leon Rambaud (Hurdle) (Turf),Theleme (FR),3,181,136,–,

## Performance and prize fields: findings

### `prize`

- The field contains no SQL `NULL` values.
- Missing values are stored as blank text.
- Populated values use two storage conventions:
  - numeric SQLite values for non-euro prize amounts;
  - text beginning with `€` for euro-denominated prize amounts.
- Euro values may contain:
  - decimal amounts;
  - thousands separators.
- No other non-blank text formats were found.
- Currency must therefore be preserved or derived separately rather than
  treating `prize` as one currency-neutral numeric field.

### `or`

- Official ratings are stored as integers when available.
- Missing values are represented by the en dash `–`.
- Numeric values range from 1 to 181.
- The maximum value of 181 appears twice for the same high-class hurdle horse
  and is not treated as an obvious source error.

### `rpr`

- Racing Post Ratings are stored as integers when available.
- Missing values are represented by the en dash `–`.
- Almost all values are within a plausible range.
- One row contains `rpr = 775`, which is an obvious isolated source anomaly and
  should be retained in the raw layer but flagged during transformation.

### `ts`

- Topspeed ratings are stored as integers when available.
- Missing values are represented by the en dash `–`.
- Numeric values range from 1 to 178.
- No obvious extreme anomalies were identified.

### Transformation implications

The raw values should remain unchanged. A later transformation layer should:

1. convert `–` to missing for `or`, `rpr`, and `ts`;
2. cast valid ratings to nullable integers;
3. flag implausible rating outliers such as `rpr = 775`;
4. parse `prize` into separate numeric amount and currency fields;
5. preserve the original `prize` value for auditability.

In [65]:
# Profile the remaining pedigree, ownership, and narrative fields.
#
# These are expected to be text-heavy fields. This first pass checks:
# - SQL NULLs;
# - blank strings;
# - distinct counts;
# - minimum and maximum text lengths.

remaining_text_fields = [
    "sire",
    "dam",
    "damsire",
    "owner",
    "comment",
]

remaining_text_profile_rows = []

for field in remaining_text_fields:
    quoted_field = f'"{field}"'

    result = pd.read_sql_query(
        f"""
        SELECT
            COUNT(*) AS total_rows,

            SUM(
                CASE
                    WHEN {quoted_field} IS NULL
                    THEN 1 ELSE 0
                END
            ) AS null_count,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) = 'text'
                     AND length(trim({quoted_field})) = 0
                    THEN 1 ELSE 0
                END
            ) AS blank_text_count,

            COUNT(DISTINCT {quoted_field})
                AS distinct_non_null_values,

            MIN(
                CASE
                    WHEN typeof({quoted_field}) = 'text'
                     AND length(trim({quoted_field})) > 0
                    THEN length({quoted_field})
                END
            ) AS minimum_populated_length,

            MAX(
                CASE
                    WHEN typeof({quoted_field}) = 'text'
                     AND length(trim({quoted_field})) > 0
                    THEN length({quoted_field})
                END
            ) AS maximum_populated_length,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) = 'text'
                    THEN 1 ELSE 0
                END
            ) AS storage_text,

            SUM(
                CASE
                    WHEN typeof({quoted_field}) <> 'text'
                    THEN 1 ELSE 0
                END
            ) AS non_text_storage_rows
        FROM data
        WHERE {DATA_ROW_PREDICATE}
        """,
        connection,
    ).iloc[0].to_dict()

    result["field_name"] = field
    remaining_text_profile_rows.append(result)

remaining_text_quality = pd.DataFrame(
    remaining_text_profile_rows
)[
    [
        "field_name",
        "total_rows",
        "null_count",
        "blank_text_count",
        "distinct_non_null_values",
        "minimum_populated_length",
        "maximum_populated_length",
        "storage_text",
        "non_text_storage_rows",
    ]
]

display(remaining_text_quality)

,field_name,total_rows,null_count,blank_text_count,distinct_non_null_values,minimum_populated_length,maximum_populated_length,storage_text,non_text_storage_rows
0,sire,1851285,0,0,5445,8,26,1851285,0
1,dam,1851285,0,5,104973,5,26,1851285,0
2,damsire,1851285,0,21,6079,3,20,1851285,0
3,owner,1851285,0,35,98235,2,60,1851285,0
4,comment,1851285,0,340394,1426746,1,2206,1851285,0

In [66]:
# Inspect blank pedigree/ownership rows and unusually long comments.
#
# The purpose is only to determine whether the blanks and long comments look
# like ordinary source behaviour or obvious corruption.

blank_reference_rows = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        horse,
        sire,
        dam,
        damsire,
        owner,
        comment
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND (
            length(trim(dam)) = 0
         OR length(trim(damsire)) = 0
         OR length(trim(owner)) = 0
      )
    ORDER BY
        date,
        course,
        off,
        horse
    """,
    connection,
)

long_comment_rows = pd.read_sql_query(
    f"""
    SELECT
        rowid AS source_rowid,
        date,
        course,
        race_id,
        off,
        race_name,
        horse,
        pos,
        length(comment) AS comment_length,
        comment
    FROM data
    WHERE {DATA_ROW_PREDICATE}
      AND length(comment) >= 500
    ORDER BY
        comment_length DESC,
        date,
        course,
        off
    LIMIT 50
    """,
    connection,
)

print(
    "Rows with blank dam, damsire, or owner: "
    f"{len(blank_reference_rows):,}"
)

with pd.option_context(
    "display.max_rows",
    None,
    "display.max_columns",
    None,
    "display.max_colwidth",
    120,
):
    display(blank_reference_rows)

print(
    "Rows with comments at least 500 characters long: "
    f"{len(long_comment_rows):,}"
)

with pd.option_context(
    "display.max_rows",
    50,
    "display.max_columns",
    None,
    "display.max_colwidth",
    220,
):
    display(long_comment_rows)

Rows with blank dam, damsire, or owner: 54

,source_rowid,date,course,race_id,off,race_name,horse,sire,dam,damsire,owner,comment
0,1443,2015-01-03,Santa Anita (USA),617158,11:30,Santa Ynez Stakes (Fillies) (Dirt),Rattataptap (USA),Tapit (USA),Sindy With An S (USA),Broken Vow,,
1,33009,2015-04-04,Caulfield (AUS),623280,6:10,Le Pine Funerals Easter Cup Handicap) (2yo+) (Turf),Post DFrance (NZ),Postponed (USA),Creil (NZ),Frenchpark,,
2,40683,2015-04-18,Nakayama (JPN),624701,7:40,Nakayama Grand Jump (Turf),Country Snow (JPN),Timber Country (USA),Snow Style (USA),,Yoshio Suzuki,
3,48891,2015-05-03,San Siro (ITY),631223,12:07,Premio Razza Ticino (Turf),Balami Fan (ITY),Johnny Red Kerr (USA),Babwin Di San Jore (ITY),In The Wings,,
4,71791,2015-06-18,Longchamp (FR),630083,11:15,Prix de Bougival (Maiden) (Unraced 3yo Colts & Geldings) (Turf),Rappeur Des Mottes (FR),Racinger (FR),Camille Des Mottes (FR),Abdonski,,
5,127268,2015-10-15,Mombetsu (JPN),638862,11:07,Edelweiss Sho (Local (Fillies) (Dirt),Derma Okaru (JPN),Million Disk (JPN),Admire Lap (JPN),,Hiroyuki Asanuma,
6,191333,2016-04-13,Funabashi (JPN),649077,11:07,Marine Cup (Local (Dirt),Kura Carmen (JPN),Star King Man (USA),Kura Masa Shuttle (JPN),,Toshihiro Kurami,
7,203991,2016-05-07,Maisons-Laffitte (FR),651027,3:30,Prix de lEtoile dArtois (Handicap) (4yo) (Round) (Turf),Colombia DEmra (FR),Naaqoos (GB),Talka (FR),Vettori,,
8,203870,2016-05-07,Maisons-Laffitte (FR),651027,3:30,Prix de lEtoile dArtois (Handicap) (4yo) (Round) (Turf),Star White (FR),Evasive (GB),Spirit Of Monaco (FR),Turtle Island,,
9,234163,2016-07-06,Kawasaki (JPN),655460,11:07,Sparking Lady Cup (Local (Dirt),Kura Carmen (JPN),Star King Man (USA),Kura Masa Shuttle (JPN),,Toshihiro Kurami,
10,254211,2016-08-18,Saga (JPN),657855,11:07,Summer Champion (LocalHandicap) (Dirt),Kassai (JPN),Screen Hero (JPN),,,Makoto Kosuge,
11,255522,2016-08-21,San Sebastian (SPA),657854,6:05,Premio Gobierno Vasco - Eusko Jaurlaritza (),Dagoberto (SPA),Dyhim Diamond (IRE),,,Cuadra Nanina,
12,266790,2016-09-15,Urawa (JPN),659796,11:07,Tele Tama Hai Oval Sprint (Local (Dirt),Legarsi (JPN),Eishin Sandy (JPN),Pink Cutie (JPN),,Nicks Co Ltd,
13,279292,2016-10-10,Morioka (JPN),661298,11:07,Mile Championship Nambu Hai (Local (Dirt),Sea Chrome (JPN),Laurel Guerreiro (JPN),Neroli (JPN),,Katsuyo Ejima,
14,291273,2016-11-03,Kawasaki (JPN),663759,12:07,JBC Sprint (Local (Dirt),Sea Chrome (JPN),Laurel Guerreiro (JPN),Neroli (JPN),,Kazuo Okubo,
15,354528,2017-04-12,Funabashi (JPN),673713,11:07,Marine Cup (Local (Dirt),Kura Carmen (JPN),Star King Man (USA),Kura Masa Shuttle (JPN),,Toshihiro Kurami,
16,365735,2017-05-04,Sonoda (JPN),676214,11:07,Hyogo Championship (Local (Dirt),Kumari (JPN),Time Paradox (JPN),Laurel Easter (JPN),,Masahiko Higuchi,
17,490573,2018-01-24,Ohi (JPN),693423,11:07,TCK Jo-o Hai (Local (Fillies & Mares) (Dirt),Luna Mattino (JPN),Kinshasa No Kiseki (AUS),Rosage (USA),,Hidenori Akanuma,
18,490577,2018-01-24,Ohi (JPN),693423,11:07,TCK Jo-o Hai (Local (Fillies & Mares) (Dirt),Party Dress (JPN),Durandal (JPN),Gronskar (JPN),,Reiko Hara,
19,615482,2018-10-11,Ohi (JPN),714164,11:07,Ladies Prelude (Local (Dirt),Ace With (JPN),Kinshasa No Kiseki (AUS),,,Kosumosu Yamanaka,
20,712612,2019-05-13,Saint-Cloud (FR),730833,4:55,Prix de la Vallee du Lot (Handicap) (4yo+) (Turf),Le Letty (FR),Youmzain (IRE),Pretty Reel (FR),Country Reel,,
21,725030,2019-06-03,Longchamp (FR),732516,4:55,Prix de la Porte de la Seine (Handicap) (4yo+) (Grande Course) (Turf),Le Letty (FR),Youmzain (IRE),Pretty Reel (FR),Country Reel,,
22,801287,2019-10-31,Mombetsu (JPN),744785,11:07,Hokkaido Nisai Yushun (Local (Dirt) (2yo),Abenin Dream (JPN),On Fire (JPN),Abenin Prunus (JPN),South Vigorous,,
23,801315,2019-10-31,Mombetsu (JPN),744785,11:07,Hokkaido Nisai Yushun (Local (Dirt) (2yo),Adjuvant (JPN),Figaro (USA),Schwerin (JPN),Manhattan Cafe,,
24,801290,2019-10-31,Mombetsu (JPN),744785,11:07,Hokkaido Nisai Yushun (Local (Dirt) (2yo),Chimera Verite (JPN),Kizuna (JPN),Lumiere Verite (USA),Cozzene,,
25,801304,2019-10-31,Mombetsu (JPN),744785,11:07,Hokkaido Nisai Yushun (Local (Dirt) (2yo),Meiner Astoria (JPN),Hard Spun (USA),Oregon Lady (IRE),Shamardal,,
26,801310,2019-10-31,Mombetsu (JPN),744785,11:07,Hokkaido Nisai Yushun (Local (Dirt) (2yo),Pionono (JPN),King Kamehameha (JPN),Marshmallow (JPN),Kurofune,,
27,871698,2020-08-08,Flemington (AUS),768529,3:05,TAB Handicap (Turf),Bertwhistle (AUS),Al Maher (AUS),,,,
28,871699,2020-08-08,Flemington (AUS),768529,3:05,TAB Handicap (Turf),Flag Edition (NZ),Raise The Flag (GB),Ears Carol (NZ),Carolingian,,
29,902806,2020-10-03,Newcastle (AUS),769163,5:49,Happy 60th Nern Maiden Plate,Deel With Me (AUS),Dundeel (NZ),Twelve Oclock Rock (NZ),OReilly,,
30,902808,2020-10-03,Newcastle (AUS),769163,5:49,Happy 60th Nern Maiden Plate,Imperial Grey (AUS),Dundeel (NZ),La Fouine Tail (JPN),Neo Universe,,
31,902803,2020-10-03,Newcastle (AUS),769163,5:49,Happy 60th Nern Maiden Plate,Luftwaffe (AUS),Panzer Division (AUS),West Love (AUS),Zedrich,,
32,902802,2020-10-03,Newcastle (AUS),769163,5:49,Happy 60th Nern Maiden Plate,Media Man (AUS),Press Statement (AUS),Mary Of Modena (AUS),Encosta De Lago,,
33,902801,2020-10-03,Newcastle (AUS),769163,5:49,Happy 60th Nern Maiden Plate,Nu Jiang (AUS),Headwater (AUS),Prison Rules (AUS),Onemorenomore,,
34,902805,2020-10-03,Newcastle (AUS),769163,5:49,Happy 60th Nern Maiden Plate,Stormwater (AUS),Headwater (AUS),Mortal Sin (AUS),All American,,
35,949270,2020-12-29,Ohi (JPN),775291,11:07,Tokyo Daishoten (Dirt) (3yo+),Casino Fountain (JPN),Casino Drive (USA),Gina Fontaine (JPN),Best Tie Up,,
36,989818,2021-04-07,Funabashi (JPN),782234,11:07,Marine Cup (Local (3yo+) (Fillies & Mares) (Dirt),Absolute Queen (JPN),Kane Hekili (JPN),Ideal Queen (JPN),Aswan,,
37,1044085,2021-07-14,Ohi (JPN),789638,11:07,Japan Dirt Derby (Local (3yo) (Dirt),Castle Top (JPN),Bamboo Ere (JPN),Sieger Top Run (JPN),Mayano Top Gun,,
38,1112631,2021-12-01,Funabashi (JPN),799985,11:07,Queen Sho (Local (3yo+ Fillies & Mares) (Dirt),Dear Rickey (JPN),Hokko Tarumae (JPN),Paquita (JPN),Special Week,,
39,1118781,2021-12-15,Kawasaki (JPN),800932,11:07,Zen-Nippon Nisai Yushun (Local (2yo) (Dirt),Praelude (JPN),Lovely Day (JPN),Anthology (JPN),Sakura Bakushin O,,
40,1118779,2021-12-15,Kawasaki (JPN),800932,11:07,Zen-Nippon Nisai Yushun (Local (2yo) (Dirt),SIl Te Plait (JPN),World Ace (JPN),Air DYquem (JPN),French Deputy,,
41,1171417,2022-04-20,Ohi (JPN),810727,11:07,Tokyo Sprint (Local (4yo+) (Dirt),Gishigishi (JPN),Aldebaran (USA),Rani (JPN),Hearts Cry,,
42,1214955,2022-07-13,Ohi (JPN),817393,11:07,Japan Dirt Derby (Local,Cryogenic (JPN),Roses In May (USA),Kogyo Digital (JPN),Agnes Digital,,
43,1214956,2022-07-13,Ohi (JPN),817393,11:07,Japan Dirt Derby (Local,Hapi (JPN),Kizuna (JPN),,,,
44,1215931,2022-07-15,Killarney (IRE),817263,3:25,Dawn Milk Omega Mares Maiden Hurdle,Fiery Brown (IRE),Robin Des Champs (FR),Sarah Massini (IRE),Dr Massini,,Towards rear of midfield - ridden but no impression from 4 out(op 9/1 tchd 17/2)
45,1217236,2022-07-18,Morioka (JPN),817570,11:07,Mercury Cup (Local (3yo+) (Dirt),Giga King (JPN),King Halo (JPN),Wolf Call (JPN),Bubble Gum Fellow,,
46,1217234,2022-07-18,Morioka (JPN),817570,11:07,Mercury Cup (Local (3yo+) (Dirt),Vacation (JPN),Espoir City (JPN),Tenno Benibara (JPN),Soccer Boy,,
47,1249441,2022-09-28,Funabashi (JPN),823080,11:07,Nippon TV Hai (Local (3yo+) (Dirt),Giga King (JPN),King Halo (JPN),Wolf Call (JPN),Bubble Gum Fellow,,
48,1273903,2022-11-13,Busan (KOR),830140,7:45,Race 6 (Dirt) (Handicap),Happy Fever (KOR),Simon Pure (USA),Feversham (USA),Distorted Humor,,
49,1385063,2023-08-17,Mombetsu (JPN),848096,11:07,Breeders Gold Cup (Local (3yo+) (Fillies & Mares) (Dirt),Paraiba Tourmaline (USA),Malibu Moon (USA),Private Jet (USA),,Unknown,
50,1765733,2025-11-15,Auteuil,908408,14:15,Geny.com - Prix Count Schomberg (Hurdle) (Listed Handicap) (5yo+) (Turf),New President (FR),Sinndar (IRE),Sun Song II (FR),,Daniel Frouin Fabrice Foucher,
51,1798032,2026-02-01,Gavea,912936,21:20,Grande Premio Estado Do Rio de Janeiro - Haras Santa Maria de Araras (Turf),Off Limits (BRZ),Put It Back (USA),Gucci Star (BRZ),,Haras Legacy,
52,1827693,2026-04-12,Gavea,918042,21:45,Grande Premio Cruzeiro Do Sul - Haras Santa Maria de Araras (Turf),Zack Attack (BRZ),Verrazano (BRZ),Et Voila (USA),,Haras Doce Vale,
53,1827679,2026-04-12,Gavea,918043,23:05,Grande Premio Zelia Gonzaga Peixoto de Castro (Fillies) (Turf),Hardest (BRZ),Drosselmeyer (USA),Parnaioca (BRZ),,Stud Sion,

Rows with comments at least 500 characters long: 50

,source_rowid,date,course,race_id,off,race_name,horse,pos,comment_length,comment
0,1622460,2025-01-13,Wolverhampton (AW),884463,5:30,Boost Your Acca At BetMGM Apprentice Handicap,Further Measure (USA),4,2206,Raced in last - still plenty to do when switched right over 1f out - ran on but never near to challenge (inquiry held into running and riding of gelding which raced in rear throughout before staying on strongly downh...
1,1745480,2025-10-06,Wolverhampton (AW),903500,4:20,Free Tips Daily On attheraces.com Amateur Jockeys Handicap,Oman (IRE),9,2083,In rear and raced wide early - still plenty to do and waiting for room over 1f out - nudged along and some headway inside final furlong (enq held into the running and riding of the gelding - which jumped well from st...
2,873883,2020-08-13,Tramore (IRE),764173,6:15,Flynn Hotels Handicap Hurdle,Enzani (IRE),PU,2034,Mid-division - dropped towards rear 6th - detached and pulled up before 3 out (jockey said gelding lost its action and was pulled up; an enquiry was held into the running and riding of Enzani; evidence was heard from...
3,1337070,2023-05-10,Gowran Park (IRE),840379,5:25,Racing Again May 23rd Handicap,Ellaat (GB),4,2023,Dwelt start - towards rear - headway under 3f out - tenderly handled but kept on well inside final furlong - went fourth towards finish - not reach leaders - eyecatcher (inquiry into running and riding of gelding; jo...
4,1753197,2025-10-20,Wolverhampton (AW),904488,16:55,Download The Raceday Ready App Apprentice Handicap,Bandello (GB),4,1990,In rear - still plenty to do 2f out - headway from over 1f out - kept on inside final furlong - nearest finish (inquiry into running and riding of gelding which jumped awkwardly from talls before racing towards the r...
5,1478171,2024-03-19,Wolverhampton (AW),861346,7:30,Win £2 000 000 With BetMGMs Golden Goals Handicap (Rider Restricted Race),Kodi Noir (IRE),10,1986,Slowly away - in rear - no telling impression (inquiry held into running and riding; rider and Mr Clutterbuck were interviewed and shown recordings of race; vet had nothing to report; rider said that his instructions...
6,1653708,2025-03-31,Wolverhampton (AW),889579,4:55,Extra Winnings With BetUK Acca Club Amateur Jockeys Handicap,Nevernay (IRE),9,1948,In rear - awkward start and lost many lengths - soon detached - some headway home straight - no impression (inquiry held into running and riding of gelding which jumped awkwardly from stalls and lost several lengths ...
7,1140782,2022-02-10,Doncaster,802285,3:20,Virgin Bet Novices Hurdle (Novices Championship Novices Hurdle Series Qualifier),Flaming Ambition (IRE),4,1937,Took keen hold - held up in rear - nudged along before 3 out - going okay but still plenty to do before 2 out - pushed along approaching last - stayed on run-in - eyecatcher (an enquiry was held into the running and ...
8,1657172,2025-04-07,Wolverhampton (AW),890629,4:05,Boost Your Acca At BetMGM Handicap,Charlatan (IRE),9,1896,Held up in rear - not clear run over 1f out - no impression (jockey was questioned regarding his riding of gelding over final 2f after reporting at scales that he had been denied a clear run in home straight; jockey ...
9,1434551,2023-11-25,Huntingdon,853038,12:28,Follow Us On Twitter @betrhino Maiden Hurdle (GBB Race),Zain Nights (GB),3,1895,Midfield - not fluent 3 out - soon shaken up - not fluent last - kept on well run-in - went third inside final 110yds - eyecatcher (inquiry held into running and riding of gelding - which raced mid-division and was t...
10,870801,2020-08-06,Stratford,761774,4:50,Watch On Racing TV Novices Handicap Chase,Simon The Great (GB),3,1816,Held up in last - headway and still plenty to do 2 out - went third last - ridden and stayed on run-in - not reach leaders (An enquiry was held into the running and riding of the gelding - which was held up in last p...
11,938336,2020-12-03,Leicester,770582,2:37,Racecourse Live Streams On RacingTV Extra Mares National Hunt Maiden Hurdle (GBB Race),Uptown Lady (IRE),4,1789,Held up in rear - went poor fourth run-in - never near to challenge (stewards inquired into running and riding; jockey said that his instructions were to be handily away - give mare plenty of room and try to get mare...
12,1495857,2024-04-27,Wolverhampton (AW),864618,6:00,Get Raceday Ready Apprentice Handicap,Sea The Buckthorn (GB),7,1788,Taken down early - held up in rear - nudged along over 1f out - carried left 1f out - kept on inside final furlong - never near to challenge (inquiry held into running and riding of gelding which was restrained at st...
13,1115289,2021-12-07,Fontwell,798161,3:20,John And Maryanne Birch Memorial Handicap Hurdle,Good Bye (GER),4,1762,Towards rear of midfield - going okay but still plenty to do 8th - shaken up last (usual 2 out) - soon well held - stayed on when tenderly handled run-in - not reach leaders - too much to do - eyecatcher (an enquiry ...
14,1780605,2025-12-17,Ludlow,908622,12:13,Tanners Cava EBF National Hunt Novices Hurdle (Qualifier) (GBB Race),Can U Feel It (IRE),9,1742,Held up in rear - some headway from 2 out - never dangerous (inquiry into running and riding of gelding - which raced towards the rear throughout before staying on steadily under a hands and heels ride in home straig...
15,1072856,2021-09-14,Fontwell,793351,2:05,Follow @starsports_bet On Twitter Handicap Hurdle (Div II),Get Supreme (IRE),5,1700,Took keen hold - raced wide early - prominent - lost position 4 out - soon dropped to rear - ridden briefly after 3 out - nudged along and no impression from 2 out - never near to challenge (stewards inquired nto run...
16,1121901,2021-12-22,Ludlow,799228,2:45,Tanners Prosecco National Hunt Novices Hurdle (GBB Race),Stumps Or Slips (IRE),9,1700,Took keen hold - held up in rear - not fluent 1st - some headway when mistake 3 out - soon pushed along and no impression (an enquiry was held into the running and riding of the gelding - which was ridden towards the...
17,1318524,2023-03-27,Wolverhampton (AW),834703,6:30,talkSPORT Download The App Novice Stakes (GBB Race),Musterion (IRE),8,1689,Bumped start - in rear - pushed along but no impression from 2f out (inquiry held into running and riding of filly which was bumped leaving the stalls and settled towards the rear of the field early on - before then ...
18,1437608,2023-12-04,Wolverhampton (AW),854367,6:00,Bet £10 Get £40 At BetMGM Maiden Stakes (Rider Restricted Race) (GBB Race),Pierrefonds (GB),6,1680,Slowly away - in rear - going okay 2f out - nudged along and headway from over 1f out - never near to challenge - eyecatcher (jockey said - regarding running and riding - that his instructions were to make sure he go...
19,1639778,2025-02-27,Ludlow,887193,2:35,Good Life Plus Free Prize Draws Novices Hurdle (GBB Race),King Of Records (FR),3,1668,Held up in midfield - headway when jumped right and nudged along 3 out - went fourth 2 out - jumped right and 5 lengths down last - ridden and ran on well run-in - went third final strides (inquiry into running and r...
20,1095238,2021-10-25,Leicester,794914,2:15,British Stallion Studs EBF Novice Stakes (GBB Race),Buachaill (IRE),4,1664,Towards rear of midfield - pushed along 2f out - headway inside final furlong - ran on towards finish (enq held into the running and riding of the gelding - which raced in mid division throughout before staying on un...
21,1428735,2023-11-14,Wolverhampton (AW),852044,6:30,Stay In Control At BetMGM Handicap,Star Zinc (IRE),6,1654,Steadied start - took keen hold - held up in rear - ran on inside final furlong - never near to challenge (jockey said - regarding running and riding - her instructions were to remove blind as late as possible in ord...
22,870862,2020-08-06,Stratford,764039,6:50,Racing TV Profits Returned To Racing Handicap Hurdle (Div II),Mighty Meg (GB),6,1652,Held up in rear - nudged along 2 out - reminders and headway approaching last - kept on run-in - not reach leaders (An enquiry was held into the running and riding of the mare - which was held up in rear throughout u...
23,1004785,2021-05-04,Wolverhampton (AW),781736,5:30,New Betting Sites At bellbet.com Handicap,Whatwouldyouknow (IRE),8,1627,Held up in rear - pushed along over 2f out - kept on inside final furlong - never near to challenge (An enquiry was held into the running and riding of the gelding - which after breaking on terms with the field - was...
24,1499481,2024-05-04,Thirsk,864566,2:10,Follow @vickersracing On X Handicap,Royal Pleasure (IRE),4,1602,Held up in rear - some headway going easily 2f out - edged right over 1f out - not clear run repeatedly inside final furlong - nudged along when in the clear inside final 110yds - ran on well - eyecatcher (inquiry he...
25,1477425,2024-03-16,Kempton,861139,3:20,Unibet 3 Uniboosts A Day Mares Novices Hurdle (Herring Queen Series Qualifier) (GBB Race),Cher Tara (IRE),9,1600,Held up in rear - pushed along and some headway after 3 out - not clear run before 2 out - soon no impression (inquiry held into running and riding of mare which was held up in rear of field before given a hands and ...
26,672558,2019-02-20,Punchestown (IRE),723234,3:15,Pertemps Network Group Handicap Hurdle (Qualifier),Its All Guesswork (IRE),3,1595,Waited with in rear - last at halfway - progress going well after 4 out - not fluent 3 out and next - soon pushed along in 8th and progress before last where left 4th - ran on - nearest finish (stewards inquired into...
27,1733896,2025-09-15,Worcester,901688,3:00,BetWright Bangers NCash Maiden Hurdle (ARC Summer Novices Brush Hurdle Qualifier) (GBB) (Div I),Lewisham Grove (IRE),5,1593,Midfield - some headway 3 out - no impression from 2 out (inquiry held into running and riding of gelding which raced in mid-division throughout before staying on under considerate handling at times in home straight ...
28,1442409,2023-12-16,Wolverhampton (AW),854484,6:00,Best Racing Odds Guaranteed At BetMGM Novice Stakes (GBB Race),Body Parts (IRE),7,1585,Dwelt start - held up in last - nudged along from over 1f out - some headway inside final furlong - eyecatcher (inquiry into running and riding; jockey said instructions were to expect filly to be slowly away as she ...
29,1494815,2024-04-25,Huntingdon,864303,6:45,Racing TV Handicap Hurdle (Div I),Parc dAmour (IRE),2,1585,Held up in last - headway and in touch with leaders 7th - headway on inner when short of room and hampered home turn - good headway approaching last - jumped right and went second last - ridden and ran on run-in - ne...
30,1099369,2021-11-01,Wolverhampton (AW),795034,3:30,MansionBet Best Odds Guaranteed Handicap,Rectory Road (GB),6,1571,Slowly away - held up in rear - pushed along over 1f out - minor headway inside final furlong - never dangerous (jockey said - regarding running and riding - her instructions were to jump out - get the gelding to set...
31,1322325,2023-04-07,Lingfield (AW),834820,2:05,BetUK All-Weather Vase Marathon Handicap,Mr Escobar (IRE),9,1571,Hung left throughout - prominent - going easily when bit short of room over 1f out - eased final furlong (jockey said - regarding running and riding - that he had been given no specific instructions other than to rid...
32,1174824,2022-04-27,Ascot,808596,1:50,Manny Mercer Apprentice Handicap,Hathlool (IRE),5,1570,Dwelt start - raced in last - going okay over 2f out - switched right and pushed along over 1f out - not clear run inside final furlong - pushed out and kept on well when in the clear inside final 110yds (enq held in...
33,1680510,2025-05-22,Wolverhampton (AW),894197,9:00,Race And Rest - Wolverhampton Holiday Inn Fillies Handicap,Sibyl Charm (IRE),4,1564,Dwelt start - in rear - going okay but plenty to do over 1f out - pushed along and good headway inside final furlong - never near to challenge (inquiry held into running and riding; jockey said his instructions from ...
34,1452528,2024-01-12,Wolverhampton (AW),856599,7:00,Boost Your Acca At BetMGM Fillies Handicap,Dazy Mazy (GB),4,1563,Towards rear - not clear run and switched right inside final furlong - ran on well final 110yds - not reach leaders - eyecatcher (jockey was asked to explain his riding in home straight; jockey said his instructions ...
35,1643603,2025-03-08,Wolverhampton (AW),887477,5:40,Win £1M With BetMGMs Golden Goals Handicap,Hala Joza (GB),8,1555,Dwelt start - in rear throughout - no chance when not clear run inside final furlong (An inquiry was held into the running and riding of Hala Joza - ridden by Darragh Keenan and trained by Martin Dunne - which jumped...
36,1119168,2021-12-16,Naas (IRE),800627,1:25,John Thomas McNamara Series (Q.R.) Handicap Hurdle,My Boy Bob (IRE),3,1552,Held up in rear - steady headway from 3rd - midfield 3 out - disputing fourth 2 out - soon shaken up and went third - kept on well - never near to challenge (jockey said - regarding running and riding - that she was ...
37,1312781,2023-03-10,Wolverhampton (AW),835259,3:55,Spreadex Sports Live UK Racing Streaming Classified Stakes,Good Humor (GB),2,1552,Held up in rear - going okay but waiting for room home turn - pushed along and headway over 1f out - ridden inside final furlong - kept on final 110yds - went second final strides (inquiry held into running and ridin...
38,841550,2020-02-16,Navan (IRE),751332,1:20,Get Your 2020 Navan Membership Maiden Hurdle (Div I),Oscar Thyne (IRE),4,1548,Mid-division - raced keenly - headway on outer 4 out - no impression on leaders in moderate 6th after 3 out - kept on in behind into moderate 4th - not hard ridden (enq into the running and riding of the gelding - tr...
39,1368829,2023-07-10,Roscommon (IRE),845304,6:05,Frenchpark Maiden Hurdle,Ballycallan King (IRE),2,1548,Towards rear - headway before 3 out - stayed on and went second run-in - no match for winner (inquiry into running and riding of gelding; jockey stated that he was instructed to sit 5th or 6th on rails - make progres...
40,954102,2021-01-13,Naas (IRE),775517,1:20,Irish Stallion Farms EBF Novice Chase,Blackbow (IRE),3,1536,Raced in last but in touch with leaders - mistake 5 out - went modest third after 3 out - no impression when tenderly handled after 2 out - never near to challenge (jockey said that his mount hung left; vet reported ...
41,1476462,2024-03-15,Wolverhampton (AW),861314,7:30,Boost Your Acca At BetMGM Handicap,Keady Town (IRE),2,1535,Held up in rear - outpaced over 3f out - headway over 1f out - switched right inside final furlong - pushed along and went second towards finish (inquiry held into running and riding of gelding which was restrained l...
42,1486235,2024-04-08,Wincanton,863169,2:38,Golf Membership On Sale Now Maiden Hurdle (GBB Race),Northern Air (IRE),2,1535,Took keen hold - held up in rear - not fluent 3 out - tenderly handled and headway before 2 out - pushed along and went second run-in - not reach winner - eyecatcher (inquiry held into the running and riding of mare ...
43,1830314,2026-04-18,Bangor-on-Dee,915383,13:17,Broxton Gates Novices Hurdle (GBB Race),Tunisya (FR),10,1531,Held up in rear - headway into midfield after 4th - lost ground from 3 out - tailed off (inquiry held into running and riding; rider and trainer were interviewed and shown recordings of race; vet examined filly on tw...
44,674955,2019-02-26,Wolverhampton (AW),722109,5:30,Sun Racing Novice Stakes,Irish Charm (FR),9,1510,Held up - never involved (enq held into the running and riding of the horse which after breaking slowly from the stalls and settling slightly worse than midfield had stayed on under apparent tender handling to finish...
45,1139812,2022-02-07,Fontwell,802244,2:25,Virgin Bet Maiden Hurdle (Novices Championship Hurdle Series Qualifier) (GBB Race),Forward Plan (IRE),6,1509,Held up in rear - going okay but still plenty to do 3 out - soon short of room and switched right - pushed along when not clear run home turn - tenderly handled but keeping on when jumped right 2 out - edged left app...
46,1653711,2025-03-31,Wolverhampton (AW),889579,4:55,Extra Winnings With BetUK Acca Club Amateur Jockeys Handicap,Drafted (IRE),11,1501,Took keen hold - held up in last - soon detached - some headway from over 1f out - never near to challenge (inquiry held into running and riding of gelding which was heavily restrained leaving stalls and became detac...
47,959472,2021-01-29,Wolverhampton (AW),774704,5:15,Bombardier Handicap,Regulator (IRE),4,1487,Slowly into stride - took keen hold - held up in rear - shaken up over 1f out - not clear run and ran on inside final furlong - not reach leaders (stewards inquired into running and riding; jockey said his instructio...
48,1597512,2024-11-13,Bangor-on-Dee,879019,12:25,Paul Ferguson Jumpers To Follow Handicap Chase,Champagnesuperover (IRE),10,1484,In rear - headway before 2 out - never near to challenge nudged out (an inquiry was held into running and riding; rider and trainer were interviewed; vet examined gelding which was selected for routine testing on two...
49,1457254,2024-01-25,Wetherby,857341,4:10,Racing TV Profits Returned To Racing Novices Handicap Hurdle,Fainche (IRE),3,1483,Held up in rear - some headway when short of room 3 out - tenderly handled before 2 out - ran on and went third run-in - eyecatcher (inquiry was held into running and riding; rider and the trainer were interviewed an...

## Pedigree, ownership, and comment fields: findings

### `sire`, `dam`, and `damsire`

- All three fields are stored consistently as text.
- No SQL `NULL` values are used.
- `sire` is fully populated.
- `dam` has only 5 blank rows.
- `damsire` has only 21 blank rows.
- The small number of blanks appears to reflect incomplete source coverage,
  especially in some overseas records, rather than malformed data.

### `owner`

- The field is stored consistently as text.
- No SQL `NULL` values are used.
- Only 35 rows are blank.
- Blank ownership values are rare and appear to be ordinary missing source data.

### `comment`

- The field is stored consistently as text.
- Missing comments are represented by blank strings.
- 340,394 rows have blank comments.
- Populated comments range from 1 to 2,206 characters.
- Very long comments are legitimate extended steward-enquiry and
  running-and-riding notes rather than obvious corruption.
- The complete raw comment should therefore be preserved without truncation.

### Transformation implications

A later transformation layer should:

1. convert blank `dam`, `damsire`, `owner`, and `comment` values to missing;
2. retain pedigree and ownership fields as text;
3. preserve the full unaltered comment text;
4. avoid imposing a restrictive comment-length limit;
5. retain raw values for auditability.

## Notebook 02 conclusion

This notebook profiled the source fields at row level and established the main
quality rules needed for later transformation work.

### Main conclusions

- The imported header row must be excluded with `rowid <> 1`.
- The source uses blank strings and sentinel values rather than SQL `NULL`.
- Several fields contain mixed storage types despite their declared SQLite type.
- Raw values should remain unchanged in the source layer.
- Cleaning and type conversion should happen only in a separate transformation
  layer.

### Important field-specific rules

- `date`, `course`, `off`, and `race_name` can be used as a provisional race
  grouping key, but this is not yet a permanent race identifier.
- `pos` contains both numeric placings and non-finisher status codes.
- Numeric finishing positions may contain gaps or exceed `ran`.
- `btn`, `ovr_btn`, and `time` preserve aspects of the physical finish even when
  official placings are later revised.
- `draw` is blank where no draw applies.
- `wgt` is stored as stone-pound text and can later be converted to total pounds.
- `hg` contains compact headgear codes and combinations.
- `sp` is mostly fractional-odds text with a small number of malformed values.
- `prize` combines numeric values with euro-prefixed text and therefore requires
  separate amount and currency fields.
- `or`, `rpr`, and `ts` use `–` as their missing-value marker.
- The isolated `rpr = 775` value should be retained raw and flagged as anomalous.
- Pedigree and ownership blanks are rare.
- Long comments are legitimate steward and running notes and must not be
  truncated.

### Transformation principles

The later cleaned layer should:

1. preserve every original raw field;
2. add parsed and standardised columns alongside the raw values;
3. convert known blanks and sentinels to explicit missing values;
4. use nullable numeric types;
5. add anomaly flags instead of silently correcting questionable values;
6. keep transformation logic reproducible and documented;
7. avoid enforcing assumptions that the source evidence does not support.

The next notebook can use these findings to design the cleaned staging schema and
formal transformation rules.

In [67]:
# Close the read-only SQLite connection now that profiling is complete.

connection.close()

print("Notebook 02 complete: source field quality profile finished.")

Notebook 02 complete: source field quality profile finished.