# Notebook 04 — Course, Jurisdiction and Surface Mapping

## Purpose

This notebook investigates how racecourses, jurisdictions and racing surfaces are represented across the source data, and which canonical attributes can be derived reliably without discarding jurisdiction-specific meaning.

The raw `course` field contains venue names and, for many international courses, apparent jurisdiction suffixes or other naming conventions. Surface information may be represented through several fields, including:

- `course`;
- `race_name`;
- `type`;
- combinations of those fields.

These representations have not yet been tested systematically. Course names may also vary across time, distinguish multiple tracks at one physical venue, or appear similar despite referring to venues in different jurisdictions.

This notebook will test:

- the inventory and frequency of raw `course` values;
- how course names encode country or racing jurisdiction;
- which suffixes and naming patterns can support jurisdiction parsing;
- where jurisdiction cannot be inferred reliably from `course` alone;
- how turf, all-weather and other surface information is represented;
- whether surface evidence appears in `course`, `race_name`, `type`, or combinations of fields;
- where one apparent physical venue has multiple raw course-name variants;
- where similar course names may refer to different jurisdictions or materially different tracks;
- how course names and representations vary over time;
- which raw values and source-lineage attributes must be preserved;
- which candidate canonical course, jurisdiction and surface attributes a later staging layer may require.

The notebook will produce course-name inventories, parsing evidence, candidate canonicalisation rules, collision and ambiguity evidence, and unresolved-risk recommendations. It will not design the final target schema.

In [1]:
# Read-only source setup for Notebook 04.
#
# The raw SQLite database is immutable. Opening it with SQLite's URI
# read-only mode prevents this notebook from modifying the source file.

from pathlib import Path
import sqlite3

# Resolve the repository root whether the notebook is run from the project
# root or from the notebooks/ directory.
PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SOURCE_DB = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "form_2015-present"
    / "form_2015-present"
    / "raceform.db"
)

SOURCE_TABLE = "data"
DATA_ROW_PREDICATE = "rowid <> 1"

if not SOURCE_DB.exists():
    raise FileNotFoundError(f"Source database not found: {SOURCE_DB}")

# mode=ro enforces read-only access at the SQLite connection level.
connection = sqlite3.connect(f"file:{SOURCE_DB}?mode=ro", uri=True)
connection.row_factory = sqlite3.Row

print(f"Project root: {PROJECT_ROOT}")
print(f"Source database: {SOURCE_DB}")
print("SQLite access: read-only")
print(f"Source table: {SOURCE_TABLE}")
print(f"Data-row predicate: {DATA_ROW_PREDICATE}")

Project root: /home/rob/Documents/inside-rails-horse-racing
Source database: /home/rob/Documents/inside-rails-horse-racing/data/raw/form_2015-present/form_2015-present/raceform.db
SQLite access: read-only
Source table: data
Data-row predicate: rowid <> 1

In [2]:
# Measure the headline structure of the raw course field.
#
# This cell establishes:
# - total data-like runner rows;
# - number of distinct raw course values;
# - whether blank course values exist;
# - minimum and maximum dates attached to the course population.
#
# This is descriptive only. It does not yet attempt to parse jurisdictions,
# identify physical venues, or canonicalise course names.

import pandas as pd

course_summary_sql = f"""
SELECT
    COUNT(*) AS runner_rows,
    COUNT(DISTINCT course) AS distinct_raw_course_values,
    SUM(CASE WHEN TRIM(CAST(course AS TEXT)) = '' THEN 1 ELSE 0 END)
        AS blank_course_rows,
    MIN(date) AS earliest_date,
    MAX(date) AS latest_date
FROM {SOURCE_TABLE}
WHERE {DATA_ROW_PREDICATE}
"""

course_summary = pd.read_sql_query(course_summary_sql, connection)
course_summary

,runner_rows,distinct_raw_course_values,blank_course_rows,earliest_date,latest_date
0,1851285,528,0,2015-01-01,2026-05-27

In [3]:
# Build the raw course-name inventory.
#
# For each exact source value, this cell measures:
# - runner-row frequency;
# - provisional race frequency using date + course + off;
# - number of active dates;
# - first and last observed dates.
#
# Raw course values are left unchanged. No trimming, suffix removal,
# jurisdiction parsing, or canonicalisation is applied here.

course_inventory_sql = f"""
WITH provisional_races AS (
    SELECT
        date,
        course,
        off
    FROM {SOURCE_TABLE}
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY
        date,
        course,
        off
),
race_counts AS (
    SELECT
        course,
        COUNT(*) AS provisional_races
    FROM provisional_races
    GROUP BY course
),
runner_counts AS (
    SELECT
        course,
        COUNT(*) AS runner_rows,
        COUNT(DISTINCT date) AS active_dates,
        MIN(date) AS first_date,
        MAX(date) AS last_date
    FROM {SOURCE_TABLE}
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY course
)
SELECT
    rc.course,
    rc.runner_rows,
    races.provisional_races,
    rc.active_dates,
    rc.first_date,
    rc.last_date
FROM runner_counts AS rc
JOIN race_counts AS races
    ON races.course = rc.course
ORDER BY
    rc.runner_rows DESC,
    rc.course
"""

course_inventory = pd.read_sql_query(course_inventory_sql, connection)

print(f"Inventory rows: {len(course_inventory):,}")
course_inventory.head(30)

Inventory rows: 528

,course,runner_rows,provisional_races,active_dates,first_date,last_date
0,Wolverhampton (AW),64746,7042,930,2015-01-02,2026-05-18
1,Sha Tin (HK),52010,4160,435,2015-01-25,2025-10-12
2,Kempton (AW),50268,5046,662,2015-01-07,2026-05-27
3,Chantilly (FR),48744,4140,497,2015-01-23,2025-10-14
4,Deauville (FR),48618,4051,472,2015-01-03,2025-08-30
5,Newcastle (AW),42092,4409,583,2016-05-17,2026-05-19
6,Lingfield (AW),41632,4803,742,2015-01-03,2026-05-12
7,Dundalk (AW) (IRE),39075,3318,428,2015-01-02,2025-10-14
8,Chelmsford (AW),37741,4310,593,2015-01-11,2026-03-26
9,Southwell (AW),34488,3816,515,2015-01-01,2026-05-21
10,Auteuil (FR),32708,3147,393,2015-03-01,2025-10-12
11,Happy Valley (HK),31058,2687,316,2016-01-06,2025-10-08
12,Saint-Cloud (FR),28412,2558,311,2015-03-07,2025-10-09
13,Doncaster,26166,2805,389,2015-01-09,2026-05-16
14,Curragh (IRE),21921,1743,226,2015-03-29,2025-10-04
15,Newbury,21535,2223,310,2015-01-14,2026-05-16
16,Ayr,20921,2325,328,2015-01-02,2026-05-20
17,Longchamp (FR),20911,1941,235,2015-04-06,2025-10-05
18,Chepstow,20804,2318,326,2015-01-30,2026-05-21
19,Leopardstown (IRE),19839,1771,242,2015-01-18,2025-09-13
20,Ascot,19669,1837,284,2015-01-17,2026-05-09
21,Fairyhouse (IRE),19326,1660,224,2015-01-01,2025-10-11
22,Haydock,19065,2269,331,2015-01-17,2026-05-23
23,Punchestown (IRE),18872,1529,208,2015-01-10,2025-10-14
24,Naas (IRE),17920,1490,202,2015-01-04,2025-10-12
25,Navan (IRE),17799,1431,192,2015-01-24,2025-10-08
26,Cork (IRE),17738,1462,199,2015-01-03,2025-10-12
27,Windsor,17677,1935,274,2015-04-13,2026-05-25
28,Gowran Park (IRE),17448,1446,194,2015-01-22,2025-10-04
29,Catterick,17389,2010,287,2015-01-01,2026-05-21

In [4]:
# Inventory the parenthetical patterns used in raw course names.
#
# This cell extracts the complete trailing parenthetical portion of each
# distinct raw course value. Examples include:
# - no suffix;
# - (AW);
# - (IRE);
# - (AW) (IRE);
# - (FR).
#
# The output measures both:
# - how many distinct raw course values use each pattern;
# - how many runner rows and provisional races those values represent.
#
# This remains descriptive. No pattern is yet accepted as a jurisdiction
# or surface rule.

import re

course_suffix_inventory = course_inventory.copy()

def extract_parenthetical_pattern(course_name):
    """Return all parenthetical groups in their original order."""
    groups = re.findall(r"\([^()]+\)", str(course_name))
    return " ".join(groups) if groups else "[none]"

course_suffix_inventory["parenthetical_pattern"] = (
    course_suffix_inventory["course"].map(extract_parenthetical_pattern)
)

parenthetical_pattern_summary = (
    course_suffix_inventory
    .groupby("parenthetical_pattern", as_index=False)
    .agg(
        distinct_course_values=("course", "nunique"),
        runner_rows=("runner_rows", "sum"),
        provisional_races=("provisional_races", "sum"),
    )
    .sort_values(
        ["runner_rows", "distinct_course_values", "parenthetical_pattern"],
        ascending=[False, False, True],
    )
    .reset_index(drop=True)
)

print(
    "Distinct parenthetical patterns: "
    f"{len(parenthetical_pattern_summary):,}"
)

parenthetical_pattern_summary

Distinct parenthetical patterns: 44

,parenthetical_pattern,distinct_course_values,runner_rows,provisional_races
0,[none],189,749748,84895
1,(IRE),25,299546,25882
2,(AW),7,274133,29705
3,(FR),73,214637,19361
4,(HK),2,83068,6847
5,(USA),55,48156,5860
6,(AUS),50,42879,3767
7,(AW) (IRE),1,39075,3318
8,(UAE),5,25178,2219
9,(JPN),21,21202,1470
10,(July),1,11820,1438
11,(GER),17,6173,710
12,(SAF),9,5527,453
13,(ARG),3,4536,416
14,(CAN),4,3746,462
15,(BRZ),3,3113,273
16,(ITY),7,3027,372
17,(NZ),14,2903,236
18,(JER),1,2774,433
19,(CHI),3,2398,198
20,(BHR),2,1014,92
21,(PER),1,952,84
22,(URU),1,849,68
23,(QA),2,843,64
24,(SWE),3,803,92
25,(KSA),1,563,41
26,(TUR),2,374,52
27,(SWI),5,369,47
28,(Perth) (AUS),1,319,31
29,(NOR),1,306,37
30,(CZE),2,225,13
31,(KOR),2,220,17
32,(RH) (IRE),1,196,15
33,(SPA),2,145,14
34,(DEN),1,132,15
35,(CHN),1,90,10
36,(GUE),1,80,20
37,(BEL),3,44,4
38,(SIN),1,36,3
39,(HUN),1,30,3
40,(South Carolina) (USA),1,26,3
41,(POL),1,11,1
42,(Perth),1,10,1
43,(South Carolina),1,9,1

In [5]:
# Inspect raw course values whose parentheses may not represent jurisdiction alone.
#
# We include:
# - values containing more than one parenthetical group;
# - recognised surface or course-configuration markers;
# - geographic qualifiers that also appear without a jurisdiction suffix.
#
# This targeted inspection will help separate:
# - jurisdiction markers;
# - surface markers;
# - venue or track variants;
# - other geographic qualifiers.
#
# No canonical names or parsing rules are assigned yet.

patterns_for_inspection = {
    "(AW)",
    "(AW) (IRE)",
    "(July)",
    "(RH) (IRE)",
    "(Perth)",
    "(Perth) (AUS)",
    "(South Carolina)",
    "(South Carolina) (USA)",
}

special_parenthetical_courses = (
    course_suffix_inventory.loc[
        course_suffix_inventory["parenthetical_pattern"].isin(
            patterns_for_inspection
        ),
        [
            "course",
            "parenthetical_pattern",
            "runner_rows",
            "provisional_races",
            "active_dates",
            "first_date",
            "last_date",
        ],
    ]
    .sort_values(
        ["parenthetical_pattern", "runner_rows", "course"],
        ascending=[True, False, True],
    )
    .reset_index(drop=True)
)

special_parenthetical_courses

,course,parenthetical_pattern,runner_rows,provisional_races,active_dates,first_date,last_date
0,Wolverhampton (AW),(AW),64746,7042,930,2015-01-02,2026-05-18
1,Kempton (AW),(AW),50268,5046,662,2015-01-07,2026-05-27
2,Newcastle (AW),(AW),42092,4409,583,2016-05-17,2026-05-19
3,Lingfield (AW),(AW),41632,4803,742,2015-01-03,2026-05-12
4,Chelmsford (AW),(AW),37741,4310,593,2015-01-11,2026-03-26
5,Southwell (AW),(AW),34488,3816,515,2015-01-01,2026-05-21
6,Dundalk (AW),(AW),3166,279,37,2025-10-17,2026-05-26
7,Dundalk (AW) (IRE),(AW) (IRE),39075,3318,428,2015-01-02,2025-10-14
8,Newmarket (July),(July),11820,1438,208,2015-06-19,2025-08-23
9,Belmont Park (Perth),(Perth),10,1,1,2026-05-16,2026-05-16
10,Belmont Park (Perth) (AUS),(Perth) (AUS),319,31,31,2015-05-16,2024-06-15
11,Wexford (RH) (IRE),(RH) (IRE),196,15,2,2015-03-17,2015-04-10
12,Camden (South Carolina),(South Carolina),9,1,1,2025-11-23,2025-11-23
13,Camden (South Carolina) (USA),(South Carolina) (USA),26,3,3,2015-11-21,2024-11-17

In [6]:
# Identify apparent course variants after removing only a recognised terminal
# jurisdiction code.
#
# Examples:
# - "Dundalk (AW) (IRE)" becomes "Dundalk (AW)";
# - "Belmont Park (Perth) (AUS)" becomes "Belmont Park (Perth)";
# - "Newmarket (July)" remains unchanged because July is not jurisdiction;
# - "Wolverhampton (AW)" remains unchanged because AW is a surface marker.
#
# The derived comparison label is used only to locate possible variants.
# It does not replace or alter the raw course value.

recognised_terminal_jurisdiction_codes = {
    "ARG", "AUS", "BEL", "BHR", "BRZ", "CAN", "CHI", "CHN",
    "CZE", "DEN", "FR", "GER", "GUE", "HK", "HUN", "IRE",
    "ITY", "JER", "JPN", "KOR", "KSA", "NOR", "NZ", "PER",
    "POL", "QA", "SAF", "SIN", "SPA", "SWE", "SWI", "TUR",
    "UAE", "URU", "USA",
}

terminal_code_pattern = re.compile(r"\s+\(([^()]+)\)$")

def remove_recognised_terminal_jurisdiction(course_name):
    """Remove the final parenthetical group only when it is a known code."""
    raw_value = str(course_name)
    match = terminal_code_pattern.search(raw_value)

    if match and match.group(1) in recognised_terminal_jurisdiction_codes:
        return raw_value[:match.start()]

    return raw_value

course_variant_inventory = course_inventory.copy()
course_variant_inventory["comparison_course_label"] = (
    course_variant_inventory["course"].map(
        remove_recognised_terminal_jurisdiction
    )
)

variant_group_sizes = (
    course_variant_inventory
    .groupby("comparison_course_label")["course"]
    .nunique()
)

multi_value_comparison_labels = variant_group_sizes[
    variant_group_sizes > 1
].index

apparent_course_variants = (
    course_variant_inventory.loc[
        course_variant_inventory["comparison_course_label"].isin(
            multi_value_comparison_labels
        ),
        [
            "comparison_course_label",
            "course",
            "runner_rows",
            "provisional_races",
            "active_dates",
            "first_date",
            "last_date",
        ],
    ]
    .sort_values(
        ["comparison_course_label", "first_date", "course"]
    )
    .reset_index(drop=True)
)

print(
    "Comparison labels with multiple raw course values: "
    f"{len(multi_value_comparison_labels):,}"
)
print(
    "Raw course values inside those groups: "
    f"{len(apparent_course_variants):,}"
)

apparent_course_variants

Comparison labels with multiple raw course values: 136
Raw course values inside those groups: 272

,comparison_course_label,course,runner_rows,provisional_races,active_dates,first_date,last_date
0,Abu Dhabi,Abu Dhabi (UAE),2002,152,137,2015-01-04,2025-04-12
1,Abu Dhabi,Abu Dhabi,427,32,16,2025-10-25,2026-04-11
2,Aqueduct,Aqueduct (USA),2204,297,181,2015-01-01,2025-04-05
3,Aqueduct,Aqueduct,199,30,14,2025-10-18,2026-05-09
4,Ascot,Ascot (AUS),2407,204,140,2015-01-01,2025-05-10
...,...,...,...,...,...,...,...
267,Vichy,Vichy,9,1,1,2026-05-13,2026-05-13
268,Wexford,Wexford (IRE),8539,789,109,2015-04-21,2025-08-29
269,Wexford,Wexford,541,52,7,2025-10-26,2026-05-27
270,Woodbine,Woodbine (CAN),3519,434,283,2015-04-18,2025-10-11
271,Woodbine,Woodbine,73,9,6,2025-10-18,2026-05-02

In [7]:
# Test whether raw course variants sharing a comparison label coexist
# on the same racing date.
#
# A group such as:
# - Dundalk (AW) (IRE)
# - Dundalk (AW)
#
# may represent a source naming transition if the forms occur in separate
# periods.
#
# By contrast, same-date use of multiple raw values under one comparison
# label is strong evidence that removing the jurisdiction suffix creates
# a collision between distinct venues.
#
# This cell reports group-level evidence only. It does not yet classify
# or canonicalise any individual course.

variant_raw_values = apparent_course_variants["course"].tolist()

# Build placeholders safely rather than interpolating course names into SQL.
placeholders = ", ".join("?" for _ in variant_raw_values)

variant_dates_sql = f"""
SELECT DISTINCT
    date,
    course
FROM {SOURCE_TABLE}
WHERE {DATA_ROW_PREDICATE}
  AND course IN ({placeholders})
"""

variant_dates = pd.read_sql_query(
    variant_dates_sql,
    connection,
    params=variant_raw_values,
)

# Attach the provisional comparison label created in the previous cell.
course_to_comparison_label = dict(
    zip(
        course_variant_inventory["course"],
        course_variant_inventory["comparison_course_label"],
    )
)

variant_dates["comparison_course_label"] = (
    variant_dates["course"].map(course_to_comparison_label)
)

# Count how many different raw course values occur for each label and date.
label_date_counts = (
    variant_dates
    .groupby(
        ["comparison_course_label", "date"],
        as_index=False,
    )
    .agg(raw_course_values_on_date=("course", "nunique"))
)

same_date_collisions = (
    label_date_counts.loc[
        label_date_counts["raw_course_values_on_date"] > 1
    ]
    .groupby("comparison_course_label", as_index=False)
    .agg(
        dates_with_multiple_raw_values=("date", "nunique"),
        first_collision_date=("date", "min"),
        last_collision_date=("date", "max"),
        maximum_raw_values_on_one_date=(
            "raw_course_values_on_date",
            "max",
        ),
    )
)

variant_group_summary = (
    apparent_course_variants
    .groupby("comparison_course_label", as_index=False)
    .agg(
        distinct_raw_course_values=("course", "nunique"),
        combined_runner_rows=("runner_rows", "sum"),
        first_observed_date=("first_date", "min"),
        last_observed_date=("last_date", "max"),
    )
    .merge(
        same_date_collisions,
        on="comparison_course_label",
        how="left",
    )
)

variant_group_summary["dates_with_multiple_raw_values"] = (
    variant_group_summary["dates_with_multiple_raw_values"]
    .fillna(0)
    .astype(int)
)

variant_group_summary["has_same_date_collision"] = (
    variant_group_summary["dates_with_multiple_raw_values"] > 0
)

variant_group_summary = (
    variant_group_summary
    .sort_values(
        [
            "has_same_date_collision",
            "dates_with_multiple_raw_values",
            "combined_runner_rows",
            "comparison_course_label",
        ],
        ascending=[False, False, False, True],
    )
    .reset_index(drop=True)
)

print(
    "Comparison labels tested: "
    f"{len(variant_group_summary):,}"
)
print(
    "Labels with multiple raw forms on at least one same date: "
    f"{variant_group_summary['has_same_date_collision'].sum():,}"
)

variant_group_summary.head(30)

Comparison labels tested: 136
Labels with multiple raw forms on at least one same date: 3

,comparison_course_label,distinct_raw_course_values,combined_runner_rows,first_observed_date,last_observed_date,dates_with_multiple_raw_values,first_collision_date,last_collision_date,maximum_raw_values_on_one_date,has_same_date_collision
0,Ascot,2,22076,2015-01-01,2026-05-09,39,2015-10-31,2025-05-10,2.0,True
1,Sandown,2,14716,2015-01-03,2026-04-25,2,2019-07-24,2025-02-01,2.0,True
2,Newcastle,2,9320,2015-01-03,2026-04-11,2,2015-03-14,2015-04-11,2.0,True
3,Sha Tin,2,56963,2015-01-25,2026-05-24,0,NaN,NaN,NaN,False
4,Chantilly,2,52403,2015-01-23,2026-05-19,0,NaN,NaN,NaN,False
5,Deauville,2,52014,2015-01-03,2026-04-08,0,NaN,NaN,NaN,False
6,Dundalk (AW),2,42241,2015-01-02,2026-05-26,0,NaN,NaN,NaN,False
7,Auteuil,2,34928,2015-03-01,2026-05-26,0,NaN,NaN,NaN,False
8,Happy Valley,2,34012,2016-01-06,2026-05-27,0,NaN,NaN,NaN,False
9,Saint-Cloud,2,30288,2015-03-07,2026-05-22,0,NaN,NaN,NaN,False
10,Curragh,2,23025,2015-03-29,2026-05-24,0,NaN,NaN,NaN,False
11,Longchamp,2,22094,2015-04-06,2026-05-24,0,NaN,NaN,NaN,False
12,Leopardstown,2,21038,2015-01-18,2026-05-15,0,NaN,NaN,NaN,False
13,Fairyhouse,2,20523,2015-01-01,2026-04-06,0,NaN,NaN,NaN,False
14,Punchestown,2,20444,2015-01-10,2026-05-13,0,NaN,NaN,NaN,False
15,Naas,2,18863,2015-01-04,2026-05-17,0,NaN,NaN,NaN,False
16,Navan,2,18830,2015-01-24,2026-05-16,0,NaN,NaN,NaN,False
17,Cork,2,18827,2015-01-03,2026-05-19,0,NaN,NaN,NaN,False
18,Gowran Park,2,18277,2015-01-22,2026-05-20,0,NaN,NaN,NaN,False
19,Limerick,2,16422,2015-03-14,2026-05-21,0,NaN,NaN,NaN,False
20,Meydan,2,16403,2015-01-08,2026-03-28,0,NaN,NaN,NaN,False
21,Galway,2,13438,2015-07-27,2025-10-27,0,NaN,NaN,NaN,False
22,Clonmel,2,10719,2015-02-10,2026-05-14,0,NaN,NaN,NaN,False
23,Down Royal,2,10483,2015-02-11,2026-05-04,0,NaN,NaN,NaN,False
24,Killarney,2,10416,2015-05-10,2026-05-12,0,NaN,NaN,NaN,False
25,Compiegne,2,10268,2015-03-09,2026-05-13,0,NaN,NaN,NaN,False
26,Thurles,2,9804,2015-01-05,2026-03-05,0,NaN,NaN,NaN,False
27,Tramore,2,9402,2015-01-01,2026-04-20,0,NaN,NaN,NaN,False
28,Wexford,2,9080,2015-04-21,2026-05-27,0,NaN,NaN,NaN,False
29,Ballinrobe,2,8703,2015-05-25,2026-05-26,0,NaN,NaN,NaN,False

In [8]:
# Inspect the exact raw course values and collision dates for the three
# comparison labels that coexist on the same date.
#
# The same list of course values is used in two SQL IN clauses, so the
# parameter list must also be supplied twice.

colliding_labels = (
    variant_group_summary.loc[
        variant_group_summary["has_same_date_collision"],
        "comparison_course_label",
    ]
    .tolist()
)

collision_course_values = (
    apparent_course_variants.loc[
        apparent_course_variants["comparison_course_label"].isin(
            colliding_labels
        ),
        "course",
    ]
    .tolist()
)

course_placeholders = ", ".join("?" for _ in collision_course_values)

collision_detail_sql = f"""
WITH collision_dates AS (
    SELECT
        date,
        CASE
            WHEN course IN ('Ascot', 'Ascot (AUS)') THEN 'Ascot'
            WHEN course IN ('Sandown', 'Sandown (AUS)') THEN 'Sandown'
            WHEN course IN ('Newcastle', 'Newcastle (AUS)') THEN 'Newcastle'
        END AS comparison_course_label
    FROM {SOURCE_TABLE}
    WHERE {DATA_ROW_PREDICATE}
      AND course IN ({course_placeholders})
    GROUP BY
        date,
        course
),
confirmed_collision_dates AS (
    SELECT
        comparison_course_label,
        date
    FROM collision_dates
    GROUP BY
        comparison_course_label,
        date
    HAVING COUNT(*) > 1
)
SELECT
    CASE
        WHEN d.course IN ('Ascot', 'Ascot (AUS)') THEN 'Ascot'
        WHEN d.course IN ('Sandown', 'Sandown (AUS)') THEN 'Sandown'
        WHEN d.course IN ('Newcastle', 'Newcastle (AUS)') THEN 'Newcastle'
    END AS comparison_course_label,
    d.date,
    d.course,
    COUNT(*) AS runner_rows,
    COUNT(
        DISTINCT
        d.date || '|' || d.course || '|' || CAST(d.off AS TEXT)
    ) AS provisional_races
FROM {SOURCE_TABLE} AS d
JOIN confirmed_collision_dates AS c
    ON c.date = d.date
   AND c.comparison_course_label =
       CASE
           WHEN d.course IN ('Ascot', 'Ascot (AUS)') THEN 'Ascot'
           WHEN d.course IN ('Sandown', 'Sandown (AUS)') THEN 'Sandown'
           WHEN d.course IN ('Newcastle', 'Newcastle (AUS)') THEN 'Newcastle'
       END
WHERE {DATA_ROW_PREDICATE}
  AND d.course IN ({course_placeholders})
GROUP BY
    comparison_course_label,
    d.date,
    d.course
ORDER BY
    comparison_course_label,
    d.date,
    d.course
"""

collision_details = pd.read_sql_query(
    collision_detail_sql,
    connection,
    params=collision_course_values + collision_course_values,
)

print(f"Collision-detail rows: {len(collision_details):,}")
collision_details

Collision-detail rows: 86

,comparison_course_label,date,course,runner_rows,provisional_races
0,Ascot,2015-10-31,Ascot,81,7
1,Ascot,2015-10-31,Ascot (AUS),8,1
2,Ascot,2015-11-21,Ascot,53,7
3,Ascot,2015-11-21,Ascot (AUS),45,3
4,Ascot,2015-12-19,Ascot,73,6
...,...,...,...,...,...
81,Newcastle,2015-04-11,Newcastle (AUS),38,3
82,Sandown,2019-07-24,Sandown,50,6
83,Sandown,2019-07-24,Sandown (AUS),10,1
84,Sandown,2025-02-01,Sandown,51,7
85,Sandown,2025-02-01,Sandown (AUS),21,2

In [9]:
# Measure temporal handovers among comparison labels with no same-date collision.
#
# For each label, this cell identifies:
# - the earlier-ending raw course form;
# - the later-starting raw course form;
# - the last date of the earlier form;
# - the first date of the later form;
# - the calendar gap between those observations.
#
# A short positive gap across many labels would support a coordinated source
# naming change. It would not, by itself, prove that every pair is the same
# physical venue.

non_collision_variants = apparent_course_variants.loc[
    ~apparent_course_variants["comparison_course_label"].isin(
        variant_group_summary.loc[
            variant_group_summary["has_same_date_collision"],
            "comparison_course_label",
        ]
    )
].copy()

# Each current group contains two raw values. Sort them by their first
# observation so that the older and newer forms can be compared directly.
ordered_variants = (
    non_collision_variants
    .sort_values(
        ["comparison_course_label", "first_date", "last_date", "course"]
    )
    .reset_index(drop=True)
)

handover_rows = []

for comparison_label, group in ordered_variants.groupby(
    "comparison_course_label",
    sort=True,
):
    group = group.reset_index(drop=True)

    earlier = group.iloc[0]
    later = group.iloc[-1]

    earlier_last_date = pd.to_datetime(earlier["last_date"])
    later_first_date = pd.to_datetime(later["first_date"])

    handover_rows.append(
        {
            "comparison_course_label": comparison_label,
            "earlier_raw_course": earlier["course"],
            "earlier_last_date": earlier["last_date"],
            "later_raw_course": later["course"],
            "later_first_date": later["first_date"],
            "calendar_gap_days": (
                later_first_date - earlier_last_date
            ).days,
        }
    )

course_handover_summary = pd.DataFrame(handover_rows)

print(
    "Non-colliding comparison labels assessed: "
    f"{len(course_handover_summary):,}"
)
print()
print("Calendar-gap distribution:")
print(
    course_handover_summary["calendar_gap_days"]
    .value_counts()
    .sort_index()
    .to_string()
)

course_handover_summary.sort_values(
    ["later_first_date", "comparison_course_label"]
).head(40)

Non-colliding comparison labels assessed: 133

Calendar-gap distribution:
calendar_gap_days
1        1
3        1
4        1
5        1
6        3
7        6
10       1
12       1
13       1
14       3
16       1
18       1
19       1
21       3
23       1
24       1
26       2
28       7
29       1
32       1
33       1
35       1
40       1
41       1
42       1
45       1
47       1
51       1
53       1
58       1
59       2
69       2
70       2
81       1
84       1
90       1
98       2
118      1
126      1
133      1
146      1
154      1
170      1
175      1
185      1
189      4
191      1
196      3
202      1
204      1
210      1
215      1
216      1
217      1
219      1
226      1
230      1
231      1
235      1
238      1
239      1
245      1
252      2
253      1
258      2
280      1
287      1
292      1
299      1
308      1
315      2
329      1
350      1
357      3
364     16
365      2
371      2
447      1
685      1
700      1
728      1
731      1
1816     1
2653     1

,comparison_course_label,earlier_raw_course,earlier_last_date,later_raw_course,later_first_date,calendar_gap_days
14,Caulfield,Caulfield (AUS),2025-10-11,Caulfield,2025-10-15,4
53,Happy Valley,Happy Valley (HK),2025-10-08,Happy Valley,2025-10-15,7
91,Nantes,Nantes (FR),2025-04-09,Nantes,2025-10-15,189
101,Punchestown,Punchestown (IRE),2025-10-14,Punchestown,2025-10-15,1
25,Curragh,Curragh (IRE),2025-10-04,Curragh,2025-10-16,12
107,Saint-Cloud,Saint-Cloud (FR),2025-10-09,Saint-Cloud,2025-10-16,7
122,Thurles,Thurles (IRE),2025-10-09,Thurles,2025-10-16,7
3,Baden-Baden,Baden-Baden (GER),2025-09-07,Baden-Baden,2025-10-17,40
33,Dundalk (AW),Dundalk (AW) (IRE),2025-10-14,Dundalk (AW),2025-10-17,3
59,Keeneland,Keeneland (USA),2025-10-12,Keeneland,2025-10-17,5
1,Aqueduct,Aqueduct (USA),2025-04-05,Aqueduct,2025-10-18,196
2,Auteuil,Auteuil (FR),2025-10-12,Auteuil,2025-10-18,6
36,Ellerslie,Ellerslie (NZ),2025-09-06,Ellerslie,2025-10-18,42
39,Far Hills,Far Hills (USA),2024-10-19,Far Hills,2025-10-18,364
44,Gavea,Gavea (BRZ),2025-06-22,Gavea,2025-10-18,118
72,Leopardstown,Leopardstown (IRE),2025-09-13,Leopardstown,2025-10-18,35
74,Limerick,Limerick (IRE),2025-07-12,Limerick,2025-10-18,98
80,Marseille Borely,Marseille Borely (FR),2025-09-15,Marseille Borely,2025-10-18,33
102,Randwick,Randwick (AUS),2025-10-04,Randwick,2025-10-18,14
123,Tokyo,Tokyo (JPN),2025-10-12,Tokyo,2025-10-18,6
132,Woodbine,Woodbine (CAN),2025-10-11,Woodbine,2025-10-18,7
66,Kyoto,Kyoto (JPN),2025-10-13,Kyoto,2025-10-19,6
76,Longchamp,Longchamp (FR),2025-10-05,Longchamp,2025-10-19,14
110,San Siro,San Siro (ITY),2025-10-12,San Siro,2025-10-19,7
114,Sha Tin,Sha Tin (HK),2025-10-12,Sha Tin,2025-10-19,7
23,Compiegne,Compiegne (FR),2025-10-10,Compiegne,2025-10-20,10
26,Deauville,Deauville (FR),2025-08-30,Deauville,2025-10-20,51
48,Gowran Park,Gowran Park (IRE),2025-10-04,Gowran Park,2025-10-20,16
92,Navan,Navan (IRE),2025-10-08,Navan,2025-10-22,14
19,Clonmel,Clonmel (IRE),2025-10-02,Clonmel,2025-10-23,21
45,Geelong,Geelong (AUS),2024-10-23,Geelong,2025-10-23,365
86,Moonee Valley,Moonee Valley (AUS),2025-09-26,Moonee Valley,2025-10-24,28
116,Sligo,Sligo (IRE),2025-10-01,Sligo,2025-10-24,23
0,Abu Dhabi,Abu Dhabi (UAE),2025-04-12,Abu Dhabi,2025-10-25,196
9,Bordeaux Le Bouscat,Bordeaux Le Bouscat (FR),2025-09-29,Bordeaux Le Bouscat,2025-10-25,26
43,Galway,Galway (IRE),2025-10-07,Galway,2025-10-25,18
88,Munich,Munich (GER),2025-07-27,Munich,2025-10-25,90
111,Santa Anita,Santa Anita (USA),2025-10-06,Santa Anita,2025-10-25,19
13,Capannelle,Capannelle (ITY),2025-06-02,Capannelle,2025-10-26,146
17,Churchill Downs,Churchill Downs (USA),2025-09-27,Churchill Downs,2025-10-26,29

In [10]:
# Quantify when the later raw course forms first appear.
#
# This tests whether the apparent suffix-removal transitions are concentrated
# around one source-wide change date rather than scattered independently.
#
# We summarise:
# - the first-observation month of each later form;
# - how many later forms began from 15 October 2025 onward;
# - how many earlier forms ended before their later form began.
#
# This remains evidence about source representation, not final
# course canonicalisation.

course_handover_summary["later_first_date_parsed"] = pd.to_datetime(
    course_handover_summary["later_first_date"]
)
course_handover_summary["earlier_last_date_parsed"] = pd.to_datetime(
    course_handover_summary["earlier_last_date"]
)

course_handover_summary["later_first_month"] = (
    course_handover_summary["later_first_date_parsed"]
    .dt.to_period("M")
    .astype(str)
)

handover_month_summary = (
    course_handover_summary
    .groupby("later_first_month", as_index=False)
    .agg(
        comparison_labels=("comparison_course_label", "nunique"),
        earliest_new_form=("later_first_date", "min"),
        latest_new_form=("later_first_date", "max"),
    )
    .sort_values("later_first_month")
    .reset_index(drop=True)
)

change_window_start = pd.Timestamp("2025-10-15")

headline_handover_evidence = pd.DataFrame(
    {
        "measure": [
            "non-colliding comparison labels",
            "later forms first seen from 2025-10-15 onward",
            "later forms first seen during October 2025",
            "pairs with no temporal overlap",
            "pairs with a gap of 31 days or fewer",
        ],
        "value": [
            len(course_handover_summary),
            (
                course_handover_summary["later_first_date_parsed"]
                >= change_window_start
            ).sum(),
            (
                course_handover_summary["later_first_month"]
                == "2025-10"
            ).sum(),
            (
                course_handover_summary["calendar_gap_days"] > 0
            ).sum(),
            (
                course_handover_summary["calendar_gap_days"]
                .between(1, 31)
            ).sum(),
        ],
    }
)

display(headline_handover_evidence)
handover_month_summary

                                         measure  value
0                non-colliding comparison labels    133
1  later forms first seen from 2025-10-15 onward    133
2     later forms first seen during October 2025     47
3                 pairs with no temporal overlap    133
4           pairs with a gap of 31 days or fewer     37

  later_first_month  comparison_labels earliest_new_form latest_new_form
0           2025-10                 47        2025-10-15      2025-10-31
1           2025-11                 28        2025-11-01      2025-11-29
2           2025-12                 14        2025-12-06      2025-12-29
3           2026-01                  7        2026-01-05      2026-01-31
4           2026-02                 11        2026-02-01      2026-02-25
5           2026-03                  5        2026-03-08      2026-03-29
6           2026-04                  3        2026-04-11      2026-04-24
7           2026-05                 18        2026-05-02      2026-05-26

In [11]:
# Build provisional historical jurisdiction evidence for unsuffixed course forms.
#
# For each non-colliding comparison label, this cell:
# - identifies the terminal jurisdiction code from the earlier raw value;
# - links it to the later unsuffixed value;
# - measures how many later runner rows and races would inherit that evidence.
#
# This is not yet an accepted parsing rule. It tests the coverage and
# consistency of using historical course-name forms as a jurisdiction lookup.

def extract_terminal_jurisdiction_code(course_name):
    """Return a recognised terminal jurisdiction code, otherwise None."""
    match = terminal_code_pattern.search(str(course_name))

    if match and match.group(1) in recognised_terminal_jurisdiction_codes:
        return match.group(1)

    return None


historical_jurisdiction_links = course_handover_summary.copy()

historical_jurisdiction_links["historical_jurisdiction_code"] = (
    historical_jurisdiction_links["earlier_raw_course"].map(
        extract_terminal_jurisdiction_code
    )
)

# Attach frequencies for the later raw form.
later_form_frequencies = (
    course_inventory[
        [
            "course",
            "runner_rows",
            "provisional_races",
            "active_dates",
        ]
    ]
    .rename(
        columns={
            "course": "later_raw_course",
            "runner_rows": "later_runner_rows",
            "provisional_races": "later_provisional_races",
            "active_dates": "later_active_dates",
        }
    )
)

historical_jurisdiction_links = (
    historical_jurisdiction_links
    .merge(
        later_form_frequencies,
        on="later_raw_course",
        how="left",
    )
)

jurisdiction_link_summary = (
    historical_jurisdiction_links
    .groupby(
        "historical_jurisdiction_code",
        dropna=False,
        as_index=False,
    )
    .agg(
        comparison_labels=("comparison_course_label", "nunique"),
        later_raw_course_values=("later_raw_course", "nunique"),
        later_runner_rows=("later_runner_rows", "sum"),
        later_provisional_races=("later_provisional_races", "sum"),
    )
    .sort_values(
        ["later_runner_rows", "comparison_labels"],
        ascending=[False, False],
    )
    .reset_index(drop=True)
)

print(
    "Historical links assessed: "
    f"{len(historical_jurisdiction_links):,}"
)
print(
    "Links with a recognised historical jurisdiction code: "
    f"{historical_jurisdiction_links['historical_jurisdiction_code'].notna().sum():,}"
)
print(
    "Later runner rows covered by recognised historical codes: "
    f"{historical_jurisdiction_links.loc[
        historical_jurisdiction_links['historical_jurisdiction_code'].notna(),
        'later_runner_rows'
    ].sum():,}"
)

jurisdiction_link_summary

Historical links assessed: 133
Links with a recognised historical jurisdiction code: 133
Later runner rows covered by recognised historical codes: 50,678

,historical_jurisdiction_code,comparison_labels,later_raw_course_values,later_runner_rows,later_provisional_races
0,IRE,23,23,18133,1568
1,FR,19,19,13695,1172
2,HK,2,2,7907,634
3,UAE,4,4,2712,232
4,AUS,21,21,2677,237
5,USA,21,21,1963,242
6,JPN,9,9,1349,89
7,BHR,1,1,593,59
8,ARG,3,3,270,21
9,NZ,5,5,217,19
10,BRZ,2,2,201,16
11,SAF,3,3,200,17
12,GER,8,8,195,21
13,ITY,2,2,139,15
14,KSA,1,1,112,8
15,CHI,3,3,83,6
16,CAN,1,1,73,9
17,QA,1,1,53,6
18,PER,1,1,52,4
19,URU,1,1,24,2
20,SWI,1,1,20,2
21,JER,1,1,10,2

In [12]:
# Inventory raw course values with no parenthetical markers that are not
# covered by a safe historical jurisdiction link.
#
# This isolates the remaining unsuffixed population after excluding:
# - later forms linked to an earlier suffixed course;
# - raw values containing any parenthetical marker.
#
# The result will include established British courses, but may also contain:
# - international courses without historical suffix evidence;
# - ambiguous names shared across jurisdictions;
# - newly introduced source values.
#
# No default jurisdiction is assigned in this cell.

historically_linked_later_courses = set(
    historical_jurisdiction_links["later_raw_course"]
)

unsuffixed_course_inventory = course_inventory.loc[
    ~course_inventory["course"].str.contains(r"\([^()]+\)", regex=True)
].copy()

unlinked_unsuffixed_courses = (
    unsuffixed_course_inventory.loc[
        ~unsuffixed_course_inventory["course"].isin(
            historically_linked_later_courses
        )
    ]
    .sort_values(
        ["runner_rows", "course"],
        ascending=[False, True],
    )
    .reset_index(drop=True)
)

unlinked_unsuffixed_summary = pd.DataFrame(
    {
        "measure": [
            "all unsuffixed raw course values",
            "historically linked unsuffixed values",
            "remaining unlinked unsuffixed values",
            "runner rows in remaining values",
            "provisional races in remaining values",
        ],
        "value": [
            len(unsuffixed_course_inventory),
            len(
                unsuffixed_course_inventory.loc[
                    unsuffixed_course_inventory["course"].isin(
                        historically_linked_later_courses
                    )
                ]
            ),
            len(unlinked_unsuffixed_courses),
            unlinked_unsuffixed_courses["runner_rows"].sum(),
            unlinked_unsuffixed_courses["provisional_races"].sum(),
        ],
    }
)

display(unlinked_unsuffixed_summary)
unlinked_unsuffixed_courses.head(50)

                                 measure   value
0       all unsuffixed raw course values     189
1  historically linked unsuffixed values     130
2   remaining unlinked unsuffixed values      59
3        runner rows in remaining values  702255
4  provisional races in remaining values   80795

,course,runner_rows,provisional_races,active_dates,first_date,last_date
0,Doncaster,26166,2805,389,2015-01-09,2026-05-16
1,Newbury,21535,2223,310,2015-01-14,2026-05-16
2,Ayr,20921,2325,328,2015-01-02,2026-05-20
3,Chepstow,20804,2318,326,2015-01-30,2026-05-21
4,Ascot,19669,1837,284,2015-01-17,2026-05-09
5,Haydock,19065,2269,331,2015-01-17,2026-05-23
6,Windsor,17677,1935,274,2015-04-13,2026-05-25
7,Catterick,17389,2010,287,2015-01-01,2026-05-21
8,Musselburgh,16365,2007,290,2015-01-01,2026-05-21
9,Uttoxeter,16185,1833,256,2015-01-24,2026-05-24
10,Leicester,16172,1989,293,2015-01-08,2026-05-26
11,York,16170,1338,193,2015-05-13,2026-05-23
12,Carlisle,15282,1775,250,2015-02-16,2026-05-18
13,Newmarket,14772,1503,205,2015-04-15,2026-05-16
14,Nottingham,14711,1642,230,2015-04-08,2026-05-19
15,Cheltenham,14146,1210,175,2015-01-01,2026-03-13
16,Redcar,14053,1377,182,2015-04-06,2026-05-26
17,Sandown,14053,1687,252,2015-01-03,2026-04-25
18,Yarmouth,13521,1628,230,2015-08-30,2026-05-20
19,Bath,13091,1540,216,2015-04-17,2026-05-26
20,Beverley,13046,1444,199,2015-04-15,2026-05-27
21,Goodwood,12687,1371,199,2015-05-02,2026-05-23
22,Thirsk,12675,1224,165,2015-04-18,2026-05-16
23,Ffos Las,12313,1576,232,2015-01-02,2026-05-20
24,Worcester,12104,1399,194,2015-05-07,2026-05-22
25,Market Rasen,12029,1545,224,2015-01-15,2026-05-08
26,Lingfield,11706,1457,248,2015-01-05,2026-05-26
27,Fontwell,11426,1579,232,2015-02-12,2026-05-24
28,Brighton,11265,1484,214,2015-04-21,2025-10-16
29,Southwell,11224,1372,198,2015-02-22,2026-05-11
30,Warwick,11205,1304,187,2015-01-10,2026-05-20
31,Wetherby,11032,1296,187,2015-01-10,2026-04-26
32,Huntingdon,10958,1316,192,2015-01-09,2026-05-25
33,Hamilton,10433,1308,187,2015-05-03,2026-05-27
34,Exeter,10285,1169,170,2015-01-01,2026-04-17
35,Ripon,9978,1192,176,2015-04-16,2026-05-17
36,Pontefract,9880,1169,166,2015-04-07,2026-05-22
37,Stratford,9759,1211,176,2015-03-09,2026-05-17
38,Sedgefield,9666,1281,190,2015-01-06,2026-04-10
39,Salisbury,9609,1140,161,2015-05-03,2026-05-23
40,Hexham,9459,1098,159,2015-03-12,2026-05-19
41,Chester,9305,1086,156,2015-05-06,2026-05-08
42,Wincanton,9276,1103,159,2015-01-03,2026-04-12
43,Ludlow,9244,1137,167,2015-01-07,2026-05-10
44,Newton Abbot,9213,1213,179,2015-03-25,2026-05-27
45,Taunton,9191,987,145,2015-01-07,2026-04-22
46,Plumpton,8586,1165,175,2015-01-04,2026-05-26
47,Perth,8562,1095,155,2015-04-22,2026-05-14
48,Kelso,8511,1064,152,2015-01-11,2026-05-24
49,Newcastle,8458,1010,146,2015-01-03,2026-04-11

In [13]:
# Display the complete inventory of unsuffixed course values that have no
# safe historical jurisdiction link.
#
# The earlier output showed only the first 50 of 59 values. This cell exposes
# the entire remaining population so that low-frequency exceptions are not
# hidden by the dominant British-course values.
#
# This is still observation only. No jurisdiction is assigned.

pd.set_option("display.max_rows", None)

unlinked_unsuffixed_courses[
    [
        "course",
        "runner_rows",
        "provisional_races",
        "active_dates",
        "first_date",
        "last_date",
    ]
]

,course,runner_rows,provisional_races,active_dates,first_date,last_date
0,Doncaster,26166,2805,389,2015-01-09,2026-05-16
1,Newbury,21535,2223,310,2015-01-14,2026-05-16
2,Ayr,20921,2325,328,2015-01-02,2026-05-20
3,Chepstow,20804,2318,326,2015-01-30,2026-05-21
4,Ascot,19669,1837,284,2015-01-17,2026-05-09
5,Haydock,19065,2269,331,2015-01-17,2026-05-23
6,Windsor,17677,1935,274,2015-04-13,2026-05-25
7,Catterick,17389,2010,287,2015-01-01,2026-05-21
8,Musselburgh,16365,2007,290,2015-01-01,2026-05-21
9,Uttoxeter,16185,1833,256,2015-01-24,2026-05-24
10,Leicester,16172,1989,293,2015-01-08,2026-05-26
11,York,16170,1338,193,2015-05-13,2026-05-23
12,Carlisle,15282,1775,250,2015-02-16,2026-05-18
13,Newmarket,14772,1503,205,2015-04-15,2026-05-16
14,Nottingham,14711,1642,230,2015-04-08,2026-05-19
15,Cheltenham,14146,1210,175,2015-01-01,2026-03-13
16,Redcar,14053,1377,182,2015-04-06,2026-05-26
17,Sandown,14053,1687,252,2015-01-03,2026-04-25
18,Yarmouth,13521,1628,230,2015-08-30,2026-05-20
19,Bath,13091,1540,216,2015-04-17,2026-05-26
20,Beverley,13046,1444,199,2015-04-15,2026-05-27
21,Goodwood,12687,1371,199,2015-05-02,2026-05-23
22,Thirsk,12675,1224,165,2015-04-18,2026-05-16
23,Ffos Las,12313,1576,232,2015-01-02,2026-05-20
24,Worcester,12104,1399,194,2015-05-07,2026-05-22
25,Market Rasen,12029,1545,224,2015-01-15,2026-05-08
26,Lingfield,11706,1457,248,2015-01-05,2026-05-26
27,Fontwell,11426,1579,232,2015-02-12,2026-05-24
28,Brighton,11265,1484,214,2015-04-21,2025-10-16
29,Southwell,11224,1372,198,2015-02-22,2026-05-11
30,Warwick,11205,1304,187,2015-01-10,2026-05-20
31,Wetherby,11032,1296,187,2015-01-10,2026-04-26
32,Huntingdon,10958,1316,192,2015-01-09,2026-05-25
33,Hamilton,10433,1308,187,2015-05-03,2026-05-27
34,Exeter,10285,1169,170,2015-01-01,2026-04-17
35,Ripon,9978,1192,176,2015-04-16,2026-05-17
36,Pontefract,9880,1169,166,2015-04-07,2026-05-22
37,Stratford,9759,1211,176,2015-03-09,2026-05-17
38,Sedgefield,9666,1281,190,2015-01-06,2026-04-10
39,Salisbury,9609,1140,161,2015-05-03,2026-05-23
40,Hexham,9459,1098,159,2015-03-12,2026-05-19
41,Chester,9305,1086,156,2015-05-06,2026-05-08
42,Wincanton,9276,1103,159,2015-01-03,2026-04-12
43,Ludlow,9244,1137,167,2015-01-07,2026-05-10
44,Newton Abbot,9213,1213,179,2015-03-25,2026-05-27
45,Taunton,9191,987,145,2015-01-07,2026-04-22
46,Plumpton,8586,1165,175,2015-01-04,2026-05-26
47,Perth,8562,1095,155,2015-04-22,2026-05-14
48,Kelso,8511,1064,152,2015-01-11,2026-05-24
49,Newcastle,8458,1010,146,2015-01-03,2026-04-11
50,Bangor-on-Dee,7962,985,145,2015-01-06,2026-05-23
51,Kempton,7284,902,132,2015-01-10,2026-03-23
52,Hereford,7158,838,122,2016-10-06,2026-05-12
53,Aintree,6616,610,87,2015-04-09,2026-05-15
54,Epsom,5991,717,111,2015-04-22,2026-04-28
55,Cartmel,5227,639,92,2015-05-25,2026-05-27
56,Fakenham,5118,798,126,2015-01-01,2026-05-04
57,Towcester,2063,259,39,2015-01-29,2018-05-21
58,Firenze,4,1,1,2026-04-25,2026-04-25

In [14]:
# Inspect the isolated unsuffixed Firenze course value.
#
# Firenze is the only value outside the established British-course population
# among the 59 unsuffixed courses without a historical jurisdiction link.
#
# This cell preserves the source values and displays the complete runner-level
# race context needed to assess whether jurisdiction or surface evidence appears
# elsewhere in the record.

firenze_rows_sql = f"""
SELECT
    rowid AS source_rowid,
    date,
    race_id,
    course,
    off,
    race_name,
    type,
    horse,
    pos,
    draw,
    ran,
    time,
    comment
FROM {SOURCE_TABLE}
WHERE {DATA_ROW_PREDICATE}
  AND course = 'Firenze'
ORDER BY
    date,
    off,
    source_rowid
"""

firenze_rows = pd.read_sql_query(firenze_rows_sql, connection)

print(f"Firenze runner rows: {len(firenze_rows):,}")
print(
    "Firenze provisional races: "
    f"{firenze_rows[['date', 'course', 'off']].drop_duplicates().shape[0]:,}"
)

firenze_rows

Firenze runner rows: 4
Firenze provisional races: 1

,source_rowid,date,race_id,course,off,race_name,type,horse,pos,draw,ran,time,comment
0,1833828,2026-04-25,919235,Firenze,16:15,Premio Natale di Roma (Turf),Flat,Kabir (IRE),1,1,4,1:30.10,
1,1833829,2026-04-25,919235,Firenze,16:15,Premio Natale di Roma (Turf),Flat,Lost President (IRE),2,7,4,1:30.27,
2,1833830,2026-04-25,919235,Firenze,16:15,Premio Natale di Roma (Turf),Flat,Heldtoransom (IRE),3,4,4,1:30.31,
3,1833831,2026-04-25,919235,Firenze,16:15,Premio Natale di Roma (Turf),Flat,Elegant Power (GB),4,3,4,1:30.68,

In [15]:
# Establish the source-wide inventory of race type values.
#
# Surface may be represented partly through the `type` field, but `type`
# may instead describe the broad racing code or discipline.
#
# For each exact raw type value, this cell measures:
# - runner rows;
# - provisional races using date + course + off;
# - distinct raw course values;
# - first and last observed dates.
#
# No type value is yet interpreted as a surface category.

type_inventory_sql = f"""
WITH provisional_race_types AS (
    SELECT
        date,
        course,
        off,
        type
    FROM {SOURCE_TABLE}
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY
        date,
        course,
        off,
        type
),
race_type_counts AS (
    SELECT
        type,
        COUNT(*) AS provisional_races
    FROM provisional_race_types
    GROUP BY type
),
runner_type_counts AS (
    SELECT
        type,
        COUNT(*) AS runner_rows,
        COUNT(DISTINCT course) AS distinct_raw_course_values,
        MIN(date) AS first_date,
        MAX(date) AS last_date
    FROM {SOURCE_TABLE}
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY type
)
SELECT
    runners.type,
    runners.runner_rows,
    races.provisional_races,
    runners.distinct_raw_course_values,
    runners.first_date,
    runners.last_date
FROM runner_type_counts AS runners
JOIN race_type_counts AS races
    ON races.type = runners.type
ORDER BY
    runners.runner_rows DESC,
    runners.type
"""

type_inventory = pd.read_sql_query(type_inventory_sql, connection)

print(f"Distinct raw type values: {len(type_inventory):,}")
type_inventory

Distinct raw type values: 4

,type,runner_rows,provisional_races,distinct_raw_course_values,first_date,last_date
0,Flat,1268229,126391,475,2015-01-01,2026-05-27
1,Hurdle,358441,35462,144,2015-01-01,2026-05-27
2,Chase,179645,22547,124,2015-01-01,2026-05-27
3,NH Flat,44970,4643,92,2015-01-01,2026-05-27

In [16]:
# Inventory parenthetical markers found in race names.
#
# Surface information may appear explicitly in race_name, as observed in:
# "Premio Natale di Roma (Turf)"
#
# This cell works at provisional race grain using:
# date + course + off
#
# For each provisional race, it:
# - preserves the exact raw race_name;
# - extracts every parenthetical group;
# - counts the resulting exact marker patterns.
#
# The output is descriptive only. Parenthetical text may represent surface,
# age, sex, grade, eligibility, sponsorship, or other race conditions.

race_name_inventory_sql = f"""
SELECT
    date,
    course,
    off,
    race_name,
    type
FROM {SOURCE_TABLE}
WHERE {DATA_ROW_PREDICATE}
GROUP BY
    date,
    course,
    off,
    race_name,
    type
"""

provisional_race_names = pd.read_sql_query(
    race_name_inventory_sql,
    connection,
)

def extract_race_name_parenthetical_pattern(race_name):
    """Return all parenthetical groups in their original order."""
    groups = re.findall(r"\([^()]+\)", str(race_name))
    return " ".join(groups) if groups else "[none]"

provisional_race_names["parenthetical_pattern"] = (
    provisional_race_names["race_name"].map(
        extract_race_name_parenthetical_pattern
    )
)

race_name_parenthetical_summary = (
    provisional_race_names
    .groupby("parenthetical_pattern", as_index=False)
    .agg(
        provisional_races=("race_name", "size"),
        distinct_race_names=("race_name", "nunique"),
        distinct_raw_courses=("course", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
    .sort_values(
        ["provisional_races", "distinct_race_names", "parenthetical_pattern"],
        ascending=[False, False, True],
    )
    .reset_index(drop=True)
)

print(
    "Provisional races inspected: "
    f"{len(provisional_race_names):,}"
)
print(
    "Distinct race-name parenthetical patterns: "
    f"{len(race_name_parenthetical_summary):,}"
)

race_name_parenthetical_summary.head(50)

Provisional races inspected: 189,043
Distinct race-name parenthetical patterns: 6,593

,parenthetical_pattern,provisional_races,distinct_race_names,distinct_raw_courses,first_date,last_date
0,[none],97445,50719,157,2015-01-01,2026-05-27
1,(GBB Race),10574,7342,64,2020-08-04,2026-05-27
2,(Div I),4197,2816,103,2015-01-16,2026-05-27
3,(Div II),4193,2817,103,2015-01-16,2026-05-27
4,(Plus 10 Race),3395,1893,60,2015-03-28,2021-09-02
5,(3yo+) (Turf),3170,1630,163,2015-01-01,2026-01-10
6,(3yo) (Turf),1413,693,117,2015-01-02,2026-01-18
7,(3yo+) (Course A) (Turf),1221,645,4,2017-02-02,2026-01-18
8,(3yo Fillies) (Turf),1134,451,90,2015-01-15,2025-12-26
9,(3yo+) (Course C) (Turf),959,623,4,2017-02-05,2026-03-08
10,(Turf),940,821,155,2015-01-03,2026-05-26
11,(3yo+) (Dirt),940,491,63,2015-01-06,2026-01-21
12,(3yo+ Fillies & Mares) (Turf),928,428,94,2015-01-03,2026-01-10
13,(4yo+) (Turf),926,354,75,2015-01-14,2026-01-18
14,(3yo+) (Course C+3) (Turf),916,659,4,2017-01-14,2026-01-11
15,(Handicap) (Dirt),856,464,7,2015-01-08,2026-03-15
16,(Handicap) (4yo+) (All-Weather Track) (Polytrack),853,414,4,2018-08-28,2026-01-08
17,(2yo) (Turf),780,323,97,2015-02-28,2026-01-01
18,(3yo+) (Course B) (Turf),765,523,3,2017-01-11,2026-01-14
19,(Handicap) (4yo+) (Turf),651,379,18,2015-03-07,2025-11-20
20,(Pro/Am),642,417,38,2015-01-01,2026-05-15
21,(Tapeta),601,293,4,2015-01-02,2026-03-21
22,(Handicap) (Turf),569,493,29,2015-01-04,2026-05-24
23,(2yo+) (Turf),547,341,53,2015-02-21,2026-01-03
24,(Dirt),540,410,67,2015-01-02,2026-05-26
25,(4yo+ Fillies & Mares) (Turf),537,214,47,2015-01-10,2026-05-14
26,(Handicap),508,325,42,2015-01-01,2025-08-09
27,(Category 1 Elimination) (GBB Race),501,363,40,2021-05-05,2026-05-26
28,(IRE Incentive Race),498,101,43,2021-03-26,2026-05-24
29,(Fillies & Mares),491,227,40,2015-01-01,2026-05-24
30,(Handicap) (3yo) (Turf),481,233,13,2015-03-27,2025-11-14
31,(GBBPlus Race),465,367,38,2025-01-24,2026-05-27
32,(Handicap) (3yo) (All-Weather Track) (Polytrack),420,215,4,2018-09-21,2026-01-09
33,(A Novices Limited Handicap),418,335,38,2015-10-04,2021-04-10
34,(GBB Race) (Div I),400,345,49,2020-08-24,2026-05-27
35,(GBB Race) (Div II),395,342,48,2020-08-24,2026-05-27
36,(Fillies),383,159,36,2015-01-01,2026-05-24
37,(3yo) (Dirt),360,140,39,2015-01-11,2025-12-06
38,(3yo+) (Main Track) (Dirt),350,123,26,2018-08-26,2025-12-28
39,(Premier Handicap),346,152,14,2015-03-29,2026-05-23
40,(3yo+) (Course B+2) (Turf),342,251,2,2017-04-02,2026-02-01
41,(C & G),341,198,35,2015-03-14,2026-05-23
42,(Conditions) (3yo) (Turf),335,171,26,2015-03-07,2025-10-16
43,(3yo+) (Course A+3) (Turf),310,251,2,2017-03-26,2025-12-27
44,(2yo Fillies) (Turf),309,146,52,2015-02-28,2025-12-14
45,(Q.R.),297,172,34,2015-01-09,2026-05-12
46,(Handicap) (3yo+) (All-Weather Track) (Polytrack),291,122,4,2018-11-27,2025-12-22
47,(Conditions) (4yo+) (Turf),283,148,27,2015-03-08,2025-10-18
48,(Heritage Handicap),281,128,16,2015-03-28,2026-05-09
49,(3yo) (Main Track) (Dirt),278,99,21,2018-08-25,2025-12-28

In [17]:
# Measure explicit surface terminology in race names.
#
# A race name may contain several parenthetical conditions, so this cell
# searches independently for each observed surface-related term.
#
# Counts are measured at provisional race grain:
# date + course + off
#
# Categories are deliberately kept as raw evidence:
# - Turf
# - Dirt
# - Tapeta
# - Polytrack
# - All-Weather Track
# - Main Track
#
# These terms may overlap within one race name. For example,
# "All-Weather Track" and "Polytrack" can occur together.
# No single canonical surface category is assigned yet.

surface_terms = {
    "Turf": r"\(Turf\)",
    "Dirt": r"\(Dirt\)",
    "Tapeta": r"\(Tapeta\)",
    "Polytrack": r"\(Polytrack\)",
    "All-Weather Track": r"\(All-Weather Track\)",
    "Main Track": r"\(Main Track\)",
}

surface_term_rows = []

for surface_term, pattern in surface_terms.items():
    matched_races = provisional_race_names.loc[
        provisional_race_names["race_name"].str.contains(
            pattern,
            regex=True,
            na=False,
        )
    ]

    surface_term_rows.append(
        {
            "surface_term": surface_term,
            "provisional_races": len(matched_races),
            "distinct_race_names": matched_races["race_name"].nunique(),
            "distinct_raw_courses": matched_races["course"].nunique(),
            "first_date": matched_races["date"].min(),
            "last_date": matched_races["date"].max(),
        }
    )

surface_term_summary = (
    pd.DataFrame(surface_term_rows)
    .sort_values(
        ["provisional_races", "surface_term"],
        ascending=[False, True],
    )
    .reset_index(drop=True)
)

# Also measure how many provisional races contain at least one of the
# recognised explicit surface terms.
combined_surface_pattern = "|".join(surface_terms.values())

races_with_explicit_surface_term = provisional_race_names.loc[
    provisional_race_names["race_name"].str.contains(
        combined_surface_pattern,
        regex=True,
        na=False,
    )
].copy()

print(
    "Provisional races with at least one recognised explicit "
    f"surface term: {len(races_with_explicit_surface_term):,}"
)
print(
    "Share of all provisional races: "
    f"{len(races_with_explicit_surface_term) / len(provisional_race_names):.2%}"
)

surface_term_summary

Provisional races with at least one recognised explicit surface term: 46,573
Share of all provisional races: 24.64%

,surface_term,provisional_races,distinct_race_names,distinct_raw_courses,first_date,last_date
0,Turf,32637,18501,344,2015-01-01,2026-05-27
1,Dirt,6869,3508,119,2015-01-01,2026-05-26
2,Polytrack,6025,3487,16,2015-01-03,2026-05-19
3,All-Weather Track,4029,1977,12,2018-08-26,2026-02-08
4,Main Track,1921,664,37,2018-08-25,2025-12-28
5,Tapeta,1012,514,8,2015-01-02,2026-05-02

In [18]:
# Test overlap and contradiction between course-based all-weather evidence
# and explicit surface terms found in race_name.
#
# Course-based evidence:
# - raw course contains "(AW)"
#
# Race-name evidence:
# - Turf
# - Dirt
# - Tapeta
# - Polytrack
# - All-Weather Track
# - Main Track
#
# The purpose is to identify:
# - confirming combinations;
# - missing race-name surface evidence;
# - potentially contradictory combinations.
#
# No final surface hierarchy is assigned yet.

surface_evidence = provisional_race_names.copy()

surface_evidence["course_marks_aw"] = (
    surface_evidence["course"].str.contains(
        r"\(AW\)",
        regex=True,
        na=False,
    )
)

for surface_term, pattern in surface_terms.items():
    column_name = (
        "race_name_marks_"
        + surface_term.lower().replace("-", "_").replace(" ", "_")
    )

    surface_evidence[column_name] = (
        surface_evidence["race_name"].str.contains(
            pattern,
            regex=True,
            na=False,
        )
    )

surface_columns = [
    column
    for column in surface_evidence.columns
    if column.startswith("race_name_marks_")
]

surface_evidence["race_name_has_explicit_surface"] = (
    surface_evidence[surface_columns].any(axis=1)
)

surface_evidence["explicit_surface_terms"] = (
    surface_evidence[surface_columns]
    .apply(
        lambda row: ", ".join(
            column.replace("race_name_marks_", "")
            for column, present in row.items()
            if present
        )
        if row.any()
        else "[none]",
        axis=1,
    )
)

course_aw_overlap_summary = (
    surface_evidence
    .groupby(
        [
            "course_marks_aw",
            "race_name_has_explicit_surface",
            "explicit_surface_terms",
        ],
        as_index=False,
    )
    .agg(
        provisional_races=("race_name", "size"),
        distinct_raw_courses=("course", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
    .sort_values(
        ["course_marks_aw", "provisional_races"],
        ascending=[False, False],
    )
    .reset_index(drop=True)
)

print(
    "Provisional races at courses marked (AW): "
    f"{surface_evidence['course_marks_aw'].sum():,}"
)
print(
    "Of those, races with an explicit race-name surface term: "
    f"{surface_evidence.loc[
        surface_evidence['course_marks_aw'],
        'race_name_has_explicit_surface'
    ].sum():,}"
)

course_aw_overlap_summary

Provisional races at courses marked (AW): 33,023
Of those, races with an explicit race-name surface term: 715

,course_marks_aw,race_name_has_explicit_surface,explicit_surface_terms,provisional_races,distinct_raw_courses,first_date,last_date
0,True,False,[none],32308,8,2015-01-01,2026-05-27
1,True,True,tapeta,714,1,2015-01-02,2015-12-30
2,True,True,polytrack,1,1,2015-01-05,2015-01-05
3,False,False,[none],110162,202,2015-01-01,2026-05-27
4,False,True,turf,32637,344,2015-01-01,2026-05-27
5,False,True,dirt,4955,112,2015-01-01,2026-05-26
6,False,True,"polytrack, all_weather_track",3788,6,2018-08-28,2026-01-23
7,False,True,polytrack,2236,15,2015-01-03,2026-05-19
8,False,True,"dirt, main_track",1911,37,2018-08-25,2025-12-28
9,False,True,"tapeta, all_weather_track",218,6,2018-08-26,2025-12-06
10,False,True,tapeta,80,5,2015-01-17,2026-05-02
11,False,True,all_weather_track,20,4,2019-08-20,2025-10-11
12,False,True,main_track,10,4,2019-05-03,2025-09-29
13,False,True,"dirt, all_weather_track",3,1,2026-02-08,2026-02-08

In [19]:
# Identify which raw courses produce each explicit surface combination.
#
# This cell helps distinguish:
# - stable course-level conventions;
# - isolated anomalies;
# - surface terminology that changes by venue or period.
#
# It also exposes the three races labelled both Dirt and
# All-Weather Track, which may reflect a legitimate synthetic dirt track
# description rather than contradictory data.

surface_course_detail = (
    surface_evidence.loc[
        surface_evidence["race_name_has_explicit_surface"]
        | surface_evidence["course_marks_aw"]
    ]
    .groupby(
        [
            "course",
            "course_marks_aw",
            "explicit_surface_terms",
        ],
        as_index=False,
    )
    .agg(
        provisional_races=("race_name", "size"),
        distinct_race_names=("race_name", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
    .sort_values(
        [
            "course_marks_aw",
            "explicit_surface_terms",
            "provisional_races",
            "course",
        ],
        ascending=[False, True, False, True],
    )
    .reset_index(drop=True)
)

print(
    "Course and surface-evidence combinations: "
    f"{len(surface_course_detail):,}"
)

surface_course_detail

Course and surface-evidence combinations: 544

,course,course_marks_aw,explicit_surface_terms,provisional_races,distinct_race_names,first_date,last_date
0,Wolverhampton (AW),True,[none],6328,2850,2015-11-10,2026-05-18
1,Kempton (AW),True,[none],5046,2159,2015-01-07,2026-05-27
2,Lingfield (AW),True,[none],4802,2230,2015-01-03,2026-05-12
3,Newcastle (AW),True,[none],4409,2301,2016-05-17,2026-05-19
4,Chelmsford (AW),True,[none],4310,2327,2015-01-11,2026-03-26
5,Southwell (AW),True,[none],3816,1660,2015-01-01,2026-05-21
6,Dundalk (AW) (IRE),True,[none],3318,1416,2015-01-02,2025-10-14
7,Dundalk (AW),True,[none],279,176,2025-10-17,2026-05-26
8,Lingfield (AW),True,polytrack,1,1,2015-01-05,2015-01-05
9,Wolverhampton (AW),True,tapeta,714,385,2015-01-02,2015-12-30
10,Deauville (FR),False,all_weather_track,12,12,2019-08-20,2025-08-12
11,Chantilly (FR),False,all_weather_track,4,4,2023-01-21,2025-02-14
12,Woodbine (CAN),False,all_weather_track,3,3,2024-05-04,2025-10-11
13,Turfway Park (USA),False,all_weather_track,1,1,2024-12-15,2024-12-15
14,Meydan (UAE),False,dirt,792,595,2015-01-08,2025-04-05
15,Sha Tin (HK),False,dirt,746,569,2016-11-27,2025-10-12
16,Jebel Ali (UAE),False,dirt,606,333,2015-01-09,2025-03-16
17,Santa Anita (USA),False,dirt,184,94,2015-01-03,2024-09-30
18,Will Rogers Downs (USA),False,dirt,178,35,2020-03-23,2020-05-20
19,Palermo (ARG),False,dirt,176,60,2015-01-24,2025-10-11
20,Gulfstream Park (USA),False,dirt,149,85,2015-01-03,2025-01-25
21,Aqueduct (USA),False,dirt,119,71,2015-01-01,2025-01-25
22,Belmont Park (USA),False,dirt,113,50,2015-04-29,2018-09-22
23,Churchill Downs (USA),False,dirt,100,49,2015-04-26,2022-05-07
24,Hipodromo Chile (CHI),False,dirt,93,34,2015-05-02,2025-10-04
25,Saratoga (USA),False,dirt,93,47,2015-07-24,2024-08-29
26,Al Ain (UAE),False,dirt,83,48,2015-01-10,2024-04-05
27,Keeneland (USA),False,dirt,82,44,2015-04-03,2022-11-04
28,Meydan,False,dirt,69,68,2025-11-07,2026-03-28
29,Maronas (URU),False,dirt,68,31,2015-01-06,2025-01-06
30,Del Mar (USA),False,dirt,67,33,2015-07-25,2025-08-03
31,Jebel Ali,False,dirt,64,63,2025-11-01,2026-03-15
32,Monterrico (PER),False,dirt,63,31,2015-01-11,2025-09-14
33,Oaklawn Park (USA),False,dirt,62,32,2015-01-15,2025-03-29
34,Sharjah (UAE),False,dirt,57,45,2015-03-14,2025-01-12
35,Sha Tin,False,dirt,51,51,2025-10-30,2026-05-06
36,Tokyo (JPN),False,dirt,41,8,2015-02-01,2025-02-23
37,La Plata (ARG),False,dirt,37,15,2015-01-18,2025-09-21
38,Fair Grounds (USA),False,dirt,36,25,2015-01-17,2025-01-18
39,Chukyo (JPN),False,dirt,33,12,2015-01-25,2025-07-27
40,Monmouth Park (USA),False,dirt,33,15,2015-06-21,2018-08-18
41,Ohi (JPN),False,dirt,33,18,2015-01-21,2025-10-09
42,Tampa Bay Downs (USA),False,dirt,33,16,2015-01-16,2018-03-10
43,Laurel Park (USA),False,dirt,30,25,2015-01-01,2025-02-22
44,Pimlico (USA),False,dirt,26,13,2015-04-18,2018-05-19
45,Charles town (USA),False,dirt,24,8,2015-04-18,2025-08-23
46,Hastings Racecourse (CAN),False,dirt,23,8,2015-09-14,2025-09-14
47,Nakayama (JPN),False,dirt,23,4,2015-03-29,2025-04-20
48,Remington Park (USA),False,dirt,23,8,2015-09-27,2025-09-29
49,Riyadh (KSA),False,dirt,23,21,2020-02-29,2025-02-22
50,Funabashi (JPN),False,dirt,20,12,2015-03-11,2024-09-26
51,Hanshin (JPN),False,dirt,20,6,2015-04-18,2025-09-27
52,Kawasaki (JPN),False,dirt,20,12,2015-01-28,2024-07-03
53,Kyoto (JPN),False,dirt,20,8,2015-05-23,2025-05-24
54,Los Alamitos (USA),False,dirt,19,10,2015-07-05,2021-12-11
55,Morioka (JPN),False,dirt,19,10,2015-07-20,2024-09-03
56,Jagersro (SWE),False,dirt,18,13,2015-05-12,2022-05-22
57,Parx (USA),False,dirt,17,7,2015-08-29,2018-04-16
58,Ellis Park (USA),False,dirt,15,10,2015-08-08,2023-08-13
59,Santa Anita,False,dirt,15,15,2026-01-10,2026-05-25
60,Aqueduct,False,dirt,14,14,2025-11-02,2026-05-09
61,Mombetsu (JPN),False,dirt,14,8,2015-06-11,2023-08-17
62,Oaklawn Park,False,dirt,14,14,2026-02-06,2026-04-19
63,Seoul (KOR),False,dirt,14,12,2017-09-10,2025-09-07
64,Delaware Park (USA),False,dirt,13,7,2015-06-20,2018-08-13
65,Gulfstream Park,False,dirt,13,13,2026-01-24,2026-03-28
66,Urawa (JPN),False,dirt,13,3,2015-05-27,2024-06-19
67,Prairie Meadows (USA),False,dirt,12,4,2015-05-25,2018-07-07
68,Sonoda (JPN),False,dirt,12,5,2015-05-06,2022-12-21
69,Niigata (JPN),False,dirt,11,1,2015-08-09,2025-08-10
70,Sunland Park (USA),False,dirt,11,8,2015-01-24,2025-02-16
71,Delta downs (USA),False,dirt,10,8,2015-02-07,2016-11-19
72,NAGOYA (JPN),False,dirt,10,6,2015-03-26,2023-05-02
73,Sapporo (JPN),False,dirt,10,1,2015-08-16,2025-08-09
74,Bro Park (SWE),False,dirt,9,5,2016-09-11,2022-09-18
75,Churchill Downs,False,dirt,9,9,2026-05-01,2026-05-25
76,Indiana Grand (USA),False,dirt,9,3,2015-07-19,2018-07-15
77,Palermo,False,dirt,9,9,2025-11-08,2026-05-01
78,Fair Grounds,False,dirt,8,8,2026-01-17,2026-03-21
79,Keeneland,False,dirt,8,8,2026-04-03,2026-04-18
80,Lone Star Park (USA),False,dirt,8,3,2015-05-02,2018-05-28
81,Saga (JPN),False,dirt,7,4,2015-02-10,2021-09-01
82,Mountaineer Park (USA),False,dirt,6,3,2015-04-05,2018-08-04
83,Emerald Downs (USA),False,dirt,5,1,2015-08-17,2019-08-12
84,Hawthorne (USA),False,dirt,5,3,2015-04-18,2017-11-25
85,Laurel Park,False,dirt,5,5,2026-05-15,2026-05-17
86,Riyadh,False,dirt,5,5,2026-02-14,2026-02-14
87,Sam Houston (USA),False,dirt,5,3,2015-01-25,2018-01-28
88,Sharjah,False,dirt,5,5,2025-11-23,2026-01-25
89,Kyoto,False,dirt,4,4,2025-11-09,2026-05-23
90,Louisiana Downs (USA),False,dirt,4,1,2015-09-12,2019-09-07
91,Northlands park (CAN),False,dirt,4,1,2015-08-16,2018-08-26
92,Thistledown (USA),False,dirt,4,3,2015-06-20,2018-06-23
93,Cidade Jardim (BRZ),False,dirt,3,3,2015-01-25,2015-04-04
94,Hipodromo Chile,False,dirt,3,3,2025-11-01,2026-05-02
95,Kanazawa (JPN),False,dirt,3,2,2015-10-06,2023-09-26
96,Kokura (JPN),False,dirt,3,1,2021-07-11,2024-07-07
97,Tokyo,False,dirt,3,3,2025-11-15,2026-02-22
98,Kochi (JPN),False,dirt,2,2,2015-03-17,2021-03-16
99,Maronas,False,dirt,2,2,2026-01-06,2026-01-06
100,Nakayama,False,dirt,2,2,2025-12-14,2026-03-29
101,Taby (SWE),False,dirt,2,2,2015-09-20,2015-11-12
102,Tampa Bay Downs,False,dirt,2,2,2026-03-07,2026-03-07
103,Zia park (USA),False,dirt,2,2,2017-11-22,2024-11-26
104,Busan (KOR),False,dirt,1,1,2022-11-13,2022-11-13
105,Chukyo,False,dirt,1,1,2025-12-07,2025-12-07
106,Club Hipico de Santiago (CHI),False,dirt,1,1,2015-02-28,2015-02-28
107,Colonial Downs,False,dirt,1,1,2026-03-14,2026-03-14
108,Cristal (BRZ),False,dirt,1,1,2015-10-10,2015-10-10
109,Doha (QA),False,dirt,1,1,2020-01-22,2020-01-22
110,Fort Erie (CAN),False,dirt,1,1,2015-07-29,2015-07-29
111,Fukushima,False,dirt,1,1,2025-11-16,2025-11-16
112,Fukushima (JPN),False,dirt,1,1,2023-11-19,2023-11-19
113,Gavea (BRZ),False,dirt,1,1,2015-01-20,2015-01-20
114,Hakodate (JPN),False,dirt,1,1,2021-08-08,2021-08-08
115,Hanshin,False,dirt,1,1,2026-04-18,2026-04-18
116,La Plata,False,dirt,1,1,2025-11-19,2025-11-19
117,Lone Star Park,False,dirt,1,1,2026-05-26,2026-05-26
118,Mahoning Valley (USA),False,dirt,1,1,2017-11-20,2017-11-20
119,Monterrico,False,dirt,1,1,2025-11-23,2025-11-23
120,Ohi,False,dirt,1,1,2025-12-29,2025-12-29
121,Retama Park (USA),False,dirt,1,1,2015-09-13,2015-09-13
122,Sam Houston,False,dirt,1,1,2026-01-24,2026-01-24
123,San Isidro (ARG),False,dirt,1,1,2015-02-22,2015-02-22
124,Sunland Park,False,dirt,1,1,2026-02-15,2026-02-15
125,Timonium (USA),False,dirt,1,1,2019-08-23,2019-08-23
126,Sha Tin,False,"dirt, all_weather_track",3,3,2026-02-08,2026-02-08
127,Santa Anita (USA),False,"dirt, main_track",242,97,2018-09-30,2025-10-05
128,Gulfstream Park (USA),False,"dirt, main_track",241,103,2018-09-02,2025-09-20
129,Churchill Downs (USA),False,"dirt, main_track",209,92,2018-09-28,2025-09-27
130,Saratoga (USA),False,"dirt, main_track",191,81,2018-08-25,2025-09-01
131,Aqueduct (USA),False,"dirt, main_track",138,62,2018-11-02,2025-04-05
132,Belmont Park (USA),False,"dirt, main_track",124,56,2018-09-23,2023-07-08
133,Del Mar (USA),False,"dirt, main_track",118,39,2018-08-26,2025-09-07
134,Keeneland (USA),False,"dirt, main_track",115,36,2018-10-05,2025-10-05
135,Oaklawn Park (USA),False,"dirt, main_track",95,38,2019-02-18,2025-04-20
136,Fonner Park (USA),False,"dirt, main_track",68,23,2020-04-27,2020-05-28
137,Fair Grounds (USA),False,"dirt, main_track",46,27,2019-01-19,2025-03-22
138,Parx (USA),False,"dirt, main_track",46,12,2018-08-25,2025-09-20
139,Monmouth Park (USA),False,"dirt, main_track",45,15,2019-05-25,2025-08-16
140,Pimlico (USA),False,"dirt, main_track",45,19,2019-05-17,2025-05-18
141,Los Alamitos (USA),False,"dirt, main_track",29,7,2018-12-08,2025-07-06
142,Laurel Park (USA),False,"dirt, main_track",23,14,2019-02-16,2024-02-17
143,Indiana Grand (USA),False,"dirt, main_track",21,7,2019-07-14,2025-07-05
144,Tampa Bay Downs (USA),False,"dirt, main_track",18,9,2019-02-09,2025-03-08
145,Delaware Park (USA),False,"dirt, main_track",13,3,2019-07-06,2025-09-28
146,Mountaineer Park (USA),False,"dirt, main_track",12,3,2019-08-03,2025-08-04
147,Prairie Meadows (USA),False,"dirt, main_track",10,2,2019-07-06,2025-07-06
148,Del Mar,False,"dirt, main_track",8,8,2025-10-31,2025-11-30
149,Aqueduct,False,"dirt, main_track",7,7,2025-11-08,2025-12-27
150,Churchill Downs,False,"dirt, main_track",6,6,2025-10-26,2025-11-29
151,Lone Star Park (USA),False,"dirt, main_track",6,1,2019-04-28,2025-05-27
152,Thistledown (USA),False,"dirt, main_track",6,1,2019-06-22,2025-06-21
153,Belterra Park (USA),False,"dirt, main_track",4,3,2018-09-03,2019-09-28
154,Sam Houston (USA),False,"dirt, main_track",4,1,2019-01-27,2024-01-27
155,Finger Lakes (USA),False,"dirt, main_track",3,3,2019-09-09,2019-11-25
156,Keeneland,False,"dirt, main_track",3,3,2025-10-18,2025-10-25
157,Penn National (USA),False,"dirt, main_track",3,3,2019-11-14,2021-05-29
158,Santa Anita,False,"dirt, main_track",3,3,2025-12-28,2025-12-28
159,Emerald Downs (USA),False,"dirt, main_track",2,2,2020-09-11,2021-08-16
160,Gulfstream Park,False,"dirt, main_track",2,2,2025-12-20,2025-12-27
161,Gulfstream Park West (USA),False,"dirt, main_track",2,2,2019-11-16,2020-10-21
162,Los Alamitos,False,"dirt, main_track",2,2,2025-12-07,2025-12-13
163,Mahoning Valley (USA),False,"dirt, main_track",1,1,2019-12-28,2019-12-28
164,Churchill Downs (USA),False,main_track,5,4,2019-05-03,2025-05-03
165,Santa Anita (USA),False,main_track,2,2,2025-03-08,2025-09-29
166,Saratoga (USA),False,main_track,2,2,2019-08-24,2023-07-16
167,Sam Houston (USA),False,main_track,1,1,2025-01-25,2025-01-25
168,Deauville (FR),False,polytrack,1044,779,2015-01-03,2025-08-07
169,Chantilly (FR),False,polytrack,876,555,2015-01-23,2024-11-23
170,Chantilly,False,polytrack,131,131,2026-01-31,2026-05-19
171,Cagnes-Sur-Mer (FR),False,polytrack,76,56,2015-01-13,2025-02-23
172,Deauville,False,polytrack,41,41,2026-01-16,2026-04-08
173,Woodbine (CAN),False,polytrack,24,24,2015-04-18,2015-11-29
174,Turfway Park (USA),False,polytrack,10,7,2015-02-28,2018-03-17
175,Arlington Park (USA),False,polytrack,9,4,2015-07-18,2018-06-23
176,Veliefendi (TUR),False,polytrack,9,6,2015-09-05,2025-09-06
177,Greyville (SAF),False,polytrack,8,8,2020-03-18,2020-03-18
178,Marseille Pont-de-Vivaux (FR),False,polytrack,4,4,2017-02-06,2018-11-19
179,Cagnes-Sur-Mer,False,polytrack,1,1,2026-01-24,2026-01-24
180,Pakenham (AUS),False,polytrack,1,1,2018-05-06,2018-05-06
181,Pornichet-La Baule (FR),False,polytrack,1,1,2018-08-31,2018-08-31
182,Riccarton Park (NZ),False,polytrack,1,1,2025-05-03,2025-05-03
183,Deauville (FR),False,"polytrack, all_weather_track",1779,976,2018-08-28,2025-08-30
184,Chantilly (FR),False,"polytrack, all_weather_track",1712,820,2018-09-21,2025-10-14
185,Deauville,False,"polytrack, all_weather_track",191,191,2025-10-20,2026-01-23
186,Chantilly,False,"polytrack, all_weather_track",95,95,2025-10-27,2025-12-27
187,Arlington Park (USA),False,"polytrack, all_weather_track",9,8,2019-05-11,2021-08-28
188,Turfway Park (USA),False,"polytrack, all_weather_track",2,1,2019-03-09,2020-03-14
189,Woodbine (CAN),False,tapeta,61,32,2016-04-10,2024-10-12
190,Golden Gate Fields (USA),False,tapeta,13,7,2015-01-17,2018-05-29
191,Presque Isle Downs (USA),False,tapeta,3,1,2015-09-08,2017-09-19
192,Turfway Park,False,tapeta,2,2,2026-03-21,2026-03-21
193,Woodbine,False,tapeta,1,1,2026-05-02,2026-05-02
194,Woodbine (CAN),False,"tapeta, all_weather_track",161,53,2018-08-26,2025-09-20
195,Golden Gate Fields (USA),False,"tapeta, all_weather_track",31,17,2018-11-25,2023-11-05
196,Turfway Park (USA),False,"tapeta, all_weather_track",11,6,2021-03-27,2025-03-22
197,Woodbine,False,"tapeta, all_weather_track",8,8,2025-10-18,2025-12-06
198,Presque Isle Downs (USA),False,"tapeta, all_weather_track",6,1,2018-09-18,2025-09-20
199,Gulfstream Park (USA),False,"tapeta, all_weather_track",1,1,2022-12-17,2022-12-17
200,Sha Tin (HK),False,turf,3411,2387,2015-01-25,2025-10-12
201,Auteuil (FR),False,turf,3117,869,2015-03-01,2025-10-12
202,Happy Valley (HK),False,turf,2686,1992,2016-01-06,2025-10-08
203,Saint-Cloud (FR),False,turf,2553,1237,2015-03-07,2025-10-09
204,Longchamp (FR),False,turf,1918,1237,2015-04-06,2025-10-05
205,Chantilly (FR),False,turf,1539,807,2015-03-30,2025-10-14
206,Deauville (FR),False,turf,1164,765,2015-06-26,2025-08-30
207,Compiegne (FR),False,turf,989,350,2015-03-09,2025-10-10
208,Maisons-Laffitte (FR),False,turf,985,698,2015-04-02,2019-10-29
209,Randwick (AUS),False,turf,719,411,2015-02-14,2025-10-04
210,Caulfield (AUS),False,turf,573,320,2015-02-14,2025-10-11
211,Meydan (UAE),False,turf,528,434,2015-01-08,2025-04-05
212,Flemington (AUS),False,turf,497,220,2015-02-21,2025-10-04
213,Rosehill (AUS),False,turf,467,314,2015-02-21,2025-10-11
214,Santa Anita (USA),False,turf,396,144,2015-01-03,2025-10-06
215,Gulfstream Park (USA),False,turf,352,151,2015-01-03,2025-05-10
216,Sha Tin,False,turf,316,313,2025-10-19,2026-05-24
217,Enghien (FR),False,turf,278,165,2015-02-24,2016-11-21
218,Les Landes (JER),False,turf,266,222,2015-06-26,2025-08-25
219,Happy Valley,False,turf,251,248,2025-10-15,2026-05-27
220,Tokyo (JPN),False,turf,245,51,2015-02-08,2025-10-12
221,Moonee Valley (AUS),False,turf,234,134,2015-01-24,2025-09-26
222,Nakayama (JPN),False,turf,230,62,2015-01-04,2025-09-28
223,Del Mar (USA),False,turf,213,68,2015-07-18,2025-09-08
224,Keeneland (USA),False,turf,211,74,2015-04-04,2025-10-12
225,Auteuil,False,turf,209,209,2025-10-18,2026-05-26
226,Morphettville (AUS),False,turf,204,132,2015-02-28,2025-08-09
227,Ascot (AUS),False,turf,202,119,2015-03-14,2025-05-10
228,Hanshin (JPN),False,turf,201,62,2015-02-28,2025-09-28
229,San Siro (ITY),False,turf,198,108,2015-04-01,2025-10-12
230,Woodbine (CAN),False,turf,181,56,2015-05-23,2025-10-04
231,San Isidro (ARG),False,turf,178,99,2015-02-07,2025-10-04
232,Eagle Farm (AUS),False,turf,166,108,2016-06-11,2025-06-28
233,Saratoga (USA),False,turf,162,110,2015-07-24,2025-09-01
234,Churchill Downs (USA),False,turf,159,76,2015-05-01,2025-06-28
235,Kyoto (JPN),False,turf,159,56,2015-01-04,2025-10-13
236,Belmont Park (USA),False,turf,158,102,2015-04-29,2021-09-18
237,Saint-Cloud,False,turf,158,158,2025-10-16,2026-05-22
238,Baden-Baden (GER),False,turf,155,122,2015-06-04,2025-09-07
239,Doomben (AUS),False,turf,153,116,2015-05-09,2025-06-04
240,Abu Dhabi (UAE),False,turf,152,111,2015-01-04,2025-04-12
241,Clairefontaine (FR),False,turf,142,131,2015-08-10,2025-08-15
242,Capannelle (ITY),False,turf,133,104,2015-04-26,2025-06-02
243,Gavea (BRZ),False,turf,133,63,2015-01-20,2025-06-22
244,Cidade Jardim (BRZ),False,turf,131,49,2015-02-01,2025-09-06
245,Greyville (SAF),False,turf,124,59,2015-05-30,2025-07-27
246,Turffontein Standside (SAF),False,turf,124,85,2015-11-28,2025-03-29
247,Fontainebleau (FR),False,turf,118,96,2015-03-04,2025-04-01
248,Longchamp,False,turf,103,103,2025-10-19,2026-05-24
249,Cagnes-Sur-Mer (FR),False,turf,97,76,2015-02-14,2025-02-25
250,Chukyo (JPN),False,turf,96,39,2015-03-14,2025-08-31
251,Cologne (GER),False,turf,94,72,2015-04-19,2025-10-12
252,Kenilworth (SAF),False,turf,94,61,2015-01-24,2025-02-22
253,Compiegne,False,turf,92,92,2025-10-20,2026-05-13
254,Toulouse (FR),False,turf,92,43,2015-02-17,2025-10-01
255,Club Hipico de Santiago (CHI),False,turf,90,47,2015-02-06,2025-10-05
256,Dusseldorf (GER),False,turf,86,76,2015-04-12,2025-10-05
257,Kentucky Downs (USA),False,turf,86,65,2015-09-15,2025-09-10
258,Vichy (FR),False,turf,79,29,2015-07-20,2025-07-18
259,Hoppegarten (GER),False,turf,76,63,2015-05-14,2025-10-03
260,Newcastle (AUS),False,turf,76,55,2015-03-07,2025-09-19
261,Ellerslie (NZ),False,turf,72,39,2015-01-01,2025-09-06
262,Lyon Parilly (FR),False,turf,72,39,2015-03-20,2025-09-09
263,Hanover (GER),False,turf,67,57,2015-05-17,2024-10-27
264,Hamburg (GER),False,turf,66,57,2015-06-27,2025-07-08
265,Sandown (AUS),False,turf,63,41,2015-02-07,2025-09-27
266,Bahrain (BHR),False,turf,62,60,2022-11-18,2025-03-20
267,Meydan,False,turf,62,62,2025-12-12,2026-03-28
268,Monmouth Park (USA),False,turf,61,13,2015-05-16,2025-07-19
269,Randwick,False,turf,60,60,2025-10-18,2026-04-18
270,Bahrain,False,turf,58,58,2025-11-14,2026-04-24
271,Doha (QA),False,turf,57,32,2015-02-26,2025-02-15
272,Niigata (JPN),False,turf,56,10,2015-05-10,2025-08-31
273,Tampa Bay Downs (USA),False,turf,56,18,2015-01-04,2025-03-08
274,Bro Park (SWE),False,turf,55,28,2016-06-19,2025-09-21
275,Dieppe (FR),False,turf,53,47,2016-06-05,2025-06-19
276,Arlington Park (USA),False,turf,51,20,2015-07-11,2021-08-15
277,Chantilly,False,turf,49,49,2025-10-27,2026-05-19
278,Trentham (NZ),False,turf,49,30,2015-01-17,2025-03-29
279,Pau (FR),False,turf,48,43,2015-12-25,2024-02-08
280,Kokura (JPN),False,turf,47,14,2015-02-22,2025-07-20
281,Gold Coast (AUS),False,turf,44,33,2015-04-25,2025-05-10
282,Munich (GER),False,turf,44,31,2015-05-01,2025-07-27
283,Nantes (FR),False,turf,44,30,2015-03-24,2025-04-09
284,Sapporo (JPN),False,turf,44,5,2015-08-02,2025-09-06
285,Craon (FR),False,turf,43,35,2015-09-07,2025-09-29
286,Caulfield,False,turf,42,42,2025-10-15,2026-04-04
287,La Teste De Buch (FR),False,turf,42,19,2015-03-20,2025-08-29
288,Bordeaux Le Bouscat (FR),False,turf,41,32,2015-04-05,2025-09-29
289,Veliefendi (TUR),False,turf,41,18,2015-09-05,2025-09-07
290,Aqueduct (USA),False,turf,40,25,2015-04-19,2024-11-16
291,Scottsville (SAF),False,turf,40,19,2015-05-23,2025-05-31
292,Fukushima (JPN),False,turf,38,4,2015-04-25,2025-07-13
293,Kembla Grange (AUS),False,turf,38,33,2015-03-09,2025-03-14
294,Flemington,False,turf,36,36,2025-11-01,2026-03-28
295,Ovrevoll (NOR),False,turf,35,17,2015-06-25,2025-08-24
296,Rosehill,False,turf,34,34,2025-11-08,2026-03-28
297,Turffontein Inside (SAF),False,turf,34,34,2018-04-02,2023-10-07
298,Hawkesbury (AUS),False,turf,33,25,2015-03-10,2025-05-03
299,Abu Dhabi,False,turf,32,32,2025-10-25,2026-04-11
300,Warwick Farm (AUS),False,turf,32,30,2015-02-28,2025-04-02
301,Belmont Park (Perth) (AUS),False,turf,31,17,2015-05-16,2024-06-15
302,Marseille Borely (FR),False,turf,31,10,2015-05-25,2025-09-15
303,Fair Grounds (USA),False,turf,30,18,2015-01-17,2025-03-22
304,Hakodate (JPN),False,turf,30,4,2015-06-21,2025-07-20
305,Pimlico (USA),False,turf,29,14,2015-05-16,2025-05-17
306,Sakhir (BHR),False,turf,29,28,2015-02-27,2022-03-11
307,Te Rapa (NZ),False,turf,29,15,2015-01-31,2025-09-27
308,Dortmund (GER),False,turf,28,25,2015-06-21,2025-09-21
309,Hastings (NZ),False,turf,28,12,2015-02-28,2024-09-07
310,Le Lion-D'Angers (FR),False,turf,28,27,2015-05-08,2025-05-29
311,Angers (FR),False,turf,26,24,2015-10-12,2024-02-17
312,Santa Anita,False,turf,26,26,2025-10-25,2026-05-26
313,Geelong (AUS),False,turf,24,15,2015-04-29,2024-10-23
314,Delaware Park (USA),False,turf,23,9,2015-07-11,2025-07-05
315,Far Hills (USA),False,turf,23,13,2015-10-17,2024-10-19
316,Palermo (ARG),False,turf,23,7,2015-01-03,2025-09-06
317,Parx (USA),False,turf,22,9,2015-07-04,2023-09-23
318,Ascot,False,turf,21,21,2025-10-18,2026-05-02
319,Krefeld (GER),False,turf,21,20,2015-04-26,2025-04-27
320,Monterrico (PER),False,turf,21,11,2015-01-18,2025-06-22
321,Sunshine Coast (AUS),False,turf,21,16,2015-05-16,2025-07-05
322,Hobart (AUS),False,turf,20,14,2016-02-05,2025-02-09
323,Launceston (AUS),False,turf,20,12,2015-02-18,2025-02-26

In [20]:
# Measure how many distinct explicit surface families occur at each raw course.
#
# This cell reduces the detailed race-name terminology into provisional
# surface families:
# - turf;
# - dirt;
# - synthetic_polytrack;
# - synthetic_tapeta;
# - other_all_weather;
# - no_explicit_race_name_surface.
#
# "Main Track" is treated as supporting context for Dirt rather than as
# a separate surface family.
#
# The purpose is to identify:
# - courses with one stable explicit surface family;
# - courses with multiple legitimate surfaces;
# - courses where the race name provides no explicit surface evidence.
#
# These are analytical categories only and are not final canonical rules.

def classify_explicit_surface_family(row):
    """Assign a provisional surface family from explicit race-name evidence."""
    if row["race_name_marks_turf"]:
        return "turf"

    if row["race_name_marks_dirt"]:
        return "dirt"

    if row["race_name_marks_polytrack"]:
        return "synthetic_polytrack"

    if row["race_name_marks_tapeta"]:
        return "synthetic_tapeta"

    if row["race_name_marks_all_weather_track"]:
        return "other_all_weather"

    return "no_explicit_race_name_surface"


surface_evidence["explicit_surface_family"] = (
    surface_evidence.apply(
        classify_explicit_surface_family,
        axis=1,
    )
)

course_surface_family_summary = (
    surface_evidence
    .groupby("course", as_index=False)
    .agg(
        provisional_races=("race_name", "size"),
        explicit_surface_families=(
            "explicit_surface_family",
            lambda values: ", ".join(
                sorted(
                    {
                        value
                        for value in values
                        if value != "no_explicit_race_name_surface"
                    }
                )
            )
            or "[none]",
        ),
        distinct_explicit_surface_families=(
            "explicit_surface_family",
            lambda values: len(
                {
                    value
                    for value in values
                    if value != "no_explicit_race_name_surface"
                }
            ),
        ),
        races_without_explicit_surface=(
            "race_name_has_explicit_surface",
            lambda values: (~values).sum(),
        ),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
)

course_surface_family_summary["share_without_explicit_surface"] = (
    course_surface_family_summary["races_without_explicit_surface"]
    / course_surface_family_summary["provisional_races"]
)

course_surface_family_summary = (
    course_surface_family_summary
    .sort_values(
        [
            "distinct_explicit_surface_families",
            "provisional_races",
            "course",
        ],
        ascending=[False, False, True],
    )
    .reset_index(drop=True)
)

print(
    "Raw courses assessed: "
    f"{len(course_surface_family_summary):,}"
)
print(
    "Courses with more than one explicit surface family: "
    f"{(
        course_surface_family_summary[
            'distinct_explicit_surface_families'
        ] > 1
    ).sum():,}"
)
print(
    "Courses with exactly one explicit surface family: "
    f"{(
        course_surface_family_summary[
            'distinct_explicit_surface_families'
        ] == 1
    ).sum():,}"
)
print(
    "Courses with no explicit race-name surface family: "
    f"{(
        course_surface_family_summary[
            'distinct_explicit_surface_families'
        ] == 0
    ).sum():,}"
)

course_surface_family_summary.head(50)

Raw courses assessed: 528
Courses with more than one explicit surface family: 79
Courses with exactly one explicit surface family: 327
Courses with no explicit race-name surface family: 122

,course,provisional_races,explicit_surface_families,distinct_explicit_surface_families,races_without_explicit_surface,first_date,last_date,share_without_explicit_surface
0,Woodbine (CAN),434,"other_all_weather, synthetic_polytrack, synthe...",4,4,2015-04-18,2025-10-11,0.009217
1,Chantilly (FR),4140,"other_all_weather, synthetic_polytrack, turf",3,9,2015-01-23,2025-10-14,0.002174
2,Deauville (FR),4051,"other_all_weather, synthetic_polytrack, turf",3,52,2015-01-03,2025-08-30,0.012836
3,Gulfstream Park (USA),745,"dirt, synthetic_tapeta, turf",3,2,2015-01-03,2025-09-20,0.002685
4,Turfway Park (USA),24,"other_all_weather, synthetic_polytrack, synthe...",3,0,2015-02-28,2025-03-22,0.000000
5,Sha Tin (HK),4160,"dirt, turf",2,3,2015-01-25,2025-10-12,0.000721
6,Meydan (UAE),1320,"dirt, turf",2,0,2015-01-08,2025-04-05,0.000000
7,Santa Anita (USA),828,"dirt, turf",2,4,2015-01-03,2025-10-06,0.004831
8,Saratoga (USA),528,"dirt, turf",2,80,2015-07-24,2025-09-01,0.151515
9,Belmont Park (USA),482,"dirt, turf",2,87,2015-04-29,2023-07-08,0.180498
10,Churchill Downs (USA),474,"dirt, turf",2,1,2015-04-26,2025-09-27,0.002110
11,Keeneland (USA),409,"dirt, turf",2,1,2015-04-03,2025-10-12,0.002445
12,Del Mar (USA),398,"dirt, turf",2,0,2015-07-18,2025-09-08,0.000000
13,Sha Tin,383,"dirt, turf",2,13,2025-10-19,2026-05-24,0.033943
14,Chantilly,298,"synthetic_polytrack, turf",2,23,2025-10-27,2026-05-19,0.077181
15,Aqueduct (USA),297,"dirt, turf",2,0,2015-01-01,2025-04-05,0.000000
16,Tokyo (JPN),286,"dirt, turf",2,0,2015-02-01,2025-10-12,0.000000
17,Deauville,266,"synthetic_polytrack, turf",2,19,2025-10-20,2026-04-08,0.071429
18,Nakayama (JPN),258,"dirt, turf",2,5,2015-01-04,2025-09-28,0.019380
19,Hanshin (JPN),221,"dirt, turf",2,0,2015-02-28,2025-09-28,0.000000
20,Palermo (ARG),200,"dirt, turf",2,1,2015-01-03,2025-10-11,0.005000
21,Kyoto (JPN),179,"dirt, turf",2,0,2015-01-04,2025-10-13,0.000000
22,San Isidro (ARG),179,"dirt, turf",2,0,2015-02-07,2025-10-04,0.000000
23,Cagnes-Sur-Mer (FR),175,"synthetic_polytrack, turf",2,2,2015-01-13,2025-02-25,0.011429
24,Monmouth Park (USA),139,"dirt, turf",2,0,2015-05-16,2025-08-16,0.000000
25,Cidade Jardim (BRZ),136,"dirt, turf",2,2,2015-01-25,2025-09-06,0.014706
26,Gavea (BRZ),136,"dirt, turf",2,2,2015-01-20,2025-06-22,0.014706
27,Greyville (SAF),132,"synthetic_polytrack, turf",2,0,2015-05-30,2025-07-27,0.000000
28,Meydan,131,"dirt, turf",2,0,2025-11-07,2026-03-28,0.000000
29,Chukyo (JPN),129,"dirt, turf",2,0,2015-01-25,2025-08-31,0.000000
30,Fair Grounds (USA),112,"dirt, turf",2,0,2015-01-17,2025-03-22,0.000000
31,Tampa Bay Downs (USA),107,"dirt, turf",2,0,2015-01-04,2025-03-08,0.000000
32,Pimlico (USA),100,"dirt, turf",2,0,2015-04-18,2025-05-18,0.000000
33,Club Hipico de Santiago (CHI),91,"dirt, turf",2,0,2015-02-06,2025-10-05,0.000000
34,Parx (USA),85,"dirt, turf",2,0,2015-07-04,2025-09-20,0.000000
35,Monterrico (PER),84,"dirt, turf",2,0,2015-01-11,2025-09-14,0.000000
36,Laurel Park (USA),71,"dirt, turf",2,0,2015-01-01,2025-02-22,0.000000
37,Arlington Park (USA),70,"synthetic_polytrack, turf",2,1,2015-07-11,2021-08-28,0.014286
38,Niigata (JPN),67,"dirt, turf",2,0,2015-05-10,2025-08-31,0.000000
39,Bro Park (SWE),64,"dirt, turf",2,0,2016-06-19,2025-09-21,0.000000
40,Doha (QA),61,"dirt, turf",2,3,2015-02-26,2025-02-15,0.049180
41,Golden Gate Fields (USA),54,"synthetic_tapeta, turf",2,0,2015-01-17,2024-04-28,0.000000
42,Sapporo (JPN),54,"dirt, turf",2,0,2015-08-02,2025-09-06,0.000000
43,Kokura (JPN),50,"dirt, turf",2,0,2015-02-22,2025-07-20,0.000000
44,Veliefendi (TUR),50,"synthetic_polytrack, turf",2,0,2015-09-05,2025-09-07,0.000000
45,Delaware Park (USA),49,"dirt, turf",2,0,2015-06-20,2025-09-28,0.000000
46,Santa Anita,44,"dirt, turf",2,0,2025-10-25,2026-05-26,0.000000
47,Riyadh (KSA),41,"dirt, turf",2,0,2020-02-29,2025-02-22,0.000000
48,Indiana Grand (USA),40,"dirt, turf",2,0,2015-07-19,2025-07-05,0.000000
49,Fukushima (JPN),39,"dirt, turf",2,0,2015-04-25,2025-07-13,0.000000

In [21]:
# Measure race-level surface coverage using only direct source evidence.
#
# Evidence hierarchy for this diagnostic:
#
# 1. An explicit surface term in race_name:
#    - Turf
#    - Dirt
#    - Polytrack
#    - Tapeta
#    - other All-Weather Track wording
#
# 2. If race_name has no explicit surface term, a course name containing
#    "(AW)" supplies broad all-weather evidence.
#
# 3. Otherwise, surface remains unresolved.
#
# This cell does not use external course knowledge or infer that all British
# Flat races are turf. It measures only what can be derived directly from the
# current source fields.

def derive_direct_surface_evidence(row):
    """Return provisional surface and evidence source from direct raw evidence."""
    if row["race_name_marks_turf"]:
        return pd.Series(
            ["turf", "race_name_explicit_turf"]
        )

    if row["race_name_marks_dirt"]:
        return pd.Series(
            ["dirt", "race_name_explicit_dirt"]
        )

    if row["race_name_marks_polytrack"]:
        return pd.Series(
            ["synthetic_polytrack", "race_name_explicit_polytrack"]
        )

    if row["race_name_marks_tapeta"]:
        return pd.Series(
            ["synthetic_tapeta", "race_name_explicit_tapeta"]
        )

    if row["race_name_marks_all_weather_track"]:
        return pd.Series(
            ["all_weather_unspecified", "race_name_explicit_all_weather"]
        )

    if row["course_marks_aw"]:
        return pd.Series(
            ["all_weather_unspecified", "course_name_aw_marker"]
        )

    return pd.Series(
        ["unresolved", "no_direct_surface_evidence"]
    )


surface_evidence[
    ["direct_surface", "surface_evidence_source"]
] = surface_evidence.apply(
    derive_direct_surface_evidence,
    axis=1,
)

direct_surface_coverage = (
    surface_evidence
    .groupby(
        ["direct_surface", "surface_evidence_source"],
        as_index=False,
    )
    .agg(
        provisional_races=("race_name", "size"),
        distinct_raw_courses=("course", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
)

direct_surface_coverage["share_of_all_races"] = (
    direct_surface_coverage["provisional_races"]
    / len(surface_evidence)
)

direct_surface_coverage = (
    direct_surface_coverage
    .sort_values(
        ["provisional_races", "direct_surface"],
        ascending=[False, True],
    )
    .reset_index(drop=True)
)

resolved_races = (
    surface_evidence["direct_surface"] != "unresolved"
).sum()

print(
    "Provisional races with directly derivable surface evidence: "
    f"{resolved_races:,}"
)
print(
    "Directly resolved share of all provisional races: "
    f"{resolved_races / len(surface_evidence):.2%}"
)
print(
    "Provisional races remaining unresolved: "
    f"{(surface_evidence['direct_surface'] == 'unresolved').sum():,}"
)

direct_surface_coverage

Provisional races with directly derivable surface evidence: 78,871
Directly resolved share of all provisional races: 41.72%
Provisional races remaining unresolved: 110,172

,direct_surface,surface_evidence_source,provisional_races,distinct_raw_courses,first_date,last_date,share_of_all_races
0,unresolved,no_direct_surface_evidence,110172,203,2015-01-01,2026-05-27,0.582788
1,turf,race_name_explicit_turf,32637,344,2015-01-01,2026-05-27,0.172643
2,all_weather_unspecified,course_name_aw_marker,32308,8,2015-01-01,2026-05-27,0.170903
3,dirt,race_name_explicit_dirt,6869,119,2015-01-01,2026-05-26,0.036336
4,synthetic_polytrack,race_name_explicit_polytrack,6025,16,2015-01-03,2026-05-19,0.031871
5,synthetic_tapeta,race_name_explicit_tapeta,1012,8,2015-01-02,2026-05-02,0.005353
6,all_weather_unspecified,race_name_explicit_all_weather,20,4,2019-08-20,2025-10-11,0.000106

In [22]:
# Profile the 110,172 races that remain unresolved after direct
# surface parsing.
#
# This cell measures unresolved races by:
# - raw race type;
# - whether the course has an explicit jurisdiction suffix;
# - whether the course is one of the longstanding unsuffixed British-course
#   values identified earlier;
# - whether it is a historically linked post-October-2025 unsuffixed
#   international course;
# - remaining unclassified course representation.
#
# The categories are diagnostic only. They do not yet assign surface.

established_unsuffixed_british_courses = set(
    unlinked_unsuffixed_courses.loc[
        unlinked_unsuffixed_courses["course"] != "Firenze",
        "course",
    ]
)

historically_linked_unsuffixed_courses = set(
    historical_jurisdiction_links["later_raw_course"]
)

def classify_unresolved_course_representation(course_name):
    """Classify how jurisdiction or venue context is represented."""
    course_name = str(course_name)

    if course_name in established_unsuffixed_british_courses:
        return "established_unsuffixed_british_course"

    if course_name in historically_linked_unsuffixed_courses:
        return "historically_linked_unsuffixed_international"

    if extract_terminal_jurisdiction_code(course_name) is not None:
        return "explicit_terminal_jurisdiction_code"

    if "(" in course_name and ")" in course_name:
        return "other_parenthetical_course_form"

    return "other_unsuffixed_or_unresolved"

unresolved_surface_races = surface_evidence.loc[
    surface_evidence["direct_surface"] == "unresolved"
].copy()

unresolved_surface_races["course_representation_group"] = (
    unresolved_surface_races["course"].map(
        classify_unresolved_course_representation
    )
)

unresolved_surface_profile = (
    unresolved_surface_races
    .groupby(
        ["course_representation_group", "type"],
        as_index=False,
    )
    .agg(
        provisional_races=("race_name", "size"),
        distinct_raw_courses=("course", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
)

unresolved_surface_profile["share_of_unresolved_races"] = (
    unresolved_surface_profile["provisional_races"]
    / len(unresolved_surface_races)
)

unresolved_surface_profile = (
    unresolved_surface_profile
    .sort_values(
        ["provisional_races", "course_representation_group", "type"],
        ascending=[False, True, True],
    )
    .reset_index(drop=True)
)

print(f"Unresolved provisional races profiled: {len(unresolved_surface_races):,}")
print(
    "Unresolved races at established unsuffixed British courses: "
    f"{(
        unresolved_surface_races['course_representation_group']
        == 'established_unsuffixed_british_course'
    ).sum():,}"
)
print(
    "Unresolved races at historically linked unsuffixed international courses: "
    f"{(
        unresolved_surface_races['course_representation_group']
        == 'historically_linked_unsuffixed_international'
    ).sum():,}"
)

unresolved_surface_profile

Unresolved provisional races profiled: 110,172
Unresolved races at established unsuffixed British courses: 80,770
Unresolved races at historically linked unsuffixed international courses: 1,353

,course_representation_group,type,provisional_races,distinct_raw_courses,first_date,last_date,share_of_unresolved_races
0,established_unsuffixed_british_course,Flat,39455,36,2015-02-13,2026-05-27,0.358122
1,established_unsuffixed_british_course,Hurdle,22645,43,2015-01-01,2026-05-27,0.205542
2,established_unsuffixed_british_course,Chase,15671,43,2015-01-01,2026-05-27,0.142241
3,explicit_terminal_jurisdiction_code,Flat,11457,104,2015-01-01,2025-10-13,0.103992
4,explicit_terminal_jurisdiction_code,Hurdle,9158,34,2015-01-01,2025-10-14,0.083125
5,explicit_terminal_jurisdiction_code,Chase,4572,34,2015-01-01,2025-10-12,0.041499
6,established_unsuffixed_british_course,NH Flat,2999,40,2015-01-01,2026-05-26,0.027221
7,other_parenthetical_course_form,Flat,1438,1,2015-06-19,2025-08-23,0.013052
8,explicit_terminal_jurisdiction_code,NH Flat,1424,24,2015-01-03,2025-10-14,0.012925
9,historically_linked_unsuffixed_international,Hurdle,581,20,2025-10-15,2026-05-27,0.005274
10,historically_linked_unsuffixed_international,Flat,389,22,2025-10-16,2026-05-24,0.003531
11,historically_linked_unsuffixed_international,Chase,287,18,2025-10-15,2026-05-25,0.002605
12,historically_linked_unsuffixed_international,NH Flat,96,20,2025-10-15,2026-05-27,0.000871

In [23]:
# Identify British venues represented by both an unsuffixed course value
# and an explicit "(AW)" course value.
#
# This tests whether the same apparent venue name is split into distinct
# surface-bearing raw course values, for example:
# - Lingfield
# - Lingfield (AW)
#
# Such pairs are important because the unsuffixed form must not inherit
# all-weather status merely from sharing a venue name.
#
# This cell compares exact raw values only. It does not yet assign turf
# to the unsuffixed form.

aw_course_values = course_inventory.loc[
    course_inventory["course"].str.contains(
        r"\(AW\)",
        regex=True,
        na=False,
    )
].copy()

aw_course_values["base_venue_name"] = (
    aw_course_values["course"]
    .str.replace(r"\s+\(AW\)", "", regex=True)
    .str.replace(r"\s+\(IRE\)$", "", regex=True)
)

unsuffixed_british_inventory = course_inventory.loc[
    course_inventory["course"].isin(
        established_unsuffixed_british_courses
    )
].copy()

dual_surface_venue_pairs = (
    aw_course_values
    .merge(
        unsuffixed_british_inventory,
        left_on="base_venue_name",
        right_on="course",
        how="inner",
        suffixes=("_aw", "_unsuffixed"),
    )
    [
        [
            "base_venue_name",
            "course_aw",
            "provisional_races_aw",
            "first_date_aw",
            "last_date_aw",
            "course_unsuffixed",
            "provisional_races_unsuffixed",
            "first_date_unsuffixed",
            "last_date_unsuffixed",
        ]
    ]
    .sort_values("base_venue_name")
    .reset_index(drop=True)
)

print(
    "Apparent British venues with both unsuffixed and (AW) forms: "
    f"{len(dual_surface_venue_pairs):,}"
)

dual_surface_venue_pairs

Apparent British venues with both unsuffixed and (AW) forms: 4

,base_venue_name,course_aw,provisional_races_aw,first_date_aw,last_date_aw,course_unsuffixed,provisional_races_unsuffixed,first_date_unsuffixed,last_date_unsuffixed
0,Kempton,Kempton (AW),5046,2015-01-07,2026-05-27,Kempton,902,2015-01-10,2026-03-23
1,Lingfield,Lingfield (AW),4803,2015-01-03,2026-05-12,Lingfield,1457,2015-01-05,2026-05-26
2,Newcastle,Newcastle (AW),4409,2016-05-17,2026-05-19,Newcastle,1010,2015-01-03,2026-04-11
3,Southwell,Southwell (AW),3816,2015-01-01,2026-05-21,Southwell,1372,2015-02-22,2026-05-11

In [24]:
# Test the unresolved unsuffixed races at the four dual-representation venues.
#
# The source distinguishes:
# - venue name alone;
# - venue name with "(AW)".
#
# This cell profiles only the unsuffixed form by race type and date range.
# The purpose is to see whether those records behave like a separate
# non-all-weather course configuration rather than incomplete copies of
# the "(AW)" form.
#
# No turf assignment is made yet.

dual_representation_venues = set(
    dual_surface_venue_pairs["base_venue_name"]
)

dual_venue_unsuffixed_profile = (
    unresolved_surface_races.loc[
        unresolved_surface_races["course"].isin(
            dual_representation_venues
        )
    ]
    .groupby(
        ["course", "type"],
        as_index=False,
    )
    .agg(
        provisional_races=("race_name", "size"),
        distinct_race_names=("race_name", "nunique"),
        active_dates=("date", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
    .sort_values(
        ["course", "provisional_races"],
        ascending=[True, False],
    )
    .reset_index(drop=True)
)

print(
    "Unresolved races at unsuffixed dual-representation venues: "
    f"{dual_venue_unsuffixed_profile['provisional_races'].sum():,}"
)

dual_venue_unsuffixed_profile

Unresolved races at unsuffixed dual-representation venues: 4,738

,course,type,provisional_races,distinct_race_names,active_dates,first_date,last_date
0,Kempton,Hurdle,482,362,130,2015-01-10,2026-03-23
1,Kempton,Chase,362,265,130,2015-01-10,2026-03-23
2,Kempton,NH Flat,58,51,37,2015-02-06,2026-03-14
3,Lingfield,Flat,992,775,172,2015-05-08,2026-05-26
4,Lingfield,Hurdle,265,220,76,2015-01-05,2026-02-05
5,Lingfield,Chase,197,173,76,2015-01-05,2026-02-05
6,Lingfield,NH Flat,3,3,3,2023-11-14,2026-01-19
7,Newcastle,Hurdle,450,393,122,2015-01-03,2026-04-11
8,Newcastle,Chase,318,276,123,2015-01-03,2026-04-11
9,Newcastle,NH Flat,121,110,83,2015-01-03,2026-04-11
10,Newcastle,Flat,118,113,16,2015-04-11,2015-09-04
11,Southwell,Hurdle,780,653,198,2015-02-22,2026-05-11
12,Southwell,Chase,458,330,198,2015-02-22,2026-05-11
13,Southwell,NH Flat,133,127,126,2015-02-22,2026-05-11
14,Southwell,Flat,1,1,1,2023-06-26,2023-06-26

In [25]:
# Inspect all unsuffixed Flat races at the four venues that also have
# a separate "(AW)" course value.
#
# This isolates:
# - Lingfield turf Flat racing;
# - Newcastle's pre-all-weather Flat history;
# - the single Southwell Flat exception;
# - confirmation that Kempton has no unsuffixed Flat records.
#
# The output remains at provisional race grain and preserves the exact
# raw course, race name and source attributes.

dual_venue_unsuffixed_flat_sql = f"""
SELECT
    date,
    course,
    off,
    race_name,
    type,
    race_id,
    COUNT(*) AS runner_rows,
    MIN(rowid) AS first_source_rowid,
    MAX(rowid) AS last_source_rowid
FROM {SOURCE_TABLE}
WHERE {DATA_ROW_PREDICATE}
  AND course IN ('Kempton', 'Lingfield', 'Newcastle', 'Southwell')
  AND type = 'Flat'
GROUP BY
    date,
    course,
    off,
    race_name,
    type,
    race_id
ORDER BY
    course,
    date,
    off
"""

dual_venue_unsuffixed_flat_races = pd.read_sql_query(
    dual_venue_unsuffixed_flat_sql,
    connection,
)

print(
    "Unsuffixed Flat provisional races at the four dual-representation venues: "
    f"{len(dual_venue_unsuffixed_flat_races):,}"
)

print()
print("Counts by course:")
print(
    dual_venue_unsuffixed_flat_races["course"]
    .value_counts()
    .sort_index()
    .to_string()
)

dual_venue_unsuffixed_flat_races.loc[
    dual_venue_unsuffixed_flat_races["course"].isin(
        ["Newcastle", "Southwell"]
    )
]

Unsuffixed Flat provisional races at the four dual-representation venues: 1,114

Counts by course:
course
Lingfield    992
Newcastle    121
Southwell      1

,date,course,off,race_name,type,race_id,runner_rows,first_source_rowid,last_source_rowid
992,2015-04-11,Newcastle,1:40,vertem.co.uk Maiden Fillies Stakes,Flat,621254,9,37296,37304
993,2015-04-11,Newcastle,2:15,Protecting Your Wealth Maiden Stakes,Flat,621255,8,37287,37310
994,2015-04-11,Newcastle,2:45,@VertemAM Twitter Handicap,Flat,621256,16,37264,37285
995,2015-04-11,Newcastle,3:15,Perfect Partnerships Handicap,Flat,621257,13,36744,37283
996,2015-04-11,Newcastle,3:55,Vertem Management Handicap (Div I),Flat,621258,11,36749,36759
997,2015-04-11,Newcastle,5:00,Vertem Management Handicap (Div II),Flat,623929,11,36737,36797
998,2015-04-11,Newcastle,5:35,Fresh Approach At Vertem Handicap,Flat,621259,12,36720,36764
999,2015-04-11,Newcastle,6:05,Investing For The Future Apprentice Handicap,Flat,621260,15,36718,36740
1000,2015-04-28,Newcastle,5:10,EBF Stallions/Hardwick Hall Hotel Novice Stakes,Flat,622992,4,45655,45817
1001,2015-04-28,Newcastle,5:45,Bowburn Hall Hotel Maiden Stakes,Flat,622993,8,45587,45595
1002,2015-04-28,Newcastle,6:15,New Spa At Ramside Hall Hotel Handicap,Flat,622994,10,45578,45737
1003,2015-04-28,Newcastle,6:50,Ramside Event Catering Handicap,Flat,622995,13,45571,45623
1004,2015-04-28,Newcastle,7:25,Ramside Hall Hotel Golf And Spa Handicap,Flat,622996,12,45609,45624
1005,2015-04-28,Newcastle,7:55,Bar Beyond In The Gate Handicap,Flat,622997,14,45534,45611
1006,2015-04-28,Newcastle,8:25,Northeast Oyster Festival On Tour Newcastle 20...,Flat,622998,8,45529,45540
1007,2015-05-13,Newcastle,2:20,ESH Group Maiden Stakes,Flat,624375,13,53554,53583
1008,2015-05-13,Newcastle,2:50,Close House Classified Stakes,Flat,624376,4,53561,53566
1009,2015-05-13,Newcastle,3:25,Complete Building Services Handicap,Flat,624377,15,53557,53616
1010,2015-05-13,Newcastle,3:55,Racing Together Claiming Stakes,Flat,624378,7,53601,53607
1011,2015-05-13,Newcastle,4:25,R F Henderson Handicap,Flat,624379,9,53592,53600
1012,2015-05-13,Newcastle,4:55,M&C Roofing Fillies Handicap,Flat,624380,5,53585,53591
1013,2015-05-13,Newcastle,5:25,White Horse Company Handicap (Div I),Flat,624381,11,53648,53800
1014,2015-05-13,Newcastle,6:00,White Horse Company Handicap (Div II),Flat,626971,13,53762,53774
1015,2015-05-19,Newcastle,2:20,Pin Point Recruitment Maiden Stakes,Flat,625066,7,57069,57075
1016,2015-05-19,Newcastle,2:50,Newcastle Flooring Fillies Handicap,Flat,625067,9,57060,57068
1017,2015-05-19,Newcastle,3:20,Collingwood Insurance Maiden Stakes,Flat,625068,9,56981,57087
1018,2015-05-19,Newcastle,3:50,J Barbour & Sons Handicap,Flat,625069,9,56982,56995
1019,2015-05-19,Newcastle,4:20,H Malone & Sons Handicap,Flat,625070,13,56969,56993
1020,2015-05-19,Newcastle,4:50,S V Rutter Handicap,Flat,625071,9,56996,57026
1021,2015-05-19,Newcastle,5:20,Marriott Gosforth Park Handicap (Div I),Flat,625072,9,57011,57019
1022,2015-05-19,Newcastle,5:50,Marriott Gosforth Park Handicap (Div II),Flat,627614,9,56997,57010
1023,2015-05-29,Newcastle,2:10,TSG-Leaders In IT Support/British Stallion Stu...,Flat,625917,10,61947,61956
1024,2015-05-29,Newcastle,2:40,Knight Frank Passionate About Property Maiden ...,Flat,625918,8,61847,61970
1025,2015-05-29,Newcastle,3:15,AIS Training Handicap,Flat,625919,10,61845,62136
1026,2015-05-29,Newcastle,3:45,Lafarge Tarmac Handicap,Flat,625920,11,61832,61862
1027,2015-05-29,Newcastle,4:20,obrienwaste.com Fillies Handicap,Flat,625921,8,61829,61843
1028,2015-05-29,Newcastle,4:55,Mitie Validus Handicap,Flat,625922,12,61838,61893
1029,2015-05-29,Newcastle,5:25,80th Anniversary of Newcastle International Ai...,Flat,625923,7,61890,61902
1030,2015-06-06,Newcastle,6:10,Get Horse Racing Odds At bookies.com EBF Maide...,Flat,626562,9,66393,66401
1031,2015-06-06,Newcastle,6:40,Compare Bookies Odds At bookies.com Handicap,Flat,626563,13,66353,66403
1032,2015-06-06,Newcastle,7:10,Compare Bookies At bookies.com Handicap,Flat,626564,9,66361,66369
1033,2015-06-06,Newcastle,7:40,Download The bookies.com App Handicap,Flat,626565,9,66370,66405
1034,2015-06-06,Newcastle,8:10,freebets.org For The Latest Free Bets Handicap,Flat,626566,16,66406,66458
1035,2015-06-06,Newcastle,8:40,Download The bookmakers.co.uk App Maiden Stakes,Flat,626567,7,66449,66455
1036,2015-06-06,Newcastle,9:10,Number Plates For Sale At uknumberplates.co.uk...,Flat,626568,6,66430,66457
1037,2015-06-25,Newcastle,2:10,Betfred Fun And Friendly Novice Stakes (Plus 1...,Flat,628440,6,75191,75196
1038,2015-06-25,Newcastle,2:45,Betfred TV Median Auction Maiden Stakes,Flat,628441,9,75181,75231
1039,2015-06-25,Newcastle,3:20,Betfred Seaton Delaval Handicap,Flat,628442,8,75260,75340
1040,2015-06-25,Newcastle,3:55,Betfred Six Best Odds Races Daily Handicap,Flat,628443,5,75329,75333
1041,2015-06-25,Newcastle,4:30,Betfred Supports Jack Berry House Handicap (Di...,Flat,628444,9,75320,75328
1042,2015-06-25,Newcastle,5:05,Betfred Supports Jack Berry House Handicap (Di...,Flat,630242,8,75344,75351
1043,2015-06-25,Newcastle,5:40,Betfred Racings Biggest Supporter Handicap,Flat,628445,10,75316,75366
1044,2015-06-25,Newcastle,6:15,Betfred Lotto Handicap,Flat,628446,12,75352,75363
1045,2015-06-26,Newcastle,6:10,Betfred Racings Biggest Supporter Maiden Stakes,Flat,628473,7,75703,75719
1046,2015-06-26,Newcastle,6:40,Betfred Racing Follow Us On Twitter Classified...,Flat,628474,6,75687,75702
1047,2015-06-26,Newcastle,7:15,Betfred TV/EBF Stallions Hoppings Stakes (),Flat,628475,11,75650,75701
1048,2015-06-26,Newcastle,7:45,Betfred Gosforth Park Cup (Handicap),Flat,628476,9,75595,75720
1049,2015-06-26,Newcastle,8:15,Betfred Still Treble Odds On Lucky15s Handicap,Flat,628477,8,75593,75608
1050,2015-06-26,Newcastle,8:45,Betfred Watch Freds Pushes On Betfred TV Handicap,Flat,628478,14,75579,75610
1051,2015-06-26,Newcastle,9:20,Betfred Supports Jack Berry House Handicap,Flat,628479,8,75587,75647
1052,2015-06-27,Newcastle,1:25,Betfred TV/Irish Stallion Farms EBF Maiden Sta...,Flat,628516,9,76171,76192
1053,2015-06-27,Newcastle,2:00,Betfred Chipchase Stakes,Flat,628517,8,76157,76164
1054,2015-06-27,Newcastle,2:35,Betfred Six Best Odds Races Daily Handicap,Flat,628518,15,76166,76220
1055,2015-06-27,Newcastle,3:10,Betfred Membership Play Your Way Handicap,Flat,628519,12,76221,76233
1056,2015-06-27,Newcastle,3:45,John Smiths Northumberland Plate (Heritage Han...,Flat,626433,19,76165,76314
1057,2015-06-27,Newcastle,4:20,Betfred Racing Like Us On Facebook Handicap,Flat,628520,9,76197,76224
1058,2015-06-27,Newcastle,4:55,Betfred Keep It Fun Handicap,Flat,628521,7,76195,76213
1059,2015-07-25,Newcastle,2:10,Collingwood Insurance Company Maiden Auction S...,Flat,630434,8,88530,88538
1060,2015-07-25,Newcastle,2:45,Collingwood Fleet Insurance Handicap,Flat,630435,5,88525,88529
1061,2015-07-25,Newcastle,3:20,Collingwood Learner Driver Insurance Beeswing ...,Flat,630436,7,88514,88537
1062,2015-07-25,Newcastle,3:55,Collingwood Young Driver Insurance Handicap,Flat,630437,7,88517,88553
1063,2015-07-25,Newcastle,4:30,Collingwood Taxi Insurance/ebfstallions.com Fi...,Flat,630438,5,88562,88566
1064,2015-07-25,Newcastle,5:05,Collingwood Short Term Learner Driver Insuranc...,Flat,630439,12,88539,88567
1065,2015-07-25,Newcastle,5:40,collingwood.gi Apprentice Handicap,Flat,630440,11,88541,88593
1066,2015-08-05,Newcastle,5:20,Equine Products UK Ltd Maiden Auction Stakes,Flat,631633,13,93926,93950
1067,2015-08-05,Newcastle,5:50,ESH Group Handicap,Flat,631634,8,93951,93958
1068,2015-08-05,Newcastle,6:20,Henderson Insurance Brokers Handicap,Flat,631635,7,93853,93960
1069,2015-08-05,Newcastle,6:50,DSE Northern Handicap,Flat,631636,7,93755,93888
1070,2015-08-05,Newcastle,7:20,North Sea Logistics Handicap,Flat,631637,3,93744,93760
1071,2015-08-05,Newcastle,7:50,Marriott Gosforth Park Fillies Handicap,Flat,631638,10,93746,93770
1072,2015-08-05,Newcastle,8:20,Straightline Construction Handicap,Flat,631639,8,93763,93778
1073,2015-08-06,Newcastle,5:30,bet365 Apprentice Handicap,Flat,631353,11,94267,94450
1074,2015-08-06,Newcastle,6:00,bet365 Nursery Handicap,Flat,631354,5,94088,94189
1075,2015-08-06,Newcastle,6:35,bet365 Median Auction Maiden Stakes,Flat,631355,12,94076,94093
1076,2015-08-06,Newcastle,7:10,Bingo At bet365 Handicap,Flat,631356,8,94068,94075
1077,2015-08-06,Newcastle,7:45,bet365.com Handicap,Flat,631357,12,94061,94115
1078,2015-08-06,Newcastle,8:15,Casino At bet365 Handicap,Flat,631358,9,94116,94268
1079,2015-08-06,Newcastle,8:45,bet365 Handicap,Flat,631359,6,94112,94127
1080,2015-08-14,Newcastle,2:00,STP Construction Nursery Handicap,Flat,631795,14,97350,97527
1081,2015-08-14,Newcastle,2:30,G.F.A. Gastech Ltd/Irish Stallion Studs EBF Ma...,Flat,631796,11,97511,97526
1082,2015-08-14,Newcastle,3:00,DSE Northern Handicap,Flat,631797,9,97502,97510
1083,2015-08-14,Newcastle,3:35,ESH Group Handicap,Flat,631798,4,97500,97528
1084,2015-08-14,Newcastle,4:10,North Sea Logistics Maiden Stakes,Flat,631799,8,97529,97555
1085,2015-08-14,Newcastle,4:40,H Malone & Sons Handicap,Flat,631800,5,97545,97549
1086,2015-08-14,Newcastle,5:10,Collingwood Insurance Handicap,Flat,631801,12,97533,97556
1087,2015-08-28,Newcastle,4:40,Mill Golden Anniversary Hands And Heels Appren...,Flat,632596,9,103568,103614
1088,2015-08-28,Newcastle,5:10,Swedish Pioneers Nursery Handicap,Flat,632597,7,103605,103615
1089,2015-08-28,Newcastle,5:45,Volvo Car Credit Torslanda Maiden Stakes,Flat,632598,5,103600,103604
1090,2015-08-28,Newcastle,6:15,Protector Group Handicap,Flat,632599,11,103591,103723
1091,2015-08-28,Newcastle,6:50,Supagard Cup Handicap,Flat,632600,12,103671,103748
1092,2015-08-28,Newcastle,7:20,Now Is The Time To Choose Volvo Handicap,Flat,632601,14,103726,103751
1093,2015-08-28,Newcastle,7:55,Mill Means Business Fillies Handicap,Flat,632602,8,103752,103776
1094,2015-08-31,Newcastle,12:45,vertem.co.uk/EBF Maiden Stakes (Plus 10 Race) ...,Flat,632945,8,105291,105299
1095,2015-08-31,Newcastle,1:15,vertem.co.uk/EBF Maiden Stakes (Plus 10 Race) ...,Flat,634320,8,105532,105539
1096,2015-08-31,Newcastle,1:50,Protecting Your Wealth Claiming Stakes,Flat,632946,8,105298,105354
1097,2015-08-31,Newcastle,2:25,#VertemAM Twitter Blaydon Race (A Nursery Hand...,Flat,632947,7,105342,105348
1098,2015-08-31,Newcastle,3:00,Perfect Partnerships Fillies Handicap,Flat,632948,6,105338,105353
1099,2015-08-31,Newcastle,3:35,Vertem Management Handicap,Flat,632949,5,105321,105337
1100,2015-08-31,Newcastle,4:10,Fresh Approach At Vertem Handicap,Flat,632950,9,105319,105335
1101,2015-08-31,Newcastle,4:40,Investing For The Future Handicap,Flat,632951,14,105331,105560
1102,2015-09-04,Newcastle,1:20,J.N. Bentley Ltd/British Stallion Studs EBF Ma...,Flat,633041,10,107034,107052
1103,2015-09-04,Newcastle,1:50,J.N. Bentley Ltd/British Stallion Studs EBF Ma...,Flat,634423,9,106962,106970
1104,2015-09-04,Newcastle,2:20,Fastflow Pipeline Services Ltd Maiden Stakes,Flat,633042,6,107028,107033
1105,2015-09-04,Newcastle,2:50,Gowland & Dawson Handicap,Flat,633043,15,106950,107037
1106,2015-09-04,Newcastle,3:25,Stonbury Maiden Stakes,Flat,633044,6,106944,106949
1107,2015-09-04,Newcastle,4:00,ESH Construction Handicap,Flat,633045,10,106934,106943
1108,2015-09-04,Newcastle,4:30,Northumbrian Water Handicap,Flat,633046,11,106928,106988
1109,2015-09-04,Newcastle,5:00,WaterAid Handicap,Flat,633047,16,106971,106989
1110,2025-11-15,Newcastle,05:05,NZB 3yo Spring Stakes (Turf),Flat,908281,11,1766003,1766013
1111,2025-11-15,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,908282,16,1766014,1766029
1112,2026-03-06,Newcastle,05:55,Horsepower Newcastle Stakes (Handicap) (Turf),Flat,914933,10,1810567,1810576
1113,2023-06-26,Southwell,3:00,Prestige Safety e-learning @ prestigesafetyser...,Flat,842254,6,1361686,1361691

In [26]:
# Inspect the ambiguous unsuffixed Newcastle and exceptional Southwell Flat
# records at runner grain.
#
# Newcastle:
# - pre-October-2025 unsuffixed Flat records may be historic British turf;
# - post-October-2025 unsuffixed Flat records may represent Newcastle (AUS)
#   after jurisdiction suffixes were removed.
#
# Southwell:
# - one unsuffixed Flat race appears in 2023 despite the separate
#   "Southwell (AW)" representation.
#
# This cell displays fields that may provide jurisdiction, surface, meeting,
# or transferred-race evidence. No correction is applied.

ambiguous_flat_rows_sql = f"""
SELECT
    rowid AS source_rowid,
    date,
    race_id,
    course,
    off,
    race_name,
    type,
    ran,
    horse,
    jockey,
    trainer,
    draw,
    pos,
    time,
    comment
FROM {SOURCE_TABLE}
WHERE {DATA_ROW_PREDICATE}
  AND type = 'Flat'
  AND (
        (course = 'Newcastle' AND date >= '2025-10-15')
        OR
        (course = 'Southwell')
      )
ORDER BY
    date,
    course,
    off,
    source_rowid
"""

ambiguous_flat_rows = pd.read_sql_query(
    ambiguous_flat_rows_sql,
    connection,
)

print(f"Runner rows inspected: {len(ambiguous_flat_rows):,}")
print()
print("Provisional races:")
display(
    ambiguous_flat_rows[
        ["date", "course", "off", "race_name", "race_id", "ran"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

ambiguous_flat_rows

Runner rows inspected: 43

Provisional races:

,date,course,off,race_name,race_id,ran
0,2023-06-26,Southwell,3:00,Prestige Safety e-learning @ prestigesafetyser...,842254,6
1,2025-11-15,Newcastle,05:05,NZB 3yo Spring Stakes (Turf),908281,11
2,2025-11-15,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,908282,16
3,2026-03-06,Newcastle,05:55,Horsepower Newcastle Stakes (Handicap) (Turf),914933,10

,source_rowid,date,race_id,course,off,race_name,type,ran,horse,jockey,trainer,draw,pos,time,comment
0,1361686,2023-06-26,842254,Southwell,3:00,Prestige Safety e-learning @ prestigesafetyser...,Flat,6,Jenner Park (IRE),Miss Eleanor Williams,Evan Williams,,6,3:57.17,Took keen hold - raced wide early - led - head...
1,1361687,2023-06-26,842254,Southwell,3:00,Prestige Safety e-learning @ prestigesafetyser...,Flat,6,Upbeat Betty (GB),Isabel Williams,Evan Williams,,5,3:56.17,Towards rear - headway on outer 5f out - weake...
2,1361688,2023-06-26,842254,Southwell,3:00,Prestige Safety e-learning @ prestigesafetyser...,Flat,6,Happy Friend (IRE),Tom Cannon,Karen Jewell,,4,3:55.77,Prominent - outpaced 4f out - dropped to rear ...
3,1361689,2023-06-26,842254,Southwell,3:00,Prestige Safety e-learning @ prestigesafetyser...,Flat,6,Gladys Eva Jane (GB),Sean Bowen,Peter Bowen,,3,3:54.69,In touch with leaders - headway and pressed le...
4,1361690,2023-06-26,842254,Southwell,3:00,Prestige Safety e-learning @ prestigesafetyser...,Flat,6,Riccirella (GB),Charlie Todd,Michael Dods,,2,3:54.67,Held up in rear - going easily but waiting for...
5,1361691,2023-06-26,842254,Southwell,3:00,Prestige Safety e-learning @ prestigesafetyser...,Flat,6,Cast A Spell (IRE),Jamie Moore,Gary Moore,,1,3:54.32,Raced in second - led 5f out - pushed along 3f...
6,1766003,2025-11-15,908281,Newcastle,05:05,NZB 3yo Spring Stakes (Turf),Flat,11,Green Spaces (AUS),Rachel King,Bjorn Baker,1,1,1:36.00,Dwelt at start - settled in midfield on inner ...
7,1766004,2025-11-15,908281,Newcastle,05:05,NZB 3yo Spring Stakes (Turf),Flat,11,Bird Whistle (AUS),Braith Nock,Brett & Georgie Cavanough,4,2,1:36.50,
8,1766005,2025-11-15,908281,Newcastle,05:05,NZB 3yo Spring Stakes (Turf),Flat,11,Long Legs (AUS),Tyler Schiller,Gary Portelli,10,3,1:36.58,
9,1766006,2025-11-15,908281,Newcastle,05:05,NZB 3yo Spring Stakes (Turf),Flat,11,Grand Prairie (AUS),Thomas Sherry,Peter Snowden,2,4,1:36.88,
10,1766007,2025-11-15,908281,Newcastle,05:05,NZB 3yo Spring Stakes (Turf),Flat,11,Probability Theory (AUS),Zac Lloyd,Nacim Dilmi,9,5,1:36.89,
11,1766008,2025-11-15,908281,Newcastle,05:05,NZB 3yo Spring Stakes (Turf),Flat,11,Ratify (NZ),Molly Bourke,John Sargent,7,6,1:37.04,
12,1766009,2025-11-15,908281,Newcastle,05:05,NZB 3yo Spring Stakes (Turf),Flat,11,Verity (AUS),Ashley Morgan,Paul Messara & Leah Gavranich,11,7,1:37.42,
13,1766010,2025-11-15,908281,Newcastle,05:05,NZB 3yo Spring Stakes (Turf),Flat,11,Rosa Incanta (NZ),Timothy Clark,Gai Waterhouse & Adrian Bott,5,8,1:37.54,
14,1766011,2025-11-15,908281,Newcastle,05:05,NZB 3yo Spring Stakes (Turf),Flat,11,Ghayoor (AUS),Kacie Adams,Darren Treacy,6,9,1:38.17,
15,1766012,2025-11-15,908281,Newcastle,05:05,NZB 3yo Spring Stakes (Turf),Flat,11,Hetzendorf (AUS),Tommy Berry,Michael Freedman,3,10,1:38.42,Broke well - chased leading pair on inner - ri...
16,1766013,2025-11-15,908281,Newcastle,05:05,NZB 3yo Spring Stakes (Turf),Flat,11,Pinot Nero (AUS),Dylan Gibbons,John W Ramsey,8,11,1:43.12,
17,1766014,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Coal Crusher (AUS),Chad Schofield,Joseph Pride,4,1,1:16.08,
18,1766015,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Accredited (AUS),Andrew Adkins,Joseph Pride,3,2,1:16.20,
19,1766016,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Brudenell (AUS),Timothy Clark,Kris Lees,1,3,1:16.25,
20,1766017,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Clear Thinking (GB),Tyler Schiller,Paul Messara & Leah Gavranich,9,4,1:16.25,
21,1766018,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Cifrado (AUS),Alysha Collett,Rex Lipp,11,5,1:16.37,
22,1766019,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Estadio Mestalla (IRE),Adam Hyeronimus,Joseph Pride,16,6,1:16.45,
23,1766020,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Robusto (AUS),Joshua Parr,Bjorn Baker,2,7,1:16.54,
24,1766021,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Infancy (AUS),Dylan Gibbons,Kris Lees,15,8,1:16.62,
25,1766022,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Airman (AUS),Tommy Berry,Michael Wayne & John Hawkes,8,9,1:16.70,
26,1766023,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Phearson (AUS),Thomas Sherry,Brad Widdup,13,10,1:16.83,
27,1766024,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Darnation (IRE),Reece Jones,Ciaron Maher,14,11,1:16.95,
28,1766025,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Golden Mile (AUS),Jean Van Overmeire,Joseph Pride,6,12,1:17.08,Broke well - tracked leader on outer - ridden ...
29,1766026,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Felix Majestic (AUS),Molly Bourke,Gary Nickson,7,13,1:17.25,
30,1766027,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Konasana (AUS),Kerrin McEvoy,Chris Waller,5,14,1:17.29,
31,1766028,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Ostraka (AUS),Jason Collett,Annabel & Rob Archibald,10,15,1:17.30,
32,1766029,2025-11-15,908282,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) ...,Flat,16,Yorkshire (AUS),Zac Lloyd,John OShea & Tom Charlton,12,16,1:18.08,
33,1810567,2026-03-06,914933,Newcastle,05:55,Horsepower Newcastle Stakes (Handicap) (Turf),Flat,10,Tuileries (AUS),Chad Schofield,Peter Snowden,9,1,1:22.77,
34,1810568,2026-03-06,914933,Newcastle,05:55,Horsepower Newcastle Stakes (Handicap) (Turf),Flat,10,Churchills Choice (AUS),Ashley Morgan,Nathan Doyle,6,2,1:22.84,
35,1810569,2026-03-06,914933,Newcastle,05:55,Horsepower Newcastle Stakes (Handicap) (Turf),Flat,10,Melody Again (AUS),Winona Costin,Scott Singleton,10,3,1:22.94,
36,1810570,2026-03-06,914933,Newcastle,05:55,Horsepower Newcastle Stakes (Handicap) (Turf),Flat,10,Just Feelin Lucky (AUS),Rachel King,Michael Freedman,2,4,1:23.06,
37,1810571,2026-03-06,914933,Newcastle,05:55,Horsepower Newcastle Stakes (Handicap) (Turf),Flat,10,Imposant (AUS),Tyler Schiller,Kris Lees,8,5,1:23.35,
38,1810572,2026-03-06,914933,Newcastle,05:55,Horsepower Newcastle Stakes (Handicap) (Turf),Flat,10,Coal Crusher (AUS),Adam Hyeronimus,Joseph Pride,1,6,1:23.39,
39,1810573,2026-03-06,914933,Newcastle,05:55,Horsepower Newcastle Stakes (Handicap) (Turf),Flat,10,West Of Africa (AUS),Thomas Sherry,Annabel & Rob Archibald,7,7,1:23.44,
40,1810574,2026-03-06,914933,Newcastle,05:55,Horsepower Newcastle Stakes (Handicap) (Turf),Flat,10,Getafix (AUS),Zac Lloyd,John OShea & Tom Charlton,5,8,1:23.56,
41,1810575,2026-03-06,914933,Newcastle,05:55,Horsepower Newcastle Stakes (Handicap) (Turf),Flat,10,Show Em Howl (AUS),Anna Roper,Robert Agnew,4,9,1:23.85,
42,1810576,2026-03-06,914933,Newcastle,05:55,Horsepower Newcastle Stakes (Handicap) (Turf),Flat,10,Berkshire Shadow (GB),Alysha Collett,Kim Waugh,3,10,1:25.31,

In [27]:
# Compare the exceptional Southwell Flat race with other races from the same
# meeting and with the same race name elsewhere in the source.
#
# The aim is to determine whether:
# - the meeting contains normal jumps or NH Flat races;
# - the same named race appears elsewhere with a different raw type;
# - the exceptional record is likely a source classification anomaly.
#
# This cell preserves all raw source values and does not correct the record.

southwell_exception_context_sql = f"""
WITH target_race AS (
    SELECT DISTINCT
        date,
        course,
        off,
        race_name
    FROM {SOURCE_TABLE}
    WHERE {DATA_ROW_PREDICATE}
      AND date = '2023-06-26'
      AND course = 'Southwell'
      AND off = '3:00'
),
same_meeting AS (
    SELECT
        'same_meeting' AS comparison_group,
        date,
        course,
        off,
        race_name,
        type,
        race_id,
        COUNT(*) AS runner_rows,
        COUNT(DISTINCT draw) AS distinct_draw_values,
        MIN(time) AS minimum_raw_time,
        MAX(time) AS maximum_raw_time
    FROM {SOURCE_TABLE}
    WHERE {DATA_ROW_PREDICATE}
      AND date = '2023-06-26'
      AND course = 'Southwell'
    GROUP BY
        date,
        course,
        off,
        race_name,
        type,
        race_id
),
same_race_name AS (
    SELECT
        'same_race_name' AS comparison_group,
        date,
        course,
        off,
        race_name,
        type,
        race_id,
        COUNT(*) AS runner_rows,
        COUNT(DISTINCT draw) AS distinct_draw_values,
        MIN(time) AS minimum_raw_time,
        MAX(time) AS maximum_raw_time
    FROM {SOURCE_TABLE}
    WHERE {DATA_ROW_PREDICATE}
      AND race_name = (
          SELECT race_name
          FROM target_race
          LIMIT 1
      )
    GROUP BY
        date,
        course,
        off,
        race_name,
        type,
        race_id
)
SELECT *
FROM same_meeting

UNION ALL

SELECT *
FROM same_race_name

ORDER BY
    comparison_group,
    date,
    course,
    off
"""

southwell_exception_context = pd.read_sql_query(
    southwell_exception_context_sql,
    connection,
)

print(
    "Context rows returned: "
    f"{len(southwell_exception_context):,}"
)

southwell_exception_context

Context rows returned: 8

,comparison_group,date,course,off,race_name,type,race_id,runner_rows,distinct_draw_values,minimum_raw_time,maximum_raw_time
0,same_meeting,2023-06-26,Southwell,1:55,Prestige Safety First Aid Training Handicap Chase,Chase,842248,6,1,-,5:9.25
1,same_meeting,2023-06-26,Southwell,2:25,Prestige Safety Your Trusted Safety Partner Ha...,Chase,842253,5,1,-,4:3.07
2,same_meeting,2023-06-26,Southwell,3:00,Prestige Safety e-learning @ prestigesafetyser...,Flat,842254,6,1,3:54.32,3:57.17
3,same_meeting,2023-06-26,Southwell,3:30,Prestige Safety Fire Risk Assessments Novices ...,Hurdle,842252,6,1,3:50.46,3:57.36
4,same_meeting,2023-06-26,Southwell,4:00,Prestige Safety Construction Safety Specialist...,Hurdle,842251,5,1,-,3:59.97
5,same_meeting,2023-06-26,Southwell,4:30,Prestige Safety Your Competent H&S Specialist ...,Hurdle,842249,7,1,-,6:7.76
6,same_meeting,2023-06-26,Southwell,5:00,Prestige Safety Services PPE And Workwear Cond...,Hurdle,842250,9,1,-,5:7.65
7,same_race_name,2023-06-26,Southwell,3:00,Prestige Safety e-learning @ prestigesafetyser...,Flat,842254,6,1,3:54.32,3:57.17

In [28]:
# Inspect the full descriptive fields for the exceptional Southwell race.
#
# The notebook display truncated the race name, and the meeting-level evidence
# suggests this may be a National Hunt Flat race recorded as type = "Flat".
#
# This cell retrieves one representative source row and preserves the exact
# raw values for fields that may clarify the race discipline:
# - full race name;
# - distance;
# - age and class conditions;
# - going;
# - weight and draw representation.
#
# No source value is corrected.

southwell_exception_description_sql = f"""
SELECT
    rowid AS source_rowid,
    date,
    course,
    off,
    race_name,
    type,
    dist,
    age,
    class,
    going,
    ran,
    draw,
    wgt,
    horse,
    jockey,
    trainer,
    time
FROM {SOURCE_TABLE}
WHERE {DATA_ROW_PREDICATE}
  AND date = '2023-06-26'
  AND course = 'Southwell'
  AND off = '3:00'
ORDER BY rowid
LIMIT 1
"""

southwell_exception_description = pd.read_sql_query(
    southwell_exception_description_sql,
    connection,
)

record = southwell_exception_description.iloc[0]

for field, value in record.items():
    print(f"{field}: {value}")

source_rowid: 1361686
date: 2023-06-26
course: Southwell
off: 3:00
race_name: Prestige Safety e-learning @ prestigesafetyservices.com Mares Open NHF Race (Cat 1 Elim) (GBB)
type: Flat
dist: 2m
age: 4
class: Class 5
going: Good
ran: 6
draw:
wgt: 10-4
horse: Jenner Park (IRE)
jockey: Miss Eleanor Williams
trainer: Evan Williams
time: 3:57.17

In [29]:
# Test source-wide consistency between explicit NH Flat wording in race_name
# and the raw type field.
#
# The Southwell exception contains "NHF Race" in race_name but type = "Flat".
# This cell searches provisional races for common explicit National Hunt Flat
# wording and compares it with the recorded type.
#
# Search terms are deliberately narrow:
# - NHF
# - National Hunt Flat
# - Bumper
#
# This is anomaly detection, not a complete NH Flat classifier. Some genuine
# NH Flat races may not contain any of these terms.

nh_flat_wording_pattern = (
    r"\bNHF\b"
    r"|National Hunt Flat"
    r"|\bBumper\b"
)

explicit_nh_flat_races = provisional_race_names.loc[
    provisional_race_names["race_name"].str.contains(
        nh_flat_wording_pattern,
        case=False,
        regex=True,
        na=False,
    )
].copy()

explicit_nh_flat_type_summary = (
    explicit_nh_flat_races
    .groupby("type", as_index=False)
    .agg(
        provisional_races=("race_name", "size"),
        distinct_raw_courses=("course", "nunique"),
        distinct_race_names=("race_name", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
    .sort_values(
        ["provisional_races", "type"],
        ascending=[False, True],
    )
    .reset_index(drop=True)
)

explicit_nh_flat_mismatches = (
    explicit_nh_flat_races.loc[
        explicit_nh_flat_races["type"] != "NH Flat"
    ]
    .sort_values(
        ["date", "course", "off", "race_name"]
    )
    .reset_index(drop=True)
)

print(
    "Provisional races with explicit NH Flat wording: "
    f"{len(explicit_nh_flat_races):,}"
)
print(
    "Those not recorded as type = 'NH Flat': "
    f"{len(explicit_nh_flat_mismatches):,}"
)

display(explicit_nh_flat_type_summary)
explicit_nh_flat_mismatches

Provisional races with explicit NH Flat wording: 3,036
Those not recorded as type = 'NH Flat': 17

,type,provisional_races,distinct_raw_courses,distinct_race_names,first_date,last_date
0,NH Flat,3019,53,2492,2015-01-01,2026-05-26
1,Flat,14,4,7,2016-04-26,2025-04-29
2,Chase,2,2,2,2022-04-03,2025-11-11
3,Hurdle,1,1,1,2024-02-24,2024-02-24

,date,course,off,race_name,type,parenthetical_pattern
0,2016-04-26,Punchestown (IRE),6:05,Goffs Land Rover Bumper INH Flat,Flat,[none]
1,2017-04-25,Punchestown (IRE),6:05,Goffs Land Rover Bumper,Flat,[none]
2,2018-04-24,Punchestown (IRE),6:05,Goffs Land Rover Bumper,Flat,[none]
3,2018-06-08,Stratford,9:00,Irish Thoroughbred Marketing Champion Point-To...,Flat,(A Standard NHF Race) (Amateur Riders)
4,2019-04-30,Punchestown (IRE),6:05,Goffs Land Rover Bumper,Flat,[none]
5,2019-05-31,Stratford,8:50,Irish Thoroughbred Marketing Champion Point-To...,Flat,(A Standard NHF Race) (Amateur Riders)
6,2021-04-27,Punchestown (IRE),5:55,Goffs Land Rover Bumper,Flat,[none]
7,2021-05-28,Stratford,8:40,Irish Thoroughbred Marketing Champion Point-To...,Flat,(Standard NHF Race) (GBB Race)
8,2022-04-03,Fairyhouse (IRE),2:55,Book Your Bumper Bundle For Easter Handicap Chase,Chase,[none]
9,2022-04-26,Punchestown (IRE),6:00,Goffs Land Rover Bumper,Flat,[none]
10,2023-04-25,Punchestown (IRE),6:00,Goffs Defender Bumper,Flat,[none]
11,2023-06-26,Southwell,3:00,Prestige Safety e-learning @ prestigesafetyser...,Flat,(Cat 1 Elim) (GBB)
12,2023-08-06,Market Rasen,5:22,Streets Chartered Accountants & Streets Bloods...,Flat,(Rider Restricted) (C1) (GBB)
13,2024-02-24,Fairyhouse (IRE),3:15,Fairyhouse Bumper Bundle For Easter Handicap H...,Hurdle,[none]
14,2024-04-30,Punchestown (IRE),4:50,Goffs Defender Bumper,Flat,[none]
15,2025-04-29,Punchestown (IRE),5:25,Goffs Defender Bumper,Flat,[none]
16,2025-11-11,Huntingdon,15:46,Book Now For The Peterborough Chase Fillies Ju...,Chase,(Cat 1 Elim) (GBB)

In [30]:
# Inspect the 17 explicit-NH-Flat wording mismatches with fuller race context.
#
# This cell retrieves one representative row per provisional race and includes:
# - the complete race name;
# - recorded type;
# - distance, class, age and going;
# - draw availability;
# - winning time;
# - runner count.
#
# The purpose is to separate:
# - genuine discipline misclassifications;
# - source conventions where Irish bumpers are recorded as Flat;
# - keyword false positives such as "Bumper Bundle".
#
# No correction is applied.

nh_flat_mismatch_context_sql = f"""
WITH mismatch_races AS (
    SELECT
        date,
        course,
        off,
        race_name,
        type
    FROM {SOURCE_TABLE}
    WHERE {DATA_ROW_PREDICATE}
      AND (
            LOWER(race_name) LIKE '%nhf%'
            OR LOWER(race_name) LIKE '%national hunt flat%'
            OR LOWER(race_name) LIKE '%bumper%'
          )
      AND type <> 'NH Flat'
    GROUP BY
        date,
        course,
        off,
        race_name,
        type
),
ranked_rows AS (
    SELECT
        d.rowid AS source_rowid,
        d.date,
        d.course,
        d.off,
        d.race_name,
        d.type,
        d.dist,
        d.age,
        d.class,
        d.going,
        d.draw,
        d.ran,
        d.time,
        d.horse,
        ROW_NUMBER() OVER (
            PARTITION BY
                d.date,
                d.course,
                d.off,
                d.race_name,
                d.type
            ORDER BY
                CASE
                    WHEN d.pos = '1' THEN 0
                    ELSE 1
                END,
                d.rowid
        ) AS row_rank
    FROM {SOURCE_TABLE} AS d
    JOIN mismatch_races AS m
        ON m.date = d.date
       AND m.course = d.course
       AND m.off = d.off
       AND m.race_name = d.race_name
       AND m.type = d.type
    WHERE {DATA_ROW_PREDICATE}
)
SELECT
    source_rowid,
    date,
    course,
    off,
    race_name,
    type,
    dist,
    age,
    class,
    going,
    draw,
    ran,
    time,
    horse
FROM ranked_rows
WHERE row_rank = 1
ORDER BY
    date,
    course,
    off
"""

nh_flat_mismatch_context = pd.read_sql_query(
    nh_flat_mismatch_context_sql,
    connection,
)

print(
    "Mismatch races inspected: "
    f"{len(nh_flat_mismatch_context):,}"
)

pd.set_option("display.max_colwidth", None)
nh_flat_mismatch_context

Mismatch races inspected: 18

,source_rowid,date,course,off,race_name,type,dist,age,class,going,draw,ran,time,horse
0,197719,2016-04-26,Punchestown (IRE),6:05,Goffs Land Rover Bumper INH Flat,Flat,2m,4,,Good To Yielding,,16,4:2.90,Coeur De Lion (FR)
1,361159,2017-04-25,Punchestown (IRE),6:05,Goffs Land Rover Bumper,Flat,2m,4,,Good To Yielding,,16,3:54.50,Vision Des Flos (FR)
2,525523,2018-04-24,Punchestown (IRE),6:05,Goffs Land Rover Bumper,Flat,2m½f,4,,Yielding To Soft,,16,4:18.40,Commander Of Fleet (IRE)
3,551769,2018-06-08,Stratford,9:00,Irish Thoroughbred Marketing Champion Point-To-Point Bumper (A Standard NHF Race) (Amateur Riders),Flat,2m½f,4,Class 4,Good,,9,3:56.60,Lily The Pink (GB)
4,704862,2019-04-30,Punchestown (IRE),6:05,Goffs Land Rover Bumper,Flat,2m½f,4,,Yielding,,19,4:3.40,Festival Dex (FR)
5,722825,2019-05-31,Stratford,8:50,Irish Thoroughbred Marketing Champion Point-To-Point Bumper (A Standard NHF Race) (Amateur Riders),Flat,2m½f,6,Class 4,Good,,13,4:1.80,Love Around (GB)
6,1000892,2021-04-27,Punchestown (IRE),5:55,Goffs Land Rover Bumper,Flat,2m½f,4,,Yielding,,22,4:6.00,Adamantly Chosen (IRE)
7,1017876,2021-05-28,Stratford,8:40,Irish Thoroughbred Marketing Champion Point-To-Point Bumper (Standard NHF Race) (GBB Race),Flat,2m½f,5,Class 4,Good,,5,4:14.20,Fountains Chief (GB)
8,1162684,2022-04-03,Fairyhouse (IRE),2:55,Book Your Bumper Bundle For Easter Handicap Chase,Chase,2m5½f,7,,Yielding,,13,5:35.90,Song Of Earth (IRE)
9,1174283,2022-04-26,Punchestown (IRE),6:00,Goffs Land Rover Bumper,Flat,2m½f,4,,Good To Yielding,,15,4:2.00,Absolute Notions (IRE)
10,1288484,2022-12-21,Lingfield (AW),12:30,Download The At The Races App Mares Open Maiden NHFlat Race (Category 3 Elimination) (GBB Race),Flat,2m,4,Class 5,Standard To Slow,,9,3:44.20,Kay Tara Tara (GB)
11,1329534,2023-04-25,Punchestown (IRE),6:00,Goffs Defender Bumper,Flat,2m½f,4,,Yielding To Soft,,16,4:5.60,Predators Gold (FR)
12,1361691,2023-06-26,Southwell,3:00,Prestige Safety e-learning @ prestigesafetyservices.com Mares Open NHF Race (Cat 1 Elim) (GBB),Flat,2m,5,Class 5,Good,,6,3:54.32,Cast A Spell (IRE)
13,1380057,2023-08-06,Market Rasen,5:22,Streets Chartered Accountants & Streets Bloodstock Mares Open NHF Race (Rider Restricted)(C1)(GBB),Flat,2m½f,4,Class 5,Good To Soft,,5,4:19.69,One Colour (IRE)
14,1469027,2024-02-24,Fairyhouse (IRE),3:15,Fairyhouse Bumper Bundle For Easter Handicap Hurdle,Hurdle,2m4½f,5,,Heavy,,10,6:8.30,Jouster (FR)
15,1497465,2024-04-30,Punchestown (IRE),4:50,Goffs Defender Bumper,Flat,2m½f,4,,Yielding,,25,4:12.70,Sermandzarak (FR)
16,1668207,2025-04-29,Punchestown (IRE),5:25,Goffs Defender Bumper,Flat,2m½f,4,,Yielding,,18,4:3.50,Wonderful Everyday (IRE)
17,1764624,2025-11-11,Huntingdon,15:46,Book Now For The Peterborough Chase Fillies Junior National Hunt Flat Race (Cat 1 Elim) (GBB),Chase,2m,3,Class 5,Good,,8,3:52.95,Laysoft (IRE)

In [31]:
# Create a narrower explicit NH Flat anomaly test.
#
# The previous search produced false positives where "Bumper" appeared only
# in promotional wording such as "Bumper Bundle".
#
# This stronger diagnostic accepts:
# - NHF;
# - NHFlat;
# - National Hunt Flat;
# - INH Flat;
# - race names ending in or explicitly describing a Bumper;
#
# It excludes the known promotional phrase "Bumper Bundle".
#
# The result remains a candidate anomaly set. It does not overwrite raw type.

strong_nh_flat_pattern = (
    r"\bNHF\b"
    r"|\bNHFlat\b"
    r"|National Hunt Flat"
    r"|\bINH Flat\b"
    r"|\bBumper\b"
)

strong_explicit_nh_flat_races = provisional_race_names.loc[
    provisional_race_names["race_name"].str.contains(
        strong_nh_flat_pattern,
        case=False,
        regex=True,
        na=False,
    )
    &
    ~provisional_race_names["race_name"].str.contains(
        r"Bumper Bundle",
        case=False,
        regex=True,
        na=False,
    )
].copy()

strong_nh_flat_type_summary = (
    strong_explicit_nh_flat_races
    .groupby("type", as_index=False)
    .agg(
        provisional_races=("race_name", "size"),
        distinct_raw_courses=("course", "nunique"),
        distinct_race_names=("race_name", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
    .sort_values(
        ["provisional_races", "type"],
        ascending=[False, True],
    )
    .reset_index(drop=True)
)

strong_nh_flat_mismatches = (
    strong_explicit_nh_flat_races.loc[
        strong_explicit_nh_flat_races["type"] != "NH Flat"
    ]
    .sort_values(
        ["date", "course", "off", "race_name"]
    )
    .reset_index(drop=True)
)

print(
    "Provisional races with strong explicit NH Flat wording: "
    f"{len(strong_explicit_nh_flat_races):,}"
)
print(
    "Strong explicit NH Flat races not recorded as type = 'NH Flat': "
    f"{len(strong_nh_flat_mismatches):,}"
)

display(strong_nh_flat_type_summary)
strong_nh_flat_mismatches

Provisional races with strong explicit NH Flat wording: 4,437
Strong explicit NH Flat races not recorded as type = 'NH Flat': 16

,type,provisional_races,distinct_raw_courses,distinct_race_names,first_date,last_date
0,NH Flat,4421,92,3287,2015-01-01,2026-05-27
1,Flat,15,5,8,2016-04-26,2025-04-29
2,Chase,1,1,1,2025-11-11,2025-11-11

,date,course,off,race_name,type,parenthetical_pattern
0,2016-04-26,Punchestown (IRE),6:05,Goffs Land Rover Bumper INH Flat,Flat,[none]
1,2017-04-25,Punchestown (IRE),6:05,Goffs Land Rover Bumper,Flat,[none]
2,2018-04-24,Punchestown (IRE),6:05,Goffs Land Rover Bumper,Flat,[none]
3,2018-06-08,Stratford,9:00,Irish Thoroughbred Marketing Champion Point-To-Point Bumper (A Standard NHF Race) (Amateur Riders),Flat,(A Standard NHF Race) (Amateur Riders)
4,2019-04-30,Punchestown (IRE),6:05,Goffs Land Rover Bumper,Flat,[none]
5,2019-05-31,Stratford,8:50,Irish Thoroughbred Marketing Champion Point-To-Point Bumper (A Standard NHF Race) (Amateur Riders),Flat,(A Standard NHF Race) (Amateur Riders)
6,2021-04-27,Punchestown (IRE),5:55,Goffs Land Rover Bumper,Flat,[none]
7,2021-05-28,Stratford,8:40,Irish Thoroughbred Marketing Champion Point-To-Point Bumper (Standard NHF Race) (GBB Race),Flat,(Standard NHF Race) (GBB Race)
8,2022-04-26,Punchestown (IRE),6:00,Goffs Land Rover Bumper,Flat,[none]
9,2022-12-21,Lingfield (AW),12:30,Download The At The Races App Mares Open Maiden NHFlat Race (Category 3 Elimination) (GBB Race),Flat,(Category 3 Elimination) (GBB Race)
10,2023-04-25,Punchestown (IRE),6:00,Goffs Defender Bumper,Flat,[none]
11,2023-06-26,Southwell,3:00,Prestige Safety e-learning @ prestigesafetyservices.com Mares Open NHF Race (Cat 1 Elim) (GBB),Flat,(Cat 1 Elim) (GBB)
12,2023-08-06,Market Rasen,5:22,Streets Chartered Accountants & Streets Bloodstock Mares Open NHF Race (Rider Restricted)(C1)(GBB),Flat,(Rider Restricted) (C1) (GBB)
13,2024-04-30,Punchestown (IRE),4:50,Goffs Defender Bumper,Flat,[none]
14,2025-04-29,Punchestown (IRE),5:25,Goffs Defender Bumper,Flat,[none]
15,2025-11-11,Huntingdon,15:46,Book Now For The Peterborough Chase Fillies Junior National Hunt Flat Race (Cat 1 Elim) (GBB),Chase,(Cat 1 Elim) (GBB)

In [32]:
# Measure provisional race-level jurisdiction coverage using only the
# evidence established in this notebook.
#
# Evidence sources:
#
# 1. Recognised terminal jurisdiction code in raw course:
#    e.g. "(IRE)", "(FR)", "(AUS)".
#
# 2. Historical suffix linkage for later unsuffixed international forms:
#    e.g. "Chantilly" linked to earlier "Chantilly (FR)".
#
# 3. The established longstanding unsuffixed British-course inventory.
#
# Important exceptions:
# - Ascot, Sandown and Newcastle have cross-jurisdiction name collisions.
# - Unsuffixed Newcastle changes meaning by race context and date.
# - Firenze has no direct jurisdiction evidence.
#
# For this diagnostic, ambiguous collision names remain unresolved rather
# than being forced into one jurisdiction.

terminal_code_to_jurisdiction = {
    "ARG": "Argentina",
    "AUS": "Australia",
    "BEL": "Belgium",
    "BHR": "Bahrain",
    "BRZ": "Brazil",
    "CAN": "Canada",
    "CHI": "Chile",
    "CHN": "China",
    "CZE": "Czech Republic",
    "DEN": "Denmark",
    "FR": "France",
    "GER": "Germany",
    "GUE": "Guernsey",
    "HK": "Hong Kong",
    "HUN": "Hungary",
    "IRE": "Ireland",
    "ITY": "Italy",
    "JER": "Jersey",
    "JPN": "Japan",
    "KOR": "South Korea",
    "KSA": "Saudi Arabia",
    "NOR": "Norway",
    "NZ": "New Zealand",
    "PER": "Peru",
    "POL": "Poland",
    "QA": "Qatar",
    "SAF": "South Africa",
    "SIN": "Singapore",
    "SPA": "Spain",
    "SWE": "Sweden",
    "SWI": "Switzerland",
    "TUR": "Turkey",
    "UAE": "United Arab Emirates",
    "URU": "Uruguay",
    "USA": "United States",
}

historical_course_to_code = dict(
    zip(
        historical_jurisdiction_links["later_raw_course"],
        historical_jurisdiction_links["historical_jurisdiction_code"],
    )
)

known_cross_jurisdiction_collision_names = {
    "Ascot",
    "Sandown",
    "Newcastle",
}

def derive_provisional_jurisdiction(course_name):
    """
    Derive jurisdiction and evidence source conservatively.

    Ambiguous unsuffixed collision names are deliberately left unresolved.
    """
    course_name = str(course_name)

    terminal_code = extract_terminal_jurisdiction_code(course_name)

    if terminal_code is not None:
        return pd.Series(
            [
                terminal_code_to_jurisdiction[terminal_code],
                "explicit_terminal_course_code",
            ]
        )

    if course_name in known_cross_jurisdiction_collision_names:
        return pd.Series(
            [
                "unresolved",
                "cross_jurisdiction_course_name_collision",
            ]
        )

    if course_name in historical_course_to_code:
        historical_code = historical_course_to_code[course_name]

        return pd.Series(
            [
                terminal_code_to_jurisdiction[historical_code],
                "historical_suffixed_course_link",
            ]
        )

    if course_name in established_unsuffixed_british_courses:
        return pd.Series(
            [
                "Great Britain",
                "established_unsuffixed_british_course",
            ]
        )

    return pd.Series(
        [
            "unresolved",
            "no_established_jurisdiction_evidence",
        ]
    )


jurisdiction_evidence = provisional_race_names.copy()

jurisdiction_evidence[
    ["provisional_jurisdiction", "jurisdiction_evidence_source"]
] = jurisdiction_evidence["course"].apply(
    derive_provisional_jurisdiction
)

jurisdiction_coverage_summary = (
    jurisdiction_evidence
    .groupby(
        [
            "provisional_jurisdiction",
            "jurisdiction_evidence_source",
        ],
        as_index=False,
    )
    .agg(
        provisional_races=("race_name", "size"),
        distinct_raw_courses=("course", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
)

jurisdiction_coverage_summary["share_of_all_races"] = (
    jurisdiction_coverage_summary["provisional_races"]
    / len(jurisdiction_evidence)
)

jurisdiction_coverage_summary = (
    jurisdiction_coverage_summary
    .sort_values(
        ["provisional_races", "provisional_jurisdiction"],
        ascending=[False, True],
    )
    .reset_index(drop=True)
)

resolved_jurisdiction_races = (
    jurisdiction_evidence["provisional_jurisdiction"] != "unresolved"
).sum()

print(
    "Provisional races with jurisdiction resolved from established evidence: "
    f"{resolved_jurisdiction_races:,}"
)
print(
    "Resolved share of all provisional races: "
    f"{resolved_jurisdiction_races / len(jurisdiction_evidence):.2%}"
)
print(
    "Provisional races remaining unresolved: "
    f"{(
        jurisdiction_evidence['provisional_jurisdiction']
        == 'unresolved'
    ).sum():,}"
)

jurisdiction_coverage_summary

Provisional races with jurisdiction resolved from established evidence: 153,644
Resolved share of all provisional races: 81.27%
Provisional races remaining unresolved: 35,399

,provisional_jurisdiction,jurisdiction_evidence_source,provisional_races,distinct_raw_courses,first_date,last_date,share_of_all_races
0,Great Britain,established_unsuffixed_british_course,76260,55,2015-01-01,2026-05-27,0.403400
1,unresolved,no_established_jurisdiction_evidence,30865,8,2015-01-01,2026-05-27,0.163270
2,Ireland,explicit_terminal_course_code,29215,27,2015-01-01,2025-10-14,0.154542
3,France,explicit_terminal_course_code,19361,73,2015-01-03,2025-10-14,0.102416
4,Hong Kong,explicit_terminal_course_code,6847,2,2015-01-25,2025-10-12,0.036219
5,United States,explicit_terminal_course_code,5863,56,2015-01-01,2025-10-12,0.031014
6,unresolved,cross_jurisdiction_course_name_collision,4534,3,2015-01-03,2026-05-09,0.023984
7,Australia,explicit_terminal_course_code,3798,51,2015-01-01,2025-10-11,0.020091
8,United Arab Emirates,explicit_terminal_course_code,2219,5,2015-01-04,2025-04-12,0.011738
9,Ireland,historical_suffixed_course_link,1568,23,2025-10-15,2026-05-27,0.008294
10,Japan,explicit_terminal_course_code,1470,21,2015-01-04,2025-10-13,0.007776
11,France,historical_suffixed_course_link,1172,19,2025-10-15,2026-05-26,0.006200
12,Germany,explicit_terminal_course_code,710,17,2015-04-05,2025-10-12,0.003756
13,Hong Kong,historical_suffixed_course_link,634,2,2025-10-15,2026-05-27,0.003354
14,Canada,explicit_terminal_course_code,462,4,2015-04-18,2025-10-11,0.002444
15,South Africa,explicit_terminal_course_code,453,9,2015-01-10,2025-07-27,0.002396
16,Jersey,explicit_terminal_course_code,433,1,2015-04-06,2025-08-25,0.002290
17,Argentina,explicit_terminal_course_code,416,3,2015-01-03,2025-10-11,0.002201
18,Italy,explicit_terminal_course_code,372,7,2015-04-01,2025-10-12,0.001968
19,Brazil,explicit_terminal_course_code,273,3,2015-01-20,2025-09-06,0.001444
20,United States,historical_suffixed_course_link,242,21,2025-10-17,2026-05-26,0.001280
21,Australia,historical_suffixed_course_link,237,21,2025-10-15,2026-05-23,0.001254
22,New Zealand,explicit_terminal_course_code,236,14,2015-01-01,2025-09-27,0.001248
23,United Arab Emirates,historical_suffixed_course_link,232,4,2025-10-25,2026-04-11,0.001227
24,Chile,explicit_terminal_course_code,198,3,2015-01-02,2025-10-05,0.001047
25,Bahrain,explicit_terminal_course_code,92,2,2015-02-27,2025-03-20,0.000487
26,Sweden,explicit_terminal_course_code,92,3,2015-05-12,2025-09-21,0.000487
27,Japan,historical_suffixed_course_link,89,9,2025-10-18,2026-05-24,0.000471
28,Peru,explicit_terminal_course_code,84,1,2015-01-11,2025-09-14,0.000444
29,Uruguay,explicit_terminal_course_code,68,1,2015-01-06,2025-01-06,0.000360
30,Qatar,explicit_terminal_course_code,64,2,2015-02-26,2025-02-16,0.000339
31,Bahrain,historical_suffixed_course_link,59,1,2025-11-14,2026-04-24,0.000312
32,Turkey,explicit_terminal_course_code,52,2,2015-09-05,2025-09-07,0.000275
33,Switzerland,explicit_terminal_course_code,47,5,2015-07-29,2025-02-16,0.000249
34,Saudi Arabia,explicit_terminal_course_code,41,1,2020-02-29,2025-02-22,0.000217
35,Norway,explicit_terminal_course_code,37,1,2015-06-25,2025-08-24,0.000196
36,Argentina,historical_suffixed_course_link,21,3,2025-11-01,2026-05-25,0.000111
37,Germany,historical_suffixed_course_link,21,8,2025-10-17,2026-05-25,0.000111
38,Guernsey,explicit_terminal_course_code,20,1,2015-05-04,2019-05-06,0.000106
39,New Zealand,historical_suffixed_course_link,19,5,2025-10-18,2026-03-28,0.000101
40,South Africa,historical_suffixed_course_link,17,3,2025-11-29,2026-05-23,0.000090
41,South Korea,explicit_terminal_course_code,17,2,2016-09-11,2025-09-07,0.000090
42,Brazil,historical_suffixed_course_link,16,2,2025-10-18,2026-05-03,0.000085
43,Denmark,explicit_terminal_course_code,15,1,2015-06-28,2025-05-24,0.000079
44,Italy,historical_suffixed_course_link,15,2,2025-10-19,2026-05-10,0.000079
45,Spain,explicit_terminal_course_code,14,2,2015-08-15,2023-08-15,0.000074
46,Czech Republic,explicit_terminal_course_code,13,2,2015-10-11,2025-10-12,0.000069
47,China,explicit_terminal_course_code,10,1,2015-04-03,2017-04-02,0.000053
48,Canada,historical_suffixed_course_link,9,1,2025-10-18,2026-05-02,0.000048
49,Saudi Arabia,historical_suffixed_course_link,8,1,2026-02-14,2026-02-14,0.000042
50,Chile,historical_suffixed_course_link,6,3,2025-10-31,2026-05-02,0.000032
51,Qatar,historical_suffixed_course_link,6,1,2025-12-20,2026-02-14,0.000032
52,Belgium,explicit_terminal_course_code,4,3,2017-03-06,2019-08-27,0.000021
53,Peru,historical_suffixed_course_link,4,1,2025-11-23,2026-04-26,0.000021
54,Hungary,explicit_terminal_course_code,3,1,2023-09-02,2025-09-07,0.000016
55,Singapore,explicit_terminal_course_code,3,1,2015-05-17,2023-07-23,0.000016
56,Jersey,historical_suffixed_course_link,2,1,2026-05-10,2026-05-10,0.000011
57,Switzerland,historical_suffixed_course_link,2,1,2026-02-22,2026-02-22,0.000011
58,Uruguay,historical_suffixed_course_link,2,1,2026-01-06,2026-01-06,0.000011
59,Poland,explicit_terminal_course_code,1,1,2025-09-28,2025-09-28,0.000005

In [33]:
# Inspect every raw course value still unresolved by the provisional
# jurisdiction derivation.
#
# The summary shows:
# - 30,865 unresolved races across eight course values with no established
#   jurisdiction evidence;
# - 4,534 races across the three known cross-jurisdiction collision names.
#
# This cell lists the exact values, race types, frequencies and date ranges
# before we add any further jurisdiction rules.
#
# No jurisdiction is assigned or corrected here.

unresolved_jurisdiction_courses = (
    jurisdiction_evidence.loc[
        jurisdiction_evidence["provisional_jurisdiction"] == "unresolved"
    ]
    .groupby(
        [
            "jurisdiction_evidence_source",
            "course",
            "type",
        ],
        as_index=False,
    )
    .agg(
        provisional_races=("race_name", "size"),
        distinct_race_names=("race_name", "nunique"),
        active_dates=("date", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
    .sort_values(
        [
            "jurisdiction_evidence_source",
            "course",
            "provisional_races",
            "type",
        ],
        ascending=[True, True, False, True],
    )
    .reset_index(drop=True)
)

print(
    "Unresolved raw course values: "
    f"{unresolved_jurisdiction_courses['course'].nunique():,}"
)
print(
    "Unresolved provisional races: "
    f"{unresolved_jurisdiction_courses['provisional_races'].sum():,}"
)

unresolved_jurisdiction_courses

Unresolved raw course values: 11
Unresolved provisional races: 35,399

,jurisdiction_evidence_source,course,type,provisional_races,distinct_race_names,active_dates,first_date,last_date
0,cross_jurisdiction_course_name_collision,Ascot,Flat,1265,665,202,2015-04-29,2026-05-09
1,cross_jurisdiction_course_name_collision,Ascot,Hurdle,276,205,85,2015-01-17,2026-03-29
2,cross_jurisdiction_course_name_collision,Ascot,Chase,252,167,85,2015-01-17,2026-03-29
3,cross_jurisdiction_course_name_collision,Ascot,NH Flat,44,32,44,2015-02-14,2026-02-14
4,cross_jurisdiction_course_name_collision,Newcastle,Hurdle,450,393,122,2015-01-03,2026-04-11
5,cross_jurisdiction_course_name_collision,Newcastle,Chase,318,276,123,2015-01-03,2026-04-11
6,cross_jurisdiction_course_name_collision,Newcastle,Flat,121,116,18,2015-04-11,2026-03-06
7,cross_jurisdiction_course_name_collision,Newcastle,NH Flat,121,110,83,2015-01-03,2026-04-11
8,cross_jurisdiction_course_name_collision,Sandown,Flat,1050,723,161,2015-02-13,2026-04-24
9,cross_jurisdiction_course_name_collision,Sandown,Hurdle,328,227,94,2015-01-03,2026-04-25
10,cross_jurisdiction_course_name_collision,Sandown,Chase,285,187,95,2015-01-03,2026-04-25
11,cross_jurisdiction_course_name_collision,Sandown,NH Flat,24,18,24,2015-03-07,2026-03-07
12,no_established_jurisdiction_evidence,Chelmsford (AW),Flat,4310,2327,593,2015-01-11,2026-03-26
13,no_established_jurisdiction_evidence,Firenze,Flat,1,1,1,2026-04-25,2026-04-25
14,no_established_jurisdiction_evidence,Kempton (AW),Flat,5039,2153,661,2015-01-07,2026-05-27
15,no_established_jurisdiction_evidence,Kempton (AW),NH Flat,7,6,1,2018-03-05,2018-03-05
16,no_established_jurisdiction_evidence,Lingfield (AW),Flat,4727,2164,696,2015-01-03,2026-05-12
17,no_established_jurisdiction_evidence,Lingfield (AW),NH Flat,76,67,46,2015-01-05,2024-12-09
18,no_established_jurisdiction_evidence,Newcastle (AW),Flat,4398,2290,578,2016-05-17,2026-05-19
19,no_established_jurisdiction_evidence,Newcastle (AW),NH Flat,11,11,5,2018-02-05,2019-02-23
20,no_established_jurisdiction_evidence,Newmarket (July),Flat,1438,994,208,2015-06-19,2025-08-23
21,no_established_jurisdiction_evidence,Southwell (AW),Flat,3809,1653,514,2015-01-01,2026-05-21
22,no_established_jurisdiction_evidence,Southwell (AW),NH Flat,7,7,1,2018-03-02,2018-03-02
23,no_established_jurisdiction_evidence,Wolverhampton (AW),Flat,7042,3235,930,2015-01-02,2026-05-18

In [34]:
# Extend the provisional jurisdiction derivation with explicitly curated
# British course configurations established in this notebook.
#
# These values were missed by the earlier rule because their parentheses
# describe surface or course configuration rather than jurisdiction:
#
# - seven British all-weather course forms;
# - Newmarket's July Course.
#
# Firenze and the three cross-jurisdiction collision names remain unresolved.
# Raw course values are preserved unchanged.

curated_british_course_configurations = {
    "Chelmsford (AW)",
    "Kempton (AW)",
    "Lingfield (AW)",
    "Newcastle (AW)",
    "Newmarket (July)",
    "Southwell (AW)",
    "Wolverhampton (AW)",
}

def derive_refined_provisional_jurisdiction(course_name):
    """
    Derive jurisdiction conservatively using established and curated evidence.
    """
    course_name = str(course_name)

    terminal_code = extract_terminal_jurisdiction_code(course_name)

    if terminal_code is not None:
        return pd.Series(
            [
                terminal_code_to_jurisdiction[terminal_code],
                "explicit_terminal_course_code",
            ]
        )

    if course_name in known_cross_jurisdiction_collision_names:
        return pd.Series(
            [
                "unresolved",
                "cross_jurisdiction_course_name_collision",
            ]
        )

    if course_name in historical_course_to_code:
        historical_code = historical_course_to_code[course_name]

        return pd.Series(
            [
                terminal_code_to_jurisdiction[historical_code],
                "historical_suffixed_course_link",
            ]
        )

    if course_name in curated_british_course_configurations:
        return pd.Series(
            [
                "Great Britain",
                "curated_british_course_configuration",
            ]
        )

    if course_name in established_unsuffixed_british_courses:
        return pd.Series(
            [
                "Great Britain",
                "established_unsuffixed_british_course",
            ]
        )

    return pd.Series(
        [
            "unresolved",
            "no_established_jurisdiction_evidence",
        ]
    )


refined_jurisdiction_evidence = provisional_race_names.copy()

refined_jurisdiction_evidence[
    ["provisional_jurisdiction", "jurisdiction_evidence_source"]
] = refined_jurisdiction_evidence["course"].apply(
    derive_refined_provisional_jurisdiction
)

refined_jurisdiction_summary = (
    refined_jurisdiction_evidence
    .groupby(
        [
            "provisional_jurisdiction",
            "jurisdiction_evidence_source",
        ],
        as_index=False,
    )
    .agg(
        provisional_races=("race_name", "size"),
        distinct_raw_courses=("course", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
)

refined_jurisdiction_summary["share_of_all_races"] = (
    refined_jurisdiction_summary["provisional_races"]
    / len(refined_jurisdiction_evidence)
)

refined_jurisdiction_summary = (
    refined_jurisdiction_summary
    .sort_values(
        ["provisional_races", "provisional_jurisdiction"],
        ascending=[False, True],
    )
    .reset_index(drop=True)
)

remaining_unresolved = refined_jurisdiction_evidence.loc[
    refined_jurisdiction_evidence["provisional_jurisdiction"]
    == "unresolved"
]

print(
    "Provisional races with jurisdiction resolved: "
    f"{len(refined_jurisdiction_evidence) - len(remaining_unresolved):,}"
)
print(
    "Resolved share of all provisional races: "
    f"{1 - len(remaining_unresolved) / len(refined_jurisdiction_evidence):.2%}"
)
print(
    "Provisional races remaining unresolved: "
    f"{len(remaining_unresolved):,}"
)
print()
print("Remaining unresolved raw course values:")
print(
    remaining_unresolved["course"]
    .value_counts()
    .sort_index()
    .to_string()
)

refined_jurisdiction_summary

Provisional races with jurisdiction resolved: 184,508
Resolved share of all provisional races: 97.60%
Provisional races remaining unresolved: 4,535

Remaining unresolved raw course values:
course
Ascot        1837
Firenze         1
Newcastle    1010
Sandown      1687

,provisional_jurisdiction,jurisdiction_evidence_source,provisional_races,distinct_raw_courses,first_date,last_date,share_of_all_races
0,Great Britain,established_unsuffixed_british_course,76260,55,2015-01-01,2026-05-27,0.403400
1,Great Britain,curated_british_course_configuration,30864,7,2015-01-01,2026-05-27,0.163264
2,Ireland,explicit_terminal_course_code,29215,27,2015-01-01,2025-10-14,0.154542
3,France,explicit_terminal_course_code,19361,73,2015-01-03,2025-10-14,0.102416
4,Hong Kong,explicit_terminal_course_code,6847,2,2015-01-25,2025-10-12,0.036219
5,United States,explicit_terminal_course_code,5863,56,2015-01-01,2025-10-12,0.031014
6,unresolved,cross_jurisdiction_course_name_collision,4534,3,2015-01-03,2026-05-09,0.023984
7,Australia,explicit_terminal_course_code,3798,51,2015-01-01,2025-10-11,0.020091
8,United Arab Emirates,explicit_terminal_course_code,2219,5,2015-01-04,2025-04-12,0.011738
9,Ireland,historical_suffixed_course_link,1568,23,2025-10-15,2026-05-27,0.008294
10,Japan,explicit_terminal_course_code,1470,21,2015-01-04,2025-10-13,0.007776
11,France,historical_suffixed_course_link,1172,19,2025-10-15,2026-05-26,0.006200
12,Germany,explicit_terminal_course_code,710,17,2015-04-05,2025-10-12,0.003756
13,Hong Kong,historical_suffixed_course_link,634,2,2025-10-15,2026-05-27,0.003354
14,Canada,explicit_terminal_course_code,462,4,2015-04-18,2025-10-11,0.002444
15,South Africa,explicit_terminal_course_code,453,9,2015-01-10,2025-07-27,0.002396
16,Jersey,explicit_terminal_course_code,433,1,2015-04-06,2025-08-25,0.002290
17,Argentina,explicit_terminal_course_code,416,3,2015-01-03,2025-10-11,0.002201
18,Italy,explicit_terminal_course_code,372,7,2015-04-01,2025-10-12,0.001968
19,Brazil,explicit_terminal_course_code,273,3,2015-01-20,2025-09-06,0.001444
20,United States,historical_suffixed_course_link,242,21,2025-10-17,2026-05-26,0.001280
21,Australia,historical_suffixed_course_link,237,21,2025-10-15,2026-05-23,0.001254
22,New Zealand,explicit_terminal_course_code,236,14,2015-01-01,2025-09-27,0.001248
23,United Arab Emirates,historical_suffixed_course_link,232,4,2025-10-25,2026-04-11,0.001227
24,Chile,explicit_terminal_course_code,198,3,2015-01-02,2025-10-05,0.001047
25,Bahrain,explicit_terminal_course_code,92,2,2015-02-27,2025-03-20,0.000487
26,Sweden,explicit_terminal_course_code,92,3,2015-05-12,2025-09-21,0.000487
27,Japan,historical_suffixed_course_link,89,9,2025-10-18,2026-05-24,0.000471
28,Peru,explicit_terminal_course_code,84,1,2015-01-11,2025-09-14,0.000444
29,Uruguay,explicit_terminal_course_code,68,1,2015-01-06,2025-01-06,0.000360
30,Qatar,explicit_terminal_course_code,64,2,2015-02-26,2025-02-16,0.000339
31,Bahrain,historical_suffixed_course_link,59,1,2025-11-14,2026-04-24,0.000312
32,Turkey,explicit_terminal_course_code,52,2,2015-09-05,2025-09-07,0.000275
33,Switzerland,explicit_terminal_course_code,47,5,2015-07-29,2025-02-16,0.000249
34,Saudi Arabia,explicit_terminal_course_code,41,1,2020-02-29,2025-02-22,0.000217
35,Norway,explicit_terminal_course_code,37,1,2015-06-25,2025-08-24,0.000196
36,Argentina,historical_suffixed_course_link,21,3,2025-11-01,2026-05-25,0.000111
37,Germany,historical_suffixed_course_link,21,8,2025-10-17,2026-05-25,0.000111
38,Guernsey,explicit_terminal_course_code,20,1,2015-05-04,2019-05-06,0.000106
39,New Zealand,historical_suffixed_course_link,19,5,2025-10-18,2026-03-28,0.000101
40,South Africa,historical_suffixed_course_link,17,3,2025-11-29,2026-05-23,0.000090
41,South Korea,explicit_terminal_course_code,17,2,2016-09-11,2025-09-07,0.000090
42,Brazil,historical_suffixed_course_link,16,2,2025-10-18,2026-05-03,0.000085
43,Denmark,explicit_terminal_course_code,15,1,2015-06-28,2025-05-24,0.000079
44,Italy,historical_suffixed_course_link,15,2,2025-10-19,2026-05-10,0.000079
45,Spain,explicit_terminal_course_code,14,2,2015-08-15,2023-08-15,0.000074
46,Czech Republic,explicit_terminal_course_code,13,2,2015-10-11,2025-10-12,0.000069
47,China,explicit_terminal_course_code,10,1,2015-04-03,2017-04-02,0.000053
48,Canada,historical_suffixed_course_link,9,1,2025-10-18,2026-05-02,0.000048
49,Saudi Arabia,historical_suffixed_course_link,8,1,2026-02-14,2026-02-14,0.000042
50,Chile,historical_suffixed_course_link,6,3,2025-10-31,2026-05-02,0.000032
51,Qatar,historical_suffixed_course_link,6,1,2025-12-20,2026-02-14,0.000032
52,Belgium,explicit_terminal_course_code,4,3,2017-03-06,2019-08-27,0.000021
53,Peru,historical_suffixed_course_link,4,1,2025-11-23,2026-04-26,0.000021
54,Hungary,explicit_terminal_course_code,3,1,2023-09-02,2025-09-07,0.000016
55,Singapore,explicit_terminal_course_code,3,1,2015-05-17,2023-07-23,0.000016
56,Jersey,historical_suffixed_course_link,2,1,2026-05-10,2026-05-10,0.000011
57,Switzerland,historical_suffixed_course_link,2,1,2026-02-22,2026-02-22,0.000011
58,Uruguay,historical_suffixed_course_link,2,1,2026-01-06,2026-01-06,0.000011
59,Poland,explicit_terminal_course_code,1,1,2025-09-28,2025-09-28,0.000005
60,unresolved,no_established_jurisdiction_evidence,1,1,2026-04-25,2026-04-25,0.000005

In [35]:
# Profile the three cross-jurisdiction course-name collisions by period,
# race type and explicit surface evidence.
#
# The earlier suffixed forms establish that:
# - Ascot (AUS)
# - Sandown (AUS)
# - Newcastle (AUS)
#
# are distinct from the longstanding British courses with the same base names.
#
# After the October 2025 suffix-removal change, the unsuffixed raw values may
# represent either jurisdiction. This cell tests whether the ambiguity can be
# separated using source evidence already available at race level:
#
# - date before or after 15 October 2025;
# - race type;
# - explicit Turf/Dirt/synthetic wording in race_name;
# - off-time format as an additional descriptive attribute.
#
# No jurisdiction is assigned yet.

collision_race_profile = refined_jurisdiction_evidence.loc[
    refined_jurisdiction_evidence["course"].isin(
        ["Ascot", "Sandown", "Newcastle"]
    )
].copy()

collision_race_profile["source_period"] = collision_race_profile["date"].map(
    lambda value: (
        "before_2025_10_15"
        if value < "2025-10-15"
        else "from_2025_10_15"
    )
)

# Reuse the explicit surface-family evidence created earlier.
collision_race_profile = collision_race_profile.merge(
    surface_evidence[
        [
            "date",
            "course",
            "off",
            "race_name",
            "type",
            "explicit_surface_family",
            "race_name_has_explicit_surface",
        ]
    ],
    on=["date", "course", "off", "race_name", "type"],
    how="left",
)

# Preserve the raw off-time while distinguishing leading-zero forms such as
# 05:05 from ordinary UK display forms such as 3:15.
collision_race_profile["off_time_format"] = (
    collision_race_profile["off"]
    .astype(str)
    .map(
        lambda value: (
            "leading_zero_24h_style"
            if re.fullmatch(r"0\d:\d{2}", value)
            else "other_raw_format"
        )
    )
)

collision_context_summary = (
    collision_race_profile
    .groupby(
        [
            "course",
            "source_period",
            "type",
            "explicit_surface_family",
            "off_time_format",
        ],
        as_index=False,
    )
    .agg(
        provisional_races=("race_name", "size"),
        distinct_race_names=("race_name", "nunique"),
        active_dates=("date", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
    .sort_values(
        [
            "course",
            "source_period",
            "provisional_races",
            "type",
            "explicit_surface_family",
        ],
        ascending=[True, True, False, True, True],
    )
    .reset_index(drop=True)
)

print(
    "Collision-course provisional races assessed: "
    f"{len(collision_race_profile):,}"
)
print()
print("Counts by raw course:")
print(
    collision_race_profile["course"]
    .value_counts()
    .sort_index()
    .to_string()
)

collision_context_summary

Collision-course provisional races assessed: 4,534

Counts by raw course:
course
Ascot        1837
Newcastle    1010
Sandown      1687

,course,source_period,type,explicit_surface_family,off_time_format,provisional_races,distinct_race_names,active_dates,first_date,last_date
0,Ascot,before_2025_10_15,Flat,no_explicit_race_name_surface,other_raw_format,1216,628,184,2015-04-29,2025-10-04
1,Ascot,before_2025_10_15,Hurdle,no_explicit_race_name_surface,other_raw_format,249,191,77,2015-01-17,2025-03-30
2,Ascot,before_2025_10_15,Chase,no_explicit_race_name_surface,other_raw_format,229,153,77,2015-01-17,2025-03-30
3,Ascot,before_2025_10_15,NH Flat,no_explicit_race_name_surface,other_raw_format,40,30,40,2015-02-14,2025-02-15
4,Ascot,from_2025_10_15,Flat,no_explicit_race_name_surface,other_raw_format,28,28,4,2025-10-18,2026-05-09
5,Ascot,from_2025_10_15,Hurdle,no_explicit_race_name_surface,other_raw_format,27,27,8,2025-11-01,2026-03-29
6,Ascot,from_2025_10_15,Chase,no_explicit_race_name_surface,other_raw_format,23,23,8,2025-11-01,2026-03-29
7,Ascot,from_2025_10_15,Flat,turf,leading_zero_24h_style,19,19,13,2025-11-01,2026-05-02
8,Ascot,from_2025_10_15,NH Flat,no_explicit_race_name_surface,other_raw_format,4,4,4,2025-11-01,2026-02-14
9,Ascot,from_2025_10_15,Flat,turf,other_raw_format,2,2,2,2025-10-18,2026-04-11
10,Newcastle,before_2025_10_15,Hurdle,no_explicit_race_name_surface,other_raw_format,409,356,111,2015-01-03,2025-04-05
11,Newcastle,before_2025_10_15,Chase,no_explicit_race_name_surface,other_raw_format,290,250,112,2015-01-03,2025-04-05
12,Newcastle,before_2025_10_15,Flat,no_explicit_race_name_surface,other_raw_format,118,113,16,2015-04-11,2015-09-04
13,Newcastle,before_2025_10_15,NH Flat,no_explicit_race_name_surface,other_raw_format,113,102,75,2015-01-03,2025-04-05
14,Newcastle,from_2025_10_15,Hurdle,no_explicit_race_name_surface,other_raw_format,41,41,11,2025-10-30,2026-04-11
15,Newcastle,from_2025_10_15,Chase,no_explicit_race_name_surface,other_raw_format,28,28,11,2025-10-30,2026-04-11
16,Newcastle,from_2025_10_15,NH Flat,no_explicit_race_name_surface,other_raw_format,8,8,8,2025-10-30,2026-04-11
17,Newcastle,from_2025_10_15,Flat,turf,leading_zero_24h_style,3,3,2,2025-11-15,2026-03-06
18,Sandown,before_2025_10_15,Flat,no_explicit_race_name_surface,other_raw_format,1043,722,160,2015-02-13,2025-09-17
19,Sandown,before_2025_10_15,Hurdle,no_explicit_race_name_surface,other_raw_format,304,212,87,2015-01-03,2025-04-26
20,Sandown,before_2025_10_15,Chase,no_explicit_race_name_surface,other_raw_format,262,171,88,2015-01-03,2025-04-26
21,Sandown,before_2025_10_15,NH Flat,no_explicit_race_name_surface,other_raw_format,22,16,22,2015-03-07,2025-03-08
22,Sandown,from_2025_10_15,Hurdle,no_explicit_race_name_surface,other_raw_format,24,24,7,2025-11-09,2026-04-25
23,Sandown,from_2025_10_15,Chase,no_explicit_race_name_surface,other_raw_format,23,23,7,2025-11-09,2026-04-25
24,Sandown,from_2025_10_15,Flat,no_explicit_race_name_surface,other_raw_format,7,7,1,2026-04-24,2026-04-24
25,Sandown,from_2025_10_15,NH Flat,no_explicit_race_name_surface,other_raw_format,2,2,2,2025-11-09,2026-03-07

In [36]:
# Inspect every post-suffix-change Flat race at the three colliding course names.
#
# This produces the small race-level set that may require either:
# - direct contextual classification from source fields; or
# - external race-result verification.
#
# Useful evidence includes:
# - full race name;
# - off time;
# - going;
# - distance;
# - horse, jockey and trainer nationality context;
# - whether the race name explicitly states a surface.
#
# One representative runner is selected per provisional race, preferring
# the winner where available. No jurisdiction is assigned in this cell.

post_change_collision_flat_sql = f"""
WITH ranked_rows AS (
    SELECT
        rowid AS source_rowid,
        date,
        course,
        off,
        race_name,
        type,
        race_id,
        dist,
        going,
        age,
        class,
        ran,
        horse,
        jockey,
        trainer,
        draw,
        time,
        pos,
        ROW_NUMBER() OVER (
            PARTITION BY
                date,
                course,
                off,
                race_name,
                type
            ORDER BY
                CASE
                    WHEN CAST(pos AS TEXT) = '1' THEN 0
                    ELSE 1
                END,
                rowid
        ) AS row_rank
    FROM {SOURCE_TABLE}
    WHERE {DATA_ROW_PREDICATE}
      AND course IN ('Ascot', 'Sandown', 'Newcastle')
      AND type = 'Flat'
      AND date >= '2025-10-15'
)
SELECT
    source_rowid,
    date,
    course,
    off,
    race_name,
    race_id,
    dist,
    going,
    age,
    class,
    ran,
    horse,
    jockey,
    trainer,
    draw,
    time
FROM ranked_rows
WHERE row_rank = 1
ORDER BY
    course,
    date,
    off
"""

post_change_collision_flat_races = pd.read_sql_query(
    post_change_collision_flat_sql,
    connection,
)

post_change_collision_flat_races["explicit_turf_marker"] = (
    post_change_collision_flat_races["race_name"]
    .str.contains(r"\(Turf\)", regex=True, na=False)
)

print(
    "Post-change Flat races at colliding raw course names: "
    f"{len(post_change_collision_flat_races):,}"
)

print()
print("Counts by course and explicit Turf marker:")
display(
    post_change_collision_flat_races
    .groupby(
        ["course", "explicit_turf_marker"],
        as_index=False,
    )
    .size()
    .rename(columns={"size": "provisional_races"})
)

pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)

post_change_collision_flat_races

Post-change Flat races at colliding raw course names: 59

Counts by course and explicit Turf marker:

      course  explicit_turf_marker  provisional_races
0      Ascot                 False                 28
1      Ascot                  True                 21
2  Newcastle                  True                  3
3    Sandown                 False                  7

,source_rowid,date,course,off,race_name,race_id,dist,going,age,class,ran,horse,jockey,trainer,draw,time,explicit_turf_marker
0,1751340,2025-10-18,Ascot,10:02,Liquor Barons - Eurythmic Stakes (3yo+) (Turf),906176,7f,Good,6,Class 1,11,Diamond Scene (AUS),Clint Johnston-Porter,Michael Grantham,9,1:23.79,True
1,1751284,2025-10-18,Ascot,12:55,Qipco British Champions Long Distance Cup,900016,2m,Good,7,Class 1,5,Trawlerman (IRE),William Buick,John & Thady Gosden,2,3:22.29,False
2,1751329,2025-10-18,Ascot,13:30,Qipco British Champions Day Two-Year-Old Conditions Stakes (GBB Race),903349,6f,Good,2,Class 2,11,Mission Central (IRE),Christophe Soumillon,A P OBrien,7,1:13.03,False
3,1751310,2025-10-18,Ascot,14:05,Qipco British Champions Sprint Stakes,900018,6f,Good,3,Class 1,19,Powerful Glory (IRE),Jamie Spencer,Richard Fahey,14,1:11.72,False
4,1751289,2025-10-18,Ascot,14:45,Qipco British Champions Fillies & Mares Stakes,900017,1m4f,Good,4,Class 1,10,Kalpana (GB),Colin Keane,Andrew Balding,7,2:32.67,False
5,1751268,2025-10-18,Ascot,15:25,Queen Elizabeth II Stakes (Sponsored By Qipco),900015,1m,Good,5,Class 1,16,Ciceros Gift (GB),Jason Watson,Charles Hills,1,1:38.35,False
6,1751299,2025-10-18,Ascot,16:05,Qipco Champion Stakes,900014,1m2f,Good,4,Class 1,11,Calandagan (IRE),Mickael Barzalona,F-H Graffard,7,2:03.19,False
7,1751248,2025-10-18,Ascot,16:40,Balmoral Handicap (Sponsored By Qipco),902470,1m,Good,3,Class 2,20,Crown Of Oaks (GB),Tom Marquand,William Haggas,23,1:39.43,False
8,1759080,2025-11-01,Ascot,07:05,TABTouch Prince Of Wales Stakes (3yo+) (Turf),907408,5f,Good,5,Class 1,7,Jokers Grin (AUS),Patrick Carbery,Bernie Miller,6,0:58.38,True
9,1759087,2025-11-01,Ascot,08:52,Asian Beau Stakes Handicap) (3yo+) (Turf),907409,7f,Good,5,Class 1,13,Watch Me Rock (AUS),William Pike,Grant & Alana Williams,2,1:23.83,True
10,1763030,2025-11-08,Ascot,08:20,Perth Racing Member Appreciation - Lee Steere Stakes (3yo+) (Turf),908114,7f,Good,5,Class 1,11,Super Smink (AUS),Chris Parnham,Daniel Morton,1,1:24.72,True
11,1765675,2025-11-15,Ascot,07:05,Hosemasters - Colonel Reeves Stakes (3yo+) (Turf),908397,5½f,Good,5,Class 1,9,Jokers Grin (AUS),Shaun ODonnell,Bernie Miller,9,1:03.59,True
12,1765650,2025-11-15,Ascot,08:20,Quayclean - WA Champion Fillies Stakes (3yo Fillies) (Turf),908398,1m,Good,3,Class 1,14,Pure Excess (AUS),Steven Parnham,Daniel Morton,5,1:37.39,True
13,1765664,2025-11-15,Ascot,09:30,R J Peters Stakes Handicap) (3yo+) (Turf),908399,7½f,Good,4,Class 1,11,Storyville (AUS),William Pike,Grant & Alana Williams,1,1:30.56,True
14,1768991,2025-11-22,Ascot,08:20,WA Guineas (3yo) (Turf),909043,1m,Good,3,Class 1,13,King Of Light (AUS),William Pike,Daniel Morton,4,1:36.83,True
15,1769004,2025-11-22,Ascot,08:58,Swan Draught - Railway Stakes Handicap) (3yo+) (Turf),908915,1m,Good,5,Class 1,16,Watch Me Rock (AUS),William Pike,Grant & Alana Williams,4,1:35.80,True
16,1772450,2025-11-29,Ascot,08:59,MCA Polytrack - Winterbottom Stakes (3yo+) (Turf),909217,6f,Good,5,Class 1,9,Libertad (AUS),Jamie Mott,Annabel & Rob Archibald,1,1:10.38,True
17,1775487,2025-12-06,Ascot,09:00,Tabtouch - Northerly Stakes (3yo+) (Turf),909859,1m1f,Good,5,Class 1,16,Cosmic Crusader (NZ),Clint Johnston-Porter,Michael Grantham,9,1:48.48,True
18,1778458,2025-12-13,Ascot,09:00,The Gold Rush (3yo+) (Turf),910290,7f,Good,6,Class 1,12,Rey Magnerio (AUS),William Pike,Robbie Griffiths,5,1:21.43,True
19,1781738,2025-12-20,Ascot,09:00,Ted Van Heemst Stakes (3yo+) (Turf),910930,1m2½f,Good,5,Class 1,11,Apulia (AUS),William Pike,Ben Will & JD Hayes,1,2:08.93,True
20,1786358,2026-01-01,Ascot,08:25,Mrs Macs - La Trice Classic (2yo+ Fillies & Mares) (Turf),4803587,1m1f,Good,5,Class 1,9,Luvnwar (NZ),Clint Johnston-Porter,Michael Grantham,2,1:49.00,True
21,1786367,2026-01-01,Ascot,09:40,TABtouch - Perth Cup Handicap) (3yo+) (Turf),4803588,1m4f,Good,5,Class 1,15,Apulia (AUS),William Pike,Ben Will & JD Hayes,3,2:28.13,True
22,1821583,2026-04-01,Ascot,08:20,Drummond Golf - W.A. Oaks (Turf),916800,1m4f,Good To Soft,3,Class 1,8,Wonderfully Made (AUS),Mrs Lucy Fiore,Daniel Morton,8,2:32.94,True
23,1822983,2026-04-04,Ascot,09:10,Swan Draught - Gimcrack Stakes (Turf),917031,5½f,Good,2,Class 1,14,Aurum Belle (AUS),Brad Parnham,Neville Parnham,10,1:04.24,True
24,1822997,2026-04-04,Ascot,09:45,PKF - Roma Cup (Turf),917032,5½f,Good,5,Class 1,9,Rope Them In (AUS),Shaun McGruddy,Stephen Wolfe,4,1:03.40,True
25,1827004,2026-04-11,Ascot,10:00,Schweppes - WATC Derby (Turf),917872,1m4f,Good,3,Class 1,9,Sentimental Legend (AUS),William Pike,Grant & Alana Williams,1,2:30.86,True
26,1830177,2026-04-18,Ascot,08:00,Lawn Pride Australia - Karrakatta Plate (Turf),918281,6f,Good To Soft,2,Class 1,16,Afireofgidgeecoals (AUS),Mrs Lucy Fiore,Daniel Morton,2,1:10.78,True
27,1836605,2026-05-01,Ascot,14:00,Ascot Shop Royal Ascot Two-Year-Old Trial EBF Conditions Stakes (GBB Race),916514,5f,Good To Firm,2,Class 2,3,Adaay Of Scarlett (IRE),James Doyle,Hugo Palmer,2,1:00.64,False
28,1836634,2026-05-01,Ascot,14:35,Longines Sagaro Stakes (A Gold Cup Trial),916508,2m,Good To Firm,7,Class 1,8,Sweet William (IRE),Robert Havlin,John & Thady Gosden,9,3:24.97,False
29,1836580,2026-05-01,Ascot,15:10,Commonwealth Cup Trial Stakes (Registered As The Pavilion Stakes),916509,6f,Good To Firm,3,Class 1,8,Coppull (GB),Rossa Ryan,Clive Cox,8,1:13.24,False
30,1836619,2026-05-01,Ascot,15:45,Memberships At Ascot Paradise Stakes (A Queen Anne Stakes Trial),916510,1m,Good To Firm,4,Class 1,8,Jonquil (GB),Colin Keane,Andrew Balding,6,1:39.79,False
31,1836588,2026-05-01,Ascot,16:20,Naas Racecourse Handicap,916512,5f,Good To Firm,4,Class 4,17,Far Above The Law (IRE),David Probert,Michael Herrington,13,0:59.47,False
32,1836627,2026-05-01,Ascot,16:55,Darley British EBF Fillies Novice Stakes (GBB Race),916511,1m,Good To Firm,3,Class 2,7,So Regal (GB),Ryan Moore,John & Thady Gosden,6,1:42.42,False
33,1836608,2026-05-01,Ascot,17:30,Ascot Racecourse Supports Debra Manny Mercer Apprentice Handicap,916513,1m,Good To Firm,5,Class 3,11,Joolianoss (IRE),Tom Kiely-Marshall,James Evans,6,1:39.19,False
34,1837196,2026-05-02,Ascot,09:10,W.A. Sires Produce Stakes (Turf),919532,7f,Good,2,Class 1,11,Beatty (AUS),William Pike,Sean & Jake Casey,5,1:23.75,True
35,1840727,2026-05-08,Ascot,13:50,Peroni Nastro Azzurro 0.0% Handicap,917642,7f,Good,3,Class 2,10,Colori Forever (GB),Marco Ghiani,Marco Botti,10,1:26.52,False
36,1840768,2026-05-08,Ascot,14:20,Juddmonte EBF Fillies Restricted Novice Stakes (Bands B/C/D) (EBF Restricted Qualifier) (GBB),917644,5f,Good,2,Class 2,12,Bint Archange (IRE),William Buick,Richard Hughes,10,1:00.86,False
37,1840720,2026-05-08,Ascot,14:55,Palmer & Co. Champagne Maiden Fillies Stakes (GBB Race),917648,1m2f,Good,3,Class 2,7,Light Of Paris (GER),William Buick,John & Thady Gosden,2,2:12.45,False
38,1840699,2026-05-08,Ascot,15:25,Only Peroni Nastro Azzurro 0.0% Handicap,917643,6f,Good,4,Class 3,10,Bolo Neighs (IRE),Rossa Ryan,Ralph Beckett,10,1:13.29,False
39,1840737,2026-05-08,Ascot,16:00,Ascot Hospitality Handicap,917647,6f,Good,3,Class 4,19,Secret Santa (IRE),Sean Levey,Richard Hannon,12,1:12.56,False
40,1840709,2026-05-08,Ascot,16:35,Peroni Nastro Azzurro 0.0% Style Handicap,917646,1m,Good,3,Class 4,11,Outback Heat (GB),Kaiya Fraser,Harry Eustace,11,1:40.99,False
41,1840756,2026-05-08,Ascot,17:10,Peroni Nastro Azzurro 0.0% Apprentice Handicap (GBBPlus Race),917645,2m,Good,5,Class 4,12,Believitanducan (IRE),Luke Catton,Alan King,13,3:28.53,False
42,1841218,2026-05-09,Ascot,13:10,Peroni Nastro Azzurro 0.0% EBF Novice Stakes (GBB Race),917655,6f,Good,2,Class 3,10,Night In Vegas (IRE),Charles Bishop,Eve Johnson Houghton,8,1:14.62,False
43,1841228,2026-05-09,Ascot,13:45,Peroni Nastro Azzurro 0.0% British EBF Fillies Handicap,917650,1m,Good,5,Class 2,9,Radiant Beauty (GB),James Doyle,James Owen,9,1:40.07,False
44,1841242,2026-05-09,Ascot,14:20,Carey Group Victoria Cup (Heritage Handicap),917649,7f,Good,7,Class 2,28,The Wizard Of Eye (IRE),Neil Callan,Tom Clover,26,1:24.81,False
45,1841270,2026-05-09,Ascot,14:55,Peroni Nastro Azzurro 0.0% Italy Handicap (GBBPlus Race),917651,1m4f,Good To Firm,4,Class 3,14,Wine Dark Sea (GB),Saffie Osborne,Harry Charlton,3,2:28.89,False
46,1841237,2026-05-09,Ascot,15:30,Royal Ascot Local Schools Art Competition Handicap,917652,1m2f,Good To Firm,3,Class 3,5,Sintra (GB),Oisin Murphy,Andrew Balding,1,2:06.62,False
47,1841209,2026-05-09,Ascot,16:05,Mariner Systems Fillies Handicap,917654,1m2f,Good To Firm,3,Class 4,9,Venetia (GB),Edward Greatrex,Ralph Beckett,2,2:06.57,False
48,1841191,2026-05-09,Ascot,16:40,Peroni Nastro Azzurro 0.0% Blue Handicap,917653,6f,Good To Firm,4,Class 4,18,Azure Zain (FR),Warren Fentiman,Richard & Peter Fahey,5,1:12.36,False
49,1766003,2025-11-15,Newcastle,05:05,NZB 3yo Spring Stakes (Turf),908281,1m,Good,3,Class 1,11,Green Spaces (AUS),Rachel King,Bjorn Baker,1,1:36.00,True
50,1766014,2025-11-15,Newcastle,05:45,The Newcastle Herald Hunter (Handicap) (3yo+) (Turf),908282,6½f,Good,8,,16,Coal Crusher (AUS),Chad Schofield,Joseph Pride,4,1:16.08,True
51,1810567,2026-03-06,Newcastle,05:55,Horsepower Newcastle Stakes (Handicap) (Turf),914933,7f,Good,4,Class 1,10,Tuileries (AUS),Chad Schofield,Peter Snowden,9,1:22.77,True
52,1833595,2026-04-24,Sandown,13:20,bet365 Handicap,916401,5f,Good,3,Class 2,9,Black Star Boy (IRE),Kieran Shoemark,Ed Walker,1,1:00.55,False
53,1833638,2026-04-24,Sandown,13:50,bet365 Esher Cup Handicap,916400,1m,Good,3,Class 2,7,Laureate Crown (IRE),Oisin Murphy,Hugo Palmer,6,1:43.58,False
54,1833626,2026-04-24,Sandown,14:25,bet365 Gordon Richards Stakes,916398,1m2f,Good,4,Class 1,5,Saddadd (IRE),Ray Dawson,Roger Varian,5,2:08.46,False
55,1833604,2026-04-24,Sandown,15:00,bet365 Mile,916397,1m,Good,4,Class 1,6,Opera Ballo (IRE),William Buick,Charlie Appleby,2,1:42.26,False
56,1833631,2026-04-24,Sandown,15:35,bet365 Classic Trial,916399,1m2f,Good,3,Class 1,7,Raaheeb (IRE),Rossa Ryan,Owen Burrows,1,2:09.36,False
57,1833610,2026-04-24,Sandown,16:10,bet365 Wild Card Fillies Novice Stakes (GBB Race),916403,1m2f,Good,3,Class 3,10,Felicitas (GB),Kieran Shoemark,Ed Walker,5,2:11.35,False
58,1833620,2026-04-24,Sandown,16:45,Nordoff & Robbins Ozzy Osbourne Memorial Handicap,916402,1m2f,Good,3,Class 4,6,Lost Boys (IRE),Hector Crouch,David Menuisier,6,2:11.57,False

In [37]:
# Apply the final candidate jurisdiction derivation at provisional race grain.
#
# This extends the established course-level evidence with narrowly bounded
# race-context rules for the three exact-name collisions:
#
# Ascot:
# - before 15 October 2025: Great Britain;
# - from that date, Flat races explicitly marked "(Turf)" are Australia;
# - all other observed Ascot races remain Great Britain.
#
# Newcastle:
# - before 15 October 2025: Great Britain;
# - from that date, Flat races explicitly marked "(Turf)" are Australia;
# - Hurdle, Chase and NH Flat remain Great Britain.
#
# Sandown:
# - all unsuffixed records in the current source are Great Britain;
# - the Australian venue remains represented separately as "Sandown (AUS)".
#
# Firenze:
# - assigned through a curated venue reference as Italy.
#
# These are candidate canonicalisation rules for the current extract.
# Raw course values remain unchanged and the evidence source is retained.

def derive_candidate_race_jurisdiction(row):
    """Derive candidate jurisdiction and retain the supporting rule."""
    course_name = str(row["course"])
    race_date = str(row["date"])
    race_type = str(row["type"])
    race_name = str(row["race_name"])

    terminal_code = extract_terminal_jurisdiction_code(course_name)

    if terminal_code is not None:
        return pd.Series(
            [
                terminal_code_to_jurisdiction[terminal_code],
                "explicit_terminal_course_code",
            ]
        )

    if course_name in historical_course_to_code:
        historical_code = historical_course_to_code[course_name]

        return pd.Series(
            [
                terminal_code_to_jurisdiction[historical_code],
                "historical_suffixed_course_link",
            ]
        )

    if course_name in curated_british_course_configurations:
        return pd.Series(
            [
                "Great Britain",
                "curated_british_course_configuration",
            ]
        )

    if course_name == "Firenze":
        return pd.Series(
            [
                "Italy",
                "curated_venue_reference",
            ]
        )

    if course_name == "Ascot":
        if (
            race_date >= "2025-10-15"
            and race_type == "Flat"
            and "(Turf)" in race_name
        ):
            return pd.Series(
                [
                    "Australia",
                    "race_context_course_collision_rule",
                ]
            )

        return pd.Series(
            [
                "Great Britain",
                "race_context_course_collision_rule",
            ]
        )

    if course_name == "Newcastle":
        if (
            race_date >= "2025-10-15"
            and race_type == "Flat"
            and "(Turf)" in race_name
        ):
            return pd.Series(
                [
                    "Australia",
                    "race_context_course_collision_rule",
                ]
            )

        return pd.Series(
            [
                "Great Britain",
                "race_context_course_collision_rule",
            ]
        )

    if course_name == "Sandown":
        return pd.Series(
            [
                "Great Britain",
                "race_context_course_collision_rule",
            ]
        )

    if course_name in established_unsuffixed_british_courses:
        return pd.Series(
            [
                "Great Britain",
                "established_unsuffixed_british_course",
            ]
        )

    return pd.Series(
        [
            "unresolved",
            "no_established_jurisdiction_evidence",
        ]
    )


candidate_jurisdiction_evidence = provisional_race_names.copy()

candidate_jurisdiction_evidence[
    ["candidate_jurisdiction", "jurisdiction_evidence_source"]
] = candidate_jurisdiction_evidence.apply(
    derive_candidate_race_jurisdiction,
    axis=1,
)

candidate_jurisdiction_summary = (
    candidate_jurisdiction_evidence
    .groupby(
        [
            "candidate_jurisdiction",
            "jurisdiction_evidence_source",
        ],
        as_index=False,
    )
    .agg(
        provisional_races=("race_name", "size"),
        distinct_raw_courses=("course", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
)

candidate_jurisdiction_summary["share_of_all_races"] = (
    candidate_jurisdiction_summary["provisional_races"]
    / len(candidate_jurisdiction_evidence)
)

candidate_jurisdiction_summary = (
    candidate_jurisdiction_summary
    .sort_values(
        ["provisional_races", "candidate_jurisdiction"],
        ascending=[False, True],
    )
    .reset_index(drop=True)
)

unresolved_candidate_races = candidate_jurisdiction_evidence.loc[
    candidate_jurisdiction_evidence["candidate_jurisdiction"]
    == "unresolved"
]

print(
    "Provisional races assigned a candidate jurisdiction: "
    f"{len(candidate_jurisdiction_evidence) - len(unresolved_candidate_races):,}"
)
print(
    "Candidate jurisdiction coverage: "
    f"{1 - len(unresolved_candidate_races) / len(candidate_jurisdiction_evidence):.2%}"
)
print(
    "Provisional races remaining unresolved: "
    f"{len(unresolved_candidate_races):,}"
)

candidate_jurisdiction_summary

Provisional races assigned a candidate jurisdiction: 189,043
Candidate jurisdiction coverage: 100.00%
Provisional races remaining unresolved: 0

,candidate_jurisdiction,jurisdiction_evidence_source,provisional_races,distinct_raw_courses,first_date,last_date,share_of_all_races
0,Great Britain,established_unsuffixed_british_course,76260,55,2015-01-01,2026-05-27,0.403400
1,Great Britain,curated_british_course_configuration,30864,7,2015-01-01,2026-05-27,0.163264
2,Ireland,explicit_terminal_course_code,29215,27,2015-01-01,2025-10-14,0.154542
3,France,explicit_terminal_course_code,19361,73,2015-01-03,2025-10-14,0.102416
4,Hong Kong,explicit_terminal_course_code,6847,2,2015-01-25,2025-10-12,0.036219
5,United States,explicit_terminal_course_code,5863,56,2015-01-01,2025-10-12,0.031014
6,Great Britain,race_context_course_collision_rule,4510,3,2015-01-03,2026-05-09,0.023857
7,Australia,explicit_terminal_course_code,3798,51,2015-01-01,2025-10-11,0.020091
8,United Arab Emirates,explicit_terminal_course_code,2219,5,2015-01-04,2025-04-12,0.011738
9,Ireland,historical_suffixed_course_link,1568,23,2025-10-15,2026-05-27,0.008294
10,Japan,explicit_terminal_course_code,1470,21,2015-01-04,2025-10-13,0.007776
11,France,historical_suffixed_course_link,1172,19,2025-10-15,2026-05-26,0.006200
12,Germany,explicit_terminal_course_code,710,17,2015-04-05,2025-10-12,0.003756
13,Hong Kong,historical_suffixed_course_link,634,2,2025-10-15,2026-05-27,0.003354
14,Canada,explicit_terminal_course_code,462,4,2015-04-18,2025-10-11,0.002444
15,South Africa,explicit_terminal_course_code,453,9,2015-01-10,2025-07-27,0.002396
16,Jersey,explicit_terminal_course_code,433,1,2015-04-06,2025-08-25,0.002290
17,Argentina,explicit_terminal_course_code,416,3,2015-01-03,2025-10-11,0.002201
18,Italy,explicit_terminal_course_code,372,7,2015-04-01,2025-10-12,0.001968
19,Brazil,explicit_terminal_course_code,273,3,2015-01-20,2025-09-06,0.001444
20,United States,historical_suffixed_course_link,242,21,2025-10-17,2026-05-26,0.001280
21,Australia,historical_suffixed_course_link,237,21,2025-10-15,2026-05-23,0.001254
22,New Zealand,explicit_terminal_course_code,236,14,2015-01-01,2025-09-27,0.001248
23,United Arab Emirates,historical_suffixed_course_link,232,4,2025-10-25,2026-04-11,0.001227
24,Chile,explicit_terminal_course_code,198,3,2015-01-02,2025-10-05,0.001047
25,Bahrain,explicit_terminal_course_code,92,2,2015-02-27,2025-03-20,0.000487
26,Sweden,explicit_terminal_course_code,92,3,2015-05-12,2025-09-21,0.000487
27,Japan,historical_suffixed_course_link,89,9,2025-10-18,2026-05-24,0.000471
28,Peru,explicit_terminal_course_code,84,1,2015-01-11,2025-09-14,0.000444
29,Uruguay,explicit_terminal_course_code,68,1,2015-01-06,2025-01-06,0.000360
30,Qatar,explicit_terminal_course_code,64,2,2015-02-26,2025-02-16,0.000339
31,Bahrain,historical_suffixed_course_link,59,1,2025-11-14,2026-04-24,0.000312
32,Turkey,explicit_terminal_course_code,52,2,2015-09-05,2025-09-07,0.000275
33,Switzerland,explicit_terminal_course_code,47,5,2015-07-29,2025-02-16,0.000249
34,Saudi Arabia,explicit_terminal_course_code,41,1,2020-02-29,2025-02-22,0.000217
35,Norway,explicit_terminal_course_code,37,1,2015-06-25,2025-08-24,0.000196
36,Australia,race_context_course_collision_rule,24,2,2025-10-18,2026-05-02,0.000127
37,Argentina,historical_suffixed_course_link,21,3,2025-11-01,2026-05-25,0.000111
38,Germany,historical_suffixed_course_link,21,8,2025-10-17,2026-05-25,0.000111
39,Guernsey,explicit_terminal_course_code,20,1,2015-05-04,2019-05-06,0.000106
40,New Zealand,historical_suffixed_course_link,19,5,2025-10-18,2026-03-28,0.000101
41,South Africa,historical_suffixed_course_link,17,3,2025-11-29,2026-05-23,0.000090
42,South Korea,explicit_terminal_course_code,17,2,2016-09-11,2025-09-07,0.000090
43,Brazil,historical_suffixed_course_link,16,2,2025-10-18,2026-05-03,0.000085
44,Denmark,explicit_terminal_course_code,15,1,2015-06-28,2025-05-24,0.000079
45,Italy,historical_suffixed_course_link,15,2,2025-10-19,2026-05-10,0.000079
46,Spain,explicit_terminal_course_code,14,2,2015-08-15,2023-08-15,0.000074
47,Czech Republic,explicit_terminal_course_code,13,2,2015-10-11,2025-10-12,0.000069
48,China,explicit_terminal_course_code,10,1,2015-04-03,2017-04-02,0.000053
49,Canada,historical_suffixed_course_link,9,1,2025-10-18,2026-05-02,0.000048
50,Saudi Arabia,historical_suffixed_course_link,8,1,2026-02-14,2026-02-14,0.000042
51,Chile,historical_suffixed_course_link,6,3,2025-10-31,2026-05-02,0.000032
52,Qatar,historical_suffixed_course_link,6,1,2025-12-20,2026-02-14,0.000032
53,Belgium,explicit_terminal_course_code,4,3,2017-03-06,2019-08-27,0.000021
54,Peru,historical_suffixed_course_link,4,1,2025-11-23,2026-04-26,0.000021
55,Hungary,explicit_terminal_course_code,3,1,2023-09-02,2025-09-07,0.000016
56,Singapore,explicit_terminal_course_code,3,1,2015-05-17,2023-07-23,0.000016
57,Jersey,historical_suffixed_course_link,2,1,2026-05-10,2026-05-10,0.000011
58,Switzerland,historical_suffixed_course_link,2,1,2026-02-22,2026-02-22,0.000011
59,Uruguay,historical_suffixed_course_link,2,1,2026-01-06,2026-01-06,0.000011
60,Italy,curated_venue_reference,1,1,2026-04-25,2026-04-25,0.000005
61,Poland,explicit_terminal_course_code,1,1,2025-09-28,2025-09-28,0.000005

In [38]:
# Test a candidate canonical venue identity.
#
# Candidate components:
# - candidate jurisdiction derived at race grain;
# - course label with only a recognised terminal jurisdiction code removed.
#
# Examples:
# - "Chantilly (FR)" and later "Chantilly"
#     -> France + Chantilly
# - "Dundalk (AW) (IRE)" and later "Dundalk (AW)"
#     -> Ireland + Dundalk (AW)
# - British Ascot and Australian Ascot
#     -> separated by jurisdiction
#
# Configuration markers such as "(AW)", "(July)" and "(RH)" are retained
# because the notebook has shown that they can carry real source meaning.
#
# This remains a diagnostic candidate, not a final venue dimension.

def remove_terminal_jurisdiction_code(course_name):
    """Remove only a recognised terminal jurisdiction suffix."""
    course_name = str(course_name)

    return re.sub(
        r"\s+\(("
        + "|".join(map(re.escape, terminal_code_to_jurisdiction))
        + r")\)$",
        "",
        course_name,
    ).strip()


candidate_venue_identity = candidate_jurisdiction_evidence.copy()

candidate_venue_identity["candidate_course_label"] = (
    candidate_venue_identity["course"]
    .map(remove_terminal_jurisdiction_code)
)

venue_raw_form_summary = (
    candidate_venue_identity
    .groupby(
        [
            "candidate_jurisdiction",
            "candidate_course_label",
        ],
        as_index=False,
    )
    .agg(
        raw_course_forms=("course", "nunique"),
        provisional_races=("race_name", "size"),
        active_dates=("date", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
)

multi_form_candidate_venues = (
    candidate_venue_identity
    .groupby(
        [
            "candidate_jurisdiction",
            "candidate_course_label",
        ]
    )["course"]
    .agg(
        raw_course_forms="nunique",
        raw_course_values=lambda values: tuple(sorted(set(values))),
    )
    .reset_index()
)

multi_form_candidate_venues = (
    multi_form_candidate_venues.loc[
        multi_form_candidate_venues["raw_course_forms"] > 1
    ]
    .merge(
        venue_raw_form_summary,
        on=[
            "candidate_jurisdiction",
            "candidate_course_label",
            "raw_course_forms",
        ],
        how="left",
    )
    .sort_values(
        [
            "raw_course_forms",
            "provisional_races",
            "candidate_jurisdiction",
            "candidate_course_label",
        ],
        ascending=[False, False, True, True],
    )
    .reset_index(drop=True)
)

jurisdictions_per_course_label = (
    candidate_venue_identity
    .groupby("candidate_course_label")[
        "candidate_jurisdiction"
    ]
    .nunique()
)

cross_jurisdiction_candidate_labels = (
    jurisdictions_per_course_label.loc[
        jurisdictions_per_course_label > 1
    ]
    .sort_values(ascending=False)
)

print(
    "Candidate venue identities: "
    f"{len(venue_raw_form_summary):,}"
)
print(
    "Candidate venues represented by multiple raw course forms: "
    f"{len(multi_form_candidate_venues):,}"
)
print(
    "Course labels occurring in multiple jurisdictions: "
    f"{len(cross_jurisdiction_candidate_labels):,}"
)

print()
print("Cross-jurisdiction candidate course labels:")
print(cross_jurisdiction_candidate_labels.to_string())

multi_form_candidate_venues

Candidate venue identities: 395
Candidate venues represented by multiple raw course forms: 135
Course labels occurring in multiple jurisdictions: 3

Cross-jurisdiction candidate course labels:
candidate_course_label
Ascot        2
Newcastle    2
Sandown      2

,candidate_jurisdiction,candidate_course_label,raw_course_forms,raw_course_values,provisional_races,active_dates,first_date,last_date
0,Hong Kong,Sha Tin,2,"(Sha Tin, Sha Tin (HK))",4543,472,2015-01-25,2026-05-24
1,France,Chantilly,2,"(Chantilly, Chantilly (FR))",4438,533,2015-01-23,2026-05-19
2,France,Deauville,2,"(Deauville, Deauville (FR))",4317,504,2015-01-03,2026-04-08
3,Ireland,Dundalk (AW),2,"(Dundalk (AW), Dundalk (AW) (IRE))",3597,465,2015-01-02,2026-05-26
4,France,Auteuil,2,"(Auteuil, Auteuil (FR))",3356,419,2015-03-01,2026-05-26
5,Hong Kong,Happy Valley,2,"(Happy Valley, Happy Valley (HK))",2938,344,2016-01-06,2026-05-27
6,France,Saint-Cloud,2,"(Saint-Cloud, Saint-Cloud (FR))",2716,330,2015-03-07,2026-05-22
7,France,Longchamp,2,"(Longchamp, Longchamp (FR))",2044,248,2015-04-06,2026-05-24
8,Ireland,Leopardstown,2,"(Leopardstown, Leopardstown (IRE))",1874,256,2015-01-18,2026-05-15
9,Ireland,Curragh,2,"(Curragh, Curragh (IRE))",1823,236,2015-03-29,2026-05-24
10,Ireland,Fairyhouse,2,"(Fairyhouse, Fairyhouse (IRE))",1759,237,2015-01-01,2026-04-06
11,Ireland,Punchestown,2,"(Punchestown, Punchestown (IRE))",1664,226,2015-01-10,2026-05-13
12,Ireland,Naas,2,"(Naas, Naas (IRE))",1579,214,2015-01-04,2026-05-17
13,Ireland,Cork,2,"(Cork, Cork (IRE))",1554,211,2015-01-03,2026-05-19
14,Ireland,Navan,2,"(Navan, Navan (IRE))",1520,204,2015-01-24,2026-05-16
15,Ireland,Gowran Park,2,"(Gowran Park, Gowran Park (IRE))",1519,204,2015-01-22,2026-05-20
16,Ireland,Limerick,2,"(Limerick, Limerick (IRE))",1460,201,2015-03-14,2026-05-21
17,United Arab Emirates,Meydan,2,"(Meydan, Meydan (UAE))",1451,213,2015-01-08,2026-03-28
18,France,Compiegne,2,"(Compiegne, Compiegne (FR))",1084,189,2015-03-09,2026-05-13
19,Ireland,Galway,2,"(Galway, Galway (IRE))",1052,140,2015-07-27,2025-10-27
20,Ireland,Killarney,2,"(Killarney, Killarney (IRE))",1010,135,2015-05-10,2026-05-12
21,Ireland,Down Royal,2,"(Down Royal, Down Royal (IRE))",978,138,2015-02-11,2026-05-04
22,Ireland,Clonmel,2,"(Clonmel, Clonmel (IRE))",932,132,2015-02-10,2026-05-14
23,Ireland,Tramore,2,"(Tramore, Tramore (IRE))",874,125,2015-01-01,2026-04-20
24,United States,Santa Anita,2,"(Santa Anita, Santa Anita (USA))",872,483,2015-01-03,2026-05-26
25,Ireland,Thurles,2,"(Thurles, Thurles (IRE))",869,124,2015-01-05,2026-03-05
26,Ireland,Wexford,2,"(Wexford, Wexford (IRE))",841,116,2015-04-21,2026-05-27
27,Australia,Randwick,2,"(Randwick, Randwick (AUS))",779,173,2015-02-14,2026-04-18
28,United States,Gulfstream Park,2,"(Gulfstream Park, Gulfstream Park (USA))",778,251,2015-01-03,2026-05-09
29,Ireland,Ballinrobe,2,"(Ballinrobe, Ballinrobe (IRE))",773,106,2015-05-25,2026-05-26
30,Ireland,Downpatrick,2,"(Downpatrick, Downpatrick (IRE))",759,108,2015-03-04,2026-05-22
31,Ireland,Roscommon,2,"(Roscommon, Roscommon (IRE))",718,98,2015-05-18,2026-05-18
32,Ireland,Kilbeggan,2,"(Kilbeggan, Kilbeggan (IRE))",707,97,2015-04-24,2026-05-15
33,United Arab Emirates,Jebel Ali,2,"(Jebel Ali, Jebel Ali (UAE))",670,112,2015-01-09,2026-03-15
34,Australia,Caulfield,2,"(Caulfield, Caulfield (AUS))",616,154,2015-02-14,2026-04-04
35,Ireland,Sligo,2,"(Sligo, Sligo (IRE))",614,87,2015-05-03,2026-05-12
36,Ireland,Bellewstown,2,"(Bellewstown, Bellewstown (IRE))",568,75,2015-07-02,2026-04-18
37,Australia,Flemington,2,"(Flemington, Flemington (AUS))",534,143,2015-01-01,2026-03-28
38,Australia,Rosehill,2,"(Rosehill, Rosehill (AUS))",506,120,2015-01-31,2026-03-28
39,United States,Churchill Downs,2,"(Churchill Downs, Churchill Downs (USA))",502,219,2015-04-26,2026-05-25
40,Canada,Woodbine,2,"(Woodbine, Woodbine (CAN))",443,289,2015-04-18,2026-05-02
41,Jersey,Les Landes,2,"(Les Landes, Les Landes (JER))",435,89,2015-04-06,2026-05-10
42,United States,Keeneland,2,"(Keeneland, Keeneland (USA))",433,215,2015-04-03,2026-04-24
43,United States,Del Mar,2,"(Del Mar, Del Mar (USA))",424,257,2015-07-18,2025-11-30
44,United States,Aqueduct,2,"(Aqueduct, Aqueduct (USA))",327,195,2015-01-01,2026-05-09
45,Japan,Tokyo,2,"(Tokyo, Tokyo (JPN))",307,294,2015-02-01,2026-05-24
46,Japan,Nakayama,2,"(Nakayama, Nakayama (JPN))",278,273,2015-01-04,2026-04-19
47,Australia,Moonee Valley,2,"(Moonee Valley, Moonee Valley (AUS))",243,87,2015-01-24,2025-10-25
48,Japan,Hanshin,2,"(Hanshin, Hanshin (JPN))",235,233,2015-02-28,2026-04-18
49,Australia,Ascot,2,"(Ascot, Ascot (AUS))",225,155,2015-01-01,2026-05-02
50,Australia,Morphettville,2,"(Morphettville, Morphettville (AUS))",222,94,2015-02-28,2026-05-09
51,Italy,San Siro,2,"(San Siro, San Siro (ITY))",217,114,2015-04-01,2026-05-10
52,Argentina,Palermo,2,"(Palermo, Palermo (ARG))",209,78,2015-01-03,2026-05-01
53,Japan,Kyoto,2,"(Kyoto, Kyoto (JPN))",200,198,2015-01-04,2026-05-23
54,Argentina,San Isidro,2,"(San Isidro, San Isidro (ARG))",190,84,2015-02-07,2026-05-25
55,France,Cagnes-Sur-Mer,2,"(Cagnes-Sur-Mer, Cagnes-Sur-Mer (FR))",185,90,2015-01-13,2026-02-22
56,United Arab Emirates,Abu Dhabi,2,"(Abu Dhabi, Abu Dhabi (UAE))",184,153,2015-01-04,2026-04-11
57,Australia,Eagle Farm,2,"(Eagle Farm, Eagle Farm (AUS))",171,50,2016-06-11,2026-05-02
58,United States,Oaklawn Park,2,"(Oaklawn Park, Oaklawn Park (USA))",171,107,2015-01-15,2026-04-19
59,Australia,Doomben,2,"(Doomben, Doomben (AUS))",162,53,2015-05-09,2026-05-23
60,Germany,Baden-Baden,2,"(Baden-Baden, Baden-Baden (GER))",161,97,2015-06-04,2025-10-19
61,Italy,Capannelle,2,"(Capannelle, Capannelle (ITY))",151,62,2015-04-19,2025-11-02
62,Brazil,Gavea,2,"(Gavea, Gavea (BRZ))",145,70,2015-01-20,2026-04-12
63,Brazil,Cidade Jardim,2,"(Cidade Jardim, Cidade Jardim (BRZ))",143,75,2015-01-25,2026-05-03
64,Japan,Chukyo,2,"(Chukyo, Chukyo (JPN))",135,134,2015-01-25,2026-03-29
65,South Africa,Turffontein Standside,2,"(Turffontein Standside, Turffontein Standside (SAF))",132,59,2015-11-28,2026-04-04
66,France,Fontainebleau,2,"(Fontainebleau, Fontainebleau (FR))",125,78,2015-03-04,2026-02-26
67,United States,Fair Grounds,2,"(Fair Grounds, Fair Grounds (USA))",123,52,2015-01-17,2026-03-21
68,Bahrain,Bahrain,2,"(Bahrain, Bahrain (BHR))",122,50,2022-11-18,2026-04-24
69,United States,Tampa Bay Downs,2,"(Tampa Bay Downs, Tampa Bay Downs (USA))",113,49,2015-01-04,2026-03-07
70,South Africa,Kenilworth,2,"(Kenilworth, Kenilworth (SAF))",104,60,2015-01-10,2026-02-28
71,Germany,Cologne,2,"(Cologne, Cologne (GER))",101,78,2015-04-06,2026-05-25
72,France,Toulouse,2,"(Toulouse, Toulouse (FR))",98,59,2015-02-17,2026-04-19
73,Germany,Dusseldorf,2,"(Dusseldorf, Dusseldorf (GER))",97,69,2015-04-12,2026-04-25
74,Chile,Hipodromo Chile,2,"(Hipodromo Chile, Hipodromo Chile (CHI))",96,91,2015-05-02,2026-05-02
75,Chile,Club Hipico de Santiago,2,"(Club Hipico de Santiago, Club Hipico de Santiago (CHI))",93,86,2015-02-06,2025-12-26
76,Germany,Hoppegarten,2,"(Hoppegarten, Hoppegarten (GER))",89,68,2015-04-05,2026-05-24
77,Peru,Monterrico,2,"(Monterrico, Monterrico (PER))",88,75,2015-01-11,2026-04-26
78,New Zealand,Ellerslie,2,"(Ellerslie, Ellerslie (NZ))",87,55,2015-01-01,2026-03-07
79,Australia,Newcastle,2,"(Newcastle, Newcastle (AUS))",80,35,2015-03-07,2026-03-06
80,France,Vichy,2,"(Vichy, Vichy (FR))",80,68,2015-07-20,2026-05-13
81,United States,Laurel Park,2,"(Laurel Park, Laurel Park (USA))",78,48,2015-01-01,2026-05-17
82,France,Lyon Parilly,2,"(Lyon Parilly, Lyon Parilly (FR))",74,66,2015-03-20,2025-11-07
83,Germany,Hanover,2,"(Hanover, Hanover (GER))",73,48,2015-05-17,2025-10-26
84,Uruguay,Maronas,2,"(Maronas, Maronas (URU))",70,41,2015-01-06,2026-01-06
85,Japan,Niigata,2,"(Niigata, Niigata (JPN))",68,66,2015-05-10,2026-05-16
86,Qatar,Doha,2,"(Doha, Doha (QA))",67,39,2015-02-26,2026-02-14
87,United Arab Emirates,Sharjah,2,"(Sharjah, Sharjah (UAE))",62,62,2015-03-14,2026-01-25
88,France,Pau,2,"(Pau, Pau (FR))",60,31,2015-12-25,2026-01-18
89,New Zealand,Trentham,2,"(Trentham, Trentham (NZ))",54,42,2015-01-17,2026-03-28
90,Germany,Munich,2,"(Munich, Munich (GER))",52,41,2015-05-01,2026-05-01
91,Japan,Kokura,2,"(Kokura, Kokura (JPN))",51,51,2015-02-22,2026-02-22
92,Australia,Gold Coast,2,"(Gold Coast, Gold Coast (AUS))",50,15,2015-04-25,2026-05-09
93,United States,Los Alamitos,2,"(Los Alamitos, Los Alamitos (USA))",50,43,2015-07-05,2025-12-13
94,Saudi Arabia,Riyadh,2,"(Riyadh, Riyadh (KSA))",49,10,2020-02-29,2026-02-14
95,France,Nantes,2,"(Nantes, Nantes (FR))",47,35,2015-03-24,2026-05-11
96,France,Bordeaux Le Bouscat,2,"(Bordeaux Le Bouscat, Bordeaux Le Bouscat (FR))",44,30,2015-04-05,2026-05-23
97,France,La Teste De Buch,2,"(La Teste De Buch, La Teste De Buch (FR))",44,33,2015-03-20,2026-03-21
98,Japan,Fukushima,2,"(Fukushima, Fukushima (JPN))",43,43,2015-04-25,2026-04-19
99,South Africa,Scottsville,2,"(Scottsville, Scottsville (SAF))",42,12,2015-05-23,2026-05-23
100,Switzerland,St Moritz,2,"(St Moritz, St Moritz (SWI))",42,23,2016-02-14,2026-02-22
101,Australia,Kembla Grange,2,"(Kembla Grange, Kembla Grange (AUS))",41,23,2015-03-09,2026-03-13
102,Argentina,La Plata,2,"(La Plata, La Plata (ARG))",38,29,2015-01-18,2025-11-19
103,Australia,Hawkesbury,2,"(Hawkesbury, Hawkesbury (AUS))",36,13,2015-03-10,2026-05-02
104,Japan,Ohi,2,"(Ohi, Ohi (JPN))",36,32,2015-01-21,2025-12-29
105,France,Marseille Borely,2,"(Marseille Borely, Marseille Borely (FR))",33,27,2015-05-25,2025-10-18
106,Germany,Dortmund,2,"(Dortmund, Dortmund (GER))",33,32,2015-05-14,2026-05-14
107,Australia,Belmont Park (Perth),2,"(Belmont Park (Perth), Belmont Park (Perth) (AUS))",32,32,2015-05-16,2026-05-16
108,New Zealand,Te Rapa,2,"(Te Rapa, Te Rapa (NZ))",31,20,2015-01-31,2026-02-07
109,France,Le Lion-D'Angers,2,"(Le Lion-D'Angers, Le Lion-D'Angers (FR))",30,24,2015-05-08,2026-05-14
110,United States,Far Hills,2,"(Far Hills, Far Hills (USA))",28,10,2015-10-17,2025-10-18
111,Australia,Geelong,2,"(Geelong, Geelong (AUS))",26,16,2015-04-29,2025-10-23
112,Germany,Krefeld,2,"(Krefeld, Krefeld (GER))",26,23,2015-04-26,2025-11-15
113,United States,Turfway Park,2,"(Turfway Park, Turfway Park (USA))",26,17,2015-02-28,2026-03-21
114,Australia,Hobart,2,"(Hobart, Hobart (AUS))",24,19,2015-02-06,2026-02-08
115,Australia,Launceston,2,"(Launceston, Launceston (AUS))",23,16,2015-02-18,2026-02-25
116,Australia,Gosford,2,"(Gosford, Gosford (AUS))",22,16,2015-01-09,2025-12-28
117,New Zealand,Riccarton Park,2,"(Riccarton Park, Riccarton Park (NZ))",22,22,2015-11-07,2025-11-15
118,Australia,Canberra,2,"(Canberra, Canberra (AUS))",19,12,2015-03-08,2026-03-08
119,France,Strasbourg,2,"(Strasbourg, Strasbourg (FR))",19,17,2015-09-27,2025-11-11
120,United States,Sam Houston,2,"(Sam Houston, Sam Houston (USA))",19,13,2015-01-25,2026-01-24
121,Australia,Bendigo,2,"(Bendigo, Bendigo (AUS))",17,15,2015-03-21,2025-10-29
122,United States,Colonial Downs,2,"(Colonial Downs, Colonial Downs (USA))",17,10,2019-09-01,2026-03-14
123,United States,Percy Warner Park,2,"(Percy Warner Park, Percy Warner Park (USA))",16,10,2016-05-14,2026-05-09
124,Australia,Scone,2,"(Scone, Scone (AUS))",15,11,2015-05-16,2026-05-16
125,Chile,Valparaiso Sporting Club,2,"(Valparaiso Sporting Club, Valparaiso Sporting Club (CHI))",15,15,2015-01-02,2026-02-01
126,United States,Lone Star Park,2,"(Lone Star Park, Lone Star Park (USA))",15,15,2015-05-02,2026-05-26
127,United States,Sunland Park,2,"(Sunland Park, Sunland Park (USA))",12,11,2015-01-24,2026-02-15
128,France,Marseille Pont-de-Vivaux,2,"(Marseille Pont-de-Vivaux, Marseille Pont-de-Vivaux (FR))",10,6,2017-02-06,2026-01-05
129,Australia,Northam,2,"(Northam, Northam (AUS))",7,7,2018-05-06,2026-05-03
130,Australia,Pakenham,2,"(Pakenham, Pakenham (AUS))",7,6,2015-03-26,2026-01-23
131,New Zealand,Matamata,2,"(Matamata, Matamata (NZ))",5,5,2015-02-21,2026-02-14
132,United States,Camden (South Carolina),2,"(Camden (South Carolina), Camden (South Carolina) (USA))",4,4,2015-11-21,2025-11-23
133,United States,Great Meadow,2,"(Great Meadow, Great Meadow (USA))",4,4,2019-05-04,2026-05-02
134,United States,Montpelier,2,"(Montpelier, Montpelier (USA))",2,2,2023-11-04,2025-11-01

In [39]:
# Test whether multiple raw course forms assigned to the same candidate
# venue identity coexist on the same date.
#
# Expected safe pattern:
# - an older suffixed form ends;
# - a later unsuffixed form begins;
# - the two forms do not appear on the same date.
#
# Same-date coexistence would warn that jurisdiction + candidate course label
# has merged values representing distinct tracks, configurations or venues.

same_date_candidate_venue_forms = (
    candidate_venue_identity
    .groupby(
        [
            "candidate_jurisdiction",
            "candidate_course_label",
            "date",
        ],
        as_index=False,
    )
    .agg(
        raw_course_forms=("course", "nunique"),
        raw_course_values=(
            "course",
            lambda values: tuple(sorted(set(values))),
        ),
        provisional_races=("race_name", "size"),
    )
)

same_date_candidate_venue_collisions = (
    same_date_candidate_venue_forms.loc[
        same_date_candidate_venue_forms["raw_course_forms"] > 1
    ]
    .sort_values(
        [
            "candidate_jurisdiction",
            "candidate_course_label",
            "date",
        ]
    )
    .reset_index(drop=True)
)

candidate_venues_with_same_date_forms = (
    same_date_candidate_venue_collisions[
        [
            "candidate_jurisdiction",
            "candidate_course_label",
        ]
    ]
    .drop_duplicates()
)

print(
    "Candidate venue identities represented by multiple raw forms: "
    f"{len(multi_form_candidate_venues):,}"
)
print(
    "Candidate venue identities with multiple raw forms on the same date: "
    f"{len(candidate_venues_with_same_date_forms):,}"
)
print(
    "Same-date collision records: "
    f"{len(same_date_candidate_venue_collisions):,}"
)

same_date_candidate_venue_collisions

Candidate venue identities represented by multiple raw forms: 135
Candidate venue identities with multiple raw forms on the same date: 0
Same-date collision records: 0

Empty DataFrame
Columns: [candidate_jurisdiction, candidate_course_label, date, raw_course_forms, raw_course_values, provisional_races]
Index: []

### Surface derivation reset

An earlier attempt derived surface from words such as `Turf`, `Dirt`, `Polytrack`, `Tapeta` and `All-Weather` in `race_name`.

Inspection showed that these terms frequently occur in sponsor names, promotions, memorials and series titles rather than describing the racing surface. That derivation was therefore rejected.

From this point onward:

- `race_name` is not used to derive canonical surface;
- only an explicit `(AW)` marker in raw `course` provides direct source-level surface evidence;
- all remaining surface values stay unresolved pending later external enrichment.

In [40]:
# Rebuild the established candidate surface hierarchy, then summarise it by
# candidate jurisdiction and raw race discipline.
#
# Evidence hierarchy:
# 1. explicit race-name surface wording;
# 2. raw course marked "(AW)";
# 3. otherwise unresolved.
#
# No additional surface inference is introduced.

surface_jurisdiction_profile = candidate_jurisdiction_evidence.copy()

def derive_candidate_surface(row):
    """Derive the directly supported race-level surface category."""
    race_name = str(row["race_name"])
    course_name = str(row["course"])

    has_turf = bool(
        re.search(r"\bTurf\b", race_name, flags=re.IGNORECASE)
    )
    has_dirt = bool(
        re.search(r"\bDirt\b", race_name, flags=re.IGNORECASE)
    )
    has_polytrack = bool(
        re.search(r"\bPolytrack\b", race_name, flags=re.IGNORECASE)
    )
    has_tapeta = bool(
        re.search(r"\bTapeta\b", race_name, flags=re.IGNORECASE)
    )
    has_all_weather = bool(
        re.search(
            r"\bAll[- ]Weather(?: Track)?\b",
            race_name,
            flags=re.IGNORECASE,
        )
    )

    if has_turf:
        return pd.Series(
            ["turf", "explicit_race_name_surface"]
        )

    if has_dirt:
        return pd.Series(
            ["dirt", "explicit_race_name_surface"]
        )

    if has_polytrack:
        return pd.Series(
            ["synthetic_polytrack", "explicit_race_name_surface"]
        )

    if has_tapeta:
        return pd.Series(
            ["synthetic_tapeta", "explicit_race_name_surface"]
        )

    if has_all_weather:
        return pd.Series(
            ["other_all_weather", "explicit_race_name_surface"]
        )

    if "(AW)" in course_name:
        return pd.Series(
            [
                "all_weather_unspecified",
                "raw_course_aw_marker",
            ]
        )

    return pd.Series(
        ["unresolved", "no_direct_surface_evidence"]
    )


surface_jurisdiction_profile[
    ["candidate_surface", "surface_evidence_source"]
] = surface_jurisdiction_profile.apply(
    derive_candidate_surface,
    axis=1,
)

# Add the candidate venue label already validated in the previous section.
surface_jurisdiction_profile["candidate_course_label"] = (
    surface_jurisdiction_profile["course"]
    .map(remove_terminal_jurisdiction_code)
)

surface_jurisdiction_summary = (
    surface_jurisdiction_profile
    .groupby(
        [
            "candidate_jurisdiction",
            "type",
            "candidate_surface",
            "surface_evidence_source",
        ],
        as_index=False,
    )
    .agg(
        provisional_races=("race_name", "size"),
        distinct_candidate_venues=(
            "candidate_course_label",
            "nunique",
        ),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
)

surface_jurisdiction_totals = (
    surface_jurisdiction_profile
    .groupby(
        [
            "candidate_jurisdiction",
            "type",
        ]
    )
    .size()
    .rename("jurisdiction_type_races")
    .reset_index()
)

surface_jurisdiction_summary = (
    surface_jurisdiction_summary
    .merge(
        surface_jurisdiction_totals,
        on=[
            "candidate_jurisdiction",
            "type",
        ],
        how="left",
    )
)

surface_jurisdiction_summary["share_within_jurisdiction_type"] = (
    surface_jurisdiction_summary["provisional_races"]
    / surface_jurisdiction_summary["jurisdiction_type_races"]
)

surface_jurisdiction_summary = (
    surface_jurisdiction_summary
    .sort_values(
        [
            "candidate_jurisdiction",
            "type",
            "provisional_races",
            "candidate_surface",
        ],
        ascending=[True, True, False, True],
    )
    .reset_index(drop=True)
)

resolved_surface_races = (
    surface_jurisdiction_profile["candidate_surface"] != "unresolved"
).sum()

print(
    "Provisional races with directly supported surface: "
    f"{resolved_surface_races:,}"
)
print(
    "Direct surface coverage: "
    f"{resolved_surface_races / len(surface_jurisdiction_profile):.2%}"
)
print(
    "Provisional races with unresolved surface: "
    f"{(
        surface_jurisdiction_profile['candidate_surface']
        == 'unresolved'
    ).sum():,}"
)

surface_jurisdiction_summary

Provisional races with directly supported surface: 79,264
Direct surface coverage: 41.93%
Provisional races with unresolved surface: 109,779

,candidate_jurisdiction,type,candidate_surface,surface_evidence_source,provisional_races,distinct_candidate_venues,first_date,last_date,jurisdiction_type_races,share_within_jurisdiction_type
0,Argentina,Flat,dirt,explicit_race_name_surface,224,3,2015-01-18,2026-05-01,437,0.512586
1,Argentina,Flat,turf,explicit_race_name_surface,212,2,2015-01-03,2026-05-25,437,0.485126
2,Argentina,Flat,unresolved,no_direct_surface_evidence,1,1,2025-06-28,2025-06-28,437,0.002288
3,Australia,Flat,turf,explicit_race_name_surface,4039,50,2015-01-09,2026-05-23,4059,0.995073
4,Australia,Flat,unresolved,no_direct_surface_evidence,19,12,2015-01-01,2020-10-03,4059,0.004681
5,Australia,Flat,synthetic_polytrack,explicit_race_name_surface,1,1,2018-05-06,2018-05-06,4059,0.000246
6,Bahrain,Flat,turf,explicit_race_name_surface,150,2,2015-02-27,2026-04-24,151,0.993377
7,Bahrain,Flat,unresolved,no_direct_surface_evidence,1,1,2024-02-02,2024-02-02,151,0.006623
8,Belgium,Chase,turf,explicit_race_name_surface,1,1,2019-08-27,2019-08-27,1,1.000000
9,Belgium,Flat,unresolved,no_direct_surface_evidence,2,1,2017-03-06,2018-04-16,3,0.666667
10,Belgium,Flat,turf,explicit_race_name_surface,1,1,2017-08-28,2017-08-28,3,0.333333
11,Brazil,Flat,turf,explicit_race_name_surface,281,2,2015-01-20,2026-05-03,289,0.972318
12,Brazil,Flat,dirt,explicit_race_name_surface,5,3,2015-01-20,2015-10-10,289,0.017301
13,Brazil,Flat,unresolved,no_direct_surface_evidence,3,2,2025-05-03,2025-06-21,289,0.010381
14,Canada,Flat,synthetic_tapeta,explicit_race_name_surface,231,1,2016-04-10,2026-05-02,471,0.490446
15,Canada,Flat,turf,explicit_race_name_surface,185,1,2015-05-23,2025-10-04,471,0.392781
16,Canada,Flat,dirt,explicit_race_name_surface,28,3,2015-07-29,2025-09-14,471,0.059448
17,Canada,Flat,synthetic_polytrack,explicit_race_name_surface,24,1,2015-04-18,2015-11-29,471,0.050955
18,Canada,Flat,other_all_weather,explicit_race_name_surface,3,1,2024-05-04,2025-10-11,471,0.006369
19,Chile,Flat,turf,explicit_race_name_surface,107,2,2015-01-02,2026-02-01,204,0.524510
20,Chile,Flat,dirt,explicit_race_name_surface,97,2,2015-02-28,2026-05-02,204,0.475490
21,China,Flat,turf,explicit_race_name_surface,9,1,2015-04-03,2017-04-02,10,0.900000
22,China,Flat,unresolved,no_direct_surface_evidence,1,1,2015-04-03,2015-04-03,10,0.100000
23,Czech Republic,Chase,turf,explicit_race_name_surface,9,1,2015-10-11,2025-10-12,9,1.000000
24,Czech Republic,Flat,turf,explicit_race_name_surface,4,2,2018-09-22,2022-10-09,4,1.000000
25,Denmark,Flat,turf,explicit_race_name_surface,14,1,2015-06-28,2025-05-24,15,0.933333
26,Denmark,Flat,unresolved,no_direct_surface_evidence,1,1,2015-08-02,2015-08-02,15,0.066667
27,France,Chase,turf,explicit_race_name_surface,1996,27,2015-02-24,2026-05-26,2013,0.991555
28,France,Chase,unresolved,no_direct_surface_evidence,17,7,2016-09-11,2025-10-12,2013,0.008445
29,France,Flat,turf,explicit_race_name_surface,9401,58,2015-02-14,2026-05-24,15514,0.605969
30,France,Flat,synthetic_polytrack,explicit_race_name_surface,5944,5,2015-01-03,2026-05-19,15514,0.383138
31,France,Flat,unresolved,no_direct_surface_evidence,99,13,2015-01-15,2025-12-12,15514,0.006381
32,France,Flat,other_all_weather,explicit_race_name_surface,70,7,2015-05-17,2026-04-28,15514,0.004512
33,France,Hurdle,turf,explicit_race_name_surface,2954,30,2015-02-24,2026-05-26,2983,0.990278
34,France,Hurdle,unresolved,no_direct_surface_evidence,29,6,2015-03-02,2024-07-25,2983,0.009722
35,France,NH Flat,turf,explicit_race_name_surface,21,2,2020-10-30,2026-04-17,23,0.913043
36,France,NH Flat,other_all_weather,explicit_race_name_surface,1,1,2024-11-23,2024-11-23,23,0.043478
37,France,NH Flat,synthetic_polytrack,explicit_race_name_surface,1,1,2024-11-23,2024-11-23,23,0.043478
38,Germany,Flat,turf,explicit_race_name_surface,687,17,2015-04-12,2026-05-25,731,0.939808
39,Germany,Flat,unresolved,no_direct_surface_evidence,44,10,2015-04-05,2022-11-13,731,0.060192
40,Great Britain,Chase,unresolved,no_direct_surface_evidence,15647,43,2015-01-01,2026-05-27,15671,0.998469
41,Great Britain,Chase,dirt,explicit_race_name_surface,10,1,2015-09-25,2025-09-26,15671,0.000638
42,Great Britain,Chase,other_all_weather,explicit_race_name_surface,10,5,2018-09-02,2025-12-26,15671,0.000638
43,Great Britain,Chase,turf,explicit_race_name_surface,4,3,2022-09-14,2023-01-31,15671,0.000255
44,Great Britain,Flat,unresolved,no_direct_surface_evidence,40844,37,2015-02-13,2026-05-27,70218,0.581674
45,Great Britain,Flat,all_weather_unspecified,raw_course_aw_marker,28287,6,2015-01-01,2026-05-27,70218,0.402845
46,Great Britain,Flat,synthetic_tapeta,explicit_race_name_surface,718,2,2015-01-02,2026-05-19,70218,0.010225
47,Great Britain,Flat,other_all_weather,explicit_race_name_surface,314,8,2015-01-11,2026-04-03,70218,0.004472
48,Great Britain,Flat,turf,explicit_race_name_surface,53,18,2015-07-28,2026-05-26,70218,0.000755
49,Great Britain,Flat,synthetic_polytrack,explicit_race_name_surface,2,2,2015-09-19,2024-10-02,70218,0.000028
50,Great Britain,Hurdle,unresolved,no_direct_surface_evidence,22619,43,2015-01-01,2026-05-27,22645,0.998852
51,Great Britain,Hurdle,other_all_weather,explicit_race_name_surface,13,4,2017-08-17,2022-09-30,22645,0.000574
52,Great Britain,Hurdle,turf,explicit_race_name_surface,13,4,2021-04-01,2026-02-11,22645,0.000574
53,Great Britain,NH Flat,unresolved,no_direct_surface_evidence,2983,40,2015-01-01,2026-05-26,3100,0.962258
54,Great Britain,NH Flat,all_weather_unspecified,raw_course_aw_marker,93,4,2015-12-01,2024-12-09,3100,0.030000
55,Great Britain,NH Flat,other_all_weather,explicit_race_name_surface,20,4,2015-11-10,2021-05-08,3100,0.006452
56,Great Britain,NH Flat,turf,explicit_race_name_surface,3,2,2021-05-10,2026-03-16,3100,0.000968
57,Great Britain,NH Flat,synthetic_polytrack,explicit_race_name_surface,1,1,2015-01-05,2015-01-05,3100,0.000323
58,Guernsey,Flat,turf,explicit_race_name_surface,15,1,2015-05-04,2019-05-06,20,0.750000
59,Guernsey,Flat,unresolved,no_direct_surface_evidence,5,1,2016-05-02,2016-05-02,20,0.250000
60,Hong Kong,Flat,turf,explicit_race_name_surface,6665,2,2015-01-25,2026-05-27,7481,0.890924
61,Hong Kong,Flat,dirt,explicit_race_name_surface,800,1,2016-11-27,2026-05-06,7481,0.106938
62,Hong Kong,Flat,other_all_weather,explicit_race_name_surface,11,1,2026-03-08,2026-04-19,7481,0.001470
63,Hong Kong,Flat,unresolved,no_direct_surface_evidence,5,1,2019-03-02,2025-11-15,7481,0.000668
64,Hungary,Flat,turf,explicit_race_name_surface,3,1,2023-09-02,2025-09-07,3,1.000000
65,Ireland,Chase,unresolved,no_direct_surface_evidence,4833,23,2015-01-01,2026-05-25,4833,1.000000
66,Ireland,Flat,unresolved,no_direct_surface_evidence,11155,25,2015-01-01,2026-05-24,14763,0.755605
67,Ireland,Flat,all_weather_unspecified,raw_course_aw_marker,3592,1,2015-01-02,2026-05-26,14763,0.243311
68,Ireland,Flat,turf,explicit_race_name_surface,10,2,2022-08-11,2025-10-19,14763,0.000677
69,Ireland,Flat,other_all_weather,explicit_race_name_surface,6,2,2016-02-19,2022-04-23,14763,0.000406
70,Ireland,Hurdle,unresolved,no_direct_surface_evidence,9667,24,2015-01-01,2026-05-27,9667,1.000000
71,Ireland,NH Flat,unresolved,no_direct_surface_evidence,1520,24,2015-01-03,2026-05-27,1520,1.000000
72,Italy,Chase,turf,explicit_race_name_surface,2,1,2015-09-27,2016-09-25,2,1.000000
73,Italy,Flat,turf,explicit_race_name_surface,364,8,2015-04-01,2026-05-10,385,0.945455
74,Italy,Flat,unresolved,no_direct_surface_evidence,21,2,2015-04-19,2023-05-21,385,0.054545
75,Italy,Hurdle,turf,explicit_race_name_surface,1,1,2015-09-26,2015-09-26,1,1.000000
76,Japan,Chase,unresolved,no_direct_surface_evidence,4,1,2015-12-26,2018-12-22,7,0.571429
77,Japan,Chase,turf,explicit_race_name_surface,3,2,2021-04-17,2022-04-16,7,0.428571
78,Japan,Flat,turf,explicit_race_name_surface,1214,11,2015-01-04,2026-05-24,1546,0.785252
79,Japan,Flat,dirt,explicit_race_name_surface,331,21,2015-01-21,2026-05-23,1546,0.214101
80,Japan,Flat,unresolved,no_direct_surface_evidence,1,1,2019-04-13,2019-04-13,1546,0.000647
81,Japan,Hurdle,turf,explicit_race_name_surface,6,3,2018-06-23,2026-04-18,6,1.000000
82,Jersey,Flat,turf,explicit_race_name_surface,220,1,2015-06-26,2026-05-10,350,0.628571
83,Jersey,Flat,unresolved,no_direct_surface_evidence,130,1,2015-04-06,2022-07-08,350,0.371429
84,Jersey,Hurdle,turf,explicit_race_name_surface,49,1,2015-06-26,2026-05-10,85,0.576471
85,Jersey,Hurdle,unresolved,no_direct_surface_evidence,36,1,2015-04-06,2022-07-08,85,0.423529
86,New Zealand,Flat,turf,explicit_race_name_surface,247,13,2015-01-01,2026-03-28,255,0.968627
87,New Zealand,Flat,unresolved,no_direct_surface_evidence,7,3,2015-01-01,2015-02-06,255,0.027451
88,New Zealand,Flat,synthetic_polytrack,explicit_race_name_surface,1,1,2025-05-03,2025-05-03,255,0.003922
89,Norway,Flat,turf,explicit_race_name_surface,35,1,2015-06-25,2025-08-24,37,0.945946
90,Norway,Flat,unresolved,no_direct_surface_evidence,2,1,2015-08-23,2016-06-02,37,0.054054
91,Peru,Flat,dirt,explicit_race_name_surface,64,1,2015-01-11,2025-11-23,88,0.727273
92,Peru,Flat,turf,explicit_race_name_surface,24,1,2015-01-18,2026-04-26,88,0.272727
93,Poland,Flat,turf,explicit_race_name_surface,1,1,2025-09-28,2025-09-28,1,1.000000
94,Qatar,Flat,turf,explicit_race_name_surface,68,2,2015-02-26,2026-02-14,70,0.971429
95,Qatar,Flat,dirt,explicit_race_name_surface,1,1,2020-01-22,2020-01-22,70,0.014286
96,Qatar,Flat,unresolved,no_direct_surface_evidence,1,1,2019-04-04,2019-04-04,70,0.014286
97,Saudi Arabia,Flat,dirt,explicit_race_name_surface,28,1,2020-02-29,2026-02-14,49,0.571429
98,Saudi Arabia,Flat,turf,explicit_race_name_surface,21,1,2020-02-29,2026-02-14,49,0.428571
99,Singapore,Flat,turf,explicit_race_name_surface,3,1,2015-05-17,2023-07-23,3,1.000000
100,South Africa,Flat,turf,explicit_race_name_surface,450,8,2015-01-24,2026-05-23,470,0.957447
101,South Africa,Flat,unresolved,no_direct_surface_evidence,12,3,2015-01-10,2021-06-06,470,0.025532
102,South Africa,Flat,synthetic_polytrack,explicit_race_name_surface,8,1,2020-03-18,2020-03-18,470,0.017021
103,South Korea,Flat,dirt,explicit_race_name_surface,15,2,2017-09-10,2025-09-07,17,0.882353
104,South Korea,Flat,unresolved,no_direct_surface_evidence,2,1,2016-09-11,2016-09-11,17,0.117647
105,Spain,Flat,turf,explicit_race_name_surface,12,2,2015-08-15,2023-08-15,14,0.857143
106,Spain,Flat,unresolved,no_direct_surface_evidence,2,1,2015-08-23,2016-08-21,14,0.142857
107,Sweden,Flat,turf,explicit_race_name_surface,59,2,2015-06-09,2025-09-21,89,0.662921
108,Sweden,Flat,dirt,explicit_race_name_surface,30,3,2015-05-12,2022-09-18,89,0.337079
109,Sweden,Hurdle,turf,explicit_race_name_surface,3,1,2022-09-18,2024-09-15,3,1.000000
110,Switzerland,Chase,turf,explicit_race_name_surface,1,1,2023-10-08,2023-10-08,1,1.000000
111,Switzerland,Flat,unresolved,no_direct_surface_evidence,41,2,2015-07-29,2026-02-22,48,0.854167
112,Switzerland,Flat,turf,explicit_race_name_surface,7,4,2015-09-13,2019-09-22,48,0.145833
113,Turkey,Flat,turf,explicit_race_name_surface,43,2,2015-09-05,2025-09-07,52,0.826923
114,Turkey,Flat,synthetic_polytrack,explicit_race_name_surface,9,1,2015-09-05,2025-09-06,52,0.173077
115,United Arab Emirates,Flat,dirt,explicit_race_name_surface,1676,4,2015-01-08,2026-03-28,2451,0.683803
116,United Arab Emirates,Flat,turf,explicit_race_name_surface,774,2,2015-01-04,2026-04-11,2451,0.315789
117,United Arab Emirates,Flat,unresolved,no_direct_surface_evidence,1,1,2017-03-10,2017-03-10,2451,0.000408
118,United States,Chase,turf,explicit_race_name_surface,6,2,2016-11-19,2023-08-23,10,0.600000
119,United States,Chase,unresolved,no_direct_surface_evidence,4,3,2015-08-06,2019-05-04,10,0.400000
120,United States,Flat,dirt,explicit_race_name_surface,3502,42,2015-01-01,2026-05-26,6023,0.581438
121,United States,Flat,turf,explicit_race_name_surface,2405,30,2015-01-03,2026-05-26,6023,0.399303
122,United States,Flat,synthetic_tapeta,explicit_race_name_surface,67,4,2015-01-17,2026-03-21,6023,0.011124
123,United States,Flat,synthetic_polytrack,explicit_race_name_surface,30,2,2015-02-28,2021-08-28,6023,0.004981
124,United States,Flat,unresolved,no_direct_surface_evidence,17,8,2019-04-07,2025-10-31,6023,0.002823
125,United States,Flat,other_all_weather,explicit_race_name_surface,2,2,2017-07-02,2024-12-15,6023,0.000332
126,United States,Hurdle,turf,explicit_race_name_surface,69,9,2015-08-27,2026-05-09,72,0.958333
127,United States,Hurdle,unresolved,no_direct_surface_evidence,3,2,2015-09-24,2018-05-12,72,0.041667
128,Uruguay,Flat,dirt,explicit_race_name_surface,70,1,2015-01-06,2026-01-06,70,1.000000

In [41]:
# Test whether unresolved British and Irish venue/type combinations can safely
# inherit a venue/configuration-level surface default.
#
# For each candidate jurisdiction-qualified course label, this cell reports:
# - unresolved race counts;
# - directly observed surface families elsewhere at that same venue;
# - whether more than one explicit surface family has been observed.
#
# This allows us to distinguish:
# - ordinary turf venues where missing surface text can reasonably inherit turf;
# - all-weather configurations already encoded in raw course;
# - mixed-surface venues where a broad venue-level rule would be unsafe.
#
# No missing surface value is filled in here.

uk_ire_surface_profile = surface_jurisdiction_profile.loc[
    surface_jurisdiction_profile["candidate_jurisdiction"].isin(
        ["Great Britain", "Ireland"]
    )
].copy()

explicit_surface_families_by_venue = (
    uk_ire_surface_profile.loc[
        uk_ire_surface_profile["candidate_surface"] != "unresolved"
    ]
    .groupby(
        [
            "candidate_jurisdiction",
            "candidate_course_label",
        ]
    )["candidate_surface"]
    .agg(
        explicit_surface_family_count="nunique",
        explicit_surface_families=lambda values: tuple(
            sorted(set(values))
        ),
    )
    .reset_index()
)

unresolved_uk_ire_by_venue = (
    uk_ire_surface_profile.loc[
        uk_ire_surface_profile["candidate_surface"] == "unresolved"
    ]
    .groupby(
        [
            "candidate_jurisdiction",
            "candidate_course_label",
            "type",
        ],
        as_index=False,
    )
    .agg(
        unresolved_races=("race_name", "size"),
        active_dates=("date", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
)

unresolved_uk_ire_venue_context = (
    unresolved_uk_ire_by_venue
    .merge(
        explicit_surface_families_by_venue,
        on=[
            "candidate_jurisdiction",
            "candidate_course_label",
        ],
        how="left",
    )
)

unresolved_uk_ire_venue_context[
    "explicit_surface_family_count"
] = (
    unresolved_uk_ire_venue_context[
        "explicit_surface_family_count"
    ]
    .fillna(0)
    .astype(int)
)

unresolved_uk_ire_venue_context[
    "explicit_surface_families"
] = unresolved_uk_ire_venue_context[
    "explicit_surface_families"
].map(
    lambda value: value if isinstance(value, tuple) else tuple()
)

unresolved_uk_ire_venue_context = (
    unresolved_uk_ire_venue_context
    .sort_values(
        [
            "unresolved_races",
            "candidate_jurisdiction",
            "candidate_course_label",
            "type",
        ],
        ascending=[False, True, True, True],
    )
    .reset_index(drop=True)
)

print(
    "Unresolved British and Irish races assessed: "
    f"{unresolved_uk_ire_venue_context['unresolved_races'].sum():,}"
)
print(
    "Venue/type groups assessed: "
    f"{len(unresolved_uk_ire_venue_context):,}"
)
print(
    "Groups at venues with multiple directly observed surface families: "
    f"{(
        unresolved_uk_ire_venue_context[
            'explicit_surface_family_count'
        ] > 1
    ).sum():,}"
)

unresolved_uk_ire_venue_context

Unresolved British and Irish races assessed: 109,268
Venue/type groups assessed: 259
Groups at venues with multiple directly observed surface families: 7

,candidate_jurisdiction,candidate_course_label,type,unresolved_races,active_dates,first_date,last_date,explicit_surface_family_count,explicit_surface_families
0,Great Britain,Doncaster,Flat,1896,259,2015-03-28,2026-05-16,0,()
1,Great Britain,Windsor,Flat,1882,267,2015-04-13,2026-05-25,1,"(other_all_weather,)"
2,Ireland,Curragh,Flat,1823,236,2015-03-29,2026-05-24,0,()
3,Great Britain,Haydock,Flat,1645,246,2015-04-25,2026-05-23,1,"(turf,)"
4,Great Britain,Nottingham,Flat,1642,230,2015-04-08,2026-05-19,0,()
5,Great Britain,Yarmouth,Flat,1626,230,2015-08-30,2026-05-20,1,"(turf,)"
6,Great Britain,Bath,Flat,1530,216,2015-04-17,2026-05-26,1,"(turf,)"
7,Great Britain,Newmarket,Flat,1502,205,2015-04-15,2026-05-16,1,"(synthetic_polytrack,)"
8,Great Britain,Brighton,Flat,1480,214,2015-04-21,2025-10-16,1,"(turf,)"
9,Great Britain,Beverley,Flat,1444,199,2015-04-15,2026-05-27,0,()
10,Great Britain,Newmarket (July),Flat,1438,208,2015-06-19,2025-08-23,0,()
11,Great Britain,Leicester,Flat,1390,197,2015-04-10,2026-05-26,0,()
12,Great Britain,Newbury,Flat,1378,188,2015-04-17,2026-05-16,1,"(turf,)"
13,Great Britain,Redcar,Flat,1377,182,2015-04-06,2026-05-26,0,()
14,Great Britain,Goodwood,Flat,1369,199,2015-05-02,2026-05-23,1,"(turf,)"
15,Great Britain,Ayr,Flat,1347,186,2015-04-27,2026-05-20,0,()
16,Great Britain,York,Flat,1338,193,2015-05-13,2026-05-23,0,()
17,Great Britain,Catterick,Flat,1312,181,2015-04-08,2026-05-21,0,()
18,Great Britain,Hamilton,Flat,1308,187,2015-05-03,2026-05-27,0,()
19,Great Britain,Ascot,Flat,1243,188,2015-04-29,2026-05-09,1,"(turf,)"
20,Great Britain,Musselburgh,Flat,1238,175,2015-04-03,2026-05-21,0,()
21,Ireland,Leopardstown,Flat,1229,184,2015-02-08,2026-05-15,1,"(turf,)"
22,Great Britain,Thirsk,Flat,1224,165,2015-04-18,2026-05-16,0,()
23,Great Britain,Ripon,Flat,1192,176,2015-04-16,2026-05-17,0,()
24,Great Britain,Pontefract,Flat,1169,166,2015-04-07,2026-05-22,0,()
25,Great Britain,Salisbury,Flat,1128,161,2015-05-03,2026-05-23,1,"(turf,)"
26,Great Britain,Uttoxeter,Hurdle,1121,256,2015-01-24,2026-05-24,1,"(turf,)"
27,Great Britain,Chepstow,Flat,1100,157,2015-05-01,2026-05-21,2,"(other_all_weather, turf)"
28,Great Britain,Chester,Flat,1081,156,2015-05-06,2026-05-08,1,"(turf,)"
29,Great Britain,Sandown,Flat,1050,161,2015-02-13,2026-04-24,0,()
30,Great Britain,Lingfield,Flat,992,172,2015-05-08,2026-05-26,0,()
31,Ireland,Gowran Park,Flat,979,142,2015-03-21,2026-05-20,0,()
32,Ireland,Naas,Flat,969,142,2015-02-22,2026-05-17,0,()
33,Great Britain,Carlisle,Flat,903,126,2015-05-25,2026-05-18,1,"(turf,)"
34,Ireland,Punchestown,Hurdle,895,219,2015-01-10,2026-05-13,0,()
35,Great Britain,Market Rasen,Hurdle,878,224,2015-01-15,2026-05-08,1,"(other_all_weather,)"
36,Great Britain,Fontwell,Hurdle,872,227,2015-02-12,2026-05-24,1,"(other_all_weather,)"
37,Great Britain,Worcester,Hurdle,805,194,2015-05-07,2026-05-22,2,"(dirt, other_all_weather)"
38,Great Britain,Southwell,Hurdle,780,198,2015-02-22,2026-05-11,1,"(other_all_weather,)"
39,Ireland,Navan,Flat,776,122,2015-04-18,2026-05-16,0,()
40,Great Britain,Huntingdon,Hurdle,741,192,2015-01-09,2026-05-25,0,()
41,Ireland,Cork,Flat,729,123,2015-04-04,2026-05-19,0,()
42,Ireland,Fairyhouse,Hurdle,728,179,2015-01-01,2026-04-06,1,"(turf,)"
43,Great Britain,Sedgefield,Hurdle,721,190,2015-01-06,2026-04-10,1,"(other_all_weather,)"
44,Great Britain,Epsom,Flat,716,111,2015-04-22,2026-04-28,0,()
45,Great Britain,Newton Abbot,Hurdle,690,179,2015-03-25,2026-05-27,0,()
46,Great Britain,Plumpton,Hurdle,690,175,2015-01-04,2026-05-26,0,()
47,Ireland,Limerick,Hurdle,690,146,2015-03-14,2026-04-16,1,"(other_all_weather,)"
48,Great Britain,Warwick,Hurdle,672,186,2015-01-10,2026-05-20,0,()
49,Great Britain,Chepstow,Hurdle,653,169,2015-01-30,2026-04-24,2,"(other_all_weather, turf)"
50,Great Britain,Taunton,Hurdle,645,145,2015-01-07,2026-04-22,0,()
51,Great Britain,Exeter,Hurdle,641,170,2015-01-01,2026-04-17,0,()
52,Great Britain,Perth,Hurdle,629,155,2015-04-22,2026-05-14,0,()
53,Great Britain,Stratford,Hurdle,629,168,2015-03-09,2026-05-17,0,()
54,Great Britain,Ludlow,Hurdle,627,167,2015-01-07,2026-05-10,0,()
55,Great Britain,Cheltenham,Chase,607,175,2015-01-01,2026-03-13,0,()
56,Great Britain,Uttoxeter,Chase,607,255,2015-01-24,2026-05-24,1,"(turf,)"
57,Great Britain,Wincanton,Hurdle,600,159,2015-01-03,2026-04-12,0,()
58,Great Britain,Hexham,Hurdle,592,159,2015-03-12,2026-05-19,1,"(other_all_weather,)"
59,Great Britain,Fontwell,Chase,591,230,2015-02-12,2026-05-24,1,"(other_all_weather,)"
60,Ireland,Cork,Hurdle,574,116,2015-01-03,2026-05-10,0,()
61,Great Britain,Wetherby,Hurdle,572,154,2015-01-10,2026-03-27,0,()
62,Great Britain,Ffos Las,Hurdle,568,151,2015-01-02,2026-05-20,1,"(turf,)"
63,Ireland,Clonmel,Hurdle,553,119,2015-02-10,2026-05-14,0,()
64,Great Britain,Ffos Las,Flat,542,81,2015-07-21,2025-09-28,1,"(turf,)"
65,Great Britain,Kelso,Hurdle,541,152,2015-01-11,2026-05-24,1,"(turf,)"
66,Great Britain,Market Rasen,Chase,537,222,2015-01-15,2026-05-08,1,"(other_all_weather,)"
67,Great Britain,Bangor-on-Dee,Hurdle,536,145,2015-01-06,2026-05-23,1,"(turf,)"
68,Great Britain,Cheltenham,Hurdle,536,165,2015-01-01,2026-03-13,0,()
69,Great Britain,Ayr,Hurdle,533,142,2015-01-02,2026-04-18,0,()
70,Great Britain,Doncaster,Hurdle,525,131,2015-01-09,2026-03-13,0,()
71,Ireland,Punchestown,Chase,497,183,2015-01-10,2026-05-02,0,()
72,Great Britain,Warwick,Chase,491,187,2015-01-10,2026-05-20,0,()
73,Ireland,Killarney,Flat,488,94,2015-05-12,2026-05-12,0,()
74,Great Britain,Stratford,Chase,487,176,2015-03-09,2026-05-17,0,()
75,Great Britain,Hereford,Hurdle,482,122,2016-10-06,2026-05-12,1,"(turf,)"
76,Great Britain,Kempton,Hurdle,482,130,2015-01-10,2026-03-23,0,()
77,Ireland,Galway,Flat,481,103,2015-07-27,2025-10-27,0,()
78,Ireland,Tipperary,Flat,481,84,2015-04-09,2025-10-05,0,()
79,Ireland,Downpatrick,Hurdle,471,108,2015-03-04,2026-05-22,0,()
80,Ireland,Fairyhouse,Flat,471,95,2015-01-01,2026-04-06,1,"(turf,)"
81,Great Britain,Sedgefield,Chase,462,190,2015-01-06,2026-04-10,1,"(other_all_weather,)"
82,Great Britain,Southwell,Chase,457,198,2015-02-22,2026-05-11,1,"(other_all_weather,)"
83,Great Britain,Worcester,Chase,457,194,2015-05-07,2026-05-22,2,"(dirt, other_all_weather)"
84,Great Britain,Musselburgh,Hurdle,453,115,2015-01-01,2026-03-20,0,()
85,Ireland,Wexford,Hurdle,453,108,2015-04-21,2026-05-27,0,()
86,Great Britain,Newcastle,Hurdle,450,122,2015-01-03,2026-04-11,1,"(other_all_weather,)"
87,Great Britain,Kelso,Chase,448,150,2015-01-11,2026-05-24,1,"(turf,)"
88,Ireland,Fairyhouse,Chase,448,170,2015-01-01,2026-04-06,1,"(turf,)"
89,Ireland,Navan,Hurdle,445,104,2015-01-24,2026-03-21,0,()
90,Great Britain,Newton Abbot,Chase,444,178,2015-03-25,2026-05-27,0,()
91,Great Britain,Fakenham,Hurdle,443,126,2015-01-01,2026-05-04,0,()
92,Great Britain,Chepstow,Chase,442,170,2015-01-30,2026-04-24,2,"(other_all_weather, turf)"
93,Great Britain,Exeter,Chase,440,164,2015-01-01,2026-04-07,0,()
94,Ireland,Thurles,Hurdle,438,114,2015-01-05,2026-03-05,0,()
95,Great Britain,Huntingdon,Chase,437,192,2015-01-09,2026-05-25,0,()
96,Great Britain,Carlisle,Hurdle,433,124,2015-02-16,2026-04-04,1,"(turf,)"
97,Great Britain,Ludlow,Chase,431,167,2015-01-07,2026-05-10,0,()
98,Great Britain,Newbury,Hurdle,430,122,2015-01-14,2026-03-21,1,"(turf,)"
99,Great Britain,Hexham,Chase,429,158,2015-03-12,2026-05-19,1,"(other_all_weather,)"
100,Ireland,Tramore,Hurdle,429,112,2015-01-01,2026-04-20,0,()
101,Ireland,Kilbeggan,Hurdle,428,97,2015-04-24,2026-05-15,0,()
102,Great Britain,Wincanton,Chase,424,158,2015-01-03,2026-04-12,0,()
103,Ireland,Ballinrobe,Hurdle,424,82,2015-05-25,2026-05-26,0,()
104,Great Britain,Plumpton,Chase,413,174,2015-01-04,2026-05-26,0,()
105,Great Britain,Perth,Chase,407,155,2015-04-22,2026-05-14,0,()
106,Great Britain,Wetherby,Chase,406,154,2015-01-10,2026-03-27,0,()
107,Ireland,Roscommon,Flat,403,71,2015-05-18,2026-05-18,0,()
108,Great Britain,Catterick,Hurdle,384,106,2015-01-01,2026-03-04,0,()
109,Ireland,Bellewstown,Flat,373,62,2015-07-02,2026-04-11,0,()
110,Great Britain,Ffos Las,Chase,372,151,2015-01-02,2026-05-20,1,"(turf,)"
111,Ireland,Limerick,Flat,370,71,2015-04-16,2026-04-25,1,"(other_all_weather,)"
112,Great Britain,Bangor-on-Dee,Chase,365,142,2015-01-06,2026-05-23,1,"(turf,)"
113,Great Britain,Kempton,Chase,362,130,2015-01-10,2026-03-23,0,()
114,Great Britain,Carlisle,Chase,358,121,2015-02-16,2026-04-04,1,"(turf,)"
115,Ireland,Down Royal,Hurdle,355,94,2015-02-11,2026-05-04,0,()
116,Great Britain,Cartmel,Hurdle,353,92,2015-05-25,2026-05-27,0,()
117,Ireland,Naas,Hurdle,347,86,2015-01-04,2026-03-08,0,()
118,Great Britain,Ayr,Chase,346,142,2015-01-02,2026-04-18,0,()
119,Ireland,Leopardstown,Hurdle,343,91,2015-01-18,2026-03-03,1,"(turf,)"
120,Great Britain,Newbury,Chase,341,122,2015-01-14,2026-03-21,1,"(turf,)"
121,Great Britain,Haydock,Hurdle,339,96,2015-01-17,2026-05-09,1,"(turf,)"
122,Great Britain,Leicester,Chase,339,87,2015-01-08,2026-03-06,0,()
123,Ireland,Down Royal,Flat,330,58,2015-06-20,2025-09-29,0,()
124,Ireland,Gowran Park,Hurdle,330,76,2015-01-22,2026-03-07,0,()
125,Great Britain,Sandown,Hurdle,328,94,2015-01-03,2026-04-25,0,()
126,Great Britain,Doncaster,Chase,326,131,2015-01-09,2026-03-13,0,()
127,Great Britain,Fakenham,Chase,319,124,2015-01-01,2026-05-04,0,()
128,Ireland,Galway,Hurdle,319,112,2015-07-27,2025-10-26,0,()
129,Great Britain,Newcastle,Chase,318,123,2015-01-03,2026-04-11,1,"(other_all_weather,)"
130,Ireland,Listowel,Flat,310,68,2015-05-31,2025-09-26,0,()
131,Ireland,Limerick,Chase,302,110,2015-03-15,2026-05-21,1,"(other_all_weather,)"
132,Great Britain,Taunton,Chase,290,140,2015-01-07,2026-04-09,0,()
133,Great Britain,Aintree,Hurdle,288,87,2015-04-09,2026-05-15,0,()
134,Great Britain,Hereford,Chase,287,122,2016-10-06,2026-05-12,1,"(turf,)"
135,Great Britain,Cartmel,Chase,286,92,2015-05-25,2026-05-27,0,()
136,Ireland,Thurles,Chase,286,114,2015-01-05,2026-03-05,0,()
137,Great Britain,Sandown,Chase,285,95,2015-01-03,2026-04-25,0,()
138,Ireland,Sligo,Hurdle,279,46,2015-05-20,2026-05-12,0,()
139,Ireland,Listowel,Hurdle,277,74,2015-06-01,2025-09-27,0,()
140,Great Britain,Ascot,Hurdle,276,85,2015-01-17,2026-03-29,1,"(turf,)"
141,Ireland,Wexford,Chase,271,100,2015-04-21,2026-05-16,0,()
142,Ireland,Killarney,Hurdle,270,75,2015-05-10,2026-05-11,0,()
143,Great Britain,Catterick,Chase,268,106,2015-01-01,2026-03-04,0,()
144,Ireland,Tramore,Chase,268,112,2015-01-01,2026-04-20,0,()
145,Great Britain,Musselburgh,Chase,266,108,2015-01-01,2026-02-15,0,()
146,Great Britain,Lingfield,Hurdle,265,76,2015-01-05,2026-02-05,0,()
147,Great Britain,Aintree,Chase,264,87,2015-04-09,2026-05-15,0,()
148,Great Britain,Haydock,Chase,263,91,2015-01-17,2026-04-15,1,"(turf,)"
149,Great Britain,Leicester,Hurdle,260,62,2015-01-08,2026-01-20,0,()
150,Great Britain,Ascot,Chase,252,85,2015-01-17,2026-03-29,1,"(turf,)"
151,Great Britain,Wetherby,Flat,238,33,2015-04-26,2026-04-26,0,()
152,Ireland,Tipperary,Hurdle,237,61,2015-04-17,2025-10-06,0,()
153,Ireland,Clonmel,Chase,235,94,2015-02-10,2026-04-14,0,()
154,Ireland,Navan,Chase,230,98,2015-01-24,2026-03-21,0,()
155,Ireland,Sligo,Flat,219,42,2015-05-03,2026-05-03,0,()
156,Ireland,Leopardstown,Chase,218,91,2015-01-18,2026-03-03,1,"(turf,)"
157,Ireland,Down Royal,Chase,216,78,2015-02-11,2026-05-04,0,()
158,Ireland,Killarney,Chase,202,65,2015-05-10,2026-05-11,0,()
159,Great Britain,Lingfield,Chase,197,76,2015-01-05,2026-02-05,0,()
160,Ireland,Downpatrick,Chase,197,79,2015-03-04,2026-05-22,0,()
161,Ireland,Naas,Chase,196,80,2015-01-04,2026-03-08,0,()
162,Ireland,Kilbeggan,Chase,193,92,2015-04-24,2026-05-15,0,()
163,Ireland,Roscommon,Hurdle,191,45,2015-06-09,2025-09-29,0,()
164,Ireland,Ballinrobe,Flat,185,42,2015-06-23,2026-05-08,0,()
165,Ireland,Bellewstown,Hurdle,182,31,2015-07-02,2026-04-18,0,()
166,Ireland,Cork,Chase,181,75,2015-01-03,2026-04-06,0,()
167,Ireland,Galway,Chase,180,94,2015-07-28,2025-10-26,0,()
168,Ireland,Gowran Park,Chase,170,60,2015-01-22,2026-03-07,0,()
169,Ireland,Punchestown,NH Flat,160,140,2015-02-01,2026-05-13,0,()
170,Great Britain,Warwick,NH Flat,141,129,2015-01-10,2026-05-09,0,()
171,Great Britain,Huntingdon,NH Flat,138,129,2015-01-09,2026-05-07,0,()
172,Ireland,Tipperary,Chase,137,42,2015-04-17,2025-10-05,0,()
173,Great Britain,Southwell,NH Flat,133,126,2015-02-22,2026-05-11,1,"(other_all_weather,)"
174,Great Britain,Towcester,Hurdle,130,39,2015-01-29,2018-05-21,0,()
175,Great Britain,Market Rasen,NH Flat,127,123,2015-02-15,2026-04-14,1,"(other_all_weather,)"
176,Great Britain,Worcester,NH Flat,125,113,2015-05-22,2026-05-22,2,"(dirt, other_all_weather)"
177,Ireland,Listowel,Chase,122,69,2015-06-01,2025-09-27,0,()
178,Ireland,Tramore,Flat,121,43,2015-04-12,2025-08-16,0,()
179,Great Britain,Newcastle,Flat,118,16,2015-04-11,2015-09-04,1,"(other_all_weather,)"
180,Great Britain,Chepstow,NH Flat,117,107,2015-01-30,2026-04-02,2,"(other_all_weather, turf)"
181,Great Britain,Fontwell,NH Flat,114,112,2015-02-12,2026-05-24,1,"(other_all_weather,)"
182,Ireland,Punchestown,Flat,112,66,2015-02-18,2025-09-16,0,()
183,Ireland,Fairyhouse,NH Flat,111,108,2015-01-21,2026-04-04,1,"(turf,)"
184,Great Britain,Newcastle,NH Flat,110,78,2015-01-03,2026-04-11,1,"(other_all_weather,)"
185,Ireland,Ballinrobe,Chase,106,48,2015-05-25,2026-05-25,0,()
186,Great Britain,Uttoxeter,NH Flat,102,99,2015-03-14,2026-05-24,1,"(turf,)"
187,Great Britain,Towcester,Chase,101,39,2015-01-29,2018-05-21,0,()
188,Great Britain,Ayr,NH Flat,99,97,2015-01-02,2026-04-18,0,()
189,Ireland,Limerick,NH Flat,97,92,2015-03-14,2026-04-16,1,"(other_all_weather,)"
190,Great Britain,Sedgefield,NH Flat,93,93,2015-01-06,2026-04-01,1,"(other_all_weather,)"
191,Great Britain,Stratford,NH Flat,92,90,2015-03-09,2026-05-17,0,()
192,Ireland,Roscommon,Chase,90,35,2015-05-18,2025-09-29,0,()
193,Ireland,Clonmel,Flat,89,27,2015-05-07,2025-09-11,0,()
194,Great Britain,Exeter,NH Flat,88,87,2015-01-01,2026-04-17,0,()
195,Ireland,Sligo,Chase,84,12,2015-09-30,2025-10-01,0,()
196,Great Britain,Ffos Las,NH Flat,82,80,2015-01-02,2026-03-01,1,"(turf,)"
197,Great Britain,Bangor-on-Dee,NH Flat,81,73,2015-01-06,2026-05-23,1,"(turf,)"
198,Great Britain,Carlisle,NH Flat,80,79,2015-03-05,2026-03-22,1,"(turf,)"
199,Great Britain,Wetherby,NH Flat,80,74,2015-01-10,2026-03-27,0,()
200,Great Britain,Ludlow,NH Flat,79,77,2015-01-07,2026-04-22,0,()
201,Great Britain,Newton Abbot,NH Flat,79,79,2015-04-20,2026-05-13,0,()
202,Great Britain,Wincanton,NH Flat,79,73,2015-01-29,2026-04-12,0,()
203,Ireland,Wexford,NH Flat,79,72,2015-04-21,2026-05-27,0,()
204,Ireland,Down Royal,NH Flat,77,74,2015-02-11,2026-05-04,0,()
205,Ireland,Leopardstown,NH Flat,75,75,2015-01-18,2026-03-03,1,"(turf,)"
206,Great Britain,Kelso,NH Flat,74,70,2015-03-21,2026-05-24,1,"(turf,)"
207,Ireland,Thurles,NH Flat,74,73,2015-01-05,2026-03-05,0,()
208,Great Britain,Newbury,NH Flat,73,71,2015-01-14,2026-03-21,1,"(turf,)"
209,Ireland,Galway,NH Flat,72,70,2015-07-27,2025-10-26,0,()
210,Ireland,Thurles,Flat,71,22,2017-02-09,2025-10-30,0,()
211,Ireland,Cork,NH Flat,70,69,2015-01-03,2026-05-10,0,()
212,Ireland,Navan,NH Flat,69,69,2015-01-24,2026-03-21,0,()
213,Great Britain,Cheltenham,NH Flat,67,67,2015-01-01,2026-03-11,0,()
214,Ireland,Naas,NH Flat,67,67,2015-01-04,2026-03-08,0,()
215,Great Britain,Hereford,NH Flat,66,65,2016-12-19,2026-05-12,1,"(turf,)"
216,Ireland,Downpatrick,NH Flat,65,65,2015-03-04,2026-05-22,0,()
217,Ireland,Kilbeggan,NH Flat,64,60,2015-04-24,2026-05-15,0,()
218,Great Britain,Hexham,NH Flat,63,58,2015-03-24,2026-04-13,1,"(other_all_weather,)"
219,Great Britain,Plumpton,NH Flat,62,62,2015-01-26,2026-05-26,0,()
220,Ireland,Laytown,Flat,60,10,2015-09-10,2025-09-04,0,()
221,Great Britain,Perth,NH Flat,59,58,2015-04-24,2026-05-14,0,()
222,Great Britain,Aintree,NH Flat,58,58,2015-04-10,2026-05-15,0,()
223,Great Britain,Doncaster,NH Flat,58,56,2015-01-24,2026-03-13,0,()
224,Great Britain,Kempton,NH Flat,58,37,2015-02-06,2026-03-14,0,()
225,Ireland,Ballinrobe,NH Flat,58,54,2015-05-25,2026-05-26,0,()
226,Ireland,Tramore,NH Flat,56,56,2015-04-13,2025-11-25,0,()
227,Ireland,Clonmel,NH Flat,55,55,2015-02-19,2026-05-14,0,()
228,Great Britain,Taunton,NH Flat,52,50,2015-02-17,2026-04-09,0,()
229,Ireland,Tipperary,NH Flat,51,37,2015-04-17,2025-10-06,0,()
230,Great Britain,Musselburgh,NH Flat,50,50,2015-01-05,2025-12-22,0,()
231,Ireland,Killarney,NH Flat,50,46,2015-05-10,2026-05-11,0,()
232,Ireland,Listowel,NH Flat,49,49,2015-06-01,2025-09-27,0,()
233,Great Britain,Catterick,NH Flat,46,45,2015-01-08,2026-03-04,0,()
234,Great Britain,Ascot,NH Flat,44,44,2015-02-14,2026-02-14,1,"(turf,)"
235,Ireland,Gowran Park,NH Flat,40,40,2015-01-22,2026-03-07,0,()
236,Ireland,Wexford,Flat,38,20,2015-07-03,2024-10-28,0,()
237,Great Britain,Fakenham,NH Flat,36,36,2015-02-13,2026-04-06,0,()
238,Ireland,Roscommon,NH Flat,34,33,2015-05-18,2025-09-29,0,()
239,Ireland,Sligo,NH Flat,32,32,2015-05-20,2026-05-12,0,()
240,Great Britain,Towcester,NH Flat,28,28,2015-01-29,2018-05-14,0,()
241,Ireland,Downpatrick,Flat,26,25,2015-06-14,2024-09-20,0,()
242,Great Britain,Windsor,Hurdle,25,7,2024-12-15,2026-01-18,1,"(other_all_weather,)"
243,Great Britain,Sandown,NH Flat,24,24,2015-03-07,2026-03-07,0,()
244,Great Britain,Windsor,Chase,24,7,2024-12-15,2026-01-18,1,"(other_all_weather,)"
245,Ireland,Kilbeggan,Flat,22,22,2015-05-15,2025-06-16,0,()
246,Great Britain,Haydock,NH Flat,21,21,2015-03-18,2026-05-09,1,"(turf,)"
247,Ireland,Bellewstown,NH Flat,13,13,2015-07-04,2026-04-18,0,()
248,Ireland,Wexford (RH),Hurdle,9,2,2015-03-17,2015-04-10,0,()
249,Ireland,Wexford (RH),Chase,4,2,2015-03-17,2015-04-10,0,()
250,Great Britain,Lingfield,NH Flat,3,3,2023-11-14,2026-01-19,0,()
251,Great Britain,Stratford,Flat,3,3,2018-06-08,2021-05-28,0,()
252,Great Britain,Windsor,NH Flat,2,2,2025-01-19,2026-01-18,1,"(other_all_weather,)"
253,Ireland,Wexford (RH),NH Flat,2,2,2015-03-17,2015-04-10,0,()
254,Great Britain,Bath,Chase,1,1,2017-08-04,2017-08-04,1,"(turf,)"
255,Great Britain,Epsom,Hurdle,1,1,2024-09-12,2024-09-12,0,()
256,Great Britain,Fontwell,Flat,1,1,2015-05-14,2015-05-14,1,"(other_all_weather,)"
257,Great Britain,Market Rasen,Flat,1,1,2023-08-06,2023-08-06,1,"(other_all_weather,)"
258,Great Britain,Southwell,Flat,1,1,2023-06-26,2023-06-26,1,"(other_all_weather,)"

In [42]:
# Inspect suspicious British and Irish non-turf surface classifications.
#
# A race is included when:
# - jurisdiction is Great Britain or Ireland;
# - the derived surface is dirt, Polytrack, Tapeta or other all-weather;
# - the raw course itself does not contain "(AW)".
#
# These are likely to include false positives where a surface word occurs in:
# - a sponsor name;
# - a series or qualifying condition;
# - promotional wording;
# rather than describing the surface of the race.
#
# The complete race name is retained so each classification can be reviewed.
# No surface value is changed in this cell.

suspicious_uk_ire_surface_terms = (
    surface_jurisdiction_profile.loc[
        surface_jurisdiction_profile["candidate_jurisdiction"].isin(
            ["Great Britain", "Ireland"]
        )
        & surface_jurisdiction_profile["candidate_surface"].isin(
            [
                "dirt",
                "synthetic_polytrack",
                "synthetic_tapeta",
                "other_all_weather",
            ]
        )
        & ~surface_jurisdiction_profile["course"].str.contains(
            r"\(AW\)",
            regex=True,
            na=False,
        )
    ]
    [
        [
            "date",
            "course",
            "off",
            "race_name",
            "type",
            "candidate_jurisdiction",
            "candidate_surface",
            "surface_evidence_source",
        ]
    ]
    .sort_values(
        [
            "candidate_surface",
            "course",
            "date",
            "off",
        ]
    )
    .reset_index(drop=True)
)

suspicious_surface_summary = (
    suspicious_uk_ire_surface_terms
    .groupby(
        [
            "candidate_surface",
            "course",
            "type",
        ],
        as_index=False,
    )
    .agg(
        provisional_races=("race_name", "size"),
        distinct_race_names=("race_name", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
    .sort_values(
        [
            "candidate_surface",
            "provisional_races",
            "course",
            "type",
        ],
        ascending=[True, False, True, True],
    )
    .reset_index(drop=True)
)

print(
    "Suspicious British and Irish non-turf classifications: "
    f"{len(suspicious_uk_ire_surface_terms):,}"
)
print(
    "Distinct race names involved: "
    f"{suspicious_uk_ire_surface_terms['race_name'].nunique():,}"
)

display(suspicious_surface_summary)

pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)

suspicious_uk_ire_surface_terms

Suspicious British and Irish non-turf classifications: 54
Distinct race names involved: 48

,candidate_surface,course,type,provisional_races,distinct_race_names,first_date,last_date
0,dirt,Worcester,Chase,10,7,2015-09-25,2025-09-26
1,other_all_weather,Newcastle,NH Flat,11,11,2019-01-05,2020-02-21
2,other_all_weather,Hexham,Hurdle,7,6,2019-05-11,2022-09-30
3,other_all_weather,Hexham,Chase,5,3,2019-05-04,2022-06-11
4,other_all_weather,Chepstow,Flat,4,4,2016-06-28,2016-08-17
5,other_all_weather,Sedgefield,Hurdle,4,4,2017-12-26,2022-02-24
6,other_all_weather,Hexham,NH Flat,2,2,2019-05-11,2021-05-08
7,other_all_weather,Market Rasen,Chase,2,2,2024-12-26,2025-12-26
8,other_all_weather,Windsor,Flat,2,2,2025-09-08,2025-09-08
9,other_all_weather,Fontwell,Hurdle,1,1,2017-08-17,2017-08-17
10,other_all_weather,Limerick (IRE),Flat,1,1,2022-04-23,2022-04-23
11,other_all_weather,Sedgefield,Chase,1,1,2021-09-28,2021-09-28
12,other_all_weather,Southwell,Chase,1,1,2025-10-02,2025-10-02
13,other_all_weather,Worcester,Chase,1,1,2018-09-02,2018-09-02
14,other_all_weather,Worcester,Hurdle,1,1,2018-08-22,2018-08-22
15,synthetic_polytrack,Newmarket,Flat,1,1,2015-09-19,2015-09-19

,date,course,off,race_name,type,candidate_jurisdiction,candidate_surface,surface_evidence_source
0,2015-09-25,Worcester,2:20,Bob Love King of The Dirt Memorial Beginners Chase,Chase,Great Britain,dirt,explicit_race_name_surface
1,2016-09-23,Worcester,3:30,Bob Love King Of The Dirt Memorial Handicap Chase,Chase,Great Britain,dirt,explicit_race_name_surface
2,2017-09-29,Worcester,3:10,Bob Love King Of The Dirt Memorial Handicap Chase,Chase,Great Britain,dirt,explicit_race_name_surface
3,2018-09-28,Worcester,3:25,Bob Love King Of The Dirt Memorial Mares Handicap Chase (Qualifier),Chase,Great Britain,dirt,explicit_race_name_surface
4,2019-09-27,Worcester,3:10,Bob Love King Of The Dirt Memorial Mares Handicap Chase (Hereford Handicap Chase Series Qual),Chase,Great Britain,dirt,explicit_race_name_surface
5,2021-09-24,Worcester,2:17,Bob Love King Of The Dirt Handicap Chase,Chase,Great Britain,dirt,explicit_race_name_surface
6,2022-09-23,Worcester,1:20,Bob Love King Of The Dirt Novices Chase (GBB Race),Chase,Great Britain,dirt,explicit_race_name_surface
7,2023-09-29,Worcester,2:15,Bob Love King Of The Dirt Novices Chase (GBB Race),Chase,Great Britain,dirt,explicit_race_name_surface
8,2024-09-27,Worcester,2:35,Bob Love King Of The Dirt Novices Chase (GBB Race),Chase,Great Britain,dirt,explicit_race_name_surface
9,2025-09-26,Worcester,2:07,Bob Love King Of The Dirt Novices Handicap Chase,Chase,Great Britain,dirt,explicit_race_name_surface
10,2016-06-28,Chepstow,9:10,All Weather Riding Surfaces from Equestrian Surfaces Handicap,Flat,Great Britain,other_all_weather,explicit_race_name_surface
11,2016-08-17,Chepstow,3:30,All-Weather Riding Surfaces From Equestrian Surfaces Maiden Stakes,Flat,Great Britain,other_all_weather,explicit_race_name_surface
12,2016-08-17,Chepstow,5:15,All-Weather Riding Surfaces From Equestrian Surfaces Handicap,Flat,Great Britain,other_all_weather,explicit_race_name_surface
13,2016-08-17,Chepstow,5:45,All-Weather Riding Surfaces From Equestrian Surfaces Apprentice Handicap,Flat,Great Britain,other_all_weather,explicit_race_name_surface
14,2017-08-17,Fontwell,1:30,totepool Fontwell All Weather Bend Handicap Hurdle,Hurdle,Great Britain,other_all_weather,explicit_race_name_surface
15,2019-05-04,Hexham,8:35,carpetgallop.co.uk All Weather Gallops Handicap Chase,Chase,Great Britain,other_all_weather,explicit_race_name_surface
16,2019-05-11,Hexham,2:05,carpetgallop.co.uk All Weather Gallops Conditional Jockeys Handicap Hurdle (Qualifier),Hurdle,Great Britain,other_all_weather,explicit_race_name_surface
17,2019-05-11,Hexham,2:40,carpetgallop.co.uk All Weather Gallops Mares Novices Hurdle,Hurdle,Great Britain,other_all_weather,explicit_race_name_surface
18,2019-05-11,Hexham,4:25,carpetgallop.co.uk All Weather Gallops Maiden Hurdle,Hurdle,Great Britain,other_all_weather,explicit_race_name_surface
19,2019-05-11,Hexham,5:00,carpetgallop.co.uk All Weather Gallops Handicap Chase,Chase,Great Britain,other_all_weather,explicit_race_name_surface
20,2019-05-11,Hexham,5:35,carpetgallop.co.uk All Weather Gallops Mares Standard Open National Hunt Flat Race,NH Flat,Great Britain,other_all_weather,explicit_race_name_surface
21,2021-05-08,Hexham,2:45,carpetgallop.co.uk All Weather Gallops Mares Novices Hurdle (GBB Race),Hurdle,Great Britain,other_all_weather,explicit_race_name_surface
22,2021-05-08,Hexham,5:40,carpetgallop.co.uk All Weather Gallops Mares Open National Hunt Flat Race (Cat 1 Elimination) (GBB),NH Flat,Great Britain,other_all_weather,explicit_race_name_surface
23,2021-06-05,Hexham,5:55,carpetgallop.co.uk All Weather Gallops Amateur Jockeys Handicap Hurdle,Hurdle,Great Britain,other_all_weather,explicit_race_name_surface
24,2021-06-12,Hexham,4:05,carpetgallop.co.uk All Weather Gallops Handicap Chase (Div I),Chase,Great Britain,other_all_weather,explicit_race_name_surface
25,2021-06-12,Hexham,4:40,carpetgallop.co.uk All Weather Gallops Handicap Chase (Div II),Chase,Great Britain,other_all_weather,explicit_race_name_surface
26,2022-06-04,Hexham,1:30,carpetgallop.co.uk All Weather Gallops Amateur Jockeys Handicap Hurdle,Hurdle,Great Britain,other_all_weather,explicit_race_name_surface
27,2022-06-11,Hexham,4:20,carpetgallop.co.uk All Weather Gallops Handicap Chase,Chase,Great Britain,other_all_weather,explicit_race_name_surface
28,2022-09-30,Hexham,1:50,Carpet Gallop All Weather Surfaces Mares Handicap Hurdle (Go North Lady Buttons Series Qualifier),Hurdle,Great Britain,other_all_weather,explicit_race_name_surface
29,2022-04-23,Limerick (IRE),3:55,carpetgallop.co.uk All Weather Surfaces Maiden,Flat,Ireland,other_all_weather,explicit_race_name_surface
30,2024-12-26,Market Rasen,12:40,Rand Farm Park All Weather Attraction Novices Handicap Chase,Chase,Great Britain,other_all_weather,explicit_race_name_surface
31,2025-12-26,Market Rasen,14:22,Rand Farm Park All Weather Attraction Handicap Chase,Chase,Great Britain,other_all_weather,explicit_race_name_surface
32,2019-01-05,Newcastle,3:10,EBF/Equine Products Mares Standard National Hunt Flat Race (Cond Jockeys/Amateurs) (All-Weather),NH Flat,Great Britain,other_all_weather,explicit_race_name_surface
33,2019-01-15,Newcastle,12:45,Sky Sports Racing Sky 415 Newcomers Standard Open NH Flat Race (All-Weather),NH Flat,Great Britain,other_all_weather,explicit_race_name_surface
34,2020-01-04,Newcastle,11:50,EBF/Parklands Mini Golf Mares Standard National Hunt Flat Race (Cond & Amateurs) (All-Weather),NH Flat,Great Britain,other_all_weather,explicit_race_name_surface
35,2020-01-20,Newcastle,12:55,Sky Sports Racing Sky 415 Newcomers Standard Open National Hunt Flat Race (All-Weather),NH Flat,Great Britain,other_all_weather,explicit_race_name_surface
36,2020-02-21,Newcastle,12:30,Equine Products UK Jumpers Bumper National Hunt Flat Race (All-Weather),NH Flat,Great Britain,other_all_weather,explicit_race_name_surface
37,2020-02-21,Newcastle,1:00,Advantex Jumpers Bumper National Hunt Flat Race (All-Weather),NH Flat,Great Britain,other_all_weather,explicit_race_name_surface
38,2020-02-21,Newcastle,1:35,Altoria Developments Jumpers Bumper National Hunt Flat Race (All-Weather),NH Flat,Great Britain,other_all_weather,explicit_race_name_surface
39,2020-02-21,Newcastle,2:07,Max Recycle Jumpers Bumper National Hunt Flat Race (All-Weather),NH Flat,Great Britain,other_all_weather,explicit_race_name_surface
40,2020-02-21,Newcastle,2:40,Parklands Golf Club Standard Open National Hunt Flat Race (All-Weather),NH Flat,Great Britain,other_all_weather,explicit_race_name_surface
41,2020-02-21,Newcastle,3:10,Three Mile Inn Jumpers Bumper National Hunt Flat Race (All-Weather),NH Flat,Great Britain,other_all_weather,explicit_race_name_surface
42,2020-02-21,Newcastle,3:43,Allingtons Kia Jumpers Bumper National Hunt Flat Race (All-Weather),NH Flat,Great Britain,other_all_weather,explicit_race_name_surface
43,2017-12-26,Sedgefield,2:40,Sovereign Debt; Arc Outstanding All-Weather Award Winner Handicap Hurdle,Hurdle,Great Britain,other_all_weather,explicit_race_name_surface
44,2021-09-28,Sedgefield,3:10,All Weather Surfaces carpetgallop.co.uk Novices Handicap Chase,Chase,Great Britain,other_all_weather,explicit_race_name_surface
45,2021-09-28,Sedgefield,3:42,All Weather Gallops By carpetgallop.co.uk Conditional Jockeys Handicap Hurdle,Hurdle,Great Britain,other_all_weather,explicit_race_name_surface
46,2021-11-04,Sedgefield,1:45,All Weather Sand And Fibre Surfaces 01785719991 Conditional Jockeys Handicap Hurdle,Hurdle,Great Britain,other_all_weather,explicit_race_name_surface
47,2022-02-24,Sedgefield,2:55,All Weather Surfaces Carpet Gallop Handicap Hurdle (Go North Cab On Target Series Qualifier),Hurdle,Great Britain,other_all_weather,explicit_race_name_surface
48,2025-10-02,Southwell,2:00,Arc All-Weather £1Million Bonus Returns Handicap Chase,Chase,Great Britain,other_all_weather,explicit_race_name_surface
49,2025-09-08,Windsor,5:34,ARC All-Weather £1Million Bonus Returns Handicap (Div I),Flat,Great Britain,other_all_weather,explicit_race_name_surface
50,2025-09-08,Windsor,6:04,ARC All-Weather £1Million Bonus Returns Handicap (Div II),Flat,Great Britain,other_all_weather,explicit_race_name_surface
51,2018-08-22,Worcester,8:00,All Weather Pool Handicap Hurdle,Hurdle,Great Britain,other_all_weather,explicit_race_name_surface
52,2018-09-02,Worcester,2:15,Carpet Gallop All Weather Surfaces Handicap Chase,Chase,Great Britain,other_all_weather,explicit_race_name_surface
53,2015-09-19,Newmarket,2:40,Martin Collins Polytrack Handicap,Flat,Great Britain,synthetic_polytrack,explicit_race_name_surface

In [43]:
# Rebuild candidate surface using course/configuration evidence only.
#
# Rules:
# - raw course containing "(AW)" -> all_weather_unspecified;
# - all other races -> unresolved.
#
# Race name is deliberately excluded because inspection showed many false
# positives from sponsors, promotions, memorials and series titles.
#
# This is a conservative baseline for later venue/configuration curation.

surface_course_only_profile = candidate_jurisdiction_evidence.copy()

surface_course_only_profile["candidate_course_label"] = (
    surface_course_only_profile["course"]
    .map(remove_terminal_jurisdiction_code)
)

aw_course_mask = surface_course_only_profile["course"].str.contains(
    r"\(AW\)",
    regex=True,
    na=False,
)

surface_course_only_profile["candidate_surface"] = "unresolved"
surface_course_only_profile.loc[
    aw_course_mask,
    "candidate_surface",
] = "all_weather_unspecified"

surface_course_only_profile[
    "surface_evidence_source"
] = "no_course_level_surface_evidence"

surface_course_only_profile.loc[
    aw_course_mask,
    "surface_evidence_source",
] = "raw_course_aw_marker"

surface_course_only_summary = (
    surface_course_only_profile
    .groupby(
        [
            "candidate_jurisdiction",
            "type",
            "candidate_surface",
            "surface_evidence_source",
        ],
        as_index=False,
    )
    .agg(
        provisional_races=("race_name", "size"),
        distinct_candidate_venues=(
            "candidate_course_label",
            "nunique",
        ),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
    .sort_values(
        [
            "candidate_jurisdiction",
            "type",
            "provisional_races",
        ],
        ascending=[True, True, False],
    )
    .reset_index(drop=True)
)

resolved_surface_races = (
    surface_course_only_profile["candidate_surface"]
    != "unresolved"
).sum()

print(
    "Provisional races with course-supported surface: "
    f"{resolved_surface_races:,}"
)
print(
    "Course-supported surface coverage: "
    f"{resolved_surface_races / len(surface_course_only_profile):.2%}"
)
print(
    "Provisional races remaining unresolved: "
    f"{(
        surface_course_only_profile['candidate_surface']
        == 'unresolved'
    ).sum():,}"
)

surface_course_only_summary

Provisional races with course-supported surface: 33,023
Course-supported surface coverage: 17.47%
Provisional races remaining unresolved: 156,020

,candidate_jurisdiction,type,candidate_surface,surface_evidence_source,provisional_races,distinct_candidate_venues,first_date,last_date
0,Argentina,Flat,unresolved,no_course_level_surface_evidence,437,3,2015-01-03,2026-05-25
1,Australia,Flat,unresolved,no_course_level_surface_evidence,4059,51,2015-01-01,2026-05-23
2,Bahrain,Flat,unresolved,no_course_level_surface_evidence,151,2,2015-02-27,2026-04-24
3,Belgium,Chase,unresolved,no_course_level_surface_evidence,1,1,2019-08-27,2019-08-27
4,Belgium,Flat,unresolved,no_course_level_surface_evidence,3,2,2017-03-06,2018-04-16
5,Brazil,Flat,unresolved,no_course_level_surface_evidence,289,3,2015-01-20,2026-05-03
6,Canada,Flat,unresolved,no_course_level_surface_evidence,471,4,2015-04-18,2026-05-02
7,Chile,Flat,unresolved,no_course_level_surface_evidence,204,3,2015-01-02,2026-05-02
8,China,Flat,unresolved,no_course_level_surface_evidence,10,1,2015-04-03,2017-04-02
9,Czech Republic,Chase,unresolved,no_course_level_surface_evidence,9,1,2015-10-11,2025-10-12
10,Czech Republic,Flat,unresolved,no_course_level_surface_evidence,4,2,2018-09-22,2022-10-09
11,Denmark,Flat,unresolved,no_course_level_surface_evidence,15,1,2015-06-28,2025-05-24
12,France,Chase,unresolved,no_course_level_surface_evidence,2013,27,2015-02-24,2026-05-26
13,France,Flat,unresolved,no_course_level_surface_evidence,15514,65,2015-01-03,2026-05-24
14,France,Hurdle,unresolved,no_course_level_surface_evidence,2983,30,2015-02-24,2026-05-26
15,France,NH Flat,unresolved,no_course_level_surface_evidence,23,3,2020-10-30,2026-04-17
16,Germany,Flat,unresolved,no_course_level_surface_evidence,731,17,2015-04-05,2026-05-25
17,Great Britain,Chase,unresolved,no_course_level_surface_evidence,15671,43,2015-01-01,2026-05-27
18,Great Britain,Flat,unresolved,no_course_level_surface_evidence,40893,37,2015-02-13,2026-05-27
19,Great Britain,Flat,all_weather_unspecified,raw_course_aw_marker,29325,6,2015-01-01,2026-05-27
20,Great Britain,Hurdle,unresolved,no_course_level_surface_evidence,22645,43,2015-01-01,2026-05-27
21,Great Britain,NH Flat,unresolved,no_course_level_surface_evidence,2999,40,2015-01-01,2026-05-26
22,Great Britain,NH Flat,all_weather_unspecified,raw_course_aw_marker,101,4,2015-01-05,2024-12-09
23,Guernsey,Flat,unresolved,no_course_level_surface_evidence,20,1,2015-05-04,2019-05-06
24,Hong Kong,Flat,unresolved,no_course_level_surface_evidence,7481,2,2015-01-25,2026-05-27
25,Hungary,Flat,unresolved,no_course_level_surface_evidence,3,1,2023-09-02,2025-09-07
26,Ireland,Chase,unresolved,no_course_level_surface_evidence,4833,23,2015-01-01,2026-05-25
27,Ireland,Flat,unresolved,no_course_level_surface_evidence,11166,25,2015-01-01,2026-05-24
28,Ireland,Flat,all_weather_unspecified,raw_course_aw_marker,3597,1,2015-01-02,2026-05-26
29,Ireland,Hurdle,unresolved,no_course_level_surface_evidence,9667,24,2015-01-01,2026-05-27
30,Ireland,NH Flat,unresolved,no_course_level_surface_evidence,1520,24,2015-01-03,2026-05-27
31,Italy,Chase,unresolved,no_course_level_surface_evidence,2,1,2015-09-27,2016-09-25
32,Italy,Flat,unresolved,no_course_level_surface_evidence,385,8,2015-04-01,2026-05-10
33,Italy,Hurdle,unresolved,no_course_level_surface_evidence,1,1,2015-09-26,2015-09-26
34,Japan,Chase,unresolved,no_course_level_surface_evidence,7,2,2015-12-26,2022-04-16
35,Japan,Flat,unresolved,no_course_level_surface_evidence,1546,21,2015-01-04,2026-05-24
36,Japan,Hurdle,unresolved,no_course_level_surface_evidence,6,3,2018-06-23,2026-04-18
37,Jersey,Flat,unresolved,no_course_level_surface_evidence,350,1,2015-04-06,2026-05-10
38,Jersey,Hurdle,unresolved,no_course_level_surface_evidence,85,1,2015-04-06,2026-05-10
39,New Zealand,Flat,unresolved,no_course_level_surface_evidence,255,14,2015-01-01,2026-03-28
40,Norway,Flat,unresolved,no_course_level_surface_evidence,37,1,2015-06-25,2025-08-24
41,Peru,Flat,unresolved,no_course_level_surface_evidence,88,1,2015-01-11,2026-04-26
42,Poland,Flat,unresolved,no_course_level_surface_evidence,1,1,2025-09-28,2025-09-28
43,Qatar,Flat,unresolved,no_course_level_surface_evidence,70,2,2015-02-26,2026-02-14
44,Saudi Arabia,Flat,unresolved,no_course_level_surface_evidence,49,1,2020-02-29,2026-02-14
45,Singapore,Flat,unresolved,no_course_level_surface_evidence,3,1,2015-05-17,2023-07-23
46,South Africa,Flat,unresolved,no_course_level_surface_evidence,470,9,2015-01-10,2026-05-23
47,South Korea,Flat,unresolved,no_course_level_surface_evidence,17,2,2016-09-11,2025-09-07
48,Spain,Flat,unresolved,no_course_level_surface_evidence,14,2,2015-08-15,2023-08-15
49,Sweden,Flat,unresolved,no_course_level_surface_evidence,89,3,2015-05-12,2025-09-21
50,Sweden,Hurdle,unresolved,no_course_level_surface_evidence,3,1,2022-09-18,2024-09-15
51,Switzerland,Chase,unresolved,no_course_level_surface_evidence,1,1,2023-10-08,2023-10-08
52,Switzerland,Flat,unresolved,no_course_level_surface_evidence,48,4,2015-07-29,2026-02-22
53,Turkey,Flat,unresolved,no_course_level_surface_evidence,52,2,2015-09-05,2025-09-07
54,United Arab Emirates,Flat,unresolved,no_course_level_surface_evidence,2451,5,2015-01-04,2026-04-11
55,United States,Chase,unresolved,no_course_level_surface_evidence,10,3,2015-08-06,2023-08-23
56,United States,Flat,unresolved,no_course_level_surface_evidence,6023,50,2015-01-01,2026-05-26
57,United States,Hurdle,unresolved,no_course_level_surface_evidence,72,9,2015-08-27,2026-05-09
58,Uruguay,Flat,unresolved,no_course_level_surface_evidence,70,1,2015-01-06,2026-01-06

In [44]:
# Build the candidate venue/configuration inventory required for curated
# surface mapping.
#
# One row is produced for each:
#     candidate jurisdiction + candidate course label
#
# The inventory retains configuration markers such as:
# - (AW)
# - (July)
# - (RH)
# - (Perth)
#
# It reports:
# - raw course forms represented;
# - race and runner volume;
# - disciplines observed;
# - date coverage;
# - whether the source itself explicitly marks the configuration as AW.
#
# This is the appropriate grain for external venue/surface research.
# No additional surface is inferred in this cell.

runner_counts_by_race = pd.read_sql_query(
    f"""
    SELECT
        date,
        course,
        off,
        race_name,
        type,
        COUNT(*) AS runner_rows
    FROM {SOURCE_TABLE}
    WHERE {DATA_ROW_PREDICATE}
    GROUP BY
        date,
        course,
        off,
        race_name,
        type
    """,
    connection,
)

venue_configuration_inventory = (
    surface_course_only_profile
    .merge(
        runner_counts_by_race,
        on=[
            "date",
            "course",
            "off",
            "race_name",
            "type",
        ],
        how="left",
    )
    .groupby(
        [
            "candidate_jurisdiction",
            "candidate_course_label",
        ],
        as_index=False,
    )
    .agg(
        raw_course_forms=("course", "nunique"),
        raw_course_values=(
            "course",
            lambda values: tuple(sorted(set(values))),
        ),
        provisional_races=("race_name", "size"),
        runner_rows=("runner_rows", "sum"),
        disciplines=(
            "type",
            lambda values: tuple(sorted(set(values))),
        ),
        active_dates=("date", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
        source_aw_marked_races=(
            "candidate_surface",
            lambda values: (
                values == "all_weather_unspecified"
            ).sum(),
        ),
    )
)

venue_configuration_inventory["source_aw_marker_present"] = (
    venue_configuration_inventory["source_aw_marked_races"] > 0
)

venue_configuration_inventory["surface_research_status"] = (
    venue_configuration_inventory["source_aw_marker_present"]
    .map(
        {
            True: "source_supports_all_weather",
            False: "requires_curated_reference",
        }
    )
)

venue_configuration_inventory = (
    venue_configuration_inventory
    .sort_values(
        [
            "surface_research_status",
            "provisional_races",
            "candidate_jurisdiction",
            "candidate_course_label",
        ],
        ascending=[True, False, True, True],
    )
    .reset_index(drop=True)
)

print(
    "Candidate venue/configuration identities: "
    f"{len(venue_configuration_inventory):,}"
)
print(
    "Configurations with source AW evidence: "
    f"{venue_configuration_inventory['source_aw_marker_present'].sum():,}"
)
print(
    "Configurations requiring curated surface reference: "
    f"{(~venue_configuration_inventory['source_aw_marker_present']).sum():,}"
)

venue_configuration_inventory

Candidate venue/configuration identities: 395
Configurations with source AW evidence: 7
Configurations requiring curated surface reference: 388

,candidate_jurisdiction,candidate_course_label,raw_course_forms,raw_course_values,provisional_races,runner_rows,disciplines,active_dates,first_date,last_date,source_aw_marked_races,source_aw_marker_present,surface_research_status
0,Hong Kong,Sha Tin,2,"(Sha Tin, Sha Tin (HK))",4543,56963,"(Flat,)",472,2015-01-25,2026-05-24,0,False,requires_curated_reference
1,France,Chantilly,2,"(Chantilly, Chantilly (FR))",4438,52403,"(Flat, NH Flat)",533,2015-01-23,2026-05-19,0,False,requires_curated_reference
2,France,Deauville,2,"(Deauville, Deauville (FR))",4317,52014,"(Flat,)",504,2015-01-03,2026-04-08,0,False,requires_curated_reference
3,France,Auteuil,2,"(Auteuil, Auteuil (FR))",3356,34928,"(Chase, Flat, Hurdle)",419,2015-03-01,2026-05-26,0,False,requires_curated_reference
4,Hong Kong,Happy Valley,2,"(Happy Valley, Happy Valley (HK))",2938,34012,"(Flat,)",344,2016-01-06,2026-05-27,0,False,requires_curated_reference
5,Great Britain,Doncaster,1,"(Doncaster,)",2805,26166,"(Chase, Flat, Hurdle, NH Flat)",389,2015-01-09,2026-05-16,0,False,requires_curated_reference
6,France,Saint-Cloud,2,"(Saint-Cloud, Saint-Cloud (FR))",2716,30288,"(Flat, NH Flat)",330,2015-03-07,2026-05-22,0,False,requires_curated_reference
7,Great Britain,Ayr,1,"(Ayr,)",2325,20921,"(Chase, Flat, Hurdle, NH Flat)",328,2015-01-02,2026-05-20,0,False,requires_curated_reference
8,Great Britain,Chepstow,1,"(Chepstow,)",2318,20804,"(Chase, Flat, Hurdle, NH Flat)",326,2015-01-30,2026-05-21,0,False,requires_curated_reference
9,Great Britain,Haydock,1,"(Haydock,)",2269,19065,"(Chase, Flat, Hurdle, NH Flat)",331,2015-01-17,2026-05-23,0,False,requires_curated_reference
10,Great Britain,Newbury,1,"(Newbury,)",2223,21535,"(Chase, Flat, Hurdle, NH Flat)",310,2015-01-14,2026-05-16,0,False,requires_curated_reference
11,France,Longchamp,2,"(Longchamp, Longchamp (FR))",2044,22094,"(Flat, NH Flat)",248,2015-04-06,2026-05-24,0,False,requires_curated_reference
12,Great Britain,Catterick,1,"(Catterick,)",2010,17389,"(Chase, Flat, Hurdle, NH Flat)",287,2015-01-01,2026-05-21,0,False,requires_curated_reference
13,Great Britain,Musselburgh,1,"(Musselburgh,)",2007,16365,"(Chase, Flat, Hurdle, NH Flat)",290,2015-01-01,2026-05-21,0,False,requires_curated_reference
14,Great Britain,Leicester,1,"(Leicester,)",1989,16172,"(Chase, Flat, Hurdle)",293,2015-01-08,2026-05-26,0,False,requires_curated_reference
15,Great Britain,Windsor,1,"(Windsor,)",1935,17677,"(Chase, Flat, Hurdle, NH Flat)",274,2015-04-13,2026-05-25,0,False,requires_curated_reference
16,Ireland,Leopardstown,2,"(Leopardstown, Leopardstown (IRE))",1874,21038,"(Chase, Flat, Hurdle, NH Flat)",256,2015-01-18,2026-05-15,0,False,requires_curated_reference
17,Great Britain,Uttoxeter,1,"(Uttoxeter,)",1833,16185,"(Chase, Hurdle, NH Flat)",256,2015-01-24,2026-05-24,0,False,requires_curated_reference
18,Ireland,Curragh,2,"(Curragh, Curragh (IRE))",1823,23025,"(Flat,)",236,2015-03-29,2026-05-24,0,False,requires_curated_reference
19,Great Britain,Ascot,1,"(Ascot,)",1816,19425,"(Chase, Flat, Hurdle, NH Flat)",273,2015-01-17,2026-05-09,0,False,requires_curated_reference
20,Great Britain,Carlisle,1,"(Carlisle,)",1775,15282,"(Chase, Flat, Hurdle, NH Flat)",250,2015-02-16,2026-05-18,0,False,requires_curated_reference
21,Ireland,Fairyhouse,2,"(Fairyhouse, Fairyhouse (IRE))",1759,20523,"(Chase, Flat, Hurdle, NH Flat)",237,2015-01-01,2026-04-06,0,False,requires_curated_reference
22,Great Britain,Sandown,1,"(Sandown,)",1687,14053,"(Chase, Flat, Hurdle, NH Flat)",252,2015-01-03,2026-04-25,0,False,requires_curated_reference
23,Ireland,Punchestown,2,"(Punchestown, Punchestown (IRE))",1664,20444,"(Chase, Flat, Hurdle, NH Flat)",226,2015-01-10,2026-05-13,0,False,requires_curated_reference
24,Great Britain,Nottingham,1,"(Nottingham,)",1642,14711,"(Flat,)",230,2015-04-08,2026-05-19,0,False,requires_curated_reference
25,Great Britain,Yarmouth,1,"(Yarmouth,)",1628,13521,"(Flat,)",230,2015-08-30,2026-05-20,0,False,requires_curated_reference
26,Great Britain,Fontwell,1,"(Fontwell,)",1579,11426,"(Chase, Flat, Hurdle, NH Flat)",232,2015-02-12,2026-05-24,0,False,requires_curated_reference
27,Ireland,Naas,2,"(Naas, Naas (IRE))",1579,18863,"(Chase, Flat, Hurdle, NH Flat)",214,2015-01-04,2026-05-17,0,False,requires_curated_reference
28,Great Britain,Ffos Las,1,"(Ffos Las,)",1576,12313,"(Chase, Flat, Hurdle, NH Flat)",232,2015-01-02,2026-05-20,0,False,requires_curated_reference
29,Ireland,Cork,2,"(Cork, Cork (IRE))",1554,18827,"(Chase, Flat, Hurdle, NH Flat)",211,2015-01-03,2026-05-19,0,False,requires_curated_reference
30,Great Britain,Market Rasen,1,"(Market Rasen,)",1545,12029,"(Chase, Flat, Hurdle, NH Flat)",224,2015-01-15,2026-05-08,0,False,requires_curated_reference
31,Great Britain,Bath,1,"(Bath,)",1540,13091,"(Chase, Flat)",216,2015-04-17,2026-05-26,0,False,requires_curated_reference
32,Ireland,Navan,2,"(Navan, Navan (IRE))",1520,18830,"(Chase, Flat, Hurdle, NH Flat)",204,2015-01-24,2026-05-16,0,False,requires_curated_reference
33,Ireland,Gowran Park,2,"(Gowran Park, Gowran Park (IRE))",1519,18277,"(Chase, Flat, Hurdle, NH Flat)",204,2015-01-22,2026-05-20,0,False,requires_curated_reference
34,Great Britain,Newmarket,1,"(Newmarket,)",1503,14772,"(Flat,)",205,2015-04-15,2026-05-16,0,False,requires_curated_reference
35,Great Britain,Brighton,1,"(Brighton,)",1484,11265,"(Flat,)",214,2015-04-21,2025-10-16,0,False,requires_curated_reference
36,Ireland,Limerick,2,"(Limerick, Limerick (IRE))",1460,16422,"(Chase, Flat, Hurdle, NH Flat)",201,2015-03-14,2026-05-21,0,False,requires_curated_reference
37,Great Britain,Lingfield,1,"(Lingfield,)",1457,11706,"(Chase, Flat, Hurdle, NH Flat)",248,2015-01-05,2026-05-26,0,False,requires_curated_reference
38,United Arab Emirates,Meydan,2,"(Meydan, Meydan (UAE))",1451,16403,"(Flat,)",213,2015-01-08,2026-03-28,0,False,requires_curated_reference
39,Great Britain,Beverley,1,"(Beverley,)",1444,13046,"(Flat,)",199,2015-04-15,2026-05-27,0,False,requires_curated_reference
40,Great Britain,Newmarket (July),1,"(Newmarket (July),)",1438,11820,"(Flat,)",208,2015-06-19,2025-08-23,0,False,requires_curated_reference
41,Great Britain,Worcester,1,"(Worcester,)",1399,12104,"(Chase, Hurdle, NH Flat)",194,2015-05-07,2026-05-22,0,False,requires_curated_reference
42,Great Britain,Redcar,1,"(Redcar,)",1377,14053,"(Flat,)",182,2015-04-06,2026-05-26,0,False,requires_curated_reference
43,Great Britain,Southwell,1,"(Southwell,)",1372,11224,"(Chase, Flat, Hurdle, NH Flat)",198,2015-02-22,2026-05-11,0,False,requires_curated_reference
44,Great Britain,Goodwood,1,"(Goodwood,)",1371,12687,"(Flat,)",199,2015-05-02,2026-05-23,0,False,requires_curated_reference
45,Great Britain,York,1,"(York,)",1338,16170,"(Flat,)",193,2015-05-13,2026-05-23,0,False,requires_curated_reference
46,Great Britain,Huntingdon,1,"(Huntingdon,)",1316,10958,"(Chase, Hurdle, NH Flat)",192,2015-01-09,2026-05-25,0,False,requires_curated_reference
47,Great Britain,Hamilton,1,"(Hamilton,)",1308,10433,"(Flat,)",187,2015-05-03,2026-05-27,0,False,requires_curated_reference
48,Great Britain,Warwick,1,"(Warwick,)",1304,11205,"(Chase, Hurdle, NH Flat)",187,2015-01-10,2026-05-20,0,False,requires_curated_reference
49,Great Britain,Wetherby,1,"(Wetherby,)",1296,11032,"(Chase, Flat, Hurdle, NH Flat)",187,2015-01-10,2026-04-26,0,False,requires_curated_reference
50,Great Britain,Sedgefield,1,"(Sedgefield,)",1281,9666,"(Chase, Hurdle, NH Flat)",190,2015-01-06,2026-04-10,0,False,requires_curated_reference
51,Great Britain,Thirsk,1,"(Thirsk,)",1224,12675,"(Flat,)",165,2015-04-18,2026-05-16,0,False,requires_curated_reference
52,Great Britain,Newton Abbot,1,"(Newton Abbot,)",1213,9213,"(Chase, Hurdle, NH Flat)",179,2015-03-25,2026-05-27,0,False,requires_curated_reference
53,Great Britain,Stratford,1,"(Stratford,)",1211,9759,"(Chase, Flat, Hurdle, NH Flat)",176,2015-03-09,2026-05-17,0,False,requires_curated_reference
54,Great Britain,Cheltenham,1,"(Cheltenham,)",1210,14146,"(Chase, Hurdle, NH Flat)",175,2015-01-01,2026-03-13,0,False,requires_curated_reference
55,Great Britain,Ripon,1,"(Ripon,)",1192,9978,"(Flat,)",176,2015-04-16,2026-05-17,0,False,requires_curated_reference
56,Great Britain,Exeter,1,"(Exeter,)",1169,10285,"(Chase, Hurdle, NH Flat)",170,2015-01-01,2026-04-17,0,False,requires_curated_reference
57,Great Britain,Pontefract,1,"(Pontefract,)",1169,9880,"(Flat,)",166,2015-04-07,2026-05-22,0,False,requires_curated_reference
58,Great Britain,Plumpton,1,"(Plumpton,)",1165,8586,"(Chase, Hurdle, NH Flat)",175,2015-01-04,2026-05-26,0,False,requires_curated_reference
59,Great Britain,Salisbury,1,"(Salisbury,)",1140,9609,"(Flat,)",161,2015-05-03,2026-05-23,0,False,requires_curated_reference
60,Great Britain,Ludlow,1,"(Ludlow,)",1137,9244,"(Chase, Hurdle, NH Flat)",167,2015-01-07,2026-05-10,0,False,requires_curated_reference
61,Great Britain,Wincanton,1,"(Wincanton,)",1103,9276,"(Chase, Hurdle, NH Flat)",159,2015-01-03,2026-04-12,0,False,requires_curated_reference
62,Great Britain,Hexham,1,"(Hexham,)",1098,9459,"(Chase, Hurdle, NH Flat)",159,2015-03-12,2026-05-19,0,False,requires_curated_reference
63,Great Britain,Perth,1,"(Perth,)",1095,8562,"(Chase, Hurdle, NH Flat)",155,2015-04-22,2026-05-14,0,False,requires_curated_reference
64,Great Britain,Chester,1,"(Chester,)",1086,9305,"(Flat,)",156,2015-05-06,2026-05-08,0,False,requires_curated_reference
65,France,Compiegne,2,"(Compiegne, Compiegne (FR))",1084,10268,"(Chase, Flat, Hurdle)",189,2015-03-09,2026-05-13,0,False,requires_curated_reference
66,Great Britain,Kelso,1,"(Kelso,)",1064,8511,"(Chase, Hurdle, NH Flat)",152,2015-01-11,2026-05-24,0,False,requires_curated_reference
67,Ireland,Galway,2,"(Galway, Galway (IRE))",1052,13438,"(Chase, Flat, Hurdle, NH Flat)",140,2015-07-27,2025-10-27,0,False,requires_curated_reference
68,Ireland,Killarney,2,"(Killarney, Killarney (IRE))",1010,10416,"(Chase, Flat, Hurdle, NH Flat)",135,2015-05-10,2026-05-12,0,False,requires_curated_reference
69,Great Britain,Newcastle,1,"(Newcastle,)",1007,8421,"(Chase, Flat, Hurdle, NH Flat)",144,2015-01-03,2026-04-11,0,False,requires_curated_reference
70,Great Britain,Taunton,1,"(Taunton,)",987,9191,"(Chase, Hurdle, NH Flat)",145,2015-01-07,2026-04-22,0,False,requires_curated_reference
71,France,Maisons-Laffitte,1,"(Maisons-Laffitte (FR),)",985,10770,"(Flat,)",122,2015-04-02,2019-10-29,0,False,requires_curated_reference
72,Great Britain,Bangor-on-Dee,1,"(Bangor-on-Dee,)",985,7962,"(Chase, Hurdle, NH Flat)",145,2015-01-06,2026-05-23,0,False,requires_curated_reference
73,Ireland,Down Royal,2,"(Down Royal, Down Royal (IRE))",978,10483,"(Chase, Flat, Hurdle, NH Flat)",138,2015-02-11,2026-05-04,0,False,requires_curated_reference
74,Ireland,Clonmel,2,"(Clonmel, Clonmel (IRE))",932,10719,"(Chase, Flat, Hurdle, NH Flat)",132,2015-02-10,2026-05-14,0,False,requires_curated_reference
75,Ireland,Tipperary,1,"(Tipperary (IRE),)",906,10388,"(Chase, Flat, Hurdle, NH Flat)",122,2015-04-09,2025-10-06,0,False,requires_curated_reference
76,Great Britain,Kempton,1,"(Kempton,)",902,7284,"(Chase, Hurdle, NH Flat)",132,2015-01-10,2026-03-23,0,False,requires_curated_reference
77,Ireland,Tramore,2,"(Tramore, Tramore (IRE))",874,9402,"(Chase, Flat, Hurdle, NH Flat)",125,2015-01-01,2026-04-20,0,False,requires_curated_reference
78,United States,Santa Anita,2,"(Santa Anita, Santa Anita (USA))",872,6379,"(Flat,)",483,2015-01-03,2026-05-26,0,False,requires_curated_reference
79,Ireland,Thurles,2,"(Thurles, Thurles (IRE))",869,9804,"(Chase, Flat, Hurdle, NH Flat)",124,2015-01-05,2026-03-05,0,False,requires_curated_reference
80,Ireland,Wexford,2,"(Wexford, Wexford (IRE))",841,9080,"(Chase, Flat, Hurdle, NH Flat)",116,2015-04-21,2026-05-27,0,False,requires_curated_reference
81,Great Britain,Hereford,1,"(Hereford,)",838,7158,"(Chase, Hurdle, NH Flat)",122,2016-10-06,2026-05-12,0,False,requires_curated_reference
82,Great Britain,Fakenham,1,"(Fakenham,)",798,5118,"(Chase, Hurdle, NH Flat)",126,2015-01-01,2026-05-04,0,False,requires_curated_reference
83,Australia,Randwick,2,"(Randwick, Randwick (AUS))",779,8541,"(Flat,)",173,2015-02-14,2026-04-18,0,False,requires_curated_reference
84,United States,Gulfstream Park,2,"(Gulfstream Park, Gulfstream Park (USA))",778,6820,"(Flat,)",251,2015-01-03,2026-05-09,0,False,requires_curated_reference
85,Ireland,Ballinrobe,2,"(Ballinrobe, Ballinrobe (IRE))",773,8703,"(Chase, Flat, Hurdle, NH Flat)",106,2015-05-25,2026-05-26,0,False,requires_curated_reference
86,Ireland,Downpatrick,2,"(Downpatrick, Downpatrick (IRE))",759,7612,"(Chase, Flat, Hurdle, NH Flat)",108,2015-03-04,2026-05-22,0,False,requires_curated_reference
87,Ireland,Listowel,1,"(Listowel (IRE),)",758,8575,"(Chase, Flat, Hurdle, NH Flat)",101,2015-05-31,2025-09-27,0,False,requires_curated_reference
88,Ireland,Roscommon,2,"(Roscommon, Roscommon (IRE))",718,8310,"(Chase, Flat, Hurdle, NH Flat)",98,2015-05-18,2026-05-18,0,False,requires_curated_reference
89,Great Britain,Epsom,1,"(Epsom,)",717,5991,"(Flat, Hurdle)",111,2015-04-22,2026-04-28,0,False,requires_curated_reference
90,Ireland,Kilbeggan,2,"(Kilbeggan, Kilbeggan (IRE))",707,8219,"(Chase, Flat, Hurdle, NH Flat)",97,2015-04-24,2026-05-15,0,False,requires_curated_reference
91,United Arab Emirates,Jebel Ali,2,"(Jebel Ali, Jebel Ali (UAE))",670,7153,"(Flat,)",112,2015-01-09,2026-03-15,0,False,requires_curated_reference
92,Great Britain,Cartmel,1,"(Cartmel,)",639,5227,"(Chase, Hurdle)",92,2015-05-25,2026-05-27,0,False,requires_curated_reference
93,Australia,Caulfield,2,"(Caulfield, Caulfield (AUS))",616,6805,"(Flat,)",154,2015-02-14,2026-04-04,0,False,requires_curated_reference
94,Ireland,Sligo,2,"(Sligo, Sligo (IRE))",614,6090,"(Chase, Flat, Hurdle, NH Flat)",87,2015-05-03,2026-05-12,0,False,requires_curated_reference
95,Great Britain,Aintree,1,"(Aintree,)",610,6616,"(Chase, Hurdle, NH Flat)",87,2015-04-09,2026-05-15,0,False,requires_curated_reference
96,Ireland,Bellewstown,2,"(Bellewstown, Bellewstown (IRE))",568,6462,"(Flat, Hurdle, NH Flat)",75,2015-07-02,2026-04-18,0,False,requires_curated_reference
97,Australia,Flemington,2,"(Flemington, Flemington (AUS))",534,6494,"(Flat,)",143,2015-01-01,2026-03-28,0,False,requires_curated_reference
98,United States,Saratoga,1,"(Saratoga (USA),)",528,3828,"(Chase, Flat, Hurdle)",273,2015-07-24,2025-09-01,0,False,requires_curated_reference
99,Australia,Rosehill,2,"(Rosehill, Rosehill (AUS))",506,5315,"(Flat,)",120,2015-01-31,2026-03-28,0,False,requires_curated_reference
100,United States,Churchill Downs,2,"(Churchill Downs, Churchill Downs (USA))",502,4635,"(Flat,)",219,2015-04-26,2026-05-25,0,False,requires_curated_reference
101,United States,Belmont Park,1,"(Belmont Park (USA),)",482,3558,"(Flat, Hurdle)",212,2015-04-29,2023-07-08,0,False,requires_curated_reference
102,Canada,Woodbine,2,"(Woodbine, Woodbine (CAN))",443,3592,"(Flat,)",289,2015-04-18,2026-05-02,0,False,requires_curated_reference
103,Jersey,Les Landes,2,"(Les Landes, Les Landes (JER))",435,2784,"(Flat, Hurdle)",89,2015-04-06,2026-05-10,0,False,requires_curated_reference
104,United States,Keeneland,2,"(Keeneland, Keeneland (USA))",433,4101,"(Flat,)",215,2015-04-03,2026-04-24,0,False,requires_curated_reference
105,United States,Del Mar,2,"(Del Mar, Del Mar (USA))",424,3622,"(Flat,)",257,2015-07-18,2025-11-30,0,False,requires_curated_reference
106,United States,Aqueduct,2,"(Aqueduct, Aqueduct (USA))",327,2403,"(Flat,)",195,2015-01-01,2026-05-09,0,False,requires_curated_reference
107,Japan,Tokyo,2,"(Tokyo, Tokyo (JPN))",307,4587,"(Chase, Flat, Hurdle)",294,2015-02-01,2026-05-24,0,False,requires_curated_reference
108,France,Enghien,1,"(Enghien (FR),)",285,3031,"(Chase, Hurdle)",37,2015-02-24,2016-11-21,0,False,requires_curated_reference
109,Japan,Nakayama,2,"(Nakayama, Nakayama (JPN))",278,4080,"(Chase, Flat, Hurdle)",273,2015-01-04,2026-04-19,0,False,requires_curated_reference
110,Great Britain,Towcester,1,"(Towcester,)",259,2063,"(Chase, Hurdle, NH Flat)",39,2015-01-29,2018-05-21,0,False,requires_curated_reference
111,Australia,Moonee Valley,2,"(Moonee Valley, Moonee Valley (AUS))",243,2407,"(Flat,)",87,2015-01-24,2025-10-25,0,False,requires_curated_reference
112,Japan,Hanshin,2,"(Hanshin, Hanshin (JPN))",235,3439,"(Flat,)",233,2015-02-28,2026-04-18,0,False,requires_curated_reference
113,Australia,Ascot,2,"(Ascot, Ascot (AUS))",225,2651,"(Flat,)",155,2015-01-01,2026-05-02,0,False,requires_curated_reference
114,Australia,Morphettville,2,"(Morphettville, Morphettville (AUS))",222,2830,"(Flat,)",94,2015-02-28,2026-05-09,0,False,requires_curated_reference
115,Italy,San Siro,2,"(San Siro, San Siro (ITY))",217,1648,"(Flat,)",114,2015-04-01,2026-05-10,0,False,requires_curated_reference
116,Argentina,Palermo,2,"(Palermo, Palermo (ARG))",209,2123,"(Flat,)",78,2015-01-03,2026-05-01,0,False,requires_curated_reference
117,Japan,Kyoto,2,"(Kyoto, Kyoto (JPN))",200,2964,"(Flat,)",198,2015-01-04,2026-05-23,0,False,requires_curated_reference
118,Argentina,San Isidro,2,"(San Isidro, San Isidro (ARG))",190,2264,"(Flat,)",84,2015-02-07,2026-05-25,0,False,requires_curated_reference
119,France,Cagnes-Sur-Mer,2,"(Cagnes-Sur-Mer, Cagnes-Sur-Mer (FR))",185,1945,"(Chase, Flat, Hurdle)",90,2015-01-13,2026-02-22,0,False,requires_curated_reference
120,United Arab Emirates,Abu Dhabi,2,"(Abu Dhabi, Abu Dhabi (UAE))",184,2429,"(Flat,)",153,2015-01-04,2026-04-11,0,False,requires_curated_reference
121,United States,Will Rogers Downs,1,"(Will Rogers Downs (USA),)",178,1661,"(Flat,)",18,2020-03-23,2020-05-20,0,False,requires_curated_reference
122,Australia,Eagle Farm,2,"(Eagle Farm, Eagle Farm (AUS))",171,2315,"(Flat,)",50,2016-06-11,2026-05-02,0,False,requires_curated_reference
123,United States,Oaklawn Park,2,"(Oaklawn Park, Oaklawn Park (USA))",171,1487,"(Flat,)",107,2015-01-15,2026-04-19,0,False,requires_curated_reference
124,Australia,Doomben,2,"(Doomben, Doomben (AUS))",162,2036,"(Flat,)",53,2015-05-09,2026-05-23,0,False,requires_curated_reference
125,Germany,Baden-Baden,2,"(Baden-Baden, Baden-Baden (GER))",161,1389,"(Flat,)",97,2015-06-04,2025-10-19,0,False,requires_curated_reference
126,Italy,Capannelle,2,"(Capannelle, Capannelle (ITY))",151,1369,"(Flat,)",62,2015-04-19,2025-11-02,0,False,requires_curated_reference
127,France,Clairefontaine,1,"(Clairefontaine (FR),)",147,1517,"(Chase, Flat, Hurdle)",81,2015-08-10,2025-08-15,0,False,requires_curated_reference
128,Brazil,Gavea,2,"(Gavea, Gavea (BRZ))",145,1759,"(Flat,)",70,2015-01-20,2026-04-12,0,False,requires_curated_reference
129,Brazil,Cidade Jardim,2,"(Cidade Jardim, Cidade Jardim (BRZ))",143,1544,"(Flat,)",75,2015-01-25,2026-05-03,0,False,requires_curated_reference
130,United States,Monmouth Park,1,"(Monmouth Park (USA),)",139,975,"(Flat,)",85,2015-05-16,2025-08-16,0,False,requires_curated_reference
131,Japan,Chukyo,2,"(Chukyo, Chukyo (JPN))",135,2093,"(Flat,)",134,2015-01-25,2026-03-29,0,False,requires_curated_reference
132,South Africa,Greyville,1,"(Greyville (SAF),)",132,1658,"(Flat,)",50,2015-05-30,2025-07-27,0,False,requires_curated_reference
133,South Africa,Turffontein Standside,2,"(Turffontein Standside, Turffontein Standside (SAF))",132,1586,"(Flat,)",59,2015-11-28,2026-04-04,0,False,requires_curated_reference
134,France,Fontainebleau,2,"(Fontainebleau, Fontainebleau (FR))",125,1259,"(Chase, Flat, Hurdle)",78,2015-03-04,2026-02-26,0,False,requires_curated_reference
135,United States,Fair Grounds,2,"(Fair Grounds, Fair Grounds (USA))",123,1055,"(Flat,)",52,2015-01-17,2026-03-21,0,False,requires_curated_reference
136,Bahrain,Bahrain,2,"(Bahrain, Bahrain (BHR))",122,1282,"(Flat,)",50,2022-11-18,2026-04-24,0,False,requires_curated_reference
137,United States,Tampa Bay Downs,2,"(Tampa Bay Downs, Tampa Bay Downs (USA))",113,1008,"(Flat,)",49,2015-01-04,2026-03-07,0,False,requires_curated_reference
138,South Africa,Kenilworth,2,"(Kenilworth, Kenilworth (SAF))",104,1270,"(Flat,)",60,2015-01-10,2026-02-28,0,False,requires_curated_reference

In [45]:
# Prioritise the curated surface-reference backlog by database coverage.
#
# The source directly supports seven all-weather configurations.
# The remaining 388 configurations require external or curated reference data.
#
# This cell ranks the unresolved configurations by provisional race volume and
# calculates cumulative coverage. It shows how many races and runner rows would
# be covered by researching the top:
# - 10
# - 25
# - 50
# - 100
# - 200
# - all remaining configurations
#
# No surface value is inferred or assigned.

surface_reference_backlog = (
    venue_configuration_inventory.loc[
        ~venue_configuration_inventory["source_aw_marker_present"]
    ]
    .sort_values(
        [
            "provisional_races",
            "runner_rows",
            "candidate_jurisdiction",
            "candidate_course_label",
        ],
        ascending=[False, False, True, True],
    )
    .reset_index(drop=True)
)

surface_reference_backlog["research_priority"] = (
    surface_reference_backlog.index + 1
)

surface_reference_backlog["cumulative_races"] = (
    surface_reference_backlog["provisional_races"].cumsum()
)

surface_reference_backlog["cumulative_runner_rows"] = (
    surface_reference_backlog["runner_rows"].cumsum()
)

total_backlog_races = surface_reference_backlog[
    "provisional_races"
].sum()

total_backlog_runner_rows = surface_reference_backlog[
    "runner_rows"
].sum()

surface_reference_backlog["cumulative_race_coverage"] = (
    surface_reference_backlog["cumulative_races"]
    / total_backlog_races
)

surface_reference_backlog["cumulative_runner_coverage"] = (
    surface_reference_backlog["cumulative_runner_rows"]
    / total_backlog_runner_rows
)

priority_thresholds = [
    10,
    25,
    50,
    100,
    200,
    len(surface_reference_backlog),
]

priority_coverage_summary = pd.DataFrame(
    [
        {
            "configurations_researched": threshold,
            "provisional_races_covered": (
                surface_reference_backlog
                .head(threshold)["provisional_races"]
                .sum()
            ),
            "share_of_backlog_races": (
                surface_reference_backlog
                .head(threshold)["provisional_races"]
                .sum()
                / total_backlog_races
            ),
            "runner_rows_covered": (
                surface_reference_backlog
                .head(threshold)["runner_rows"]
                .sum()
            ),
            "share_of_backlog_runner_rows": (
                surface_reference_backlog
                .head(threshold)["runner_rows"]
                .sum()
                / total_backlog_runner_rows
            ),
        }
        for threshold in priority_thresholds
    ]
)

print(
    "Venue/configurations requiring curated surface research: "
    f"{len(surface_reference_backlog):,}"
)
print(
    "Provisional races in curated-reference backlog: "
    f"{total_backlog_races:,}"
)
print(
    "Runner rows in curated-reference backlog: "
    f"{total_backlog_runner_rows:,}"
)

display(priority_coverage_summary)

surface_reference_backlog[
    [
        "research_priority",
        "candidate_jurisdiction",
        "candidate_course_label",
        "provisional_races",
        "runner_rows",
        "disciplines",
        "first_date",
        "last_date",
        "cumulative_race_coverage",
        "cumulative_runner_coverage",
    ]
].head(50)

Venue/configurations requiring curated surface research: 388
Provisional races in curated-reference backlog: 156,020
Runner rows in curated-reference backlog: 1,538,077

,configurations_researched,provisional_races_covered,share_of_backlog_races,runner_rows_covered,share_of_backlog_runner_rows
0,10,32025,0.205262,347564,0.225973
1,25,60106,0.385245,623482,0.405365
2,50,96464,0.618280,965959,0.628030
3,100,142215,0.911518,1397155,0.908378
4,200,154656,0.991258,1524558,0.991210
5,388,156020,1.000000,1538077,1.000000

,research_priority,candidate_jurisdiction,candidate_course_label,provisional_races,runner_rows,disciplines,first_date,last_date,cumulative_race_coverage,cumulative_runner_coverage
0,1,Hong Kong,Sha Tin,4543,56963,"(Flat,)",2015-01-25,2026-05-24,0.029118,0.037035
1,2,France,Chantilly,4438,52403,"(Flat, NH Flat)",2015-01-23,2026-05-19,0.057563,0.071106
2,3,France,Deauville,4317,52014,"(Flat,)",2015-01-03,2026-04-08,0.085233,0.104923
3,4,France,Auteuil,3356,34928,"(Chase, Flat, Hurdle)",2015-03-01,2026-05-26,0.106743,0.127632
4,5,Hong Kong,Happy Valley,2938,34012,"(Flat,)",2016-01-06,2026-05-27,0.125574,0.149745
5,6,Great Britain,Doncaster,2805,26166,"(Chase, Flat, Hurdle, NH Flat)",2015-01-09,2026-05-16,0.143552,0.166758
6,7,France,Saint-Cloud,2716,30288,"(Flat, NH Flat)",2015-03-07,2026-05-22,0.160960,0.186450
7,8,Great Britain,Ayr,2325,20921,"(Chase, Flat, Hurdle, NH Flat)",2015-01-02,2026-05-20,0.175862,0.200052
8,9,Great Britain,Chepstow,2318,20804,"(Chase, Flat, Hurdle, NH Flat)",2015-01-30,2026-05-21,0.190719,0.213578
9,10,Great Britain,Haydock,2269,19065,"(Chase, Flat, Hurdle, NH Flat)",2015-01-17,2026-05-23,0.205262,0.225973
10,11,Great Britain,Newbury,2223,21535,"(Chase, Flat, Hurdle, NH Flat)",2015-01-14,2026-05-16,0.219510,0.239974
11,12,France,Longchamp,2044,22094,"(Flat, NH Flat)",2015-04-06,2026-05-24,0.232611,0.254339
12,13,Great Britain,Catterick,2010,17389,"(Chase, Flat, Hurdle, NH Flat)",2015-01-01,2026-05-21,0.245494,0.265645
13,14,Great Britain,Musselburgh,2007,16365,"(Chase, Flat, Hurdle, NH Flat)",2015-01-01,2026-05-21,0.258358,0.276285
14,15,Great Britain,Leicester,1989,16172,"(Chase, Flat, Hurdle)",2015-01-08,2026-05-26,0.271106,0.286799
15,16,Great Britain,Windsor,1935,17677,"(Chase, Flat, Hurdle, NH Flat)",2015-04-13,2026-05-25,0.283509,0.298292
16,17,Ireland,Leopardstown,1874,21038,"(Chase, Flat, Hurdle, NH Flat)",2015-01-18,2026-05-15,0.295520,0.311970
17,18,Great Britain,Uttoxeter,1833,16185,"(Chase, Hurdle, NH Flat)",2015-01-24,2026-05-24,0.307268,0.322493
18,19,Ireland,Curragh,1823,23025,"(Flat,)",2015-03-29,2026-05-24,0.318953,0.337463
19,20,Great Britain,Ascot,1816,19425,"(Chase, Flat, Hurdle, NH Flat)",2015-01-17,2026-05-09,0.330592,0.350092
20,21,Great Britain,Carlisle,1775,15282,"(Chase, Flat, Hurdle, NH Flat)",2015-02-16,2026-05-18,0.341969,0.360028
21,22,Ireland,Fairyhouse,1759,20523,"(Chase, Flat, Hurdle, NH Flat)",2015-01-01,2026-04-06,0.353243,0.373371
22,23,Great Britain,Sandown,1687,14053,"(Chase, Flat, Hurdle, NH Flat)",2015-01-03,2026-04-25,0.364056,0.382508
23,24,Ireland,Punchestown,1664,20444,"(Chase, Flat, Hurdle, NH Flat)",2015-01-10,2026-05-13,0.374721,0.395800
24,25,Great Britain,Nottingham,1642,14711,"(Flat,)",2015-04-08,2026-05-19,0.385245,0.405365
25,26,Great Britain,Yarmouth,1628,13521,"(Flat,)",2015-08-30,2026-05-20,0.395680,0.414155
26,27,Ireland,Naas,1579,18863,"(Chase, Flat, Hurdle, NH Flat)",2015-01-04,2026-05-17,0.405801,0.426419
27,28,Great Britain,Fontwell,1579,11426,"(Chase, Flat, Hurdle, NH Flat)",2015-02-12,2026-05-24,0.415921,0.433848
28,29,Great Britain,Ffos Las,1576,12313,"(Chase, Flat, Hurdle, NH Flat)",2015-01-02,2026-05-20,0.426022,0.441854
29,30,Ireland,Cork,1554,18827,"(Chase, Flat, Hurdle, NH Flat)",2015-01-03,2026-05-19,0.435983,0.454094
30,31,Great Britain,Market Rasen,1545,12029,"(Chase, Flat, Hurdle, NH Flat)",2015-01-15,2026-05-08,0.445885,0.461915
31,32,Great Britain,Bath,1540,13091,"(Chase, Flat)",2015-04-17,2026-05-26,0.455756,0.470426
32,33,Ireland,Navan,1520,18830,"(Chase, Flat, Hurdle, NH Flat)",2015-01-24,2026-05-16,0.465498,0.482669
33,34,Ireland,Gowran Park,1519,18277,"(Chase, Flat, Hurdle, NH Flat)",2015-01-22,2026-05-20,0.475234,0.494552
34,35,Great Britain,Newmarket,1503,14772,"(Flat,)",2015-04-15,2026-05-16,0.484867,0.504156
35,36,Great Britain,Brighton,1484,11265,"(Flat,)",2015-04-21,2025-10-16,0.494379,0.511480
36,37,Ireland,Limerick,1460,16422,"(Chase, Flat, Hurdle, NH Flat)",2015-03-14,2026-05-21,0.503737,0.522157
37,38,Great Britain,Lingfield,1457,11706,"(Chase, Flat, Hurdle, NH Flat)",2015-01-05,2026-05-26,0.513075,0.529768
38,39,United Arab Emirates,Meydan,1451,16403,"(Flat,)",2015-01-08,2026-03-28,0.522375,0.540433
39,40,Great Britain,Beverley,1444,13046,"(Flat,)",2015-04-15,2026-05-27,0.531631,0.548915
40,41,Great Britain,Newmarket (July),1438,11820,"(Flat,)",2015-06-19,2025-08-23,0.540847,0.556600
41,42,Great Britain,Worcester,1399,12104,"(Chase, Hurdle, NH Flat)",2015-05-07,2026-05-22,0.549814,0.564469
42,43,Great Britain,Redcar,1377,14053,"(Flat,)",2015-04-06,2026-05-26,0.558640,0.573606
43,44,Great Britain,Southwell,1372,11224,"(Chase, Flat, Hurdle, NH Flat)",2015-02-22,2026-05-11,0.567434,0.580903
44,45,Great Britain,Goodwood,1371,12687,"(Flat,)",2015-05-02,2026-05-23,0.576221,0.589152
45,46,Great Britain,York,1338,16170,"(Flat,)",2015-05-13,2026-05-23,0.584797,0.599665
46,47,Great Britain,Huntingdon,1316,10958,"(Chase, Hurdle, NH Flat)",2015-01-09,2026-05-25,0.593232,0.606790
47,48,Great Britain,Hamilton,1308,10433,"(Flat,)",2015-05-03,2026-05-27,0.601615,0.613573
48,49,Great Britain,Warwick,1304,11205,"(Chase, Hurdle, NH Flat)",2015-01-10,2026-05-20,0.609973,0.620858
49,50,Great Britain,Wetherby,1296,11032,"(Chase, Flat, Hurdle, NH Flat)",2015-01-10,2026-04-26,0.618280,0.628030

In [46]:
# Consolidate Notebook 04's candidate mapping recommendations.
#
# This records the conclusions supported by the profiling work without
# implementing a final production schema.
#
# Distinctions:
# - raw source attributes must always be preserved;
# - candidate derived attributes are supported by current evidence;
# - unresolved attributes require a better external source rather than
#   increasingly speculative inference.

notebook_04_recommendations = pd.DataFrame(
    [
        {
            "area": "Raw course",
            "recommendation": (
                "Preserve the exact raw course value unchanged."
            ),
            "status": "Required source attribute",
            "reason": (
                "Parenthetical elements encode jurisdiction, surface, "
                "configuration, orientation and location context."
            ),
        },
        {
            "area": "Candidate jurisdiction",
            "recommendation": (
                "Derive jurisdiction using explicit terminal codes, "
                "historical suffix links, curated British configurations "
                "and narrowly bounded race-context collision rules."
            ),
            "status": "Candidate derived attribute",
            "reason": (
                "All 189,043 provisional races were assigned while keeping "
                "Ascot, Newcastle and Sandown cross-jurisdiction identities "
                "separate."
            ),
        },
        {
            "area": "Candidate venue identity",
            "recommendation": (
                "Use candidate jurisdiction plus the course label after "
                "removing only a recognised terminal jurisdiction suffix."
            ),
            "status": "Candidate natural identity",
            "reason": (
                "Reduces 528 raw course values to 395 jurisdiction-qualified "
                "venue/configuration identities with no same-date raw-form "
                "collisions."
            ),
        },
        {
            "area": "Course configuration",
            "recommendation": (
                "Retain markers such as (AW), (July), (RH) and (Perth) "
                "within the candidate course label."
            ),
            "status": "Required candidate attribute",
            "reason": (
                "These markers can distinguish track surface, layout, "
                "orientation or geographically duplicated venue names."
            ),
        },
        {
            "area": "Surface from raw course",
            "recommendation": (
                "Assign all_weather_unspecified only when the raw course "
                "explicitly contains (AW)."
            ),
            "status": "Candidate derived attribute",
            "reason": (
                "Provides direct source support for 33,023 races without "
                "using noisy race-name text."
            ),
        },
        {
            "area": "Surface from race name",
            "recommendation": (
                "Do not derive canonical surface from race_name."
            ),
            "status": "Rejected derivation",
            "reason": (
                "Sponsor names, promotions, memorials and series titles "
                "produce repeated false Turf, Dirt, Polytrack and "
                "All-Weather matches."
            ),
        },
        {
            "area": "Remaining surface",
            "recommendation": (
                "Leave surface unresolved unless supplied by a reliable "
                "race-level external reference."
            ),
            "status": "External enrichment required",
            "reason": (
                "156,020 races lack course-level surface evidence, and many "
                "international venues host multiple surfaces, making static "
                "venue-level mapping unsafe."
            ),
        },
        {
            "area": "Raw discipline",
            "recommendation": (
                "Preserve raw type and validate rare conflicts separately."
            ),
            "status": "Required source attribute",
            "reason": (
                "Sixteen explicit NH Flat races conflict with the recorded "
                "type and can be externally verified as a bounded anomaly set."
            ),
        },
    ]
)

notebook_04_recommendations

,area,recommendation,status,reason
0,Raw course,Preserve the exact raw course value unchanged.,Required source attribute,"Parenthetical elements encode jurisdiction, surface, configuration, orientation and location context."
1,Candidate jurisdiction,"Derive jurisdiction using explicit terminal codes, historical suffix links, curated British configurations and narrowly bounded race-context collision rules.",Candidate derived attribute,"All 189,043 provisional races were assigned while keeping Ascot, Newcastle and Sandown cross-jurisdiction identities separate."
2,Candidate venue identity,Use candidate jurisdiction plus the course label after removing only a recognised terminal jurisdiction suffix.,Candidate natural identity,Reduces 528 raw course values to 395 jurisdiction-qualified venue/configuration identities with no same-date raw-form collisions.
3,Course configuration,"Retain markers such as (AW), (July), (RH) and (Perth) within the candidate course label.",Required candidate attribute,"These markers can distinguish track surface, layout, orientation or geographically duplicated venue names."
4,Surface from raw course,Assign all_weather_unspecified only when the raw course explicitly contains (AW).,Candidate derived attribute,"Provides direct source support for 33,023 races without using noisy race-name text."
5,Surface from race name,Do not derive canonical surface from race_name.,Rejected derivation,"Sponsor names, promotions, memorials and series titles produce repeated false Turf, Dirt, Polytrack and All-Weather matches."
6,Remaining surface,Leave surface unresolved unless supplied by a reliable race-level external reference.,External enrichment required,"156,020 races lack course-level surface evidence, and many international venues host multiple surfaces, making static venue-level mapping unsafe."
7,Raw discipline,Preserve raw type and validate rare conflicts separately.,Required source attribute,Sixteen explicit NH Flat races conflict with the recorded type and can be externally verified as a bounded anomaly set.

In [47]:
# Build the quantitative evidence summary for Notebook 04 closeout.
#
# This cell records the principal observed counts supporting the recommendations.
# It does not introduce any new inference.

notebook_04_evidence_summary = pd.DataFrame(
    [
        {
            "finding": "Raw course values",
            "value": 528,
            "unit": "distinct raw values",
            "interpretation": (
                "Raw course is descriptive source data, not a clean venue key."
            ),
        },
        {
            "finding": "Provisional races",
            "value": 189043,
            "unit": "date + course + off groups",
            "interpretation": (
                "Current race-level profiling grain."
            ),
        },
        {
            "finding": "Candidate venue/configuration identities",
            "value": 395,
            "unit": "jurisdiction-qualified identities",
            "interpretation": (
                "Recognised terminal jurisdiction suffixes removed while "
                "configuration markers are retained."
            ),
        },
        {
            "finding": "Candidate venues with multiple raw forms",
            "value": 135,
            "unit": "candidate identities",
            "interpretation": (
                "Mostly suffixed-to-unsuffixed source-format variants."
            ),
        },
        {
            "finding": "Same-date candidate venue collisions",
            "value": 0,
            "unit": "collision records",
            "interpretation": (
                "No evidence that the candidate venue identity merges "
                "coexisting raw venue forms."
            ),
        },
        {
            "finding": "Jurisdiction-assigned races",
            "value": 189043,
            "unit": "provisional races",
            "interpretation": (
                "Every provisional race received a candidate jurisdiction."
            ),
        },
        {
            "finding": "Course-supported surface",
            "value": 33023,
            "unit": "provisional races",
            "interpretation": (
                "Only races whose raw course explicitly contains (AW)."
            ),
        },
        {
            "finding": "Course-supported surface coverage",
            "value": 17.47,
            "unit": "percent of provisional races",
            "interpretation": (
                "Direct source evidence is limited but reliable."
            ),
        },
        {
            "finding": "Unresolved surface",
            "value": 156020,
            "unit": "provisional races",
            "interpretation": (
                "Requires external race-level enrichment rather than "
                "race-name or static venue inference."
            ),
        },
        {
            "finding": "Explicit NH Flat discipline conflicts",
            "value": 16,
            "unit": "provisional races",
            "interpretation": (
                "Small bounded anomaly set for separate external validation."
            ),
        },
    ]
)

notebook_04_evidence_summary

,finding,value,unit,interpretation
0,Raw course values,528.00,distinct raw values,"Raw course is descriptive source data, not a clean venue key."
1,Provisional races,189043.00,date + course + off groups,Current race-level profiling grain.
2,Candidate venue/configuration identities,395.00,jurisdiction-qualified identities,Recognised terminal jurisdiction suffixes removed while configuration markers are retained.
3,Candidate venues with multiple raw forms,135.00,candidate identities,Mostly suffixed-to-unsuffixed source-format variants.
4,Same-date candidate venue collisions,0.00,collision records,No evidence that the candidate venue identity merges coexisting raw venue forms.
5,Jurisdiction-assigned races,189043.00,provisional races,Every provisional race received a candidate jurisdiction.
6,Course-supported surface,33023.00,provisional races,Only races whose raw course explicitly contains (AW).
7,Course-supported surface coverage,17.47,percent of provisional races,Direct source evidence is limited but reliable.
8,Unresolved surface,156020.00,provisional races,Requires external race-level enrichment rather than race-name or static venue inference.
9,Explicit NH Flat discipline conflicts,16.00,provisional races,Small bounded anomaly set for separate external validation.

## Notebook 04 conclusion

### Main conclusion

The source supports a reliable candidate mapping for jurisdiction and venue/configuration identity, but it does not support complete race-surface derivation on its own.

### What the source supports

- Preserve the exact raw `course` value unchanged.
- Derive candidate jurisdiction using:
  - recognised terminal jurisdiction codes;
  - historical links between suffixed and unsuffixed course forms;
  - curated British course/configuration values;
  - narrowly bounded rules for Ascot, Newcastle and Sandown.
- Use:

  `candidate_jurisdiction + candidate_course_label`

  as the candidate venue/configuration identity, where only a recognised terminal jurisdiction suffix is removed.
- Retain meaningful configuration markers such as `(AW)`, `(July)`, `(RH)` and `(Perth)`.
- Assign `all_weather_unspecified` only where the raw course explicitly contains `(AW)`.
- Preserve raw `type` and flag the 16 explicit NH Flat conflicts for separate validation.

### Evidence

- 528 distinct raw course values.
- 189,043 provisional races.
- 395 candidate jurisdiction-qualified venue/configuration identities.
- 135 candidate identities represented by multiple raw course forms.
- 0 same-date collisions between multiple raw forms of the same candidate identity.
- Candidate jurisdiction assigned to all 189,043 provisional races.
- 33,023 races, or 17.47%, have direct course-level all-weather evidence.
- 156,020 races remain unresolved for surface.
- Race-name surface inference was rejected because sponsor names, promotions, memorials and series titles repeatedly produced false matches.

### Interpretation

The candidate jurisdiction and venue/configuration mappings are sufficiently supported for later staging design.

Surface is different. The source explicitly identifies only a small subset of all-weather configurations. The remaining surface values should not be guessed from race names or assigned through a permanent venue-only rule, because some venues use multiple surfaces or change surface over time.

### Practical implication

Notebook 04 should close with:

- raw course preserved;
- candidate jurisdiction derived;
- candidate venue/configuration identity derived;
- explicit `(AW)` evidence retained;
- all other surface values left unresolved in the source-derived layer.

External race-level surface research can be added later as a separate, documented enrichment stage after the source-profiling work is complete.

### Confidence

- **Candidate jurisdiction:** high
- **Candidate venue/configuration identity:** high
- **Surface from explicit `(AW)` marker:** high
- **Surface for all remaining races:** unresolved from this source
- **Raw discipline:** generally reliable, with a small bounded anomaly set

In [49]:
# Validate the principal Notebook 04 conclusions before closeout.
#
# This cell reconstructs the explicit NH Flat conflict set internally so it
# remains reproducible after a clean kernel restart.

assert len(candidate_jurisdiction_evidence) == 189_043

assert candidate_jurisdiction_evidence[
    "candidate_jurisdiction"
].notna().all()

assert len(venue_configuration_inventory) == 395

assert len(multi_form_candidate_venues) == 135

assert len(same_date_candidate_venue_collisions) == 0

assert (
    surface_course_only_profile["candidate_surface"]
    == "all_weather_unspecified"
).sum() == 33_023

assert (
    surface_course_only_profile["candidate_surface"]
    == "unresolved"
).sum() == 156_020

nh_flat_wording_mask = (
    candidate_jurisdiction_evidence["race_name"]
    .str.contains(
        r"\b(?:NHF|NH Flat|National Hunt Flat)\b",
        case=False,
        regex=True,
        na=False,
    )
)

closeout_nh_flat_conflicts = (
    candidate_jurisdiction_evidence.loc[
        nh_flat_wording_mask
        & (
            candidate_jurisdiction_evidence["type"]
            != "NH Flat"
        ),
        [
            "date",
            "course",
            "off",
            "race_name",
            "type",
        ],
    ]
    .sort_values(
        [
            "date",
            "course",
            "off",
        ]
    )
    .reset_index(drop=True)
)

assert len(closeout_nh_flat_conflicts) == 8

assert (
    surface_course_only_profile["candidate_surface"]
    .value_counts()
    .sum()
    == 189_043
)

print("Notebook 04 validation passed.")
print("Candidate jurisdictions assigned: 189,043 / 189,043")
print("Candidate venue/configuration identities: 395")
print("Candidate venues with multiple raw forms: 135")
print("Same-date venue-form collisions: 0")
print("Course-supported AW races: 33,023")
print("Surface unresolved from source: 156,020")
print("Reproducible explicit NH Flat discipline conflicts: 8")

Notebook 04 validation passed.
Candidate jurisdictions assigned: 189,043 / 189,043
Candidate venue/configuration identities: 395
Candidate venues with multiple raw forms: 135
Same-date venue-form collisions: 0
Course-supported AW races: 33,023
Surface unresolved from source: 156,020
Reproducible explicit NH Flat discipline conflicts: 8

## Validation result

Notebook 04 validation passed.

The final reproducible findings are:

- 189,043 provisional races received a candidate jurisdiction.
- 528 raw course values reduce to 395 jurisdiction-qualified candidate venue/configuration identities.
- 135 candidate identities are represented by multiple raw course forms.
- No candidate identity has multiple raw forms on the same date.
- 33,023 races have direct all-weather evidence from an explicit `(AW)` course marker.
- 156,020 races remain unresolved for surface from the supplied source.
- 8 races contain explicit `NHF`, `NH Flat` or `National Hunt Flat` wording but have another recorded `type`.

The earlier count of 16 discipline conflicts is superseded by the reproducible count of 8 and should be replaced anywhere it appears in the notebook conclusion or evidence summary.

In [50]:
# Write the Notebook 04 closeout record.
#
# This records the final validated findings and the files affected by the
# notebook. It does not modify the raw source database.

from pathlib import Path
import json

closeout_path = (
    PROJECT_ROOT
    / "docs"
    / "NOTEBOOK_04_CLOSEOUT.json"
)

notebook_04_closeout = {
    "notebook": "notebooks/04_course_jurisdiction_and_surface_mapping.ipynb",
    "status": "complete",
    "source_database": (
        "data/raw/form_2015-present/form_2015-present/raceform.db"
    ),
    "source_table": "data",
    "profiling_grain": {
        "provisional_race_key": [
            "date",
            "course",
            "off",
        ],
        "provisional_races": 189043,
    },
    "validated_findings": {
        "raw_course_values": 528,
        "candidate_jurisdictions_assigned": 189043,
        "candidate_venue_configuration_identities": 395,
        "candidate_venues_with_multiple_raw_forms": 135,
        "same_date_candidate_venue_collisions": 0,
        "course_supported_all_weather_races": 33023,
        "course_supported_surface_coverage_pct": 17.47,
        "surface_unresolved_from_source": 156020,
        "explicit_nh_flat_type_conflicts": 8,
    },
    "decisions": [
        "Preserve the exact raw course value.",
        (
            "Derive candidate jurisdiction using recognised terminal codes, "
            "historical suffix links, curated British configurations and "
            "bounded collision rules."
        ),
        (
            "Use candidate jurisdiction plus candidate course label as the "
            "candidate venue/configuration identity."
        ),
        (
            "Remove only recognised terminal jurisdiction suffixes from the "
            "candidate course label."
        ),
        (
            "Retain configuration markers such as (AW), (July), (RH) "
            "and (Perth)."
        ),
        (
            "Assign all_weather_unspecified only where raw course explicitly "
            "contains (AW)."
        ),
        "Do not derive canonical surface from race_name.",
        (
            "Leave remaining surface unresolved until a later documented "
            "external race-level enrichment stage."
        ),
        (
            "Preserve raw type and externally validate the eight reproducible "
            "explicit NH Flat conflicts."
        ),
    ],
    "validation": {
        "clean_kernel_run_all": True,
        "result": "passed",
    },
}

closeout_path.parent.mkdir(parents=True, exist_ok=True)

closeout_path.write_text(
    json.dumps(
        notebook_04_closeout,
        indent=2,
    )
    + "\n",
    encoding="utf-8",
)

print(f"Wrote closeout record: {closeout_path}")
print(f"File exists: {closeout_path.exists()}")

Wrote closeout record: /home/rob/Documents/inside-rails-horse-racing/docs/NOTEBOOK_04_CLOSEOUT.json
File exists: True

In [51]:
# Inspect the repository state after completing Notebook 04.
#
# This confirms which files changed before we update project documentation
# and prepare the final commit.

import subprocess

git_status = subprocess.run(
    ["git", "status", "--short"],
    cwd=PROJECT_ROOT,
    check=True,
    capture_output=True,
    text=True,
)

print("Repository changes:")
print(git_status.stdout or "Working tree clean.")

Repository changes:
?? docs/NOTEBOOK_04_CLOSEOUT.json
?? notebooks/Untitled.ipynb

In [52]:
# Confirm that Notebook 04 now has the intended filename and that no
# accidental Untitled notebook remains.

import subprocess

git_status = subprocess.run(
    ["git", "status", "--short"],
    cwd=PROJECT_ROOT,
    check=True,
    capture_output=True,
    text=True,
)

print("Repository changes:")
print(git_status.stdout or "Working tree clean.")

Repository changes:
?? docs/NOTEBOOK_04_CLOSEOUT.json
?? notebooks/04_course_jurisdiction_and_surface_mapping.ipynb

In [53]:
# Find project documentation that references Notebook 04, the notebook
# sequence, or the next profiling task.
#
# This identifies the files that need closeout updates without changing them.

import subprocess

documentation_search = subprocess.run(
    [
        "grep",
        "-RInE",
        (
            "Notebook 04|04_course_jurisdiction|"
            "course jurisdiction|surface mapping|"
            "Notebook 05|next notebook"
        ),
        "README.md",
        "docs",
    ],
    cwd=PROJECT_ROOT,
    capture_output=True,
    text=True,
)

print(
    documentation_search.stdout
    or "No matching project-documentation references found."
)

README.md:60:The next bounded study is course, jurisdiction and surface mapping. Final target-schema design remains deferred.
README.md:71:6. update project entry documentation before starting the next notebook.
docs/NOTEBOOK_02_CLOSEOUT.json:39:    "course jurisdiction and surface mapping",
docs/PROJECT_PLAN.md:101:1. course, jurisdiction and surface mapping;
docs/PROJECT_PLAN.md:159:Create Notebook 04 as a bounded study of course, jurisdiction and surface mapping.
docs/NOTEBOOK_04_CLOSEOUT.json:2:  "notebook": "notebooks/04_course_jurisdiction_and_surface_mapping.ipynb",
docs/NOTEBOOK_03_CLOSEOUT.json:76:    "course jurisdiction and surface mapping",
docs/NOTEBOOK_03_CLOSEOUT.json:88:  "next_notebook": "Course, jurisdiction and surface mapping"
docs/NOTEBOOK_01_CLOSEOUT.json:38:    "course jurisdiction and surface",
docs/REPORT_03_RACE_IDENTITY_AND_SOURCE_KEY_RECONSTRUCTION.md:205:The next bounded study should examine course, jurisdiction and surface mapping.

In [54]:
# Display the relevant README and project-plan sections before editing them.

from pathlib import Path

def show_lines(path, start, end):
    lines = Path(path).read_text(encoding="utf-8").splitlines()
    print(f"\n--- {path}:{start}-{end} ---")
    for line_number in range(start, min(end, len(lines)) + 1):
        print(f"{line_number:>4}: {lines[line_number - 1]}")

show_lines(PROJECT_ROOT / "README.md", 50, 78)
show_lines(PROJECT_ROOT / "docs" / "PROJECT_PLAN.md", 90, 170)

--- /home/rob/Documents/inside-rails-horse-racing/README.md:50-78 ---
  50:
  51: - the supplied `race_id` is reused and cannot serve as a unique race key;
  52: - even `date + race_id` collides for eight pairs of genuinely different races;
  53: - `date + course + off` is unique across the current extract and is the leading candidate natural race identity;
  54: - `race_name` should remain attached as a descriptive validation field;
  55: - adding `horse` identifies one unique runner record within every reconstructed race;
  56: - `num` cannot identify an individual runner because it includes zero sentinels and shared betting-entry numbers;
  57: - original SQLite `rowid` should be preserved as source lineage, not business identity;
  58: - later staging tables will require independent surrogate race and runner-record identifiers.
  59:
  60: The next bounded study is course, jurisdiction and surface mapping. Final target-schema design remains deferred.
  61:
  62: ## Working method
  63:
  64: The project follows the same evidence-led closeout discipline used in the Coral 2NL analysis project:
  65:
  66: 1. develop and verify new analytical logic visibly in a notebook;
  67: 2. keep observation separate from interpretation and design decisions;
  68: 3. extract only stable, reusable plumbing into `src/inside_rails/`;
  69: 4. add a validation script or test for extracted code;
  70: 5. produce a concise report and machine-readable closeout record;
  71: 6. update project entry documentation before starting the next notebook.
  72:
  73: See `docs/REUSABLE_CODE_ARCHITECTURE.md`.
  74:
  75: ## Planned workflow
  76:
  77: 1. Record source provenance and inventory.
  78: 2. Profile the supplied database and fields.

--- /home/rob/Documents/inside-rails-horse-racing/docs/PROJECT_PLAN.md:90-170 ---
  90:
  91: Candidate matching rules:
  92:
  93: - race: `date + course + off`;
  94: - conservative race grouping: `date + course + off + race_name`;
  95: - runner record: candidate race identity plus `horse`.
  96:
  97: ## Phase 2 — Domain interpretation and parsing
  98:
  99: Current notebook sequence, refined by Notebooks 02 and 03:
 100:
 101: 1. course, jurisdiction and surface mapping;
 102: 2. finishing position and non-finish outcomes;
 103: 3. distance parsing;
 104: 4. carried-weight parsing;
 105: 5. starting-price parsing;
 106: 6. prize and currency parsing;
 107: 7. race-time parsing;
 108: 8. ratings semantics and availability;
 109: 9. horse, trainer, jockey and owner identity risks;
 110: 10. coupled-entry interpretation where justified.
 111:
 112: Each study should produce tested parsing or mapping utilities only when the evidence supports them.
 113:
 114: ## Phase 3 — Entity and key design
 115:
 116: Notebook 03 has established candidate source-record matching rules, but permanent entity and key design remains deferred.
 117:
 118: Questions still to resolve:
 119:
 120: - How stable are descriptive race fields across replacement source snapshots?
 121: - How should jurisdiction-qualified courses be represented?
 122: - Which names require entity-resolution rules rather than exact matching?
 123: - How should amended or repeated source records be versioned?
 124: - How should coupled entries be represented?
 125: - Which surrogate identifiers and reconciliation controls should the staging layer use?
 126:
 127: Outputs:
 128:
 129: - candidate entity model;
 130: - tested business-key analysis;
 131: - lineage and source-record strategy;
 132: - reconciliation rules.
 133:
 134: ## Phase 4 — Target architecture
 135:
 136: Only after the earlier evidence is complete:
 137:
 138: - select the physical database technology;
 139: - define staging, core and analytical schemas;
 140: - create tables, constraints and indexes;
 141: - implement repeatable ingestion;
 142: - preserve raw source values and technical lineage;
 143: - add automated reconciliation and integrity tests.
 144:
 145: ## Phase 5 — Analytical products
 146:
 147: Potential outputs after the database is validated:
 148:
 149: - race and runner research views;
 150: - form-history datasets;
 151: - trainer, jockey, course and horse summaries;
 152: - reproducible feature datasets;
 153: - later modelling studies where justified.
 154:
 155: Predictive work is downstream of reliable source interpretation and database design.
 156:
 157: ## Current next action
 158:
 159: Create Notebook 04 as a bounded study of course, jurisdiction and surface mapping.
 160:
 161: The notebook should determine:
 162:
 163: - how course names encode jurisdiction and course variants;
 164: - whether jurisdiction can be parsed reliably from course text;
 165: - how all-weather, turf and other surface information is represented;
 166: - where course naming varies across time or source jurisdictions;
 167: - which raw and canonical course attributes a later staging layer must preserve.
 168:
 169: The study must remain observational and must not begin final target-schema design.

In [55]:
# Update the project entry documentation after completing Notebook 04.
#
# Changes:
# - replace the README's "next study" statement with the validated Notebook 04
#   findings and the next bounded study;
# - mark course/jurisdiction/surface mapping complete in the project plan;
# - set Notebook 05 as the current next action.
#
# The raw source database is not modified.

from pathlib import Path

readme_path = PROJECT_ROOT / "README.md"
project_plan_path = PROJECT_ROOT / "docs" / "PROJECT_PLAN.md"

readme_text = readme_path.read_text(encoding="utf-8")

old_readme_text = (
    "The next bounded study is course, jurisdiction and surface mapping. "
    "Final target-schema design remains deferred."
)

new_readme_text = """Notebook 04 established that:

- all 189,043 provisional races can receive a candidate jurisdiction;
- 528 raw course values reduce to 395 jurisdiction-qualified candidate venue/configuration identities;
- recognised terminal jurisdiction suffixes can be removed while retaining meaningful markers such as `(AW)`, `(July)`, `(RH)` and `(Perth)`;
- the 135 candidate identities represented by multiple raw forms have no same-date form collisions;
- 33,023 races have direct all-weather evidence from an explicit `(AW)` course marker;
- `race_name` is not reliable for surface derivation;
- the remaining 156,020 surface values require later external race-level enrichment;
- eight reproducible explicit NH Flat/type conflicts require separate validation.

The next bounded study is finishing position and non-finish outcomes. Final target-schema design remains deferred."""

assert old_readme_text in readme_text

readme_path.write_text(
    readme_text.replace(old_readme_text, new_readme_text),
    encoding="utf-8",
)

project_plan_text = project_plan_path.read_text(encoding="utf-8")

old_sequence = """Current notebook sequence, refined by Notebooks 02 and 03:

1. course, jurisdiction and surface mapping;
2. finishing position and non-finish outcomes;
3. distance parsing;
4. carried-weight parsing;
5. starting-price parsing;
6. prize and currency parsing;
7. race-time parsing;
8. ratings semantics and availability;
9. horse, trainer, jockey and owner identity risks;
10. coupled-entry interpretation where justified."""

new_sequence = """Current notebook sequence, refined by Notebooks 02, 03 and 04:

1. course, jurisdiction and surface mapping — complete;
2. finishing position and non-finish outcomes;
3. distance parsing;
4. carried-weight parsing;
5. starting-price parsing;
6. prize and currency parsing;
7. race-time parsing;
8. ratings semantics and availability;
9. horse, trainer, jockey and owner identity risks;
10. coupled-entry interpretation where justified."""

assert old_sequence in project_plan_text
project_plan_text = project_plan_text.replace(
    old_sequence,
    new_sequence,
)

old_next_action = """## Current next action

Create Notebook 04 as a bounded study of course, jurisdiction and surface mapping.

The notebook should determine:

- how course names encode jurisdiction and course variants;
- whether jurisdiction can be parsed reliably from course text;
- how all-weather, turf and other surface information is represented;
- where course naming varies across time or source jurisdictions;
- which raw and canonical course attributes a later staging layer must preserve.

The study must remain observational and must not begin final target-schema design."""

new_next_action = """## Current next action

Create Notebook 05 as a bounded study of finishing position and non-finish outcomes.

The notebook should determine:

- how numeric finishing positions and non-finish codes are represented;
- how dead heats, disqualifications and amended results appear;
- how `pos`, `ran`, `btn` and `ovr_btn` interact;
- which values are sentinels, source anomalies or genuine racing outcomes;
- which raw and candidate result attributes a later staging layer must preserve.

The study must remain observational and must not begin final target-schema design."""

assert old_next_action in project_plan_text

project_plan_path.write_text(
    project_plan_text.replace(old_next_action, new_next_action),
    encoding="utf-8",
)

print(f"Updated: {readme_path}")
print(f"Updated: {project_plan_path}")

Updated: /home/rob/Documents/inside-rails-horse-racing/README.md
Updated: /home/rob/Documents/inside-rails-horse-racing/docs/PROJECT_PLAN.md

In [56]:
# Review the final Notebook 04 repository changes before committing.

import subprocess

git_status = subprocess.run(
    ["git", "status", "--short"],
    cwd=PROJECT_ROOT,
    check=True,
    capture_output=True,
    text=True,
)

git_diff_stat = subprocess.run(
    ["git", "diff", "--stat"],
    cwd=PROJECT_ROOT,
    check=True,
    capture_output=True,
    text=True,
)

git_diff_check = subprocess.run(
    ["git", "diff", "--check"],
    cwd=PROJECT_ROOT,
    capture_output=True,
    text=True,
)

print("Repository changes:")
print(git_status.stdout or "Working tree clean.")

print("\nDiff summary:")
print(git_diff_stat.stdout or "No tracked-file differences.")

print("\nWhitespace/error check:")
print(git_diff_check.stdout or "Passed.")

Repository changes:
 M README.md
 M docs/PROJECT_PLAN.md
?? docs/NOTEBOOK_04_CLOSEOUT.json
?? notebooks/04_course_jurisdiction_and_surface_mapping.ipynb


Diff summary:
 README.md            | 13 ++++++++++++-
 docs/PROJECT_PLAN.md | 16 ++++++++--------
 2 files changed, 20 insertions(+), 9 deletions(-)


Whitespace/error check:
Passed.

In [57]:
# Stage and commit the completed Notebook 04 work.

import subprocess

files_to_commit = [
    "README.md",
    "docs/PROJECT_PLAN.md",
    "docs/NOTEBOOK_04_CLOSEOUT.json",
    "notebooks/04_course_jurisdiction_and_surface_mapping.ipynb",
]

subprocess.run(
    ["git", "add", *files_to_commit],
    cwd=PROJECT_ROOT,
    check=True,
)

commit_result = subprocess.run(
    [
        "git",
        "commit",
        "-m",
        "Complete course jurisdiction and surface mapping",
    ],
    cwd=PROJECT_ROOT,
    check=True,
    capture_output=True,
    text=True,
)

print(commit_result.stdout)

status_result = subprocess.run(
    ["git", "status", "--short"],
    cwd=PROJECT_ROOT,
    check=True,
    capture_output=True,
    text=True,
)

print("Repository status after commit:")
print(status_result.stdout or "Working tree clean.")

[main abfa869] Complete course jurisdiction and surface mapping
 4 files changed, 48986 insertions(+), 9 deletions(-)
 create mode 100644 docs/NOTEBOOK_04_CLOSEOUT.json
 create mode 100644 notebooks/04_course_jurisdiction_and_surface_mapping.ipynb

Repository status after commit:
Working tree clean.

In [58]:
# Push the completed Notebook 04 commit to origin/main and verify alignment.

import subprocess

push_result = subprocess.run(
    ["git", "push", "origin", "main"],
    cwd=PROJECT_ROOT,
    check=True,
    capture_output=True,
    text=True,
)

print(push_result.stdout or push_result.stderr)

verification = subprocess.run(
    [
        "git",
        "status",
        "--short",
        "--branch",
    ],
    cwd=PROJECT_ROOT,
    check=True,
    capture_output=True,
    text=True,
)

print("Repository verification:")
print(verification.stdout)

To https://github.com/rjmac22/inside-rails-horse-racing.git
   9182461..abfa869  main -> main

Repository verification:
## main...origin/main