# Ayr

Racecourse evidence notebook supporting Study 03: **British racecourse and course identity**.

This notebook is self-contained: governed venue/course records and their provenance are written directly into the notebook.

## Scope

- Racecourse: **Ayr**
- Jurisdiction: **Great Britain**
- Study period: **2015-01-01 to 2026-05-27**
- Study 03 source label(s): `Ayr`
- Physical-model confidence: **high for Flat-vs-Jumps separation; straight sprint section retained below peer-course level**
- Key temporal boundary: no permanent course-identity boundary established during the study period.

## Racecourse identity

**Governed racecourse identity:** `Ayr`

Ayr is governed as one racecourse containing two peer physical racing-course identities: **Flat Course** and **Jumps Course**.

BHA evidence distinguishes the Flat track from the Hurdles/Jumps course by transferring Flat fixtures to the Hurdles Course when the Flat track was unavailable. Ayr Racecourse's own history also states that the jumps course was established in 1950.

Ayr Racecourse separately refers to the six-furlong **straight course**. For Study 03 it is retained as a named physical component/route of the Flat Course rather than promoted to a third peer course identity, because the available official material does not place it at the same hierarchy level as the Flat and Jumps courses.

In [1]:
import pandas as pd

In [2]:
source_label_mapping = pd.DataFrame(
    [['Great Britain', 'Ayr', 'Ayr']],
    columns=['jurisdiction', 'candidate_course_label', 'racecourse_identity'],
)
source_label_mapping

    jurisdiction candidate_course_label racecourse_identity
0  Great Britain                    Ayr                 Ayr

## Location metadata

Location remains a venue-level property.

In [3]:
location_metadata = pd.DataFrame(
    [['Ayr', 'Ayr Racecourse, Whitletts Road, Ayr, KA8 0JE', 'Ayr', 'South Ayrshire / Ayrshire', 'KA8 0JE', 55.46539, -4.60587, 13, 'Europe/London', 'secondary_geospatial_reference', 'single venue reference elevation; NOT course profile']],
    columns=['racecourse_identity', 'address', 'locality', 'county_or_region', 'postcode', 'latitude', 'longitude', 'elevation_m', 'iana_timezone', 'coordinate_status', 'elevation_status'],
)
location_metadata

,racecourse_identity,address,locality,county_or_region,postcode,latitude,longitude,elevation_m,iana_timezone,coordinate_status,elevation_status
0,Ayr,"Ayr Racecourse, Whitletts Road, Ayr, KA8 0JE",Ayr,South Ayrshire / Ayrshire,KA8 0JE,55.46539,-4.60587,13,Europe/London,secondary_geospatial_reference,single venue reference elevation; NOT course p...

In [4]:
location_provenance = pd.DataFrame(
    [
        ['Ayr', 'racecourse_identity', 'Ayr Racecourse', '2015-01-01', '2026-05-27', 'British Horseracing Authority', 'Heritage — British racecourses', 'https://www.britishhorseracing.com/heritage/', '2026-08-11', 'Stable venue identity.', 'verified_official'],
        ['Ayr', 'physical_venue_address', 'Ayr Racecourse, Whitletts Road, Ayr, KA8 0JE', '2015-01-01', '2026-05-27', 'British Horseracing Authority', 'Heritage — British racecourses', 'https://www.britishhorseracing.com/heritage/', '2026-08-11', 'Venue-level address.', 'derived_from_verified_location'],
        ['Ayr', 'venue_coordinates', '55.46539, -4.60587', '2015-01-01', '2026-05-27', 'Mapcarta / underlying OpenStreetMap-GeoNames-Wikidata', 'Racecourse map', 'https://mapcarta.com/26950440', '2026-08-11', 'Secondary venue reference coordinates; not surveyed course coordinates.', 'secondary_geospatial_reference'],
        ['Ayr', 'iana_timezone', 'Europe/London', '2015-01-01', '2026-05-27', 'IANA Time Zone Database', 'zone1970.tab', 'https://data.iana.org/time-zones/tzdb/zone1970.tab', '2026-08-11', 'Derived from verified GB venue location.', 'derived_from_verified_location'],
    ],
    columns=['racecourse_identity', 'field', 'value', 'valid_from', 'valid_to', 'source_authority', 'source_title', 'source_url', 'accessed_date', 'evidence_note', 'verification_status'],
)
location_provenance

,racecourse_identity,field,value,valid_from,valid_to,source_authority,source_title,source_url,accessed_date,evidence_note,verification_status
0,Ayr,racecourse_identity,Ayr Racecourse,2015-01-01,2026-05-27,British Horseracing Authority,Heritage — British racecourses,https://www.britishhorseracing.com/heritage/,2026-08-11,Stable venue identity.,verified_official
1,Ayr,physical_venue_address,"Ayr Racecourse, Whitletts Road, Ayr, KA8 0JE",2015-01-01,2026-05-27,British Horseracing Authority,Heritage — British racecourses,https://www.britishhorseracing.com/heritage/,2026-08-11,Venue-level address.,derived_from_verified_location
2,Ayr,venue_coordinates,"55.46539, -4.60587",2015-01-01,2026-05-27,Mapcarta / underlying OpenStreetMap-GeoNames-W...,Racecourse map,https://mapcarta.com/26950440,2026-08-11,Secondary venue reference coordinates; not sur...,secondary_geospatial_reference
3,Ayr,iana_timezone,Europe/London,2015-01-01,2026-05-27,IANA Time Zone Database,zone1970.tab,https://data.iana.org/time-zones/tzdb/zone1970...,2026-08-11,Derived from verified GB venue location.,derived_from_verified_location

## Recognised courses and tracks

Governed study-period inventory: **Flat Course; Jumps Course**.

The six-furlong Straight Course is recorded as a named component/route of the Flat Course, not as a third peer identity.

In [5]:
# Keep peer course identities separate from lower-level named routes.
course_inventory = pd.DataFrame(
    [
        ['Ayr', 'Flat Course', 'verified_official', 'course/track', '2015-01-01', '2026-05-27', 'turf', 'Flat', 'left-handed (round course)'],
        ['Ayr', 'Jumps Course', 'verified_official', 'course/track', '2015-01-01', '2026-05-27', 'turf', 'hurdle; chase; NH Flat', 'left-handed'],
    ],
    columns=['racecourse_identity', 'course_or_track_name', 'identity_status', 'entity_type', 'valid_from', 'valid_to', 'surface', 'primary_use', 'handedness'],
)
course_inventory

,racecourse_identity,course_or_track_name,identity_status,entity_type,valid_from,valid_to,surface,primary_use,handedness
0,Ayr,Flat Course,verified_official,course/track,2015-01-01,2026-05-27,turf,Flat,left-handed (round course)
1,Ayr,Jumps Course,verified_official,course/track,2015-01-01,2026-05-27,turf,hurdle; chase; NH Flat,left-handed

In [6]:
course_physical_characteristics = pd.DataFrame(
    [
        ['Ayr', 'Flat Course', 'left-handed round course with six-furlong straight sprint section', 'physically distinct from Jumps Course; Straight Course retained as component/route', 'about 12f round course', 'six-furlong straight course', None, None, 'Ayr Racecourse', 'History', 'https://www.ayr-racecourse.co.uk/about/history/', '2026-08-11', 'Official venue history explicitly calls it the Ayr straight course and separately records establishment of the jumps course.', 'verified_official'],
        ['Ayr', 'Jumps Course', 'left-handed National Hunt circuit', 'separate course from Flat track', None, None, None, None, 'Ayr Racecourse', 'History', 'https://www.ayr-racecourse.co.uk/about/history/', '2026-08-11', 'Official venue history states that the jumps course was established in 1950.', 'verified_official'],
    ],
    columns=['racecourse_identity', 'course_or_track_name', 'course_geometry', 'physical_relationship', 'circumference_or_length', 'straight_length_or_route', 'gradients_or_elevation_characteristics', 'permanent_obstacles_or_distinctive_features', 'source_authority', 'source_title', 'exact_source_url', 'accessed_date', 'evidence_note', 'verification_status'],
)
course_physical_characteristics

,racecourse_identity,course_or_track_name,course_geometry,physical_relationship,circumference_or_length,straight_length_or_route,gradients_or_elevation_characteristics,permanent_obstacles_or_distinctive_features,source_authority,source_title,exact_source_url,accessed_date,evidence_note,verification_status
0,Ayr,Flat Course,left-handed round course with six-furlong stra...,physically distinct from Jumps Course; Straigh...,about 12f round course,six-furlong straight course,None,None,Ayr Racecourse,History,https://www.ayr-racecourse.co.uk/about/history/,2026-08-11,Official venue history explicitly calls it the...,verified_official
1,Ayr,Jumps Course,left-handed National Hunt circuit,separate course from Flat track,NaN,NaN,None,None,Ayr Racecourse,History,https://www.ayr-racecourse.co.uk/about/history/,2026-08-11,Official venue history states that the jumps c...,verified_official

In [7]:
historical_changes = pd.DataFrame(
    [['Ayr', '1950', 'course establishment', 'Jumps Course', 'Flat racing venue', 'Separate jumps course established', 'Ayr Racecourse', 'History', 'https://www.ayr-racecourse.co.uk/about/history/', '2026-08-11', 'verified_official', 'Supports persistent Flat-vs-Jumps distinction during Study 03 period']],
    columns=['racecourse_identity', 'change_date_or_period', 'change_type', 'affected_course_or_track', 'before_state', 'after_state', 'source_authority', 'source_title', 'source_url', 'accessed_date', 'verification_status', 'model_impact'],
)
historical_changes

,racecourse_identity,change_date_or_period,change_type,affected_course_or_track,before_state,after_state,source_authority,source_title,source_url,accessed_date,verification_status,model_impact
0,Ayr,1950,course establishment,Jumps Course,Flat racing venue,Separate jumps course established,Ayr Racecourse,History,https://www.ayr-racecourse.co.uk/about/history/,2026-08-11,verified_official,Supports persistent Flat-vs-Jumps distinction ...

## Evidence and provenance

The straight-course terminology is preserved without promoting it above the hierarchy level supported by official evidence.

In [8]:
course_characteristic_provenance = pd.DataFrame(
    [
        ['AYR001', 'Great Britain', 'Ayr', 'Flat Course', 'course_or_track_name', 'Flat Course', '2015-01-01', '2026-05-27', 'British Horseracing Authority', 'Ayr fixture transfer / Flat track evidence', 'https://www.britishhorseracing.com/', '2026-08-11', 'BHA study-period material distinguishes the Flat track from the Hurdles Course.', 'verified_official'],
        ['AYR002', 'Great Britain', 'Ayr', 'Jumps Course', 'course_or_track_name', 'Jumps Course', '2015-01-01', '2026-05-27', 'Ayr Racecourse', 'History', 'https://www.ayr-racecourse.co.uk/about/history/', '2026-08-11', 'Official history states the jumps course was established in 1950.', 'verified_official'],
        ['AYR003', 'Great Britain', 'Ayr', 'Flat Course', 'named_component_route', 'Straight Course', '2015-01-01', '2026-05-27', 'Ayr Racecourse', 'History', 'https://www.ayr-racecourse.co.uk/about/history/', '2026-08-11', 'Official history explicitly uses the term Ayr straight course; Study 03 retains it below peer-course level.', 'verified_official'],
        ['AYR004', 'Great Britain', 'Ayr', 'Flat Course', 'straight_length_or_route', 'six furlongs', '2015-01-01', '2026-05-27', 'Ayr Racecourse', 'History', 'https://www.ayr-racecourse.co.uk/about/history/', '2026-08-11', 'Official history states the Ayr straight course is six furlongs.', 'verified_official'],
    ],
    columns=['assertion_id', 'jurisdiction', 'racecourse_identity', 'course_or_track_name', 'characteristic', 'value', 'valid_from', 'valid_to', 'source_authority', 'source_title', 'source_url', 'accessed_date', 'evidence_note', 'verification_status'],
)
course_characteristic_provenance

,assertion_id,jurisdiction,racecourse_identity,course_or_track_name,characteristic,value,valid_from,valid_to,source_authority,source_title,source_url,accessed_date,evidence_note,verification_status
0,AYR001,Great Britain,Ayr,Flat Course,course_or_track_name,Flat Course,2015-01-01,2026-05-27,British Horseracing Authority,Ayr fixture transfer / Flat track evidence,https://www.britishhorseracing.com/,2026-08-11,BHA study-period material distinguishes the Fl...,verified_official
1,AYR002,Great Britain,Ayr,Jumps Course,course_or_track_name,Jumps Course,2015-01-01,2026-05-27,Ayr Racecourse,History,https://www.ayr-racecourse.co.uk/about/history/,2026-08-11,Official history states the jumps course was e...,verified_official
2,AYR003,Great Britain,Ayr,Flat Course,named_component_route,Straight Course,2015-01-01,2026-05-27,Ayr Racecourse,History,https://www.ayr-racecourse.co.uk/about/history/,2026-08-11,Official history explicitly uses the term Ayr ...,verified_official
3,AYR004,Great Britain,Ayr,Flat Course,straight_length_or_route,six furlongs,2015-01-01,2026-05-27,Ayr Racecourse,History,https://www.ayr-racecourse.co.uk/about/history/,2026-08-11,Official history states the Ayr straight cours...,verified_official

In [9]:
# The straight course is real, but is retained as a lower-level route/component.
course_candidates_not_promoted = pd.DataFrame(
    [['Ayr', 'Straight Course', 'Ayr Racecourse official history', 'named physical route/component of Flat Course', 'Official evidence names the straight course but does not establish it as a peer identity alongside Flat Course and Jumps Course.', 'https://www.ayr-racecourse.co.uk/about/history/', '2026-08-11', 'retained_as_subcourse_component']],
    columns=['racecourse_identity', 'candidate_course_name', 'evidence', 'candidate_type', 'reason_not_promoted', 'source_url', 'accessed_date', 'verification_status'],
)
course_candidates_not_promoted

,racecourse_identity,candidate_course_name,evidence,candidate_type,reason_not_promoted,source_url,accessed_date,verification_status
0,Ayr,Straight Course,Ayr Racecourse official history,named physical route/component of Flat Course,Official evidence names the straight course bu...,https://www.ayr-racecourse.co.uk/about/history/,2026-08-11,retained_as_subcourse_component

In [10]:
human_review_items = pd.DataFrame(
    [],
    columns=['racecourse_identity', 'anomaly', 'conflicting_sources_or_terms', 'why_human_review', 'conservative_handling', 'priority'],
)
human_review_items

Empty DataFrame
Columns: [racecourse_identity, anomaly, conflicting_sources_or_terms, why_human_review, conservative_handling, priority]
Index: []

In [11]:
# No count-level unresolved question remains: the straight course is retained below the peer-course identity layer.
unresolved_questions = pd.DataFrame(
    [],
    columns=['racecourse_identity', 'question', 'why_unresolved', 'research_attempted', 'impact', 'unresolved_class', 'verification_status'],
)
unresolved_questions

Empty DataFrame
Columns: [racecourse_identity, question, why_unresolved, research_attempted, impact, unresolved_class, verification_status]
Index: []

## Conclusion

Ayr is governed as one racecourse containing **two peer course identities: Flat Course and Jumps Course**. The official six-furlong Straight Course terminology is preserved as a named physical component/route of the Flat Course rather than counted as a third peer course.

This resolves the former national-count uncertainty without pretending that the straight course does not physically exist.

In [12]:
assert len(source_label_mapping) == 1
assert len(location_metadata) == 1
assert set(course_inventory['course_or_track_name']) == {'Flat Course', 'Jumps Course'}
assert len(course_inventory) == 2
assert course_characteristic_provenance['source_url'].fillna('').str.len().gt(0).all()
assert len(unresolved_questions) == 0
print('Ayr venue, two-course hierarchy and provenance checks passed.')

Ayr venue, two-course hierarchy and provenance checks passed.