# Newmarket

Racecourse evidence notebook supporting Study 03: **British racecourse and course identity**.

This notebook is self-contained: governed venue/course records and their provenance are written directly into the notebook.

## Scope

- Racecourse grouping: **Newmarket**
- Jurisdiction: **Great Britain**
- Study period: **2015-01-01 to 2026-05-27**
- Study 03 source label(s): `Newmarket`, `Newmarket (July)`
- Physical-model confidence: **high at governed racecourse/course level**
- Key conclusion: The Jockey Club explicitly identifies two Newmarket racecourses — **The Rowley Mile** and **The July Course**.

## Racecourse identity

For Study 03, `Newmarket` is a parent analytical grouping over two officially named racecourses/courses:

- **Rowley Mile Course**
- **July Course**

The Jockey Club explicitly describes Newmarket as having two racecourses, the Rowley Mile and July Course. Named long-distance routes such as the Cesarewitch route are therefore retained below this peer identity layer rather than promoted as additional racecourses.

In [1]:
import pandas as pd

In [2]:
source_label_mapping = pd.DataFrame(
    [
        ['Great Britain', 'Newmarket', 'Newmarket'],
        ['Great Britain', 'Newmarket (July)', 'Newmarket'],
    ],
    columns=['jurisdiction', 'candidate_course_label', 'racecourse_identity'],
)
source_label_mapping

    jurisdiction candidate_course_label racecourse_identity
0  Great Britain              Newmarket           Newmarket
1  Great Britain       Newmarket (July)           Newmarket

## Location metadata

The `Newmarket` parent row is a study grouping. The two official racecourses have distinct visitor postcodes and should not be mistaken for one surveyed physical point.

In [3]:
location_metadata = pd.DataFrame(
    [['Newmarket', 'Newmarket Racecourses, Newmarket, Suffolk', 'Newmarket', 'Suffolk', None, 52.23673, 0.37299, 34, 'Europe/London', 'analytical_parent_reference', 'single reference elevation; NOT either course profile']],
    columns=['racecourse_identity', 'address', 'locality', 'county_or_region', 'postcode', 'latitude', 'longitude', 'elevation_m', 'iana_timezone', 'coordinate_status', 'elevation_status'],
)
location_metadata

,racecourse_identity,address,locality,county_or_region,postcode,latitude,longitude,elevation_m,iana_timezone,coordinate_status,elevation_status
0,Newmarket,"Newmarket Racecourses, Newmarket, Suffolk",Newmarket,Suffolk,None,52.23673,0.37299,34,Europe/London,analytical_parent_reference,single reference elevation; NOT either course ...

In [4]:
location_provenance = pd.DataFrame(
    [
        ['Newmarket', 'racecourse_identity', 'Newmarket Racecourses analytical grouping', '2015-01-01', '2026-05-27', 'The Jockey Club', 'About Newmarket Racecourses', 'https://www.thejockeyclub.co.uk/newmarket/about/', '2026-08-11', 'Official source states Newmarket has two racecourses: Rowley Mile and July Course.', 'derived_from_verified_structure'],
        ['Newmarket', 'rowley_mile_postcode', 'CB8 0TF', '2015-01-01', '2026-05-27', 'The Jockey Club', 'Arrival | Owners & Trainers', 'https://www.thejockeyclub.co.uk/newmarket/owners-and-trainers/arrival/', '2026-08-11', 'Official visitor postcode for Rowley Mile.', 'verified_official'],
        ['Newmarket', 'july_course_postcode', 'CB8 0XE', '2015-01-01', '2026-05-27', 'The Jockey Club', 'Arrival | Owners & Trainers', 'https://www.thejockeyclub.co.uk/newmarket/owners-and-trainers/arrival/', '2026-08-11', 'Official visitor postcode for July Course.', 'verified_official'],
        ['Newmarket', 'iana_timezone', 'Europe/London', '2015-01-01', '2026-05-27', 'IANA Time Zone Database', 'zone1970.tab', 'https://data.iana.org/time-zones/tzdb/zone1970.tab', '2026-08-11', 'Derived from verified GB location.', 'derived_from_verified_location'],
    ],
    columns=['racecourse_identity', 'field', 'value', 'valid_from', 'valid_to', 'source_authority', 'source_title', 'source_url', 'accessed_date', 'evidence_note', 'verification_status'],
)
location_provenance

,racecourse_identity,field,value,valid_from,valid_to,source_authority,source_title,source_url,accessed_date,evidence_note,verification_status
0,Newmarket,racecourse_identity,Newmarket Racecourses analytical grouping,2015-01-01,2026-05-27,The Jockey Club,About Newmarket Racecourses,https://www.thejockeyclub.co.uk/newmarket/about/,2026-08-11,Official source states Newmarket has two racec...,derived_from_verified_structure
1,Newmarket,rowley_mile_postcode,CB8 0TF,2015-01-01,2026-05-27,The Jockey Club,Arrival | Owners & Trainers,https://www.thejockeyclub.co.uk/newmarket/owne...,2026-08-11,Official visitor postcode for Rowley Mile.,verified_official
2,Newmarket,july_course_postcode,CB8 0XE,2015-01-01,2026-05-27,The Jockey Club,Arrival | Owners & Trainers,https://www.thejockeyclub.co.uk/newmarket/owne...,2026-08-11,Official visitor postcode for July Course.,verified_official
3,Newmarket,iana_timezone,Europe/London,2015-01-01,2026-05-27,IANA Time Zone Database,zone1970.tab,https://data.iana.org/time-zones/tzdb/zone1970...,2026-08-11,Derived from verified GB location.,derived_from_verified_location

## Recognised courses and tracks

Governed peer inventory: **Rowley Mile Course; July Course**.

The Jockey Club explicitly presents these as Newmarket's two racecourses.

In [5]:
course_inventory = pd.DataFrame(
    [
        ['Newmarket', 'Rowley Mile Course', 'verified_official', 'course/track', '2015-01-01', '2026-05-27', 'turf', 'Flat', 'predominantly straight; longer routes join the straight'],
        ['Newmarket', 'July Course', 'verified_official', 'course/track', '2015-01-01', '2026-05-27', 'turf', 'Flat', 'turning route into long straight'],
    ],
    columns=['racecourse_identity', 'course_or_track_name', 'identity_status', 'entity_type', 'valid_from', 'valid_to', 'surface', 'primary_use', 'handedness'],
)
course_inventory

,racecourse_identity,course_or_track_name,identity_status,entity_type,valid_from,valid_to,surface,primary_use,handedness
0,Newmarket,Rowley Mile Course,verified_official,course/track,2015-01-01,2026-05-27,turf,Flat,predominantly straight; longer routes join the...
1,Newmarket,July Course,verified_official,course/track,2015-01-01,2026-05-27,turf,Flat,turning route into long straight

In [6]:
course_physical_characteristics = pd.DataFrame(
    [
        ['Newmarket', 'Rowley Mile Course', 'one of the two official Newmarket racecourses', 'separate from July Course', None, 'Cesarewitch-distance racing is staged on the Rowley Mile', 'includes The Dip', None, 'The Jockey Club', 'About Newmarket Racecourses / Cesarewitch Trial Day', 'https://www.thejockeyclub.co.uk/newmarket/about/', '2026-08-11', 'Official hierarchy identifies Rowley Mile as one of two racecourses; official Cesarewitch Trial material places the staying race on the Rowley Mile.', 'verified_official'],
        ['Newmarket', 'July Course', 'one of the two official Newmarket racecourses', 'separate from Rowley Mile', None, None, None, None, 'The Jockey Club', 'About Newmarket Racecourses', 'https://www.thejockeyclub.co.uk/newmarket/about/', '2026-08-11', 'Official hierarchy identifies July Course as one of two racecourses.', 'verified_official'],
    ],
    columns=['racecourse_identity', 'course_or_track_name', 'course_geometry', 'physical_relationship', 'circumference_or_length', 'straight_length_or_route', 'gradients_or_elevation_characteristics', 'permanent_obstacles_or_distinctive_features', 'source_authority', 'source_title', 'exact_source_url', 'accessed_date', 'evidence_note', 'verification_status'],
)
course_physical_characteristics

,racecourse_identity,course_or_track_name,course_geometry,physical_relationship,circumference_or_length,straight_length_or_route,gradients_or_elevation_characteristics,permanent_obstacles_or_distinctive_features,source_authority,source_title,exact_source_url,accessed_date,evidence_note,verification_status
0,Newmarket,Rowley Mile Course,one of the two official Newmarket racecourses,separate from July Course,None,Cesarewitch-distance racing is staged on the R...,includes The Dip,None,The Jockey Club,About Newmarket Racecourses / Cesarewitch Tria...,https://www.thejockeyclub.co.uk/newmarket/about/,2026-08-11,Official hierarchy identifies Rowley Mile as o...,verified_official
1,Newmarket,July Course,one of the two official Newmarket racecourses,separate from Rowley Mile,None,NaN,NaN,None,The Jockey Club,About Newmarket Racecourses,https://www.thejockeyclub.co.uk/newmarket/about/,2026-08-11,Official hierarchy identifies July Course as o...,verified_official

In [7]:
historical_changes = pd.DataFrame(
    [],
    columns=['racecourse_identity', 'change_date_or_period', 'change_type', 'affected_course_or_track', 'before_state', 'after_state', 'source_authority', 'source_title', 'source_url', 'accessed_date', 'verification_status', 'model_impact'],
)
historical_changes

Empty DataFrame
Columns: [racecourse_identity, change_date_or_period, change_type, affected_course_or_track, before_state, after_state, source_authority, source_title, source_url, accessed_date, verification_status, model_impact]
Index: []

## Evidence and provenance

Official Jockey Club evidence fixes the governed peer hierarchy at Rowley Mile and July Course. Cesarewitch/Beacon terminology is not promoted into additional peer identities without equivalent official hierarchy evidence.

In [8]:
course_characteristic_provenance = pd.DataFrame(
    [
        ['NMK001', 'Great Britain', 'Newmarket', 'Rowley Mile Course', 'course_or_track_name', 'Rowley Mile Course', '2015-01-01', '2026-05-27', 'The Jockey Club', 'About Newmarket Racecourses', 'https://www.thejockeyclub.co.uk/newmarket/about/', '2026-08-11', 'Official source identifies Rowley Mile as one of the two Newmarket racecourses.', 'verified_official'],
        ['NMK002', 'Great Britain', 'Newmarket', 'July Course', 'course_or_track_name', 'July Course', '2015-01-01', '2026-05-27', 'The Jockey Club', 'About Newmarket Racecourses', 'https://www.thejockeyclub.co.uk/newmarket/about/', '2026-08-11', 'Official source identifies July Course as one of the two Newmarket racecourses.', 'verified_official'],
        ['NMK003', 'Great Britain', 'Newmarket', 'Rowley Mile Course', 'cesarewitch_route_relationship', 'Cesarewitch-distance racing occurs on Rowley Mile', '2015-01-01', '2026-05-27', 'The Jockey Club', 'Cesarewitch Trial Day', 'https://www.thejockeyclub.co.uk/newmarket/events-tickets/cesarewitch-trial-day/', '2026-08-11', 'Official event material states the Cesarewitch Trial is run over the Rowley Mile course.', 'verified_official'],
        ['NMK004', 'Great Britain', 'Newmarket', None, 'peer_course_count', 2, '2015-01-01', '2026-05-27', 'The Jockey Club', 'About Newmarket Racecourses', 'https://www.thejockeyclub.co.uk/newmarket/about/', '2026-08-11', 'Official source explicitly says Newmarket has two racecourses.', 'verified_official'],
    ],
    columns=['assertion_id', 'jurisdiction', 'racecourse_identity', 'course_or_track_name', 'characteristic', 'value', 'valid_from', 'valid_to', 'source_authority', 'source_title', 'source_url', 'accessed_date', 'evidence_note', 'verification_status'],
)
course_characteristic_provenance

,assertion_id,jurisdiction,racecourse_identity,course_or_track_name,characteristic,value,valid_from,valid_to,source_authority,source_title,source_url,accessed_date,evidence_note,verification_status
0,NMK001,Great Britain,Newmarket,Rowley Mile Course,course_or_track_name,Rowley Mile Course,2015-01-01,2026-05-27,The Jockey Club,About Newmarket Racecourses,https://www.thejockeyclub.co.uk/newmarket/about/,2026-08-11,Official source identifies Rowley Mile as one ...,verified_official
1,NMK002,Great Britain,Newmarket,July Course,course_or_track_name,July Course,2015-01-01,2026-05-27,The Jockey Club,About Newmarket Racecourses,https://www.thejockeyclub.co.uk/newmarket/about/,2026-08-11,Official source identifies July Course as one ...,verified_official
2,NMK003,Great Britain,Newmarket,Rowley Mile Course,cesarewitch_route_relationship,Cesarewitch-distance racing occurs on Rowley Mile,2015-01-01,2026-05-27,The Jockey Club,Cesarewitch Trial Day,https://www.thejockeyclub.co.uk/newmarket/even...,2026-08-11,Official event material states the Cesarewitch...,verified_official
3,NMK004,Great Britain,Newmarket,NaN,peer_course_count,2,2015-01-01,2026-05-27,The Jockey Club,About Newmarket Racecourses,https://www.thejockeyclub.co.uk/newmarket/about/,2026-08-11,Official source explicitly says Newmarket has ...,verified_official

In [9]:
course_candidates_not_promoted = pd.DataFrame(
    [
        ['Newmarket', 'Cesarewitch Course / route terminology', 'named long-distance route', 'below Rowley Mile peer identity', 'Official Jockey Club material places Cesarewitch racing on the Rowley Mile and identifies only Rowley Mile and July Course as the two racecourses.', 'https://www.thejockeyclub.co.uk/newmarket/events-tickets/cesarewitch-trial-day/', '2026-08-11', 'retained_as_subcourse_route'],
        ['Newmarket', 'Beacon Course terminology', 'historical/technical named route', 'below governed peer layer', 'No official evidence found promoting Beacon Course as a third Newmarket racecourse alongside Rowley Mile and July Course.', 'https://www.thejockeyclub.co.uk/newmarket/about/', '2026-08-11', 'not_promoted'],
    ],
    columns=['racecourse_identity', 'candidate_course_name', 'evidence', 'candidate_type', 'reason_not_promoted', 'source_url', 'accessed_date', 'verification_status'],
)
course_candidates_not_promoted

,racecourse_identity,candidate_course_name,evidence,candidate_type,reason_not_promoted,source_url,accessed_date,verification_status
0,Newmarket,Cesarewitch Course / route terminology,named long-distance route,below Rowley Mile peer identity,Official Jockey Club material places Cesarewit...,https://www.thejockeyclub.co.uk/newmarket/even...,2026-08-11,retained_as_subcourse_route
1,Newmarket,Beacon Course terminology,historical/technical named route,below governed peer layer,No official evidence found promoting Beacon Co...,https://www.thejockeyclub.co.uk/newmarket/about/,2026-08-11,not_promoted

In [10]:
human_review_items = pd.DataFrame(
    [],
    columns=['racecourse_identity', 'anomaly', 'conflicting_sources_or_terms', 'why_human_review', 'conservative_handling', 'priority'],
)
human_review_items

Empty DataFrame
Columns: [racecourse_identity, anomaly, conflicting_sources_or_terms, why_human_review, conservative_handling, priority]
Index: []

In [11]:
# The peer hierarchy is resolved by explicit official evidence.
unresolved_questions = pd.DataFrame(
    [],
    columns=['racecourse_identity', 'question', 'why_unresolved', 'research_attempted', 'impact', 'unresolved_class', 'verification_status'],
)
unresolved_questions

Empty DataFrame
Columns: [racecourse_identity, question, why_unresolved, research_attempted, impact, unresolved_class, verification_status]
Index: []

## Conclusion

Newmarket's governed peer inventory remains **two identities: Rowley Mile Course and July Course**. The former Beacon/Cesarewitch taxonomy question no longer threatens the national count: official Jockey Club evidence explicitly defines the two racecourses, and official Cesarewitch material places the staying route on the Rowley Mile.

Named sub-routes may still be useful in later route-level modelling, but they are not additional peer racecourse/course identities for Study 03.

In [12]:
assert len(source_label_mapping) == 2
assert set(course_inventory['course_or_track_name']) == {'Rowley Mile Course', 'July Course'}
assert len(course_inventory) == 2
assert course_characteristic_provenance['source_url'].fillna('').str.len().gt(0).all()
assert len(unresolved_questions) == 0
print('Newmarket two-racecourse hierarchy and provenance checks passed.')

Newmarket two-racecourse hierarchy and provenance checks passed.